### ISSUE TITLE
Request the algorithm references

### ISSUE THREAD

**Issue by despild** [cnr-isti-vclab/meshlab#1]
Dear meshlab Dev team.
Thank you for aswsome project and results. For understanding the projects, I want to know the algorithms name or references of the filters, such as close hole, Re-Orient all faces coherentely. 
I searched about them, but I don't know which one is correct one. If you can let me know, I'll be really happy.
Thank you.

**Comment by sjparker** [comment]
Tried compiling against vcglib on github (v1.0.0) and get the following error regarding missing methods ... 
`
ml_shared_data_context.cpp: In member function ‘void MLSceneGLSharedDataContext::setRenderingDataPerAllMeshViews(int, const MLRenderingData&)’:
ml_shared_data_context.cpp:81:8: error: ‘MLSceneGLSharedDataContext::PerMeshMultiViewManager’ has no member named ‘setPerAllViewsInfo’
   man->setPerAllViewsInfo(perviewdata);
        ^
ml_shared_data_context.cpp: In member function ‘void MLSceneGLSharedDataContext::drawAllocatedAttributesSubset(int, QGLContext*, const MLRenderingData&)’:
ml_shared_data_context.cpp:241:8: error: ‘MLSceneGLSharedDataContext::PerMeshMultiViewManager’ has no member named ‘drawAllocatedAttributesSubset’
   man->drawAllocatedAttributesSubset(viewid,dt);
        ^
`

**Comment by cignoni** [comment]
@despild : we usually add references for the algorithms that are more on the state of the art. For the other ones we have been to lazy up to now. It is a reasonable request but probably will be done very slowly when for some reason we have to touch the code of each filter...

@sjparker : you have to use the devel branch of the vcglib (as written in the readme.md in the src folder. I will add this note also in the tl;dr . btw please do not attach other issues to existing ones but open a new issue.
