### ISSUE TITLE
meshlabserver on MacOS Sierra Screened Poisson Surface Reconstruction filter

### ISSUE THREAD

**Issue by omhafez** [cnr-isti-vclab/meshlab#100]
I am on 64-bit MacOS Sierra. I installed the dmg and made the following calls:
export PATH=/Applications/meshlab.app/Contents/MacOS:$PATH
cd /Applications/meshlab.app/Contents/MacOS/ && install_name_tool -add_rpath "@executable_path/../Frameworks" meshlabserver && cd -
(the second line per the recommendation of this issue: https://github.com/cnr-isti-vclab/meshlab/issues/64)

The GUI works fine but meshlabserver is not working correctly.

-----------------------------------------------------------------------------------------------

**I make the following call:**
meshlabserver -i ptcloud.ply -o surf.ply -s screen.mlx

where screen.mlx was generated from the Meshlab GUI and looks like the following:
<!DOCTYPE FilterScript>
<FilterScript>
 <xmlfilter name="Screened Poisson Surface Reconstruction">
  <xmlparam name="cgDepth" value="0"/>
  <xmlparam name="confidence" value="false"/>
  <xmlparam name="depth" value="8"/>
  <xmlparam name="fullDepth" value="5"/>
  <xmlparam name="iters" value="8"/>
  <xmlparam name="pointWeight" value="4"/>
  <xmlparam name="preClean" value="false"/>
  <xmlparam name="samplesPerNode" value="1.5"/>
  <xmlparam name="scale" value="1.1"/>
  <xmlparam name="visibleLayer" value="false"/>
 </xmlfilter>
</FilterScript>

-----------------------------------------------------------------------------------------------

**I get the following output:**
Loading Plugins:
The base dir is /Applications/meshlab.app/Contents
The base dir is /Applications/meshlab.app/Contents
The base dir is /Applications/meshlab.app/Contents
Current Plugins Dir is: /Applications/meshlab.app/Contents/plugins 
Total 241 filtering actions
Total 12 io plugins
Opening a file with extention ply
Mesh /Users/omhafez/projects/shabaka/reslt/sphere/ptcloud.ply loaded has 61944 vn 0 fn
output mesh  /Users/omhafez/projects/shabaka/reslt/sphere/surf.ply
Apply FilterScript: '/Users/omhafez/projects/shabaka/reslt/sphere/screen.mlx'
FilterScript
Reading filter with name Screened Poisson Surface Reconstruction
Starting Script of 1 actionsfilter: Screened Poisson Surface Reconstruction
**no additional memory available!!! memory required: 1486656**
bbox 18.553152 18.553152 18.553152 - 81.056221 81.056221 81.056221 
Running Screened Poisson Reconstruction (Version 9.0)

Using 4 threads

Input Points / Samples: 61944 / 57192

 /#  Read input into tree:       0.0 (s),      92.3 (MB) /      92.3 (MB)

 /#    Got kernel density:       0.0 (s),      96.7 (MB) /      96.7 (MB)

/#     Got normal field:       0.1 (s),     106.8 (MB) /     106.8 (MB)

/#       Finalized tree:       0.1 (s),     115.7 (MB) /     115.7 (MB)

/#  Set FEM constraints:       0.7 (s),     120.5 (MB) /     120.5 (MB)

/#Set point constraints:       0.1 (s),     120.9 (MB) /     120.9 (MB)

Leaf Nodes / Active Nodes / Ghost Nodes: 643392 / 417480 / 317825

Memory Usage: 120.855 MB

Depth[0/8]:	Evaluated / Got / Solved in:  0.000 /  0.000 /  0.001	(120.926 MB)	Nodes: 1
Depth[1/8]:	Evaluated / Got / Solved in:  0.000 /  0.000 /  0.028	(120.953 MB)	Nodes: 8
Depth[2/8]:	Evaluated / Got / Solved in:  0.000 /  0.001 /  0.001	(120.953 MB)	Nodes: 64
Depth[3/8]:	Evaluated / Got / Solved in:  0.000 /  0.005 /  0.004	(121.133 MB)	Nodes: 512
Depth[4/8]:	Evaluated / Got / Solved in:  0.000 /  0.027 /  0.017	(123.930 MB)	Nodes: 4096
Depth[5/8]:	Evaluated / Got / Solved in:  0.001 /  0.121 /  0.052	(136.492 MB)	Nodes: 32768
Depth[6/8]:	Evaluated / Got / Solved in:  0.002 /  0.222 /  0.184	(149.102 MB)	Nodes: 109568
Depth[7/8]:	Evaluated / Got / Solved in:  0.006 /  0.332 /  0.226	(149.102 MB)	Nodes: 238208
Depth[8/8]:	Evaluated / Got / Solved in:  0.000 /  0.023 /  0.238	(149.102 MB)	Nodes: 2816
/# Linear system solved:       1.6 (s),     149.1 (MB) /     149.1 (MB)

Got average:       0.1 (s),     131.8 (MB) /     149.1 (MB) /       0.0 (MB)

Iso-Value: 4.991802e-01

Vertices / Polygons: 65404 / 130804

/#        Got triangles:       1.1 (s),     145.4 (MB) /     149.1 (MB)

/#          Total Solve:       4.0 (s),     149.1 (MB)

**Creating MeshDoneMesh /Users/omhafez/projects/shabaka/reslt/sphere/ptcloud.ply saved as /Users/omhafez/projects/shabaka/reslt/sphere/surf.ply (61944 vn 0 fn)**

-----------------------------------------------------------------------------------------------

The output has no faces! Even though it works successfully in the GUI.

Any suggestions?

Thanks,
Omar

**Comment by raymondsalmi** [comment]
I am having the same problem on Windows 7 64 bits with MeshLab 2016.12.

I found a solution by adding the following filter at the end of my script:

`<filter name="Delete Current Mesh"/>`

It seems that meshlabserver does not output the new mesh generated by the Screened Poisson Surface Reconstruction filter, but instead the input "mesh" (point cloud).

**Comment by omhafez** [comment]
This worked on MacOS Sierra 10.12.3 as well, thank you so much Raymond!

**Comment by mcallieri** [comment]
MeshLabServer keeps layers in the same way MeshLab does, and saves layers following their order. So, as there are two layers (the original one and the poisson), you have to export 2 meshes. If you add two exporting parameters -o layer1.ply -o layer2.ply the first one will contain the original mesh, and the second the merged one. Unfortunately, it is not possible, at the moment, to save just the CURRENT LAYER.

 Another option is to make a script like this:
1.do the poisson
2.select layer 0
3.delete current layer
 In this way, the only remaining layer will be the convex hull (layer 1), and it will be possible to save only that one.
step #2 is optional, at the moment, as the CURRENT LAYER is the original one, but inthe next release, the newly created layer will be the current one, so you have to set the first one as current.

 The filter to change the current layer is filter->mesh layer->"change the current layer", that in script will be

```
<filter name="Change the current layer">
  <Param tooltip="The name of the current mesh" type="RichMesh" value="0" name="mesh" description="Mesh"/>
 </filter>
```

layer numbers start at 0.
 then, to delete the current mesh, use filter->mesh layer->"delete current mesh".

`<filter name="Delete Current Mesh"/>`


If you add those filters after the poisson, and than save the only remaining layer, you should have what you need.
