### ISSUE TITLE
Texture Defrag filter crashes Meshlab 2021.05 - Win10

### ISSUE THREAD

**Issue by Ben-Mack** [cnr-isti-vclab/meshlab#1004]
Thanks for the newly Texture Defragmentation filter! When it works, it worked wonderfully. 
But I'm having constant crashing on a lot of models. Right after clicking apply, Meshlab will be exited without notice.

I've attached 2 reproducable .obj files (more can be provided if needed). Both case have pretty low tris count (~40k):
[txDefrag-crash-models.zip](https://github.com/cnr-isti-vclab/meshlab/files/6583255/txDefrag-crash-models.zip)

**Comment by alemuntoni** [comment]
Hi, the archive you shared cannot be unzipped (it could be damaged...).

In any case, it could be the fact that the filter requires edge and vertex manifoldness, and in 2021.05 this check was missing.
I added it in the last commit, could you please try the last nightly build and let me know (it will be ready in a few minutes)?
[Here](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-intall-the-last-nightly) you can find instructions to download the last nightly.

**Comment by Ben-Mack** [comment]
Thanks for the quick update! I've just tested and both of my case still crash in the latest nightly.

I've re-archived these files using 7z:
[txDefrag-crash-test-case.zip](https://github.com/cnr-isti-vclab/meshlab/files/6589746/txDefrag-crash-test-case.zip)

**Comment by alemuntoni** [comment]
Thanks, we'll look into this!

**Comment by alemuntoni** [comment]
This issue has been fixed in #1012.
You can try the fixed version by [downloading the last nightly](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version).

**Comment by Ben-Mack** [comment]
The reported problem is fixed. Thanks a lot!!
