### ISSUE TITLE
Crash after duplicating layer

### ISSUE THREAD

**Issue by Bzucko** [cnr-isti-vclab/meshlab#1008]
1. import mesh
2. duplicate layer...meshlab crash.
Tested on Windows 10 LTSC, meshlab_64bit_fp v2021.05 / 64bit_fp/dp_2021.06_nightly_66ba59.
No crash on 2020.12
[TorusKnot.zip](https://github.com/cnr-isti-vclab/meshlab/files/6590029/TorusKnot.zip)

**Comment by alemuntoni** [comment]
Thanks for reporting, fixed in the last commit.
You can try it by downloading the last nightly (it will be ready soon).
[Here](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-intall-the-last-nightly) there are the instructions to download it.
