### ISSUE TITLE
Two bugs

### ISSUE THREAD

**Issue by xueyuhanlang** [cnr-isti-vclab/meshlab#1009]
Hi forks, 

Here are two bugs I encountered in windows platform.

1.  Program crash
     Platform: Windows 10
     MeshLab version:  all the 2020.x & 2021.x
     Issue: When closing multiple project windows one by one,  the MeshLab program stops responding and crashes.
     Issue reproduction:
     (1) Open MeshLab, create several empty projects (>=1 projects)
     (2) close these project windows one by one.
     (3) Then create a new empty project,  the closing of this project window will trigger the crash.
     
       I guess that this issue is related to QtOpenGL module,  but I have not taken a close look.
  

2.   Line ending of project file (*.mlp)
     Platform: windows 10
     MeshLab version:  2021.5
     Issue:   I generated mlp files by my program,  MeshLab 2021.5 can only recognize files with LF line ending correctly, and CR/LF line ending will cause weird results.   The old versions of MeshLab have no such issues.

Thanks!

**Comment by alemuntoni** [comment]
Hi, thanks for reporting.
Bug 1 is a known bug (see #780). Debugging does not help finding the root cause of the crash, therefore it is almost impossible for me to solve it.
Does Bug 2 happen only with mlp projects saved with old versions of meshlab? It could be related with the fix made in #913.
