### ISSUE TITLE
I'm wander why boolean use igl instead?

### ISSUE THREAD

**Issue by kingui1106** [cnr-isti-vclab/meshlab#1010]
I'm wander why boolean use igl instead? Is any improve?

**Comment by cignoni** [comment]
yes.

**Comment by kingui1106** [comment]
How can i build it. I meet some problem on cmake.
- meshlabplugins/filter_mesh_booleans
Skipping filter_mesh_booleans - don't know about boost, cgal or libigl on this system.

How can i solve it.

**Comment by alemuntoni** [comment]
What platform are you using? It depends on the platform.
Generally speaking, the filter requires cgal and boost, which are not bundled inside the meshlab repository and need to be found in the system by cmake.
You can check the [github workflows](https://github.com/cnr-isti-vclab/meshlab/tree/master/.github/workflows) to see how meshlab is automatically built on each operative system.

**Comment by kingui1106** [comment]
Thanks~!
