### ISSUE TITLE
OBJ mesh does not export texture atlas

### ISSUE THREAD

**Issue by VisionaryMind** [cnr-isti-vclab/meshlab#1015]
We have ~100 images from different positions imported into Meshlab as rasters along with poses. The following procedure is used to project the images onto our mesh:

1. Repair non-manifold edges by removing faces
2. Parameterization: Trivial per triangle
3. Project active rasters color to current mesh, filling the texture

For this last step, we set a pixel size of 8192, specify the texture file, and leave all other settings at default. After roughly 30-40 minutes, all textures are projected successfully onto the mesh, but there is no way to save the final product. When attempting to export the mesh (with normals and texture coordinates), the texture file is not saved. Meshlab will stay at 99-100% and do nothing for an hour or more (we have not waited longer). 

Is there any way to work around this bug? This is a very useful feature and the inability to export texture atlases with projections is, from my point of view, a significant problem. At the very least, it would be useful if the texture atlas could be saved separately since the mesh is exported without a problem.

**Comment by alemuntoni** [comment]
This issue should be already solved. Could you please try the last nightly? [here](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version) there are the instructions on how to download it.

**Comment by VisionaryMind** [comment]
I have been trying every nightly build since this issue was posted in June, and the problem has still not been resolved. I will open a duplicate ticket.

**Comment by ttsesm** [comment]
@VisionaryMind did you have any luck with this? I guess it is also related with this issue https://github.com/cnr-isti-vclab/PyMeshLab/issues/179

Btw, is there any tutorial that I can follow for the procedure that you describe and how to load poses and images and project them into my mesh?

**Comment by alemuntoni** [comment]
I don't think they are related. 
https://github.com/cnr-isti-vclab/PyMeshLab/issues/179 is a bug on a filter that goes in an endless loop.
This issue was about exporting textures trough the obj exporter, which should be solved in recent versions of meshlab.
If there are still some issues about it, please report it with a reproducible example.
