### ISSUE TITLE
The qt configuration file is parsed incorrectly in the qt plugin of vs2019

### ISSUE THREAD

**Issue by weiyu666** [cnr-isti-vclab/meshlab#1020]
OS: windows10;
version: new ! 2021.5 

Use the plugin of vs2019 to open meshlab_mini.pro or the vs2019 project generated by meshlab.pro cannot be compiled, and the vcglib library cannot be found! Manual inculdeing in has no effect, at least the version that has been used in the previous month of 2020.9 is ok and no problem, but the latest one is not! Of course, after downloading meshlab, I found that vcglib was missing. I went to github to download and put it in.
![image](https://user-images.githubusercontent.com/22174508/123144775-a1cddd80-d48e-11eb-83f8-936f3a4032f4.png)
![image](https://user-images.githubusercontent.com/22174508/123144815-af836300-d48e-11eb-8d89-c8d0bf8ae008.png)

**Comment by alemuntoni** [comment]
As clearly stated in the [build instructions readme](https://github.com/cnr-isti-vclab/meshlab/blob/master/src/README.md), you need to clone the meshlab repository using the command 
```
git clone --recursive https://github.com/cnr-isti-vclab/meshlab
```

Moreover, the qmake configuration is no longer supported on windows and will be dismissed soon on all the platform. 
The fully supported build tool is `cmake`.
