### ISSUE TITLE
nxz export issue

### ISSUE THREAD

**Issue by virgilejarrige** [cnr-isti-vclab/meshlab#1022]
Hello,

I tried on Windows 10 and macOS 11.4 with the nightly version that came out earlier today (thanks again!), and I have the same error message when attempting to export a .ply or .obj to nxz:

"No parameter with name textures_bits found in RichParameterList"

I tried to untick the texture option, same error message.

It seems to work for nxs export.

Take care,

Virgile

**Comment by alemuntoni** [comment]
Hi, I already solved this, precisely on [this commit](https://github.com/cnr-isti-vclab/meshlab/commit/70bb79d4a9ac7b67bbf8fb66ad5c4d6fb2dfc6ec#diff-dace07973ce3e9aa6bade942bf89462e9e0ff8501c230e40c664936efdb7ea9cR279). If you download the very last build, it should work!

Note: right now textures are not exported into nxs and nxz, but I'm already working on making it possible.

**Comment by alemuntoni** [comment]
fixed in the last commit, now nxs and nxz export also textures
