### ISSUE TITLE
Linux AppImage execution fails, libOpenGL.so.0 cannot open, no such file

### ISSUE THREAD

**Issue by FlatCapElectronics** [cnr-isti-vclab/meshlab#1023]
Fresh installation, never used the program before.
Execution in terminal proceeds as follows:
> me@large:~/appimage$ ./MeshLab2021.05-linux.AppImage 
> /tmp/.mount_MeshLaCOCZA4/usr/bin/meshlab: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory

My junk:
Kernel: 5.11.0-22-generic x86_64 
Desktop: Xfce 4.14.2 
tk: Gtk 3.24.13 
wm: xfwm4  dm: LightDM 
Distro: Linux Mint 20.1 Ulyssa
base: Ubuntu 20.04 focal

I have PrusaSlicer and DigiKam running as appimages without issue. I haven't really a clue about this stuff but I tried to do some basic due diligence and it seems appimages are intended to be entirely self contained, so I don't think there's anything I could be doing wrong on this end, though I can't say I'd be surprised. :)

**Comment by alemuntoni** [comment]
It is a known issue and it does not depend on meshlab (https://github.com/probonopd/linuxdeployqt/issues/486 for further details). 
You can run the appimage by installing the `libopengl0` library.
On debian based distros:
```
sudo apt install libopengl0
```

**Comment by FlatCapElectronics** [comment]
Thank you very much.
Just to verify, using :
```
sudo apt install libopengl0
```
. . . allowed application start without issue, no warnings in console.

**Comment by alemuntoni** [comment]
Update: starting from 589cf4d27c03e1ab71d6a7e9fdd477f6b061cfa3, `libopengl0` is not required anymore.
Therefore, in the next MeshLab version, the AppImage will be totally self-contained.
