### ISSUE TITLE
windows 10 64: Version (2020.12 & 2021.05) problem with filter Iso Parametrization: Main

### ISSUE THREAD

**Issue by amsolton** [cnr-isti-vclab/meshlab#1024]
After reconstructing the surface of an object, the filter  Iso Parametrization: Main has two diffrent probems.
in Version 2021.05 the program crashes while applying this filter.
in Version 2020.12 the filter works partialy. The filter itself works fine but when I want to use "save AM" and load it afterwards for the same surface the error " Failure of filter: "Iso Parametraization: Main" Abstract domain doesn't fit well with the parametrized mesh " This error accours regardless of the path/ name I put in for the param load AM. This error also accours wehn I put an in non existing path. Same problem with pymeshlab version 0.2 and 0.2.1 here 0.2.1 crashes and with 0.2 load_AM does not work.
I hope this report is helpful enough.

![Screenshot (12)](https://user-images.githubusercontent.com/86597014/123612451-d7622600-d802-11eb-8b0f-bbbaa206cad5.png)

**Comment by alemuntoni** [comment]
Thanks for reporting, I'll look into this ASAP.

**Comment by alemuntoni** [comment]
Hi, I fixed the issue about the crash, now the abstract mesh is correctly generated.

About the options of loading/saving the abstract mesh, these options apparently never worked (they did not on 2016.12)..
I temporarily removed them, because they require a major revision of a very old codebase.
