### ISSUE TITLE
There is no way to install on Linux Mint 17.3

### ISSUE THREAD

**Issue by allstar87** [cnr-isti-vclab/meshlab#103]
There's no package in the repository, there's no .deb, After installing about 40TB worth of dependencies, Sophos called the snap package a virus, and there's no make file so you can't compile it from source.

Either provide a way to install this software on Linux machines, or stop advertising it as Linux compatible.

**Comment by cignoni** [comment]
How can you say that you cannot compile it from source? 
Have you looked at the src/install/snap* folder?
Please.
