### ISSUE TITLE
Compiled meshlab crashes when screened poisson filter is applied. 

### ISSUE THREAD

**Issue by SikanderBinMukaram** [cnr-isti-vclab/meshlab#1030]
I have compiled meshlab on ubuntu using gcc and also using clang. I apply these filters in sequence:
- 'compute_normals_for_point_sets', k=5, smoothiter=5
- 're_orient_vertex_normals_using_cameras'
- 'smooths_normals_on_a_point_sets', k=10
- 'surface_reconstruction_screened_poisson', depth=9, preclean=True

But when the last filter is applied, meshlab crashes with an assertion message. here is the error
```
meshlab: /home/sikander/Desktop/meshlab/src/common/parameters/rich_parameter.cpp:109: void RichParameter::setValue(const Value &): Assertion `val->typeName() == ov.typeName()' failed.
Aborted (core dumped)
```
I have also installed meshlab and the installed version works fine. I have checked the previous issues with the changes done in .pro files but didn't find anything related to this.

**Comment by alemuntoni** [comment]
This issue has been already solved on [this commit](https://github.com/cnr-isti-vclab/meshlab/commit/76145cf731658ae1b068c8004b17fdf3073a8832). If you pull to the last commit it should work fine.
