### ISSUE TITLE
Mesh import options dissapeared on 2021.05 (Win and Mac)

### ISSUE THREAD

**Issue by sergiobd** [cnr-isti-vclab/meshlab#1031]
**Issue**
Import dialog does not appear anymore

**VErsions**
2021.05 Both mac and PC

**Description**
I used to import pointclouds as text files using File>ImportMesh, and selection options in a dialog box. Now the dialog doesn't appear any more. When I try to import a file, MeshLab tries to import without any options, and fails. The loaded meshes have zero vertices.

**Expected behaviour**
File>ImportMesh, then a dialog appears where the user selects options.

**How to reproduce**
Try to import a pts file using File>ImportMesh.

**Comment by alemuntoni** [comment]
Hi, this issue should be already solved in the last nightlies (you can try it by [downloading the last one](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version)), and the fix will be available in the next release.

You can also "fix" it in the 2020.05, by going into Tools -> Options, and then setting to true the option "MeshLab::System::showPreOpenParameterDialog".
