### ISSUE TITLE
Flatpak: Tries to save into non writable directory by default

### ISSUE THREAD

**Issue by simonschmeisser** [cnr-isti-vclab/meshlab#1033]
I opened an issue at the flathub repo as well: https://github.com/flathub/net.meshlab.MeshLab/issues/3

When I open a STL file by clicking on it in Dolphin (file manager of KDE) and then go for "File" > "Save Mesh as ..." I end up in a directory that is not writable and meshlab just hangs when I try to save into it:

![grafik](https://user-images.githubusercontent.com/372442/125088108-6574c100-e0cd-11eb-9aed-e6b3170c7b01.png)

Preferably the dialog should end up in the folder containing the actual file

**Comment by alemuntoni** [comment]
Thanks for reporting! Solved in the last commit.
