### ISSUE TITLE
Meshlab Point Based Gluing Issue

### ISSUE THREAD

**Issue by Kate6598** [cnr-isti-vclab/meshlab#1034]
I am using Meshlab 2020.12 and am attempting to place two identical stl files 'into' each other. To do so I have got one stl file and clicked 'glue here mesh' and the other pressed 'point based gluing' using the align tool. When I try to click my points however they generate at a distance to where i actually clicked. I'm not sure why this is happening and any advice would be appreciated. Thanks 
For reference, the yellow dot is where I clicked and 0 is the marker generated
![image](https://user-images.githubusercontent.com/87407642/125561816-d8872a35-5804-4c58-839f-59fb1a45db83.png)

**Comment by alemuntoni** [comment]
Could you please share the models that are causing this and if this happens every time or just for a specific set of areas of the meshes used as points?
