### ISSUE TITLE
Meshlab crashes when loading polygonal obj files with more than one textures

### ISSUE THREAD

**Issue by WuKongBlog** [cnr-isti-vclab/meshlab#1035]
The meshlab version I use was **MeshLab2021.07d_nightly_f60c934-windows**.

I have an polygonal OBJ file along with a corresponding MTL and several PNG textures. However, I found that if I only use one of the two (whichever) material meshlab opens the file alright. But if I use two simultaneously, meshlab crashes on start-up.

Here is a small example, If I comment out one of these lines “usemtl material0000”  “usemtl material0001” ，the file can be opened normally, otherwise it will crash.

building.mtl
```
newmtl material0000
Ka 1.000000 1.000000 1.000000
Kd 1.000000 1.000000 1.000000
Ks 0.000000 0.000000 0.000000
Tr 1.000000
illum 1
Ns 1.000000
map_Kd building_material0000_map_Kd.png
newmtl material0001
Ka 1.000000 1.000000 1.000000
Kd 1.000000 1.000000 1.000000
Ks 0.000000 0.000000 0.000000
Tr 1.000000
illum 1
Ns 1.000000
map_Kd building_material0001_map_Kd.png
```
building.obj
```
mtllib building.mtl
v 21609.599609 -19086.248047 3.616000
v 21609.396484 -19088.847656 3.616000
v 21610.871094 -19088.962891 3.616000
v 21611.074219 -19086.363281 3.616000
v 21609.396484 -19088.847656 6.252000
v 21609.599609 -19086.248047 6.252000
v 21609.687500 -19088.597656 6.252000
v 21609.849609 -19086.541016 6.252000

vt 0.007812 0.893926
vt 0.737985 0.893926
vt 0.737985 0.887149
vt 0.749180 0.887149
vt 0.749925 0.887149
vt 0.772749 0.941363
vt 0.749925 0.992188
vt 0.740763 0.992188

vn -0.531657 0.618713 -0.578391
vn -0.619826 -0.532613 -0.576315
vn 0.530562 -0.620543 -0.577435
vn 0.620633 0.530640 -0.577266
vn -0.438676 -0.376952 0.815764
vn -0.375599 0.437102 0.817232
vn 0.438296 0.377597 0.815670
vn 0.376069 -0.436521 0.817326

usemtl material0000
f 1/1/1 2/2/2 3/3/3 4/4/4 

usemtl material0001
f 5/5/5 7/7/7 8/8/8 6/6/6
```

**Comment by WuKongBlog** [comment]
PS：Here is a similar question [meshlab-crashes-when-loading-obj-files-with-more-than-one-png-textures](https://stackoverflow.com/questions/65121529/meshlab-crashes-when-loading-obj-files-with-more-than-one-png-textures)

**Comment by alemuntoni** [comment]
Same issue of #982, #796, #239

**Comment by alemuntoni** [comment]
fixed [here](https://github.com/cnr-isti-vclab/meshlab/commit/8dbf6b635f61c154371872be62bb7de7eab77e11). Will be available in the next version of meshlab, which will be released in the next days.
