### ISSUE TITLE
FBX importing error

### ISSUE THREAD

**Issue by serdaraltin** [cnr-isti-vclab/meshlab#1037]
When I import 3d model (.fbx) I get this error.

OS:  Linux kubuntu 5.4.0-77-generic Ubuntu
Version: 2021.05d-linux

![meshlab-gl-error-2](https://user-images.githubusercontent.com/43209941/125806731-2f0a0f9f-a3ca-426f-af1e-ad381af25424.png)

![meshlab-gl-error-3](https://user-images.githubusercontent.com/43209941/125807029-027c47d4-46f0-4bd8-9684-88bbb617870d.png)

![meshlab-gl-error](https://user-images.githubusercontent.com/43209941/125806353-f46a094c-c858-4b24-aab0-59498bfddca3.png)

**Comment by alemuntoni** [comment]
Without the file, I'm unable to reproduce the issue.

**Comment by serdaraltin** [comment]
Object file: [object.zip](https://github.com/cnr-isti-vclab/meshlab/files/6825343/object.zip)

**Comment by alemuntoni** [comment]
There is no such "tiwidimhx_LOD0.fbx" in the archive you shared, but just "house.fbx", with all the textures non loadable since the file stores invalid file paths.

**Comment by serdaraltin** [comment]
All imports have the same problem, forwarded as an additional example.
The content in the image is megascan content.
I guess the problem is with Open GL.

**Comment by alemuntoni** [comment]
I don't know, I am not able to reproduce the issue.
2021.05d never prints "There are gl errors: invalid operation" when importing an fbx file.
Apart from the message error in the log, do you experience some other issue?

**Comment by serdaraltin** [comment]
The cause of the error is the Amd driver, no problems occurred when I used open source drivers.
My video card uses mesa drivers and this is causing problems with many programs.
Thanks for your interest and help.
