### ISSUE TITLE
Seperatly compiled filters slower than meshlab.

### ISSUE THREAD

**Issue by SikanderBinMukaram** [cnr-isti-vclab/meshlab#1046]
I compiled some of the meshlab filters separately (from their source code available). The results of the filters are almost similar to the ones using meshlab but are slower. For example, Compute normals take 2320 ms for a bundle file on meshlab while it takes around 15000 ms on the separately compiled filter. I am compiling like this 
```
	g++ -DBRUNO_LEVY_FIX -DMESHLAB_SCALAR=float -I./../common/ml_document -I./../vcglib -I./../vcglib/eigenlib -I./../external/easyexif -c -fopenmp -lpthread -g -o driverCode.o driverCode.cpp
```
Is meshlab using multi threads which are making it faster ?

**Comment by alemuntoni** [comment]
There is nothing special in the cmake configuration about compile options.
We just link some plugins with OpenMP targets, and then build with the cmake option `-DCMAKE_BUILD_TYPE=MinSizeRel`.

**Comment by SikanderBinMukaram** [comment]
Thanks a lot, it helped. Now it's taking almost the same time as meshlab. Adding -Os -DNDEBUG solved the problem.
