### ISSUE TITLE
shift + wheel not working when using mouse instead of trackpad on mac 

### ISSUE THREAD

**Issue by AsaphLightricks** [cnr-isti-vclab/meshlab#1049]
Hi, 

I'm using meshlab on mac, when i use my trackpad to adjust the camera FOV (shift + drag) it works no problem. But, when i try to adjust the camera FOV using shift + wheel with my mouse it doesn't work. (regular zoom in/out using the mouse wheel does work)

meshlab version:
![image](https://user-images.githubusercontent.com/50834050/127133665-b6537a0b-5ba7-44a0-aa98-0bb12d791e59.png)

macOS
Big Sur version: 11.4 (20F71)

**Comment by alemuntoni** [comment]
Fix will be available in the next version of meshlab!
