### ISSUE TITLE
Unable to load libio_e57.so plugin on launch; 2021.07 on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by rchensix** [cnr-isti-vclab/meshlab#1050]
I get the following error popup when trying to open 2021.07 Linux AppImage after doing `sudo apt install libopengl0` (it didn't open at all before).

```
Unable to load the following plugins:

	libio_e57.so: libio_e57.so does not seem to be a Qt Plugin.

Cannot load library /tmp/.mount_MeshLatjRwgC/usr/lib/meshlab/plugins/libio_e57.so: (libxerces-c-3.2.so: cannot open shared object file: No such file or directory)
```
The app still opens up after I dismiss the popup. Not sure which plugins are affected, if any.

Platform: Ubuntu 20.04.2 LTS, AMD Ryzen 4700U
Meshlab Version: 2021.07 (for reference, 2020.12 opens with no errors and I didn't have to install `libopengl0` either).

**Comment by alemuntoni** [comment]
Hi, the issue about `libopengl0` is known and does not depend on us (see #1023).
About the error of `libio_e57`, that's weird: the missing xerces library is actually correctly bundled into the appimage.
In the meantime, you could remove the error by installing the xerces package:
```
sudo apt install libxerces-c-dev
```

**Comment by alemuntoni** [comment]
Fixed in the last commit. Next release won't require libxerces installed in the system.
Thanks for reporting!

**Comment by Symbian9** [comment]
> Fixed in the last commit. Next release won't require libxerces installed in the system.

@alemuntoni, Issue still persists:

```
Unable to load the following plugins:

	libio_e57.so: libio_e57.so does not seem to be a Qt Plugin.

Cannot load library /tmp/.mount_MeshLag1Vvdp/usr/lib/meshlab/plugins/libio_e57.so: (libicuuc.so.60: cannot open shared object file: No such file or directory)
```

Just tried latest nightly (`MeshLab2021.08_nightly_5ec6585-linux.AppImage`) under **Debian 10.x**.

**Comment by alemuntoni** [comment]
@Symbian9 Could you please try the AppImage generated with [this build](https://github.com/cnr-isti-vclab/meshlab/runs/3359742089?check_suite_focus=true)? It will be ready in ~15 minutes.

**Comment by Symbian9** [comment]
> Could you please try the AppImage generated with this build?

Just tried and seems like there is no issues anymore ;) 

- https://github.com/cnr-isti-vclab/meshlab/actions/runs/1142644737
  - https://github.com/cnr-isti-vclab/meshlab/suites/3529352267/artifacts/84379405
