### ISSUE TITLE
"xxx.dll does not seem to be a Qt plugin" error when starting MeshLab in Windows10

### ISSUE THREAD

**Issue by xiechun-tsukuba** [cnr-isti-vclab/meshlab#1060]
Hi,

I just installed the latest version of MeshLab (2021.7) using the installer for Win64. Every time I start MeshLab, it shows the plugin errors as shown in the screenshot below. Clicking the OK button then MeshLab will start as usual, but those failed plugins are not loaded. I checked the paths and confirmed that those dll files exist.

It looks like some plugin compatibility issues to me, but I didn't download them from some third-party sites, they came with the installer. I googled it but couldn't find similar issues reported elsewhere. Do you know what is going wrong here?

Thank you in advance.
![image](https://user-images.githubusercontent.com/83652157/129541876-f7d8682d-7a5e-44c0-ae03-0a58b724ac00.png)

**Comment by meacoder** [comment]
I had this issue. I tracked it to MS Visual studio c++ 2015-2019. After using the repair feature it went away.

**Comment by alemuntoni** [comment]
The not-loadable plugins are all plugins that require OMP, therefore this issue could be related with a non-properly installed vc_redist.
Could you please go into the MeshLab installation directory (C:\Program Files\VCG\MeshLab) and re-install `vc_redist.x64.exe`?

@meacoder, could you please be more specific on what "repair feature" exactly did you run to solve the issue? Could you please share a link that could help other users?

**Comment by meacoder** [comment]
the vc_redist.x64.exe in C:\Program Files\VCG\MeshLab gives an error since the I have a newer version installed. In the Control Panel Items\Programs and Features\ I had the Microsoft Visual C++ 2015-2019 Redistributable Package 14.29.30040.  If you uninstall them it will give a repair function too and that is what i did. When the 64 bit finish i did not have to restart my computer but when the 32 bit finished I did. After restart I no longer get the error when starting Meshlab.

**Comment by xiechun-tsukuba** [comment]
Hi @meacoder @alemuntoni 

Thank you very much for your advices.

I went to "C:\Program Files\VCG\MeshLab" and re-run vc_redist.x64.exe. It gives a repair function so I tried that first instead of reinstall. After repairing the errors are gone. 

I have MS Visual studio c++ previously  installed in my computer, maybe they are the cause of the problem?

**Comment by alemuntoni** [comment]
I don't know, @xiechun-tsukuba.
Maybe something just broken somehow... Very hard do say!

**Comment by liuxiaozhu01** [comment]
Hi! I met the same question with the newest version 2022.02 in win11. And i cannot find the `vc_redist.x64.exe` in the install path. Any ideas?

**Comment by liuxiaozhu01** [comment]
> Hi! I met the same question with the newest version 2022.02 in win11. And i cannot find the `vc_redist.x64.exe` in the install path. Any ideas?

OK it is solved by download it from [here](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) and re-install microsoft visual c++.
