### ISSUE TITLE
.ply To .E57 export Meshlab crashe

### ISSUE THREAD

**Issue by ggaspard54** [cnr-isti-vclab/meshlab#1063]
Hello,

i'm trying to export to .e57 a .ply file but Meshlab crash...

My .ply file have 7M points so i decimate to less points (300k) but i still have this problem..

My ply file is from kinect for Azure.

My ply file :
[ply_300k.zip](https://github.com/cnr-isti-vclab/meshlab/files/7007784/ply_300k.zip)

Thx !

**Comment by alemuntoni** [comment]
Fixed in the last commit! 
You can check it by downloading the [last nightly build](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version) (will be available in ~20 minutes).
Thanks for reporting!

**Comment by ggaspard54** [comment]
Perfect ! it works !

thx !
