### ISSUE TITLE
2021.07 Crashes while importing e57 file on Windows 10

### ISSUE THREAD

**Issue by TristanLecallier** [cnr-isti-vclab/meshlab#1067]
Hi, 
I'm trying to import an e57 file into Meshlab (~300Mo) but Meshlab crashes (it closes). I'm running on Windows 10.
Does anyone has encountered the same issue ?

**Comment by alemuntoni** [comment]
Could you please share the file that causes the issue?

**Comment by TristanLecallier** [comment]
I sent it privately.

**Comment by alemuntoni** [comment]
This issue was already solved in #1063 and the fix will be available in the next version.
You can try the fixed version by downloading the [last nightly build](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version).
