### ISSUE TITLE
Cannot load obj file with tif texture

### ISSUE THREAD

**Issue by csparker247** [cnr-isti-vclab/meshlab#1068]
I'm running MeshLab 2021.07, installed via Homebrew, on macOS Big Sur 11.5.2. I have code which saves OBJ files with textures in various formats. I recently needed to switch the default texture format in my active project from a PNG file to a TIF file. When trying to load the OBJ in MeshLab, I get a texturing loading error:

<img width="532" alt="Error message" src="https://user-images.githubusercontent.com/1434526/130478280-cf27f496-8e42-4f01-9996-ddd10e3865b3.png">

The mesh itself appears to load fine, just without the texture:

<img width="668" alt="No texture mesh" src="https://user-images.githubusercontent.com/1434526/130478346-490bc830-e82b-41b5-bdec-ce70026da828.png">

A version of the same mesh with a PNG texture loads just fine:

<img width="668" alt="Texture mesh" src="https://user-images.githubusercontent.com/1434526/130478633-31e8b292-b7b3-4a67-8b4c-cb8555ad5b0f.png">

This is very similar (if not the same) as #255. My native image is 16-bit, grayscale, but I have converted it to 8-bit, RGB and still cannot load it. To sanity check, I have loaded the TIF mesh in Blender with no issues. Additionally, I have a Qt5-based image viewer app that loads the image with no issues, so I don't think the TIF file itself is invalid. 

Problematic example file (obj + mtl + 8bpc, RGB tif) is attached: [obj_tif.zip](https://github.com/cnr-isti-vclab/meshlab/files/7033320/obj_tif.zip)

**Comment by alemuntoni** [comment]
fixed in the last commit. You can try it by downloading the last [nightly](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version) (ready in ~20 minutes)

**Comment by csparker247** [comment]
Can confirm that it works as expected. Thanks for the quick help!

**Comment by csparker247** [comment]
> I seem to have the same bug on MeshLab_64bit_fp v2020.03+dfsg1 on ubuntu 20.04. I can load the file just fine in blender and gimp but I can't in meshlab. My image is the same as @csparker247 (16-bit, grayscale).

Oh I see. Your MeshLab version is even older than the one I was using. You should download a newer build: https://www.meshlab.net/#download

**Comment by billmdevs** [comment]
Thank you very much @csparker247 It was because of the version I was using.
