### ISSUE TITLE
Custom PLY attributes.

### ISSUE THREAD

**Issue by bartoszek** [cnr-isti-vclab/meshlab#107]
Is there a way to handle custom PLY attributes ?
I have file like this produced by mvs software.

`ply`
`format binary_little_endian 1.0`
`comment Export generated by libmve`
`element vertex 12703245`
`property float x`
`property float y`
`property float z`
`property uchar red`
`property uchar green`
`property uchar blue`
`property float confidence`
`property float value`
`element face 25181321`
`property list uchar int vertex_indices`
`end_header`

Would like to use _confidence_ attribute for selection and quality visualization.

**Comment by cignoni** [comment]
MeshLab when saving ply allows to preserve the scalar `quality`field in the ply file. It is saved as a float property as follow:

```
ply
format binary_little_endian 1.0
comment VCGLIB generated
element vertex 18432
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
property float quality
element face 36864
property list uchar int vertex_indices
end_header
```

You can find an example here: https://github.com/cnr-isti-vclab/meshlabjs/raw/master/mesh/torus_quality.ply

If a loaded PLY has a property named 'confidence' it is automatically loaded  and mapped into the usual MeshLab _quality_.

**Comment by bartoszek** [comment]
Thanks for clarifying, and also for _correcting my spelling_ ;)

**Comment by rajjakabdu699-art** [comment]
Uuurr
