### ISSUE TITLE
[2021.07] libxerces dependency missing on Debian 11

### ISSUE THREAD

**Issue by wsdookadr** [cnr-isti-vclab/meshlab#1074]
### Problem description

I'm using **Debian 11 bullseye** and I tried using the [latest appimage release 2021.07](https://github.com/cnr-isti-vclab/meshlab/releases/tag/Meshlab-2021.07). At startup, it shows an error with the following message:

```Unable to load the following plugins:

	libio_e57.so: libio_e57.so does not seem to be a Qt Plugin.

Cannot load library /tmp/.mount_MeshLardC8HA/usr/lib/meshlab/plugins/libio_e57.so: 
(libxerces-c-3.2.so: cannot open shared object file: No such file or directory)
```

![Screenshot_2021-09-01_09-56-20](https://user-images.githubusercontent.com/180373/131626446-e55d9945-42d3-4ebb-9b4f-72cc405bf8bc.png)

### Workaround

I worked around this by installing libxerces:

`sudo apt-get install libxerces-c-dev libxerces-c3.2`

### Proposed solution

To fix this, I propose libxerces be added to the list of installed packages in the build environment, so in the file [0_setup_env_ubuntu.sh](https://github.com/cnr-isti-vclab/meshlab/blob/32ddb41/scripts/Linux/0_setup_env_ubuntu.sh) and maybe also to the script that bundles together everything in the AppImage, in [2_deploy.sh](https://github.com/cnr-isti-vclab/meshlab/blob/539725c/scripts/Linux/2_deploy.sh) . In the latter, I agree that [`-bundle-non-qt-libs`](https://github.com/probonopd/linuxdeployqt#usage) should be enough, but it seems like libs need to be explicitly added there.

**Comment by alemuntoni** [comment]
This issue should be already solved here: 3327cebb9bfa57584f62daff9f2ed2ed1da6e539
You can downloading the [last nightly build](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version) to check if everything works as expected.
