### ISSUE TITLE
 Distribution of some menus.

### ISSUE THREAD

**Issue by GiovanniSer** [cnr-isti-vclab/meshlab#1075]
I'm doing some very complicated STL faces bug-hunting work.
ML is very useful but I have a problem using some menus expeditiously.
I don't understand why in my opinion they are not intuitively articulated.
I explain better.
**"Selection"** select the faces, but it contains four "Delete [SELECTED] faces... "
**"Cleaing and repairing"**, in reverse, contains "Select self intersecting faces"
It seems a small thing but it is very uncomfortable working fast, it forces us to continually reverse the paths in a non-intuitive way.
Thank!

**Comment by alemuntoni** [comment]
"Selection" and "Cleaning and repairing" are just categories.
Filters can also be contained in multiple categories (e.g. "Select self intersecting faces" is contained both in "Cleaing and repairing" and "Selection"). 

If you already know which filter you need to use, you can use the CTRL+F shortcut, or click into the magnifying glass icon in the top-right of the meshlab window, and search for the filter you need to run. This solution should be faster :)
