### ISSUE TITLE
[MacOS] Filter Transfer Color: Texture to Vertex duplicates the texture path, and fails

### ISSUE THREAD

**Issue by sergiobd** [cnr-isti-vclab/meshlab#1079]
**Platform:** MacOS 11.2.2 Big Sur

The filter 'Transfer Color: Texture to Vertex' duplicates the texture path:

<img src="https://user-images.githubusercontent.com/4733666/132470439-0885bc3f-8170-4812-8ae9-41165cb6cad0.png" width="300" >

and of course, fails.

**Version** : 2020.12 (had to downgrade because of another issue)

**Comment by alemuntoni** [comment]
This issue has been already solved and does not appear in newer versions. 
If you had to downgrade because of another issue, please do not open issues for (already solved) bugs of old versions, and report the new issue instead.
