### ISSUE TITLE
Challenge using Meshlab server: How to use multiple input objs to create a poisson mesh and save the poisson mesh

### ISSUE THREAD

**Issue by DanWhitton** [cnr-isti-vclab/meshlab#108]
Hello,

I've been working for a few days now to find a way to batch a set of directories each with 3 obj's that I would like to combine using screened Poisson surface reconstruction then save the result using meshLab server.

The approach I have been taking thus far is:
create a .mlp that holds the place of each .obj
create a .mlx with the screened poisson filter as well as a filter that sets the result layer to current.

Using a visual basic script pointing to the directory of the obj's and script along with the arguments to read the lmp I execute.

Problem is I can not find a way for the meshlab server to see the result of the poisson filter in order to save it.

Does anyone have any ideas?

I'll include the .mlp, .mlx, and vbs script.

Dim stRep,scriptRep,meshLabRep,ext

stRep = "N:\2KGNOV\Whiskey\Development\Team\Dan_Whitton\Face_Pipeline\__test_pythonScript_search_and_replace" 'Name of the directory where the objs are
scriptRep = "N:\2KGNOV\Whiskey\Development\Team\Dan_Whitton\Face_Pipeline\__test_pythonScript_search_and_replace\poisson_and_change_layer.mlx" 'Name of the directory where the mlx file is
ext = "mlp"

Dim oFSO,oFl
Set oFSO = CreateObject("Scripting.FileSystemObject")

Set WshShell = WScript.CreateObject("WScript.Shell")

If oFSO.FolderExists(stRep) Then
 For each oFl in  oFSO.GetFolder(stRep).Files
   FOR EACH strExt in SPLIT(UCASE(ext),",")
      IF RIGHT(UCASE(oFl),LEN(strExt)+1) = "." & strExt THEN
         'IF 64 BIT OS
         cmd = """%ProgramFiles%\VCG\MeshLab\meshlabserver""" & "-p " & stRep & "\" & oFl.Name & " -o " & stRep & "\OUT_" & oFSO.GetBaseName(oFl.Name) & ".obj" & " -s " & scriptRep
         WshShell.Run cmd ,1,True
      END IF
   Next
 Next
End If

<!DOCTYPE FilterScript>
<FilterScript>
 <xmlfilter name="Screened Poisson Surface Reconstruction">
  <xmlparam value="0" name="cgDepth"/>
  <xmlparam value="false" name="confidence"/>
  <xmlparam value="8" name="depth"/>
  <xmlparam value="5" name="fullDepth"/>
  <xmlparam value="8" name="iters"/>
  <xmlparam value="4" name="pointWeight"/>
  <xmlparam value="true" name="preClean"/>
  <xmlparam value="1.5" name="samplesPerNode"/>
  <xmlparam value="1.1" name="scale"/>
  <xmlparam value="true" name="visibleLayer"/>
 </xmlfilter>
 <filter name="Change the current layer">
  <Param value="3" name="mesh" type="RichMesh" tooltip="The name of the current mesh" description="Mesh"/>
 </filter>
</FilterScript>

<!DOCTYPE MeshLabDocument>
<MeshLabProject>
 <MeshGroup>
  <MLMesh label="exp10_left.obj" filename="exp10_left.obj">
   <MLMatrix44>
1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 
</MLMatrix44>
  </MLMesh>
  <MLMesh label="exp10_right.obj" filename="exp10_right.obj">
   <MLMatrix44>
1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 
</MLMatrix44>
  </MLMesh>
  <MLMesh label="exp10_front.obj" filename="exp10_front.obj">
   <MLMatrix44>
1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 
</MLMatrix44>
  </MLMesh>
 </MeshGroup>
 <RasterGroup/>
</MeshLabProject>

**Comment by mcallieri** [comment]
Setting the current layer is not enough:

MeshLabServer keeps layers in the same way MeshLab does, and saves layers following their order. So, as there are 3+1 layers (the original ones and the poisson), you have to export X+1 meshes. If you add two exporting parameters -o layer0.ply -o layer1.ply -o layer2.ply -o layer3.ply -o layer4.ply the first 3 ones will contain the original mesh, and the last one the merged one. Unfortunately, it is not possible, at the moment, to save just the CURRENT LAYER.

Another option is to make a script like this:
 1.do the poisson
 2.select layer 0
 3.delete current layer
 4.select layer 1
 5.delete current layer
 6.select layer 2
 7.delete current layer

In this way, the only remaining layer will be the poisson (layer 4), and it will be possible to save only that one.
 
The filter to change the current layer is filter->mesh layer->"change the current layer", that in script will be

```
<filter name="Change the current layer">
  <Param tooltip="The name of the current mesh" type="RichMesh" value="0" name="mesh" description="Mesh"/>
 </filter>
```

layer numbers start at 0.
then, to delete the current mesh, use filter->mesh layer->"delete current mesh".

` <filter name="Delete Current Mesh"/> `

If you add those filters after the poisson, and than save the only remaining layer, you should have what you need.

let me know

**Comment by granzuglia** [comment]
It's a lot more simple than you think. 

c:\Program Files\VCG\meshlab\meshlabserver.exe -i file1.obj -i file2.obj -i file3.obj -w outputpoissonproj.mlp -s poissonscript.mlx

In output you will have a MeshLab project file containing the input models and the screened poisson file. The screened poisson file will be called Poissonmesh_out.ply

the only problem you can have with this approach is when you need to save additional attributes per mesh (vertex/face color, vertex/face texture coords, etc.) different from the "standard" ones.

PS as it was pointed in a previous thread you cannot run (the 2016.12 version of) meshlabserver in its containing folder. You should move to the obj files folder and launch the MeshLabServer executable from there. We solved the issue in the current MeshLabServer code that you can download and compile from the MeshLab git repository.
