### ISSUE TITLE
Texture loading from different extensions impossible

### ISSUE THREAD

**Issue by arnaudbletterer** [cnr-isti-vclab/meshlab#1081]
I have models whose textures (in JPEG format most of the time) do not always have an extension matching the expected one, but can have a custom one for my specific needs. However the content of the file is of course JPEG.

Since Meshlab 2021.07, it is not possible to load models with textures whose extension doesn't match a list of known extensions anymore. Thus, every time I try to load the aforementioned models, I get a warning from meshlab "The following textures have not been loaded: ..." and effectively, no texture is associated to the loaded mesh.

It seems that this behavior follows partly the changes from commit cedf7f1dfdacf1a9c31aa9d8ae51dadf1ad275c4, and the fact that `BaseMeshIOPlugin::openImage` checks for correct formats by iterating through a list of known extensions and matching these extensions to the one of the image trying to be loaded.

Could it be possible to have a different mechanism to identify image formats than based on the extension of the file? 

As a way to start providing some insights for an answer, here is what I can find based on what Meshlab is currently using.

From Qt documention (https://doc.qt.io/qt-5/qimage.html#load) it is said, for `QImage::load`:
*The loader attempts to read the image using the specified format, e.g., PNG or JPG. If format is not specified (which is the default), it is auto-detected based on the file's suffix and header. For details, see QImageReader::setAutoDetectImageFormat().*

So maybe some mechanism around `QImage::load` (which is actually used to read images by Meshlab) could be used to allow the format of the file to be inferred on its content rather than its extension.

**Comment by alemuntoni** [comment]
We switched to a different mechanism to identify image formats in order to extend the image formats known by MeshLab.
`QImage::load` is not anymore the only function that loads an image: now, anyone can implement a IO plugin with a custom load function that loads the image and stores it in a `QImage`. Moreover, the same mechanism is used to load rasters.
I'll try to figure out if there is some way to have a fallback on QImage::load when the format is not known..

**Comment by arnaudbletterer** [comment]
I see, thanks for the explanation.

I was imagining that after checking for those file formats (and thus after having decided to use the appropriate IO plugin to be used), for all the formats that do not require a custom load function (such as what you explained for TGA images), to use by default the `QImage::load`, and to leave to that specific loader the task of filtering out the images that really cannot be loaded.

I have some idea of implementation with respect of what I have seen that I could try during the weekend, on which we might iterate, if you want.

**Comment by alemuntoni** [comment]
I had a look into the code and it was actually pretty easy to code! Should be fixed now!
You can try it by downloading the last [nightly version](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version) (will be ready in ~20 minutes)! Let me know if it works with your files!

**Comment by arnaudbletterer** [comment]
It behaves as expected, loading correctly the texture associated to the mesh, despite the extension of the texture file not being something standard.

Thank you for that quick correction!
