### ISSUE TITLE
Texture Parameterization from Rasters has offset for some reason

### ISSUE THREAD

**Issue by syberspaz** [cnr-isti-vclab/meshlab#1088]
I've been working with the Texture Parameterization filter to texture a mesh and I've noticed that for some reason it is sampling the texture with an offset thus creating an incorrectly textured mesh that doesn't line up properly.  

You can clearly see it in this gif of me just changing the visibility of the registered raster layer.
https://gyazo.com/ce3642771030a2c9bb82172ad244a31b

In this case I have a single raster layer registered with this model and the mesh itself is registered well to the image.
I'm using Meshlab 2020.03

Here is the execution log:
VISIBILITY CHECK: 0.011 sec.
BOUNDARY OPTIMIZATION: 0.014 sec.
CLEANING ISOLATED TRIANGLES: 0.003 sec.
* 18 triangles cleaned.
PATCH EXTRACTION: 0.001 sec.
* 10 patches extracted, 9 null patches.
PATCH EXTENSION: 0.000 sec.
PATCHES UV COMPUTATION: 0.000 sec.
PATCH MERGING: 0.000 sec.
* Area reduction: 97.1%.
* Patches number reduced from 10 to 1.
PATCH TEXTURE PACKING: 0.001 sec.
TEXTURE PAINTING: 0.054 sec.
Applied filter Parameterization + texturing from registered rasters in 782 msec

**Comment by syberspaz** [comment]
also just checked and this bug also exists in MeshLab version 2021.07

**Comment by syberspaz** [comment]
I have determined that it is due to the CenterPx values on my y.  Setting the CenterPx y value to be exactly in the middle of my image "fixes" the issue.  However my camera intrinsic parameters do have non-centered CenterPx values from my calibration software. So, is Meshlab not taking this into account properly during the projection phase of the algorithm?

**Comment by alemuntoni** [comment]
Hi @syberspaz, sorry for the very late reply. Could you please share the input you are using and the exact steps to help us reproduce the issue?

**Comment by syberspaz** [comment]
Hi, I'm not sure if I still have those files but I'll check later and see.  

I think what would help is a description of the camera parameters that need to be specified in the Raster layer, i.e. what units are they, how are the lens Distortions taken into account (i.e. are they normalized etc).  I noticed that FocalMm is not necessarily specified in millimeters, so should it just be Focal length specified in pixels, is this only true if PixelSizeMm is specified as "1 1" etc.  

Potentially similar to : [https://sourceforge.net/p/meshlab/discussion/499533/thread/975e0cf6/](https://sourceforge.net/p/meshlab/discussion/499533/thread/975e0cf6/)
