### ISSUE TITLE
.mlp files with Windows (CR LF) not opening properly

### ISSUE THREAD

**Issue by syberspaz** [cnr-isti-vclab/meshlab#1091]
If a .mlp project file is saved with Windows (CR LF) line endings, the file does not open properly.  

Specifically, I am specifying a mesh as a .obj file in the .mlp, if I open this in Notepad++ and save 2 versions one with Windows (CR LF) and one with Unix (LF), both files "open" but only the Unix (LF) version opens the .obj properly.  The windows (CR LF) version contains a very stretched mesh that is not correctly loaded.

Meshlab Version 2021.07

Note that this used to work under Meshlab version 2020 (i.e. issue isn't present under previous versions).

**Comment by alemuntoni** [comment]
If you are modifying manually .mlp files, just use only unix line endings.
mlp project files must be the same for all the operative systems, therefore just one line ending is fully supported (LF), and meshlab must open correctly only the mlp files that it stores.
