### ISSUE TITLE
Crashed while deleting vertices / faces when "Render ( Vert / Faces )"

### ISSUE THREAD

**Issue by sprhawk** [cnr-isti-vclab/meshlab#1094]
MeshLab 2021.07, Linux, Flatpak version
Debian 11 Bullseye

After I select a bunch of Vertices,  If I delete vertices when MeshLab in Render Vert / Faces mode, it will crash.
It works well when in Render ( Wireframe ) mode.

I am using [this model](https://free3d.com/3d-model/excevator-321729.html) and exported as .obj from blender

**Comment by alemuntoni** [comment]
I am trying to replicate the issue (on ubuntu), but I cannot replicate it. 
Before setting up a debian machine, I would like to be sure that I am performing the same operations that you are.

After loading [this model](https://github.com/cnr-isti-vclab/meshlab/files/7209137/excavator.zip):
- deactive wireframe render mode;
- start the "select vertices" edit mode, select some vertices;
- apply the filter "delete selected vertices".

could you please confirm that if you perform these steps meshlab crashes?
Moreover, could you please try if it crashes also when running the AppImage?

**Comment by sprhawk** [comment]
> Moreover, could you please try if it crashes also when running the AppImage?

I tried AppImage, It works, no problem.


> After loading [this model](https://github.com/cnr-isti-vclab/meshlab/files/7209137/excavator.zip):
> 
>     * deactive wireframe render mode;
>     * start the "select vertices" edit mode, select some vertices;
>     * apply the filter "delete selected vertices".

By default, MeshLab started in both wireframe mode and face mode enabled. 
Then I choose `Select Faces in a rectangle region` and select some vertices;
Then I `Delete the current set of selected faces, vertices that remains unreference are not deleted`

**Comment by sprhawk** [comment]
gdb crash stack log
```
Starting program: /app/bin/meshlab 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff2ea5700 (LWP 9)]
[New Thread 0x7ffff13fc700 (LWP 10)]
[New Thread 0x7ffff0bf1700 (LWP 11)]
Gtk-Message: 18:07:06.509: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:07:06.509: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
[New Thread 0x7fffe3fff700 (LWP 12)]
[New Thread 0x7fffe1271700 (LWP 13)]
[New Thread 0x7fffe0a70700 (LWP 14)]
[New Thread 0x7fffd3fff700 (LWP 15)]
[New Thread 0x7fffcb7fe700 (LWP 16)]
Shader directory found '/app/bin/shaders', and it contains 0 gdp files
Shader directory found '/app/bin/shaders', and it contains 0 gdp files
Using OpenGL 4.6
Mesh is Polygonal!
LOG: 0 Opened mesh /home/xxx/Downloads/excavator/excavator.obj in 24 msec
LOG: 0 All files opened in 32 msec
LOG: 0 Started Mode Select Faces in a rectagular region
libpng warning: iCCP: known incorrect sRGB profile
LOG: 2 Deleted 552 faces.
/usr/include/c++/10.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>; std::vector<_Tp, _Alloc>::reference = unsigned int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

Thread 1 "meshlab" received signal SIGABRT, Aborted.
0x00007ffff634c7f5 in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
```

**Comment by alemuntoni** [comment]
thanks @sprhawk.
I can confirm the crash also in ubuntu, but when running "Delete selected faces and vertices".

**Comment by sprhawk** [comment]
> thanks @sprhawk.
> I can confirm the crash also in ubuntu, but when running "Delete selected faces and vertices".

Right, multple "delete"s did crash on my machine.

**Comment by alemuntoni** [comment]
I was checking again this issue, and I cannot replicate it anymore. It could have been solved by some other bugfix some time ago.
I'll ship a new release soon, if the issue persists also in the new release please let me know! Thanks again @sprhawk!

**Comment by sprhawk** [comment]
> I was checking again this issue, and I cannot replicate it anymore. It could have been solved by some other bugfix some time ago. I'll ship a new release soon, if the issue persists also in the new release please let me know! Thanks again @sprhawk!

Great !
