### ISSUE TITLE
CMake Policy CMP0072 (GLNVD) not applied correctly

### ISSUE THREAD

**Issue by StefanBruens** [cnr-isti-vclab/meshlab#1095]
Commit https://github.com/cnr-isti-vclab/meshlab/commit/7d47760d37b47ab01c1b426500c7e79fdeee9f43 moved
the `cmake_policy(SET CMP0072 NEW)` from the toplevel scope to the scope of the included file.

https://cmake.org/cmake/help/latest/manual/cmake-policies.7.html:

> The setting of a policy is confined in some cases to not propagate to the parent scope. For example, if the files read by the include() command or the find_package() command contain a use of cmake_policy(), that policy setting will not affect the caller by default. Both commands accept an optional NO_POLICY_SCOPE keyword to control this behavior.

**Comment by alemuntoni** [comment]
Thank you very much  @StefanBruens, I didn't know that scope changed also when using `include` in cmake. I thought only concert the `add_subdirectory` instruction. Thanks!!

**Comment by alemuntoni** [comment]
I think that this is also why I was having the problem related to this issue: https://github.com/probonopd/linuxdeployqt/issues/486
I tried to force using legacy opengl everywhere in meshlab in order to remove `libopengl.so` dependency, which cannot be bundled in appimages.
