### ISSUE TITLE
Export e57 to DAE / OBJ

### ISSUE THREAD

**Issue by ati184** [cnr-isti-vclab/meshlab#1098]
Hello Meshlab Developers,

thank´s a lot for the development of Meshlab. It´s a great software. I have an issue with DAE and obj - file. They will be processed, but I couldn´t open it e.g. with 3D-Viewer or Sketchup.

The file size of the 3 files is as zip-file 300 MB. I couldn´t upload it to github, but I can send it via e.g. WETransfer.

You can contact me at andreas.tigges@teamproject.de

Thank´s in advance

Andreas

**Comment by alemuntoni** [comment]
Are you getting errors from 3D-Viewer or Sketchup while loading the exported file? Could just be that some obj file specifications are not supported by these software? In that case would be their issue, not meshlab's. 
Is the exported obj file correctly loaded by meshlab?

**Comment by alemuntoni** [comment]
yes, please send me the link at muntoni.alessandro@gmail.com

**Comment by alemuntoni** [comment]
As far as I can see, the Microsoft 3D viewer is not able to open point clouds in general, therefore it is not possible to show an exported e57 there. I think that you should report this to microsoft.
The obj file exported by meshlab looks fine, and it should be correctly imported by any software that supports correctly the wavefront obj standard file format.
