### ISSUE TITLE
GLEW initialization failed error

### ISSUE THREAD

**Issue by R7CrazyCanucks** [cnr-isti-vclab/meshlab#1102]
How in the depths of hell do you fix this error???
![image](https://user-images.githubusercontent.com/61438841/135364651-c37709c5-ee93-4c45-b29e-24180f95443c.png)

**Comment by alemuntoni** [comment]
You have several options:
- check your graphics card driver;
- buy a new computer having a graphics card that supports opengl (it's very basic requirement);
- check the ckeckbox and just press ok, that should be easy.
