### ISSUE TITLE
[Feature request] Rearrange layers

### ISSUE THREAD

**Issue by Marriaga** [cnr-isti-vclab/meshlab#111]
I have two meshes (A and B), where B is a subset of A. 

When I load both of them and set the color of A to red and B to blue, I would like to have B "on top of" A. In other words, the areas where B is not in A show in red but the areas where both B and A exist show in blue.

Currently in Meshlab, the definition of which mesh is on top seems to be based on the loading order of  the meshes. Basically the first one to be loaded is the top-most mesh and shows completely.

As far as I understood there is no simple way of rearranging the meshes in MeshLab. Therefore, a simple Right-click>Move Layer Up/Down or a keyboard shortcut Ctrl+Arrow_Up/Down would be very convenient.

Best regards,
Miguel

**Comment by cignoni** [comment]
In MeshLab layer order is just syntactic. It should not have any impact on the rendering, like in the classical 2D drawing programs. The fact that you see one mesh or another one is a purely geometric issue.

**Comment by Marriaga** [comment]
I'm sorry to insist but it seems that Meshlab renders the meshes in the reverse order they are added, which means that, when two meshes overlap, only the first added is visible. I understand that maybe the case where this matters is so narrow that it doesn't justify a change, but it does affect the rendering.

**Comment by mcallieri** [comment]
partially true, meshlab renders the layers in the current order, and in the areas where two layers are EXACTLY COINCIDENT, the topmost layer appears "drawn on top" (possibly thanks to a GL_LESS in the depth test). However, this is a side effect of the rendering, and never intended as a feature (and may also disappear, as we work on the rendering). Moreover, layer order is not used in any of the filters. So, for the moment, we will not implement this feature, sorry.

**Comment by Marriaga** [comment]
Totally understandable. Thank you for your time and for an amazing software. Best regards!
