### ISSUE TITLE
CUDA accelerated reconstruction

### ISSUE THREAD

**Issue by eric-schleicher** [cnr-isti-vclab/meshlab#112]
Putting this here as a leading question/would be great feature request.   

Is there a practical implementation of this approach? 

"GPU-Accelerated 3D Surface Reconstruction using Gaussian Mixture Sampling and Sparse Voxel Lists"
- http://www.gputechconf.com/resources/poster-gallery/computer-vision-and-machine-vision

![image](https://user-images.githubusercontent.com/8261783/27517344-ce11aca2-597f-11e7-9eea-da02cdc1d788.png)

It would obviously be beneficial to any realtime meshing process, but also within a a tool like meshlab.  I'm finding that getting the right amount of detail in my clouds is taking much too long, even on powerful machines (single-threaded :( ).  something like this might be a great alternative to screen poisson reconstruction.  Not just for speed, but for mesh quality.

**Comment by mcallieri** [comment]
As far as I could see, there is no usable code we can use to build a filter.

**Comment by eric-schleicher** [comment]
I've been informed that some version of this will be released.  I'll update this issue when learn more.

**Comment by zhangxaochen** [comment]
@eric-schleicher is there any news on the release of your mentioned code? THX~

**Comment by eric-schleicher** [comment]
Hi @zhangxaochen  I've learned a bit about how the approach I refrenced works since I originally posted this.  Unfortunately i don't think it's would ever be applicable to unorganized point clouds ex-post-facto.   

The approach is similar to TSDF style approach where a flowing stream of depth information is used to create an underlying model of the volume, which can when be converted into a field of vertices and mesh (with marching cubes).   

I have heard that Nvidia plans on releasing some variation of the code, so that will be nice if you have a RGB-D (like a kinect) devices to provide the stream.

**Comment by eric-schleicher** [comment]
Oops I re-read the article.   it looks like this might someday be usefull on single frame point clouds.  leaving it open.

**Comment by zhangxaochen** [comment]
Thx for ur reply ;)
On what you 'heard', would you mind offering some links or keywords for me to search and read?
On you mentioned 'RGB-D (like a kinect) devices', I know the 'KinectFusion' algorithms a bit, such as the `Kinfu` open source implementation in PCL repo. Do you mean the same thing? I'm a bit confused if u say Nvidia plans to release some code on this algorithm. Where is this message from?

**Comment by Amir-Arsalan** [comment]
@eric-schleicher Any updates on this? Did they release the code somewhere?

**Comment by Amir-Arsalan** [comment]
@eric-schleicher Any updates on this? Did they release the code somewhere?
Or did someone else implement their method and release the code?
If the answer to both of the above questions is no, I wonder if you know any other point cloud to mesh reconstruction methods that do the job in real time whose implementation is available online?

**Comment by PerspectivesLab** [comment]
yes any update on this ? really interesting
