### ISSUE TITLE
add 'sudo apt install -y libcgal-qt5-dev'

### ISSUE THREAD

**Issue by RainbowRui** [cnr-isti-vclab/meshlab#1125]
OpenMesh is a fantastic work! Maybe the developers need to add 'sudo apt install -y libcgal-qt5-dev' command into 'scripts/Linux/0_setup_env_ubuntu.sh'. Because the users usually receive a warning that`"/usr/lib/x86_64-linux-gnu/libCGAL_Qt5.so.11.0.1" does not exist.` during running 'sh scripts/Linux/1_build.sh'.

OS system: Ubuntu 16.04
OpenMesh version: 2021.07

**Comment by alemuntoni** [comment]
Hi, ubuntu 16.04 is not supported anymore, and the module `cgal-qt5` is never used by our framework.
I don't know why this warning is shown, but it is a warning that does not make any sense here. 

By the way, this is MeshLab, not OpenMesh :)

**Comment by RainbowRui** [comment]
Thanks for your prompt response! Excuse me, it's a written mistake.
