### ISSUE TITLE
build.sh error 

### ISSUE THREAD

**Issue by abc619539082** [cnr-isti-vclab/meshlab#1139]
using meshlab on ubuntu18.04LTS
build error 'WithBraces' is not a member of 'QUuid'

/home/igrape/.local/share/Trash/files/meshlab/src/meshlabplugins/io_e57/io_e57.cpp: In member function ‘virtual void E57IOPlugin::save(const QString&, const QString&, MeshModel&, int, const RichParameterList&, bool (*)(int, const char*))’:
/home/igrape/.local/share/Trash/files/meshlab/src/meshlabplugins/io_e57/io_e57.cpp:260:59: error: ‘WithBraces’ is not a member of ‘QUuid’
     scanHeader.guid = QUuid::createUuid().toString(QUuid::WithBraces).toStdString();
                                                           ^~~~~~~~~~
meshlabplugins/io_e57/CMakeFiles/io_e57.dir/build.make:62: recipe for target 'meshlabplugins/io_e57/CMakeFiles/io_e57.dir/io_e57.cpp.o' failed
make[2]: *** [meshlabplugins/io_e57/CMakeFiles/io_e57.dir/io_e57.cpp.o] Error 1
CMakeFiles/Makefile2:1943: recipe for target 'meshlabplugins/io_e57/CMakeFiles/io_e57.dir/all' failed
make[1]: *** [meshlabplugins/io_e57/CMakeFiles/io_e57.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 73%] Building CXX object meshlabplugins/io_pdb/CMakeFiles/io_pdb.dir/io_pdb_autogen/mocs_compilation.cpp.o
[ 73%] Building CXX object meshlabplugins/io_json/CMakeFiles/io_json.dir/io_json_autogen/mocs_compilation.cpp.o
[ 73%] Building CXX object meshlabplugins/io_gltf/CMakeFiles/io_gltf.dir/gltf_loader.cpp.o
[ 73%] Linking CXX shared module ../../distrib/plugins/libio_pdb.so
[ 73%] Built target io_pdb
[ 73%] Building CXX object meshlabplugins/io_gltf/CMakeFiles/io_gltf.dir/io_gltf_autogen/mocs_compilation.cpp.o
[ 73%] Linking CXX shared module ../../distrib/plugins/libio_json.so
[ 73%] Built target io_json
[ 73%] Linking CXX shared module ../../distrib/plugins/libio_gltf.so
[ 73%] Built target io_gltf
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
[  8%] Built target copy-distrib-files
[  8%] Automatic MOC, UIC and RCC for target external-levmar
[  8%] Built target external-levmar_autogen
[  9%] Built target external-levmar
[  9%] Automatic MOC, UIC and RCC for target external-exif
[  9%] Built target external-exif_autogen
[  9%] Built target external-exif
[  9%] Automatic MOC, UIC and RCC for target external-glew
[  9%] Built target external-glew_autogen
[  9%] Built target external-glew
[  9%] Automatic MOC, UIC and RCC for target external-muparser
[  9%] Built target external-muparser_autogen
[ 10%] Built target external-muparser
[ 10%] Automatic MOC, UIC and RCC for target external-ssynth
[ 10%] Built target external-ssynth_autogen
[ 13%] Built target external-ssynth
[ 13%] Automatic MOC, UIC and RCC for target external-openctm
[ 13%] Built target external-openctm_autogen
[ 14%] Built target external-openctm
[ 15%] Automatic MOC, UIC and RCC for target external-qhull
[ 15%] Built target external-qhull_autogen
[ 16%] Built target external-qhull
[ 16%] Automatic MOC, UIC and RCC for target external-lib3ds
[ 16%] Built target external-lib3ds_autogen
[ 18%] Built target external-lib3ds
[ 18%] Automatic MOC, UIC and RCC for target IFXCore
[ 18%] Built target IFXCore_autogen
[ 40%] Built target IFXCore
[ 40%] Automatic MOC, UIC and RCC for target IFXCoreStatic
[ 40%] Built target IFXCoreStatic_autogen
[ 42%] Built target IFXCoreStatic
[ 42%] Automatic MOC, UIC and RCC for target IFXScheduling
[ 42%] Built target IFXScheduling_autogen
[ 45%] Built target IFXScheduling
[ 45%] Automatic MOC, UIC and RCC for target IFXExporting
[ 45%] Built target IFXExporting_autogen
[ 50%] Built target IFXExporting
[ 51%] Automatic MOC, UIC and RCC for target external-IDTFConverter
[ 51%] Built target external-IDTFConverter_autogen
[ 55%] Built target external-IDTFConverter
[ 55%] Automatic MOC, UIC and RCC for target meshlab-common
[ 55%] Built target meshlab-common_autogen
[ 59%] Built target meshlab-common
[ 59%] Automatic MOC, UIC and RCC for target meshlab
[ 59%] Built target meshlab_autogen
[ 61%] Built target meshlab
[ 61%] Automatic MOC, UIC and RCC for target io_3ds
[ 61%] Built target io_3ds_autogen
[ 62%] Built target io_3ds
[ 62%] Automatic MOC, UIC and RCC for target io_base
[ 62%] Built target io_base_autogen
[ 62%] Built target io_base
[ 62%] Automatic MOC, UIC and RCC for target io_bre
[ 62%] Built target io_bre_autogen
[ 63%] Built target io_bre
[ 63%] Automatic MOC, UIC and RCC for target io_collada
[ 63%] Built target io_collada_autogen
[ 63%] Built target io_collada
[ 63%] Automatic MOC, UIC and RCC for target io_ctm
[ 63%] Built target io_ctm_autogen
[ 63%] Built target io_ctm
[ 63%] Automatic MOC, UIC and RCC for target io_e57
[ 63%] Built target io_e57_autogen
[ 63%] Automatic MOC, UIC and RCC for target E57Format
[ 63%] Built target E57Format_autogen
[ 65%] Built target E57Format
[ 66%] Building CXX object meshlabplugins/io_e57/CMakeFiles/io_e57.dir/io_e57.cpp.o
/home/igrape/.local/share/Trash/files/meshlab/src/meshlabplugins/io_e57/io_e57.cpp: In member function ‘virtual void E57IOPlugin::save(const QString&, const QString&, MeshModel&, int, const RichParameterList&, bool (*)(int, const char*))’:
/home/igrape/.local/share/Trash/files/meshlab/src/meshlabplugins/io_e57/io_e57.cpp:260:59: error: ‘WithBraces’ is not a member of ‘QUuid’
     scanHeader.guid = QUuid::createUuid().toString(QUuid::WithBraces).toStdString();
                                                           ^~~~~~~~~~
meshlabplugins/io_e57/CMakeFiles/io_e57.dir/build.make:62: recipe for target 'meshlabplugins/io_e57/CMakeFiles/io_e57.dir/io_e57.cpp.o' failed
make[2]: *** [meshlabplugins/io_e57/CMakeFiles/io_e57.dir/io_e57.cpp.o] Error 1
CMakeFiles/Makefile2:1943: recipe for target 'meshlabplugins/io_e57/CMakeFiles/io_e57.dir/all' failed
make[1]: *** [meshlabplugins/io_e57/CMakeFiles/io_e57.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alemuntoni** [comment]
You've probably installed an old version of Qt. As stated [here](https://github.com/cnr-isti-vclab/meshlab/tree/master/src#readme), Qt >= 5.12 is required.
