### ISSUE TITLE
[BUG] program crash after certain input

### ISSUE THREAD

**Issue by ST6Daniel** [cnr-isti-vclab/meshlab#114]
1. Open meshlab
2. "file", "import mesh", then select an "obj." file
3. "file", "export mesh as", export as ".obj"
4. after "writing vertices" in bottom left corner disappeared, close the project (2nd "x" from top right corner)
5. click "file", then the "export mesh as" button will show up as clickable!
6. click that button, program crashes.

**Comment by cignoni** [comment]
Confirmed! Thanks!

**Comment by granzuglia** [comment]
fixed. thanks!
