### ISSUE TITLE
How to Give Shadow and Lighting to x,y,z Point Cloud PLY File?

### ISSUE THREAD

**Issue by ardianumam** [cnr-isti-vclab/meshlab#1146]
Hi,

I have a `ply` point cloud file (picture below), with 1024 points, each has x,y,z coordinate, and all rgb color info. When I open it using MeshLab, it looks plain, without any shadow and lighting. I try to enable shadow and lightning, but seems it cannot cast it. How can I do that so my `ply` file cab be more natural and has more sense of 3D object look?

Thanks! 
![image](https://user-images.githubusercontent.com/12822715/140597831-baaafe54-d92d-487c-847f-6cd87a549d67.png)

**Comment by Lionel-McCree** [comment]
I have the same problem with you.Have you solved it?

**Comment by cignoni** [comment]
For shading you need normals, so, if your point cloud does not have them you have to "Compute Normals for Point Sets" (e.g. use the filter with that name)

**Comment by Lionel-McCree** [comment]
You can use Easy3D for simple shadow like this.[https://github.com/LiangliangNan/Easy3D](url).  And as cignoni mentioned, if you need precise shadow for every point, you need normals.

**Comment by Lionel-McCree** [comment]
You can use Easy3D for simple shadow .[https://github.com/LiangliangNan/Easy3D](url), It can add a global light. And as cignoni mentioned, if you need precise shadow for every point, you need normals.
