### ISSUE TITLE
Couldn't find "Compute Geometric Measures" in the new version meshlab interface

### ISSUE THREAD

**Issue by QingkaiLu** [cnr-isti-vclab/meshlab#115]
In the old version meshlab,  "Filters->Quality Measure and Computations->Compute Geometric Measures" will compute the inertia. I couldn't find "Compute Geometric Measures" in the new version. Could anyone help? Thank you.

**Comment by mcallieri** [comment]
on which Operating System? because on Windows, I've just checked and it's in the usual submenu

**Comment by cignoni** [comment]
On osx too...

**Comment by QingkaiLu** [comment]
My system is ubuntu 14.04, this is how I installed the new version meshlab: https://sysads.co.uk/2014/06/16/install-meshlab-ubuntu-14-04/

**Comment by cignoni** [comment]
Ok, that distribution, (not done by us) has some issues. 
Use the snap package.
