### ISSUE TITLE
Meshlab from flatpak and Snap doesn't open smb mounts

### ISSUE THREAD

**Issue by adizhol** [cnr-isti-vclab/meshlab#1157]
Ubuntu 20.04
Meshlab 2021.10 and 2021.05

Path from mounted smb (cifs) share can't be opened (Meshlab says path doesn't exist)
Browsing to a mounted smb folder inside mershlab prompts doesn't show any files.

Works fine with AppImage

**Comment by alemuntoni** [comment]
That's probably an issue related to flatpak permissions. See [this issue](https://github.com/cnr-isti-vclab/meshlab/issues/1103).
