### ISSUE TITLE
point to mesh

### ISSUE THREAD

**Issue by jiandandian2** [cnr-isti-vclab/meshlab#1158]
#Please read carefully before submitting an issue

- be as detailed as possible while describing an issue:
  - which platform are you using (say it also on the subject of the issue)
  - which version of meshlab are you using (e.g. 2020.09 portable. 2020.06 snap, 2020.12 installer)
  - be sure that the issue is reproducible: list step by step all the operations performed to reproduce the issue
  - if it applies, share all the involved files
- if it is possible, verify if the problem persists in other platforms;
- be sure that your issue also happens on the most recent MeshLab version;
- check if your issue has been already reported by someone else. In this case, do not open another issue: just add your experience in the existing issue;
- delete these guidelines before submitting :)

If it is not an issue but something else (need help, feature request, ...) consider to use github discussion: https://github.com/cnr-isti-vclab/meshlab/discussions

Dear doctor, the first is the point cloud, and the second is the mesh(sample->ball pivoting).
I want to know how to move the first points' color to the second mesh?
hope your reply, very grateful!
<img width="2032" alt="屏幕快照 2021-11-19 下午9 42 33" src="https://user-images.githubusercontent.com/33227739/142633092-5ec0cea8-330e-4379-9745-fa3967a77ab3.png">
point cloud
<img width="2032" alt="屏幕快照 2021-11-19 下午9 42 37" src="https://user-images.githubusercontent.com/33227739/142633108-34cca02c-0972-4380-ad04-dffc6299346f.png">
mesh

**Comment by alemuntoni** [comment]
You can use the Filter:
Sampling -> Vertex Attribute Transfer
be sure to select the right meshes and transfer the color.
