### ISSUE TITLE
Crash importing a particular OBJ file

### ISSUE THREAD

**Issue by kring** [cnr-isti-vclab/meshlab#116]
1. Download the Dabrovic Sponza mesh from http://graphics.cs.williams.edu/data/meshes.xml.  Direct download link: http://graphics.cs.williams.edu/data/meshes/dabrovic-sponza.zip
2. Extract it somewhere on your system.
3. Launch MeshLab and choose File -> Import Mesh.
4. Select the extracted sponza.obj.
5. MeshLab loads the mesh for a few seconds and then crashes.

![image](https://cloud.githubusercontent.com/assets/924374/24189586/b214c254-0f39-11e7-8e0a-8980bef90ab6.png)

This is MeshLab 2016.12 64-bit on an up-to-date Windows 10 system.

This mesh loads just fine in Meshlab v1.3.3 on the same system.

**Comment by kring** [comment]
Here's the call stack according to Visual Studio (though I doubt it's much use without symbols):
![image](https://cloud.githubusercontent.com/assets/924374/24189848/b1683b8c-0f3a-11e7-9fe4-a7682f2ec142.png)

Visual Studio also reports that the error is:
`Unhandled exception at 0x00007FF661758663 in meshlab.exe: 0xC0000005: Access violation reading location 0x0000026A36D1C01C.`

**Comment by kring** [comment]
Another mesh on that same page (the [Conference Room](http://graphics.cs.williams.edu/data/meshes/conference.zip)) loads successfully.  But then if I go to `Filters -> Remeshing, Simplification and Reconstruction -> Simplification: Quadric Edge Collapse Decimation`, leave default settings and click Apply, the Simplifying progress bar gets all the way to 100% and then MeshLab crashes with a very similar callstack to the one above.

**Comment by mcallieri** [comment]
I believe it is the same issue of #91 that is due to an inconsistent texture mapping (some triangles have texture, some other does not).
We are trying to fix it.
However, these are NOT really 3d models, they are multi-object scenes, which are somehow borderline, considering the MeshLab architecture of (1 file -> 1 object) :). 
Finally, as the geometry has texture mapping, you should use the Quadric Edge Collapse Decimation (with texture) variant. It still crashes now, because of the inconsistency we need to fix, but this variant try to preserve mapping. If you do not need mapping, just export the layer without saving the UV mapping, and re-load the new mesh, without it.

**Comment by kring** [comment]
Thanks @mcallieri!

For what it's worth, I've been unable to use the "with texture" variant of Quadric Edge Collapse Decimation with models like this in the past for exactly the reason you mentioned: the mesh has textures for some triangles but not others, and so the "with texture" filter refuses to run.  On the other hand, the non-texture Quadric Edge Collapse Decimation appears to work fine (at least in v1.3.3) and does at least a passable job of preserving texture mapping.  It could be I just don't know what I'm missing!

**Comment by jpryne** [comment]
I'm crashing immediately upon clicking "Import mesh" without so much as selecting a file.

**Comment by mcallieri** [comment]
@jpryne let me guess... you have a DELL laptop. If so, there is an incompatibility of QT with a DELL backup software... http://en.community.dell.com/support-forums/software-os/f/3526/t/19634253
This is the only case in which we have encountered a crash as soon as you try to import/export a mesh.

**Comment by jpryne** [comment]
Almost. I have a Dell desktop. Is there a workaround?

**Comment by jpryne** [comment]
Ah, apologies, I found the workaround in the thread you kindly provided.
Best wishes-

**Comment by mcallieri** [comment]
I hope is the same issue for you. It is an amazing bug, looks like black magic, and it is impossible to debug. Luckily, searching for some keywords, I found a forum where people were describing this exact issue (not about MeshLab, but another tool).

**Comment by jpryne** [comment]
I went into Visual Studio to debug, but it was way over my head, lol.

I uninstalled DBAR, and am up and running in Meshlab. Thanks very much for
your help! Grazie molto!
