### ISSUE TITLE
Issue with crashing when I try to downscale polygons by any ammount?

### ISSUE THREAD

**Issue by randompersononline** [cnr-isti-vclab/meshlab#1162]
Hello, My Windows 10 x64 Meshlab version (the newest, just downloaded the software) is crashing every time I try to downscale the mesh by any amount. My mesh has 46518 faces and even when I try to change it to 46517, my software crashes. Please help!
[https://drive.google.com/file/d/1EGYAzgfJmY7rn-6r8kwCIPNwcJzTH89B/view?usp=sharing](url) is the link to the file I am trying to downscale)

(my bad, problem fixed, sorry if I bothered anyone)

**Comment by cignoni** [comment]
as user reported.
