### ISSUE TITLE
Repair non manifold edges does not work or unable to save

### ISSUE THREAD

**Issue by GiovanniSer** [cnr-isti-vclab/meshlab#1164]
WIN 10 and ML 21.10
I load the STL file.
Re-orient faces coherentely does not want to work because I have some non manifold edges.
I repair the edges splitting vertices (ok).
Now, "Re-orient faces coherentely" seems to work.
Ok, I save the STL.
I close it then I reopen it.
Again Re-orient faces coherentely does not work because I have some non manifold edges ...
I repair the edges splitting vertices.. (ok).
Now "Re-orient faces coherentely" works.
I save the STL.
I close it then I reopen it.....
Again Re-orient faces coherentely does not work because I have some non manifold edges.....
It is impossible to understand if the repair, and the normalize, fail... or the "save" does not save the repair item
Thanks!
[SenzaTitolo.zip](https://github.com/cnr-isti-vclab/meshlab/files/7608794/SenzaTitolo.zip)

**Comment by alemuntoni** [comment]
There is no bug here. STL saves data as a triangle soup (each triangle has its own vertices), and when importing and unifying vertices it is possible that issues happen, and this seem to be the case... Just don't use STL format for saving temporary meshes that need more processing in meshlab, it is not the proper format to do that.
