### ISSUE TITLE
Qt version - building from source

### ISSUE THREAD

**Issue by liushuya7** [cnr-isti-vclab/meshlab#1171]
Hi,

Does Meshlab build with Qt6?
Ubuntu 20.04 still comes with Qt 5.12. Why is the minimum supported Qt version changed to 5.15?
https://github.com/cnr-isti-vclab/meshlab/blob/d9d9ed105c07cda524e0e5d17506fafdf680160f/src/CMakeLists.txt#L31

**Comment by alemuntoni** [comment]
Right now it does not build with Qt6, but we plan to migrate to Qt6 in the future.
For this reason, we are slowly upgrading to newer versions of Qt. 
Right now some portions of codebase do not build with Qt 5.12 anymore, and we cannot support simultaneously multiple versions of Qt.
