### ISSUE TITLE
Meshlab crashing when importing models (Windows 10)

### ISSUE THREAD

**Issue by rfs5052** [cnr-isti-vclab/meshlab#1175]
Ok, so I can't even get Meshlab to stay open when I try accessing my models. I go into the import window, and the moment I hover my mouse over one of my models in my model folder, Meshlab crashes instantly. This happens every time I try to access my models to import. There is no error code, it just crashes to desktop.

I'm using the latest version 2021.10

I'm running Windows 10 64-bit

My specs are: 
Intel i7-7700k CPU
32 GB of 2400Mhz RAM
500 GB SSD C drive, default install location
Models stored on secondary 1 TB SSD
RTX 3060 Ti  8GB GPU, latest driver as of 12/20/21

I don't see an error log to upload anywhere in the install folder.

**Comment by alemuntoni** [comment]
Hi, sorry for the issue. I never experienced an issue like this before, it could be something related to drivers or system.. It's very hard to tell. Did you experience the same issue also with previous versions of meshlab? Does this happen also with the [portable version](https://github.com/cnr-isti-vclab/meshlab/releases)?

**Comment by alemuntoni** [comment]
If he is using an official release, there should be no issues related with antiviruses.
We are regularly signing all our official releases with certificates that are trusted by microsoft. 
If it is not an official release but a nightly version, then the antivirus could cause this issue since nightly versions are not signed.

**Comment by GiovanniSer** [comment]
Yes, but I suppose this because win has often bugs, not because ML may have incorrect procedures.
In fact, it does not seem to be a warning, but the program closes.
I never had a crash, but by excluding certain folders I have solved waiting times so long as to be unjustified.

**Comment by matches30** [comment]
I have just started having this or similar issue with Meshlab... opens fine, click import, dialog comes up... as soon as I click ONLY on DESKTOP, CTD. Any help please? This is one of my most valued programs!

**Comment by chameroy** [comment]
I am also experiencing crashing when attempting to import a GLB file.

**Comment by pclausen** [comment]
I have the same problem, MeshLab crashes on import of glb file. Version: 2022.02

I attached a glb file: 
[bunny.zip](https://github.com/cnr-isti-vclab/meshlab/files/10324853/bunny.zip)

I created the glb file with python library [trimesh](trimesh.org)

`
import trimesh 
tri = trimesh.import('bunny.obj')
tri.export('bunny.glb')`

The exported glb file renders fine on
https://3dviewer.net/

so to me this looks like a MeshLab problem
Original obj file:

[bunny.obj.zip](https://github.com/cnr-isti-vclab/meshlab/files/10324857/bunny.obj.zip)

**Comment by pclausen** [comment]
@alemuntoni Are you able to reproduce on your side with [bunny.zip](https://github.com/cnr-isti-vclab/meshlab/files/10324853/bunny.zip) ? If yes, could you reopen the issue ?

**Comment by matches30** [comment]
yes, it crashed when it tried to load bunny

**Comment by GiovanniSer** [comment]
Win 11 Bunny error (reading normals?) and ML crash.
Bunny is loaded fine on MS 3D Viewer. I saved a Bunny2.qlb by MS but it fails again in ML.

**Comment by matches30** [comment]
I think this is something to do with Windows, cause this happens with more
programs now :( Every time I load or save anything to DESKTOP, programs
crash... strange and very annoying!

**Comment by GiovanniSer** [comment]
but bunny.qlb works fine here
 https://products.aspose.app/3d/it/viewer/glb
 and here
 https://imagetostl.com/it/visualizza-glb-online

**Comment by chris838** [comment]
Same problem - crashes on importing bunny.glb. Tried on Windows and MacOS, exactly the same issue.

**Comment by palferenc** [comment]
Same problem on Ubuntu 20.04 with Linux App Image MeshLab2022.02.
Older version (MeshLab2021.10) works fine.
