### ISSUE TITLE
Cylindrical Unwrapping only leads to bulging 

### ISSUE THREAD

**Issue by Askanderre** [cnr-isti-vclab/meshlab#1176]
Good Evening (at my time zone).

I know that I am not often posting here but I have realized a issue with the Unwrapping function. I tried to use Meshlab 2020.07, 2021.10 and because last time I tried and it worked I used a older version 2016.12. I am using Windwos 10 x64.

I have an evenly round vessel that I would like to unroll. But when I try to do so with the Geometric Cylindrical Unwrapping function its not unrolling but relocated a bit to the front and much to the left and it bulges forward in the direction of the Z-axis and backwards at 45 degrees to the left and right. I prepared some pictures which I attached to this post that you see what I am actual descriping.... :D 

Can you help me what I am doing wrong? I tried File formats in PLY and OBJ but but didn't work.

Tnx in advance!

Alex

![Original](https://user-images.githubusercontent.com/22260642/146816030-dd1edad4-b5c2-4531-8609-d76e3ff34d7d.png)
![Unwraped](https://user-images.githubusercontent.com/22260642/146816039-63dc5d82-df7e-4c66-b602-c270580c1690.png)
![Relocation](https://user-images.githubusercontent.com/22260642/146816037-6ef9025a-418a-4f06-ae10-8ee5f6e17236.png)

**Comment by alemuntoni** [comment]
Hi, sorry for the late reply. Could you please share the model you are using, to help us understanding what's going on?
Is your mesh centered in the origin? The filter of the cylindrical unwrapping it is not much flexible...
