### ISSUE TITLE
Planar cut with "Compute Planar Section".

### ISSUE THREAD

**Issue by bartoszek** [cnr-isti-vclab/meshlab#118]
Wold be useful to have additional option in `Compute Planar Section` to leave geometry on on side of a plane and than reconnect it with section result. This way you can have clean cut of non-manifold meshes, witch can't be achieved with `CSG Operations`.

**Comment by mcallieri** [comment]
yes, it would. However, we are, at the moment, not even clipping the triangles, we just compute the intersection with the plane, and use it to create the section.
A proper boolean (and clipping) filter is missing, we know, but we have no suitable code to make one. Most of the available libraries simply do not work on complex geometries, or produce too many topologicla errors :(

**Comment by cignoni** [comment]
Implemented mesh splitting by a plane in commit cf8270cc9d87301ea49d2b775b9695d70b8eea95 
Added an option that if selected, it will create two layers with the portion of the mesh
under and over the section plane. It requires manifoldness of the mesh
