### ISSUE TITLE
Meshlab and precision

### ISSUE THREAD

**Issue by oleg-alexandrov** [cnr-isti-vclab/meshlab#1188]
I got bitten, like many other people as it appears from the issues, by the fact that the default Meshlab operates in single-precision.

I see that a double-precision version is offered. Come on, people it is 2022. I think the double-precision version should be the default. Computational geometry is hard enough without having to worry about getting junk results because of precision loss. 

And while here, one should use int_64_t instead of int (which is 32 bit) for indices. If you take a 50,000 x  50,000 pixel Digital Terrain Model, which is not much nowadays, and make a surface mesh out of it, so each grid cell is split into two triangles, you will overflow 32 bit int. 

So, in code like here: https://github.com/cnr-isti-vclab/meshlab/blob/0d77cf84a90b291bea0251d8eeb48f7996f76c38/src/external/libigl-2.3.0/include/igl/readOBJ.cpp#L307

one should use std::vector<int64_t>. Also instead of Eigen::MatrixXi one should use the version with int64_t values when reading obj files.

**Comment by alemuntoni** [comment]
@oleg-alexandrov, yes, it's 2022 but the double precision version of MeshLab was firstly released just one year ago, as a *beta*.
The entire codebase of MeshLab and VCG has been developed in the last 20 years and more taking into account just floats, mostly. You can imagine that making sure that everything works also with double precision is not an easy task. Our resources are limited.

You are free to use the double precision version (we released it for this reason), and maybe you could help by reporting if there are different behaviors between float and double precision (or, better, send pull requests).

BTW, the portion of code you linked is from the external library libigl. We don't use libigl to read obj files.

**Comment by oleg-alexandrov** [comment]
I do understand about limited resources, and it is nice to know that MeshLab is continuously maintained (at my lab the funding can be sporadic and there can be many months of no work on some things including bugs because funding only for other things exist). 

Good to know the double precision version of MeshLab is making progress.  For obj files, in particular, the float format is a serious limitation when it comes storing vt, which is textureVertex/imageSize. MeshLab in the float version was not displaying an obj file correctly for big imageSize, say 300,000, even when the obj file was saved in double precision. This will go away once the double precision version of meshlab is the default.

And I am sure at some point you folks will run into overflow of int, which is 32 bit even on 64 bit system. A mesh of the surface (not volume!) of a cube 10 m x 10 m x 10 m, at 1 mm/pixel, which is big, but not outrageous, with RGBA values, can result in an image whose size (in bytes) is bigger than the biggest int32. Even if you reader is not what I saw in libigl, an Eigen::MatrixXi which i saw Meshlab uses, may still overflow. 

These are longer-terms issues, of course. Thank you for reading.
