### ISSUE TITLE
Cannot run mlx scripts either on Linux, Windows, or MacOS

### ISSUE THREAD

**Issue by mpottinger** [cnr-isti-vclab/meshlab#1189]
Hello, I am wondering if anyone else is finding it impossible to run mlx scripts. I have tried scripts included in other software I was trying to run, and also just simple scripts created in meshlab itself. Nothing will run. Meshlab just segfaults. This is both on the latest version of Meshlab and any other version I tried. Doesn't matter if it's on my PC on Windows, on Linux, or on my M1 Mac. All segfault on any attempt to run a script.

**Comment by mpottinger** [comment]
Solved this by using pymeshlab instead of mlx for scripting. lol.
Maybe the menu should be disabled in meshlab.

**Comment by alemuntoni** [comment]
Hi, I actually cannot replicate your issue. 
I tested mlx scripts with few filters and they work as expected. Are you using a specific filter? Maybe is a specific one that is causing the crash

**Comment by mpottinger** [comment]
Strange. This was happening on all platforms for me and I swear I tried even a blank script, or creating a new script in the application itself. In any case I find pymeshlab works nicely and it was easy to convert the script to that.

The script was from the mesh-fusion github repo:
[https://github.com/weders/mesh-fusion/blob/c2638dda2a7b240807be83f028eacc3cd498c3ef/simplification.mlx](url)

<!DOCTYPE FilterScript>
<FilterScript>
 <filter name="Quadric Edge Collapse Decimation">
  <Param type="RichInt" value="5000" name="TargetFaceNum"/>
  <Param type="RichFloat" value="0" name="TargetPerc"/>
  <Param type="RichFloat" value="0.5" name="QualityThr"/>
  <Param type="RichBool" value="false" name="PreserveBoundary"/>
  <Param type="RichFloat" value="1" name="BoundaryWeight"/>
  <Param type="RichBool" value="true" name="PreserveNormal"/>
  <Param type="RichBool" value="false" name="PreserveTopology"/>
  <Param type="RichBool" value="true" name="OptimalPlacement"/>
  <Param type="RichBool" value="true" name="PlanarQuadric"/>
  <Param type="RichBool" value="false" name="QualityWeight"/>
  <Param type="RichBool" value="true" name="AutoClean"/>
  <Param type="RichBool" value="false" name="Selected"/>
 </filter>
</FilterScript>

**Comment by alemuntoni** [comment]
Oh, these are really old mlx scripts. Lot of things changed in meshlab since 2018 (like replaced filters and changed parameters)..

**Comment by mpottinger** [comment]
Ok thank you for looking at it, I think I'll close this issue. I've seen documentation recommending pymeshlab anyway.
