### ISSUE TITLE
Inerface  translation to other languages

### ISSUE THREAD

**Issue by slichtzzz** [cnr-isti-vclab/meshlab#1196]
I couldn't find if there is an application interface translation to other languages, even though the translation is built-in, like in the example code below (from mainwindow_Init.cpp):

 appendProjectAct = new QAction(tr("Append project to current..."), this);

But I cannot find the translation files. I mean the *.ts ones. Does it mean that interface translation is not considered for implementation?

**Comment by alemuntoni** [comment]
Hi, there is a small support for translation in some parts of meshlab, but it is not homogeneous. 
But in the end there never was a translation to other languages, and I don't think there should be one given the context on which meshlab is used.

**Comment by slichtzzz** [comment]
Hi! Thank you for your reasoned reply! The interface should be kept in English then. Wish you further creative achievements!

**Comment by windtring-max** [comment]
MeshLab Chinese translation qm download

**Comment by windtring-max** [comment]
MeshLab zh_CN qm free download
