### ISSUE TITLE
Hardware requirements for opening large files

### ISSUE THREAD

**Issue by StephanRavel** [cnr-isti-vclab/meshlab#1197]
Hello everyone, I installed Meshlab 64bit v2021.10
I 'd like to know what are the recommended hardware requirements for opening big files on this Meshlab version. 

In fact, I imported an .OBJ file. This one was approximately 700Mo. 
It worked but the navigation was too slugish. So it is impossible to work with it.

FYI, about my laptop : 
- OS: Windows10
- Processor : Intel Core i5-6200U CPU @ 2.3GHz
- Memory: 20Go
- GPU:  Intel HD Graphics 520

My questions are: 
- Could you please give me more infos about the hardware requirements ? 
- Is Meshlab even able to handle files that large ? 
- Any other open source / free software to handle that ?

Thank you in advance
Regards

**Comment by alemuntoni** [comment]
Meshlab is able to handle even larger files, but of course proper hardware is required. Your graphic card it is not great for this kind of purpose.
"Hardware requirements" do not have much sense if we consider just meshlab: it depends on the size of the rendered geometry. MeshLab itself is able to run easily also on old graphic cards, but of course it is able to render smoothly only geometries of limited size (that depend on the graphic card).
