### ISSUE TITLE
Operator dialog appears on different monitor.

### ISSUE THREAD

**Issue by will-ca** [cnr-isti-vclab/meshlab#1201]
**Platform:** Linux/GNOME.
**Version:** FlatPak `net.meshlab.MeshLab` `2021.10`

MeshLab seems to open its operator dialog windows in the top left corner of the screen.

In my case, that means it appears on my secondary monitor, quite literally as far away from the main MeshLab window as possible.

If possible, setting popup window position relative to main window position would probably be better.

**Comment by alemuntoni** [comment]
Fixed, it will be available in the next release! Thanks for reporting!
