### ISSUE TITLE
Inefficient usage of parallelism in Poisson surface reconstruction

### ISSUE THREAD

**Issue by mgrewe** [cnr-isti-vclab/meshlab#1206]
Hi folks,

the Poisson surface reconstruction is inefficient when working on systems with many cores under heavy load. Especially when running multiple surface reconstructions in parallel, the scaling is horrible. E.g., with only 3 parallel processes, I got a performance drop of a factor of 10 or more! 
I suspect this is due to the usage of OMP. Unfortunately, I can not adjust the number of threads from outside, e.g., using the env var OMP_NUM_THREADS. Instead, Meshlab just determines the value itself from the number of cores.

Do you see any chance of changing the behavior, either by respecting the environment vars or by adding another parameter to the filter's dialog?

Thanks for consideration and Cheers!

**Comment by mgrewe** [comment]
Actually, I just found a way to adjust the number of cores, at least in Linux. One can use sched_setaffinity system call. It is exposed to the Python world via the os module. So if you are using pymeshlab, you can do something like this:

```
import os
os.sched_setaffinity(0, [0,1,2,3]) #The list determines the cores to use, i.e., the first 4 cores in this case.
```

This workaround dramatically reduced the computation time for me. 

Hope that helps. Cheers.

**Comment by mgrewe** [comment]
Wohoo, that was quick. Thanks a lot! When is it expected to be available in pymeshlab?

**Comment by alemuntoni** [comment]
There was a number threads parameter in the screened poisson algorithm, therefore the fix to this was quite easy.
I just exposed the parameter to the filter dialog, and now the user can choose the number of threads!

**Comment by alemuntoni** [comment]
> Wohoo, that was quick. Thanks a lot! When is it expected to be available in pymeshlab?

in a few days, actually. We are going to release new versions of meshlab and pymeshlab soon!

**Comment by mgrewe** [comment]
Great. I owe you a coffee!
