### ISSUE TITLE
"Select faces by view angle" "Get" button gets normal instead of position

### ISSUE THREAD

**Issue by nh2** [cnr-isti-vclab/meshlab#1207]
In `Select faces by view angle`:

![image](https://user-images.githubusercontent.com/399535/154059442-71d549c8-b35a-437f-92bd-2590de4f1395.png)

in the `ViewPoint` column there is a `Get` button.

But it doesn't, as expected, fill in the current _position_ of the camera into `ViewPoint`; instead, it fills in the current view angle as a normal.

I think this doesn't make sense, because the filter quite evidently operates on the thing in `ViewPoint` being a position. This can be easily checked by just scaling the values that "Get" puts in by a constant, and observing that different faces are selected.

I think the `Get` button should fill in the position.

**Comment by nh2** [comment]
Suspicion:

https://github.com/cnr-isti-vclab/meshlab/blob/cac36d7e01d5731fdbfbd55153b61bbd916ae280/src/meshlabplugins/filter_select/meshselect.cpp#L301-L305

should not be `RichDirection` but `RichDirection`.

**Comment by nh2** [comment]
I suspect that this is a regression introduced by:

https://github.com/cnr-isti-vclab/meshlab/commit/8b490fc2e8e7d99a0b33c81512cfd09b8015ceb4#diff-538cc8d0524f530596db0ca99c1cc74552152a1b1fd584a324524383804008adR185

from PR #1084

**Comment by alemuntoni** [comment]
Yes, you are right. When introducing the distinction between direction and position parameters, I just set the wrong parameter type for that filter. Sorry about that!
And thanks for the PR!!

**Comment by nh2** [comment]
Currently testing, will submit a PR in a moment.

**Comment by nh2** [comment]
Yes, the fix works. PR: #1208
