### ISSUE TITLE
LoadLibrary Failed with Error 87: The parameter is incorrect.

### ISSUE THREAD

**Issue by gchoquet** [cnr-isti-vclab/meshlab#1210]
#Please read carefully before submitting an issue
Clean install with version meshlab2021.10 on windows 64. 

Error occurs when attempting to run the application for the first time after the install.

**Comment by alemuntoni** [comment]
Hard to understand what's going on. 
However, after a quick google search it seems that there is something wrong in your system: https://support.esri.com/en/technical-article/000020069
