### ISSUE TITLE
How to display the triangle mesh and cameras in Meshlab?

### ISSUE THREAD

**Issue by XYZ-qiyh** [cnr-isti-vclab/meshlab#1219]
Now I have the triangle mesh which is reconstructed from multi-view images (COLMAP + Poisson Surface Recon). Is there a way to display the triangle mesh as well as the camera positions in Meshlab? The format of the camera pose is [**R** | **t**] (rotation matrix and translation vector).

**Note**: COLMAP could display the sparse model and the camera positions, but it cannot display the triangle mesh model.

Looking forward to your reply. Many thanks!

**Comment by no1nemo** [comment]
Did you get any progress with this? @XYZ-qiyh

**Comment by XYZ-qiyh** [comment]
> Did you get any progress with this? @XYZ-qiyh

Not yet.

**Comment by no1nemo** [comment]
Would you mind sharing what you've tried so far?

**Comment by XYZ-qiyh** [comment]
Hello, @no1nemo 
I want to show the results of the multi-view 3D reconstruction pipeline (i.e. input images, sparse points by SfM, dense points by MVS, and the final mesh).
So, the visualization of the camera and mesh is optional for me.
