### ISSUE TITLE
Mac download link from https://www.meshlab.net/#download does not work

### ISSUE THREAD

**Issue by habi** [cnr-isti-vclab/meshlab#1220]
The MacOS download link on https://www.meshlab.net/#download points to 
https://github.com/cnr-isti-vclab/meshlab/releases/download/Meshlab-2022.02/MeshLab2022.02-macos.dmg, which does not work.
The correct link has a capital L: https://github.com/cnr-isti-vclab/meshlab/releases/download/MeshLab-2022.02/MeshLab2022.02-macos.dmg

I couldn't find where the code of the website lives, otherwise I'd have submitted a PR...

**Comment by habi** [comment]
This also means that MeshLab can't be installed via `brew`: https://formulae.brew.sh/cask/meshlab

**Comment by alemuntoni** [comment]
Thanks for reporting! I just fixed all the links of the website!
