### ISSUE TITLE
Meshlab crashes in Windows 7 Professional 64 bit

### ISSUE THREAD

**Issue by JerryTreich** [cnr-isti-vclab/meshlab#1222]
Hello, 
  - I am running Windows 7 Professional 64 bit, 8.00 GB RAM, Intel Core2 Quad CPU Q6600 @ 2.40 GHz with AMD Radeon HD 6670 and Triple Buffering of Open GL3D.
  - I am using Meshlab  2022.02d-windows.exe
  -  I have reinstalled Microsoft Visual C++ (vc_redist.x64.exe).  Have reinstalled all versions of "MSVCP140.dll).  Installation of Meshlab results in Application Error Message:  The application was unable to start correctly (0xc000007b). Click OK to close the application.
 - I don't know which files in the installation might be useful to share.
-  I have the identical problem / error message on the Windows 10 Professional 64 bit platform running on the same computer (separate boot partition).
- This is the most current MeshLab version.  I cannot find earlier versions to download that might be more suitable for my system / platforms.
-  I cannot find a solution for this issue or that this specific error has been reported by anyone else.

**Comment by GiovanniSer** [comment]
For me (win 10) the first ML 2022 run fine, anyway ...
https://github.com/cnr-isti-vclab/meshlab/releases/tag/Meshlab-2021.07

**Comment by GiovanniSer** [comment]
sorry ... 
the parent page
https://github.com/cnr-isti-vclab/meshlab/releases

**Comment by alemuntoni** [comment]
Hi, you can refer to the [release page](https://github.com/cnr-isti-vclab/meshlab/releases) for previous download versions.
Right now Windows 7 is not supported anymore by microsoft, and I cannot be sure that MeshLab will run on that platform, considering also that github actions recently switched to Visual Studio 2022.
Moreover, googling 0xc000007b it seems that is a common error that appears when something is wrong with graphic drivers on the system.
Please, try 2021.07 version on the Windows 10 platform and let me know if it works.

**Comment by JerryTreich** [comment]
Hello Mr. Muntoni,

My apologies for taking so long to reply.  I had hip replacement surgery in April and today is the first opportunity I have had to try your suggestion of using the 2021.07 version.  I am happy to report that I successfully installed, rand and opened / imported a .stl file in that version of Meshlab!  Thank you for your insight.

Best regards –

Jerry Treich
