### ISSUE TITLE
Filter Failure: no RichParameterList

### ISSUE THREAD

**Issue by Omni-Moulage** [cnr-isti-vclab/meshlab#1224]
Hello, 
In order to create a "Voronoi" pattern on an existing 3D model, I followed several tutorials that require the "Select by Vertex quality" function.
Unfortunately, I get an error message about "No parameters with name Inclusive found in RichParameterList.
I couldn't find any help on the internet.
Could you help me please ?

Meshlab version:  2022.02
Windows 11 professional
Computer: AMD Ryzen 9 3950X , 128GO Ram
Graphic card: Nvidia Geforce RTX 3060 Ti
![RichParameterList-Issue](https://user-images.githubusercontent.com/86853216/158744747-b839d1e7-143c-49a9-9961-b4064de5b2b2.png)

**Comment by Omni-Moulage** [comment]
Hi, thank you for this prompt answer. 
So I download the latest nightly build but unfortunately I received another issue message about missing plugins.
Does I forget something during the installation 
![plugins issue](https://user-images.githubusercontent.com/86853216/159629815-0c1ff5a1-623d-463e-8288-a284376f63e8.png)
?

**Comment by alemuntoni** [comment]
You probably downloaded a version generated from another branch. Please be sure to download the last nightly version generated from the `master` branch.

**Comment by Omni-Moulage** [comment]
You are right, now that works. Thank you very much.

**Comment by PMDevine1** [comment]
I'm seeing this problem in Pymeshlab as well. Is there a way to get the nightly updates in pymeshlab?

**Comment by alemuntoni** [comment]
Yes, there is also a wiki to download the last nightly of pymeshlab: https://github.com/cnr-isti-vclab/PyMeshLab/wiki/How-to-install-the-last-nightly-version

**Comment by alemuntoni** [comment]
I still don't know when we will be able to release the next version of meshlab. 
I'll try to make a 2022.02 post release soon, having only bugfixes and no new features.

**Comment by reynoldscem** [comment]
Any luck on getting a release out including this?
