### ISSUE TITLE
Feature request - filter to set layer visiblity

### ISSUE THREAD

**Issue by 3DLIRIOUS** [cnr-isti-vclab/meshlab#123]
It would be helpful to have a filter to set and/or toggle the layer visibility. This would primarily be useful for meshlabserver. There are many filters (such as Flatten Visible Layers) that have the option to operate only on visible layers, however there is currently no way to set the layer visibility from meshlabserver. It would be nice to be able to explicitly set the visibility of a specified layer (or the current layer), and also to toggle the visibility of the current layer, a specified layer, or all layers.

**Comment by cignoni** [comment]
Done. Thanks for the suggestion!
