### ISSUE TITLE
Simplifying a 9 million object with Quadric edge collapse decimation - OS X 10.15.7

### ISSUE THREAD

**Issue by rikkkkkkka** [cnr-isti-vclab/meshlab#1235]
Thanks for the great work on Meshlab.

I'm new on Meshlab and I'm posting a question about user experience, hoping it doesn't be out of topic here.

I'm trying to reduce a polygon count from a 9 million polygon object to 100.000 poly, using the Quadric edge collapse decimation. Preview works smooth and well, doing a great job, but when I try to export to obj Meshlab freezes, starting to accumulate ram until reaches the machine ram and SSD limit capacity (450GB) then go to pause and stuck.
Am I doing something wrong, missing something or is too big my object?

Version : MeshLab2022.02-macos

Please help .)
Thank you in advance

**Comment by alemuntoni** [comment]
Hi, sorry for the late reply.
It is definitely a meshlab bug! Could you please share in some way the file that causes the issue?

**Comment by maxmadzz** [comment]
I have the same question, I can provide documents
After this operation, the export file will trigger this problem.
<img width="399" alt="QQ20221023-112452@2x" src="https://user-images.githubusercontent.com/32274609/197371960-193e3fc0-5032-40da-a91c-c9847f2158a2.png">
[sample.obj.zip](https://github.com/cnr-isti-vclab/meshlab/files/9845717/sample.obj.zip)
