### ISSUE TITLE
Transfer Color: Texture to Vertex does not support multiple textures

### ISSUE THREAD

**Issue by 3DLIRIOUS** [cnr-isti-vclab/meshlab#124]
The filter "Transfer Color: Texture to Vertex" does not appear to support multiple textures on a single model; only one texture is transferred. A simple dual texture sample file is attached for testing purposes. Interestingly, the filter "Transfer: Texture to Vertex Color (1 or 2 meshes)" seems to work correctly. On that note, since the latter filter now supports operating on a single mesh, is the former filter still needed?

[sphere_2_texture.zip](https://github.com/cnr-isti-vclab/meshlab/files/901744/sphere_2_texture.zip)

**Comment by mcallieri** [comment]
oh, sorry, my fault. 
I found and corrected the bug in the multi-layer version, and not the same-layer version. I'll do it soon.
as far as removing the single-layer version, I am not sure, the single.layer version is definetely more stable and faster, and possibly even more precise. I'll see if it's the case.

**Comment by mcallieri** [comment]
should be corrected. now.
