### ISSUE TITLE
Meshlab does not run on 3090 RTX

### ISSUE THREAD

**Issue by blakejrobinson** [cnr-isti-vclab/meshlab#1247]
Meshlab will not start on a Windows 10, 3090 RTX with the latest NVIDIA drivers.

The program encounters a critical error when run:
Error: GLEW initialization failed: Missing GL version

![image](https://user-images.githubusercontent.com/9593019/164274192-d01fac06-d421-49af-be6a-bd01a799f510.png)

Using CPU OpenGL mode does not seem to fix this.

- Windows 10 21H2
- Nvidia 3090 RTX
- Nvidia drivers 512.15
- Other OpenGL applications work fine.

**Comment by blakejrobinson** [comment]
Apologies. I tried to solve this for hours (and then noticed some other QT OpenGL applications weren't actually working).

A reformat of my machine fixed this problem. Now working fine on 3090 RTX.

**Comment by alemuntoni** [comment]
Great! Thanks!
