### ISSUE TITLE
Grid Generator creates non-zero z values

### ISSUE THREAD

**Issue by 3DLIRIOUS** [cnr-isti-vclab/meshlab#125]
The grid generator filter does not create zero values for z as expected; some values are small but non zero, e.g. 0.000001. To duplicate, create a grid with 101x101 vertices, size 100x100, and save as obj. Open file in a text editor and verify that the z values are non-zero (they range from 0 to 0.000009)

As a workaround, after creating the grid you can run a geometric function with "z = rint(z)" to round these values down to zero.

**Comment by cignoni** [comment]
Thanks for raising the issue!
