### ISSUE TITLE
U3D export error Message

### ISSUE THREAD

**Issue by YumeSK** [cnr-isti-vclab/meshlab#1254]
When I try to export an `.obj` to U3D I get an error message.

I use MeshLab 2022.02 and I am on a macOS 12.3.1

My steps:
1. I `import` my test `.obj`, I exported it as `.obj` in Blender if that is relevant.
2. Then when it's loaded I click on `export mesh as`. and choose U3D File Format (*.u3d) and also change the object name to `.u3d`
![Bildschirmfoto 2022-05-09 um 08 21 59](https://user-images.githubusercontent.com/104828380/167351810-ca8db3e2-8a42-4e4a-b355-526923db2eb9.png)

3. I click on `save` and change no options, and then on `ok`.
4. Then I get this error message and the file doesn't save:
![Bildschirmfoto 2022-05-09 um 08 23 59](https://user-images.githubusercontent.com/104828380/167352188-9a23168f-c9c8-47ef-bb2a-dc8d6fdaee34.png)

I included the `.obj` file of the test object I am using. ( I have also tested it on other objects, the same problem occurs)
[Star.zip](https://github.com/cnr-isti-vclab/meshlab/files/8649221/Star.zip)

**Comment by skulumani** [comment]
I'm having the same issue. Here's an OBJ file that is causing the issue.

[psp.obj.zip](https://github.com/cnr-isti-vclab/meshlab/files/9283157/psp.obj.zip)

* Meshlab 2022.02
* MacOS 12.5
* 
<img width="332" alt="image" src="https://user-images.githubusercontent.com/5266022/183458487-7b82558a-5639-4040-bc8f-92ae2f2293f9.png">

<img width="221" alt="image" src="https://user-images.githubusercontent.com/5266022/183458546-cb4c329f-55b1-46e6-941e-525c4cd4e53f.png">

**Comment by alemuntoni** [comment]
This issue should be solved in the last commits. 
You can try the fix by [downloading the last nightly](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version) from the `main` branch. The feature will be available in the next MeshLab version.
