### ISSUE TITLE
Feature request - filter to select connected components

### ISSUE THREAD

**Issue by 3DLIRIOUS** [cnr-isti-vclab/meshlab#126]
Requesting a filter that will expand a selection to select the entire connected component, i.e. you select a small part of a component, run the filter, and the entire connected component is selected. This can currently be (inefficiently) emulated by running "dilate selection" many times until the entire component is selected.

**Comment by cignoni** [comment]
For interactive selection the functionality is already there: one of the selecting tools works by connected component, but yes for scripting it is missing...

**Comment by 3DLIRIOUS** [comment]
Yes, this is requested for scripting/meshlabserver usage. Thanks!

**Comment by cignoni** [comment]
Done! (thanks for the suggestion)
