### ISSUE TITLE
Windows 10 MeshLab2022.02-windows Isoparametrization Filter Not Present On Download

### ISSUE THREAD

**Issue by cnb2376** [cnr-isti-vclab/meshlab#1261]
Using Meshlab 2022.02 on Windows 10. After using the 2022.02 installer and starting MeshLab for the first time, I encountered this error: 
![image](https://user-images.githubusercontent.com/89807214/171188559-a6195f92-d22e-4220-96f4-2ef078f6295c.png)
I need to use the isoparametrization feature, and find that is not in the filters task bar. After looking in the plugins folder of the program files, I found that the filter_isoparametrization.dll is present with the other filter files.
![image](https://user-images.githubusercontent.com/89807214/171189024-449b7d7c-1d91-4960-a0c2-8706c13f4595.png)
I've uninstalled and reinstalled several times with no change to the error message on startup and missing filter. I'm unsure of whether the .dll file came corrupted or if a desktop setting could be interfering with MeshLab's ability to run with this specific filter.

**Comment by alemuntoni** [comment]
Hi, that's weird. 
The filters that are failing to be loaded use parallelization (OMP). Maybe your system does not have OMP dll for some reason...

**Comment by alemuntoni** [comment]
Could you please try to install the last [vc redist package](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) and let me know if it solves the issue?

**Comment by cnb2376** [comment]
Installing the latest VC Redist package did not solve the issue.

**Comment by cnb2376** [comment]
> Installing the latest VC Redist package did not solve the issue.

After several desktop restarts later, MeshLab initiated without a startup error and the isoparametrization filters are visible. Looks like the VC Redist package installation worked. Thank you alemuntoni.
