### ISSUE TITLE
MeshLab objFile add Face

### ISSUE THREAD

**Issue by SowisLiuYiming** [cnr-isti-vclab/meshlab#1263]
Hello，
I want to add faces to an OBJ file that only has vertex coordinates.Whether the vertex coordinates can be processed into a sphere model.How does MeshLab represent the OBJ model so that it shows only vertex coordinates without faces?
Regards,
Leo
![image](https://user-images.githubusercontent.com/106128162/172094903-d1e2dd83-f733-4a61-b3e6-dbd6fb41b16b.png)
![image](https://user-images.githubusercontent.com/106128162/172094976-e59fdb99-0654-48be-92d6-8528bc347e16.png)

**Comment by alemuntoni** [comment]
There are several filters called "Surface reconstruction" that allow to compute surfaces starting from a point cloud. However, I'm not sure that this is what you're looking for.
