### ISSUE TITLE
MeshLab is not responding after "Remeshing, simplification and reconstruction – Surface reconstruction: Screened poisson"

### ISSUE THREAD

**Issue by WinkensM** [cnr-isti-vclab/meshlab#1268]
Whenever I convert a point cloud to a 3d drawing with lines my laptops are crashing. I tried on a Macbook Pro 2021 16” with a M1 PRO and on a Macbook pro 13” Mid 2012.

My procedure/sequence is as follows:

Filerts – Normals, Curvatures and orientation – Compute normal for point sets (Neighbor number 5) or (Neighbor number 10)

Remeshing, simplification and reconstruction – Surface reconstruction: Screened poisson (Reconstruction depth 14)

_**Crash appears, “MeshLab is not responding”**_

Texture – parametrization: trival per triangle _(would be the next step)_

**Hardware/Software**
MacBook Pro (13-inch, Mid 2012) // 2,5 GHz Dual-Core Intel Core i5 // 4 GB 1600 MHz DDR3
MacBook Pro (16-inch, 2021) // Apple M1 Pro // 16 GB
Latest version Meshlab

**Comment by cRuntX** [comment]
https://www.youtube.com/watch?v=fZI925P1aXw  **03:05min**

The higher the reconstruction depth the more processing power the task would need. In the video they say there is not much  difference after 13/14 reconstruction depth.
My PC is Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz   4.00 GHz 16GB RAM and I have been using 10/11 as reconstruction depth. I get quite good detail and my PC can handle it fine.

**Comment by alemuntoni** [comment]
> be as detailed as possible while describing an issue: 
> - **if it applies, share all the involved files**

*Please read carefully the instructions before submitting an issue*.  Without the input model, there is not much I can do here. 
However, I think @cRuntX is right and that the you are just asking too much to your hardware. Try with a lower reconstruction depth parameter
