### ISSUE TITLE
Meshlab crashes when trying to open objs

### ISSUE THREAD

**Issue by Makogan** [cnr-isti-vclab/meshlab#1270]
Trying to open a model crashes the program. When launching from the terminal I get the error:

```
./vcglib/wrap/io_trimesh/import_obj.h:640: static int vcg::tri::io::ImporterOBJ<OpenMeshType>::Open(OpenMeshType&, const char*, vcg::tri::io::ImporterOBJ<OpenMeshType>::Info&) [with OpenMeshType = CMeshO]: Assertion `(numTriangles +numVertices) == numVerticesPlusFaces+extraTriangles' failed.
Aborted (core dumped)
```

This occurs in a machine with Ubuntu 22.04. It doesn't seem to happen in a machine with Ubuntu 21.10.

I have tried uninstalling and reinstalling from different providers so far I tried:

* Official debian repositories
* Snap store
* Installing binaries from the meshlab website

I get the same error regardless of which source I used. I am unsure why it doesn;t work on this machine specifically.

I am using the same meshes in the system that works so it;s not a problem with the objs, it also happens with any obj including the default blender cube.

**Comment by alemuntoni** [comment]
*Please read carefully the instructions before submitting an issue*.

> be as detailed as possible while describing an issue: 
> - **if it applies, share all the involved files**

There is not much I can do here without the model that crashes meshlab.

**Comment by allo-** [comment]
Same issue on (K)Ubuntu 22.04. Literally ANY obj file crashes meshlab. Example attached.
[example1.txt](https://github.com/cnr-isti-vclab/meshlab/files/9716488/example1.txt)

**Comment by thomasdebruin** [comment]
Same issue here, on ubuntu 20.04.5 LTS no problems, but on Ubuntu 22.04.1 LTS I get this issue with any obj file

**Comment by CILT** [comment]
Same issue on Debian 12 Bookworm.

I've tried to open an .obj file (attached) and MeshLab just crashes.  It only occurs with .obj files, not with .ply, .off, etc.

I've also tested opening the app from here [https://github.com/cnr-isti-vclab/meshlab/releases/tag/MeshLab-2022.02](MeshLab repo) and it works fine.

Some output:
```
$ sudo apt show meshlab
Package: meshlab
Version: 2020.09+dfsg1-2
Priority: optional
Section: graphics
Maintainer: Debian Science Team <debian-science-maintainers@lists.alioth.debian.org>
Installed-Size: 23,5 MB
Depends: lib3ds-1-3 (>= 1.3.0), libc6 (>= 2.33), libgcc-s1 (>= 3.4), libglew2.2 (>= 2.2.0-4), libglu1-mesa | libglu1, libglx0, libgmp10 (>= 2:6.2.1+dfsg), libgomp1 (>= 6), libmuparser2v5 (>= 2.2.6.1+dfsg), libopenctm1 (>= 1.0.3), libopengl0, libqhull8.0 (>= 2020.1), libqt5core5a (>= 5.15.1), libqt5gui5 (>= 5.14.1) | libqt5gui5-gles (>= 5.14.1), libqt5network5 (>= 5.0.2), libqt5opengl5 (>= 5.0.2), libqt5qml5 (>= 5.0.2), libqt5widgets5 (>= 5.15.1), libqt5xml5 (>= 5.0.2), libstdc++6 (>= 11)
Recommends: chemical-mime-data
Homepage: https://www.meshlab.net/
Tag: field::mathematics, field::physics, interface::graphical,
 interface::x11, role::program, uitoolkit::qt, x11::application
Download-Size: 5.010 kB
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian bookworm/main amd64 Packages
Description: System for processing and editing triangular meshes
 This is an open source, portable, and extendible system for the
 processing and editing of unstructured 3D triangular meshes.
 The system is aimed to help the processing of the typical not-so-small
 unstructured models arising in 3D scanning, providing a set of tools for
 editing, cleaning, healing, inspecting, rendering and converting this kind
 of meshes.
 .
 Meshlab can read files in these formats: PLY, STL, OFF, OBJ, 3DS, COLLADA
 and PTX. It can write PLY, STL, OFF, OBJ, 3DS, COLLADA, VRML, and DXF.
```
[mesh.txt](https://github.com/cnr-isti-vclab/meshlab/files/9944918/mesh.txt)


```
$ sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bookworm/sid
Release:	n/a
Codename:	bookworm
```

The error:
```
meshlab: ./vcglib/wrap/io_trimesh/import_obj.h:640: static int vcg::tri::io::ImporterOBJ<OpenMeshType>::Open(OpenMeshType&, const char*, vcg::tri::io::ImporterOBJ<OpenMeshType>::Info&) [with OpenMeshType = CMeshO]: Assertion `(numTriangles +numVertices) == numVerticesPlusFaces+extraTriangles' failed.
Avortat
```

Attached is the .obj file I'm trying to open (notice that it is in .txt format because I couldn't upload the .obj file. Changing extension to .obj should work).

**Comment by allo-** [comment]
The crash reads as if there is a wrong assertion on the number of mesh elements. I only wonder why, because the minimal example for the crash does not have complicated geometry. Maybe some number is not initialized or updated correctly? And I wonder if the versions that do not crash simply have Assertions disabled.

**Comment by alemuntoni** [comment]
@MikePelton @allo- @CILT @thomasdebruin 
The official apt package is not maintained by us and it is outdated. I can't do anything about that, since I am not a maintaner and I don't have time to do that. Our latest release is 2022.02, which is newer than 2020.09. 
Also snap package is not maintained anymore, but [flatpak is](https://flathub.org/apps/details/net.meshlab.MeshLab).
Please be sure to run the latest available release before posting.

**Comment by ferdymercury** [comment]
This was reported in launchpad: https://bugs.launchpad.net/ubuntu/+source/meshlab/+bug/1995736

Maybe @rpavlik can update the apt version?

**Comment by mmpiotrek** [comment]
I had the same problem. Installing snap version works for me.
`sudo snap install meshlab`

**Comment by Echo-jyt** [comment]
> I had the same problem with .obj files. Installing snap version works for me. `sudo snap install meshlab`

thank you very much!

**Comment by fjganan14** [comment]
I installed meshlab from source in ubuntu 22.04 and it is not able to load the obj. 

meshlab: ./vcglib/wrap/io_trimesh/import_obj.h:640: static int vcg::tri::io::ImporterOBJ<OpenMeshType>::Open(OpenMeshType&, const char*, vcg::tri::io::ImporterOBJ<OpenMeshType>::Info&) [with OpenMeshType = CMeshO]: Assertion `(numTriangles +numVertices) == numVerticesPlusFaces+extraTriangles' failed.
Aborted (core dumped)

The obj is like this:

v -23.06726646 -30.24573326 43.50404739 0.6705880165 0.4862749875 0.4784309864
vn -0.6018839478 -0.7969385982 -0.05123063177
v -22.99390221 -30.30145454 43.44314575 0.6627449989 0.4745100141 0.4705879986
vn -0.5994690061 -0.8002261519 0.01658421196
...
f 386//386 387//387 5310//5310 
f 386//386 5310//5310 19178//19178 
f 386//386 19178//19178 12518//12518 
f 387//387 5061//5061 5185//5185 
f 387//387 5184//5184 5310//5310 
f 387//387 5185//5185 5184//5184 
f 388//388 389//389 390//390 
f 388//388 390//390 19330//19330 
f 388//388 5576//5576 389//389 
...

**Comment by nepfaff** [comment]
`flatpak install meshlab` worked for me while snap couldn't find meshlab. Make sure that the apt version is uninstalled before installing with flatpak

**Comment by Masterxilo** [comment]
for reference, this bug has also been reported here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1054006 & https://bugs.launchpad.net/ubuntu/+source/meshlab/+bug/1995736
