### ISSUE TITLE
"Flatten Visible Layers" does not preserve textures

### ISSUE THREAD

**Issue by 3DLIRIOUS** [cnr-isti-vclab/meshlab#128]
"Flatten Visible Layers" filter drops any textures associated with the mesh layers; these should be retained.

**Comment by mcallieri** [comment]
it is not guarantee that is possible. for example, if "merge duplicated vertices" is true and there are per-vertex UV mapping.
I'll try looking into it.

**Comment by mcallieri** [comment]
partly corrected the existing bug: texture indices are preserved, when each original layer had an associatex texture. The resulting layer has UV and multiple texture names.
However, texture is not automatically shown for the new layer.  If you save the new layer, and reload it, it will show.
This is a deeper issue, related to texure update, and I'm not sure how much time it will take.
