### ISSUE TITLE
Running ML 2022.02 on my new notebook with win 11

### ISSUE THREAD

**Issue by GiovanniSer** [cnr-isti-vclab/meshlab#1282]
MeshLab is working but after this
(only in Win 11)
![Clipboard01](https://user-images.githubusercontent.com/67306481/183313153-c6968995-f45f-4903-b52b-2063ff5baa42.jpg)

**Comment by GiovanniSer** [comment]
I have those dll,, but in plugins, not in PlugIns (uppercase problem?)

**Comment by Yao-DY** [comment]
I had the same problem

**Comment by alemuntoni** [comment]
Sorry for the late reply.
Could you please try to install the last [VC Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)?
These plugins are the ones that use parallelization, therefore there is something missing in your system.

**Comment by GiovanniSer** [comment]
t this moment I wait the next ML version, I dont' use those filters and and i don't trust windows soup of update and messages.
My win 10 it hasn't been updated for years because the disk is too small, but In win 10 this problem there is not.
On win 11 I have all the updates. Before overwriting the system I wait to see if it was a temporary glitch.
Windows is crazy, what does it mean by "module"? The plugin or a library module ?
The plugin exists, and normally the message should be library not found.
