### ISSUE TITLE
Windows 10 - Problem setting meshlab as default app for opening mesh files

### ISSUE THREAD

**Issue by patrikhuber** [cnr-isti-vclab/meshlab#129]
Hi,

I have issues on Windows 10 to get MeshLab to open 3D scan files by default on double-clicking. I was able to set MeshLab as default for .obj files, but it doesn't work for .wrl, no matter which way one tries.
I believe that somehow MeshLab doesn't register itself correctly to Windows 10 (the registry or whatever), so Windows 10 doesn't recognise MeshLab as a valid program for opening these files.

If you for example right click a .wrl file, choose "Open With", then you can select the MeshLab exe, but there's no "Use as default app" checkbox.

In this screen, MeshLab is not available:
![image](https://cloud.githubusercontent.com/assets/4967343/24830524/c982f5c0-1c7f-11e7-8a54-0c88f8d25aa7.png)

In this screen, MeshLab is available as an option to choose but once you click it, it just stays at "Choose a default":
![image](https://cloud.githubusercontent.com/assets/4967343/24830487/296a2e64-1c7f-11e7-91e9-aaacd2e576dc.png)

There's probably something or somewhere that MeshLab needs to register itself so Windows 10 will put MeshLab in that list of "Set your default programs" Control Panel screen.

**Comment by mcallieri** [comment]
We are using MeshLab on Windows 10 for a while, never had this issue, MeshLab register itself in the system as the default for opening few 3D file formats.
In some cases, just after installing the association is not available, but becomes available after a restart.
Some other tools, like the "3D Builder" app from Microsoft overwrite the defaults after their updates.

**Comment by ChenXuelinCXL** [comment]
I had this too... Just cannot set MeshLab as the default app for some files...

**Comment by mcallieri** [comment]
After one of the recent updates, I also have this problem :(
I can only choose between PAINT3D and 3DVIEWER Microsoft apps for most 3D formats. I cannot assign other third party tools as default.

**Comment by ChenXuelinCXL** [comment]
@mcallieri  Yes, exactly what you said, no matter how many times I choose MeshLab for the default app, it all ended up with PAINT3D OR 3DVIEWER.

**Comment by pablospe** [comment]
Same for me, even uninstalling 3D viewer app with (in powershell):
`Get-AppxPackage Microsoft.Microsoft3DViewer | Remove-AppxPackage`

Search for all apps related to 3D:
     `Get-AppxPackage *3D*`

**Comment by martin-frbg** [comment]
I believe "inability to change the default app for a file format" is on the list of bugs supposedly fixed with the (in)famous october update to Windows 10 that has recently been rolled out again after resolving the "lost documents" issue with the original version.

**Comment by roman-orekhov** [comment]
I have the same issue for *.ply files for Win 10 1903 version build 18362.476 and MeshLab 2016.12
