### ISSUE TITLE
"Simplification: Clustering Decimation" applies to all faces

### ISSUE THREAD

**Issue by ita1024** [cnr-isti-vclab/meshlab#1297]
Open a mesh, select faces using "select faces in a rectagular region" (there is a typo in the tooltip by the way), then "Simplification: Clustering Decimation" and tick the box "Affect only selected faces". The entire mesh will be simplified, and not just the selected faces. 

Using Meshlab 2020.2

**Comment by alemuntoni** [comment]
MeshLab and vcg do not actually allow to apply the filter just to selected faces. 
I don't know why that option has been added to the filter in the first place... I removed it right now, and I opened a new feature request. See #1338
