### ISSUE TITLE
Export Mesh As... u3d file.

### ISSUE THREAD

**Issue by wufsbc** [cnr-isti-vclab/meshlab#130]
In MashLab 2016.12 I'm try to export STL to U3D file. In console I get information that file is saved as U3D.
__Saved Mesh C:/temp/mashlab/texturedknot.u3d in 902 msec_
But file texturedknot.u3d is missing. IInstead of that is created only TEX file.

http://stackoverflow.com/questions/42226059/meshlab-detailed-merged-meshes-not-exporting-to-u3d

**Comment by mcallieri** [comment]
yes, sorry, there has been a problem packing the converter, it will be ok int he next release.
There is a temporary fix, please refer to this issue for more details: #33

**Comment by wufsbc** [comment]
Thanks. It's work.
