### ISSUE TITLE
Using ball pivoting to generate a triangular mesh, it keeps showing adding 0 faces

### ISSUE THREAD

**Issue by 19990101lrk** [cnr-isti-vclab/meshlab#1305]
Using ball pivoting to generate a triangular mesh, it keeps showing adding 0 faces，Adjusting the radius has no effect either

**Comment by alemuntoni** [comment]
Could you please provide the input mesh/point cloud and the exact steps you are performing? 
Are you using the last version of MeshLab (2022.02)? Thanks.
