### ISSUE TITLE
"MeshLab" is not responding.

### ISSUE THREAD

**Issue by LogWell** [cnr-isti-vclab/meshlab#1309]
OS: Ubuntu 18.04.5 LTS
Version: `sudo snap install --devmode meshlab` : `meshlab --version` >> "MeshLab 2021.05"
Problem:  `"MeshLab" is not responding.` often appears when browsing point clouds or meshes (no operations are involved), the window may disappear immediately, it may get stuck, and you need `kill` the process. It hardly appears in "MeshLab 2022.02", but it seems that this version cannot control the view direction (Windows >> View from ...) with the keypad, so I still use the previous version.

![image](https://user-images.githubusercontent.com/34391447/191501804-bd5a38ff-8dad-43d9-be42-cd0db6db826c.png)

**Comment by alemuntoni** [comment]
See #1270
