### ISSUE TITLE
Voronoi Sampling Doesn't Generate Voro or Poly Layers When Quality Weighted

### ISSUE THREAD

**Issue by zoyt** [cnr-isti-vclab/meshlab#1318]
Hello,

Thanks so much for such a fantastic and powerful mesh processor! I've been using it for a few years now, and have always been astonished by it's range and ease of use, and have been using PyMeshLab for almost as long to automate functions. Really great stuff, I cannot express my appreciation enough. 

Version: 64_bit_fp v2022.02, built with MSVC 1931 and Qt 5.15.2

I've been working on a problem which relies on a weighted Voronoi sampling. [These are the](https://ufile.io/6zgc59v7) preprocessing steps to generate generate the vertex qualities I'm after, but it seems to be universal to all meshes with vertex quality. 

When I apply the "Voronoi Sampling" function with the following parameters, the "Voro" and "Poly" mesh layers (generated by the function) are empty, with no vertices or faces. The problem seems to be identical in PyMeshLab (though the function takes at least 10x the runtime to complete vs ML desktop, not sure what's going on there). Changing the Radius Variance, color strategy, iteration number, relax type, or sample number does not appear to change this bug. 

I would greatly appreciate any ideas or advice on possible solutions to this issue. 

Thank you!

![image](https://user-images.githubusercontent.com/64329370/197824095-e0eeabf2-de6b-40c9-a89f-2a5ab92afb7d.png)

**Comment by alemuntoni** [comment]
I am trying to replicate this issue using 2022.02 on windows, but without success.
I am using [this bunny model](https://github.com/cnr-isti-vclab/meshlab/files/10194338/bunny.zip):
- I run 'Colorize curvature APSS' filter to compute vertex quality
- I compute the Voronoi Sampling filter, leaving all the parameters defaulted except 'Distance Type' that is set to 'Quality Weighted'.

Could you please share a model that you are using or tell me what I need to do to replicate this issue?

**Comment by zoyt** [comment]
Hi @alemuntoni, thanks for looking into this. 

This may just a problem on my machine. I downloaded the bunny model, applied the 'Colorize curvature APSS' filter, and applied the 'Voronoi Sampling filter' with the distance type set to quality weighted, just as you suggested. Strangely, the same thing happened. 

When I apply the filter to the bunny model, but don't use quality weighted distance, the poly and voro layers generate just fine:
![image](https://user-images.githubusercontent.com/64329370/227609452-ec7b7656-d748-4d49-a5c1-755dd4badfa8.png)

However, when I go through the same process, but use quality weighted distance, the poly and voro layers don't generate:
![image](https://user-images.githubusercontent.com/64329370/227609285-244f905e-c151-48f7-92f4-0371d08ec67a.png)

Given your reaction and suggestions, I'm assuming that this doesn't happen on your computer. I don't have a conclusion here, other than - strange. It may worth noting that quality weighted function definitely works outside of this, but the setup for that workflow is quite different.
