### ISSUE TITLE
Postcondition mechanism is a bit flawed...

### ISSUE THREAD

**Issue by cignoni** [cnr-isti-vclab/meshlab#132]
Example texture update...

**Comment by mcallieri** [comment]
postoconditions are used for 2 different things:
- deciding which is the correct menu for the filter
- deciding what are the post-filter operations (allocation/deallocation, rendering status, texture update...)

Tha two things should be ideally de-coupled.
Moreover, it make sense that the menu entry is statically decided, while the post-filter operation depends on the input layers AND on the filter parameters AND on what happens during filter execution.
It may have have sense to have a statically-defined post-filter operation 8for the general case), plus a series of "flags" raised by the filter during the APPLY, telling the system what has been actually changed, beside the default... e.g. "hey, I changed the texture, please update it when I finish"
