### ISSUE TITLE
How can I obtain the rgb value of the selected point?

### ISSUE THREAD

**Issue by 1215232494** [cnr-isti-vclab/meshlab#1322]
Ubuntu20.04
MeshLab 2020.03+dfsg1-1

I use meshlab to view the ply file. How can I obtain the **rgb value** of the selected point. When I double-click a point, the output is `Recentering on point [-0.090,095 0.065,358 -0.361,002] [358,551]`, but this does not seem to be the value I want

**Comment by zoyt** [comment]
Hi,

I've got a solution for you, but it actually seems that there may be a bug in this as well - 

If you are looking at the mesh, you can select the "Get Info" tool in the top, it looks like yellow circle with a black lowercase 'i'. Using the Get Info tool, you can select a particular face on the mesh, and it will get a red outline with info about vertices and faces appearing on top of the mesh. Useful in your case, is that the text information for each vertex lists the vertex index, position (coordinates), and RGB color.

Interestingly, and this may be a bug or just an issue with my machine, but when I print this information to the text box in the bottom right by pressing "P", the color information is displayed as "color (0.000000 0.000000 0.000000 0.000000)". However, I have had no issues accessing the color RGBA values of a mesh using PyMeshLab, which I would recommend if you need to check the color of more than a few verts.

In the future, please put questions like this [in the Q&A section of the Discussions tab. ](https://github.com/cnr-isti-vclab/meshlab/discussions/categories/q-a)

**Comment by 1215232494** [comment]
Thank you for your reply. I tried. But not all the points can be clicked, and I also mentioned the problem of pressing the P key.
And I found that my point cloud color only has three rgb channels, and he will automatically add a channel to me, and the default value is 255.
