### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by sherpya** [cnr-isti-vclab/meshlab#1323]
I'm experiencing a lot of crashes loading models, mainly exported from blender, some of them are a bit invalid (e.g. mesh with scale 0), other look ok.
I've tested the version in git and all my tested models are loaded correcly so I suppose most of the bug are fixed, it would be nice to have a new bugfix release

Or maybe something to do with the AppImage? I can provide a model that crashes the app image on my linux debian sid

Thanks

**Comment by sherpya** [comment]
FYI
```
Thread 1 "meshlab" received signal SIGSEGV, Segmentation fault.
0x00007fff78c6131a in void gltf::internal::populateAttr<float>(gltf::internal::GLTF_ATTR_TYPE, MeshModel&, std::vector<CVertexO*, std::allocator<CVertexO*> >&, float const*, unsigned int, int) () from /tmp/.mount_MeshLaID7ap8/usr/lib/meshlab/plugins/libio_gltf.so
```

**Comment by alemuntoni** [comment]
Yes, gltf importer has been fixed some time ago. I am planning to make a post release of MeshLab 2022.02 soon, just to have those bugs fixed.
