### ISSUE TITLE
Crash after using "delete non-visible meshes"

### ISSUE THREAD

**Issue by adizhol** [cnr-isti-vclab/meshlab#1328]
Ubuntu 20.04
Meshlab 2022.2

Loaded point clouds
Created a mesh from it (Ball Pivot). 
Run "connected components" filter. 
Selected only two meshes as visible.
Selected "delete non-visible meshes from drop down"
Meshlab crashed

**Comment by alemuntoni** [comment]
Can't replicate.
Could you please share a model that allows to replicate it?
Which mesh layers do you keep as visible?
