### ISSUE TITLE
poisson reconstruction not responding

### ISSUE THREAD

**Issue by LogWell** [cnr-isti-vclab/meshlab#1332]
system: Ubuntu 18.04.5 LTS
version: meshlab --version / MeshLab 2021.05
install by: sudo snap install meshlab

Description: For any mesh, when performing `poisson reconstruction` and meshlab will occupy all resources, 

![image](https://user-images.githubusercontent.com/34391447/205802464-6412d5b3-4e76-4ec7-9225-7618c98a5865.png)

it has been running, but there is no result, and the following prompts often appear

![image](https://user-images.githubusercontent.com/34391447/205803454-deea6b1b-a058-4ed9-a3f4-18aed1279f51.png)

The current device was able to run PR successfully before, and the system may have been modified to make this function unable to operate normally.

**Comment by alemuntoni** [comment]
See #1270.

**Comment by LogWell** [comment]
Computer configuration

![image](https://user-images.githubusercontent.com/34391447/206186877-743160f3-80ae-4311-870c-36ada4228a62.png)


Reinstall:
```
sudo apt install flatpak
flatpak install --from '/home/lab0/Downloads/net.meshlab.MeshLab.flatpakref'
```

![image](https://user-images.githubusercontent.com/34391447/206187909-8e8675e2-248e-487a-8cbc-e90642de3245.png)

It must be abnormal for such a mesh to take so long under such a configuration.

**Comment by LogWell** [comment]
I'll run it again on Windows
```
Opened mesh C:\Users\ustcer\Desktop\10001_1937_v1.obj in 1879 msec
All files opened in 1880 msec
Applied filter Surface Reconstruction: Screened Poisson in 2308 msec
```

**Comment by alemuntoni** [comment]
I am not sure, but may be that the flatpak version does not use parallelism properly.
Could you try also the AppImage to see if the problem persists?

**Comment by LogWell** [comment]
Also very slow in `pymeshlab`:
```
def poisson_recon(path_mesh):
    import pymeshlab

    ms = ml.MeshSet()
    ms.load_new_mesh(path_mesh)
    ms.generate_surface_reconstruction_screened_poisson(depth=8, preclean=True)
    ms.save_current_mesh(path_mesh[:-4] + "_pr.ply")
```

```
Depth[0/8]:     Evaluated / Got / Solved in:  0.000 /  0.003 /  0.096   (1507.391 MB)   Nodes: 1
Depth[1/8]:     Evaluated / Got / Solved in:  0.022 /  0.048 /  7.496   (1571.391 MB)   Nodes: 8
Depth[2/8]:     Evaluated / Got / Solved in:  0.021 /  0.065 / 10.963   (1763.391 MB)   Nodes: 64
Depth[3/8]:     Evaluated / Got / Solved in:  0.020 /  0.118 / 21.871   (1827.391 MB)   Nodes: 512
...
```

**Comment by alemuntoni** [comment]
could you please share the input model you are using?

**Comment by LogWell** [comment]
I restarted my computer and it worked fine again ......
