### ISSUE TITLE
Screened Poisson Surface Reconstruction filter is reporting a problem with the plugin in Meshlab 2020.07 

### ISSUE THREAD

**Issue by ortobajt** [cnr-isti-vclab/meshlab#1333]
Hello.
I have a problem with Meshlab 2020.07, which is installed on Windows 11.
When I run the following command in cmd:

`.\meshlabserver.exe  -i C:\Users\...\AppData\Local\Temp\in0.stl -o C:\Users\...\AppData\Local\Temp\out.stl -s C:\Users\...\AppData\Local\Temp\PoissonSurfaceReconstruction.mlx`

I get the following message
`Loading Plugins:
Current Plugins Dir is: C:/Program Files/VCG/MeshLab/plugins
"Cannot load library C:\\Program Files\\VCG\\MeshLab\\plugins\\filter_sketchfab.dll: Nie mo┐na odnalečŠ okreťlonego modu│u."
Total 265 filtering actions
Total 13 io plugins
Opening a file with extension stl
Mesh C:/Users/rafal/AppData/Local/Temp/in0.stl loaded has 116446 vn 231954 fn
output mesh  C:/Users/rafal/AppData/Local/Temp/out.stl
Apply FilterScript: 'C:/Users/rafal/AppData/Local/Temp/PoissonSurfaceReconstruction.mlx'
FilterScript
Reading filter with name Remove Duplicate Vertices
Starting Script of 1 actionsfilter: Remove Duplicate Vertices
LOG: 2 Removed 0 duplicated vertices
Removed 0 duplicated vertices
Mesh C:/Users/rafal/AppData/Local/Temp/in0.stl saved as C:/Users/rafal/AppData/Local/Temp/out.stl (116446 vn 231954 fn)
`

My PoissonSurfaceReconstruction.mlx script:
```
`<!DOCTYPE FilterScript>
<FilterScript>
 <filter name="Remove Duplicate Vertices"/>
 <xmlfilter name="Screened Poisson Surface Reconstruction">
  <xmlparam value="0" name="cgDepth"/>
  <xmlparam value="false" name="confidence"/>
  <xmlparam value="12" name="depth"/>
  <xmlparam value="5" name="fullDepth"/>
  <xmlparam value="8" name="iters"/>
  <xmlparam value="4" name="pointWeight"/>
  <xmlparam value="true" name="preClean"/>
  <xmlparam value="1.5" name="samplesPerNode"/>
  <xmlparam value="1.1" name="scale"/>
  <xmlparam value="false" name="visibleLayer"/>
 </xmlfilter>
 
</FilterScript>`
```

My out.stl is identical as in.stl
 
![image](https://user-images.githubusercontent.com/20069941/206217389-b3ae8eb6-ff5a-44e9-b11e-ef73f6e2fed7.png)

If I check plugin folder:  C:/Program Files/VCG/MeshLab/plugins I see there is a filter_sketchfab.dll
![image](https://user-images.githubusercontent.com/20069941/206211041-b804344a-0c67-4191-9993-2c85d7a28080.png)

If in filter scipt I add:
`
```
 <filter name="Change the current layer">
  <Param tooltip="The name of the current mesh" type="RichMesh" value="0" name="mesh" description="Mesh"/>
 </filter> 
 
 <filter name="Delete Current Mesh"/>
```
`

I get the following message
```
Loading Plugins:
Current Plugins Dir is: C:/Program Files/VCG/MeshLab/plugins
"Cannot load library C:\\Program Files\\VCG\\MeshLab\\plugins\\filter_sketchfab.dll: Nie mo┐na odnalečŠ okreťlonego modu│u."
Total 265 filtering actions
Total 13 io plugins
Opening a file with extension stl
Mesh C:/Users/rafal/AppData/Local/Temp/in0.stl loaded has 116446 vn 231954 fn
output mesh  C:/Users/rafal/AppData/Local/Temp/out.stl
Apply FilterScript: 'C:/Users/rafal/AppData/Local/Temp/PoissonSurfaceReconstruction.mlx'
FilterScript
Reading filter with name Remove Duplicate Vertices
Reading filter with name Change the current layer
Reading filter with name Delete Current Mesh
Starting Script of 3 actionsfilter: Remove Duplicate Vertices
LOG: 2 Removed 0 duplicated vertices
Removed 0 duplicated vertices
filter: Change the current layer
Removed 0 duplicated vertices
filter: Delete Current Mesh
Removed 0 duplicated vertices
Error: trying to save 1 meshes, but only 0 available in the project
Output mesh C:/Users/rafal/AppData/Local/Temp/out.stl has NOT been saved. A not existent layer has been requested to be saved
```

When I perform the steps contained in the filters manually in the MeshLab 2020.07 program, everything runs fine
![image](https://user-images.githubusercontent.com/20069941/206216742-acbaab38-f0b0-47be-9630-5ebad7436f1a.png)

I am sending the model in the attachment
[in0.zip](https://github.com/cnr-isti-vclab/meshlab/files/10177251/in0.zip)

**Comment by alemuntoni** [comment]
See #911 - meshlabserver it is not supported anymore.
Moreover, the latest version of MeshLab is 2022.02.
Please check if the errors persist in the latest versions of MeshLab and PyMeshLab.

**Comment by ortobajt** [comment]
#911 is a completely different topic. In version 2020.04 meshlabserver is still installed and other filters are executed correctly. I'm asking about this particular case of a filter.

**Comment by alemuntoni** [comment]
#911 tells that meshlabserver is not supported anymore. 
After 2020.07, 6 newer versions of MeshLab have been released. That means that bugs of 2020.07 may have been fixed in newer versions.
The issue you are reporting is about a tool that is not supported since two years. Bugs on that tool won't be fixed. 
We can't and we won't support obsolete versions.
