### ISSUE TITLE
Re-Orient all faces coherentely [sic] not working

### ISSUE THREAD

**Issue by mbex9ts3** [cnr-isti-vclab/meshlab#1334]
I have Meshlab installed on two Windows 64-bit OS machines: both reported as v2022.02 in the 'Help' dropdown menu though one software (termed 'new_behavior' in the attached figures) was installed on the date of writing, whereas the other (termed 'old_behavior' in the attached figures) was installed several months ago. 

When attempting to run 'Re-Orient all faces coherentely' in the 'Normals, curvature and Curvature' dropdown menu using the newer install the functionality no longer works, whereas coherency is still achieved using the earlier install (see attachments: note that we have edited out some triangles for viewing / same mesh used in both cases).

Thanks

![old_behavior01](https://user-images.githubusercontent.com/58100363/206445324-dc8f6aea-0bf3-4cbc-baca-b884a4e5cc9a.png)

![new_behavior01](https://user-images.githubusercontent.com/58100363/206445363-0b3354bd-3465-4a1b-9c77-fcbbe8fe20d8.png)

**Comment by alemuntoni** [comment]
Could you please:
- share the model
- share a screen of the 'about' dialog for both the MeshLab versions?

thanks.
