### ISSUE TITLE
Crash by trying to glue a pair of mesh

### ISSUE THREAD

**Issue by jaquesvoleur** [cnr-isti-vclab/meshlab#134]
Hi, Javier Bonilla From México, I'm using MeshLab like a mesh viewer for my projects, but when I use the Aling tool, in order to glue a pair of mesh, from the same piece and having common pair of points, the program crash inmediately after clicking the Glue by pair of points option.

**Comment by mcallieri** [comment]
We cannot replicate the issue. This problme has never been reported.
It may be related to having a new rendering window, try updating the videocard drivers.
