### ISSUE TITLE
Crash when opening incomplete .obj

### ISSUE THREAD

**Issue by tkircher** [cnr-isti-vclab/meshlab#1341]
Version: MacOS M1 Meshlab 64-bit fp v2022.02, Mar 2 2022 build, Clang 13.0.0, Qt 5.15.2

Noticed when trying to open an .obj that had not finished downloading. It attempts to import and then it seems that when it reaches the end of the file, there is a processing step that crashes with a segmentation fault.

**Comment by alemuntoni** [comment]
Do you have the file? I cannot replicate the issue without it.

**Comment by tkircher** [comment]
I can replicate this by truncating any .obj file

**Comment by alemuntoni** [comment]
Still, cannot replicate. I am randomly truncating obj files, but I do not experience segmentation faults.
