### ISSUE TITLE
gLTF models and multiple texture coordinate channels

### ISSUE THREAD

**Issue by mikeucfl** [cnr-isti-vclab/meshlab#1345]
I noticed the current implementation for the gLTF loader only supports reading one texture coordinate channel (TEXCOORD_0). Is MeshLab's framework set up to handle multiple channels, if one were to iterate through the other texture coordinates? From what I can tell, populateVTextCoords (https://github.com/cnr-isti-vclab/meshlab/blob/main/src/meshlabplugins/io_gltf/gltf_loader.cpp#L620) seems to only have one spot to hold UVs, so doesn't seem like it's something trivial to add support for?

**Comment by alemuntoni** [comment]
No, there is not, sorry. At the moment, VCG Mesh is able to store just one per vertex texture coordinate.

**Comment by mikeucfl** [comment]
Thanks for the information
