### ISSUE TITLE
gltf not importing - Failed opening gltf file: accessor[3] invalid bufferView

### ISSUE THREAD

**Issue by lex3001** [cnr-isti-vclab/meshlab#1346]
Windows 11 Meshlab 2022.02

---------------------------
Meshlab Opening Error
---------------------------
Failed opening gltf file: accessor[3] invalid bufferView
---------------------------
OK   
---------------------------

I am trying to import a gltf file that has an associated .bin (vertices etc. using Draco compression) and ,jpg texture image as separate files. It was exported from Blender. I am guessing that there is not currently support for Draco compression but figured I would post this issue and find out. Thanks!

**Comment by alemuntoni** [comment]
Could you please share the file that causes the issue?
