### ISSUE TITLE
Cannot launch Meshlab 2016.12 on windows 10 pro 64 build 14393

### ISSUE THREAD

**Issue by bioman666** [cnr-isti-vclab/meshlab#135]
Hello all,

I'm currently not able to launch Meshlab 2016.12 on windows 10 pro 64 build 14393, using a core i7 4790k and its embedded GPU. Rebooting, launching as admin or windows 8 compatibility does not help.

Any guess?

Hugo.

**Comment by mcallieri** [comment]
It may be the integrated videocard not supporting some of the rendering features. Try updating the videocard driver.

**Comment by Marriaga** [comment]
I have a similar issue. Meshlab used to work on my laptop but now when I launch it, it quickly opens and closes two different windows. Nothing happens after that.

**Comment by mcallieri** [comment]
Are you using an integrated videocard? have you tried updating the drivers?
As the new version of MeshLab heavily uses GPU, some drivers of integrated videocard may cause problems.

**Comment by Marriaga** [comment]
I have switchable graphics cards, both an Integrated card and a Dedicated one. It might be the case that Meshlab is trying to use the integrated card and crashes. Is there anyway to test this hypothesis? Updating drivers in my experience is not so simple in this case because the drivers must usually be supplied by the manufacturer.

**Comment by mcallieri** [comment]
Most notebook have this problem. By default, almost all software start with the integrated one. If you right-click on the link, in the menu there should be something like "start application with..." and then the two options, inegrated and dedicated. This will start the software ONCE with the card of your choice.
Furthermore, from the graphic card control panel there is Always a way to set this permanently. https://www.howtogeek.com/175281/how-to-force-graphics-options-in-pc-games-with-nvidia-amd-or-intel-graphics/
beware, even with this "permanent" change, after major system updates, it may happen that the preference is reset. Yes, I know, it is annoying.

**Comment by Marriaga** [comment]
Thank you for the answer. I've tried setting the drivers to start meshlab with the dedicated card, but it doesn't solve the issue. The annoying thing is that it wasn't always like this, it used to work, but at some point some update broke it.

**Comment by khmseu** [comment]
I see the same problem on my notebook under Win7. No option to start the program with different graphics, and resetting graphics options to something sensible doesn't help. I append the info output from the graphic card utility.

Intel(R) HD Graphics 3000




Report Date:			6/8/2017
Report Time[hh:mm:ss]:		13:00:13
Driver Version:			9.17.10.4229
Operating System:		Microsoft Windows 7 Professional (6.1.7601)
Default Language:		German (Germany)
DirectX* Version:		11.0
Physical Memory:		8075 MB
Processor:			Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
Processor Speed:		2491 MHz
Vendor ID:			8086
Device ID:			0126
Device Revision:		09




*   Processor Graphics Information   *


Processor Graphics in Use:		Intel(R) HD Graphics 3000
Video BIOS:			2089.0
Current Graphics Mode:		1366 by 768




*   Devices Connected to the Graphics Accelerator   *


Active Notebook Displays: 1
	*	Built-in Display	*


Monitor Name:			PnP-Monitor  Standard 
Display Type:			Digital
Gamma Value:			2,2
DDC2 Protocol:			Supported


Maximum Image Size:
Horizontal:			12,20 inches
Vertical:			06,69 inches


Monitor Supported Modes:
1366 by 768 (40 Hz)
1366 by 768 (60 Hz)



Display Power Management Support:
Standby Mode:			Not Supported
Suspend Mode:			Not Supported
Active Off Mode:		Not Supported


Raw EDID:
00 FF FF FF FF FF FF 00 06 AF 3C 10 00 00 00 00 
00 16 01 04 90 1F 11 78 02 10 B5 97 58 57 92 26 
1E 50 54 00 00 00 01 01 01 01 01 01 01 01 01 01 
01 01 01 01 01 01 CE 1D 56 D2 50 00 26 30 10 10 
3E 00 35 AD 10 00 00 18 DF 13 56 D2 50 00 26 30 
10 10 3E 00 35 AD 10 00 00 18 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 
00 0C 39 CC 0D 3C 64 0F 0C 1B 6F 20 20 20 00 0D 


* Other names and brands are the property of their respective owners. *

**Comment by alemuntoni** [comment]
Hi, this issue should be solved in the last commits. 
Probably your graphic drivers do not support newer versions of OpenGL, and therefore MeshLab did not start. Now, if this happens, MeshLab asks to use a CPU implementation of OpenGL that allows it to start.
You can find a working installer [here](https://github.com/cnr-isti-vclab/meshlab/actions/runs/73720133), or starting from version 2020.05.
Feel free to open another issue if the problem persists! :)
