### ISSUE TITLE
Unable to run with either hardware or software OpenGL on Windows 10

### ISSUE THREAD

**Issue by rmcardle** [cnr-isti-vclab/meshlab#1351]
I'm trying to run MeshLab 2022.02 on Windows 10 21H2 19044.2251 64-bit. My GPU is an nVidia GeForce GTX 1060 3GB and I am using version 527.56 of the GeForce Game Reader driver. I have no integrated graphics.

When I start MeshLab, I get the following error:

> Critical Error
> 
> MeshLab was not able to start.
> Please check your Graphics drivers.
> 
> Error: GLEW initialization failed: Missing GL version
> 
> [ ] Use CPU OpenGL and restart MeshLab

If I click `OK`, the program just closes. If I check the `Use CPU OpenGL and restart MeshLab` and press `OK`, I get prompted to disable hardware acceleration. If I agree to that, after a UAC prompt, the program restarts and I still get the above error message again. After disabling hardware acceleration, I have verified that `opengl32sw.dll` has been renamed to `opengl32.dll` in my MeshLab installation folder (`C:\Program Files\VCG\MeshLab`).

I tried running [realtech VR OpenGL Extensions Viewer 6](https://www.realtech-vr.com/glview/) and it has no problem accessing OpenGL. It shows that I have OpenGL 4.6 and that 100% of core features for versions 3.0, 3.1, 3.2, 3.3, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, and ARB 2015 are supported.

**Comment by alemuntoni** [comment]
Sorry for the late reply. That's strange, when using the renamed `opengl.dll`, all the graphics calls are run on CPU and therefore they should run smoothly on every system...
I just don't know how to solve this issue, sorry.
