### ISSUE TITLE
Texture has not been loaded

### ISSUE THREAD

**Issue by Anonyme415** [cnr-isti-vclab/meshlab#1352]
Hi，I used openmvs to rebuild the model and obtained the following file，including texture.ply，texture.mvs，texture.png.But when i opened texture.ply, i encountered the following problem.And the loaded model has no texture effect.
![1674044726395](https://user-images.githubusercontent.com/62164167/213170909-167da729-33b9-4f45-aae9-7232845e638f.jpg)
How to solve it？

**Comment by oguzhanilter** [comment]
I am having the same issue. 
Version: MeshLab_64bit_fp v2022.02

**Comment by alemuntoni** [comment]
Does the texture *exist* in the same directory where the file is placed?
Without providing a file that allows to replicate the issue, it is hard to understand if the issue is related to the file or to our software.
