### ISSUE TITLE
cannot open mesh with NaNs

### ISSUE THREAD

**Issue by christian-rauch** [cnr-isti-vclab/meshlab#1354]
When I open a PLY mesh with NAN values in MeshLab, I initially get the warning `Warning mesh contains [XXXXXXX] vertices with NAN coords and 0 degenerated faces. Corrected.` and the mesh is not shown.

The same PLY mesh opens just fine in CloudCompare. MeshLab could ignore those points with NaNs but still show the remaining valid points.

**Comment by cignoni** [comment]
Agree. Has to be done (and it should not be very hard)
