### ISSUE TITLE
Feature request: save snapshot with original file name instead of base name "snapshot"

### ISSUE THREAD

**Issue by fabricecarles** [cnr-isti-vclab/meshlab#1358]
Default snapshot output use only a base name "snapshot" + a counter.
But my goal is to link resulting  snapshot name with original 3d ply, stl ... files
When checkbox "snap All layers" each mesh is saved with name like
snapshot00_L00.png
snapshot00_L01.png
snapshot00_L02.png
...

could you add an optional checkbox to save the original layer name instead ? 

Example : if I load 3 meshs with name "mesh.ply",  "mesh_custom.ply and "reference.stl"
expected result : 
mesh.png
mesh_custom.png
reference.png

and if we keep the counter : 

mesh00.png
mesh_custom00.png
reference00.png

**Comment by cignoni** [comment]
Agree! It would be very useful
