### ISSUE TITLE
Meshlab 2016 Not Functioning

### ISSUE THREAD

**Issue by rockman44181000** [cnr-isti-vclab/meshlab#136]
Everytime I attempt to scale an STL file, nothing is happening. Regardless as to what scale I'm using or to which axis whether being kept Uniform or not is checked. I get zero difference in file size.

**Comment by mcallieri** [comment]
why the SIZE of the file should change? Scaling means just a change in coordinates, and the format is binary.
Moreover, scaling happens on the 3d data, and does not depend on the format you use.
