### ISSUE TITLE
Screened Poisson Surface Reconstruction is not reproducible

### ISSUE THREAD

**Issue by omhafez** [cnr-isti-vclab/meshlab#137]
Running a script using ONLY the screened poisson surface reconstruction filter does not produce the same result on multiple runs for the same input.

This is true at least on MacOS Sierra.

**Comment by mcallieri** [comment]
I cannot replicate the issue. 
Are you sure you are not overwriting the input mesh every time, when saving?

**Comment by omhafez** [comment]
@mcallieri I am pretty sure I am not overwriting anything. Per previous recommendations, the filters in the script I am running are: 
```<xmlfilter name="Screened Poisson Surface Reconstruction">```,
 ```<filter name="Change the current layer">```, and
```<filter name="Delete Current Mesh"/>```

Here is a zip file [**issue137.zip**](https://github.com/cnr-isti-vclab/meshlab/files/955913/issue137.zip) that includes:

**ptcloud.ply** - input point cloud
**poissrecon.mlx** - Meshlab script file
**out1.ply** - output from the following run:
`meshlabserver -i ptcloud.ply -o out1.ply -s poissrecon.mlx`
**out2.ply** - output from the following run immediately after:
`meshlabserver -i ptcloud.ply -o out2.ply -s poissrecon.mlx`

Running `diff out1.ply out2.ply` says the output files differ. I assume the result is the same but the node/element ordering is not reproducible.

I replicated the same error on Ubuntu 14.04 with the snap version of Meshlab 2016.12 as well.

Thanks,
Omar

**Comment by mcallieri** [comment]
I am still unable to replicate the issue on Windows. The generated files are identical.
I see the difference in the file you sent. There seems to be minor changes in ordering and in coordinates (although we are close to number precision). From the practical point of view, the two surfaces are identical, but still not perfectly corresponding.
It may be something related to a rounding function working differently on Windows - Linux/mac.

I will try to find more info, but from the practical point of view, we have no problems with this kind of results, so it's NOT our priority.

here is an example of two faces, one for each of your model, that should be identical:
```
------
face# 304227 : vert# (151441 152500 151153)
face vert 0 : vert# 151441
position [30.467804 58.935993 72.589668]
normal [-3.638600 1.621203 4.858756]
quality 0.000008
color (0.000000 1.621202 4.858753 0.000000)
face vert 1 : vert# 152500
position [30.621754 58.756950 72.765106]
normal [-3.565126 1.696263 4.887825]
quality 0.000008
color (0.000000 1.696262 4.887825 0.000000)
face vert 2 : vert# 151153
position [30.525414 58.935993 72.632957]
normal [-3.610914 1.626430 4.877785]
quality 0.000000
color (0.000000 1.626430 4.877785 0.000000)
------
------
face# 304229 : vert# (151439 152501 151150)
face vert 0 : vert# 151439
position [30.467804 58.935993 72.589676]
normal [-3.638464 1.621326 4.858820]
quality 0.000000
color (0.000000 1.621325 4.858818 0.000000)
face vert 1 : vert# 152501
position [30.621754 58.756950 72.765114]
normal [-3.565087 1.696284 4.887846]
quality 0.000000
color (0.000000 1.696284 4.887844 0.000000)
face vert 2 : vert# 151150
position [30.525414 58.935993 72.632957]
normal [-3.610644 1.626719 4.877891]
quality 0.000000
color (0.000000 1.626719 4.877888 0.000000)
------

```

**Comment by omhafez** [comment]
@mcallieri, 
Fair enough, thank you for looking into it!

**Comment by mcallieri** [comment]
I checked the code.
There is no difference between Windows and mac/Linux code, and there is nothing random in the MAIN FILTER CODE. 
However, as the surface reconstruction is done using a multi-core parallel approach, the differences in vertex ordering may depend on how parallel thread are managed in the different operating systems. 
As I said, the two meshes you sent are equivalent from a geometrical point of view, and the differences are way below the merging resolution, close to numerical precision.
There is not much we can do to make the process alway repeatable, sorry.
