### ISSUE TITLE
STL ascii saved malformed

### ISSUE THREAD

**Issue by GiovanniSer** [cnr-isti-vclab/meshlab#1372]
Win 10 MeshLab 20022.2
This small STL ascii file in ML is loaded fine.
If I save as bin STL, it is loaded again fine.
BUT if I save, instead as bin file, as ASCII file, this file works fine for me and for Win 3D programs, but Meshlab is unable to read his own file. (error Malformed file)

[c.zip](https://github.com/cnr-isti-vclab/meshlab/files/11078466/c.zip)

**Comment by alemuntoni** [comment]
Fixed in the last commit, thanks for reporting!
