### ISSUE TITLE
Meshlab runs single-threaded and is super slow on Ubuntu 20.04/22.04

### ISSUE THREAD

**Issue by adfayed** [cnr-isti-vclab/meshlab#1374]
# Meshlab runs single-threaded for me and is super slow.

Installing Meshlab 2020.03+dfsg1 on Ubuntu 20.04 (just simply using `apt install meshlab`) runs single threaded for me. I tried it on an Ubuntu 22.04 but it still has the same slow performance. On Ubuntu 22.04, right-clicking the Meshlab icon shows an option to run it on discrete-graphics, but checking `htop` and `nvtop` doesn't show a difference. I even increased the shader memory setting but that changes nothing.

Please help. Is there a way to enable it to run on multiple-cores? Is it multi-threaded? Or can it actually run on the GPU?

#### Specs & Reproducibility: 
- i9-13000K CPU, 64GB DDR5 RAM, NVIDIA RTX 4080 GPU (definitely not shy on power)
- Ubuntu 20.04 LTS and Ubuntu 22.04
- 2020.03+dfsg1 using `apt install meshlab`
- Import any `.xyz` file of pointclouds by clicking `import mesh`. Mine was generated with Open3D, but doesn't have to be.
- Does happen on Ubuntu 22.04

#### P.S. I also tried the latest release 2022.02, but the same thing happens. I tried to build from source, but honestly documentation is scarce on how to do that with 2022.02. Digging on my own it required QT 5.18 which is complicated to build on its own.

**Comment by alemuntoni** [comment]
- meshlab from apt is not maintaned by us: https://github.com/cnr-isti-vclab/meshlab/issues/1270#issuecomment-1340532087
- Qt 5.18 does not exists. MeshLab requires Qt 5.15, it is specified [here](https://github.com/cnr-isti-vclab/meshlab/blob/main/src/README.md#build-meshlab). And you don't need to build it, you can just download it from [here](https://www.qt.io/download-qt-installer-oss?hsCtaTracking=99d9dd4f-5681-48d2-b096-470725510d34%7C074ddad0-fdef-4e53-8aa8-5e8a876d6ab4). Then you need to run the scripts (they are automatically run by github actions at every commit on this repo, for example).
- What do you mean with multiple cores? What do you mean with slow performances? Is it the rendering, applying filters, or what? There are only a few filters that run on multi thread
