### ISSUE TITLE
as a mesh editor/creator, this is very hard to use

### ISSUE THREAD

**Issue by goofyseeker311** [cnr-isti-vclab/meshlab#1375]
compare to editors like fusion 360, which is focused on simple primitive management/creation process.

why would you save each mesh as separate file, not one single file, and have save dialog for each.
how do you export the full combined mesh as one .stl/.obj etc. why do you move meshes when doing union.

**Comment by alemuntoni** [comment]
Because if there are separate layers, it means that the user wants to treat them as separate.
If you want to have all the layers in a single file, just apply the "flatten visible layers" before saving.
