### ISSUE TITLE
Screened Poisson Surface Reconstruction not working with meshlabserver when built from source

### ISSUE THREAD

**Issue by omhafez** [cnr-isti-vclab/meshlab#138]
Rather than comment on a closed issue, I'll open a new issue. Apologies for the repeat but this is still outstanding:

I build Meshlab 2016.12 on 64-bit Ubuntu 14.04 from @zarquon42b's PPA. As much as I'd prefer to use the snap version, I ultimately need to use this on the Linux subsystem on Windows 10, which does not support snaps. The following error I will describe _is_ on a native Linux system though.

I install the PPA like so:
```
sudo add-apt-repository ppa:zarquon42/meshlab
sudo apt-get update
sudo apt-get install meshlab
```

I run the following from command line:
`meshlabserver -i ptcloud.ply -o surface.ply -s screen.mlx`
where ptcloud.ply is a point cloud, and screen.mlx looks as follows:

```
<!DOCTYPE FilterScript>
<FilterScript>
 <xmlfilter name="Screened Poisson Surface Reconstruction">
  <xmlparam value="0" name="cgDepth"/>
  <xmlparam value="false" name="confidence"/>
  <xmlparam value="12" name="depth"/>
  <xmlparam value="5" name="fullDepth"/>
  <xmlparam value="8" name="iters"/>
  <xmlparam value="4" name="pointWeight"/>
  <xmlparam value="false" name="preClean"/>
  <xmlparam value="1.5" name="samplesPerNode"/>
  <xmlparam value="1.1" name="scale"/>
  <xmlparam value="false" name="visibleLayer"/>
 </xmlfilter>

 <filter name="Change the current layer">
  <Param tooltip="The name of the current mesh" type="RichMesh" value="0" name="mesh" description="Mesh"/>
 </filter>

 <filter name="Delete Current Mesh"/>
</FilterScript>
```

Yet, I get the following error in the output:
```
Apply FilterScript: '/home/omar/projects/shabaka/reslt/sphere/screen.mlx'
FilterScript
Reading filter with name Screened Poisson Surface Reconstruction
Starting Script of 1 actionsfilter: Screened Poisson Surface Reconstruction
LOG: 1 WARNING! The MeshLab Script System is able to manage just the C++ XML filters.
Problem with filter: Screened Poisson Surface Reconstruction
```

Interestingly, the filter does show up in the GUI and works fine.

And worth noting @mcallieri, filter_screened_poisson.xml now already exists in /usr/lib/meshlab/plugins after installing from the PPA, which probably explains why it shows up the GUI now. But I am interested in using the filter from the command line and the error in the previous comment still persists..

I want to emphasize that this exact procedure works with the snap version of Meshlab 2016.12 on native Ubuntu, on MacOS Sierra, and even on Windows 10 using PowerShell.

Thanks,
Omar

**Comment by granzuglia** [comment]
The problem is related with the fact that you should copy the filter_screened_poisson.xml file inside the ../../distrib/plugins folder. But It should happen automatically when you recompile MeshLab. 
The devoted line of code is in filter_screened_poisson.pro:

linux:QMAKE_POST_LINK = "cp "$$_PRO_FILE_PWD_/$$TARGET".xml ../../distrib/plugins/"$$TARGET".xml; cd ../../distrib/plugins/ ; ln -s "$$TARGET".xml lib"$$TARGET".xml"

Sometimes it happen that each linux system has its own specific tag. So instead of "linux" you can have something  like "linux-64", avoiding the automatic relocation of the file in the correct folder. Anyway, in the meanwhile we try to find all the possible tags for the various linux system, can you just try if the manual copying of the file solve the problem?

Thanks

**Comment by omhafez** [comment]
@granzuglia Thank you for your response. Unfortunately I've moved past this issue and cannot really devote any more time to it. But I will note that I downloaded the source code from [meshlab.net](url) just now, and took a look at filter_screened_poisson.pro in the following directory: 
`meshlab-2016.12/src/meshlabplugins/filter_screened_poisson/`
In that file I find the line you refer to, but surprisingly find the following rule mac instead of linux:

**macx**:QMAKE_POST_LINK = "cp "$$PRO_FILE_PWD/$$TARGET".xml ../../distrib/plugins/"$$TARGET".xml; cd ../../distrib/plugins/ ; ln -s "$$TARGET".xml lib"$$TARGET".xml"

Thanks,
Omar
