### ISSUE TITLE
Failure of filter 'Select by Vertex quality' 

### ISSUE THREAD

**Issue by ngmacha** [cnr-isti-vclab/meshlab#1384]
This is with reference to issue #1224: 

MeshLab ver 2022.02 on Windows 10 x64: applying 'Select by Vertex Quality' gets filter failure "No parameter with name Inclusive found in RichParameterList'
![image](https://github.com/cnr-isti-vclab/meshlab/assets/883534/d09fd217-4685-4229-9631-a6b818de4978)

**Comment by alemuntoni** [comment]
This issue has been already fixed. The fix will be available in the next meshlab version, or you can try  it by downloading any of the last nightly versions,
