### ISSUE TITLE
Select by Vertex Quality doesn't work

### ISSUE THREAD

**Issue by terrielsimmons** [cnr-isti-vclab/meshlab#1388]
"Select by Vertex Quality" hasn't worked for a while now. I am using 2022.02 on Windows. After comparing meshes or doing anything that stores a value in vertex quality, I can do everything (compute histograms, stats, etc) except select vertices by vertex quality. For some use cases, I just transfer the vertex quality to face quality and select that way. Is this a known issue and is there any way to get around it?

![2023-05-24_11-26-32](https://github.com/cnr-isti-vclab/meshlab/assets/46006221/593ae9f1-56e9-41d1-946c-b590cb88cc9a)

**Comment by alemuntoni** [comment]
This issue has been already solved, we will provide a new version of MeshLab soon (in a month, hopefully) with this fixed.
