### ISSUE TITLE
Hovering over Layer Dialog focuses the application

### ISSUE THREAD

**Issue by Zoodinger** [cnr-isti-vclab/meshlab#139]
Application is focused when the cursor hovers over Layer Dialog, even if Meshlab is not the currently active window (but not when obscured by other windows).

My version is compiled on CentOS 7 from source.

**Comment by mcallieri** [comment]
yes, confirmed.
Frankly, I have no idea why this was necessary. I removed it in 43b042d60a0620d72a4b7edd66a83042696a1a14
It may need some testing to see if there was a hidden reason to do so
