### ISSUE TITLE
I use pip to install pymeshlab in my server, but it goes wrong

### ISSUE THREAD

**Issue by zhangzhr4** [cnr-isti-vclab/meshlab#1390]
Warning:
Unable to load the following plugins:

        libio_e57.so: libio_e57.so does not seem to be a Qt Plugin.

Cannot load library /home/xxx/anaconda3/envs/rembg/lib/python3.9/site-packages/pymeshlab/lib/plugins/libio_e57.so: (/lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0)

As the title describing, I use pip to install pymeshlab in my remote server (it does not have GUI), I also install Meshlab in it, but I can not fix this bug, if there any solutions?
Maybe the main reason is the no-GUI linux server? I am very confused!
Thanks!

**Comment by alemuntoni** [comment]
This is a warning. You should be able to run pymeshlab anyway.
Moreover, with pymeshlab we don't support anaconda. Try it in a clean python environment.
