### ISSUE TITLE
Meshlab crashed on .stl import from a Lidar scan and now my MacBook is not working. Mid 2015 MacBook pro running OS X 12.6.6, MeshLab2022.02 2, .STL file exported from polygon pro app on iPhone 13 pro using LiDar. After the .stl loaded into meshlab, the screen went black, I used a force shut down and tried to reboot and the screen came on for a few seconds with multi colored random lines across it, so force shut down again. Now all it does is chime when powered on and only has a black screen. Things I've tried are: PRAM/NVRAM/SMC reset, safe/recovery mode boot, power-s key-force shut down sequence but nothing has worked. Any ideas about next steps?

### ISSUE THREAD

**Issue by noahjack** [cnr-isti-vclab/meshlab#1391]
#Please read carefully before submitting an issue

- be as detailed as possible while describing an issue:
  - which platform are you using (say it also on the subject of the issue)
  - which version of meshlab are you using (e.g. 2020.09 portable. 2020.06 snap, 2020.12 installer)
  - be sure that the issue is reproducible: list step by step all the operations performed to reproduce the issue
  - if it applies, share all the involved files
- if it is possible, verify if the problem persists in other platforms;
- be sure that your issue also happens on the most recent MeshLab version;
- check if your issue has been already reported by someone else. In this case, do not open another issue: just add your experience in the existing issue;
- delete these guidelines before submitting :)

If it is not an issue but something else (need help, feature request, ...) consider to use github discussion: https://github.com/cnr-isti-vclab/meshlab/discussions

**Comment by alemuntoni** [comment]
MeshLab can't break a computer. There is probably something broken in your hardware or in the OS. 
You should contact the Apple support.
