### ISSUE TITLE
Raster alignment tool point picking

### ISSUE THREAD

**Issue by irenelunghi** [cnr-isti-vclab/meshlab#1396]
When I use the raster alignment tool, I can't pick 3D or 2D points after adding them in the list. The points automatically set on the origin axes and if I pick the mesh and/or the raster image I can't move them. I can only move them setting manually the value on the box, but it's very difficult to find the homologous points in this way.
The mouse wheel also not allows controlling opacity of the raster. 

Meshlab version: MeshLab 2022.02
Windows 11 Pro, version 22H2

**Comment by alemuntoni** [comment]
Hi, could you please share some inputs (rasters and meshes) and instructions that allow us to reproduce the issue?
