### ISSUE TITLE
IFXCoreList.cpp:(.text+0xbc)：对‘operator delete(void*, unsigned long)’未定义的引用

### ISSUE THREAD

**Issue by dizhenx** [cnr-isti-vclab/meshlab#1398]
MakeFiles/IFXCore.dir/RTL/Kernel/IFXCom/CIFXPluginProxy.cpp.o：在函数‘CIFXPluginProxy::Release()’中：
CIFXPluginProxy.cpp:(.text+0x1b6)：对‘operator delete(void*, unsigned long)’未定义的引用
CMakeFiles/IFXCore.dir/RTL/Kernel/IFXCom/IFXCom.cpp.o：在函数‘IFXCOMInitialize’中：
IFXCom.cpp:(.text+0x92)：对‘operator delete(void*, unsigned long)’未定义的引用
CMakeFiles/IFXCore.dir/RTL/Kernel/DataTypes/IFXCoreList.cpp.o：在函数‘IFXCoreList::IFXCoreList()’中：
IFXCoreList.cpp:(.text+0xbc)：对‘operator delete(void*, unsigned long)’未定义的引用
CMakeFiles/IFXCore.dir/RTL/Kernel/DataTypes/IFXCoreList.cpp.o:IFXCoreList.cpp:(.text+0x13c): 跟着更多未定义的参考到 operator delete(void*, unsigned long)
collect2: 错误：ld 返回 1
make[2]: *** [src/external/downloads/u3d-1.5.1/libIFXCore.so] 错误 1
make[1]: *** [src/external/downloads/u3d-1.5.1/CMakeFiles/IFXCore.dir/all] 错误 2
make: *** [all] 错误 2
When run make，that happens。How to solve it？

**Comment by alemuntoni** [comment]
Could you please elaborate? What is your issue?
