### ISSUE TITLE
Exporting to obj with texture causes object to be marked as transparent by default

### ISSUE THREAD

**Issue by shameekganguly** [cnr-isti-vclab/meshlab#1399]
When exporting a mesh with textures as OBJ, the generated mtl file has transparency set to 1 by default, that is `Tr 1`

**Comment by alemuntoni** [comment]
This was already fixes in [this commit](https://github.com/cnr-isti-vclab/vcglib/commit/4c4636dbe5b944e9d1d025e3086a011ceb50dd15), the fix will be available in the next meshlab version
