### ISSUE TITLE
Layer Dialog does not like long file names

### ISSUE THREAD

**Issue by Zoodinger** [cnr-isti-vclab/meshlab#140]
When opening a file with a long name, the Layer Dialog gets resized to fit the name. However, I can no longer resize it back to a sensible width, even if the mesh is renamed/removed or even when the project is closed. The only way to reset it is to close and restart the application.

**Comment by mcallieri** [comment]
yes, confirmed. I'm looking into it, but until now I have not been able to pin down the problem. Sorry.

**Comment by AymericFerreira** [comment]
Hello,

I still have the problem with MeshLab 2020.02, any fixes possible  ?

Thank you

**Comment by alemuntoni** [comment]
the issue has been "fixed" in the last commit. It is not a proper fix, since it just truncates mesh names when they are longer than a fixed size, but it should be fine for now.
