### ISSUE TITLE
 select corner border

### ISSUE THREAD

**Issue by GeorgesSadaka** [cnr-isti-vclab/meshlab#1409]
Hello,
I have a surface rectangular mesh, I want to know if there is a way to select only triangle at the 4 corners?
I can select them manually.
The idea is to invert selection of these cells, and use the Taubin smooth to smooth the surface with smoothing the corner.
Thanks in advance
GS

**Comment by jmespadero** [comment]
To my knowledge, this is not possible in meshlab, but you could do some work in pyMeshLab if the rectangle is axis-aligned. 

The nearest you can do is:
* Select border
* Invert Selection

And, depending of the topology of your mesh it may help (or not)
* Select border
* Invert Selection
* Erode Selection x1
* Dilate Selection x2

This will achieve something like this, which may be useful or not:

![imagen](https://github.com/cnr-isti-vclab/meshlab/assets/6451497/847fbf87-e506-417c-a096-a15d78ed8a32)

**Comment by GeorgesSadaka** [comment]
Dear jmeaspadero,
thanks you for your reply, I tried your solution but it was not what I'm looking for, instead of this I succeed to do it like this :
I put inside the boolean function inside the conditional face selection :
((x0<=xmin+eps) && (y0<=ymin+eps)) || ((x0<=xmin+eps) && (y0>=ymax-eps)) || ((x0>=xmax-eps) && (y0>=ymax-eps)) || ((x0>=xmax-eps) && (y0<=ymin+eps))
where xmin, xmax, ymin, ymax are my bounding box of the mesh and the eps is small parameter

**Comment by jmespadero** [comment]
That is a correct solution. Glad you solved your problem.


@alemuntoni Would you think it would be interesting adding "xmin", "xmax", etc... as predefined token in muParser so users can develop such kind of filters without without the help of a "external piece of paper". Would you accept this kind of Pull Request if I program it?

My idea is to add tokens for values taken from "Compute Geometric Measures " filter,
so maybe these 14 token to be defined.

 Bounding Box Size -> xdim ydim zdim
 Bounding Box Diag -> bbdiag
 Bounding Box min   -> xmin ymin zmin
 Bounding Box max  -> xmax ymax zmax
 Surface Area is        -> meshArea
 Vertices barycenter  -> xcentroid ycentroid zcentroid

**Comment by alemuntoni** [comment]
Yes, I would definitely accept it. It would be quite useful!
