### ISSUE TITLE
Menu options aren't disabled when projects are closed

### ISSUE THREAD

**Issue by Zoodinger** [cnr-isti-vclab/meshlab#141]
Most menu options are disabled when a project with no meshes is selected. However, they still stay enabled when all projects close.

Selecting a menu item that shouldn't be enabled causes the application to crash with a segmentation fault. The crashing doesn't happen with ALL menu items that should be disabled, but it happens at least with "Export mesh [as]", "Save snapshot" and "Append project to current".

**Comment by mcallieri** [comment]
Partly duplicated: fixed in 820e6634e3f5c668a0966f528507d33f773d3fb3 for most menus, and 08d58a97ce72c24de977d0062fc0c226ab8586e0 for screenshot and import raster
