### ISSUE TITLE
Meshlab compiling example for Windows

### ISSUE THREAD

**Issue by ebarnett2** [cnr-isti-vclab/meshlab#142]
Windows 7 64-bit, Qt 5.7.1 msvc2015_64-5.7.1

I had a lot of trouble getting MeshLab to compile in Windows, so I have summarized the procedure that worked for me below. Initially, I successfully compiled Meshlab in Ubuntu, based on the instructions of jnweiger and BETLOG here:

https://github.com/cnr-isti-vclab/meshlab/pull/68#issuecomment-292308094

I have attempted to follow their instructions for Windows as closely as possible.

1. Download and install Visual C++ 2015 Build Tools 2015:
http://landinghub.visualstudio.com/visual-cpp-build-tools
Use the default install options.

2. Download and install Qt 5.7.1:
http://download.qt.io/official_releases/qt/5.7/5.7.1/qt-opensource-windows-x86-msvc2015_64-5.7.1.exe
During Setup, I unselected Qt WebEngine.

3. Download ZIP files for meshlab (master branch) and vcglib (devel branch) source code:
https://github.com/cnr-isti-vclab/meshlab
https://github.com/cnr-isti-vclab/vcglib/tree/devel

-Extract both ZIP files to the same folder
-Rename the "meshlab-master" folder "meshlab"
-Rename the "vcglib-devel" folder "vcglib"

4. Open the Visual C++ 2015 x64 Native Build Tools Command Prompt (not the regular Windows Command Prompt):
Start->Visual C++ Build Tools->Windows Desktop Command Prompts->Visual C++ 2015 x64 Native Build Tools Command Prompt

Run the following commands (don't run the text in brackets):

cd "[folder]\meshlab"
([folder] is the folder that meshlab was extracted to above, e.g., "C:\myCompiledCode\meshlab")

[disk]:
([disk] is the disk containing [folder], e.g., "c:")

SET qm=C:\Qt\Qt5.7.1\5.7\msvc2015_64\bin\qmake "CONFIG+=no_batch CONFIG+=release CONFIG +=qml_release CONFIG+=c++11 QMAKE_CXXFLAGS+=-fPIC QMAKE_CXXFLAGS+=-std=c++11 QMAKE_CXXFLAGS+=-fpermissive QMAKESPEC+=win32-msvc2015"

%qm% -recursive external.pro
nmake

cd ..\common
%qm% common.pro
nmake

cd ..
%qm% meshlab_mini.pro
nmake

%qm% meshlab_full.pro
nmake

Some of the  nmake commands take several minutes to execute. If everything completes successfully, the meshlab executable file will be in "[folder]\meshlab\src\distrib".

To get it to run, you will need to copy the following files from "C:\Qt\Qt5.7.1\5.7\msvc2015_64\bin" to "[folder]\meshlab\src\distrib":
Qt5Core.dll
Qt5Gui.dll
Qt5Network.dll
Qt5OpenGL.dll
Qt5Script.dll
Qt5Widgets.dll
Qt5Xml.dll
Qt5XmlPatterns.dll

Alternatively, you can add "C:\Qt\Qt5.7.1\5.7\msvc2015_64\bin" to the Windows Path Environment Variable.

One problem that I noticed with my installation: The screened Poisson surface reconstruction filter was missing from the filters menu in the GUI, even though the library was compiled successfully and was copied to the distrib\plugins folder. I discovered that the XML file associated with the DLL was not copied. After executing the command

copy .\meshlabplugins\filter_screened_poisson\filter_screened_poisson.xml .\distrib\plugins

the filter appeared in the GUI and ran successfully. Upon comparing the plugins folder for my compiled meshlab to the version created using the installation package downloaded from http://www.meshlab.net/#download, I see that none of the XML files were copied for the four plugins that require these files. This can be resolved by running the commands:

copy .\meshlabplugins\filter_measure\filter_measure.xml .\distrib\plugins
copy .\meshlabplugins\filter_mutualinfoxml\filter_mutualinfo.xml .\distrib\plugins
copy .\meshlabplugins\filter_sketchfab\filter_sketchfab.xml .\distrib\plugins

**Comment by vnarasimhan** [comment]
I got a working Windows Build. Sharing some information here.

**Versions**

Windows 10 Pro
Visual Studio Community 2017
QT 5.7
vcglib **devel** branch, 912e78c4cf57fe8daa6e16271bffebf2a0c33bf9
meshlab **master** branch, e4d49f2106d2f8228a67f8b43a9f8a9c573bdcac

**Build Console**

Open a Cmd prompt and run below two batch files IN THE SAME console
```

Microsoft Windows [Version 10.0.16299.125]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Demo>C:\Windows\System32\cmd.exe /A /Q /K D:\Qt5\5.7\msvc2015_64\bin\qtenv2.bat
Setting up environment for Qt usage...
Remember to call vcvarsall.bat to complete environment setup!

D:\Qt5\5.7\msvc2015_64>%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.5.7
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
```

**Folder structure**

```
C:\Demo\meshLabBuild>dir
 Volume in drive C has no label.
 Volume Serial Number is E04D-302D

 Directory of C:\Demo\meshLabBuild

03/07/2018  05:36 PM    <DIR>          .
03/07/2018  05:36 PM    <DIR>          ..
03/06/2018  05:04 PM    <DIR>          meshlab
03/06/2018  08:15 PM    <DIR>          vcglib
               0 File(s)              0 bytes
               4 Dir(s)  193,662,824,448 bytes free
```

**Build external modules**

```
C:\Demo\meshLabBuild>cd meshlab\src\external

C:\Demo\meshLabBuild\meshlab\src\external>qmake.exe external.pro

C:\Demo\meshLabBuild\meshlab\src\external>nmake release

```
**Build meshlab**

```
C:\Demo\meshLabBuild\meshlab\src\external>cd ..

C:\Demo\meshLabBuild\meshlab\src>qmake meshlab_full.pro

C:\Demo\meshLabBuild\meshlab\src>nmake release

```
**Ensure QT DLLs in PATH**

```
C:\Demo\meshLabBuild\meshlab\src\distrib>SET PATH=D:\Qt5\5.7\msvc2015_64\bin:%PATH%
C:\Demo\meshLabBuild\meshlab\src\distrib>echo %PATH%
D:\Qt5\5.7\msvc2015_64\bin:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64;

```
**Crash on first run?**

2 plugins (filter_isoparametrization.dll, filter_ssynth.dll) failed to load for me. meshlabserver terminated with an exception. To track down these failures, I added below code - have copy pasted diff from a msys console.

```
$ git diff
diff --git a/src/common/mlexception.h b/src/common/mlexception.h
index 6c6ab8d4..20864c69 100644
--- a/src/common/mlexception.h
+++ b/src/common/mlexception.h
@@ -7,7 +7,7 @@ class MLException : public std::exception
 {
 public:
        MLException(const QString& text)
-               :std::exception(),excText(text){_ba = excText.toLocal8Bit();}
+               :std::exception(), excText(text) { _ba = excText.toLocal8Bit(); qDebug(_ba.constData()); }

        ~MLException() throw() {}
        inline const char* what() const throw() {return _ba.constData();}
diff --git a/src/meshlabserver/mainserver.cpp b/src/meshlabserver/mainserver.cpp
index efeac055..ad62a69d 100644
--- a/src/meshlabserver/mainserver.cpp
+++ b/src/meshlabserver/mainserver.cpp
@@ -685,8 +685,32 @@ struct OutProject
     bool overwrite;
 };

+void myMessageOutput(QtMsgType type, const QMessageLogContext &context, const QString &msg)
+{
+       QByteArray localMsg = msg.toLocal8Bit();
+       switch (type) {
+       case QtDebugMsg:
+               fprintf(stderr, "Debug: %s (%s:%u, %s)\n", localMsg.constData(), context.file, context.line, context.function);
+               break;
+       case QtInfoMsg:
+               fprintf(stderr, "Info: %s (%s:%u, %s)\n", localMsg.constData(), context.file, context.line, context.function);
+               break;
+       case QtWarningMsg:
+               fprintf(stderr, "Warning: %s (%s:%u, %s)\n", localMsg.constData(), context.file, context.line, context.function);
+               break;
+       case QtCriticalMsg:
+               fprintf(stderr, "Critical: %s (%s:%u, %s)\n", localMsg.constData(), context.file, context.line, context.function);
+               break;
+       case QtFatalMsg:
+               fprintf(stderr, "Fatal: %s (%s:%u, %s)\n", localMsg.constData(), context.file, context.line, context.function);
+               abort();
+       }
+}
+
 int main(int argc, char *argv[])
 {
+       qInstallMessageHandler(myMessageOutput);
+
     FILE* logfp = stdout;
     FILE* dumpfp = NULL;
     MeshLabApplication app(argc, argv);


```

**Copy plugin XMLs**

As mentioned by the earlier poster, it is necessary to copy plugin XMLs into the distrib\plugins folder.

```
 Directory of C:\Demo\meshLabBuild\meshlab\src\distrib\plugins

03/06/2018  05:04 PM             6,837 filter_measure.xml
03/06/2018  05:04 PM             3,124 filter_mutualinfo.xml
03/06/2018  05:04 PM             5,612 filter_screened_poisson.xml
03/06/2018  05:04 PM             2,580 filter_sketchfab.xml
03/06/2018  05:04 PM            14,269 filter_voronoi.xml
               5 File(s)         32,422 bytes
               0 Dir(s)  193,659,273,216 bytes free
```

**Comment by mcallieri** [comment]
We have now an automatic build system for MeshLab on Windows.
https://ci.appveyor.com/project/cignoni/meshlab

we are using, at the moment:
- Visual Studio 2015
- QT 5.9

with Visual Studio 2017 there is a QT bug when creating the solutions, that require you manually change the target platform.
QT 5.10 produce some issues with menus and rendering, so we are sticking to 5.9 (long term support).
With the commits of the last months, the XML are directly copied in the correct folder.

The current WIN64 build can be found here

https://ci.appveyor.com/project/cignoni/meshlab/build/artifacts

It is not an installer, just a zipped folder with a "portable" executable. We are starting testing, now, while fixing few more issues. We have used on some machines, here, and seems working. I have no idea, however if it has ALL the possible dll and Runtime that may be needed.

If there is an ongoing build, the site will write "The build job does not contain any artifacts.". In that case, you may wait for the build to end or just click "HISTORY", select the last succesful build, and then "ARTIFACTS"

**Comment by lookiamluke** [comment]
From all of us still using Meshlab and running windows --- THANK YOU for continuing to compile it for us. As much as I love Meshlab, trying to figure out how to compile it myself would be a very long and error prone process. You're doing God's work, my friend!
