### ISSUE TITLE
STL face color

### ISSUE THREAD

**Issue by GiovanniSer** [cnr-isti-vclab/meshlab#1423]
Hi all,
I don't know if this is of interest but it is very useful to me.
The STL file format does not normally handle face colors.
However, even if it is not documented, the developers have found a place for color in binary STL files.
In ASCII STL files, however, color cannot be used.
For many reasons ascii STL files are useful (For example, AutoLisp, incredible but true, does not handle single precision numbers), and so I came up with a way. In the line position that I show no program gives an error. 

And I archive the color so I don't lose it.
I came up with this syntax:
```
 facet normal 0 0 1
  outer loop
   vertex 6.34871011 6.87823834 0
   vertex 2.06788109 3.50113990 0
   vertex 8.33057539 2.05834197 0
  endloop
 endfacet color **herethecolor**
```
where herethecolor is the colors RGB number (converted in the STL subset used in binry files)
This system could be easily implemented, as a proprietary MeshLab system, which however, importantly, is compatible even if ignored by other programs.
NOTE : Be careful, do not test with a few faces in ASCII. At least half a dozen are needed. It's a ML's old problem I reported. If there are few faces, ML believes it is binary and generates an error.
B.R.
G.

**Comment by alemuntoni** [comment]
I am not sure this should be implemented into MeshLab... I just think that, if someone needs to store face color, they should use another file format and do not stick with STL. Also face colors in the binary STL are a hack that could be not supported. 
STL is just not the proper file format to store these information.

**Comment by GiovanniSer** [comment]
Mine was just an observation. MeshLab however supports colors in binary STLs, like many other programs. I hope it doesn't get removed. Using STLs is very useful for those who work in 3D printing like me, because it avoids the need for converters with the problems they often generate. Color is certainly used not for aesthetic reasons but to aid part selections. So I hope you don't remove this utility that MeshLab already has in the binary files. Thank you!

**Comment by alemuntoni** [comment]
I am not going to remove features, don't worry. :)
I just don't think that adding other non-standard features that could break compatibility with other tools is a good idea.
Thanks anyway for the suggestion!

**Comment by GiovanniSer** [comment]
I understand, I currently use Meshlab to control almost step by step what I'm doing in CAD, Autolisp can write text STL while I work at run time. So I need traslate to binary (some seconds) before import the file in ML. The colors are very useful in the check, I understand that it is my personal method, but I assure you that even in the text format I have never had incompatibilities. Lately tested also on mobile viewers, which in that case ignore it.
Thanks!
![Clipboard01](https://github.com/cnr-isti-vclab/meshlab/assets/67306481/dbcbfc90-977c-41e1-b37a-1d8b08f00d21)
