### ISSUE TITLE
[ubuntu 22.04] MeshLab crashes after closing the 2nd project

### ISSUE THREAD

**Issue by MatthijsBurgh** [cnr-isti-vclab/meshlab#1425]
I have experienced this issue in both the 2022.02(github) and the 2020.09(apt) release.

I open a mesh file. I close the project. And I open the mesh file again. When closing the project again, meshlab crashes.

```bash
./MeshLab2022.02d-linux.AppImage 
Using OpenGL 4.6
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id
qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
LOG: 0 Opened mesh /home/USER/Downloads/SOME_MESH.stl in 855 msec
LOG: 0 All files opened in 1963 msec
Using OpenGL 4.6
LOG: 0 Opened mesh /home/USER/Downloads/SOME_MESH.stl in 816 msec
LOG: 0 All files opened in 2048 msec
Segmentation fault (core dumped)
```

**Comment by alemuntoni** [comment]
Could you please try the [last nightly release from the devel branch](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version) to check if the issue still persists? This issue should be already solved.

**Comment by MatthijsBurgh** [comment]
I do not experience this issue when using the AppImage double precision from https://github.com/cnr-isti-vclab/meshlab/actions/runs/6532222643.

**Comment by alemuntoni** [comment]
Great, thanks! The fix will be available in the next meshlab version.
