### ISSUE TITLE
Mesh decimation of Sponza atrium crashes

### ISSUE THREAD

**Issue by StudenteChamp2** [cnr-isti-vclab/meshlab#1428]
I am trying to decimate the Sponza atrium model. All the decimation methods crash:

- Simplification: Clustering Decimation
- Simplification: Quadric Edge Collapse Decimation
- Simplification: Quadric Edge Collapse Decimation(with texture)

The model as well as the textures is available here:
https://casual-effects.com/g3d/data10/common/model/crytek_sponza/sponza.zip

Thanks for helping!

**Comment by alemuntoni** [comment]
This issue has been already solved, and the fix will be available in the next MeshLab version. 
You can try it by downloading any of the last [nightly versions](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version).

**Comment by StudenteChamp2** [comment]
Thank you :) Was it a VCGlib bug?

**Comment by StudenteChamp2** [comment]
Just tried. It still crashes :O
