### ISSUE TITLE
No rule to make trackball.cpp, needed by trackball.o

### ISSUE THREAD

**Issue by heatblazer** [cnr-isti-vclab/meshlab#143]
Hello, I am trying to make meshlab following the instructions from the doc in the `src` folder, but I am reaching `:-1: error: No rule to make target '../../../vcglib/wrap/gui/trackball.cpp', needed by 'trackball.o'.  Stop.` in the qtcreator.

**Comment by nh2** [comment]
That happens when you don't have a clone of https://github.com/cnr-isti-vclab/vcglib next to the directory in which your meshlab clone is.

Your directory layout should look like this:

```
$ ls -1
meshlab
vcglib
```

(I say "should", but personally I find it silly that it needs to be this way, IMO this should be configurable.)

**Comment by granzuglia** [comment]
You are right nh2.
