### ISSUE TITLE
Can open mainwindow in Qtdesign?

### ISSUE THREAD

**Issue by HungNgoCT** [cnr-isti-vclab/meshlab#1431]
Hi,

Thank you for the wonderful work.

I built meshlab in Qt. Now can run.

For easily do experiments on a function, I need to retrieve the function from GUI. However, I did not know how to load the mainwindow in QtCreator (Qtdesign) to do that.

Is there anyway I can load GUI in Qtdesign?

Thank you for your help.

**Comment by alemuntoni** [comment]
There are no UI files of the mainwindow. Everything is made trough code in the MainWindow class. 
Please, do not open issues and discussions with the same text. One is just enough.

**Comment by HungNgoCT** [comment]
> There are no UI files of the mainwindow. Everything is made trough code in the MainWindow class. Please, do not open issues and discussions with the same text. One is just enough.

Thank you @alemuntoni
