### ISSUE TITLE
crash attempting Iso Parameterization: Main

### ISSUE THREAD

**Issue by wtholliday** [cnr-isti-vclab/meshlab#1456]
- macOS 14.2.1 (23C71) arm
- Meshlab 2023.12

To reproduce:
1. Filter -> Create New Mesh Layer -> Icosahedron
2. Filter -> Remeshing, Simplification and Reconstruction -> Iso Parameterization: Main
3. Click Apply
4. Crash

(I'm aware this algorithm wants a bigger mesh. Still shouldn't crash)

**Comment by alemuntoni** [comment]
Thanks for reporting!
