### ISSUE TITLE
Meshlab crash when loading this .obj file on Ubuntu but not on Windows.

### ISSUE THREAD

**Issue by pchaillo** [cnr-isti-vclab/meshlab#1457]
Meshlab crash when loading this .obj file on Ubuntu but not on Windows : 
I've tested my file on two different computer with the same version of Ubuntu, and both crash when I tried to load them into Meshlab

OS : Ubuntu 22.04.1 LTS and Ubuntu 22.04.2 LTS (bug happen on both computer).
Meshlab version : 2020.09
3D files : [_foie_deuxieme_jour__Thibaud6_projection_clean_cutted.zip](https://github.com/cnr-isti-vclab/meshlab/files/13886332/_foie_deuxieme_jour__Thibaud6_projection_clean_cutted.zip)

I succeed to load it on Meshlab on a windows computer : 
![beef_03_reconstruct_in_3D](https://github.com/cnr-isti-vclab/meshlab/assets/99733932/e768545a-e36e-4ad1-9eb8-944da4ac0c6c)
It was an old computer, with Windows Vista (I don't have access to the version of Meshlab on that computer now, but I may get the information if needed.

Full error in terminal : 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Current Plugins Dir is: /usr/lib/x86_64-linux-gnu/meshlab/plugins 
Shader directory found '/usr/share/meshlab/shaders', and it contains 19 gdp files
meshlab: ./vcglib/wrap/io_trimesh/import_obj.h:640: static int vcg::tri::io::ImporterOBJ<OpenMeshType>::Open(OpenMeshType&, const char*, vcg::tri::io::ImporterOBJ<OpenMeshType>::Info&) [with OpenMeshType = CMeshO]: Assertion `(numTriangles +numVertices) == numVerticesPlusFaces+extraTriangles' failed.
Aborted (core dumped)

I create this .obj file using the pymeshlab API, I may also transmit this code if needed (but as the file may be opened on Windows computer, it's not the cause of the bug).

I hope you have everything you need to understand and reproduce the bug, otherwise tell me what's missing !

Thanks in advance for your help (and for maintaining Meshlab) ;)

**Comment by jmespadero** [comment]
Hi, 

Just comment that the file is loading correctly in my Ubuntu 22.04.2 LTS  linux for these versions of Meshlab: 
* MeshLab 2023.12 (double precision)
* MeshLab 2022.02 (double precision) 
* MeshLab 2021.10 (single precision) 

The error seems to be in a sanity check written in vcg::tri::io::ImporterOBJ ( `(numTriangles +numVertices) == numVerticesPlusFaces+extraTriangles' failed) that is not present in newer versions  of meshlab.

Is it possible for you to upgrade to a new Meshlab version? It is posible to use .ply file format instead .obj file format?

**Comment by alemuntoni** [comment]
I can confirm that the version in the official ubuntu repos has this bug when opening objs. 
I hope that the ubuntu maintaners will update the meshlab apt package for the next 24.04 LTS...
