### ISSUE TITLE
Meshlab v2016.12 crashing for certain exports after decimation

### ISSUE THREAD

**Issue by patrickatomic** [cnr-isti-vclab/meshlab#146]
Under Linux, 
Meshlab v2016.12 seems to crash upon export for certain lidars. Generally, after decimating heavy geometry and exporting, it crashes with the following error message. It only happens to some geometry and I cannot put a finger to which geometry it happens to. Is it possible for me to test with the previous version of Meshlab?

Error message:
QLayout: Attempting to add QLayout "" to SaveMaskExporterDialog "MaskExporterDialog", which already has a layout
meshlab: ../../../../vcglib/vcg/simplex/face/pos.h:198: void vcg::face::Pos<FaceType>::FlipF() [with FaceType = CFaceO]: Assertion `f->FFp(z)->FFp(f->FFi(z))==f' failed.
/Volumes/af/tools/pipetools/installs/pipetools-new_render-4056/bin/af_meshlab.sh: line 6: 142957 Aborted                 $MESHLAB_LOCATION/meshlab "$@"

**Comment by mcallieri** [comment]
which format are you trying to save to?

**Comment by patrickatomic** [comment]
.obj

**Comment by mcallieri** [comment]
Why you have an assert in release? are you using the Snap Package, or have you built it yourself?
And it is strange a call to FlipF() inside an exporter...

**Comment by patrickatomic** [comment]
the artist who had the issue is not sure of what you're asking.. on my end, if you're asking if I built the meshlab myself, then yeah I did compile it for centos7.

**Comment by annekagoss** [comment]
I've had the same issue with the web download.
