### ISSUE TITLE
Import Mesh but does not appear in the viewer.

### ISSUE THREAD

**Issue by Stevecommand** [cnr-isti-vclab/meshlab#1462]
I tried to import a 3d file in .fbx but it does not appear inside the viewer port. I tried others same fomats model and no problem.

- be as detailed as possible while describing an issue:
  - Windows Microsoft 11 which platform are you using (say it also on the subject of the issue)
  - 2022.12, 2023.12 installer
  - Import Mesh > select the 3d object .fbx > ok
![Screenshot 2024-01-26 160417](https://github.com/cnr-isti-vclab/meshlab/assets/49393915/2824d81c-863a-4251-bed2-f325b053ada0)

**Comment by jmespadero** [comment]
Does your input file really has 14 million of vertex and 75 million of faces? This is not a ordinary surface.

**Comment by alemuntoni** [comment]
Closing due to lack of response from the OP.
