### ISSUE TITLE
Slow to non-functional after obj/ply import

### ISSUE THREAD

**Issue by MegByst** [cnr-isti-vclab/meshlab#147]
(Using windows 10 64, latest meshlab version)

I opened a fairly simple .obj file that I'd been working on in Meshlab, and it basically refused to work. The FOV was 60, and the FPS 0.2. The file's 3.10 MB, with 40K faces. Response timw was quite slow, with a lot of "Not Responding" warnings. Commands ran faster when the visual was toggled off.

Similar issues with .ply files from regard 3D.

**Comment by mcallieri** [comment]
Hi. Can you send me an example of the files that causes the issue?
If you cannot link them here, use callieri@isti.cnr.it

**Comment by MegByst** [comment]
In retrospect, it may be that the laptop I'm using isn't powerful enough to run meshlab properly (I used my old laptop before), though I hope that isn't the case. Here's the 7zip
[ring blank.zip](https://github.com/cnr-isti-vclab/meshlab/files/980281/ring.blank.zip)

**Comment by mcallieri** [comment]
I have chacked the model, and there is nothing strange in it. Moreover, with this kind of complexity (39K faces) even older laptop (5-7 years) should be able to render it with good performances, even when using an integrated videocard. Please check your driver, and any other possible problems on your laptop.
