### ISSUE TITLE
2023.12 Can't drag models into the program

### ISSUE THREAD

**Issue by crossmr** [cnr-isti-vclab/meshlab#1471]
Previously was using a 2022 version, finally got annoyed at the pop up and updated today. After update, I am no longer able to drag STLs directly into the program. Previously I could just grab the file and drag it onto the program and drop it in. Now I have to go through a file menu to get the model in, significant disruption to work flow. Is there a setting or something I need to enable/change in this newer version?

**Comment by alemuntoni** [comment]
Are you using windows? Did you restarted meshlab after installing the new version?
Drag and drop does not work when meshlab is run as administrator, and that happens in the first run from the installer.

**Comment by crossmr** [comment]
Ah yes, okay. I didn't realize that. Thank you very much that fixed it.
