### ISSUE TITLE
meshlab start ends up with error message

### ISSUE THREAD

**Issue by CleanaZ** [cnr-isti-vclab/meshlab#149]
After double-clicking on the meshlab desktop icon the program shows me an error message.
Please look at the attached screenshots.
My System: 
ASUS Notebook P53E
Intel Core i3-2310M
RAM: 4 GB
Windows 7 SP1 64bit german
![screenshot 001](https://cloud.githubusercontent.com/assets/1440458/25804653/0b82c02e-33fd-11e7-935f-759780e92072.png)
![screenshot 002](https://cloud.githubusercontent.com/assets/1440458/25804654/0b8eb05a-33fd-11e7-8a6b-7fb357877c6d.png)

**Comment by mcallieri** [comment]
Your laptop only has an integrated videocard. As MeshLab now uses a lot the GPU, is much more sensitive to driver issue. Mosto probagbly, the videocard  drivers are not up-to-date or they do not support all the features needed by te tool.
This issue has been discussed here #29
There is no guarantee solution, but some users were able to solve it updating or re-installing the videocard drivers.
