### ISSUE TITLE
How to install the last nightly version

### ISSUE THREAD

**Issue by StudenteChamp2** [cnr-isti-vclab/meshlab#1509]
I followed the instructions provided here:
https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version  

I want to download MeshLab_Windows_portable_x86_64 but it is not clickable:
![Screenshot 2024-07-18 210829](https://github.com/user-attachments/assets/e99c503b-dac8-48a5-954d-d07904d6b924)

**Comment by alemuntoni** [comment]
Just login to github, and the artifacts will be downloadable.
