### ISSUE TITLE
Feature request: Add quality to .XYZ export

### ISSUE THREAD

**Issue by danwbean** [cnr-isti-vclab/meshlab#151]
Currently the vertices may be exported with x, y, z, nx, ny, nz in the .xyz format.  Please add the option to add the **vertex quality value**.  MeshLab can calculate wonderful things and store them in vertex quality.  They would be very useful externally.

**Comment by danwbean** [comment]
Update.  The information I need is available through the PLY export.  You can delete this request.

**Comment by mcallieri** [comment]
You are perfectly right. We know we should provide a better way to export custom per-vertex data, for PLY format, but also for other ASCII-based formats. It is in our roadmap, however, not int he immediate future.
