### ISSUE TITLE
Low FPS on 2+ Point Clouds with vertex shading

### ISSUE THREAD

**Issue by ErlerPhilipp** [cnr-isti-vclab/meshlab#1513]
Hi,

I'd like to quickly compare point clouds created by my new surface reconstruction method. The point clouds have almost 10M points without colors, with normals. As soon as I load the 2nd point cloud, the performance drops critically. From ~60 FPS to ~5 FPS on a RTX 3090. This seems to be only with vertex shading, which I need for the normals. Memory is clearly not a problem with only 2 GB used.

Platform: Win 10, Meshlab 2023.12, RTX 3090

Steps to reproduce:
1. Get a point cloud, I used this one: https://drive.google.com/file/d/1XhB-_X-7utAtMyXKWOxNa7u7jda79FWy/view?usp=sharing
2. Double click on point cloud to open in Meshlab
3. Rotate it -> ~60FPS
4. Drag&drop the same point cloud in the same Meshlab window
5. Rotate it -> ~5FPS
6. Make sure both point clouds have vertex shading active (should be by default)

**Comment by devshgraphicsprogramming** [comment]
Are you on a laptop ?

I've had problems with the program starting on my RTX, it was running on my iGPU and running 30x slower.

**Comment by ErlerPhilipp** [comment]
Hi!
I'm on desktop with only the rtx 3090.

I tried a few more point clouds in the meantime. I think the fps don't scale limearly with the number of points. There seems to be a jump at 15M points. It seems independent from the point of view. Might be a bookkeeping issue.

**Comment by devshgraphicsprogramming** [comment]
> Hi! I'm on desktop with only the rtx 3090.
> 
> I tried a few more point clouds in the meantime. I think the fps don't scale limearly with the number of points. There seems to be a jump at 15M points. It seems independent from the point of view. Might be a bookkeeping issue.

Go into "settings" there's a Dedicated VRAM pool size, I think its defaulted to something stupidly low like 350 MB

I set it to 4096 and now its nice and healthy

btw at the bottom of the meshlab window where FPS is displayed it says what mode its rendering in, if you see `IMMEDIATE` it means the whole of the mesh data is not on the GPU and its being transiently pushed in chunks every frame (which is why your display speed drops to the speed of your PCIE bus).

**Comment by ErlerPhilipp** [comment]
There is a setting for VRAM dedicated to geometry data. I set it to 15 GB and it's fine at 60-100 FPS.

I'm not sure where to look for Ìmmediate`. I see `BO Rendering` all the time if that's the place.

Anyway, thanks a lot!

**Comment by devshgraphicsprogramming** [comment]
> There is a setting for VRAM dedicated to geometry data. I set it to 15 GB and it's fine at 60-100 FPS.
> 
> I'm not sure where to look for `Immediate`. I see `BO Rendering` all the time if that's the place.
> 
> Anyway, thanks a lot!

`BO Rendering` means the data is resident on GPU always.
