### ISSUE TITLE
Windows installer: installer shows dialog boxes if existing installation when silent switch is set

### ISSUE THREAD

**Issue by Rotzbua** [cnr-isti-vclab/meshlab#1524]
Platform: Windows 10
Meshlab version: from 2022.02 to 2023.12 

## Use case

Silent installation without any interaction.

## Steps to reproduce

- Existing installation
- Start silent installation
- Warning for existing installation pops up and question to uninstall first

## Possible solution

Skip warning and directly silent uninstall existing installation and continue with silent installation.

**Comment by alemuntoni** [comment]
Fixed in the last commit, it will be available in the next version. Thanks for reporting!
