### ISSUE TITLE
U3D export not working even with workaround fix

### ISSUE THREAD

**Issue by jirgg** [cnr-isti-vclab/meshlab#153]
I am having trouble with exporting to U3D format. I imported a VRML created in ArcScene software but when I export to U3D only the .tex file is created. I have seen the other issues (e.g. #33 ) raised so I tried the steps below to copy&paste the two folders, however this has not solved my issue. How can I export to a U3D?

- Go to https://github.com/cnr-isti-vclab/meshlab/
- press on the green button "clone or download" then on the button "download zip"
- open the zip and go to the folder meshlab-master\src\distrib\plugins
- there copy the folders U3D_OSX and U3D_W32
- open the folder where you installed MeshLab (if you are on windows usually it should be C:\Program Files\VCG\MeshLab)
- paste the two folders in C:\Program Files\VCG\MeshLab\plugins
- run again MeshLab and you should not have the problem again

**Comment by granzuglia** [comment]
I tried it following the workaround (that I wrote...) and it works. You should get two files the .tex and .u3d. After you have to compile them using a latex compiler, being sure you already installed all the latex dependency. Let me know if you have still the problem. Please note that it U3D exporter doesn't work on linux. Only on mac and windows.

**Comment by worm6666** [comment]
by Me it works after placing the both dirs into plugin directory... MeshLab x64_fp v2016.12 (build on Dec 23 2016)

**Comment by stla** [comment]
Works for me. Thank you. Amazing. 

However I get a small bug in the rendering. Look at the white part at the bottom left here:

![captureu3d](https://user-images.githubusercontent.com/4466543/37792111-304a6d40-2e0b-11e8-9413-b35767fd7ded.PNG)

This comes from an OBJ file that I found [here](https://www.yobi3d.com/q/3D-model/Klein-Bottle.obj). But I don't remember which one it is. It's a big file, 45 MB.

**Comment by stla** [comment]
Perhaps a problem with the bigness of the file. I"ve tested a small one and the rendering is perfect. Pan, zoom, etc., everything works perfectly.
![capturetrefoil](https://user-images.githubusercontent.com/4466543/37794320-7a1b59c4-2e11-11e8-8fb7-7e28ba4a0f12.PNG)

**Comment by Saabikraus** [comment]
Hey!

I have the same problem like User jirgg, only the .tex file is generated, although I followed the steps to install the plugins. I'm using Windows 7.
Is there any other solution?
