### ISSUE TITLE
The color chooser becomes unreadable because of its colored background

### ISSUE THREAD

**Issue by allo-** [cnr-isti-vclab/meshlab#1531]
It seems that meshlab uses for effect or for comparing with the previous color the currently selected color as background for the color chooser dialog. When using dark colors, this leads to a hard-to-read UI. I attached a screenshot how it looks here.
Version: v2022.02 (AppImage)

![image](https://github.com/user-attachments/assets/c408eba8-02df-4806-983d-c5413792b631)

**Comment by allo-** [comment]
I upgraded to 2023.12 (The update dialog did not tell there is a new version), but the problem is almost the same. The buttons now have icons, so one can at least find them to set the color or reset the color to something that makes the dialog readable until one accepts a dark color again.

![image](https://github.com/user-attachments/assets/fa0495a2-1391-4f90-b628-5a0ff79aa8da)

**Comment by alemuntoni** [comment]
Thanks for reporting! Fixed in the last commit.
