### ISSUE TITLE
Bug in Simplification Cluster Decimation

### ISSUE THREAD

**Issue by GiovanniSer** [cnr-isti-vclab/meshlab#1537]
Bug in Simplification Cluster Decimation (default values) creates also some non manifold faces.
Warning because you might not realize that you are ruining a proper mesh.
Win 10

**Comment by GiovanniSer** [comment]
In case anyone wants to debug, try applying the filter here. (ply)
[castleZ1.zip](https://github.com/user-attachments/files/17196433/castleZ1.zip)

**Comment by cignoni** [comment]
The creation of non manifold faces is indeed a well known issue of the clustering simplification algorithm (Rossignac, Jarek, and Paul Borrel. "Multi-resolution 3D approximations for rendering complex scenes." Modeling in computer graphics: methods and applications. Berlin, Heidelberg: Springer Berlin Heidelberg, 1993. 455-465.). 
Added warning in the documentation of the filter.

**Comment by GiovanniSer** [comment]
Thank you. just a small clarification, in addition to non-manifold faces I also found missing faces (small holes in the mesh). An even more insidious event because it is not perceptible at the moment.
