### ISSUE TITLE
Point Based Gluing Not Counting Points Correctly

### ISSUE THREAD

**Issue by ctgivan** [cnr-isti-vclab/meshlab#154]
On my MBP (running OX S 10.12.4) Meshlab 2016 behaves oddly when trying to use the point based gluing feature. The interface opens correctly, but clicking on each point to match does not produce paired labels, rather Meshlab treats them as though the clicked points belong to the same mesh (e.g. instead of point 0 on mesh 1 and point 0 on mesh 2, I get point 0 on mesh 1 and point 1 on mesh 2). This happens probably 90-95% of the time, and is not just a problem with the labels. Trying to accept a match where there are no matching labels results in an error message saying there needs to be an equal number of points selected between the two meshes. I can't seem to find a pattern to it—clicking on the already glued-mesh first, rotating one mesh first, and so on, doesn't seem to affect the behavior.

**Comment by mcallieri** [comment]
I will do some testing, but at the moment it was impossible for me to replicate the issue.

**Comment by carriere4** [comment]
I experienced this same issue running v2016.12 on MBP
