### ISSUE TITLE
Pickpoints

### ISSUE THREAD

**Issue by VladShmi** [cnr-isti-vclab/meshlab#155]
In Linux 16.04 I click in Pickpoint and I create a point, but when I click in **Rename point** the program can't be closed so I need to switch off the computer.
                                                                                                                             VladShmi

**Comment by mcallieri** [comment]
I will do some test on a Linux machine, on the other systems it seems working.

Anyway, point-picking filter is an outdated and buggy filter, and will be probably removed soon. We plan to add a more usable filter for point/line/area editing.
