### ISSUE TITLE
[Question] Filters > Point Set > Point Cloud Simplification - What algorithm is this ?

### ISSUE THREAD

**Issue by IgorWojas** [cnr-isti-vclab/meshlab#1556]
Hello!

I would like to know more about the Point Simplification algorithm. I cannot find it in the MeshLab nor VCGLib repo. Any links greatly appreciated!

Thanks!

**Comment by cignoni** [comment]
As described, in the help it creates  "a new layer populated with a simplified version of the current point cloud.  The simplification is performed by subsampling the original point cloud using a Poisson Disk strategy"

I will improve the description adding the reference to the paper.
