### ISSUE TITLE
meshlabserver crashes without an input file

### ISSUE THREAD

**Issue by 3DLIRIOUS** [cnr-isti-vclab/meshlab#158]
Meshlabserver crashes if no input file is provided. It should be possible to run meshlabserver without an input file and still run the limited set of filters available, i.e. the "Create New Mesh Layer" filters, the same as in the GUI.

To work around this, I currently create a dummy xyz point cloud file with a single vertex at (0, 0, 0), use this as the input file, then delete it as the first filter in the stack.

**Comment by granzuglia** [comment]
Fixed. Thanks!
