### ISSUE TITLE
ASCII PLY alpha channel is ignored => transparency does not work

### ISSUE THREAD

**Issue by krystufe** [cnr-isti-vclab/meshlab#161]
version: MeshLab 2016.12
OS: Windows 10

If mesh color is defined in ASCII PLY format as semitransparent using RGBA, MeshLab visualize it 100% opaque.

Example:
```
ply
format ascii 1.0
comment VCGLIB generated
element vertex 8
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 12
property list uchar int vertex_indices
end_header
0 0 0 0 255 0 125 
0 0 1 5 255 0 125 
0 1 1 5 255 0 125 
0 1 0 5 255 0 125 
1 0 0 5 255 0 125 
1 0 1 5 255 0 125 
1 1 1 5 255 0 125  
1 1 0 0 255 0 125 
3 0 1 2
3 0 2 3
3 7 6 5 
3 7 5 4 
3 0 4 5 
3 0 5 1
3 1 5 6
3 1 6 2 
3 2 6 7 
3 2 7 3
3 3 7 4 
3 3 4 0
```

**Comment by mcallieri** [comment]
The Alpha component is not intended to be used as rendering transparency. MeshLab does not even support transparent rendering.
Alpha is read and saved, and available to many filters as data.

**Comment by devshgraphicsprogramming** [comment]
It seems that #351 would indicate that its not exactly being read and saved

**Comment by mcallieri** [comment]
alpha is NOT used for transparency in MeshLab. anyway, it is available as data for the filters.
Grab the new beta version:

MacOS:
from GitHub
https://github.com/cnr-isti-vclab/meshlab/releases
Get the latest .dmg installer

Windows:
from AppVeyor
https://ci.appveyor.com/pro…/cignoni/meshlab/build/artifacts
For Window version, there is no installer, yet, but we have a portable folder, just unpack it on your PC and double-click on MeshLab icon. As this version is continuosly updated, if you see there is a compilation ongoing (or failed) just go to "history" and look for the artifact in last successful build.
