### ISSUE TITLE
Transfer Vertex Attributes to Texture (between 2 meshes)

### ISSUE THREAD

**Issue by mlutteral** [cnr-isti-vclab/meshlab#162]
Trying to bake a texture from a point cloud to a mesh is not working after the dec/16 update (crash or blank png). Works fine on v1.3.3.

**Comment by mcallieri** [comment]
you have layer A, a pointcloud, with color, and you want to bake the color to a layer B, which is a mesh with texture. Is it correct? 
it's working for me...

**Comment by mlutteral** [comment]
Exactly, a point cloud, loaded from a TXT file, and a mesh, imported from an OBJ. Doesn't work on the dec/16 version (it crashes half of the time, or give a blank PNG the other half). It work fine on version 1.3.3

**Comment by mcallieri** [comment]
that is what I tested, and it is working for me.

**Comment by mlutteral** [comment]
I'll try to debug this on my side, and I'll keep you posted. Thank you for your time

**Comment by TheBricktop** [comment]
meshlab 2020 doesnt allow baking from point cloud to mesh 
Error : both meshes require to have faces.
