### ISSUE TITLE
No face selection error when using Select All in a filter script.

### ISSUE THREAD

**Issue by raikkin-tk** [cnr-isti-vclab/meshlab#163]
Hello,

I am using windows 10 64 bit.

I am importing a 2d stl file and having an error when applying the following filters using a script;
- Select All
- Create Selection Perimeter Polyline

In the GUI, performing the steps manually works.
In the GUI, running the above as a filter script fails due to the no selection error. However, running the script a second time immediately in the GUI does work. (shown below)
Using the Command Line interface, the script just fails, showing the no face selection error.

I am not sure if this is a true bug or this is due to the lack of support for Polylines, however the error appears to be the selection not registering quick enough as running the script with the faces pre selected does work.

Cheers.

![bug](https://user-images.githubusercontent.com/29272179/26917789-eec9f522-4c72-11e7-9513-138973a7585c.png)

**Comment by mcallieri** [comment]
Yes, sorry, it is a known bug in the Scripting. Selection does not work in Scripting. 
It has been fixed in the source, but we are still waiting for a new release.

**Comment by raikkin-tk** [comment]
Thanks for the quick response.
Looking forward to it.

**Comment by danivelikova** [comment]
can you point out to which release?
I want to use Select Faces by Color but it doesn't appear in the filter script. Is there an example how I can add this to the script?
