### ISSUE TITLE
MeshLabServer does not handle spaces on Windows

### ISSUE THREAD

**Issue by Owloid** [cnr-isti-vclab/meshlab#164]
MeshLabServer doesn't seem to handle spaces in paths in Windows 10 x64 (checked on 2 computers).

`meshlabserver -i model.obj -o model2.obj -s meshlabscript.mlx` works fine, but the following cause "CommandLine Syntax Error"s

`meshlabserver -i model.obj -o model2.obj -s "sp ace/meshlabscript.mlx"`
`meshlabserver -i model.obj -o "sp ace/model2.obj" -s meshlabscript.mlx"`
`meshlabserver -i sp^ ace/model.obj -o model2.obj -s meshlabscript.mlx"`
`meshlabserver -i "sp^ ace/model.obj" -o model2.obj -s meshlabscript.mlx"`
`meshlabserver -i "mo del.obj" -o "sp ace/model2.obj" -s meshlabscript.mlx"`

Is this a known issue?

**Comment by amenzies** [comment]
I am also seeing this issue in MeshLab_64bit_fp v2016.12

**Comment by granzuglia** [comment]
I confirm the issue. I'm working on it.

**Comment by amenzies** [comment]
Thanks!

**Comment by granzuglia** [comment]
I should have solved it in the current version of MeshLabServer that you can compile from the code available in the GitHub server.

**Comment by amenzies** [comment]
Awesome!

**Comment by TravisEvashkevich** [comment]
Has this been built and rolled into a download? Cause I'm still getting this with the latest meshlab download
