### ISSUE TITLE
Keyboard shortcut for Show Trackball

### ISSUE THREAD

**Issue by dixxi** [cnr-isti-vclab/meshlab#167]
I frequently have to hide the track ball when working with point clouds as it irritates me.
It would be very nice to have a keyboard shortcut for this. Can you please add one?

**Comment by mcallieri** [comment]
ok... added in a955efd017c7c30a1712965a9d3d3af3cd698db6 as shift-H
however, i must stress how we do love our trackball, is so cute and cuddly.
