### ISSUE TITLE
MeshLab stops working when loading a mesh with a single triangle (facet)

### ISSUE THREAD

**Issue by ericpar** [cnr-isti-vclab/meshlab#168]
Hi,

I observed that MeshLab crashes anytime I try to load an ASCII STL file that contains the description of a mesh with a single triangle (facet). You can find attached such a file.

I am working Windows 10 64 bits with this version of MeshLab:
![image](https://user-images.githubusercontent.com/1882164/27196705-97ccdce6-51d9-11e7-8286-43c867931576.png)

Here is a sample file that is causing the crash:
[face_5_facet_1.zip](https://github.com/cnr-isti-vclab/meshlab/files/1078657/face_5_facet_1.zip)

On Windows, I just get a popup window with the message "meshlab.exe has stopped working".

**Comment by mcallieri** [comment]
the file you are using is not compliant with the specification: numbers must be in the format "1.000000e+000"
as also explained here https://en.wikipedia.org/wiki/STL_(file_format)   << where each n or v is a floating-point number in sign-mantissa-"e"-sign-exponent format, e.g., "2.648000e-002" >>

The original specification was even more strict, as all vertices coordiantes should be positive and fit in a specific bounding box. Those limits have been relaxed, but still most reader/writer expect numbers int his format.
