### ISSUE TITLE
meshlab 2016: Pointclouds are dark!

### ISSUE THREAD

**Issue by arianaa30** [cnr-isti-vclab/meshlab#169]
In 2014 version there was an option for `Lights On`. But in 2016 that disappeared so .ply models are very dark and not clear. Is it somewhere that I can not find?

**Comment by granzuglia** [comment]
It depends on the fact if the point clouds has/hasn't a set of meaningful per vertex normal. BTW, you can simulate the "light on/off" just going on the rendering menu in the per point tab visualization settings and on the shading options click on "None". That's equivalent to "Turn off" light.
