### ISSUE TITLE
Sketchfab filter parameter is rooted in the mainwindow

### ISSUE THREAD

**Issue by cignoni** [cnr-isti-vclab/meshlab#17]
The name of the parameter storing the private API token used to upload sketchfab files is rooted into mainwindow_init.cpp 
We need a mechanism to add persistent parameters in filters...

**Comment by alemuntoni** [comment]
Better management of sketchfab api, that can be saved in meshlab settings. 
Commit [e243315](https://github.com/cnr-isti-vclab/meshlab/commit/e2433151ef3c4d12941595f319e9a402327eba82)
