### ISSUE TITLE
Screened Poisson Surface Reconstruction filter crashes meshlab on Ubuntu 14

### ISSUE THREAD

**Issue by ruslanagit** [cnr-isti-vclab/meshlab#171]
I have installed meshlab following the procedure given by @DBobkov in his [comment](https://github.com/cnr-isti-vclab/meshlab/issues/74#issuecomment-279254296).

When I try to use Screened Poisson Surface Reconstruction - application crashes. Tried to use a few meshes with different parameters - the same. The moment I click "Apply" - there is a crash.

I also tried to run the filter from the command line, as described in #138, and got the following output:
```
FilterScript
Reading filter with name Screened Poisson Surface Reconstruction
Starting Script of 1 actionsfilter: Screened Poisson Surface Reconstruction
no additional memory available!!! memory required: 1692768
./meshlabserver: symbol lookup error: [my_path]/meshlab/src/distrib/plugins/libfilter_screened_poisson.so: undefined symbol: omp_get_num_procs
```

Then I took the fix #55 , and recompiled everything. No change - the application still crashes, meshlabserver command outputs the same error.

My system:
Ubuntu 14.04 LTS (64 bit) 
memory 15.7 GiB
Intel® Core™ i7 CPU 870 @ 2.93GHz × 8
GeForce GT 330/PCIe/SSE2
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Any help would be highly appreciated! Thanks.

**Comment by granzuglia** [comment]
I will try to setup a linux system in the very next days. Unfortunately I need sometime to do it. I will install a Mint distro, presumably. I hope the problem is not related with the distro, too. Can you paste the output you get with the recompiled MeshLabServer version, please? Do you still get the "no additional memory available..." warning?

Thanks a lot.

**Comment by ikapelyukhin** [comment]
I've encountered the ` undefined symbol: omp_get_num_procs` issue as well. I've had success building the plugin after removing `QMAKE_CXXFLAGS=-fopenmp`, and adding `linux:QMAKE_LFLAGS += -lomp` instead. Hope this helps.

**Comment by madEngin33r** [comment]
May I know the final fix? I too installed using [comment](https://github.com/cnr-isti-vclab/meshlab/issues/74#issuecomment-279254296) 
Tried all the fixes in the issues but couldn't make it work. 

error : ./meshlab: symbol lookup error: /home/badri/Documents/MESHLAB/meshlab/src/distrib/plugins/libfilter_screened_poisson.so: undefined symbol: omp_get_num_procs

OS: Ubuntu 14.04
