### ISSUE TITLE
Ok-Button in Export Settings is not the default action on Enter

### ISSUE THREAD

**Issue by kallitokaco** [cnr-isti-vclab/meshlab#177]
In the "Save As.." workflow after the appearence of the SaveFile-dialog the Ok-button in the export properties of stl for example is not the default action on Enter-Pressed.

This forces the user to use the mouse instead of just pressing enter.

**Comment by mcallieri** [comment]
should be fixed now in 80d30780d897e4c69aef37ce87312842fd3a3ec5
