### ISSUE TITLE
Strange start of meshlab on Windows 7, 64 bit

### ISSUE THREAD

**Issue by miroi** [cnr-isti-vclab/meshlab#178]
Dear experts,

I installed the fresh meshlab 2016.12.

Upon clicking the start icon I noticed it quick opening and immediate closing of two smaller blank windows, and after them the meshlab opens.

However, on the bottom of the meshlab window I got 2 progress bars, the second on active.

Picture:
![meshlab2016 12-startwin7](https://user-images.githubusercontent.com/1047336/27906071-548546c0-6242-11e7-8da5-5d49b9a629a3.png)

This seems strange; any help, please ? Maybe something is missing on my Windows 7 machine ?

**Comment by granzuglia** [comment]
The second progress bar tells you how much  GPU total memory you have installed on your pc and the free GPU memory currently available. It works only with NVIDIA graphics card for the moment.
