### ISSUE TITLE
Crash on Filters and Render menu options

### ISSUE THREAD

**Issue by polarathene** [cnr-isti-vclab/meshlab#180]
I am trying to use MeshLab to delete some points/vertices and then create a mesh from a .ply file I've imported, generated from a tool called colmap. While I can select the points with tool like rectangle or polyline select, trying to delete them crashes the program.

Two different errors in my terminal after MeshLab crashes(no idea where those `&` come from):
```
unable to find the id corresponding to action  'Dele&te Selected Vertices'
unable to find the id corresponding to action  'C&onditional Vertex Selection'
```

After one of the above lines is this line:
```
meshlab: ../../common/interfaces.h:370: virtual MeshCommonInterface::FilterIDType MeshFilterInterface::ID(QAction*) const: Assertion `0' failed.
```

It seems any choice from this menu: `Filters -> Selection` causes a crash.
If I mouse over the vertex delete buttons on the UI, I notice it mentions the library: `libfilter_select.so`. So I guess whenever this is called, a crash happens?

---

I am running Manjaro Linux, using AUR packages, one of which builds from git. The program seems to be working fine, both of the packages have this issue.

**Comment by polarathene** [comment]
`Filters -> Samping -> Poisson-disk Sampling`
```
unable to find the id corresponding to action  'Po&isson-disk Sampling'
meshlab: ../../common/interfaces.h:370: virtual MeshCommonInterface::FilterIDType MeshFilterInterface::ID(QAction*) const: Assertion `0' failed.
```

`Filters -> Create New Mesh Layer  -> Sphere`
```
unable to find the id corresponding to action  '&Sphere'
meshlab: ../../common/interfaces.h:370: virtual MeshCommonInterface::FilterIDType MeshFilterInterface::ID(QAction*) const: Assertion `0' failed.
```

`Render -> Background Grid`
```
unable to find the id corresponding to action  '&Background Grid'
meshlab: ../../common/interfaces.h:525: virtual MeshCommonInterface::FilterIDType MeshDecorateInterface::ID(QAction*) const: Assertion `0' failed.
```
This does nothing on blank open of MeshLab, if I import a mesh and try it, crash... 

`View -> Show Layer Dialog` seems to work fine, including with imported mesh, I can change the rendering options like shading. Seems just `Filters` and `Render` menu's cause the crash.

**Comment by polarathene** [comment]
The git package in the AUR has [a recent user comment](https://aur.archlinux.org/packages/meshlab-git/) that identifies the problem, it's specific to Linux distros with KDE apparently. The [bug](https://bugs.kde.org/show_bug.cgi?id=337491) is 3 years old. I've tried to reach out to the KDE community and hopefully something will be done about it, else at least other users that use KDE might come across this issue for how to get meshlab working in the meantime.

**Comment by SelvamArul** [comment]
Any updates on this issue?
