### ISSUE TITLE
Inconsistent behavior on Quad Edge Collapse Decimation

### ISSUE THREAD

**Issue by misan** [cnr-isti-vclab/meshlab#181]
The problem happens when using meshlabserver (command line) and it works ok using meshlab GUI (playing the exact same filter mlx file that fails otherwise). 

This is the original mesh view:
![image](https://user-images.githubusercontent.com/466120/28225925-84612006-68d4-11e7-95a2-d6d345290eb8.png)

This is the decimated version (to 146 faces)
![image](https://user-images.githubusercontent.com/466120/28225861-5749ca00-68d4-11e7-816a-f882f9f4de4f.png)

And this is what happens when doing 
meshlabserver -i original.stl -o output.obj -s filter.mlx
![image](https://user-images.githubusercontent.com/466120/28226294-e9664ec6-68d5-11e7-9997-1b4f4fd3f761.png)

It is clear mesh is destroyed using exactly the same filter that works ok for the GUI version.

And now I am attaching the source files involved:

[files.zip](https://github.com/cnr-isti-vclab/meshlab/files/1149394/files.zip)

**Comment by 3DLIRIOUS** [comment]
misan,

When importing stl files with meshlabserver you need to run "Merge Close Vertices" as the first filter. This is the same as selecting "Unify Duplicated Vertices" in the GUI. In fact, if you try running your script in the GUI without selecting "Unify Duplicated Vertices" you should see the same results as meshlabserver.

The reason behind this is that stl files are awful; they don't actually store a mesh, just a list of unconnected triangles. It is up to the reader to try to merge these into a connected (hopefully manifold) mesh. Most software does this automatically behind the scenes, however MeshLab gives you the explicit choice to merge it or keep it as a bunch of separate triangles.

**Comment by misan** [comment]
3DLIRIOUS,

Thanks a lot for your answer. I did not understand why that was happening and you are right I was answering yes on the GUI when loading the STL file. I make sure that it is all there is to it and I will close the issue (user error).

**Comment by misan** [comment]
3DLIRIOUS,

If I convert the file from STL to OBJ and then I try to use meshlabserver to do the same as before I seem to obtain the same result (which can no longer be attributed to the mess STL format is). I know that is not the solution you proposed but I thought you might want to hear about it.

**Comment by misan** [comment]
I did as 3DLIRIOUS suggested and it all is good. Thanks a lot.
