### ISSUE TITLE
PLY defined vertex colors not displaying from PLY import

### ISSUE THREAD

**Issue by meder411** [cnr-isti-vclab/meshlab#186]
I am importing a PLY file with the header styled as below, but Meshlab does not correctly color the vertices. Instead I just get grey clouds. These PLY files have correctly loaded before--back in early May when I was using the then-newest Meshlab on Ubuntu 14.04.

Now I am using Ubuntu 16.04 and the version of Meshlab available via `snap install`.

My PLY header:

```
ply
format ascii 1.0
element vertex 948
property float x
property float y
property float z
property float nx
property float ny
property float nz
property uchar red
property uchar green
property uchar blue
end_header
```

I've checked the data, and the color info is there. Is this a bug?

**Comment by kylemcdonald** [comment]
i also don't see the colors from my imported ply. when i import the file into rhino, it displays the colors.

i'm also on ubuntu 16.04 running v.1.3.2_64bit (feb 19 2016).

i made sure to turn on render>color>per vertex, but this just changes the color of all the points from gray to white.

```
ply
format binary_little_endian 1.0
element vertex 244510571
property float x
property float y
property float z
property uchar r
property uchar g
property uchar b
end_header
```

**Comment by mcallieri** [comment]
beware: the property names should be "red, green blue", and not "r g b". some tools may also use r,g,b but the standard for the format is the full name. Range is 0-255.

I checked, and it works on the 3d models I preapared. MeshLab also saves the alpha channel, but it reads also when the alpha is not present.

**Comment by Anutrix** [comment]
Any updates? Colors not working for a file I have too. Also I couldn't find  render>color>per vertex option.
