### ISSUE TITLE
Dragging from "Import Mesh" dialog

### ISSUE THREAD

**Issue by jakobkogler** [cnr-isti-vclab/meshlab#190]
If you open the "Import Mesh" dialog, choose a file and drag it into the scene window, the "Post-Open Processing" opens. After you exited "Import Mesh" (by cancle or loading a different file), you can move the "Post-Open Processing" dialog, but you can't click anything on it. And also the other parts of Meshlab freeze. 

Tested with MeshLab_64bit_fp v2016.12 (build on Dec 23 2016) on Windows 7 64 bit. I've used STL files in binary format for testing.

**Comment by mcallieri** [comment]
yes... but why? 
why would you drag a file from a dialog, and then go back to the dialog and interrupt the loading?
