### ISSUE TITLE
no additional memory available!!! memory required 84000

### ISSUE THREAD

**Issue by cedemax** [cnr-isti-vclab/meshlab#191]
Hi!

I'm trying to use meshlabserver to optimize meshes generated by my program. Unfortunately the script reports the error of "no additional memory available" No matter how small a file i use. It also reports it on any filter (I've tried "recompute normals" and "Quadric edge collapse"). Everything works smoothly in the GUI. 

The command **"C:\Program Files/VCG/MeshLab/meshlabserver.exe" -i C:\Users/Max/Documents/topo(3).stl -o C:/Users/Max/Documents/topo.obj -s C:/Users/Max/Documents/reduce.mlx**

The log

`Loading Plugins:
Current Plugins Dir is: C:/Program Files/VCG/MeshLab/plugins
Total 241 filtering actions
Total 12 io plugins
Opening a file with extention stl
Mesh C:/Users/Max/Documents/topo(3).stl loaded has 3000 vn 1000 fn
output mesh  C:/Users/Max/Documents/topo.obj
Apply FilterScript: 'C:/Users/Max/Documents/reduce.mlx'
FilterScript
Reading filter with name Re-Compute Face Normals
Reading filter with name Simplification: Quadric Edge Collapse Decimation
    Reading Param with name TargetFaceNum : RichInt
    Reading Param with name TargetPerc : RichFloat
    Reading Param with name QualityThr : RichFloat
    Reading Param with name PreserveBoundary : RichBool
    Reading Param with name BoundaryWeight : RichFloat
    Reading Param with name PreserveNormal : RichBool
    Reading Param with name PreserveTopology : RichBool
    Reading Param with name OptimalPlacement : RichBool
    Reading Param with name PlanarQuadric : RichBool
    Reading Param with name QualityWeight : RichBool
    Reading Param with name AutoClean : RichBool
    Reading Param with name Selected : RichBool
Starting Script of 2 actionsfilter: Re-Compute Face Normals
no additional memory available!!! memory required: 84000
filter: Simplification: Quadric Edge Collapse Decimation
no additional memory available!!! memory required: 84000
Initializing simplificationLOG: 2 PostSimplification Cleaning: Removed 2463 duplicated vertices
PostSimplification Cleaning: Removed 2463 duplicated vertices
Mesh C:/Users/Max/Documents/topo(3).stl saved as C:/Users/Max/Documents/topo.obj (537 vn 1000 fn)`

As can be seen in the log, the output file is saved succesfully but the filters have not been applied. 
This rules out anything with read/write access I would think.

Any help much appreciated!

(MeshLab_64bit_fp v2016.12)

**Comment by cedemax** [comment]
This is no longer an issue with the latest build (from source)

**Comment by RolfLampa** [comment]
Are there any later binaries available, compiled after the 2016.12?  

I'm wrapping MeshLab into a RhinoCAD / GrassHopper component, but I keep getting "no additional memory available" message. I'm using C# but I have difficulties compiling C++ projects.

// Rolf

**Comment by mcallieri** [comment]
nope, sorry, we are still missing a release, unfortunately

**Comment by timothytai** [comment]
Hi all, has this been solved? I'm running into the exact same problem as Rolf in Rhino/Grasshopper. Thanks!
