### ISSUE TITLE
Impossible to export .u3d files in Mac OS Sierra

### ISSUE THREAD

**Issue by afasc** [cnr-isti-vclab/meshlab#192]
When trying to export a .u3d file, only the corresponding .tex is created. I know this issue is known, but the workaround posted [here](https://github.com/cnr-isti-vclab/meshlab/issues/33) is not working on Mac OS Sierra. Any other advice?

**Comment by alemuntoni** [comment]
Hi, this should be fixed with #557.
The feature will be available starting from MeshLab 2020.02.
Feel free to open a new issue if you still have troubles with U3D!
