### ISSUE TITLE
Compilation fixes [in Debian]

### ISSUE THREAD

**Issue by jaggzh** [cnr-isti-vclab/meshlab#193]
When working from the downloaded source I get the following errors.  I'm testing from a clone of github now and the following items may no longer be issues.

1. The compile was looking for io_TXT.pro, but I found only a lowercase version:
src/plugins_experimental/io_TXT/io_txt.pro
Hack/fix: ln -s io_txt.pro io_TXT.pro

2. One of the rules referencing, among others, moc_filter_csg.o, was looking for ../external
Hack/fix: ln -s external ../external
* Note: This might be due to my relocation of the meshlab/ folder when arranging vcglib

3. libmpir.a and libmpirxx.a were looked for in linux-g++-64, but they were in linux-g++/
Hack/fix: ln -s ../linux-g++/libmpir.a
Hack/fix: ln -s ../linux-g++/libmpirxx.a

4. I'm currently working on:
eqhandle.cpp:86:47: error: call of overloaded ‘abs(qreal)’ is ambiguous
  qreal handleOffset = abs(newPos.x()-pos().x());

**Comment by jaggzh** [comment]
#4 is handled by editing eqhandle.cpp:
   #include <cmath>
and changing the line 86 abs() call to std::fabs()

**Comment by jingpengw** [comment]
the `io_TXT` issue also happens in ubuntu 16.04

**Comment by alemuntoni** [comment]
Hi @jingpengw, right now io_TXT is no longer inside `plugins_experimental`, and looking in the actual version of the repo I did not find `io_TXT` anywhere, just `io_txt`. There is also a Github Actions workflow that successfully compiles meshlab in a clean ubuntu 16.04 machine. 
Could you please check if you are compiling the last version of meshlab?

**Comment by jingpengw** [comment]
thanks, I was compiling the 2016 release version.
