### ISSUE TITLE
Meshlab - ASCII-stl

### ISSUE THREAD

**Issue by xarminius** [cnr-isti-vclab/meshlab#194]
Sorry- there is Not Way to suppress Bold Chars- I tried via vim, edit- everything fails. 
After 20 minutes I gave up. 

Yesterday I "found" "meshlab" as software.
I use it for pre-processing STL-Files being generated by a computer program to bring them into CAD.
My question: Why does it not read (my) ASCII-STL?

It reads one face with three vortices and that's it.

"Paraview" reads them. But this is no tool to check/smooth/modify a grid.
When I convert ASCII-stl via "Freecad" to bin-stl:
That's readable. The same model.
IMO ASCII is easier to read. This is what confuses me.
---
A snippet:

solid MOULD_GRID
facet normal 0.000003 0.052336 0.998630
outer loop
vertex 0.000 81.20 20.78
vertex -87.098 81.20 20.78
vertex 0.000 78.66 20.91
end loop
endfacet
facet normal 0.000004 0.052345 0.998629
outer loop
vertex -87.098 78.66 20.91
vertex 0.000 78.66 20.91
vertex -87.098 81.20 20.78
end loop
endfacet
facet normal 0.000004 0.052336 0.998630
outer loop
vertex 0.000 78.66 20.91
vertex -87.098 78.66 20.91
vertex 0.000 75.54 21.08
end loop
endfacet
facet normal 0.000004 0.052345 0.998629
outer loop
vertex -87.098 75.54 21.08
vertex 0.000 75.54 21.08
vertex -87.098 78.66 20.91
end loop
endfacet
facet normal 0.000004 0.052336 0.998630
outer loop
vertex 0.000 75.54 21.08
vertex -87.098 75.54 21.08
vertex 0.000 71.85 21.27
end loop
endfacet
facet normal 0.000004 0.052343 0.998629
outer loop
vertex -87.098 71.85 21.27
vertex 0.000 71.85 21.27
vertex -87.098 75.54 21.08
end loop
endfacet
...

...
...
endsolid MOULD_GRID
-------------
I am on Windows7 german OS, but I can test it also on Ubuntu.
------
uups - a similar bug was 2009...
https://sourceforge.net/p/meshlab/bugs/127/

**Comment by mcallieri** [comment]
endloop should be written WITHOUT the space inbetween
http://www.fabbers.com/tech/STL_Format
