### ISSUE TITLE
[Bug] Diacritic letter(s) in folder name.

### ISSUE THREAD

**Issue by Radd78** [cnr-isti-vclab/meshlab#196]
During opening a file containing polish diacritic letter (eg. ś, Ś) there is an error:
Unable to open file:
"xyz\?ss\picture.obj"

Error details: file
xyz\?ss\picture.obj does not exit.

**Comment by Synxis** [comment]
I have this problem too, it would be nice if it was fixed !

The solution is to use the method `toLocal8Bit()` on the filename after the selection dialog.

**Comment by mcallieri** [comment]
fixing it, not sure if completely removed.

**Comment by mcallieri** [comment]
found another error, and fixed it.
Still searching and testing.
