### ISSUE TITLE
Surface Reconstruction: Poisson missing in v: 2016.12

### ISSUE THREAD

**Issue by 3DLIRIOUS** [cnr-isti-vclab/meshlab#199]
This is a request to please bring back Surface Reconstruction: Poisson from the previous version, as it appears to be missing in 2016.12. I expect that Screened Poisson Surface Reconstruction is considered to be it's replacement, however the filters do not work the same, and the newer is not a direct replacement for the older.

The older version is much more robust on some meshes, and is also much simpler to use (only 4 attributes to adjust, as opposed to 10 for the newer version). If there can be at least 5 different Laplacian smoothing filters, why not multiple Poisson Reconstruction filters as well?

**Comment by cignoni** [comment]
As explained in the help of the screened poisson filter, you can obtain the old behaviour by setting zero in the **_Interpolation weight_** parameter

**Comment by 3DLIRIOUS** [comment]
Ah, thank you! I had missed that.

I'm still a bit confused regarding what the old SolverDivide and Offset parameters are in the new filter, as the descriptions are different. Put another way, which parameters are then ignored if pointWeight is set to zero?
