### ISSUE TITLE
Compilation Error caused by gluBuild2DMipmaps

### ISSUE THREAD

**Issue by nmellado** [cnr-isti-vclab/meshlab#2]
Hi,

I've failed to compile the current master version due to link error caused by gluBuild2DMipmaps, which is [deprecated](https://www.opengl.org/wiki/Common_Mistakes#gluBuild2DMipmaps) and not included in recent GL release (tested with OpenGL 4.5.0, driver NVIDIA 367.57, Debian Testing 4.7.8-1).
 
This function is called in a couple of places, including common/ml_shared_data_context.cpp.

Cheers

**Comment by cignoni** [comment]
True!
Done in commit 21399f2280fbcb1152898c96988e8dd77c007dc2

Thanks
