### ISSUE TITLE
MeshLab feature "Automatic Mesh Optimization" - How to perform it?

### ISSUE THREAD

**Issue by polarathene** [cnr-isti-vclab/meshlab#201]
From the website slides, the image before/after looks very interesting. I have tried to identify this feature but it's keywords are not easy to perform queries with. 

Usually I will come across mesh reduction features, whereas the way the image is shown it looks like rather than focus on decreasing the mesh it improved the quality/topology conforming to the shape better but not degrading the overall shape/form/silhouette.

**I would love to know how to perform this.** The slides show off great features of MeshLab but I feel teased as it is not clear how to achieve them(unless a video exists by Mister P). For the ones that do, they could be linked to the youtub video from the website.
---

Another feature "Automatic Remeshing" seems to be Iso Parametrization? Requiring water tight meshes, when a mesh is not water tight(eg a slice of a larger model, like the face of a cube) Is `Surface Reconstruction: Screened Poisson` the only way to go about it? 

With such a surface it seems to cause heavy distortion and ballooning as it tries to seal the mesh. There does not seem to be much information about this, presumably the exterior edges of the mesh would just need to be extruded a bit and filled to give some thickness, sealing the mesh? Does that need to be done manually or is it something Meshlab is capable of doing(lack of documentation makes it hard to discover this information).

**Comment by ecofarer** [comment]
I agree, the slides and site say "auto" but there is no auto

**Comment by polarathene** [comment]
Still relevant afaik.

**Comment by alemuntoni** [comment]
There is not such magic button "Automatic Mesh Optimization" in MeshLab. MeshLab provides a series of tools for automatic mesh optimization, but each one of them is a specific procedure that can be applied in some specific contexts.
