### ISSUE TITLE
Meshlab crash during start Win7_64 

### ISSUE THREAD

**Issue by xarminius** [cnr-isti-vclab/meshlab#202]
Crash is only on Win7 professional.

This is error message of actual version:
Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	meshlab.exe
  Anwendungsversion:	0.0.0.0
  Anwendungszeitstempel:	585d002a
  Fehlermodulname:	ucrtbase.DLL
  Fehlermodulversion:	10.0.10586.788
  Fehlermodulzeitstempel:	5879ab76
  Ausnahmecode:	40000015
  Ausnahmeoffset:	000000000006990f
  Betriebsystemversion:	6.1.7601.2.1.0.256.48
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	c43e
  Zusatzinformation 2:	c43e1dd176de4ae964907a31eab21136
  Zusatzinformation 3:	1c40
  Zusatzinformation 4:	1c406c5a2361639c269fe71aa039c335
--------------
I installed 1.3.4 beta from May 2014 version - this works, too.
---------------------------------
On one Win7 home PC the actual version works.
---------------------------------

Thank you for supporting such a nice software!

**Comment by alemuntoni** [comment]
I'll close this issue since refers to old MeshLab version and an unsupported windows version.
