### ISSUE TITLE
Crash during MC Edge Collapse

### ISSUE THREAD

**Issue by thefoofighter** [cnr-isti-vclab/meshlab#203]
Hi,

When I try MC Edge Collapse on a fairly simple mesh MeshLab crashes.

Windows 10 x64
MeshLab_64bit_fp v2016.12

[New Game Object.zip](https://github.com/cnr-isti-vclab/meshlab/files/1272861/New.Game.Object.zip)

Just in case it matters this mesh was generated in Unity3D via the Mapbox Api and represents a few buildings outlines. 
I exported with OBJ IO and opened with Meshlab and attempted the simplification.

**Comment by mcallieri** [comment]
I cannot replicate the error. I tried to simplify up to 5 faces.
However... what is the point in simplifying such a model? you cannot remove any triangle without destroying its topology and shape... it is already a minimal mesh.
24 faces... even an arduino can manage this.

**Comment by thefoofighter** [comment]
Yeah.. rendering a scene with a few million of these meshes.. Current Gen Nvidia/AMD couldn't even handle it...

I was just testing something with Meshab, came across a bug.. wanted to let you know about it..

Wont bother with providing potentially useful information that may lead to bug fixes in the future...

**Comment by mcallieri** [comment]
There is nothing that can simplified on those geometries, as they are minimal. There is no way to create these shapes with fewer triangels than now. 
Moreover, the triangles are disconnected (i.e. the vertex are replicated between triangles), which also prevents simplification.
In our lab, a guy worked on rendering building extruded from cadastrial data, like this one, and faced the same issue. Simplification is not a solution.... it looks terrible and every building looks crooked. 
One first thing was to work with level of details, replacing all "rectangle with small protrusions" (you have 3, in your mesh) with simple rectangles, and render these instad of the origial ones from distance. The nest step was to convert all shapes in a combination of pure rectangles, that were batched on the GPU using array buffers. But there is no such tools in MeshLab, it was custom-made code.

**Comment by mcallieri** [comment]
But, still, batching of quads was not enough for large cities, and the guy came up with this: http://vcg.isti.cnr.it/Publications/2007/CDGGMS07/
it is very complex, but has outstanding performances. 
However, the guy does nto work with us anymore, so I can only point you to this publication.

**Comment by thefoofighter** [comment]
No worries, I am facing similar problems and i was just using Mesh lab as an example to see if your mesh reduction algorithms could perhaps reduce some of the smaller protrusions while keeping the overall shape. I realized early on though that it doesn't work :) 

This was more of a bug report than anything, Thanks for the info & publication though!
