### ISSUE TITLE
Mesh generation from point cloud

### ISSUE THREAD

**Issue by WildSpirit007** [cnr-isti-vclab/meshlab#204]
Thank you for this useful open source program
I'm looking for the file that enables to generate meshes (Like Delaunay triangulation).
Could you please help me to localize that file or those files in those folders?

**Comment by mcallieri** [comment]
find the filter, and look inside the code. 
Some code, like "Poisson merging" is inside the filter folder. In other cases, it is in te VCG Library, and you will see it included in the header of the filter code.
