### ISSUE TITLE
Point Based Gluing Does not work propely on Ubuntu HiDPI screens

### ISSUE THREAD

**Issue by jakobwilm** [cnr-isti-vclab/meshlab#207]
Using a 4k screen on Ubuntu with 192dpi and 2x interface scaling and the following environment variables set in ~/.profile:
export QT_AUTO_SCREEN_SCALE_FACTOR=2
export QT_SCALE_FACTOR=1
export QT_DEVICE_PIXEL_RATIO=2
This works for allmost all of the Meshlab GUI (and most software), but not in the "Point Based Gluing" interface. Points are not clickable, number indicators turn up in the wrong places and it does not seem possible to align subscans properly.

![screenshot from 2017-09-06 14-09-16](https://user-images.githubusercontent.com/4461208/30111102-b8411644-930c-11e7-81d1-11e063eb6764.png)

**Comment by alemuntoni** [comment]
Tested on the last version with 4K display, it works now!
