### ISSUE TITLE
Uninstaller shows dialog boxes even when the silent switch is set

### ISSUE THREAD

**Issue by Franestra** [cnr-isti-vclab/meshlab#208]
Running the Uninstaller from a command line with the '/S' parameter doesn't stop confirmation dialog boxes from appearing.
For deployment scenarios, it would be great to be able to uninstall it truly silently this way.

This happens because of this code segment in meshlab.nsi:
https://github.com/cnr-isti-vclab/meshlab/blob/70b9dd7fc4a9d4044f486e3044572ca5cd0fefb6/src/install/meshlab.nsi#L283-L291

According to http://nsis.sourceforge.net/Docs/Chapter4.html#silent, adding /SD and the button ID of the default answer would solve the issue.

**Comment by alemuntoni** [comment]
Hi, this issue should be solved in the last commits, and now meshlab can be uninstalled silently!
You can find a working installer [here](https://github.com/cnr-isti-vclab/meshlab/actions/runs/73720133), or starting from version 2020.05.
