### ISSUE TITLE
Meshlab is "damaged or incomplete" on the case sensitive filesystem on macos.

### ISSUE THREAD

**Issue by hacker** [cnr-isti-vclab/meshlab#209]
The easy fix for me was to change `CFBundleExecutable` key's value from `MeshLab` to `meshlab` (this is how the executable is actually called in the bundle). Another option would probably be renaming `meshlab` to `MeshLab` to match `Info.plist`.

**Comment by hacker** [comment]
I spoke too soon, that fix is not enough, it can't open `stl` after applying this fix, so perhaps there are more mismatched names, guess it's easier for devs to fix and find and I'll resort to running from case-insensitive dmg for now.

**Comment by alemuntoni** [comment]
I'll close this issue since it should be fixed with the last PR.
Feel free to open another issue if the problem persists.
