### ISSUE TITLE
meshlabserver: cannot connect to X server

### ISSUE THREAD

**Issue by KrisRoofe** [cnr-isti-vclab/meshlab#211]
I use meshlabserver to simplify models for 3D printing on an ubuntu server. As it's a server version of ubuntu, so there is no X installed. 

I want to know how to run meshlabserver without X server.

**Comment by lizarge** [comment]
you need use xvfb (apt get install xvfb) in this case,
like this:
$ xvfb-run -a -s "-screen 0 800x600x24" meshlabserver

**Comment by alemuntoni** [comment]
Duplicate of #78
