### ISSUE TITLE
Huge memory leak on OBJ Export Windows 10 MeshLab 2016.12

### ISSUE THREAD

**Issue by ssh4net** [cnr-isti-vclab/meshlab#212]
1) Run MeshLab 
2) Create Noisy Isostructure
3) SubDivision Catmul-Clark

4) Export as OBJ 
In bottom left corner Polygonal check mark become active and selected.
Press OK. ANd see that even 64Gb RAM will be filled and system become unstable.

If deactivate Polygonal checkmark. Save work without problem.

BTW, what this checkmark mean? It become active only if mesh contain Quads.

And small bug - HELP Radio Button in OBJ Export not work.

**Comment by mcallieri** [comment]
That option should be, by default, unchecked. It has been corrected in the code, but still we do not have a new release.
MeshLab only works with triangles, so quads are split in triangles on loading, but kept as "false edges", for some kind of processing, it may be possible, at saving time, to re-join the quads. However, this is not Always true. The option try to do so, and should be used only when one is SURE that the joining is possible. 
By mistake, it was by default on, and this makes the exporter crashes most of the times the mesh has been modified :(
So, just disable it when exporting.

**Comment by JarrettBillingsley** [comment]
Is there a new release yet? I keep running into this too.
