### ISSUE TITLE
Questions about parameterization and texturing from registered rasters

### ISSUE THREAD

**Issue by nosleduc** [cnr-isti-vclab/meshlab#213]
Is it possible to know how this plugin works ?
How the option color correction works ?

**Comment by mcallieri** [comment]
here is a tutorial 
https://www.youtube.com/watch?v=OJZRuIzHcVw&index=8&list=PL60mCsep96Je1bzGrWnK-nL9pi95r7UqI
and the color correction is explained in this paper
http://vcg.isti.cnr.it/publications/papers/weaver_vmv02.pdf
