### ISSUE TITLE
Problems with Snap install on Ubuntu 16.04

### ISSUE THREAD

**Issue by john-davies** [cnr-isti-vclab/meshlab#215]
I've installed Meshlab via the Snap method and I'm having trouble getting it to run. OS details:
Release 16.04.3 LTS (Xenial Xerus) 64-bit
Kernel Linux 4.4.0-96-generic x86_64
MATE 1.12.1

When I try to run it I get the following:

```
john ~ $ snap list
Name          Version    Rev   Developer       Notes
cloudcompare  2.8.1-1    1     cloudcompare    -
core          16-2.27.6  2898  canonical       core
meshlab       2016.12-2  4     cnr-isti-vclab  -
john ~ $ sudo snap refresh meshlab
snap "meshlab" has no updates available
john ~ $ meshlab
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "topmenu-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
^C
john ~ $
```
If I try to run it using the suggestion in issue #98 then it runs fine:

```
john ~ $ cd /snap/meshlab/current/bin
john bin $ LD_LIBRARY_PATH=/snap/meshlab/current/lib:/snap/meshlab/current/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH ./meshlab
```

and I get Meshlab version - "MeshLab_64bit_fp v2016.12 ( built on Mar 7 2017 )"

Is it likely that I'm missing some dependencies / packages?

**Comment by john-davies** [comment]
A quick update. I'm working around this problem by:

1. Install the older version of Meshlab from the Ubuntu repositories ( v1.3.2 ) in addition to the newer Snap version
2. Replace /usr/bin/meshlab with a shell script:

```
#!/bin/bash
# Workaround for https://github.com/cnr-isti-vclab/meshlab/issues/215
cd /snap/meshlab/current/bin
LD_LIBRARY_PATH=/snap/meshlab/current/lib:/snap/meshlab/current/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH ./meshlab $1
```

which seems to work OK and gives me all the correct file associations and I can right click on files and use "open with ..."

I've also come across another slight oddity in that the progress bar in the bottom right of the Meshlab window bounces back and forth continuously with no indication of what it's waiting for - see screenshot below

![meshlab](https://user-images.githubusercontent.com/16657559/30687503-579a8458-9eb3-11e7-8d81-d91ab52cee0f.jpg)

There's a similar comment in this thread - https://aur.archlinux.org/packages/meshlab/ 

From a quick check it seems that it's the problem discussed in issue #99 - "UI: hide memory bar if memory info is not available"? I'm not sure if this fix has been included in the Snap package that's linked from the main Meshlab download page.

**Comment by balazsdukai** [comment]
Yesterday I've tried on a fresh Ubuntu 16.04.3 install with Unity (as downloaded from https://www.ubuntu.com/). The same error occurs as @john-davies described it.

**Comment by jhbell** [comment]
I ran into the same issue a little over a week ago. Error occurs as @john-davies described above and I came to the same conclusion of using the above workaround to launch Meshlab. I spent a lot of time messing around with different library versions trying to get it to work before I found the same script in #98. 

In my experiences with the bug, none of the GTK errors seem to be causing the hang. I uninstalled/reinstalled the different GTK libraries which didn't have any effect. I was only able to get something running by using the shell script.

Another thing worth noting is that I was able to use the snap version of Meshlab for a while. I noticed it stopped working very shortly after Ubuntu updated one day. I am thinking that maybe something in the latest version of Ubuntu or snap led to the error.

As far as the bouncing bar goes, that was happening before the snap broke on my machine as well.

**Comment by norru** [comment]
Hi, thanks for your suggestions. I am unable to run Meshlab on Ubuntu 16.07 as well.

```
snap run meshlab
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
```

Suggested workaround causes a core dump.

```
norru@GBWWSRUNUBWS02:/snap/meshlab/current/bin$ cd /snap/meshlab/current/bin
norru@GBWWSRUNUBWS02:/snap/meshlab/current/bin$ LD_LIBRARY_PATH=/snap/meshlab/current/lib:/snap/meshlab/current/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH ./meshlab
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

**Comment by john-davies** [comment]
@norru - that's not a problem that I've encountered but it looks like some Qt components are missing. Searching for _Qt platform plugin "xcb"_ brings the up the following as the first result which may provide some pointers:

https://stackoverflow.com/questions/17106315/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without

**Comment by Jarek-SRT** [comment]
I have exactly the same behavior as @norru, but on openSUSE Leap 42.3. The xcb QT plugin is installed, and no other QT-based application complains about it. This leads me to believe that the meshlab snap is not looking for the xcb plugin in the right place.

**Comment by john-davies** [comment]
I seem to have encountered a similar problem to @jhbell where, after an Ubuntu upgrade, Meshlab will now no longer work. If I run from the command line I get:

```
john ~ $ meshlab
./meshlab: symbol lookup error: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevice2
```

I haven't used Meshlab for a few weeks so I can't comment on which update broke it. Everything else, including the old v1.3.2 of Meshlab works fine. I've tried reinstalling the snap version but no change. I though that "snap" was meant to isolate an install from this sort of problem so I'm a bit stuck on how to proceed.

**Comment by norru** [comment]
Given that it appears to be necessary to manually apply custom "patches" as workarounds, I wonder what the advantage of Snap is, compared to a .deb package.

**Comment by ivocavalcante** [comment]
Guys, this how I solved both issues on Ubuntu 16.04, using @john-davies previous solution and including another fix. Create the following bash script:

```
root:~$ touch /usr/local/bin/meshlab
root:~$ chmod 755 /usr/local/bin/meshlab
root:~$ vim /usr/local/bin/meshlab
```

(copy and paste code below)

```bash
#!/bin/bash

cd /snap/meshlab/current/bin
LD_PRELOAD=/snap/meshlab/current/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 LD_LIBRARY_PATH=/snap/meshlab/current/lib:/snap/meshlab/current/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH ./meshlab
```

(save and exit)

```
user:~$ meshlab
```


Happy modelling!!

**Comment by john-davies** [comment]
@ivocavalcante - thanks for the suggestion. However when I try it I get:

```
john ~ $ meshlab
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Current Plugins Dir is: /snap/meshlab/4/bin/plugins 
"Cannot load library /snap/meshlab/4/bin/plugins/libfilter_ssynth.so: (/snap/meshlab/4/bin/plugins/libfilter_ssynth.so: undefined symbol: _ZTIN14StructureSynth5Model9Rendering16TemplateRendererE)"
```
I suspect that the Snap install is broken beyond repair for me on Ubuntu 16.04. Note that in a similar issue ( #271 ) there's a link to a personal PPA which may work a little better. The other alternative I guess is to try to build from source.

**Comment by john-davies** [comment]
I've added a comment on issue #271 about building from source which may be helpful.

**Comment by deepseven** [comment]
The personal PPA mentioned above worked for me on Ubuntu 16.04 when nothing else did.
Pasting it here for the really lazy among us :) 
```
sudo add-apt-repository ppa:zarquon42/meshlab
sudo apt-get update
```

**Comment by alemuntoni** [comment]
This issue should be solved in the latest version (2020.06). Feel free to reopen if the problem persists.

**Comment by john-davies** [comment]
A few comments on the new snap version:

- It now installs and runs correctly on my Ubuntu 16.04
- When the snap version of Meshlab is started it takes a long time ( ~15s ) before the Meshlab window appears. This makes it unusable for me
- A fresh install of the snap version doesn't set up the correct file associations. For example I can't right click on a PLY file and get the option "Open in Meshlab". I guess that it should be possible to set these up manually. Installing the snap version over an older version retains the file associations correctly ( I think ).

I compile Meshlab from source and will probably continue to do but I'm happy to provide any further information if it helps.

Thanks.

**Comment by alemuntoni** [comment]
Thanks @john-davies.
About the association with ply and other file types, I fixed that a few days ago in one of the last PRs, the feature will be available starting from 2020.07.
About the long times required to start, it is apparently a problem of snap packages. On my computer, I see the same problems on every snap package. I don't know if there are some magic tricks to make the startup of the package faster. If someone knows how to do it, PRs are welcome!

**Comment by adizhol** [comment]
version 2020.12 doesn't run in ubuntu 16.04 (installed with snap)
` /snap/meshlab/36/usr/bin/meshlab: symbol lookup error: /snap/meshlab/36/usr/lib/x86_64-linux-gnu/libOpenGL.so.0: undefined symbol: _glapi_tls_Current`

**Comment by john-davies** [comment]
A further update. I recently upgraded to Ubuntu 20.04 and the snap install of Meshlab 2021.05 works perfectly. The very first start is slow but after that it loads quickly. All the file associations appear to be fine as well. Many thanks :)

**Comment by alemuntoni** [comment]
@john-davies just to let you know that we are not going to update the snap package of meshlab.
We will keep updated the [flathub package](https://flathub.org/apps/details/net.meshlab.MeshLab) instead. Works better and it is definitely easier to maintain!

**Comment by tkazik** [comment]
> We will keep updated the flathub package instead. Works better and it is definitely easier to maintain!
Interesting...so this will then pull KDE, right? That is almost 1GB (platform, locale, etc.)

**Comment by alemuntoni** [comment]
> > We will keep updated the flathub package instead. Works better and it is definitely easier to maintain!
> 
> Interesting...so this will then pull KDE, right? That is almost 1GB (platform, locale, etc.)

@tkazik I don't think that it will download the entire KDE. Maybe @kevinsmia1939 can be more clear about this aspect.
In my system, MeshLab occupies 68 MB.
![image](https://user-images.githubusercontent.com/6656168/129902169-b25c7ecc-3997-4e25-b49e-c934d137044b.png)

**Comment by kevinsmia1939** [comment]
> > We will keep updated the flathub package instead. Works better and it is definitely easier to maintain!
> 
> Interesting...so this will then pull KDE, right? That is almost 1GB (platform, locale, etc.)

It does not pull the entire KDE, the KDE runtime will also be share across other apps that use KDE runtime, so when you download other Flatpak apps that use KDE runtime, it won't be as big.
