### ISSUE TITLE
Meshlab ruined my cmd in windows

### ISSUE THREAD

**Issue by NervenCid** [cnr-isti-vclab/meshlab#216]
Hello:

I installed MeshLab in a windows machine, and that installed something called meshlab center that changed my cmd to MeshLab server and  hihacked my cmd. 

I uninstalled Meshlab but my cmde still appear like MeshLabserver

How can i restore cmd?

Is disapointing to lose the comand prompt and a software shouldn't do that is abussive

Thank you

**Comment by mcallieri** [comment]
hello. 
  I'm sorry for the problem.
It is a known bug, we created a shortcut to MeshLabServer using wrong parameters, and Windows redirected the CMD.exe to that folder, it was not our intention :( it is terribly annoying also for us.
We have tried fixing it in the code, but we still do not have a new release.

CMD.exe still opens a shell, and nothing has changed, in terms of how it works, it is just the name of the window. You can still use CMD.exe as usual.
Frankly, we still do not know how to remove the name from the link, once it has been overwritten.
