### ISSUE TITLE
Snap not working on Ubuntu 14.04 again

### ISSUE THREAD

**Issue by omhafez** [cnr-isti-vclab/meshlab#217]
I make the following calls:
`sudo snap install meshlab`
`/snap/bin/meshlab`

and get the following error:
`Gtk-Message: Failed to load module "overlay-scrollbar"`
`Gtk-Message: Failed to load module "unity-gtk-module"`
`Gtk-Message: Failed to load module "canberra-gtk-module"`
`Qt: Session management error: None of the authentication protocols specified are supported`

I am using Ubuntu 14.04.5

Thanks,
Omar

**Comment by jhbell** [comment]
We are experiencing the same error where Meshlab will not open on 16.04 in #215. There is a workaround there that may help temporarily solve the issue for you as well.

**Comment by omhafez** [comment]
Thanks @jhbell, unfortunately in 14.04 I get the following error when attempting the workaround:
`./meshlab: symbol lookup error: /snap/meshlab/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_option_group_unref`

**Comment by omhafez** [comment]
Is there any update on this issue? Thanks in advance.

**Comment by eric-schleicher** [comment]
another workaround is to use a different source.   in my experience, the snaps rare yunk.
https://launchpad.net/~zarquon42/+archive/ubuntu/meshlab

**Comment by alemuntoni** [comment]
This issue should be solved in the latest version (2020.06). Feel free to reopen if the problem persists.
