### ISSUE TITLE
The new version 2016.12 not working in my Windows 10

### ISSUE THREAD

**Issue by LuisGuillermoRR** [cnr-isti-vclab/meshlab#218]
I had an older version of Meshlab (i don'remember which one, i removed it to install the new one) which worked well, but downloaded the 2016.12 version and it doesn't work. It seems to try to rapidly (blink) open one or two windows and then nothing appears. It doesn' work!
So I also removed the 2016.12 version.
Any suggestion?
System: Windows 10 home, 64 bit, version 1703 (compilation 15063.608).
Lenovo Ideacentre B320
CPU: Intel Core i3, Sandy Bridge

**Comment by mcallieri** [comment]
Given the fact the PC is 5 years old, it is highly probable that the videocard does not fully support the GPU features we are using for rendering.
Try updating the videocard drivers.
