### ISSUE TITLE
Sketchfab tags should include "meshlab" by default

### ISSUE THREAD

**Issue by PadreZippo** [cnr-isti-vclab/meshlab#22]
https://github.com/cnr-isti-vclab/meshlab/blob/76ba0ccadf4b7fe5b92da8520e59ceb1058ad446/src/plugins_experimental/filter_sketchfab/filter_sketchfab.cpp#L150

Alternatively, "meshlab" could be the placeholder instead of "scan"

**Comment by cignoni** [comment]
Done with the last commit.
