### ISSUE TITLE
Crush during importing .obj mesh

### ISSUE THREAD

**Issue by Lishen1** [cnr-isti-vclab/meshlab#220]
I use MeshLab_64bit_fp v2016.12 (built on Dec 23 2016), and it crush during importing .obj mesh with only one face (triangle). 
example of mesh:
```
v -1186.90 25.41 385.24
v -1190.26 25.97 385.35
v -1188.18 23.20 385.66
vt 0.05 0.99
vt 0.14 0.89
vt 0.003 0.89
f 1/1/ 2/2/ 3/3/
```

**Comment by alemuntoni** [comment]
I'll close this issue since it should be fixed with the last PR.
Feel free to open another issue if the problem persists.
