### ISSUE TITLE
Meshlabserver won't create filters list text file.

### ISSUE THREAD

**Issue by NikWillmore** [cnr-isti-vclab/meshlab#222]
Windows 10, 64 bit, fresh Meshlab installation, the manual for filters is hiding in the program itself, so I can't read it, as the:

meshlabserver -d Filters.txt 

command crashes Meshlabserver with:

Loading Plugins:
Current Plugins Dir is: C:/Program Files/MeshLab/plugins
Total 241 filtering actions
Total 12 io plugins
called here!

It also seems very odd that it can output a filters log file (blank text file at first), but that it wan't me to create my own blank text file to open and write to?! I did that and that's when the crash happens instead a file not found error. I made the tile with Notepad and then closed Notepad. The crash spits out a Windows error box about Meshlabserver has stopped working. I tried moving Filters.txt out of the Meshlab folder onto my C: drive and it didn't help, so is unlikely a permissions thing, nor did running Cmd.exe as Administrator help. Whether the GUI program was running or not didn't matter.

The -d flag is described rather oddly too:

"-d filename             dump on a text file a list of all the filtering functions"

Dump on?! Why not normal English descriptions of commands and why not just spit out a text file instead of need to open an existing one? Better yet, why not just generate the text file and include it in the directory for me to read? This is very disappointing after being so excited about good triangular remeshing being callable from Python so easily.

When the Windows crash error happens I was able to assign Visual Studio as my debugger and it gave this error:

Unhandled exception at 0x00007FFB64F58378 (filter_layer.dll) in meshlabserver.exe: 0xC0000005: Access violation reading location 0x00000000000000A8.

I can use the -i flag to successfully load an STL file.

Could someone just post the manual here?

**Comment by NikWillmore** [comment]
Next, if I create and export a two step script to do Iso Parameterization remeshing, a script that runs fine in the GUI., meshlabserver.exe fails with a memory error:

C:\Program Files\MeshLab>meshlabserver -i Torus.stl -o TorusOUT.stl -s Iso_Nik.mlx
Loading Plugins:
Current Plugins Dir is: C:/Program Files/MeshLab/plugins
Total 241 filtering actions
Total 12 io plugins
Opening a file with extention stl
Mesh C:/Program Files/MeshLab/Torus.stl loaded has 34764 vn 11588 fn
output mesh  C:/Program Files/MeshLab/TorusOUT.stl
Apply FilterScript: 'C:/Program Files/MeshLab/Iso_Nik.mlx'
FilterScript
Reading filter with name Iso Parametrization: Main
    Reading Param with name targetAbstractMinFaceNum : RichInt
    Reading Param with name targetAbstractMaxFaceNum : RichInt
    Reading Param with name stopCriteria : RichEnum
    Reading Param with name convergenceSpeed : RichInt
    Reading Param with name DoubleStep : RichBool
    Reading Param with name AbsLoadName : RichString
    Reading Param with name AbsSaveName : RichString
Reading filter with name Iso Parametrization Remeshing
    Reading Param with name SamplingRate : RichInt
Starting Script of 2 actionsfilter: Iso Parametrization: Main
no additional memory available!!! memory required: 973392
Problem with filter: Iso Parametrization: Main
Failed to apply script file C:/Program Files/MeshLab/Iso_Nik.mlx

**Comment by paulirotta** [comment]
I saw similar problems, also on Window 10

**Comment by lynconEBB** [comment]
If you need to know the params of a filter, you can aply that filter in MeshLab and then go to "Filters"-> "show Current filter script" and save this script.
