### ISSUE TITLE
filter_csg does not compile in Debian Stretch

### ISSUE THREAD

**Issue by livmion** [cnr-isti-vclab/meshlab#223]
Hi all,

My sistem is `Linux PC-livmion 4.12.0-0.bpo.2-amd64 #1 SMP Debian 4.12.13-1~bpo9+1 (2017-09-28) x86_64 GNU/Linux`. When I try to compile meshlab_full.pro with `qmake -recursive meshlab_full.pro && make` I get the following error:
```
In file included from ../../../../vcglib/vcg/complex/algorithms/update/color.h:33:0,
                 from ../../common/meshmodel.h:35,
                 from filter_csg.h:31,
                 from filter_csg.cpp:24:
../../../../vcglib/vcg/complex/algorithms/clean.h:1803:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for schedule(dynamic, 10)
 
In file included from filter_csg.cpp:29:0:
gmpfrac.h:5:20: fatal error: mpirxx.h: No such file or directory
 #include <mpirxx.h>
                    ^
compilation terminated.
Makefile:984: recipe for target 'filter_csg.o' failed
make[1]: *** [filter_csg.o] Error 1
make[1]: Leaving directory '/home/livmion/git/meshlab/src/meshlabplugins/filter_csg'
Makefile:1144: recipe for target 'sub-meshlabplugins-filter_csg-make_first-ordered' failed
make: *** [sub-meshlabplugins-filter_csg-make_first-ordered] Error 2
```
If I comment `meshlabplugins/filter_csg \` the compilation ends correctly.

Tell me if I can provide you more information. I am not a programmer, but I would do my best.

**Comment by Geremia** [comment]
I get the `sub-common-make_first-ordered` error, too, with with the master branch of MeshLab on Slackware-current:
`make: *** [Makefile:115: sub-common-make_first-ordered] Error 2`

**Comment by alemuntoni** [comment]
This compilation error should be solved in the last versions of MeshLab. Feel free to open a new issue if the problem persists.
