### ISSUE TITLE
Questions about importing normals

### ISSUE THREAD

**Issue by dukeNashor** [cnr-isti-vclab/meshlab#226]
Right now I have a .asc file in 6 columns, with first 3 columns declaring the x,y,z, and the last 3 columns declaring the normals of the point. However when I load this file into Meshlab, it loses all the normals information.

Is this a bug? Is there a way I can load the normals into Meshlab? Then I can directly make use of the Poisson surface reconstruction without having to recalculate the normals.

Thanks.

**Comment by mcallieri** [comment]
hi.
ASC is a very specific data format. However, many tool use the extension ASC also to indicate that they have exported as an ascii list of points + other data.

When this kind of thing happens, do this:
1- rename your file with TXT extension
2- load it in MeshLab, and a parameter dialog will appear
3- in the dialog, you may choose what is inside your file (coordinates, notmals, color, ...) and in which order they are saved, what is the separator (space, semicolon,...) and other details. You have to set them according to your data format

In this way we may load many of these custom ascii clouds

**Comment by dukeNashor** [comment]
Thanks a lot dude.
