### ISSUE TITLE
Fill holes tool disappeared

### ISSUE THREAD

**Issue by pnauer** [cnr-isti-vclab/meshlab#227]
Hi,

in the latest version of Meshlab (v2016.12) the "Fill Holes" tool disappeared from the toolbar and edit menu. I reinstalled an older version (v1.3.3) and there it appears without issues.

Is this intentional, or is it a bug? Couldn't find anything on the web and would be grateful for some clarification...

Running Win10 Education 64bit on a Dell Latitude E7440.
![fill-holes-present_v1-3-3](https://user-images.githubusercontent.com/32826449/31592403-b6757b30-b273-11e7-9d46-fd8a091ba16a.PNG)
![fill-holes-absent_v2016-12](https://user-images.githubusercontent.com/32826449/31592404-b6b526f4-b273-11e7-9120-96bed41d0898.PNG)

Thanks
pnauer

**Comment by mcallieri** [comment]
hi.
It was intentional. The filter was really buggy, and after the update to the 2016.12 code, it was even more unstable.

**Comment by pnauer** [comment]
Thanks for the feedback! Any other way of filling holes in the new version?
(Which is great otherwise!!!)

**Comment by mcallieri** [comment]
There is the "close hole " filter, under the "remeshing..." submenu.
The parameter is the PERIMETER of the hole, in terms of the number of triangles around it.
It automatically closes all holes of that size or below. It is usable on SMALL holes.
