### ISSUE TITLE
Using Meshlab source code in a personal project on Windows

### ISSUE THREAD

**Issue by oeches** [cnr-isti-vclab/meshlab#229]
Dear all,

I have been trying to use meshlab source code in a personal project, on Windows, using Visual Studio 2015 as a compiler.
.vcxproj files have been generated for each meshlab plugins, for common, for meshlab and meshlabserver and for the external parts (ssynth.lib, etc).
The Meshlab part is compiling well.
However, my project do not compile at all due to these errors :
"filter_meshing.lib(moc_meshfilter.obj) : error LNK2005: qt_plugin_query_metadata already defined in filter_measure.lib(moc_filter_measure.obj)
filter_meshing.lib(moc_meshfilter.obj) : error LNK2005: qt_plugin_instance already defined in filter_measure.lib(moc_filter_measure.obj)"

Here is the part of my personal project calling these objects : 
`
MeshDocument *testMesh = new MeshDocument();
MeshModel *testMeshModel = new MeshModel(testMesh->mm());
FilterMeasurePlugin test;
ExtraMeshFilterPlugin filtNorm;
`
As you can see, I am using the common part of Meshlab and the plugins filter_measure and filter_meshing. I have tested with other plugins also and I met the same issues.

I may have missed something when configuring my project but I don't know what : I included all the Qt .h files, linked all the necessary libraries.
Could someone help me solve this issue ?

Regards.

**Comment by martinmartinhi** [comment]
Hi, have you solved this problem? I also want to use meshlab source code in my project? But I'm not sure what I should do. Can you explain it in detail? Thank you very much.

**Comment by mcallieri** [comment]
Hi.
  MeshLab uses the GPL license. So, you may use MeshLab code in your projects, provided that they do not violate the GPL license.
As far as compilation and how to integrate the code in your own projects, I'm afraid, but you are on your own. 
We have now continuous build systems, and we take care that the basic code DOES compile on Windows, MacOS and Linux, bu we are unable to check why the code is not working outside the basic environemnts we have setup.
