### ISSUE TITLE
[discussion] Gentoo adoption

### ISSUE THREAD

**Issue by archenroot** [cnr-isti-vclab/meshlab#230]
Hi,

great stuff here. I open this ticket on behalf of Gentoo community users. From beginning of the year there has been effort to adopt this new version of meshlab into Gentoo tree, so far there are still issues and task is not done as bellow the bug:
https://bugs.gentoo.org/607228

There exists Gentoo working nonfunctional version of ebuild file (ebuild is how Gentoo describe/define packages):
https://gitlab.com/Zelena/hell-overlay/blob/master/media-gfx/meshlab/meshlab-2016.12.ebuild

I would like to leave this issue open to help Gentoo finish the ebuild.

**Question:**
Do you have any plans to support CMake build system? This could dramatically simplify adoption by (not only) Gentoo Linux.

Thank you for any hints.

I also encourage Gentoo package maintainers to discuss here the issues we still have.

**Comment by archenroot** [comment]
Ok, one member identified fork of meshlab repo which already supports cmake style, so I will try to adopt this to see how it goes/work.

https://github.com/starseeker/meshlab

**Comment by holgersson32644** [comment]
Hi, asking mostly as another Gentoo user: Did you make any progress?

**Comment by alemuntoni** [comment]
We do now support cmake build system.
