### ISSUE TITLE
Error in the Align tool

### ISSUE THREAD

**Issue by ammster** [cnr-isti-vclab/meshlab#232]
When i try to Align 2 objects together, I set the first object to be glued and the select the second object then press the point align option the 2 objects are over lying eachother instead of being separate. I am unable to pick points as a result... please help asap...
my email is arihal1@shaw.ca 

![screen shot 2017-10-26 at 4 56 26 pm](https://user-images.githubusercontent.com/23036813/32076885-79a14d70-ba6f-11e7-9e10-f12b6f586f1e.png)

**Comment by mcallieri** [comment]
sorry, it is a known bug, we have fixed it in the code, but unfortunately we still do nothave a release.
I do not have a workaround

**Comment by ammster** [comment]
Thanks for getting back to me! I ended up downloading an earlier version with out the bug so I am back in action. I was wondering if you have a comprehensive site for training on your software you can direct me to... I’m picking up stray stuff on YouTube but I’m looking for something more comprehensive 

Regards
A

**Comment by mcallieri** [comment]
we have videotutorials here: https://www.youtube.com/user/MrPMeshLabTutorials

**Comment by ammster** [comment]
Thanks cheers!!
A
