### ISSUE TITLE
"Cannot open" meshes on Version 2016.12, Windows 10 Home v1703 Build 15063.674

### ISSUE THREAD

**Issue by pfloris** [cnr-isti-vclab/meshlab#233]
I moved some of my .ply files to a different folder, and when I try to open them by directly clicking the icon I get an error:
"Unable to open file: \path_to_file
Error details: file \path_to_file does not exist"
I can still import them after the program starts, so it's not a real problem, though this should not happen.
I can still open other files that I didn't move, directly by clicking the icons.

**Comment by mcallieri** [comment]
you mean when you click on a PROJECT (.mlp) file isn't it? 
you probably had a PROJECT  file that was referencing files in different folders, and now you have moved/renamed the folders.
Well, yes, if the project used a file located in ./oldfolder/foo.ply and now there is no file there, you do get an error....

is this the case?
if so, just open the MLP file with a text editor, and correct the folder names inside.
We have no way to magically detect that a file has been moved.

**Comment by ponneso** [comment]
It is not the case, I mean just (.ply) files. They were created with matlab then just moved to a different folder.
I didn't move any (.mlp) file.

**Comment by mcallieri** [comment]
you double-click a file in a folder, and you get an error?
This is really unheard... 
Is the folder peculiar in some way? (virtual disk, compressed folder, network folder, system folder) is the name of the folder using strange language unicode characters?

**Comment by ponneso** [comment]
Oh ok, it's just the name of the folder then. There's "...\Università\..." in the path. 
Then again, I can still import the mesh once the program is open, so I thank you for taking the time to address such a silly issue.

**Comment by mcallieri** [comment]
It's not silly. Apparently, we have a rpoblem with some letters/symbls, which should not be a problem. We will look into it.

**Comment by Synxis** [comment]
I have to say I also have this problem. By the way, it is the same problem as #196.

**Comment by mcallieri** [comment]
fixing it, not sure if completely removed.

**Comment by mcallieri** [comment]
found another error, and fixed it.
Still searching and testing.

**Comment by mcallieri** [comment]
I did lot more testing, and seems ok, now. I am closing this issue. If some operations still have problems, let me know

You may preview the new version here
The current WIN64 build can be found here

https://ci.appveyor.com/project/cignoni/meshlab/build/artifacts

It is not an installer, just a zipped folder with a "portable" executable. We are starting testing, now, while fixing few more issues. We have used on some machines, here, and seems working. I have no idea, however if it has ALL the possible dll and Runtime that may be needed.

If there is an ongoing build, the site will write "The build job does not contain any artifacts.". In that case, you may wait for the build to end or just click "HISTORY", select the last succesful build, and then "ARTIFACTS"
