### ISSUE TITLE
Surface Reconstruction: Poisson removed in 2016.12

### ISSUE THREAD

**Issue by 3DLIRIOUS** [cnr-isti-vclab/meshlab#234]
This is the same issue as [issue #199](https://github.com/cnr-isti-vclab/meshlab/issues/199), but with additional evidence and explanation. I apologize for reopening the same issue, however I feel it was closed a bit too hastily the first time, and no one seems interested in responding to comments on a closed issue.

The issue is that the "Surface Reconstruction: Poisson" filter was removed from MeshLab in 2016.12, and the newer "Screened Poisson Surface Reconstruction" is not a direct replacement in my experience and tests. The previous filter does not produce as fine of a result, however it is still quite useful, as it has proved to be much more robust for some meshes, and is much simpler to use (only 4 parameters instead of 10). My specific request is either to bring back the previous filter (in addition to the newer one), or explain how to obtain the same results with the newer filter (if even possible).

Issue #199 was closed with the comment "As explained in the help of the screened poisson filter, you can obtain the old behaviour by setting zero in the Interpolation weight parameter", however as will be shown below, this does not appear to be correct.

The first mesh considered is a random spherical point cloud generated using the filters "Points on a Sphere" and "Compute normals for point sets", and is attached. Per the instructions, the Interpolation Weight in the new filter is set to 0 to try to obtain the same results as the old filter. The Octree Depth and Reconstruction Depth are both set to 8, and the rest of the parameters are left as the defaults, as it is not clear what to set them to so as to make the filters as similar to each other as possible.
![screenshot 6](https://user-images.githubusercontent.com/15272764/32120894-eb2a694e-bb1f-11e7-9cb8-835c209017fe.png)

![screenshot 7](https://user-images.githubusercontent.com/15272764/32120904-f7b19ea8-bb1f-11e7-8f09-1f689dc15e82.png)

As can be seen, the results are nowhere near equivalent for this mesh. The newer filter produces a much denser and smoother mesh, however it also has two holes. The older filter produces a coarser mesh, but at least it is watertight.

For a perhaps more realistic example, we will consider bunny10k.ply, included in the MeshLab source. The same parameters will be used as in the previous example.

![screenshot 8](https://user-images.githubusercontent.com/15272764/32120921-0d50a1aa-bb20-11e7-90c7-f6f8035ade6a.png)

![screenshot 9](https://user-images.githubusercontent.com/15272764/32120938-232c32a0-bb20-11e7-8d6f-bb604de13145.png)

The first thing noticed is that the newer filter fails to execute, however the older filter executed fine. This is what is meant in part by the statement that the newer filter is not as robust as the older. After checking the "Pre-Clean" option the newer filter executes, with the results shown below. While the newer filter does produce a nice mesh, it is certainly not equivalent to the results of the previous filter, as it contains nearly twice as many vertices.

![screenshot 12](https://user-images.githubusercontent.com/15272764/32120969-3a3841e6-bb20-11e7-9626-321d96f806f8.png)

I believe that both filters still have valid use cases, and so implore you to please consider adding the "Surface Reconstruction: Poisson" filter back into the next version of MeshLab.

**Comment by 3DLIRIOUS** [comment]
[point_cloud.zip](https://github.com/cnr-isti-vclab/meshlab/files/1423174/point_cloud.zip)

**Comment by ichbinscheisse** [comment]
I agree that the old filter is more robust and I happen to have the exact same problems you mentioned.
Non solid meshes and alot of error messages for not so perfect meshes (can be solved with additonal filters, but on the older poisson you don't have to). Preclean on the newer won't help either.

Right now I'm only using the newer filter to preserve vertex colors, which is a great feature.

**Comment by sonumathur** [comment]
hello how to surface generated in meshlab using ply file,please explaine with example

**Comment by mcallieri** [comment]
For the last time. NO.
What was removed is the older version of the current filter, that was ABANDONED by the authors themselves YEARS ago.
Every other software out there switched to the newer version.
It had severe memory limitations and it DEFORMED the sampled geometry in uncontrollable ways.
The check on invalid normals is there to let you know there are ERRORS in the input data. It's not a matter of being "more robust", it is a matter of being clean and mindful of the data you are working on.

WE DO NOT WANT TO RETURN TO THIS INSANE REQUEST ANYMORE.
