### ISSUE TITLE
no additional memory available!!! memory required: 20130096

### ISSUE THREAD

**Issue by apchenstu** [cnr-isti-vclab/meshlab#235]
Reading filter with name Re-Compute Vertex Normals
    Reading Param with name weightMode : RichEnum
Starting Script of 1 actionsfilter: Re-Compute Vertex Normals
no additional memory available!!! memory required: 20130096

I need to computer vertex normals(loaded has 419378 vn 838752 fn), and got some errors using meshlabserver, what wrong?

**Comment by timothytai** [comment]
hey, have you found a solution? thanks!
