### ISSUE TITLE
Cannot set as default application on macOS. 

### ISSUE THREAD

**Issue by dingzeyuli** [cnr-isti-vclab/meshlab#236]
When I tried to set Meshlab.app as the default app to open stl/obj files, the following error message poped up. I am using the latest macOS High Sierra. But this issue has been around for quite a while, at least a few years on macOS.
![image](https://user-images.githubusercontent.com/5297902/32290650-204cc276-bf11-11e7-9bf9-e82e5c282875.png)

I googled the error message. It seems some plist file is missing, from this [post](http://linuxtoosx.blogspot.com/2016/07/error-associating-all-ply-files-to.html). I followed their fix and it worked.

**Comment by mcallieri** [comment]
It is strange, I have checked the key in the info.plist file that is in our repository, and it is there. And the file has not been updated in a while. 
I will check on MacOS

**Comment by alemuntoni** [comment]
I'll close this issue since it should be fixed with the last PR.
Feel free to open another issue if the problem persists.
