### ISSUE TITLE
Meshlab Server Does Not Work With XVFB

### ISSUE THREAD

**Issue by rustyguts** [cnr-isti-vclab/meshlab#237]
We are using the Meshlab (v1.3) aptitude package on Ubuntu 16.04LTS
We can run meshlabserver with...
`xvfb-run --auto-servernum meshlab -i teapot.obj -o teapot.dae`

However, after upgrading Meshlab to V2016 using snap, we get the following error
`xvfb-run --auto-servernum meshlab.meshlabserver -i teapot.obj -o teapot.dae`

```
Unsupported screen format: depth: 8, red_mask: 0, blue_mask: 0
Unsupported screen format: depth: 8, red_mask: 0, blue_mask: 0
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface.
Unsupported screen format: depth: 8, red_mask: 0, blue_mask: 0
```

Or this command
`xvfb-run -a -s "-screen 0 800x600x24" meshlab.meshlabserver -i teapot.obj -o teapot.dae`

Returns (but never completes)
```
Loading Plugins:
Current Plugins Dir is: /snap/meshlab/4/bin/plugins
```

I also compiled this repo manually with qmake and got the same errors. 

**Is running Meshlab 2016 on Linux with a fully headless environment even possible anymore?**

**Comment by david-zwicker** [comment]
I have a similar problem running meshlabserver in headless mode on Ubuntu 16.04LTS. However, meshlab simply quits with

    GLEW Init: failed!

I suspect that OpenGL is not available, but I'm not sure how to fix this.

**Comment by lizarge** [comment]
Guys, you have some progress with this issue? @Gwydion-Inc @david-zwicker

**Comment by brenwkennedy** [comment]
@lizarge I know this probably doesn't help you but we switched to blender and python scripts. From what we've found, you can mostly do the same things in blender that you can do in meshlab.  We decided the tradeoff between stability and support vs. features was worth it. 

I wish you the best.
