### ISSUE TITLE
New version of Meshlab on Windows 7 32 bit systems

### ISSUE THREAD

**Issue by RaulCarneiroNeto** [cnr-isti-vclab/meshlab#238]
I downloaded a new version of Meshlab, but  I don't saw that the version was only for 64 bit systems.  I don´t found the new version for 32 bit for downloading. I need help...

**Comment by mcallieri** [comment]
32 bit is no longer available. PC and notebooks sold in the last 5 years are almost 100% 64bit systems. It is not possible to support old 32bit legacy code.
