### ISSUE TITLE
Crash when using Quadric Edge Collapse Decimation with .obj exported from Maya

### ISSUE THREAD

**Issue by atouchet** [cnr-isti-vclab/meshlab#239]
Hello,

I have an .obj model of a 3D scan that I am looking to work with in MeshLab. The original model appears to work fine in the program. However I edited the model in Maya first and then exported it to a new .obj file which is the one I am hoping to use in MeshLab. This file opens fine but when I try to run operations such as Quadric Edge Collapse Decimation MeshLab crashes. Do you know why this crash is occurring and if there is a way I can fix it? I have attached a copy of the .obj and .mtl files (the texture has been omitted for privacy reasons).

[model.zip](https://github.com/cnr-isti-vclab/meshlab/files/1447440/model.zip)

My system information:

MeshLab 2016.12
Windows 10 64-bit

**Comment by atouchet** [comment]
I tried selection Turn into a Pure-Triangular mesh before using decimation and that appears to have helped. Does the decimation feature not work on models with non-triangular faces?

**Comment by Gosorio96** [comment]
I am exactly having the same problem. Really hope there´s a fix to that!!

**Comment by m1ndflux** [comment]
I'm having the same issue, especially large meshes seem to cause crashes with Quadric Edge Collapse Decimation.

MeshLab 2016.12
Windows 10 64-bit

**Comment by mcallieri** [comment]
it is not the simplification, it is the rendering of the EDGES. if you disable the rendering of the edges, it works. We will try fixing this.

beware: there is also another (hidden) issue. If you want to export in OBJ, be sure to uncheck the "polygonal" checkbox on the lower-left corner.

I have no problem with large meshes (unless, of course, when they are occupying 80-90% of the RAM, an in that case you simply ran out of memory).

**Comment by fasterthan** [comment]
I too am having the same issue of Meshlab crashing during quadric edge collapse decimation. I am trying to reduce a mesh with 11,190,130 faces in half and I've let the program run overnight but it keeps crashing.

@mcallieri how does one disable the rendering of edges? I don't see anything like that in the Simplification menu.

**Comment by saltfishzzh** [comment]
I am also facing the exact same problem of Mashlab crashing during quadric edge collapse decimation for large meshs... Is there any solution now? 

I don't see how to disable the rendering of edges in the menu as well...

**Comment by den232** [comment]
@mcallieri: you are 100% correct as of Oct 2019.  Whatever that checkbox does, it crashes the export.  Multiple times.   Thanks jb

**_beware: there is also another (hidden) issue. If you want to export in OBJ, be sure to uncheck the "polygonal" checkbox on the lower-left corner._**

**Comment by briana-jin-zhang** [comment]
Also wondering how to disable the rendering of edges in the menu. We are not exporting anything.

**Comment by coreynoxon** [comment]
I've been trying to run this decimation iteratively and the program keeps crashing. The first run through finishes without an issue, but on subsequent iterations it will eventually crash the program. I downloaded the newest version but am still having this issue.

**Comment by alemuntoni** [comment]
> Also wondering how to disable the rendering of edges in the menu. We are not exporting anything.

@briana-jin-zhang just uncheck this button:
![image](https://user-images.githubusercontent.com/6656168/120277076-d8f80700-c2b3-11eb-9d26-b9680f7b0bad.png)



> I've been trying to run this decimation iteratively and the program keeps crashing. The first run through finishes without an issue, but on subsequent iterations it will eventually crash the program. I downloaded the newest version but am still having this issue.

@coreynoxon it is not clear if this issue is related with the problem of rendering the wireframe of the meshes. If the crash happens also when edge rendering is disabled, please open another issue listing the steps to reproduce the issue (and if it's possible share the input mesh). Thanks!

**Comment by coreynoxon** [comment]
@alemuntoni 
I messed around a little more this week. Just to confirm, when I was processing the model I didn't have the wireframe enabled and wasn't to the point of exporting anything. One thing I did realize was that I was using the decimation without texture earlier. When I repeated the same process but used the "with texture" version, I didn't have any issues.
