### ISSUE TITLE
meshlan won't open & crashes every time

### ISSUE THREAD

**Issue by mbouksim** [cnr-isti-vclab/meshlab#24]
Hello
I have this issue only with the last version of meshlab 2016 , when I try to open it it crashes and when I try to use the server it gives me the following error
`Failed to load libEGL (Le module spÚcifiÚ est introuvable.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (Le module spÚcifiÚ est introuvable.)
Failed to load and resolve WGL/OpenGL functions
Failed to load libEGL (Le module spÚcifiÚ est introuvable.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (Le module spÚcifiÚ est introuvable.)
Failed to load and resolve WGL/OpenGL functions
GLEW Init: failed!`

Tried ti force it to use the NVidia and the Intel graphic card but without succeed

**Comment by cignoni** [comment]
Please, read very carefully the following page and if you are willing to write down a complete, informative, effective bug report, re submit your issue. 

[**How to Report Bugs Effectively**
_by Simon Tatham_](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)

Thanks.
