### ISSUE TITLE
MD3 model support.

### ISSUE THREAD

**Issue by uq1** [cnr-isti-vclab/meshlab#242]
I am using Meshlab for generating collision objects, for which it is awesome software, but using multiple programs and converting between them takes a lot of time. Is there any chance Quake 3 MD3 model support could be added?

Note: I don't care at all about MD3 animation support, just static single frame models.

**Comment by mcallieri** [comment]
It will be unlikely, sorry.
It's not very used, and there are tons of custom, game-related data we do not support.
