### ISSUE TITLE
Compute normals for point sets into filter scripts integration

### ISSUE THREAD

**Issue by SPike666** [cnr-isti-vclab/meshlab#243]
Can you enable adding "Normals, Curvatures and Orientation>Compute normals for point sets" to filter script?

I'm using Meshlab for point cloud to 3d mesh conversion and want to automate it via meshlabserver scripts, but before running poisson reconstruction and transferring vertex colors to textures I have to compute normals which can't be done through meshlabserver script.

I also obtained a messages like "segmentation fault(core dumped)"(Ubuntu) and "no additional memory available!!!"(windows) on poisson reconstruction before figured out that it happens due to missing normals.

**Comment by Eimantas-S** [comment]
Having the exact same issue. Would like to automate the process of surface creation using Meshlabserver scripts and use the output file for later processes.

Is there any way around it?

**Comment by alemuntoni** [comment]
We are going to dismiss meshlabserver in the future, and replace it with [PyMeshLab](https://github.com/cnr-isti-vclab/PyMeshLab). 
PyMeshLab includes also the "compute normals for point sets" filters ([here](https://pymeshlab.readthedocs.io/en/latest/filter_list.html#compute_normals_for_point_sets) is the documentation)! It is an alpha stage, and we are looking for feedbacks :)
