### ISSUE TITLE
Last binaries are from 2016. Any plans to update them? =)

### ISSUE THREAD

**Issue by chipweinberger** [cnr-isti-vclab/meshlab#247]

**Comment by nh2** [comment]
It would indeed be very nice if a new release could be made.

**Comment by mcallieri** [comment]
We are trying to do a new release, hopefully, in January.
We were very busy, at the lab, in these last months :(, and the date slipped again and again.

**Comment by chipweinberger** [comment]
Awesome! I'm looking forward to it.
