### ISSUE TITLE
meshlabserver does not report program version

### ISSUE THREAD

**Issue by david-zwicker** [cnr-isti-vclab/meshlab#249]
I could not find any way to extract the version of the installed meshlab using `meshlabserver`. I use meshlabserver to automate mesh conversion and editing, but since the parameters of the filters sometimes change from version to version, it would be great to have an idea what version of meshlab I'm dealing with. This is especially important in heterogeneous computing environments, where the same code needs to work on different machines with different software environments.

I suggest adding the standard command line flags `-v` and `--version` to `meshlabserver`, which would simply print the meshlab version (and possibly other useful information, like libraries and compilers) to stdout.

**Comment by mcallieri** [comment]
adding version output, when calling meshlabserver without parameters.
