### ISSUE TITLE
MashLab crash when I run it

### ISSUE THREAD

**Issue by kozintsev** [cnr-isti-vclab/meshlab#25]
Hello!

MashLab crash when I run it

[Screenshot](https://dl.dropboxusercontent.com/u/54495412/2016-12-27%2017_00_27-meshlab.exe.png)

**Comment by cignoni** [comment]
I am sorry, but this report does not contain enough background info to be useful.
Please, read very carefully the following document on how report issues, and, if you are willing to write down a complete, informative, effective bug report, re submit your issue. 

[**How to Report Bugs Effectively**
_by Simon Tatham_](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)

Thanks.
