### ISSUE TITLE
Crash when trying to Plot Curvatures

### ISSUE THREAD

**Issue by Marriaga** [cnr-isti-vclab/meshlab#251]
**Issue**: Software crashes when trying to render the curvatures Render>Show Curvature
**System**: Win7 64-bit, Intel Xeon E5606 CPU, 80GB RAM, ATI FirePro V4800 4GB
**Steps to reproduce**:

1. Open MeshLab
2. Filters > Create New Mesh Layer > Dodecaheadron
3. Filters > Polygonal and Quad Mesh > Turn into a Pure-Triangular mesh
4. Filters > Remeshing, Simplification and Reconstruction > Subdivision Surfaces: Butterfly Subdivision > Apply
5. Filters > Normals, Curvatures and Orientation > Compute curvature principal directions > Apply
6. Render > Show Curvature (Crashes)

**Comment by mcallieri** [comment]
yes, you are right.
It was trying to access both vertex and faces curvature WITHOUT checking first if they were available
Corrected in the code. We are waiting for a new Release
