### ISSUE TITLE
Unbounded memory usage leading to system freeze when exporting OBJ on Windows 7.

### ISSUE THREAD

**Issue by adambuchbinder** [cnr-isti-vclab/meshlab#253]
To reproduce: download [parkbench.zip](https://github.com/cnr-isti-vclab/meshlab/files/1533185/parkbench.zip), and unzip to get the OBJ file.

Install meshlab (2016.12) from the website, 64-bit Windows version, running on Windows 7. Import the mesh, note that it says errors were fixed. Export the mesh as a new OBJ file. Memory usage in Task Manager will rise unboundedly, until the machine locks up. (It got to 25GB for me; note that this is a 2MB file.)

Using meshlab 1.3.2+dfsg1-4 on Debian, I can follow the same steps, and the file is written out properly.

**Comment by baalrog** [comment]
I believe I'm experiencing the same issue, but without meshlab claiming to fix any errors. Unzip [nako.zip](https://github.com/cnr-isti-vclab/meshlab/files/1546893/nako.zip), import into meshlab, export as obj. Meshlab goes unbounded. I'm in Windows10. 

The software that created this mesh is called Instant Meshes. I've opened and saved dozens of objs from other software without a hitch.

**Comment by mcallieri** [comment]
sorry, it is aknown bug.
When you export, a window will pop up, asking which properties you want to save. On the bottom of that window, there is a checkbox named "polygonal". be sure to uncheck it.
It has been corrected in the code, but we are still waiting a release
