### ISSUE TITLE
Latest meshlab cannot load obj files that has tif textures

### ISSUE THREAD

**Issue by jasjuang** [cnr-isti-vclab/meshlab#255]
I am having problems loading obj files that uses tif images as textures for the 2016.12 meshlab, not that this problem doesn't exist in the older meshlab 2013.

Here is a minimal cube obj to reproduce it

```
# cube.obj
#
mtllib ./cube.mtl 
g cube
 
v -0.500000 -0.500000 0.500000
v 0.500000 -0.500000 0.500000
v -0.500000 0.500000 0.500000
v 0.500000 0.500000 0.500000
v -0.500000 0.500000 -0.500000
v 0.500000 0.500000 -0.500000
v -0.500000 -0.500000 -0.500000
v 0.500000 -0.500000 -0.500000

vt 0.000000 0.000000
vt 1.000000 0.000000
vt 0.000000 1.000000
vt 1.000000 1.000000

vn 0.000000 0.000000 1.000000
vn 0.000000 1.000000 0.000000
vn 0.000000 0.000000 -1.000000
vn 0.000000 -1.000000 0.000000
vn 1.000000 0.000000 0.000000
vn -1.000000 0.000000 0.000000

g cube
usemtl cube
s 1
f 1/1/1 2/2/1 3/3/1
f 3/3/1 2/2/1 4/4/1
s 2
f 3/1/2 4/2/2 5/3/2
f 5/3/2 4/2/2 6/4/2
s 3
f 5/4/3 6/3/3 7/2/3
f 7/2/3 6/3/3 8/1/3
s 4
f 7/1/4 8/2/4 1/3/4
f 1/3/4 8/2/4 2/4/4
s 5
f 2/1/5 8/2/5 4/3/5
f 4/3/5 8/2/5 6/4/5
s 6
f 7/1/6 1/2/6 5/3/6
f 5/3/6 1/2/6 3/4/6
```

cube.mtl

```
newmtl material0
Ka 0 0 0
Ks 0 0 0
map_Kd test.tif
```

test.tif can be any random tiff image. Double click the cube obj it will fail. If test.tif is changed into test.png it will work. Would be great to see it fixed.

**Comment by mcallieri** [comment]
it does work for me.... 
You have an error because in the file you mention a material called "cube"
usemtl cube
but then in the mtl file you specify a material called material0
newmtl material0
but, in the end, the texture is loaded anyway.

**Comment by jasjuang** [comment]
@mcallieri Even if I change `material0` to `cube` it still fails for me. I even tried jpg files and it works. Only tif files are not working. Which tif file did you use to test?

**Comment by mcallieri** [comment]
[tif.zip](https://github.com/cnr-isti-vclab/meshlab/files/1689332/tif.zip)

**Comment by jasjuang** [comment]
I downloaded your zip file and double click it didn't work. Here are a few screen shots 

![screenshot from 2018-02-02 09-25-37](https://user-images.githubusercontent.com/11759200/35747095-ead3e210-07fd-11e8-9e75-df285d8c0ca1.png)
![screenshot from 2018-02-02 09-25-47](https://user-images.githubusercontent.com/11759200/35747099-ef38b3a8-07fd-11e8-9f9b-348e8c416584.png)
![screenshot from 2018-02-02 09-25-54](https://user-images.githubusercontent.com/11759200/35747105-f3034106-07fd-11e8-96d5-a71dc5f9f010.png)

Additionally my meshlab is the 2016.12 version:

```
$ sudo apt install meshlab
Reading package lists... Done
Building dependency tree       
Reading state information... Done
meshlab is already the newest version (2016.12~xenial2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by mcallieri** [comment]
we use QT for image input/output. We have to packa series of external libs for QT to load certains formats, and it is always a mess.
We will look into it, but I have no idea if I can pull it off.

**Comment by jasjuang** [comment]
@mcallieri I tried it out on another computer and I encounter the same problem. Just to double check, are you testing on the latest master or the 2016.12 version?

I am having trouble to compile the latest master myself to test whether his problem is fixed in the latest master.

**Comment by rahulbhadani** [comment]
I can confirm that I am having the same problem except I have tga while instead of tif file. I use Ubuntu 18.04.

**Comment by csparker247** [comment]
Hitting this issue on 2021.07 on macOS.

**Comment by alemuntoni** [comment]
@csparker247 please open a new issue describing the issue and sharing the file that causes it.
