### ISSUE TITLE
Load multiple mesh is really slow

### ISSUE THREAD

**Issue by JamesYangLim** [cnr-isti-vclab/meshlab#256]
Hi,

I tried to load some of the mesh and it gets really slow when it gets to 80 meshes where each mesh contain about 10 triangles with the size of 4KB which is not big at all.

I guess there might be a bug that cause the loading of the meshes really slow. 
Other than that, this is an awesome software to use.

If this can be fixed soon that will be great!

Cheers, 
James

**Comment by mcallieri** [comment]
Yes, when a lot of meshes are loaded (or a project with moe than 40-50 layers is loaded) MeshLab takes an insane amout of time to load them.
We have corrected the bg in the code, and we are waiting a release (hopefully, soon).

**Comment by Kiord** [comment]
Hi, 
Is this issue resolved? I'm still encountering it in the latest MeshLab version (2023.12)
