### ISSUE TITLE
Export to .u3D

### ISSUE THREAD

**Issue by MastaEnmey** [cnr-isti-vclab/meshlab#257]
Hi,

I'm having an issue when I try to export in .u3D even if I have installed plugins U3D_OSX and U3D_W32. When I export in .u3D Meshlab is bugging and doesn't answer anymore.

Thx for help

**Comment by alemuntoni** [comment]
This should be fixed with #557. 
The feature will be available starting from MeshLab 2020.02.
Feel free to open a new issue if you still have troubles with U3D!
