### ISSUE TITLE
MLRenderingData::GLOptionsType not a member...

### ISSUE THREAD

**Issue by fordfrog** [cnr-isti-vclab/meshlab#258]
i'm trying to create meshlab live ebuild on gentoo linux distro but compilation fails for me with following error:
```
meshlabdocumentxml.cpp: In function ‘bool MeshDocumentFromXML(MeshDocument&, QString, bool, std::map<int, MLRenderingData>&)’:
meshlabdocumentxml.cpp:115:23: error: ‘GLOptionsType’ is not a member of ‘MLRenderingData’
      MLRenderingData::GLOptionsType opt;
                       ^~~~~~~~~~~~~
```
i tried to search the code where the reference occurs and where the definition is, but i got only this:
```
$ git grep GLOptionsType
src/common/meshlabdocumentxml.cpp:                                      MLRenderingData::GLOptionsType opt;
src/common/meshlabdocumentxml.cpp:      MLRenderingData::GLOptionsType opt;
```
the ebuild (building script) and applied patch can be seen here: https://cgit.gentoo.org/dev/fordfrog.git/tree/media-gfx/meshlab

am i doing something wrong or is it a code bug?

**Comment by baronzzl** [comment]
I meet the same problem, did you had resolve?

**Comment by andorardo** [comment]
Same problem here.

**Comment by learnForever90** [comment]
same problem. any fixes?

**Comment by aambrosano** [comment]
Switching to branch 'devel' on vcglib solved the issue for me.

**Comment by mcallieri** [comment]
As specified in the compiling instructions, the DEVEL branch should be used.
