### ISSUE TITLE
Crash When Exporting Obj Files

### ISSUE THREAD

**Issue by Lockedbeast** [cnr-isti-vclab/meshlab#260]
Hello , for the past week i tried everything to fix this but it didnt work ! also i tried to research but no one really said how to fix it ! 

So basically it just crashes after i press export then press ok ! 
I used the simplification quadric edge filter on my model and thats it !

**Comment by mcallieri** [comment]
hello.
Sorry, our fault.  It is a known bug. 
When you export, a window will pop up, asking which properties you want to save. On the bottom of that window, there is a checkbox named "polygonal". be sure to uncheck it.
We have fixed it int he code, but we do not have a new release yet.
