### ISSUE TITLE
Is there any way to use MeshLab source code with C++

### ISSUE THREAD

**Issue by Visheshevi** [cnr-isti-vclab/meshlab#261]
I want to use the provided source code on Windows. In the src folder there are some instructions given to compile Meshlab. Is that the correct procedure to start working on MeshLab source code with C++

**Comment by charmland** [comment]
VCGLib is the core library of meshlab, you can try that.

**Comment by Visheshevi** [comment]
But, it requires Qt which is a paid software.

**Comment by cignoni** [comment]
Yes MeshLab requires Qt and Qt is free under (L)GPL v3 license obligations.
