### ISSUE TITLE
Crash while taking snapshot if one of meshes was removed

### ISSUE THREAD

**Issue by adammandryk** [cnr-isti-vclab/meshlab#263]
OSX 10.13.2

To reproduce:
1. Open application
2. Import (at least) 3 meshes
3. Delete middle one
4. Try taking snapshot with "snap all layers" option checked

Application crashes at  `GLArea::saveSnapshot() + 550`

**Comment by dempo93** [comment]
Happens on ubuntu as well.

**Comment by mcallieri** [comment]
Yes, it was an error in managing the layer list. Thanks.
corrected in code.
