### ISSUE TITLE
Loading .OBJ file results in Error due to one Tab separation in Vertex field 

### ISSUE THREAD

**Issue by ozzp** [cnr-isti-vclab/meshlab#267]
"No vertex found" error message while loading .OBJ file that uses Tab-separation:

v       0.5     -0.5    0.5

The tab placed between v and the first coordinate results in the loading error described above.  The tab-separators between other fields do not produce error.  The workaround is to use "space+tab" separator between "v" and the first coordinate.  

The test .OBJ file is attached to this report and also listed below:

o       1

v       -0.5    -0.5    +0.5
v       -0.5    -0.5    -0.5
v       -0.5    +0.5    -0.5
v       -0.5    0.5     0.5
v       0.5     -0.5    0.5
v       +0.5    -0.5    -0.5
v       +0.5    0.5     -0.5
v       +0.5    0.5     0.5

usemtl Default
f       4       3       2       1
f       2       6       5       1
f       3       7       6       2
f       8       7       3       4
f       5       8       4       1
f       6       7       8       5

[box_tab_obj.txt](https://github.com/cnr-isti-vclab/meshlab/files/1644204/box_tab_obj.txt)

**Comment by mcallieri** [comment]
found it, thanks.
Corrected the code. We are waiting for a Release
