### ISSUE TITLE
Errors while compiling "common" subproject under Linux

### ISSUE THREAD

**Issue by eboudrand** [cnr-isti-vclab/meshlab#27]
I failed to compile "common" subproject in meshlab_full project. Two errors are related to ml_shared_data_context.cpp file. Here is the log. I removed unecessary warnings before the 2 compiling errors.

g++ -c -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DMESHLAB_SCALAR=float -DGLEW_STATIC -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_SCRIPT_LIB -DQT_CORE_LIB -I../../src/common -I. -I../../../meshlab -I../../../vcglib -I../../src/external/glew-1.7.0/include -I../../src/common -I../../src/external/jhead-2.95 -I/opt/Qt/5.7/gcc_64/include -I/opt/Qt/5.7/gcc_64/include/QtOpenGL -I/opt/Qt/5.7/gcc_64/include/QtWidgets -I/opt/Qt/5.7/gcc_64/include/QtGui -I/opt/Qt/5.7/gcc_64/include/QtXml -I/opt/Qt/5.7/gcc_64/include/QtXmlPatterns -I/opt/Qt/5.7/gcc_64/include/QtNetwork -I/opt/Qt/5.7/gcc_64/include/QtScript -I/opt/Qt/5.7/gcc_64/include/QtCore -I. -I/opt/Qt/5.7/gcc_64/mkspecs/linux-g++ -o ml_shared_data_context.o ../../src/common/ml_shared_data_context.cpp

[...]

../../src/common/ml_shared_data_context.cpp: In member function ‘void MLSceneGLSharedDataContext::setRenderingDataPerAllMeshViews(int, const MLRenderingData&)’:
../../src/common/ml_shared_data_context.cpp:81:8: error: ‘MLSceneGLSharedDataContext::PerMeshMultiViewManager {aka class vcg::QtThreadSafeGLMeshAttributesMultiViewerBOManager<CMeshO, QGLContext*, MLPerViewGLOptions>}’ has no member named ‘setPerAllViewsInfo’
   man->setPerAllViewsInfo(perviewdata);
        ^
../../src/common/ml_shared_data_context.cpp: In member function ‘void MLSceneGLSharedDataContext::drawAllocatedAttributesSubset(int, QGLContext*, const MLRenderingData&)’:
../../src/common/ml_shared_data_context.cpp:242:8: error: ‘MLSceneGLSharedDataContext::PerMeshMultiViewManager {aka class vcg::QtThreadSafeGLMeshAttributesMultiViewerBOManager<CMeshO, QGLContext*, MLPerViewGLOptions>}’ has no member named ‘drawAllocatedAttributesSubset’
   man->drawAllocatedAttributesSubset(viewid,dt);

Compiled on Ubuntu 16.04 LTS 64 bits

**Comment by cignoni** [comment]
Are you using the master or the devel branch of the vcglib?
As specified in https://github.com/cnr-isti-vclab/meshlab/tree/master/src you should use the 'devel' branch.

**Comment by eboudrand** [comment]
I was using master branch of vcglib. Thanks for pointing to the remark. I did not see it.
