### ISSUE TITLE
g1 errors: invalid frame buffer operation when importing

### ISSUE THREAD

**Issue by Jekyll1021** [cnr-isti-vclab/meshlab#270]
when I tried to import a .ply file, I got this:

> Warning:
 Warning: There are gl errors: invalid framebuffer operation
There are gl errors: invalid framebuffer operation
Opened mesh /Users/Xenon/reconstruction.ply in 41 msec
All files opened in 105 msec

I'm using OSX 10.13.2 if that helps. The ply file I'm trying to open is as follows:

> ply
format ascii 1.0
element vertex 2023
property float x
property float y
property float z
property uchar diffuse_red
property uchar diffuse_green
property uchar diffuse_blue
end_header
33.7108091878 31.6569917994 23.7537000481 119 102 84
25.9036459588 36.8281519188 10.5753783873 70 69 72
12.127708212 29.1458324876 18.7300654534 114 101 87
22.7986018495 37.2679894192 25.3039650765 83 83 78
12.6235208752 30.4022112387 15.429541357 64 55 52
29.2666941217 33.0126523305 24.8780594363 42 26 24
12.1285117351 29.8477535764 24.5362270026 220 214 197
4.15614687527 28.3375184266 6.46250742734 202 181 158
..........

So the formatting looks good to me.

**Comment by mcallieri** [comment]
nothing to worry about.
The GL errors on MacOS are due to a long-lasting bug of the QT library.... it does not cause problems, but we simply cannot get rid of it :(

**Comment by jiapei100** [comment]
From my side, the 3D model is NOT showing at all, probably due to **There are gl errors: invalid framebuffer operation** .

**Comment by alemuntoni** [comment]
@jiapei100 please open a new issue describing the platform and the meshlab version you are using, and listing as much details as possible to help us to reproduce and then resolve the problem.
