### ISSUE TITLE
filter not applying, 'no additional memory available'

### ISSUE THREAD

**Issue by timothytai** [cnr-isti-vclab/meshlab#272]
Hi,

I encountered the problem that when I tried to apply "Turn into Quad-Dominant mesh" in MeshLab, everything works fine, but when I tried to apply a script simply containing this filter in MeshLabServer, the commandline returns the below:

```
Microsoft Windows [Version 10.0.16299.192]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Program Files\VCG\MeshLab>meshlabserver.exe -i C:\Test\TestExport1.obj -o C:\Test\TestExport2.obj -s C:\Users\user\Desktop\model_current\transfer\MeshLab_Filter_QuadDominant.mlx
Loading Plugins:
Current Plugins Dir is: C:/Program Files/VCG/MeshLab/plugins
Total 241 filtering actions
Total 12 io plugins
Opening a file with extention obj
Mesh C:/Test/TestExport1.obj loaded has 100 vn 146 fn
output mesh  C:/Test/TestExport2.obj
Apply FilterScript: 'C:/Users/user/Desktop/model_current/transfer/MeshLab_Filter_QuadDominant.mlx'
FilterScript
Reading filter with name Turn into Quad-Dominant mesh
    Reading Param with name level : RichEnum
Starting Script of 1 actionsfilter: Turn into Quad-Dominant mesh
no additional memory available!!! memory required: 4152
Mesh C:/Test/TestExport1.obj saved as C:/Test/TestExport2.obj (100 vn 146 fn)
```

In addition, when I tried to apply the 4-8 Subdivision after the Quad Dominant, MeshLab seems to be returning the wrong face counts. For instance, with an input [triangular mesh (V:100 F:146)](https://www.dropbox.com/s/4w441xhr2w8o11y/ml_tri.png?dl=0), the Quad Dominant filter turns the mesh into all quads and MeshLab shows that [the current mesh still has the same amount of V and F](https://www.dropbox.com/s/8ab7rtk1uyy6625/ml_quad1.png?dl=0), while it seems like it should be (V:100 F:75), and after the 4-8 Subdivision filter, MeshLab shows the [mesh as (V:207 F:324)](https://www.dropbox.com/s/93vn018vv2axuas/ml_quad2.png?dl=0), while it seems like it should be (V:207 F:162).

Essentially, I would love to run MeshLabServer through commandline, and filter meshes with first Quad Dominant and then 4-8 Subdivision, and then outputs a separate file.
Any help or advice would be greatly appreciated.

Thanks a lot!

Tim

**Comment by granzuglia** [comment]
Probably you can forget about the "no additional memory available!!! memory required: 4152". 99% of the times it is completely meaningless. My fault, sorry.  I will take a look on the filter and i will let you know in the next week.

**Comment by timothytai** [comment]
Hi granzuglia,

Thanks a lot for the response. I've gone through a few of the related threads, and read that most of the time it has no effect on the output, like you said. However, the command is actually not producing the desired/expected mesh as it does through MeshLab. Please find [here the input triangular mesh in OBJ](https://www.dropbox.com/s/u7zr9e1v4z775mz/ml_tri.obj?dl=0) as described in the original post, the [mesh after Quad Dominant filter](https://www.dropbox.com/s/1y7knddkdrqqfy8/ml_quad1.obj?dl=0) is applied in MeshLab, and finally the [mesh after 4-8 Subdivision](https://www.dropbox.com/s/i4ucp4ne1bdexnf/ml_quad2.obj?dl=0) after the first Quad conversion.
MeshLabServer is not producing either of the latter.

Thanks again!

**Comment by timothytai** [comment]
Hi granzuglia,

Following up on this since it's been a while.

Thanks a lot!

**Comment by timothytai** [comment]
perhaps @mcallieri ?

simply - i could not get "Turn into Quad-Dominant mesh" working on a simple triangular mesh through meshlabserver even though it works just fine on the actual mesh lab application.

thanks you!

**Comment by timothytai** [comment]
I realized the filters do seem to be applying, as you suggested @granzuglia , but somehow the exporting is only outputing triangular faces, hence the Quad-Dominant filter alone is not visible. If you try Quad-Dominant and then 4-8 in MeshLabServer, and re-import the output into MeshLab, you will see that there are changes made, but the faces remain as triangles.
