### ISSUE TITLE
Exported X3D doesn't comply with the standards

### ISSUE THREAD

**Issue by AndreAhmed** [cnr-isti-vclab/meshlab#273]
Hi,
X3D file format exported from mesh lab has the ImageTexture url = "image.pnp", it doesn't have a tag like url = '"image.png"'. Which is not in the standards of the web3d.

**Comment by mcallieri** [comment]
ok, maybe I have understood... are you saying the ImageTexture url is supposed to be a LIST of values, and not a single value ?

**Comment by mabuchner** [comment]
I think, he is trying to say that [`url` is a MFString](http://www.web3d.org/documents/specifications/19775-1/V3.2/Part01/components/texturing.html#ImageTexture). Therefore `url='"image.png"'` or `url="&quot;image.png&quot;"`  is the correct spelling, but MeshLab seems to output `url="image.png"`.

**Comment by AndreAhmed** [comment]
@mabuchner  Yes that's what I wanted to say

**Comment by mcallieri** [comment]
corrected. Now it saves:
<ImageTexture url="&quot;Texture.png&quot;"/>
just out of curiosity, which was the tool not opening the other encoding? Because, looking online, i found many tens of examples with the single quote.

**Comment by mabuchner** [comment]
[Assimp](https://github.com/assimp/assimp)
