### ISSUE TITLE
Vertex color to texture (1 Mesh or 2 mesh)

### ISSUE THREAD

**Issue by sarvagyshah** [cnr-isti-vclab/meshlab#274]
vertex color to texture is not working #
![1](https://user-images.githubusercontent.com/36230868/35916343-f97082c8-0bbe-11e8-81da-2b8d8b32f034.png)

**Comment by mcallieri** [comment]
well, looks a nice artistic result, to me.

Any more specific detail on the problem? It is hard to guess what is wrong from this image... This screenshot is not from MeshLab, isn't it?
We have corrected few issues about multiple textures, in the filter, but are still not live in the release.
