### ISSUE TITLE
pressing numeric 7 shows model upside down

### ISSUE THREAD

**Issue by macsimski** [cnr-isti-vclab/meshlab#276]
the z arrow is pointing down in stead of up, hence the model is shown upside down

version 2016-12 64 bit linux

**Comment by mcallieri** [comment]
MeshLab, as some other tools, uses the Computer Graphics axis convention, where Y is up (looking at the screen, X is horizontal, going right, Y is vertical, going up, Z is depth, going towards observer). Engineering axis convention has X-Y as ground (X is east-west going east, Y is north-south going north) and Z as vertical axis. Both conventions are used. 
As we use both:
1 3 7   are front, right, top for CG axis  (and ctrl-1 ctrl-2 ctrl-3 are back, left, bottom)
alt-1 alt-2 alt-3 are front, right, top for ENGINEERING axis (and ctrl-alt-1 ctrl-alt-2 ctrl-alt-3 are back, left, bottom)

**Comment by macsimski** [comment]
Thanks. I could not find this info in the help files.
