### ISSUE TITLE
Functors.h not found

### ISSUE THREAD

**Issue by fishcu** [cnr-isti-vclab/meshlab#279]
I tried to compile meshlab on Ubuntu 16.04, pretty fresh install, QT 5.7.1.

I checked out master branch of meshlab and devel branch of vcglib. Compiling with Qt Creator gives me:
`error: No rule to make target '../../../vcglib/eigenlib/Eigen/src/Core/Functors.h', needed by 'filterparameter.o'.  Stop.`

It seems Functors.h was once part of Eigen, but is not with the current version. What's the best way to get it to compile?

**Comment by cignoni** [comment]
probably for some path issue you are not using the version of eigen provided with meshlab. Look at the travis configuration files to see how to set up a ubuntu compiling env.

**Comment by fishcu** [comment]
Check out the path in the error.

It is trying to look for a file that is not actually present in the repo. See here: https://github.com/cnr-isti-vclab/vcglib/tree/devel/eigenlib/Eigen/src/Core -- there is only "functors" subfolder, but no file "Functors.h".

So, either:
1. filterparameter has a wrong include and needs to be fixed
2. The repo (devel branch) of vcglib has the wrong version of Eigen included
3. You are expecting an installation of Eigen by a different process (for example, manual installation of newest version in /usr/local/include) without stating it.

Nothing to do with path issues. Please reopen issue.

**Comment by avnermosh** [comment]
I have the same problem on my side.

**Comment by chaitanya100100** [comment]
Any workaround ?

**Comment by cignoni** [comment]
Currently meshlab compiles correctly on Ubuntu 14.04.5 LTS 
see the travis log here:
https://travis-ci.org/cnr-isti-vclab/meshlab/jobs/368720331

Please try to see how your system config differs from the above

**Comment by Theophile88** [comment]
Same problem here.
