### ISSUE TITLE
Crash "Error While parsing the XML filter plugin descriptors"

### ISSUE THREAD

**Issue by luntik2012** [cnr-isti-vclab/meshlab#281]
meshlab version
MeshLab_64bit_fp v2016.2 (build on Feb 22 2018) (git verions from AUR(archlinux))

stl files: 
https://mega.nz/#!ZcRV2LiB!IxHDjVTjS-OBMCyEraYesiF6iLN0BRu01XxbBLrLN3Y
https://mega.nz/#!pJRzlTzQ!YQrooCthDX3IS2rBy82sjVPunuEZhzRV6PJaSK1Bpbw
https://mega.nz/#!1cAlxJTD!qt2XdHPIX4h9o_0Thxs_akaqOOBWgZb16TZCjo15Sf4

`Current Plugins Dir is: /usr/lib/meshlab/plugins 
Error While parsing the XML filter plugin descriptors: We are trying to load a xml file that does not correspond to any dll or javascript code; please delete all the spurious xml files
    Reading Param with name MeshLab::Appearance::backgroundBotColor : RichColor
    Reading Param with name MeshLab::Appearance::backgroundTopColor : RichColor
    Reading Param with name MeshLab::Appearance::baseLightAmbientColor : RichColor
    Reading Param with name MeshLab::Appearance::baseLightDiffuseColor : RichColor
    Reading Param with name MeshLab::Appearance::baseLightSpecularColor : RichColor
    Reading Param with name MeshLab::Appearance::fancyBLightDiffuseColor : RichColor
    Reading Param with name MeshLab::Appearance::fancyFLightDiffuseColor : RichColor
    Reading Param with name MeshLab::Appearance::logAreaColor : RichColor
    Reading Param with name MeshLab::Appearance::pointDistanceAttenuation : RichBool
    Reading Param with name MeshLab::Appearance::pointSize : RichFloat
    Reading Param with name MeshLab::Appearance::pointSmooth : RichBool
    Reading Param with name MeshLab::Appearance::textColor : RichColor
    Reading Param with name MeshLab::Appearance::textureMagFilter : RichEnum
    Reading Param with name MeshLab::Appearance::textureMinFilter : RichEnum
    Reading Param with name MeshLab::Decoration::AreaHistParam : RichBool
    Reading Param with name MeshLab::Decoration::BBAbs : RichBool
    Reading Param with name MeshLab::Decoration::BoxRatio : RichFloat
    Reading Param with name MeshLab::Decoration::CameraFixedScaleParam : RichFloat
    Reading Param with name MeshLab::Decoration::CameraRenderScaleType : RichEnum
    Reading Param with name MeshLab::Decoration::CameraShowCameraDetails : RichBool
    Reading Param with name MeshLab::Decoration::CurvatureLength : RichFloat
    Reading Param with name MeshLab::Decoration::EnableAlpha : RichBool
    Reading Param with name MeshLab::Decoration::FixedHistMaxParam : RichFloat
    Reading Param with name MeshLab::Decoration::FixedHistMinParam : RichFloat
    Reading Param with name MeshLab::Decoration::FixedHistWidthParam : RichFloat
    Reading Param with name MeshLab::Decoration::GridBack : RichBool
    Reading Param with name MeshLab::Decoration::GridColorBack : RichColor
    Reading Param with name MeshLab::Decoration::GridColorFront : RichColor
    Reading Param with name MeshLab::Decoration::GridMajor : RichFloat
    Reading Param with name MeshLab::Decoration::GridMinor : RichFloat
    Reading Param with name MeshLab::Decoration::HistBinNumParam : RichInt
    Reading Param with name MeshLab::Decoration::HistType : RichEnum
    Reading Param with name MeshLab::Decoration::LabelEdgeFlag : RichBool
    Reading Param with name MeshLab::Decoration::LabelFaceFlag : RichBool
    Reading Param with name MeshLab::Decoration::LabelVertFlag : RichBool
    Reading Param with name MeshLab::Decoration::MeshBlendingColor : RichColor
    Reading Param with name MeshLab::Decoration::NormalFaceFlag : RichBool
    Reading Param with name MeshLab::Decoration::NormalLength : RichFloat
    Reading Param with name MeshLab::Decoration::NormalVertFlag : RichBool
    Reading Param with name MeshLab::Decoration::ProjRasterAlpha : RichDynamicFloat
    Reading Param with name MeshLab::Decoration::ProjRasterLighting : RichBool
    Reading Param with name MeshLab::Decoration::ProjRasterOnAllMeshes : RichBool
    Reading Param with name MeshLab::Decoration::SSAORadius : RichFloat
    Reading Param with name MeshLab::Decoration::ShadowIntensityVal : RichDynamicFloat
    Reading Param with name MeshLab::Decoration::ShadowMethod : RichEnum
    Reading Param with name MeshLab::Decoration::ShowAlpha : RichBool
    Reading Param with name MeshLab::Decoration::ShowContourAlpha : RichDynamicFloat
    Reading Param with name MeshLab::Decoration::ShowContourColorMap : RichEnum
    Reading Param with name MeshLab::Decoration::ShowContourFreq : RichFloat
    Reading Param with name MeshLab::Decoration::ShowContourRamp : RichBool
    Reading Param with name MeshLab::Decoration::ShowContourWidth : RichDynamicFloat
    Reading Param with name MeshLab::Decoration::ShowMeshCameras : RichBool
    Reading Param with name MeshLab::Decoration::ShowPerFaceCurvature : RichBool
    Reading Param with name MeshLab::Decoration::ShowPerVertexCurvature : RichBool
    Reading Param with name MeshLab::Decoration::ShowRasterCameras : RichBool
    Reading Param with name MeshLab::Decoration::ShowShadow : RichBool
    Reading Param with name MeshLab::Decoration::TextureFaceColor : RichBool
    Reading Param with name MeshLab::Decoration::TextureStyle : RichBool
    Reading Param with name MeshLab::Decoration::UseFixedHistParam : RichBool
    Reading Param with name MeshLab::GUI::perMeshToolBar : RichBool
    Reading Param with name MeshLab::Plugins::sketchFabKeyCode : RichString
    Reading Param with name MeshLab::System::maxGPUMemDedicatedToGeometry : RichInt
    Reading Param with name MeshLab::System::maxTextureMemory : RichInt
    Reading Param with name MeshLab::System::minPolygonNumberPerSmoothRendering : RichInt
    Reading Param with name MeshLab::System::perBatchPrimitives : RichInt
Shader directory found '/usr/share/meshlab/shaders', and it contains 19 gdp files
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted (core dumped)
`

**Comment by cignoni** [comment]
the first two stl files are malformed (binary stl where the number of faces is huge)
<img width="1041" alt="screen shot 2018-02-22 at 18 22 52 pm" src="https://user-images.githubusercontent.com/8055819/36553861-bc674ee8-17fd-11e8-8d4d-a528fc4864e4.png">
Patching the stl importer to be more robust to malformed files...

**Comment by luntik2012** [comment]
you now that malformed files and huge amount of faces is not a reason for software crash. there must be warning/error message at least. faces count is not huge by the way

**Comment by cignoni** [comment]
If you had fully read my message you could have noted:

> Patching the stl importer to be more robust to malformed files...

**Comment by luntik2012** [comment]
yes, I have read it. big thanks for that, sorry for no meantion. hope you will success with that)

**Comment by cignoni** [comment]
Corrected :) 
thanks for submitting the files (btw where did you get these STL's? who was the creator?)

**Comment by luntik2012** [comment]
@cignoni I've created this while coding triangulation algorythm, so they are testing and not really adequate. Also I've scaned it)
