### ISSUE TITLE
Ridiculously slow on windows 10 and messes with default command prompt 

### ISSUE THREAD

**Issue by abhijitgujar86** [cnr-isti-vclab/meshlab#283]
![issue](https://user-images.githubusercontent.com/8208868/36634535-cda53538-19cb-11e8-8c29-d0017db14e18.png)

**Comment by mcallieri** [comment]
Yes, it is a known issue. A mistake in the installer renamed the link.
In any case, it is just the name of the link, if you launch it, it is the standard CMD.exe environment.

Regarding the slowness, it is the first time we hear this, can you be more precise? We are using it on Windows 10, and have no problems with it.
