### ISSUE TITLE
Broken directory architecture

### ISSUE THREAD

**Issue by lasellem** [cnr-isti-vclab/meshlab#285]
Dear all,

I was trying to compile meshlab with g++ on debian stretch, with the compilation instructions in the src/ folder. When I used meshlab_mini.pro, the compilation went smoothly, but when I used the meshlab_full.pro, make was looking for a src/external/lib/linux-g++-64 folder, which indeed didn't exist. All I could see were a linux/ and a linux-g++/ folders, so I copied out everything that was in linux-g++/ into linux/, and made linux-g++/ and linux-g++-64/ be symlinks to linux/

I guess this would be pretty easy to fix properly.

Best regards,
Lev-Arcady Sellem

P.S.: perhaps you should add a note in the README.md file about installing Qt's script and xmlpatterns libraries, which are missing in a standard Qt setup. The error message is pretty straightforward to understand, but this would still be appreciated.

**Comment by texnokrates** [comment]
Same problem on Ubuntu Xenial, worked around by symlinks.
BTW, the instructions in README.md seem to be for zsh without explicitly mentioning this.
(The lines for setting the build flags apparently do not work with bash.)

**Comment by infinitesnow** [comment]
Can confirm, same problem on Debian Bullseye

**Comment by alemuntoni** [comment]
I'll close this issue since it should be fixed with the last PR.
Feel free to open another issue if the problem persists.
