### ISSUE TITLE
Problem with the new Meshlab Version

### ISSUE THREAD

**Issue by claudiofeldman** [cnr-isti-vclab/meshlab#286]
hello
i dont know why but the new version is not in order in my laptop,
before that, i have a good use from Meshlab (old versions).
I dont know why ?
i have Windows 10, ....64 bits,but i cant open files and work normally,
that run so slow slow, whitout chances.

I tryed to re-install the last version, but the same problem stay here.
Can me help me,pls ?
Thanks
..............................

**Comment by mcallieri** [comment]
MeshLab now uses a lot the videocard. Many laptops have two videocards, one accelerated, and another integrated: be sure to start the software using the accelerated videocard. In case, update the drivers.
We have used MeshLab on many, many, many PC with Windows 10, without any issue.
