### ISSUE TITLE
Meshlab crashes while texturing+par..

### ISSUE THREAD

**Issue by HilfloserBenutzer** [cnr-isti-vclab/meshlab#287]
Hi,
I have installed the program on an Acer V3-772G ($GB, GT750M) Win10 latest version. 
I tried to mesh a model of my car with a little street scene in the Background. The cloud was generated with VisualSFM and imported to Meshlab.
The following workflow was adapted fron several YouTube tutorials. When I do this step by step I have no problmems till the Step: Filter- Texture - Parameterization + texturing from regiostrated rasters.
The Filter starts working and after a few seconds the Programm crashes, with a shutdown. I tried this severel times with different Parameters but in the end the program crashes ervery time.
I'm hopefull that this is an known problem with an easy resolving.

Greatings

**Comment by mcallieri** [comment]
I have no idea. I use this filter often. 
Can you give me some detail on the dataset? e.g. number of images, image resolution, model size, etc etc.

**Comment by ConfidantCommunications** [comment]
I had a similar experience, crashing when using Parameterization > Trivial Per triangle. The crash went away if I first did Remove Zero Area Faces.
