### ISSUE TITLE
face count

### ISSUE THREAD

**Issue by timothytai** [cnr-isti-vclab/meshlab#288]
Hi all,

When I imported a mesh consisting of 100 vertices and 75 quad faces, meshlab somehow recognizes it to have 146 faces. What is the problem here?

Please find [here](https://www.dropbox.com/s/2w37ntqsnklca11/TestExport_quad1.obj?dl=0) the OBJ file and [here](https://www.dropbox.com/s/yjp7irfpwmjsb8b/meshlab_facecount.png?dl=0) the screenshot.

Thank you!

**Comment by mcallieri** [comment]
MeshLab only works with triangles. Quads are converted in triangles on loading, so 146 is the number of triangles.

BEWARE: due to a bug, when exporting the obj, uncheck the "polygonal" checkbox on the bottom-left of the exporting dialog.
