### ISSUE TITLE
meshlabserver save option

### ISSUE THREAD

**Issue by timothytai** [cnr-isti-vclab/meshlab#289]
Hi,

I am wondering if it might be possible to save meshes with the polygonal (default) option on using MeshLabServer. I currently can not find a work around and any filter that involves quad meshes are practically useless because the output will still be saved as triangular meshes.

Thank you very much,

Tim

**Comment by mcallieri** [comment]
Hi.
At the moment, support for non-triangle polygons is veeeery limited ad buggy.
There is no option for exporting quad geometries in server, currently, because most filters will destroy quadrangulation. I have no idea when it will be supported, sorry.
