### ISSUE TITLE
.ply loading exception

### ISSUE THREAD

**Issue by Tomiinek** [cnr-isti-vclab/meshlab#290]
Hello, I found out that loading .ply file throws exception in an unexpected scenario.

Importing file with following header workds fine:
```
ply
format ascii 1.0
element vertex 204458
property float x
property float y
property float z
property float nx
property float ny
property float nz
element face 408498
property list uchar uint vertex_indices
property list uchar float texcoord
end_header
```

But after this tiny change MeshLab throws an exception while importing:

```
ply
format ascii 1.0
element vertex 204458
property float x
property float y
property float z
property float nx
property float ny
property float nz
element face 408498
property list ushort uint vertex_indices
property list uchar float texcoord
end_header
```

Using MeshLab v2016.12

**Comment by mcallieri** [comment]
yes, not all possible combination of types are parsed by our loader. 
Just to know it, which tool is using this strange combination?

**Comment by mcallieri** [comment]
sorry, wrong button :)

anyway, we will look into it, but I cannot give you an estimate for this fix.
Do you have a test object?

**Comment by Tomiinek** [comment]
Huh, ushort does not seem so strange :) There is no need to fix it, I was just validating my own .ply implementation and was not sure whose bug or format misunderstanding it is. Anyway, I will post a simple object later this day.

**Comment by mcallieri** [comment]
ok, on some tools, it might be useful to have polygons with more than 255 vertices, but MeshLab normally works with triangles, so it is uncommon, at least for us. :)

**Comment by cignoni** [comment]
Committed an updated version of the ply loader in the vcglib.
