### ISSUE TITLE
Suggestion: Option to adjust camera view angle

### ISSUE THREAD

**Issue by ChristopherKing42** [cnr-isti-vclab/meshlab#291]
An option to adjust the [angle of view](https://en.wikipedia.org/wiki/Angle_of_view) on the camera would be nice. My use case probably an 120 degree view angle, for example.

**Comment by mcallieri** [comment]
I am not sure to understand.
In MeshLab, using shift-wheel, you may change the FOV of the realtime rendering. The current FOV is written on the left of the bottom info-panel. It is displayed as HALF-fov. So, when you read 60 it means 60° each direction, thus 120°
