### ISSUE TITLE
FREEZE loading large X Y Z 3d scanner Point Cloud

### ISSUE THREAD

**Issue by c3kkos** [cnr-isti-vclab/meshlab#294]
Hi there,

i'm experiencing a Meshlab FREEZE loading a very large 3d scanner generated point cloud.

The file (raw data ASCII x y z coords format) is 750mb and contains 20,673,625 points.

I can tell you this because Meshlab succesfully loads and render a still frame of the mesh, but suddenly just after the loading process is done, the program hangs/freezes for an undefined amount of time

![clipboard01](https://user-images.githubusercontent.com/30070329/37348341-25eb9736-26d4-11e8-8153-0341da9763ef.jpg)

Davide from Pisa

**Comment by c3kkos** [comment]
PC SPECS are:

 i7-4770 CPU 8,0 GB RAM, NVIDIA Quadro K600, Windows 7 Professional 64-bit SP1

As far as i know, i have not any other issues with this machine.

**Comment by c3kkos** [comment]
Ok , a quick and dirty solution i managed to find, call it a workaround.

I coded some java to help me strip out some unnecessary data from the "big file".

I started with a X Y Z R G B file, one big chunk.

with Java i stripped off the R G B data and splitted into 1M points files.

It worked flawlessy. Hope this will help someone facing this issue.

Thank you

![clipboard01](https://user-images.githubusercontent.com/30070329/37352361-59542418-26dd-11e8-9c9e-d6b597952b6f.jpg)

(this is a work-in-progress screenshot)

**Comment by mcallieri** [comment]
hi there...
1- QUADRO card are really good for CAD, but their driver has a huge problem with generic OpenGL stuff. When a buffer is created, or when some parameters of the rendering are changed, the driver STOPS for few milliseconds, to flush the rendering buffers. We never found a real solution... :(
2- the rendering is switching to IMMEDIATE MODE, but you still have plenty of GU memory. By defualt, MeshLab uses only a small amout of GPU memory (for compatibility with lower specs videocards), but you can change the limits, and have all the data in GPU. Follow this tutorial https://www.youtube.com/watch?v=ZbyzQHo666E&t=204s
3- we are located in Pisa, too. Come to our offices, if you need help :)
