### ISSUE TITLE
Assertion `0' failed with many menu items

### ISSUE THREAD

**Issue by ChristophHaag** [cnr-isti-vclab/meshlab#296]
For example in an empty project Filters->Create New Mesh Layer->Annulus
```
unable to find the id corresponding to action  '&Annulus'
meshlab: ../../common/interfaces.h:372: virtual MeshCommonInterface::FilterIDType MeshFilterInterface::ID(QAction*) const: Assertion `0' failed.
```
Also everything in the Render menu, when a mesh is loaded.

My guess is it breaks on new Qt versions. I'm using Archlinux with currently Qt 5.10.1.

**Comment by mcallieri** [comment]
It might be true, when using 5.10, we had but lots of "sizing" issue for menus. However, we had no assertion failures.
At the moment we are using QT 5.9, also because it is a Long Support version.
If you are able to pinpoint the issue, we might correct it, but for the moment, we are sticking to 5.9

**Comment by martin-frbg** [comment]
I am getting these with the current `master` branch on openSuSE 15, which has Qt 5.9.4 ...
Any hints for tracking this down ?
