### ISSUE TITLE
Opening problem

### ISSUE THREAD

**Issue by Gemmarii** [cnr-isti-vclab/meshlab#297]
I just downloaded the version for Windows 64 and it won't open, whether I double click it or right click and select open.  It just flashes at me for a split second and then closes itself and doesn't even give me an error message or say something is wrong.  Just every time I try to open it, flash and close flash and close.  I have Windows 64, but should I have not downloaded it, is that one no longer a working option and you forgot to remove it?

**Comment by mcallieri** [comment]
I assume you downloaded MeshLab 2016.12 This is the only current version for Windows (32 bit is no longer available).
The problem may be the videocard, as the new version uses intensively the GPU.
- if you have a notebook, most of times they have two videocards: ine integrated and one accelerated. Be sure to start the software with the accelerated one (right-click menu, there should be an option to specify the videocard and set the default card to use)
- update videocard drivers
- if your videocard is too old, or not powerful enough (old intel integrated chipsets), it might be possible that you are unable to run MeshLab

**Comment by Gemmarii** [comment]
Okay thanks
