### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by PABLOGONZALEZR** [cnr-isti-vclab/meshlab#30]
Im trying to align 2 stl files based on points, when the new window (when i click on point based glueing) opens up, the program puts the two structures overlaping each other making it very hard to align by points.

When i saw the tutorial the two structures appears one next to each other. i've tried this in 3 mac's and they all show the same problem. Maybe its because the files?

like this
![captura de pantalla 2016-12-29 a las 18 52 33](https://cloud.githubusercontent.com/assets/24832800/21555593/2b436c3a-cdf8-11e6-8d03-9c09aac01ebf.png)

**Comment by PABLOGONZALEZR** [comment]
like this
![captura de pantalla 2016-12-29 a las 18 52 33](https://cloud.githubusercontent.com/assets/24832800/21555574/019d8e60-cdf8-11e6-9e5d-6f56cd2b0c10.png)

**Comment by cignoni** [comment]
confirmed. I was able to replicate this bug. We are on it...

**Comment by cignoni** [comment]
Luckily enough it was an easy one. :) see commit https://github.com/cnr-isti-vclab/meshlab/commit/a68d41beba0e74b11dd1fba2e5569e4fe60bcfa3
Thanks again for spotting out!
We should plan a new release quite soon...

**Comment by PABLOGONZALEZR** [comment]
Thanks!

How do i proceed to put those files in the meshlab folder?

2016-12-29 21:40 GMT-03:00 Paolo Cignoni <notifications@github.com>:

**Comment by cignoni** [comment]
Probably you have to wait for the next release (that, I promise, will be not very far :) )
Alternatively you could re-build meshlab from the sources...

**Comment by bverheij** [comment]
Hi all, just ran into this bug too.. @cignoni are you planning to release an updated version in the near future? I'm now in the process of diving into installing Xcode, QT, etc on my Mac to compile, but this will be a bit of a bumpy road.

**Comment by fowlkes** [comment]
Is this the most recent release that doesn't have this bug?

  https://sourceforge.net/projects/meshlab/files/meshlab/MeshLab%20v1.3.3/

I'm teaching a class of 70 students where I suggested they use 
meshlab for alignment and now they are all stuck in this dead 
end :-)

**Comment by richardmonette** [comment]
@fowlkes Perhaps a bit late reply, but I just ran into this same issue. I found https://github.com/cnr-isti-vclab/meshlab/releases/tag/c6e9b0f which seems to have the fix, and I have been making some progress on alignment (with OSX) using that build. Hope it might help, cheers.
