### ISSUE TITLE
libfilter_csg.so: undefined symbol: __gmpz_init_set_si

### ISSUE THREAD

**Issue by lizarge** [cnr-isti-vclab/meshlab#304]
This problem reproduce in latest self compiled build, and in builds downloaded from resp.

**Comment by martin-frbg** [comment]
This symbol is from libgmp, apparently the Makefile generated for src/meshlabplugins/filter_csg is missing a `-lgmp' on its LIBS line. (Or the filter_csg.pro should require to link libmpir.a on linux as well,
which it currently seems to be doing for osx and windows only)
