### ISSUE TITLE
Different results from menu and "Apply Filter Script:" "Simplification: Quadric Edge Collapse Decimation with Textures"

### ISSUE THREAD

**Issue by RPSpicer** [cnr-isti-vclab/meshlab#305]
I am running 2016.12 on Windows 10 x64.  Repro steps:
1. In a new project, import a textured OBJ mesh.
2. Apply the "Simplification: Quadric Edge Collapse Decimation (with texture)" filter.
3. Observe that the mesh is appropriately decimated.
![01_orig_with_settings](https://user-images.githubusercontent.com/16723602/38571701-1c9ecac6-3ca6-11e8-80aa-851c10c0ca43.png)
4. Reload the same input mesh.
5. Use "Show Current Filter Script" -> "Apply" to apply the same filter, with the same settings, to the same mesh.

![02_filter_settings](https://user-images.githubusercontent.com/16723602/38571716-255946c8-3ca6-11e8-8b71-64cdfc5da5c1.png)

6. Observe that the mesh is missing piles of triangles.

![03_after_apply_filter](https://user-images.githubusercontent.com/16723602/38571721-2c2d5430-3ca6-11e8-8d74-6772c8b6928a.png)

**Comment by mcallieri** [comment]
Hi,
  it is just a problem of visualization, if you save the model, it is fine.
I have corrected the bug in the code, now should work properly.
While waiting for the release, you may try the nightly build
The current WIN64 build can ba found here
https://ci.appveyor.com/project/cignoni/meshlab/build/artifacts
It is not an installer, just a zipped folder with a "portable" executable. We are starting testing, now, while fixing few more issues. We have used on some machines, here, and seems working. I have no idea, however if it has ALL the possible dll and Runtime that may be needed.
If there is an ongoing build, the site will write "The build job does not contain any artifacts.". In that case, you may wait for the build to end or just click "HISTORY", select the last succesful build, and then "ARTIFACTS"
