### ISSUE TITLE
what does the Edge Threshhold mean in Subdivision Surface:LS3 LOOP?

### ISSUE THREAD

**Issue by DamonsJ** [cnr-isti-vclab/meshlab#306]
what does the Edge Threshhold mean in Subdivision Surface:LS3 LOOP?
It is different when model changed

**Comment by mcallieri** [comment]
it means "when the edge is smaller than this value, do not subdivide further". When the filter opens up, a starting value is calculated, trying to adapt it to the size of the model (i.e. it is set at a certaing fraction of the model bounding box diagonal), for this reason, the default absolute value seems to change from model to model.
