### ISSUE TITLE
Can not be compiled No suche file for Eigen/core

### ISSUE THREAD

**Issue by waschbaer00** [cnr-isti-vclab/meshlab#308]
Hi there,

I clone the meshlab and vcglib in the same level and compile external, then try to compile the meshlab_full.pro. I use qt5.7.

The message from make:

```
In file included from ../../vcglib/vcg/space/box3.h:27:0,
                 from ../../vcglib/vcg/complex/used_types.h:27,
                 from ../../vcglib/vcg/complex/complex.h:46,
                 from ../src/common/ml_mesh_type.h:4,
                 from ../src/common/meshmodel.h:32,
                 from ../src/common/meshmodel.cpp:28:
../../vcglib/vcg/math/matrix44.h:33:22: fatal error: Eigen/Core: No such file or directory
compilation terminated.
```
However Eigen/core is inside vcglib folder.

Thank you for your help.

**Comment by cignoni** [comment]
look at the travis and appveyor script to get hints on what you are missing in setting up the compiling environment (most of the times you are using the wrong branch of the vcglib).

**Comment by jingpengw** [comment]
changing the `Eigen/XXX` to `eigenlib/Eigen/XXX` fixed this issue.
