### ISSUE TITLE
Error: LNK1104: cannot open file 'jhead.lib'

### ISSUE THREAD

**Issue by huenguyen594** [cnr-isti-vclab/meshlab#309]
Hello,

I am trying to build MeshLab from source on Windows with Qt for a university project using Qt 5.9.0 (tested with msvc2013-64 and msvc2017-64), latest meshlab (master branch) and vcglib (devel branch)
I've followed the instruction and managed to successfully compile external.pro (with 114+ issues/ warnings) but failed to build meshlab_mini.pro and meshlab_full.pro due to 1 error: **LNK1104: cannot open file 'jhead.lib'**

> LINK : fatal error LNK1104: cannot open file 'jhead.lib'
> jom: E:\Development\meshlab-test\meshlab\build-meshlab_mini-Desktop_Qt_5_9_0_MSVC2017_64bit-Debug\meshlab\Makefile.Debug [..\distrib\meshlab.exe] Error 1104
> jom: E:\Development\meshlab-test\meshlab\build-meshlab_mini-Desktop_Qt_5_9_0_MSVC2017_64bit-Debug\meshlab\Makefile [debug] Error 2
> jom: E:\Development\meshlab-test\meshlab\build-meshlab_mini-Desktop_Qt_5_9_0_MSVC2017_64bit-Debug\Makefile [sub-meshlab-make_first-ordered] Error 2
> 21:35:59: The process "C:\Qt\Qt5.9.0\Tools\QtCreator\bin\jom.exe" exited with code 2.
> Error while building/deploying project meshlab_mini (kit: Desktop Qt 5.9.0 MSVC2017 64bit)
> The kit Desktop Qt 5.9.0 MSVC2017 64bit has configuration issues which might be the root cause for this problem.
> When executing step "Make"

Can someone please help me to fix this?

**Comment by cignoni** [comment]
Have you tried to build the external.pro project? it seems that you need one of the libraries build by it. 
Actually jhead is the only library needed by the meshlabmini.pro and it would be nice to find the time to remove even this small dependency by using a leaner lib... Hope to find time for this....

**Comment by huenguyen594** [comment]
Thank you for answering my question!
Yes, I have built the external.pro project (with no error but 114+ warning)

After all I gave up on building with QtCreator and tried to use Visual Studio 2015 native tools command prompt. I could finally get meshlab_mini compiled and also meshlab_full (with 60/67 successfully built plugins)
