### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by ricrav** [cnr-isti-vclab/meshlab#31]
Hallo,
I've tryed to perform installation using MeshLab2016.12.exe.
By clicking on the desktop icon, it doesn't happen anything...
Is this a common error?
How can I fix it?
Thanks

**Comment by granzuglia** [comment]
Can you tell us, at least, which OS are you using? is it a 32 or 64 bit? otherwise it's quite impossible to understand the possible causes of your problem

**Comment by ricrav** [comment]
Sure I can, thank you for reply.

Windows 7 Home Premium 64 bit
Windows Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
RAM 8,00 GB
VS C++ 2015 x64 14.0.2415 seems to be installed correctly
At this moment I'm downloading some (imporant) Windows updates, i will notice if this will resolve.

I will be nice to give you any other useful information

**Comment by ricrav** [comment]
I have installed any available update for W7, the problem remain the same.
Prevoius version of Meshlab seem to run fine.

**Comment by granzuglia** [comment]
Can you try to install the package contained at this link https://support.microsoft.com/en-us/kb/2999226 being careful to select the version related with your specific version of the Windows OS? It looks like it could be an issue related with a not updated version of the file ucrtbase.dll. It's difficult for us to replicate the problem so we can just try to guess which could be the solution. Sorry for the inconvenience but probably (and i highlight "probably") it's independent from MeshLab itself.

**Comment by ricrav** [comment]
Windows is in Italian. I will try to install the package above and I'll notice about.
Thanks

**Comment by ricrav** [comment]
I have performed further Windows update (recently I have made a clean installation of OS), including the packge at the mentioned link, and Mashlab 2016 run!.
Thank you for help.

**Comment by cignoni** [comment]
Thanks for reporting that now works!
