### ISSUE TITLE
How to estimate rough complexity of 3D models?

### ISSUE THREAD

**Issue by Ben-Mack** [cnr-isti-vclab/meshlab#312]
I'm having a project need rough estimate for the complexity of 3D models.

By the complexity means, for example, 3D model of furniture in modern style has low complexity, but 3D model of royal style furniture has high complexity.

Please guide me which way, or the name of the algorithm for this purpose. (It the best if we can process inside meshlab, but any other source is fine too)

Thanks!

**Comment by mcallieri** [comment]
This is not a precise and usable definition....
It also depends a lot on the nature of the 3d model (hand-modeled or scanned)

I'm afraid we do not have a filter taht gives this kind of information
