### ISSUE TITLE
How would I go about extracting the intermediate SDF from the Poisson filter?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [cnr-isti-vclab/meshlab#313]
I want to go from point-clouds straight to voxels, I was wondering if there was some functionality to save the octree before the meshing. 

OR

Where in the code can I grab the octree and get the SDF at each node ?

**Comment by mcallieri** [comment]
Hi there...
I'm sorry, but I have no way to directly export this intermediate data
The code for the Screened Poisson comes directly from the Michael Kazhdan repository, he kindly agreed to integrate it in MeshLab.
http://www.cs.jhu.edu/~misha/Code/PoissonRecon/
https://github.com/mkazhdan/PoissonRecon
currently, we have in MeshLab version, 9.01
It might be easier to get the basic executable code, and add your functions there.
