### ISSUE TITLE
About source code of meshlab questions

### ISSUE THREAD

**Issue by luckygoodlily** [cnr-isti-vclab/meshlab#314]
To whom it may concern. I am Lily, I’m sorry to bother you.

Recently,I want to compile open source code of meshlab in Mac, but I encountered some compilation problems.First, I use command "qmake -recursive meshlab_mini.pro”, then use “make”. There is error in file(src/glarea.h”) like annex, I try my best to resolve. But I can’t.

Please advise if necessary. I would appreciate your immediate attention to this matter.
<img width="570" alt="2018-05-07 12 11 44" src="https://user-images.githubusercontent.com/8471340/39675930-45551b52-5194-11e8-9385-b0f1279605d2.png">

**Comment by cignoni** [comment]
Currently MeshLab is correctly compiling on OSx, windows and linux. 
Please try to replicate your compiling environment with the one of the automated building systems. 
They are as described in:

https://github.com/cnr-isti-vclab/meshlab/blob/master/.travis.yml     (osx and linux)
https://github.com/cnr-isti-vclab/meshlab/blob/master/appveyor.yml  (visual studio)

**Comment by luckygoodlily** [comment]
Sorry to bother you again.
I'm try use the URL(https://github.com/cnr-isti-vclab/meshlab/blob/master/.travis.ym osx) step by step, but I still encounter some error. I use command "qmake meshlab_mini.pro” "qmake meshlab_full.pro", then use “make -j4”. There are some error like annex.

Thank you for your assistance. I would appreciate very much.
<img width="569" alt="2018-05-07 10 49 09" src="https://user-images.githubusercontent.com/8471340/39709568-ca70d3fe-524c-11e8-901d-723daa9bfdf0.png">
<img width="569" alt="2018-05-07 10 50 11" src="https://user-images.githubusercontent.com/8471340/39709577-d3abe378-524c-11e8-924b-242b78f6e792.png">
