### ISSUE TITLE
Add way to select points based on neighbour count / density

### ISSUE THREAD

**Issue by Harvie** [cnr-isti-vclab/meshlab#315]
I have pointset with some outliers like this:

![image](https://user-images.githubusercontent.com/276504/39710336-d72e1f0a-521c-11e8-8b2f-e3edecac56b1.png)

I think it would be usefull to add some tool that would allow me to select these points based on how dense they are, so i can delete them. Eg. based on number of neighbours in some radius around the point. Or overall density.

**Comment by cignoni** [comment]
You can try (at your own risk :) ) the prerelease builds; 
we have added a 'select outlier' filter that probably works well for your needs....

you can found them here:
- dmg for osx: https://github.com/cnr-isti-vclab/meshlab/releases 
- portable version for win https://ci.appveyor.com/project/cignoni/meshlab/build/artifacts

**Comment by mcallieri** [comment]
Alternatively, you may calculate radius, and then do a conditional vertex selection specifying in the condition which is your radius threshold

**Comment by Harvie** [comment]
> Alternatively, you may calculate radius, and then do a conditional vertex selection specifying in the condition which is your radius threshold

How do i calculate vertex radius? What that even mean? Is radius of vertex the distance to the closest neighbour vertex?

That would mean that i can select low-density vertices like this?

`(rad > 0.01)`

**Comment by Harvie** [comment]
Aha! I got it working. I've done it like this:

filters->point set->estimate radius from density
filters->selection->conditional vertex selection->`(rad > 0.007)`
delete selected vertices

That way i get much cleaner output of screened poison surface reconstruction, since it removed most of the noise that was left after manual cleanup.

**Comment by mcallieri** [comment]
filters->point set->estimate radius from density
(when you do not know where exactly a filter is, just use the search feature)
radius is an average of the distance from the closest points
After you have computed it, using filters->selection->conditional vertex selection, you may use a selection like rad > 0.2 to select all vertices that, on average, are farther away from ther neighbours more than 0.2 units.

**Comment by Toypar** [comment]
> You can try (at your own risk :) ) the prerelease builds;
> we have added a 'select outlier' filter that probably works well for your needs....
> 
> you can found them here:
> 
> * dmg for osx: https://github.com/cnr-isti-vclab/meshlab/releases
> * portable version for win https://ci.appveyor.com/project/cignoni/meshlab/build/artifacts

Works like a charm!  I'm working on a point cloud that has 3/4 million points and have cranked it up to 16,384 neighbors so far. 30 minute calculation by my estimates but the model keeps getting better and better.  Started out at 1024 and have kept doubling the number iteratively to 16k.  Tonight I am going to run it at 32k and find the sweet spot.   Thanks for the link.  

![image](https://user-images.githubusercontent.com/36872847/49619025-6fb40900-f980-11e8-8eff-6c4d16f13810.png)

![image](https://user-images.githubusercontent.com/36872847/49618899-e0a6f100-f97f-11e8-8dcf-d02966b6866a.png)
