### ISSUE TITLE
Meshlab silently ignores full disk when saving files.

### ISSUE THREAD

**Issue by Harvie** [cnr-isti-vclab/meshlab#316]
I've been saving file when my disk went full. Meshlab only saved begining of file and written this to console:

`LOG: 0 Saved Mesh /home/harvie/Desktop/3d_scan/padlo/scn/pset-L2-hrv.ply in 23057 msec`

Also in the GUI everything looked the same as if the file was saved succesfully. But the partial file obviously was not possible to be open. Took me a while until i realized why the file got corrupted.

**Comment by mcallieri** [comment]
yes... our fault. 

I added check and error display on some of the most used exporters.
I will test the other format as soon as I can.
