### ISSUE TITLE
source code of meshlab questions by Mac

### ISSUE THREAD

**Issue by luckygoodlily** [cnr-isti-vclab/meshlab#317]
I'm try use the URL(https://github.com/cnr-isti-vclab/meshlab/blob/master/.travis.ym osx) step by step, but I still encounter some error. After I use command "qmake meshlab_mini.pro” "qmake meshlab_full.pro", then use “make -j4”. There are some error in "meshlabdocumentxml.cpp" like annex.

Thank you for your assistance. I would appreciate very much.
<img width="569" alt="2018-05-07 10 49 09" src="https://user-images.githubusercontent.com/8471340/39709568-ca70d3fe-524c-11e8-901d-723daa9bfdf0.png">
<img width="569" alt="2018-05-07 10 50 11" src="https://user-images.githubusercontent.com/8471340/39709577-d3abe378-524c-11e8-924b-242b78f6e792.png">

**Comment by alemuntoni** [comment]
I'll close this issue since it should be fixed with the last PR.
Feel free to open another issue if the problem persists.
