### ISSUE TITLE
Hardware requirements on Windows 10

### ISSUE THREAD

**Issue by russelaw** [cnr-isti-vclab/meshlab#318]
I have a researcher that needs to build a computer for meshlab. I have never used the software so I do not know the hardware requirements for Windows?

**Comment by mcallieri** [comment]
Nothing special. The only thing is that MeshLab is heavily using the GPU, so you need to have an accelarated graphics card. MeshLab works better with NVidia cards, but ATI cards are also supported.
The more GPU memory, the large 3D models you can render with good performances. see this video for more info on configuring video RAM https://www.youtube.com/watch?v=ZbyzQHo666E&t=204s
