### ISSUE TITLE
[Select Self Intersecting Faces] no additional memory available!!! memory required: 8768256

### ISSUE THREAD

**Issue by vacingforo** [cnr-isti-vclab/meshlab#320]
I have the following scritp:

```
<!DOCTYPE FilterScript>
<FilterScript>
 <filter name="Select Self Intersecting Faces"/>
</FilterScript>
```

and I get the following result:

```
C:\Users\me\Downloads\skull_art_1.5.3>"C:\Program Files\VCG\MeshLab\meshlabserver.exe" -i model_0.stl -o model_0_fixed.stl  -m vc fq wt -s myscript.mlx
Loading Plugins:
Current Plugins Dir is: C:/Program Files/VCG/MeshLab/plugins
Total 241 filtering actions
Total 12 io plugins
Opening a file with extention stl
Mesh C:/Users/me/Downloads/skull_art_1.5.3/model_0.stl loaded has 313152 vn 104384 fn
output mesh  C:/Users/me/Downloads/skull_art_1.5.3/model_0_fixed.stl
vertex color, face quality, wedge tex coords, Apply FilterScript: 'C:/Users/me/Downloads/skull_art_1.5.3/myscript.mlx'
FilterScript
Reading filter with name Select Self Intersecting Faces
Starting Script of 1 actionsfilter: Select Self Intersecting Faces
no additional memory available!!! memory required: 8768256
Mesh C:/Users/me/Downloads/skull_art_1.5.3/model_0.stl saved as C:/Users/me/Downloads/skull_art_1.5.3/model_0_fixed.stl (313152 vn 104384 fn)
```
I would like to get number of intersection faces.

**Comment by HenrryBryant** [comment]
@vacingforo  download the latest release version and the problem will be solved

**Comment by vacingforo** [comment]
@HenrryBryant  thanks for your answer but I have the lastest:

MeshLab 2016 23/12/2016
[http://github.com/cnr-isti-vclab/meshlab/releases/download/v2016.12/MeshLab2016.12.exe](http://github.com/cnr-isti-vclab/meshlab/releases/download/v2016.12/MeshLab2016.12.exe)

**Comment by HenrryBryant** [comment]
@vacingforo  not this one, see here: https://github.com/cnr-isti-vclab/meshlab/releases.  I download the latest one which is 2018.4.   and now the same problem as you posted have been solved.

**Comment by vacingforo** [comment]
Hi Shengyu Huang Do I need to compile the source or is there a binary
executable for windows of this version?
Thanks,
Sergio

**Comment by HenrryBryant** [comment]
@vacingforo  I use MacOS so I just download the dmg file and use it. I didn't see the binary executable for windows so I think you have to compile the source. I tried to compile before but I failed, even the mini-meshlab, but you can give it a try. Good luck 
Henry

**Comment by mcallieri** [comment]
portable version for windows: https://ci.appveyor.com/pro…/cignoni/meshlab/build/artifacts
It's still a work in progress, but most of the bugs have been fixed, and they are usable.
Let us know issues and problems.
For Window version, there is no installer, yet, but we have a portable folder, just unpack it on your PC and double-click on MeshLab icon. As this version is continuosly updated, if you see there is a compilation ongoing (or failed) just go to "history" and look for the artifact in last successful build.

**Comment by vacingforo** [comment]
I know that meshlab depends of vcblib so I compiled (
https://github.com/cnr-isti-vclab/vcglib/releases/tag/v1.0.1 ) in debug and
release without any errors with the following environment:

Windows 10 32 bit MSVC 2015 V14 compiler

When I execute my program

C:\Users\me\Documents\projectCGALII\build\Debug>cgal_vtk_test.exe pig.stl

and i get the following error:

Assertion failed: j>=0 && jVN(), file
C:\vcglib-1.0.1\vcg/simplex/face/component_polygon.h,
line 70

See the attached files please(ignore cgal strings). What's wrong?

https://drive.google.com/open?id=1fEqZft_OhHxTsAvio58_TWOtvrYbGCOA

-----------------------------------------------------------------
cgal_vtk_test.cpp ----------------------------------------------------------

int  nonManifoldEdge(const char* filename){
    int loadmask;
    vcg::tri::io::ImporterSTL<PMesh>::OpenBinary(pm, filename, loadmask);
    //vcg::tri::UpdateTopology<PMesh>::FaceFace(pm);
    //vcg::tri::Clean<PMesh>::RemoveNonManifoldFace(pm);
    //vcg::tri::UpdateTopology<PMesh>::FaceFace(pm);
    //assert(vcg::tri::Clean<PMesh>::CountNonManifoldEdgeFF(pm));
    return vcg::tri::Clean<PMesh>::CountNonManifoldEdgeFF(pm);}
int main(int argc, char* argv[]){
    std::cout << "Count non manifold Edge: " <<
nonManifoldEdge(argv[1]) << std::endl;
    return 0;}
