### ISSUE TITLE
Can't run meshlabserver filters on Linux

### ISSUE THREAD

**Issue by evansque** [cnr-isti-vclab/meshlab#322]
I have meshlab installed on debian 9.4 using sudo apt-get install meshlab

first when trying to dump on the filters list

`sudo xvfb-run -a -s "-screen 0 800x600x24" meshlabserver -d filters`

it fails with this log

```
Loading Plugins:
Current Plugins Dir is: /usr/lib/meshlab/plugins 
Error in XMLFile: filter_measure.xml - line: -1, column: -1 - 
Error in XMLFile: filter_mutualinfo.xml - line: -1, column: -1 - 
Total 227 filtering actions
Total 13 io plugins
called here! 
Segmentation fault (core dumped)
```

and when trying to run a filter

`sudo xvfb-run -a -s "-screen 0 800x600x24" meshlabserver -i original.obj -s /usr/lib/meshlab/plugins/filter_measure.xml
`

it fails and shows this log

```
script /usr/lib/meshlab/plugins/filter_measure.xml
Loading Plugins:
Current Plugins Dir is: /usr/lib/meshlab/plugins 
Error in XMLFile: filter_measure.xml - line: -1, column: -1 - 
Error in XMLFile: filter_mutualinfo.xml - line: -1, column: -1 - 
Total 227 filtering actions
Total 13 io plugins
Opening a file with extention obj
Mesh original.obj loaded has 22296 vn 7432 fn
Apply FilterScript: '/usr/lib/meshlab/plugins/filter_measure.xml'
Failure in parsing script /usr/lib/meshlab/plugins/filter_measure.xml
No root node with name FilterScript
Current rootname is MESHLAB_FILTER_INTERFACE
```
what am I doing wrong?

Here I asked on stackoverflow with a 500 points bounty https://stackoverflow.com/questions/49799634/cant-run-meshlabserver-filters-on-linux

**Comment by texnokrates** [comment]
Same problem here, using version 1.3.2+dfsg1-2build4.

**Comment by texnokrates** [comment]
> Same problem here, using version 1.3.2+dfsg1-2build4 on Ubuntu xenial.
... and apparently still broken (segfault) in the current github version.

**Comment by gerroon** [comment]
I have this issue on MeshlabServer 2018 Linux but not on Windows, though not the same versions probably

**Comment by themasterlink** [comment]
For future reference:

I had the same problem and in my case, setting the `LD_LIBRARY_PATH` to the current folder and the lib folder, where the `meshlabserver` is, solved the problem.

**Comment by nicolasugrinovic** [comment]
@themasterlink thank you for the post. Could you elaborate your solution? I have tried to set the `LD_LIBRARY_PATH` as you mention but no luck. Maybe I am doing something wrong.

**Comment by themasterlink** [comment]
@nicolasugrinovic 
Sorry, that was not a great answer from me, I set my LD path to: 

`LD_LIBRARY_PATH=PATH_TO_MESHLAB/meshlab/meshlab_portable_linux:PATH_TO_MESHLAB/meshlab/meshlab_portable_linux/lib/:$LD_LIBRARY_PATH`

Does this help you?

**Comment by alemuntoni** [comment]
`meshlabserver` does not take xml plugins files (`filter_measure.xml` is not a script for `meshlabserver`)!

`meshlabserver` takes as input `*.mlx` files.
More details [here](https://github.com/cnr-isti-vclab/meshlab/blob/master/src/meshlabserver/README.md).

If you are having trouble on running meshlabserver, please try the [AppImage Bundle](https://github.com/cnr-isti-vclab/meshlab/releases/download/Meshlab-2020.03/MeshLabServer2020.03-linux.AppImage).
