### ISSUE TITLE
[vcglib]Assertion failed: j>=0 && j<this->VN(), file C:\vcglib-1.0.1\vcg/simplex/face/component_polygon.h, line 70

### ISSUE THREAD

**Issue by vacingforo** [cnr-isti-vclab/meshlab#326]
I know meshlab depends of vcglib so I compiled it in debug and release without any errors with the following environment:

Windows 10 32 bit MSVC 2015 V14 compiler

When I execute my program

> C:\Users\me\Documents\projectCGALII\build\Debug>cgal_vtk_test.exe pig.stl

and i get the following error:

> Assertion failed: j>=0 && jVN(), file C:\vcglib-1.0.1\vcg/simplex/face/component_polygon.h, line 70

See the attached files please(ignore cgal strings). What's wrong? 

https://drive.google.com/open?id=1fEqZft_OhHxTsAvio58_TWOtvrYbGCOA

-----------------------------------------------------------------Code----------------------------------------------------------

```
int  nonManifoldEdge(const char* filename)
{
    int loadmask;
    vcg::tri::io::ImporterSTL<PMesh>::OpenBinary(pm, filename, loadmask);
    //vcg::tri::UpdateTopology<PMesh>::FaceFace(pm);
    //vcg::tri::Clean<PMesh>::RemoveNonManifoldFace(pm);
    //vcg::tri::UpdateTopology<PMesh>::FaceFace(pm);
    //assert(vcg::tri::Clean<PMesh>::CountNonManifoldEdgeFF(pm));
    return vcg::tri::Clean<PMesh>::CountNonManifoldEdgeFF(pm);
}

int main(int argc, char* argv[])
{
    std::cout << "Count non manifold Edge: " << nonManifoldEdge(argv[1]) << std::endl;
    return 0;
}
```

**Comment by mcallieri** [comment]
I believe thi should go on the VCGLIB GitHub page
