### ISSUE TITLE
Qt 5.11 compatibility.

### ISSUE THREAD

**Issue by bartoszek** [cnr-isti-vclab/meshlab#327]
Meshlab fails to build with newest qt 5.11.
[build.log.txt](https://github.com/cnr-isti-vclab/meshlab/files/2084450/build.log.txt)

**Comment by mcallieri** [comment]
We have not even tried 5.11, since 5.10 were already causing problems on some parts of the interface.
At the moment, in the automatic Travis and Appveyor build systems, we are sticking with 5.9, that is a Long Time Support version...

**Comment by bartoszek** [comment]
5.11 works fine, only few small tweaks required.
