### ISSUE TITLE
Skript: Ply to Obj

### ISSUE THREAD

**Issue by anjabruecke31** [cnr-isti-vclab/meshlab#330]
Hi!
I'm trying to write a batch file for a project that automatically converts meshes from ply to obj using meshlab. 

My meshlab-script contains the following two filters:
- Parametrization: Trivial Per-Triangle
- Transfer: Vertex Color to Texture

and I use the following code:
`meshlabserver -i meshname.ply -o meshname.obj -m vc -s meshlab_script.mlx`

A texture is created, but not linked correctly to the obj-file. If you export the mesh manually as obj everything works fine. I also tried to add the filter 'Set Texture' to my script, but this doesn't change the result. Thanks for any help I can get :)

**Comment by jmespadero** [comment]
Your command is:
```meshlabserver -i meshname.ply -o meshname.obj -m vc -s meshlab_sc```

where ```-m vc``` means "export with **c**olor-per-**v**ertex information".
You should be using ```-m wt``` to save with "wedge texture coords"

Also, please don't use github issues as a forum where you ask questions that are not useful for the developers of meshlab. Use [stackoverflow](https://stackoverflow.com/questions/tagged/meshlab) instead.
