### ISSUE TITLE
exporting to obj

### ISSUE THREAD

**Issue by borkog** [cnr-isti-vclab/meshlab#332]
(maybe a simple question)

have a 5milion polygon rock surface with 16k x 16k polypack texture (png)

i managed to reduce it 500.000 with quadric edge colapse with texture ... looks fine

when I try to export it just exports obj without new texture .... texture name box is empty and file is referenced to old 16x16k texture which does not fit 

any ideas?

**Comment by alemuntoni** [comment]
Please use [stackoverflow](https://stackoverflow.com/questions/tagged/meshlab) for questions unrelated with the development of meshlab.
