### ISSUE TITLE
App crashes reading Collada file

### ISSUE THREAD

**Issue by ghostman2013** [cnr-isti-vclab/meshlab#339]
I has own app that generates Collada files using Assimp library. Blender and my app imports generated files successfully but Meshlab crashes with error **Segmentation fault (core dumped)**.
Full output:

> ----- Starting the processing of /home/ghostman/Downloads/test/test2_out.dae ------
> File Contains 1 Scenes
> Scene 0 contains 1 instance_visual_scene 
> instance_visual_scene 0 refers Scene 
> instance_visual_scene Scene has 1 children
> Processing Visual Scene child 0 - of type 'node'
> Starting processing <node> with id Root
> getTrans form node with tag node
> Parsing matrix node; text value is '1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1'
> ** instance_geometry with url #meshId0 (intial mesh size 0 0 T = 0)
> **    instance_geometry has a material binding
> ++++ Found 1 instance_material binding
> ++++++ defaultMaterial -> #m0mat
> **** Loading a Geometry Mesh **** (initial mesh size 0 0)
> ****** LoadTriangularMesh (initial mesh size 684 0)
> ******    material id 'defaultMaterial' -> '#m0mat'
> ====== searching among library_effects the effect with id 'm0mat-fx' 
> ====== searching among library_images the effect with id 'm0mat-diffuse-image' 
> ====== the image 'm0mat-diffuse-image' has a 1 init_from nodes text 'input.jpg'
> Found use of Texture input.jpg, adding it to texutres
> ****** LoadTriangularMesh (final  mesh size 684 684 - 76 76)
> ****** LoadPolygonalListMesh (initial mesh size 684 76)
> ******    material id 'defaultMaterial' -> 'm0mat'
> ====== searching among library_effects the effect with id 'm0mat-fx' 
> ====== searching among library_images the effect with id 'm0mat-diffuse-image' 
> ====== the image 'm0mat-diffuse-image' has a 1 init_from nodes text 'input.jpg'
> *******                 Start Reading faces. Attributes Offsets: offtx 0 - offnm 0 - offcl 0
> Segmentation fault (core dumped)
> 

I am not sure if it's a bug in Meshlab or invalid file but in any case Meshlab crashes, it's unexpected behavior. After re-export of my file from Blender it works in Meshlab well again.
It's a sample of file that produces the bug: [test2_out.dae](https://drive.google.com/open?id=1UmOyxS677BAnM5sExJrlvh08PTFI5F8u).
**P.S.** Please, can u tell me what I should change in the file structure to Meshlab could read it normally?

**Comment by mcallieri** [comment]
Collada format is a mess, and some of its features (or combination of features) are not supported by MeshLab.
I have no idea what is, exactly, that causes the crash. The new beta does not crash, but is still unable to load the geometry.
