### ISSUE TITLE
Link failed when using shadow build

### ISSUE THREAD

**Issue by eboudrand** [cnr-isti-vclab/meshlab#34]
I cannot link meshlab and other meshlab_full subjects when I am using "shadow build" for compilation. I have the following error :
/usr/bin/ld : could not find -ljhead

In QtCreator, I checked "Shadow Build" box so that compilation is output in an intermediate directory (for example build-meshlab_full-Desktop_Qt_5_7_1_GCC_64bit-Debug).

I fixed the issue by modifying paths in pro file. The fix is available is this [commit](https://github.com/eboudrand/meshlab/commit/1e8f64b3457f3fddef1cd081d7d47e40f0d8c728). I am only compiling for Linux. I have not tested this for Windows plateform.

**Comment by alemuntoni** [comment]
I'll close this issue since it should be fixed with the last PR.
Feel free to open another issue if the problem persists.
