### ISSUE TITLE
hidden lines not available on windows download

### ISSUE THREAD

**Issue by nosarious** [cnr-isti-vclab/meshlab#340]
I have meshlab on an ubuntu machine which, of course, one compiles for.

I have meshlab on a windows 10 surface.

The ubuntu setup has an option for 'hidden lines' as a rendering mode, but the windows version does not.

Aside from compiling MeshLab on the windows device, is there a secret spot I can turn this on? The windows version tends to render the shaders better than the ubuntu version, so I would prefer to play with my models there...

GErry.

**Comment by mcallieri** [comment]
If you have the 2016.12 version, some rendering modes have changed.
pure "hidden lines" rendering is no longer available, but you may turn on WIREFRAME and SOLID (and disable shading on surface, for a flat appearance)
