### ISSUE TITLE
cannot export script of filter "Transform: Translate, Center, set Origin"

### ISSUE THREAD

**Issue by hironoriyh** [cnr-isti-vclab/meshlab#345]
I cannot export the filter "Transform: Translate, Center, set Origin".
I found the following discussion, but it seems the filter has changed. 
[link](https://sourceforge.net/p/meshlab/discussion/499533/thread/85034f6f/)

My current filter is  like this,
```
  <filter name="Transform: Translate, Center, set Origin">
  <Param description="X Axis" value="0" type="RichDynamicFloat" tooltip="Absolute translation amount along the X axis" min="-829.52" max="829.52" name="axisX"/>
  <Param description="Y Axis" value="0" type="RichDynamicFloat" tooltip="Absolute translation amount along the Y axis" min="-829.52" max="829.52" name="axisY"/>
  <Param description="Z Axis" value="0" type="RichDynamicFloat" tooltip="Absolute translation amount along the Z axis" min="-829.52" max="829.52" name="axisZ"/>
  <Param description="translate center of bbox to the origin" value="true" type="RichBool" tooltip="If selected, the object is scaled to a box whose sides are at most 1 unit lenght" name="centerFlag"/>
  <Param description="Freeze Matrix" value="true" type="RichBool" tooltip="The transformation is explicitly applied and the vertex coords are actually changed" name="Freeze"/>
  <Param description="Apply to all layers" value="false" type="RichBool" tooltip="The transformation is explicitly applied to all the mesh and raster layers in the project" name="ToAll"/>
 </filter>
```
but meshlabserver returns error such as 
```
meshlabserver: mainserver.cpp:365: bool MeshLabServer::script(MeshDocument&, const QString&, FILE*): Assertion `parameterSet.paramList.size() == required.paramList.size()' failed.
```

My environment is as follows:
- meshlab version: meshlab_64bitan_fp v2016.12 built on Mar 7 2017
- OS: ubuntu 16.04

Please let me know about the filter script of transform. 
Thanks,

**Comment by mcallieri** [comment]
The filter has changed, since that script was posted online.
Open MeshLab, load one of your meshes, call the filter, and set the correct parameters, hit apply, and see if the result is correct.
Now, select filters->show current script
you should see the translation step you just used. save this script on your drive.
You may still change the parameters using a txt editor.
