### ISSUE TITLE
Wrong raster projection (depending on depth value)

### ISSUE THREAD

**Issue by fj-melero** [cnr-isti-vclab/meshlab#348]
In a set of >50 images, there are two that result in a strange behaviour:
-using the default value of 0.5 for depth threshold, the result is as follow. Som parts are not projected:
![m2](https://user-images.githubusercontent.com/20094514/44080921-ad922888-9fad-11e8-8c6f-5eb049ed531f.JPG)
- the larger is the depth threshold value, less unprojected areas are in the surface. Over 25 the complete image is projected:
![m1](https://user-images.githubusercontent.com/20094514/44080920-ad796f6e-9fad-11e8-8c55-2c391b89b61f.JPG)

**Comment by mcallieri** [comment]
that's a reeeeally big value. Either the scale of the scene is peculiar (veryt large or very small), or those cameras have "extreme" focal value. 
depending on how the camera has been estimated, the focal may be "almost" its original value in mm (i.e. willhave a value that is close to the value it has in reality, in millimiters), but other tools always estimate a focal of 1, and what changes is the size of image plane, and other tools estimate very large/small focals. 
MeshLab works best when the value of focal is close to the physical counterpart,a nd the scale of the scene is in mm. You may deviate a bit from this, but not much.
Can you tell me which is the scale of the scene, and show me the camera parameters?
