### ISSUE TITLE
Problem with vertex attribute transfer using meshlabserver

### ISSUE THREAD

**Issue by gmiguelr87** [cnr-isti-vclab/meshlab#350]
Dear all,

I have a pointcloud with noise and holes and the corresponding mesh, but my generated mesh hasn't noise and holes, so I've obtained a dense point cloud from the mesh using CloudCompare.

Now, I'm trying to apply the color of the first pointcloud to the dense point cloud. If I use Meshlab (GUI) I haven't problems, the result is perfect, but if I save the script (*.mlx) and I try to use meshlabserver by command line to do it, the final result is not good. It has the same number of the dense pointcloud but the same shape of the original pointcloud.

In the script, I only have selected the transference of the color. It's very strange. By the way, the order of the clouds when I call to meshlabserver by cmd is the correct.

Where could be the problem ? I attach an image to clarify the process.
Thank you in advance!

![grafico](https://user-images.githubusercontent.com/20948392/44402180-3ed6d200-a551-11e8-8584-c437fed8edbc.jpg)

**Comment by Dawars** [comment]
I have the same problem, have you found a solution?

**Comment by gmiguelr87** [comment]
Hi @Dawars !

I'm sorry, but I still can't find a solution.

**Comment by alemuntoni** [comment]
We are going to dismiss meshlabserver in the future, and replace it with [PyMeshLab](https://github.com/cnr-isti-vclab/PyMeshLab). 
It is an alpha stage, and we are looking for feedbacks :) If this or any other issue occurs in PyMeshLab, please open an issue there! :)
