### ISSUE TITLE
After running a filter the output file's alpha component of a vertex is set to 1.0 (or 255)

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [cnr-isti-vclab/meshlab#351]
Hello,

I have a PLY pointcloud, where I use the *alpha* property to store classification.

After running a filter like this (normal estimation)
```
<!DOCTYPE FilterScript>
<FilterScript>
 <filter name="Compute normals for point sets">
  <Param type="RichInt" value="32" name="K"/>
  <Param type="RichBool" value="false" name="flipFlag"/>
  <Param x="0" y="0" z="0" type="RichPoint3f" name="viewPos"/>
 </filter>
</FilterScript>
```

The output PLY file's vertex alpha is all 255 (uchar)

I would expect that alpha would be preserved.

**Comment by mcallieri** [comment]
Yes, the alpha was ignored in saving/loading. It has been corrected.
Grab the new beta version:

MacOS:
from GitHub
https://github.com/cnr-isti-vclab/meshlab/releases
Get the latest .dmg installer

Windows:
from AppVeyor
https://ci.appveyor.com/pro…/cignoni/meshlab/build/artifacts
For Window version, there is no installer, yet, but we have a portable folder, just unpack it on your PC and double-click on MeshLab icon. As this version is continuosly updated, if you see there is a compilation ongoing (or failed) just go to "history" and look for the artifact in last successful build.
