### ISSUE TITLE
How to get a 3X3 rotation matrix and a 3X1 translation matrix?

### ISSUE THREAD

**Issue by sevenlovechen** [cnr-isti-vclab/meshlab#352]
**Target:** 
Once import a 3D model into Meshlab, I intend to get the intrinsic and extrinsic parameters of the camera of a specific viewpoint.

**Method:** 
Ctrl+C in Meshlab, I get the following data:
<VCGCamera 
RotationMatrix= 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1   
CenterPx= 728 464  
LensDistortion= 0 0  
CameraType= 1  
FocalMm= 392.743  
ViewportPx= 1457 929  
PixelSizeMm= 0.0369161 0.0369161  
TranslationVector= -0.49982 -0.499819 -14.0477 1 />
<ViewSettings NearPlane= 0.3  FarPlane= 5.33288  TrackScale= 2.91552 />

**Problem:** 
Here, the Rotation and Translation are 4X4 and 1X4 respectively. How can I get a 3X3 rotation matrix and a 3X1 translation vector?

**Comment by mcallieri** [comment]
well, 4x4 rotation matrices are build like this
RRR0
RRR0
RRR0
0001
so, just get the 3x3 submatrix :)
The translation is in the field "TranslationVector"

MeshLab uses 4x4 matrices because are easier to manage. the roto-translation matrix you see on the bottom of the info panel, for mesh layers is like this: 
RRRT
RRRT
RRRT
0001

**Comment by sevenlovechen** [comment]
Hi macllieri

Thanks for your reply.
I also thought the 3X3 rotation matrix is the submatrix of "RotationMatrix".
However, It seems not like that from my observation.
For example, when a 3D model is observed from FRONT view (Meshlab->Windows->View From->Front), the RotationMatrix is [1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1].
It means that the orientations of the camera coordinate and world coordinate are identical.
But they are not identical in fact.
The z-axis of the world coordinate points out of the image, while the z-axis of the camera coordinate should point into the image.
