### ISSUE TITLE
How to install newer versions of Meshlab for windows?

### ISSUE THREAD

**Issue by AviP1234** [cnr-isti-vclab/meshlab#355]

**Comment by AviP1234** [comment]
Like many before me encounter, meshlabserver refuse to execute filters under the claim that:
"no additional memory available!!! memory required:"
The standard advice is to install a newer version of Meshlab, for example:
cnr-isti-vclab/meshlab#320 (comment)
But how does one install a newer version?
the link from the thread:
https://ci.appveyor.com/pro%E2%80%A6/cignoni/meshlab/build/artifacts
is a stab.

Or there is another solution to the problem?
Thanks

**Comment by cignoni** [comment]
For some reason the link you provide seems wrong 
The correct one seems to be the following one:
https://ci.appveyor.com/project/cignoni/meshlab/build/artifacts
Can you check it?

**Comment by AviP1234** [comment]
Thanks, I will try it.

**Comment by mcallieri** [comment]
it is not an installer, but a "live" folder. Just unzip it and run the executable from it

**Comment by fiddybux** [comment]
I'm glad I found this. Thank you. The prospect of downtime trying to compile a Windows version was not appealing. However, why not put this Windows binary on the Github page with the Mac DMG binaries?
