### ISSUE TITLE
MacOS Mojave latest cannot import PLY from ColMap

### ISSUE THREAD

**Issue by enzyme69** [cnr-isti-vclab/meshlab#356]
I tried this many times and somewhat having Meshlab crashing when importing PLY from ColMap. Is there a new updated version on Mac?

**Comment by cignoni** [comment]
Have you tried the latest pre-release dmg for mac that are available here?

https://github.com/cnr-isti-vclab/meshlab/releases

**Comment by enzyme69** [comment]
@cignoni Ok the DMG on those releases work! Thanks~
