### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [cnr-isti-vclab/meshlab#359]
i've downloaded Version '2016.12' as well as version '20180909' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. i guess the CFBundleVersion and CFShortVersionString entries in your Info.plist file are missing. 
all apps on macOS are supposed to contain valid version information.

**Comment by core-code** [comment]
please re-open. this is still an issue in MeshLab2020.04-macos

both the CFBundleVersion and CFShortVersionString are still missing

<img width="315" alt="Screenshot 2020-04-09 at 11 44 45" src="https://user-images.githubusercontent.com/1261954/78881827-a065f000-7a57-11ea-9227-d23dc08cc716.png">
<img width="259" alt="Screenshot 2020-04-09 at 11 44 48" src="https://user-images.githubusercontent.com/1261954/78881841-a3f97700-7a57-11ea-9f8c-d6188ea935f4.png">

**Comment by alemuntoni** [comment]
Sorry, my bad on closing this.
I think that this issue can be easily solved modifying [this file](https://github.com/cnr-isti-vclab/meshlab/blob/master/src/meshlab/Info.plist). However I can't do it and test right now (I don't have a Mac at home). 
If someone could do it and make a PR putting 2020.04 would be appreciated!
I'll then take care on updating the version automatically every month via github actions.

**Comment by core-code** [comment]
thanks for re-opening. i can test anything, no problem.

i wonder if directly adjusting the Info.plist is the right way to go though instead of generating the value at deploy-time. there must be some options for qt/make. alternatively one can do it in your deploy script:
```

/usr/libexec/PlistBuddy -c "Set CFBundleShortVersionString $(date +%Y.%m)" $DISTRIB_PATH/$APPNAME/Contents/Info.plist
/usr/libexec/PlistBuddy -c "Set CFBundleVersion $(date +%Y.%m)" $DISTRIB_PATH/$APPNAME/Contents/Info.plist
```

**Comment by alemuntoni** [comment]
Cool, I didn't know the existence of PlistBuddy :D 
I think that modifying Info.plist in this way it's easier. 
I am modifying the github workflows to do this in my meshlab fork, when I finish I send you a link to a dmg to test!
Thank you!

**Comment by alemuntoni** [comment]
@core-code, [here](https://github.com/alemuntoni/meshlab/suites/585382934/artifacts/4118808) you can find a dmg that should have version numbers :) 
could you please test it and let me know? thank you very much!

**Comment by core-code** [comment]
thanks for your quick turnaround here. i can confirm that this test version properly contains the version number "2020.03"

one problem remains though. your Info.plist file contains the "CFBundleGetInfoString" key that has been deprecated for more than 10 years and will prevent the version number "2020.03" from showing up in the "Get Info" or "QuickLook" views in the Finder. it will show up properly in "ColumnView" though.

i'd recommend getting rid of this

```
	<key>CFBundleGetInfoString</key>
	<string>MeshLab VCG-ISTI-CNR</string>
```

if you want copyright information, it should be added to the 'NSHumanReadableCopyright' field instead.

**Comment by alemuntoni** [comment]
Great, thank you again! 
All the edits have been done in #635 !

**Comment by core-code** [comment]
all good in the new release, thanks!
