### ISSUE TITLE
Flattening layers removes vertex colors from point clouds

### ISSUE THREAD

**Issue by thnewlands** [cnr-isti-vclab/meshlab#361]
I'm trying to manage 800 unique point clouds and merging them down seems like the easiest way to manage them. Unfortunately whenever I merge them together by using the flatten layers option in the layers hierarchy I lose my vertex colors. I haven't found a better way to solve this problem.

**Comment by mcallieri** [comment]
I am unable to replicate this. in both 2016.12 version as well as in the current beta.
Which version are you using?

**Comment by thnewlands** [comment]
Oops -- seems like I was back in 2014... Thank you! That fixed my issue.
