### ISSUE TITLE
Failure to find: ../../../../vcglib/wrap/openfbx/src/ofbx.cpp

### ISSUE THREAD

**Issue by yurivict** [cnr-isti-vclab/meshlab#363]
These files don't exist in vcglib:
```
WARNING: Failure to find: ../../../../vcglib/wrap/openfbx/src/ofbx.cpp
WARNING: Failure to find: ../../../../vcglib/wrap/openfbx/src/miniz.c
```

**Comment by tatsy** [comment]
Hi, I think you can probably fix the problem by switching the branch of `vcglib` to `devel`.

**Comment by alemuntoni** [comment]
I'll close this issue since it should be fixed with the last PRs.
Feel free to open another issue if the problem persists.
