### ISSUE TITLE
Working around "std::bad_alloc" error during "Parameterization + texturing from registered rasters"

### ISSUE THREAD

**Issue by fasterthan** [cnr-isti-vclab/meshlab#366]
I am trying to use Meshlab's `Parameterization + texturing from registered rasters` to apply texture to a photogrammetry object created using a Poisson reconstruction of a COLMAP ply file. When I try to use the filter, however, I receive the following error message:

![error_bad_alloc](https://user-images.githubusercontent.com/13704150/46262297-45dbf300-c4b4-11e8-9428-ad5c9d81f8e2.png)

I have 330 raster layers and the images they are based on are around 3 mb. My computer has 8 gb of memory and I am using 64 bit version of Meshlab, as the program warmly suggests using. I have tried adjusting the texture size setting in the `Parameterization + texturing from registered rasters` dialog box, but nothing works.

Is there a way I can get this process to run, so I can texture the Poisson reconstructed object?

**Comment by mcallieri** [comment]
Hi... The "Parameterization + texturing from registered rasters" is a filter intended to texturize the model using a SMALL set of images. Ideally, from 5 to 20.
It is useful when you have a model and few images, that you manually aligh using mutual information. We never implemented a method to directly work with such large image datasets as they comes from SFM and 3D-from-images tools.
