### ISSUE TITLE
Meshlab 2016.12 crashes when clicking right mouse button

### ISSUE THREAD

**Issue by scs640** [cnr-isti-vclab/meshlab#37]
.STL file open in MeshLab, any time right mouse button is clicked the program crashes. All other features tested working as expected. STL file is 21MB and issue is not RAM/PC performance related. 

Windows 7 SP1 64bit
Meshlab 2016.12

**Comment by mcallieri** [comment]
Never seen this behaviour before. We are unable to replicate the issue.
Does it happen for every mesh or just this one?

**Comment by scs640** [comment]
It doesn't happen with every mesh, only seems to happen with STL file >~18MB. I have tried with multiple different files with different model geometries and the file size rule seems to hold.

If you have an email address I will send one of my files.

**Comment by mcallieri** [comment]
Leave a comment

**Comment by mcallieri** [comment]
I closed the topic beause it is inactive from a long time, we had no other reports of this issue, and we cannot replicate it on any of the tens of machines we are using.

**Comment by fakedeltatime** [comment]
Another case appears, for I'm also experiencing crashes when right clicking in a project on Arch Linux, meshlab build from 2022-03-02 since that's what I installed from the AUR as meshlab-appimage.
