### ISSUE TITLE
Compile issues in Debian stable

### ISSUE THREAD

**Issue by jaggzh** [cnr-isti-vclab/meshlab#379]
I get no errors during run.  However, for compiling I edited:
`meshlabplugins/filter_csg/filter_csg.pro`
Adding lines:
`linux-g++:INCLUDEPATH += ../../external/inc/linux-g++/mpir-2.4.0`

This might be better done with adding a lib path to QMAKE_FLAGS includes, as I also had to modify that line to get to libs in external/lib/, like lib3ds.a

The README.md says:
``QMAKE_FLAGS=('-spec' 'linux-g++' 'CONFIG+=release' 'CONFIG+=qml_release' 'CONFIG+=c++11' 'QMAKE_CXXFLAGS+=-fPIC' 'QMAKE_CXXFLAGS+=-std=c++11' 'QMAKE_CXXFLAGS+=-fpermissive' 'INCLUDEPATH+=/usr/include/eigen3' "LIBS+=-L`pwd`/lib/linux-g++")``
I added to the end, making it:
```QMAKE_FLAGS=('-spec' 'linux-g++' 'CONFIG+=release' 'CONFIG+=qml_release' 'CONFIG+=c++11' 'QMAKE_CXXFLAGS+=-fPIC' 'QMAKE_CXXFLAGS+=-std=c++11' 'QMAKE_CXXFLAGS+=-fpermissive' 'INCLUDEPATH+=/usr/include/eigen3' "LIBS+=-L`pwd`/lib/linux-g++" "LIBS+=-L`pwd`/lib/linux")```

Also, the README.md qmake commands don't work in bash, due to the array variables expanding only the first item the way it's written.  For example, the README says:
`qmake meshlab_full.pro $QMAKE_FLAGS && make $MAKE_FLAGS`
New working version (for bash):
`qmake meshlab_full.pro "${QMAKE_FLAGS[@]}" && make "${MAKE_FLAGS[@]}"`

**Comment by jaggzh** [comment]
Here's the output of a run:
`Current Plugins Dir is: /home/jaggz/prj/meshlab/src/distrib/plugins 
Error While parsing the XML filter plugin descriptors: We are trying to load a xml file that does not correspond to any dll or javascript code; please delete all the spurious xml files
"Cannot load library /home/jaggz/prj/meshlab/src/distrib/plugins/libfilter_ssynth.so: (/home/jaggz/prj/meshlab/src/distrib/plugins/libfilter_ssynth.so: undefined symbol: _ZTIN14StructureSynth5Model9Rendering16TemplateRendererE)"
    Reading Param with name MeshLab::Appearance::backgroundBotColor : RichColor
	...Many 'Reading Param' lines here...
    Reading Param with name MeshLab::System::perBatchPrimitives : RichInt
Shader directory found '/home/jaggz/prj/meshlab/src/distrib/shaders', and it contains 19 gdp files
`

**Comment by martin-frbg** [comment]
Does the CSG filter work for you with this change ? (Issue #304 , I do not see it linking to either mpir or gmp on Linux with the current filter_csg.pro)

**Comment by jaggzh** [comment]
Hmm. #304 might resolve it.  My changes above do resolve it (this problem at least).
Regarding -lgmp, my build tree only has win32-gcc/libgmp.a (and xx.a).   My filter_csg has the direct linking of linux-g++/libmpir.a (and xx.a).  (I don't think this is the result of adding lib/linux to the QMAKE vars above; that is, the linking to libmpir.a might have been successful without that, the .a being in the g++ dir that's already in the QMAKE LIBS+=).
