### ISSUE TITLE
cpp11 abs() is ambiguous. 

### ISSUE THREAD

**Issue by bartoszek** [cnr-isti-vclab/meshlab#38]
When building meshlab with gcc6 i got this error.
```
eqhandle.cpp:86:47: error: call of overloaded ‘abs(qreal)’ is ambiguous
  qreal handleOffset = abs(newPos.x()-pos().x());
```

As _newPos.x()_ returns double you should use fabs() to get the absolute value.

> patch i used with my AUR package https://aur.archlinux.org/cgit/aur.git/plain/cpp11_abs.patch?h=meshlab-git

**Comment by mcallieri** [comment]
corrected in commit [be21cc8](https://github.com/cnr-isti-vclab/meshlab/commit/be21cc8d3009004fef1f23812da62524ee26df1b)
