### ISSUE TITLE
Can we open smpl model using meshlab

### ISSUE THREAD

**Issue by gangooteli** [cnr-isti-vclab/meshlab#380]
I have requirement to use smpl model. Can we use meshlab to open basic smpl model?

**Comment by martin-frbg** [comment]
Can you explain what SMPL is ? The only references I can find are either an obsolete raytracing software or what appears to be a coding framework to generate posed images of a human figurine.
Meshlab can handle file formats that are typically used in 3D scanning and printing, like STL, PLY, OBJ, DAE or X3D - basically a mesh of points in 3D space with optional color and normals.

**Comment by gangooteli** [comment]
Quoting from reference site:  http://smpl.is.tue.mpg.de/
SMPL (A Skinned Multi-Person Linear Model) is a realistic 3D model of the human body that is based on skinning and blend shapes and is learned from thousands of 3D body scans.

I am working on project related to Virtual Reality and Deep Learning. I need to do some experiment with human body mesh. I installed meshlab on ubuntu machine. I am able to open model in ply file format using meshlab. So that is fine.
Now need to do experiment with SMPL model file which I downloaded from website which is in FBX format. I am not seeing any option to open fbx model file using meshlab. I want to ask whether Can FBX file be opened using meshlab ?

**Comment by martin-frbg** [comment]
I do not think meshlab can handle FBX, you may have more luck with Blender (though its user interface is a bit daunting...)

**Comment by cignoni** [comment]
next version, will handle them. We have added fbx input support a few weeks ago...

**Comment by martin-frbg** [comment]
Ah sorry, somehow I managed to miss this despite building from master.

**Comment by LogWell** [comment]
When will the next version be released?

There are many formats of the model in [3D People](https://renderpeople.com/free-3d-people/), we are eager for the meshlab to support the FBX format.

^_^

**Comment by cignoni** [comment]
You can try (at your own risk :) ) the prerelease builds; you can found them here:
- dmg for osx: https://github.com/cnr-isti-vclab/meshlab/releases 
- portable version for win https://ci.appveyor.com/project/cignoni/meshlab/build/artifacts

**Comment by LogWell** [comment]
Thank you for your prompt reply~

The instructions of `Ubuntu18+MeshLab-20190129-beta`  are rare, there are always some errors while compiling.

Can you update `Ubuntu 18 Compilation example`, thanksss!!!
