### ISSUE TITLE
Filters menus mostly empty.

### ISSUE THREAD

**Issue by jaggzh** [cnr-isti-vclab/meshlab#381]
Poisson displays no options (as if the menu option were not chosen at all).
Tested "Butterfly Subdivision": Meshlab terminates with:
``unable to find the id corresponding to action  'S&ubdivision Surfaces: Butterfly Subdivision'
meshlab: ../common/interfaces.h:372: virtual MeshCommonInterface::FilterIDType MeshFilterInterface::ID(QAction*) const: Assertion `0' failed.
Aborted``

**Comment by martin-frbg** [comment]
See #180 if you are running it under KDE5 (either add an entry to your kdeglobals to keep it from adding accelerators to non-KDE applications or try my PR #374)
