### ISSUE TITLE
Snapcraft.yaml syntax error

### ISSUE THREAD

**Issue by plouj** [cnr-isti-vclab/meshlab#383]
Both `src/install/snap201703/snapcraft.yaml` and `snap/snapcraft.yaml` cause `snapcraft` to error out with the following syntax error:

```
yaml.parser.ParserError: while parsing a block mapping
  in "snap/snapcraft.yaml", line 58, column 5
expected <block end>, but found '-'
  in "snap/snapcraft.yaml", line 63, column 5
```

I believe the line above that should say `stage:`, but I'm not sure.

**Comment by alemuntoni** [comment]
This issue should be solved in the latest version (2020.06).
