### ISSUE TITLE
Error compiling using devel branch [UpdateFlags is not a member of vcg::tri]

### ISSUE THREAD

**Issue by parisana** [cnr-isti-vclab/meshlab#389]
> **~/meshlab/src/common$** qmake common.pro -spec linux-g++ CONFIG+=release CONFIG+=qml_release CONFIG+=c++11 QMAKE_CXXFLAGS+=-fPIC QMAKE_CXXFLAGS+=-std=c++11 QMAKE_CXXFLAGS+=-fpermissive INCLUDEPATH+=/usr/include/eigen3 LIBS+=-L`pwd`/lib/linux-g++ && make -j11

vcglib/vcg/complex/algorithms/polygon_support.h: In static member function ‘static void vcg::tri::PolygonSupport<TriMeshType, PolyMeshType>::ImportFromTriMesh(PolyMeshType&, TriMeshType&)’:
../../../vcglib/vcg/complex/algorithms/polygon_support.h:128:7: error: ‘UpdateFlags’ is not a member of ‘vcg::tri’
       tri::UpdateFlags<TriMeshType>::FaceClearV(tm);
       ^
../../../vcglib/vcg/complex/algorithms/polygon_support.h:128:35: error: expected primary-expression before ‘>’ token
       tri::UpdateFlags<TriMeshType>::FaceClearV(tm);
                                   ^
../../../vcglib/vcg/complex/algorithms/polygon_support.h:128:36: error: ‘::FaceClearV’ has not been declared
       tri::UpdateFlags<TriMeshType>::FaceClearV(tm);
                                    ^
In file included from ../../../vcglib/vcg/complex/algorithms/clean.h:34:0,
                 from ../../../vcglib/vcg/simplex/tetrahedron/topology.h:28,
                 from ../../../vcglib/vcg/complex/complex.h:54,
                 from ml_mesh_type.h:4,
                 from mlapplication.h:7,
                 from mlapplication.cpp:1:
../../../vcglib/vcg/complex/algorithms/update/normal.h: In static member function ‘static void vcg::tri::UpdateNormal<ComputeMeshType>::PerVertexClear(ComputeMeshType&, bool)’:
../../../vcglib/vcg/complex/algorithms/update/normal.h:68:5: error: ‘UpdateFlags’ was not declared in this scope
     UpdateFlags<ComputeMeshType>::VertexClearV(m);
     ^
../../../vcglib/vcg/complex/algorithms/update/normal.h:68:32: error: expected primary-expression before ‘>’ token
     UpdateFlags<ComputeMeshType>::VertexClearV(m);
                                ^
../../../vcglib/vcg/complex/algorithms/update/normal.h:68:33: error: ‘::VertexClearV’ has not been declared
     UpdateFlags<ComputeMeshType>::VertexClearV(m);
                                 ^
../../../vcglib/vcg/complex/algorithms/update/normal.h:71:5: error: ‘UpdateFlags’ was not declared in this scope
     UpdateFlags<ComputeMeshType>::VertexSetV(m);
     ^
../../../vcglib/vcg/complex/algorithms/update/normal.h:71:32: error: expected primary-expression before ‘>’ token
     UpdateFlags<ComputeMeshType>::VertexSetV(m);
                                ^
../../../vcglib/vcg/complex/algorithms/update/normal.h:71:33: error: ‘::VertexSetV’ has not been declared
     UpdateFlags<ComputeMeshType>::VertexSetV(m);

**Comment by martin-frbg** [comment]
Are you sure that you are compiling against a devel checkout of vcglib as well ?

**Comment by parisana** [comment]
@martin-frbg I used this command to clone
`git clone --depth 1 -b devel https://github.com/cnr-isti-vclab/vcglib.git`

N.B: I have also tried using the Rel branch but it show a different error.

**Comment by martin-frbg** [comment]
Qt 5.9 and somewhat recent compiler ? I got lots of strange errors trying to build in an older environment that had only Qt5.6 and a similarly dated gcc - these did not occur on a more modern system.
The only thing that probably really needs fixing (removing) is a conflicting declaration of ReadHeader() in wrap/io_trimesh/import_nvm.h and export_nvm.h (issue #329)

**Comment by cignoni** [comment]
sorry a wrong vcg commit broke the build. Fixed, pull the latest devel branch of the vcglib.

**Comment by parisana** [comment]
Its compiling now. Thanks a lot @cignoni @martin-frbg

**Comment by parisana** [comment]
> There is one error though while compiling common.pro

In file included from meshlabdocumentbundler.h:4:0,
                 from meshlabdocumentbundler.cpp:11:
../../../vcglib/wrap/io_trimesh/import_out.h: In static member function ‘static bool vcg::tri::io::ImporterOUT<OpenMeshType>::ReadHeader(const char*, unsigned int&, unsigned int&)’:
../../../vcglib/wrap/io_trimesh/import_out.h:91:18: error: no matching function for call to ‘vcg::tri::io::ImporterOUT<OpenMeshType>::ReadHeader(FILE*&)’
     ReadHeader(fp);
                  ^
../../../vcglib/wrap/io_trimesh/import_out.h:76:13: note: candidate: static bool vcg::tri::io::ImporterOUT<OpenMeshType>::ReadHeader(FILE*, unsigned int&, unsigned int&)
 static bool ReadHeader(FILE *fp,unsigned int &num_cams, unsigned int &num_points){
             ^~~~~~~~~~
../../../vcglib/wrap/io_trimesh/import_out.h:76:13: note:   candidate expects 3 arguments, 1 provided
../../../vcglib/wrap/io_trimesh/import_out.h:88:13: note: candidate: static bool vcg::tri::io::ImporterOUT<OpenMeshType>::ReadHeader(const char*, unsigned int&, unsigned int&)
 static bool ReadHeader(const char * filename,unsigned int &/*num_cams*/, unsigned int &/*num_points*/){
             ^~~~~~~~~~
../../../vcglib/wrap/io_trimesh/import_out.h:88:13: note:   candidate expects 3 arguments, 1 provided
In file included from meshlabdocumentbundler.h:5:0,
                 from meshlabdocumentbundler.cpp:11:
../../../vcglib/wrap/io_trimesh/import_nvm.h: In static member function ‘static bool vcg::tri::io::ImporterNVM<OpenMeshType>::ReadHeader(const char*, unsigned int&, unsigned int&)’:
../../../vcglib/wrap/io_trimesh/import_nvm.h:91:18: error: no matching function for call to ‘vcg::tri::io::ImporterNVM<OpenMeshType>::ReadHeader(FILE*&)’
     ReadHeader(fp);
                  ^
../../../vcglib/wrap/io_trimesh/import_nvm.h:78:13: note: candidate: static bool vcg::tri::io::ImporterNVM<OpenMeshType>::ReadHeader(FILE*, unsigned int&)

**Comment by martin-frbg** [comment]
That is what I mentioned above. The attached diff seems to fix it.
[gitdiff.txt](https://github.com/cnr-isti-vclab/meshlab/files/2514887/gitdiff.txt)

**Comment by parisana** [comment]
@martin-frbg Thanks. I am not a C developer btw. I'll try to get it working. And if you could provide more info on how to get it done, that'll be great.

**Comment by martin-frbg** [comment]
What I posted is a recipe for the `patch` program, telling it where to add(+) or remove(-) lines in the original to arrive at the changed version. If you put it in the top level of your vcglib sources and run
`patch -p1 <gitdiff.txt` it should apply the changes. You can also use the option `--dry-run` in addition to the `-p1` to make it test if it can apply the diff without actually changing anything first. (The `-p1` tells it to skip the first part of the path mentioned in the diff file in its attempt to find the matching file - this is usually "a/" vs. "b/" for a change relative to the toplevel directory).
Alternatively, you can simply read the diff file to see where it adds ("+" in first column) an `#if 0` and
matching `#endif`and make that change by hand.

**Comment by parisana** [comment]
Yes that patching fixed the error. Thanks again. Have a good day :D
