### ISSUE TITLE
Locale issue when importing ascii files.

### ISSUE THREAD

**Issue by bartoszek** [cnr-isti-vclab/meshlab#39]
There is a problem when reading ASCII based files when system locale is set to one witch utilise _comma_ instead of _dot_ as decimal separator. Think meshlab should override locale to prevent this _exotic_ problem (spend few days before figure this out, have polish localisation on my linux machine).

> here is the patch used for my AUR package https://aur.archlinux.org/cgit/aur.git/plain/fix_locale.patch?h=meshlab-git

_Have reported this on sourceforge bug tracker earlier_

**Comment by granzuglia** [comment]
Thanks a lot! we reviewed your proposed commit (we changed it a little bit using the standard template library std::setlocale function) and we integrated it in MeshLab.
Thanks again for your contribution!
