### ISSUE TITLE
Option to skip 'Unify Duplicated Vertices'

### ISSUE THREAD

**Issue by daef** [cnr-isti-vclab/meshlab#390]
Looking for a way to disable the 'Unify Duplicated Vertices' prompt I found [two](https://stackoverflow.com/questions/48662309/meshlab-how-to-turn-off-the-unify-duplicated-vertices-prompt) stackoverflow [questions](https://stackoverflow.com/questions/43219065/how-can-i-suppress-the-prompt-to-unify-duplicated-vertices-when-opening-severa?rq=1) but no solution. A setting (Always/Never/Ask) would suffice I guess.

**Comment by cignoni** [comment]
It is already there :) 

You can try (at your own risk :) ) the prerelease builds; you can found them here:
- dmg for osx: https://github.com/cnr-isti-vclab/meshlab/releases 
- portable version for win https://ci.appveyor.com/project/cignoni/meshlab/build/artifacts


<img width="655" alt="screen shot 2018-10-26 at 9 29 19 am" src="https://user-images.githubusercontent.com/8055819/47551185-c9490280-d901-11e8-8593-dc6a54876d0c.png">
