### ISSUE TITLE
meshlabserver : [ERROR] Failed to open file: PR_a

### ISSUE THREAD

**Issue by katakurashohei** [cnr-isti-vclab/meshlab#392]
Hi,

Now I am trying to run meshlabserver from Grasshopper Component.
because try some mesh processing, we run Python from C #  using System.Diagnostics.Process. the python code has meshlabserver command.
There is an error, and it is something like the following. 
What does this mean and what is occurring here?
If I run Python alone from shell, meshlabserver work well.

![capture](https://user-images.githubusercontent.com/13250740/47646146-5ddb8b00-dbb6-11e8-8ce9-1ee85bf19673.PNG)

**Comment by martin-frbg** [comment]
This error message appears to be generated in the Screened Poisson filter code where it tries to create a temporary file (using _mktemp without a path component in the template). Perhaps your C# environment blocks use of _mktemp (e.g. by running your code from a non-writable directory).

**Comment by katakurashohei** [comment]
@martin-frbg Thanks a lot! I solved this problem when I launch Rhino as an administrator.
