### ISSUE TITLE
dramatic shutdown with "compute planar section" function.

### ISSUE THREAD

**Issue by Niconol26** [cnr-isti-vclab/meshlab#393]
Hi,
I'm using meshlab v1.3.2_64bit (Feb 19 2016) on a linux Mint station.
I got trouble when I want to use "compute planar section", and when I want to speak english too ....

That is what I do:

- Open Meshlab
- Filters / create new mesh layer / box  (scale factor = 1). Apply
- Compute Planar Section / I don't change any parameter (Xaxis; 0-1-0; ViewDir; 0; Bounding box center)
- Apply -> meshlab closes imediately, no message

Nothing more. Is it a known problem? Is there a solution?
best

**Comment by martin-frbg** [comment]
Does not crash with current builds, and if I am not mistaken meshlab 1.3.2 was actually released some time in 2012. I guess you could try the "snap" package of the latest stable release (2016.12) from http://www.meshlab.net/#download if you do not want to go to the trouble of building from source.

**Comment by Niconol26** [comment]
Ok, thanks martin-frbg, I installed the last stable snap package. I got several problem to launch meshlab. 
```
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Qt: Session management error: None of the authentication protocols specified are supported
QNetworkManagerInterface::QNetworkManagerInterface(QObject*) propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.85\" (uid=1000 pid=11285 comm=\"meshlab \") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1233 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
QNetworkManagerInterface::QNetworkManagerInterface(QObject*) nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.85\" (uid=1000 pid=11285 comm=\"meshlab \") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1233 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
"Object path cannot be empty"
Current Plugins Dir is: /snap/meshlab/4/bin/plugins 
"Cannot load library /snap/meshlab/4/bin/plugins/libfilter_ssynth.so: (/snap/meshlab/4/bin/plugins/libfilter_ssynth.so: undefined symbol: _ZTIN14StructureSynth5Model9Rendering16TemplateRendererE)"
. 
```
Now I try to solve that.
Best
