### ISSUE TITLE
meshlabserver not working using Linux snap on Ubuntu 18.04.1 LTS 

### ISSUE THREAD

**Issue by srs7** [cnr-isti-vclab/meshlab#395]
I installed the Snap on Ubuntu 18.04.1 LTS and I can launch meshlab from the command line (not desktop icon), but now I am trying to use meshlabserver and it does not work. 

When I run `./meshlabserver` from /snap/meshlab/current/bin/ 

`./meshlabserver: error while loading shared libraries: libcommon.so.1: cannot open shared object file: No such file or directory`

I have followed  issue #98 but when using the proposed solution:

```
LD_LIBRARY_PATH=/snap/meshlab/current/lib:/snap/meshlab/current/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH ./meshlabserver
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Aborted (core dumped)

```
I have also check this:
```
locate libqxcb

/snap/meshlab/4/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
/snap/meshlab/4/usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-egl-integration.so
/snap/meshlab/4/usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
/usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-egl-integration.so
/usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
```

Any ideas to solve the problem?

**Comment by martin-frbg** [comment]
Seems to me the "missing" lib is in a path that has "4" where your LD_LIBRARY_PATH has "current", try adding another entry for the /snap/meshlab/4/usr/lib/x86...  path to your LD_LIBRARY_PATH?

**Comment by srs7** [comment]
I added as you suggested but still had the same bug.

However, I found how to run it
`snap run meshlab.meshlabserver `

**Comment by the4thchild** [comment]
I was able to run meshlabserver on Ubuntu 18.04.1 with the command you used (`snap run meshlab.meshlabserver`), but when I try to input a file, I get this error (also mentioned in #393 and #160 ):

```
"Cannot load library /snap/meshlab/4/bin/plugins/libfilter_ssynth.so: (/snap/meshlab/4/bin/plugins/libfilter_ssynth.so: undefined symbol: _ZTIN14StructureSynth5Model9Rendering16TemplateRendererE)"
```

I encounter a similar error when running meshlabserver directly with `/snap/bin/meshlab.meshlabserver` as well.

Have you been able to load files with meshlabserver on Ubuntu 18.04?

**Comment by its-phisherman** [comment]
first check out if you have meshlab instaled

**Comment by albertotono** [comment]
I am installing meshlab with `sudo snap install meshlab` but it doesn't install meshlabserver. I needed for an old project, it looks like now there is PyMeshLab? and meshlabserver is "deprecated" am I right? how can I use meshlabserver now?

**Comment by alemuntoni** [comment]
You can't. It is deprecated and it won't work with modern scripts. You have to use pymeshlab, which requires just 5 minutes of time of [reading documentation](https://pymeshlab.readthedocs.io/en/latest/filter_scripts.html) and use it in the same way of meshlabserver.
