### ISSUE TITLE
How to compile plugin separately?

### ISSUE THREAD

**Issue by LogWell** [cnr-isti-vclab/meshlab#396]
There's such a remark in /meshlab/src/README.md :

>MeshLab has a plugin architecture and therefore all the plugins are compiled separately; some of them are harder to be compiled. Don't worry, if a plugin fails to compile just remove it and you lose just that functionality.

If I want to compile and run plugins like `/meshlab/src/meshlabplugins/filter_screened_poisson`, how to config it? And what's the output?

Thanks for your time and attention!

**Comment by cignoni** [comment]
You can compile a plugin separately (just run its .pro into qmake or open it inside qtcreator), but you can't run any plugin without meshlab.
