### ISSUE TITLE
Failure of Filter: "Screened Poisson Surface Reconstruction"

### ISSUE THREAD

**Issue by hacking93** [cnr-isti-vclab/meshlab#398]
Hi all,

I am struggling with the Screened Poisson Surface Reconstruction in Meshlab 2016.12 for Windows 10. I have imported a .stl mesh of a bunch of grapes, which has the back missing. For some of the bunches, the tool works fine. For others, I get the “Failure of Filter” error which tells me that  **it is necessary that ALL the input vertices have a proper, not-null normal**. The message tells you to try and use the **Remove Unreferenced Vertices **filter, which I try, but nothing is removed, and thus does not resolve my issue. The help also tells you to try pre-clean, which also does not work for me.  I have tried everything to try and resolve this issue. I see some people have mentioned to compute the normals, which works, but the Poisson reconstruction is then extremely bad (see image), and does not reconstruct the mesh as expected, like it does when it works.

Any assistance would be greatly appreciated. Perhaps I am missing something, but currently I am unable to resolve this issue.

Thanks in advance,

Chris
![poisson reconstruction01](https://user-images.githubusercontent.com/45006163/48418262-7d99b400-e75d-11e8-8bda-bab2b41bd664.png)

**Comment by SimonNgj** [comment]
I think your input is a point cloud without normals. If you calculate the normals before applying Screened Poisson Surface Reconstruction, you may get what you want
