### ISSUE TITLE
Quadric Edge Collapse Decimation assertion "IsValid" fails.

### ISSUE THREAD

**Issue by John-Nagle** [cnr-isti-vclab/meshlab#399]
I've been struggling to get "meshlabserver" on Linux to do a successful decimation. This works in the GUI program, but not in "meshlabserver". Linux 16.04 LTS.

- Test case: create default mesh "cylinder" in Blender 2.79, export as .ply file. This is the simplest thing worth simplifying. 
- Get meshlabserver from source suggested in https://github.com/cnr-isti-vclab/meshlab/issues/271 because Linux "snap" distribution does not work. 
- Run meshlabserver with an XML script as suggested at (http://www.cicoplay.com/diary/2016/04/12)
- Meshlabserver crashes with an assertion failure.

Result:

```
meshlabserver -i cylinder.ply -o cone_o.ply  -s quadric_mesh_reduction.mlx
Loading Plugins:
Current Plugins Dir is: /usr/lib/meshlab/plugins 
Error While parsing the XML filter plugin descriptors: We are trying to load a xml file that does not correspond to any dll or javascript code; please delete all the spurious xml files
Total 224 filtering actions
Total 12 io plugins
Opening a file with extention ply
Mesh /home/john/Documents/sl/meshlabtests/cylinder.ply loaded has 192 vn 124 fn
output mesh  /home/john/Documents/sl/meshlabtests/cone_o.ply
Apply FilterScript: '/home/john/Documents/sl/meshlabtests/quadric_mesh_reduction.mlx'
FilterScript
Reading filter with name Remove Unreferenced Vertices
Reading filter with name Remove Duplicate Vertices
Reading filter with name Remove Duplicate Faces
Reading filter with name Simplification: Quadric Edge Collapse Decimation
    Reading Param with name TargetFaceNum : RichInt
    Reading Param with name TargetPerc : RichFloat
    Reading Param with name QualityThr : RichFloat
    Reading Param with name PreserveBoundary : RichBool
    Reading Param with name BoundaryWeight : RichFloat
    Reading Param with name PreserveNormal : RichBool
    Reading Param with name PreserveTopology : RichBool
    Reading Param with name OptimalPlacement : RichBool
    Reading Param with name PlanarQuadric : RichBool
    Reading Param with name QualityWeight : RichBool
    Reading Param with name AutoClean : RichBool
    Reading Param with name Selected : RichBool
Starting Script of 4 actionsfilter: Remove Unreferenced Vertices
LOG: 2 Removed 0 unreferenced vertices
Removed 0 unreferenced vertices
filter: Remove Duplicate Vertices
LOG: 2 Removed 128 duplicated vertices
Removed 0 unreferenced vertices
Removed 128 duplicated vertices
filter: Remove Duplicate Faces
LOG: 2 Successfully deleted 0 duplicated faces
Removed 0 unreferenced vertices
Removed 128 duplicated vertices
Successfully deleted 0 duplicated faces
filter: Simplification: Quadric Edge Collapse Decimation
meshlabserver: ../../../../vcglib/vcg/math/quadric.h:160: ResultScalarType vcg::math::Quadric<_ScalarType>::Apply(const vcg::Point3<Q>&) const [with ResultScalarType = float; _ScalarType = double]: Assertion `IsValid()' failed.
Initializing simplificationAborted (core dumped)




```

**Comment by John-Nagle** [comment]
Filter script used: 

```
<!DOCTYPE FilterScript>
<FilterScript>
 <filter name="Remove Unreferenced Vertices"/>
 <filter name="Remove Duplicate Vertices"/>
 <filter name="Remove Duplicate Faces"/>
 <filter name="Simplification: Quadric Edge Collapse Decimation"> 
  <Param description="Target number of faces" name="TargetFaceNum" value="0" tooltip="The desired final number of faces." type="RichInt"/>
  <Param description="Percentage reduction (0..1)" name="TargetPerc" value="0.9" tooltip="If non zero, this parameter specifies the desired final size of the mesh as a percentage of the initial size." type="RichFloat"/>
  <Param description="Quality threshold" name="QualityThr" value="1" tooltip="Quality threshold for penalizing bad shaped faces.&lt;br>The value is in the range [0..1]&#xa; 0 accept any kind of face (no penalties),&#xa; 0.5  penalize faces with quality &lt; 0.5, proportionally to their shape&#xa;" type="RichFloat"/>
  <Param description="Preserve Boundary of the mesh" name="PreserveBoundary" value="true" tooltip="The simplification process tries to do not affect mesh boundaries during simplification" type="RichBool"/>
  <Param description="Boundary Preserving Weight" name="BoundaryWeight" value="1" tooltip="The importance of the boundary during simplification. Default (1.0) means that the boundary has the same importance of the rest. Values greater than 1.0 raise boundary importance and has the effect of removing less vertices on the border. Admitted range of values (0,+inf). " type="RichFloat"/>
  <Param description="Preserve Normal" name="PreserveNormal" value="true" tooltip="Try to avoid face flipping effects and try to preserve the original orientation of the surface" type="RichBool"/>
  <Param description="Preserve Topology" name="PreserveTopology" value="true" tooltip="Avoid all the collapses that should cause a topology change in the mesh (like closing holes, squeezing handles, etc). If checked the genus of the mesh should stay unchanged." type="RichBool"/>
  <Param description="Optimal position of simplified vertices" name="OptimalPlacement" value="true" tooltip="Each collapsed vertex is placed in the position minimizing the quadric error.&#xa; It can fail (creating bad spikes) in case of very flat areas. &#xa;If disabled edges are collapsed onto one of the two original vertices and the final mesh is composed by a subset of the original vertices. " type="RichBool"/>
  <Param description="Planar Simplification" name="PlanarQuadric" value="true" tooltip="Add additional simplification constraints that improves the quality of the simplification of the planar portion of the mesh." type="RichBool"/>
  <Param description="Weighted Simplification" name="QualityWeight" value="true" tooltip="Use the Per-Vertex quality as a weighting factor for the simplification. The weight is used as a error amplification value, so a vertex with a high quality value will not be simplified and a portion of the mesh with low quality values will be aggressively simplified." type="RichBool"/>
  <Param description="Post-simplification cleaning" name="AutoClean" value="true" tooltip="After the simplification an additional set of steps is performed to clean the mesh (unreferenced vertices, bad faces, etc)" type="RichBool"/>
  <Param description="Simplify only selected faces" name="Selected" value="false" tooltip="The simplification is applied only to the selected set of faces.&#xa; Take care of the target number of faces!" type="RichBool"/>
 </filter>
</FilterScript>
```

**Comment by martin-frbg** [comment]
I suspect the sources of both meshlab and vcglib contain a lot of assertions as developer aids that are commented out in the (scarce) releases.. That said, did you remember to use the development branch of vcglib for building ? 
(I believe we are lucky to get access to meshlab at all, as it seems to be the internal tool of a group of archeologists and art historians with little developer time to spare beyond their own needs. If your use case goes beyond what they regularly do with the program, you may end up in uncharted territory - but they do accept pull requests)

**Comment by albertotono** [comment]
I am getting this error when I am trying to use a simplification.mlx file

```
Starting Script of 1 actionsfilter: Simplification: Quadric Edge Collapse Decimation
meshlabserver: ./src/meshlabserver/mainserver.cpp:375: bool MeshLabServer::script(MeshDocument&, const QString&, FILE*): Assertion `parameterSet.paramList.size() == required.paramList.size()' failed.
```

any idea?

**Comment by ktertikas** [comment]
> I am getting this error when I am trying to use a simplification.mlx file
> 
> ```
> Starting Script of 1 actionsfilter: Simplification: Quadric Edge Collapse Decimation
> meshlabserver: ./src/meshlabserver/mainserver.cpp:375: bool MeshLabServer::script(MeshDocument&, const QString&, FILE*): Assertion `parameterSet.paramList.size() == required.paramList.size()' failed.
> ```
> 
> this is the python script
> 
> ```
> import os
> import argparse
> import ntpath
> import common
> 
> 
> class Simplification:
>     """
>     Perform simplification of watertight meshes.
>     """
> 
>     def __init__(self):
>         """
>         Constructor.
>         """
> 
>         parser = self.get_parser()
>         self.options = parser.parse_args()
>         self.simplification_script = os.path.join(
>             os.path.dirname(os.path.realpath(__file__)), 'simplification.mlx')
> 
>     def get_parser(self):
>         """
>         Get parser of tool.
> 
>         :return: parser
>         """
> 
>         parser = argparse.ArgumentParser(description='Scale a set of meshes stored as OFF files.')
>         input_group = parser.add_mutually_exclusive_group(required=True)
>         input_group.add_argument('--in_dir', type=str,
>                                  help='Path to input directory.')
>         input_group.add_argument('--in_file', type=str,
>                                  help='Path to input directory.')
>         parser.add_argument('--out_dir', type=str,
>                             help='Path to output directory; files within are overwritten!')
> 
>         return parser
> 
>     def read_directory(self, directory):
>         """
>         Read directory.
> 
>         :param directory: path to directory
>         :return: list of files
>         """
> 
>         files = []
>         for filename in os.listdir(directory):
>             files.append(os.path.normpath(os.path.join(directory, filename)))
> 
>         return files
> 
>     def get_in_files(self):
>         if self.options.in_dir is not None:
>             assert os.path.exists(self.options.in_dir)
>             common.makedir(self.options.out_dir)
>             files = self.read_directory(self.options.in_dir)
>         else:
>             files = [self.options.in_file]
> 
>         return files
> 
>     def run(self):
>         """
>         Run simplification.
>         """
> 
>         common.makedir(self.options.out_dir)
>         files = self.get_in_files()
> 
>         for filepath in files:
>             os.system('meshlabserver -i %s -o %s -s %s' % (
>                 filepath,
>                 os.path.join(self.options.out_dir, ntpath.basename(filepath)),
>                 self.simplification_script
>             ))
> 
> 
> if __name__ == '__main__':
>     app = Simplification()
>     app.run()
> ```
> 
> and the mlx file
> 
> ```
> <!DOCTYPE FilterScript>
> <FilterScript>
>  <filter name="Simplification: Quadric Edge Collapse Decimation">
>   <Param type="RichInt" value="5000" name="TargetFaceNum"/>
>   <Param type="RichFloat" value="0" name="TargetPerc"/>
>   <Param type="RichFloat" value="0.5" name="QualityThr"/>
>   <Param type="RichBool" value="false" name="PreserveBoundary"/>
>   <Param type="RichFloat" value="1" name="BoundaryWeight"/>
>   <Param type="RichBool" value="true" name="PreserveNormal"/>
>   <Param type="RichBool" value="false" name="PreserveTopology"/>
>   <Param type="RichBool" value="true" name="OptimalPlacement"/>
>   <Param type="RichBool" value="true" name="PlanarQuadric"/>
>   <Param type="RichBool" value="false" name="QualityWeight"/>
>   <Param type="RichBool" value="true" name="AutoClean"/>
>   <Param type="RichBool" value="false" name="Selected"/>
>  </filter>
> </FilterScript>
> ```
> 
> any idea?

Hi @albertotono , could it be related to this?
https://github.com/davidstutz/mesh-fusion/issues/15

Your mlx file does not seem to include the `PlanarWeight` parameter.
