### ISSUE TITLE
i build master, and nothing works....

### ISSUE THREAD

**Issue by brothermechanic** [cnr-isti-vclab/meshlab#401]
Hello
I try to build meshlab from git master, but i can't import any mesh, and create primitives.
![screenshot_20181203_083239](https://user-images.githubusercontent.com/3109995/49354861-03ae7800-f6d6-11e8-8786-cbba8c6e2956.png)

**Comment by cignoni** [comment]
from the toolbar you do not have any plugin loaded. object loading is done via plugin

**Comment by brothermechanic** [comment]
I fix plugin  finding, but nothing works
please, see screencast video
[2018-12-03 17-37-36.zip](https://github.com/cnr-isti-vclab/meshlab/files/2639856/2018-12-03.17-37-36.zip)

**Comment by brothermechanic** [comment]
i get it work with adding 
```
[Development]
AutoCheckAccelerators=false
to
```
~/.config/kdeglobals
