### ISSUE TITLE
Where is Screened Poisson Surface Reconstruction?

### ISSUE THREAD

**Issue by brothermechanic** [cnr-isti-vclab/meshlab#402]
Hello
I'm new here)
Help me to find Screened Poisson Surface Reconstruction
THis is my Meshlab git master +  vcglib git devel build window
![screenshot_20181203_213340](https://user-images.githubusercontent.com/3109995/49393723-1f039c80-f743-11e8-8d2a-7c4cf6bc2a1f.png)
Do you remove it?

**Comment by martin-frbg** [comment]
does #44 help ?

**Comment by brothermechanic** [comment]
@martin-frbg hello
no help ( 

i try all methods, but i have other filters works, only lost this filter

this is list of my package 
https://paste.pound-python.org/show/YwNPBYDGNkS4BYUM51jX/
this is plugins folder
https://paste.pound-python.org/show/qjFwkBGQFhgOrBBwaNng/

**Comment by alemuntoni** [comment]
I'll close this issue since it should be fixed with the last PR.
Feel free to open another issue if the problem persists.
