### ISSUE TITLE
MeshlabServer exports .objs as triangulated

### ISSUE THREAD

**Issue by gerroon** [cnr-isti-vclab/meshlab#407]
Hi

I have a simple script that does this

```subprocess.run(' meshlabserver.exe -i "{}" -o "{}"  -s "{}" '.format(in, out, script_path), shell=True)```

both "in" and "out" are .objs

This works, but my "out.obj" is **always triangulated** even when I have a simple script like

```
<!DOCTYPE FilterScript>
<FilterScript>
  <xmlfilter name="Compute Geometric Measures"/>
</FilterScript>
```

How can I make sure that my mesh is always what it is  in Meshlab when exported, basically I do not want it  to be saved as triangulated if it was not triangulated by the meshlab filter operation in the first place. It is naturally fine if the filter operation creates a triangulated mesh in the first place.

You can see this behavior with Meshlab itself. Open an .obj "export mesh as" then repopen it, you will see it is triangulated.

Is this a bug or by design?

I am using MeshLab_64bit_fp v2018.04   (built on Oct 21 2018) on Winx64 10

**Comment by mcallieri** [comment]
MeshLab, internally, only works with triangles. The conversion to triangles is automatic. However, as you are not touching the model, but just computing some measurements, why do you need the output?

**Comment by gerroon** [comment]
Well here is a use case, maybe only some normals are recalculated and saved back? I think there are many use cases of Meshlab where the actual geometry does not change, normals, vertex colors etc are couple of those use cases.
