### ISSUE TITLE
Mac: Application from DMG marked as broken / can't start

### ISSUE THREAD

**Issue by domdorn** [cnr-isti-vclab/meshlab#408]
Version 2016.12:
After downloading DMG and moving the App to the Applications Folder, the Application is marked as broken by OSX and double clicking won't open it.
![image](https://user-images.githubusercontent.com/100349/50999196-eb7a1600-1529-11e9-9920-33ad9eb6a73a.png)
![image](https://user-images.githubusercontent.com/100349/50999214-efa63380-1529-11e9-9457-5c7410e2cc9b.png)

I have to manually start the Application by doing "Show Package Contents" and navigating to Contents/MacOS/ and starting meshlab there.

**Comment by domdorn** [comment]
I'm running High Sierra (10.13.6) if this is important.

**Comment by martin-frbg** [comment]
Possibly same issue as #209 ?

**Comment by alemuntoni** [comment]
I'll close this issue since it should be fixed with the last PR.
Feel free to open another issue if the problem persists.
