### ISSUE TITLE
"No Vertex Found" when importing OBJ file

### ISSUE THREAD

**Issue by Casuallynoted** [cnr-isti-vclab/meshlab#409]
I can't seem to import a specific kind of OBJ file. Every single time I get the following error:

![image](https://user-images.githubusercontent.com/6272557/51287937-ef91b200-19c7-11e9-9f51-4b4b41205766.png)

I've checked and the file can be imported into blender/maya/max, but I've been hoping to import it into MeshLab as it has Vertex Colors. I'll be attaching the file here as well.

[se2_02.zip](https://github.com/cnr-isti-vclab/meshlab/files/2766700/se2_02.zip)

**Comment by NPatch** [comment]
If you mean per-vertex colors instead of through a texture using uvs, then OBJ does not officially support them. Other software does so by extending the spec but it's not standard for everyone to do so.

**Comment by chixian** [comment]
i have the same problem,do you solve it?

**Comment by NPatch** [comment]
At this point Meshlab won't fix it, so you might as well remove the vertex colors from your file, or use a different software.

**Comment by alemuntoni** [comment]
@chixian @NPatch I tried the only file shared in this thread and the issue does not exist anymore.
If you have some obj file that causes this issue **in the last version of MeshLab**, please open a new issue describing the issue and sharing the problematic file. Without it, there is not much I can do.
