### ISSUE TITLE
Meshlabserver ascii ouput

### ISSUE THREAD

**Issue by walsvid** [cnr-isti-vclab/meshlab#410]
When using GUI meshlab, I can turn off additional save parameter `binary encoding` to save ascii format `*.ply`.

Is there a solution when using the server version **`meshlabserver`**? What parameters should be added?

**Comment by alemuntoni** [comment]
```
meshlabserver -i input.obj -o output.ply -m sa
```
the option `-m sa` saves the ply output with ascii encoding. This feature has been added in #528
