### ISSUE TITLE
HausdorffSamplePoint_out.ply that is the output of the hausdorff distance at mlx is same with HausdorffClosestPoints_out.ply

### ISSUE THREAD

**Issue by dotchang** [cnr-isti-vclab/meshlab#412]
Hello. I want to use the Hausdorff Distance at meshlabserver. 
Usually, the function give the results as 2 files, HausedorffClosestPoint_out.ply and HausdorffSamplePoint_out.ply.
I need to use HausdorffSamplePoint_out.ply, but the data seems same as HausedorffClosestPoint_out.ply.

Could you check the problem?

**Comment by dotchang** [comment]
The result of the same operation at MeshLab.exe is totally different with MeshLabServers case.

**Comment by jbayardo** [comment]
I am having the same issue. The following mlx:

```
<!DOCTYPE FilterScript>
<FilterScript>
 <filter name="Change the current layer">
  <Param type="RichMesh" value="1" name="mesh"/>
 </filter>
 <filter name="Define New Per Vertex Attribute">
  <Param type="RichString" value="Quality" name="name"/>
  <Param type="RichString" value="q" name="expr"/>
 </filter>
 <filter name="Hausdorff Distance">
  <Param type="RichMesh" value="1" name="SampledMesh"/>
  <Param type="RichMesh" value="0" name="TargetMesh"/>
  <Param type="RichBool" value="false" name="SaveSample"/>
  <Param type="RichBool" value="true" name="SampleVert"/>
  <Param type="RichBool" value="false" name="SampleEdge"/>
  <Param type="RichBool" value="false" name="SampleFauxEdge"/>
  <Param type="RichBool" value="false" name="SampleFace"/>
  <Param type="RichInt" value="100000" name="SampleNum"/>
  <Param type="RichAbsPerc" value="0" min="0" name="MaxDist" max="32.5818"/>
 </filter>
</FilterScript>
```

Works fine for estimating the Hausdorff distance (i.e. I get the expected output in my stdout), but no quality information is recorded, so I can't use the Quality Mapper. The command I am running is:

`meshlabserver -i "reference_mesh.ply" -i "mesh.ply" -o "comparison.ply" -s "script.mlx" -om vc vf vq vn vt fc ff fq fn wc wn wt`

I have also tried running it with two outputs, but that doesn't work either. For whatever reason, the quality is not saved.
