### ISSUE TITLE
Import of a STL file fails (Premature end of file)

### ISSUE THREAD

**Issue by texnokrates** [cnr-isti-vclab/meshlab#416]
With the current github version of meshlab, some of the STL files that were imported well in an older meshlab version (1.3.2) fail to open now.

An example file which fails to import (generated by OpenSCAD; here attached gzipped due to github limitations): [blbost.stl.gz](https://github.com/cnr-isti-vclab/meshlab/files/2829576/blbost.stl.gz)

When trying to import, meshlab pops an "Opening Failure" window with the following:
> While opening: '/m/phys/project/qd/Marek/tmatrix-experiments/tvary/tmp/blbost.stl'
> 
> Error encountered while loading file:
> "/m/phys/project/qd/Marek/tmatrix-experiments/tvary/tmp/blbost.stl"
> 
> Error details: Premature end of file

**Comment by mcallieri** [comment]
Loads perfectly on multiple machines, with both 2016.12 and the new beta.
Looking inside the file, everything seems ok.
