### ISSUE TITLE
Meshlabserver output all zero

### ISSUE THREAD

**Issue by DYT-code** [cnr-isti-vclab/meshlab#418]
Hello Community,

I've tried to use Meshlabserver to convert my obj.

Here my code and the result:
meshlabserver -i "/home/yeting/ros_ws/src/dex-net/data/test/models/bar_clamp.obj" -o "/home/yeting/ros_ws/src/dex-net/data/test/models/test.obj"
Input mesh  /home/yeting/ros_ws/src/dex-net/data/test/models/bar_clamp.obj
output mesh  /home/yeting/ros_ws/src/dex-net/data/test/models/test.obj
Loading Plugins:
Current Plugins Dir is: /usr/lib/meshlab/plugins 
Error in XMLFile: filter_measure.xml - line: -1, column: -1 - 
Error in XMLFile: filter_mutualinfo.xml - line: -1, column: -1 - 
Total 227 filtering actions
Total 13 io plugins
Opening a file with extention obj
Mesh bar_clamp.obj loaded has 1428 vn 476 fn
No Script to apply.
Mesh /home/yeting/ros_ws/src/dex-net/data/test/models/bar_clamp.obj saved as /home/yeting/ros_ws/src/dex-net/data/test/models/test.obj (1428 vn 476 fn)

However, the output are all zeros and the delimiter becomes , instead of .
Here is a short piece of the result.
####
#
# OBJ File Generated by Meshlab
#
####
# Object test.obj
#
# Vertices: 1428
# Faces: 476
#
####
v 0,000000 -0,000000 0,000000
v 0,000000 -0,000000 0,000000
v 0,000000 -0,000000 0,000000
v 0,000000 -0,000000 0,000000
v 0,000000 -0,000000 0,000000
v 0,000000 -0,000000 0,000000

Could anyone help? Thanks in advance!

**Comment by martin-frbg** [comment]
The wrong decimal delimiter suggests a problem with your locale, can you try running that same command with "LANG=C" prepended, as in `LANG=C  meshlabserver  -i "/home/yeting/ros_ws/...` ?

**Comment by science-code** [comment]
I confirm that the solution to solving the mesh parsing error for DexNet caused by meshlab is to change the locale to one that uses a dot decimal separator.
