### ISSUE TITLE
Suggestion: an option to lock camera position when adding a mesh

### ISSUE THREAD

**Issue by jcoslovsky** [cnr-isti-vclab/meshlab#419]
When adding a new mesh to an already open mesh, the camera position jumps to the default view. It would be nice to have an option to lock the camera position at the current view.

**Comment by mcallieri** [comment]
true :(
There is a workaround: press CTRL-C when your mouse is in the 3D rendering area BEFORE importing, and press CTRL-V after importing, to return to the previous view.
I will take note of this, but it's not on our priority list.
