### ISSUE TITLE
cannot use space bar in macOS

### ISSUE THREAD

**Issue by mattmyne** [cnr-isti-vclab/meshlab#42]
When trying to use the space bar to toggle face/vertex selection on Get Info, only an "error" sound is played and the selection does not toggle. It is therefore not possible to select a vertex for Get Info.

I'm using macOS Sierra 10.12.2 and MeshLab 2016.12.

**Comment by mcallieri** [comment]
Confirmed... apparently, spacebar is "system reserved" :)
I will change the key.

**Comment by mcallieri** [comment]
Changed the key from "spacebar" to "t" or "T" (as in toggle).
Thanks for spotting this. You will have to wait for the next update to the release.
