### ISSUE TITLE
Customizing keyboard shortcuts

### ISSUE THREAD

**Issue by jfbourdon** [cnr-isti-vclab/meshlab#422]
Several tools have no keyboard shortcut which hinder productivity in my opinion. It would be great if it was possible to customize keyboard shortcuts, at least for all tools listed in the Edit menu. Being able to do the same thing with filters would be a big plus.

It was also on the [old SourceForge repo](https://sourceforge.net/p/meshlab/feature-requests/49/) from 2010.

**Comment by mcallieri** [comment]
Unfortunately, the way keyboard shortcuts are managed is not really uniform across the whole project.
I am trying to incorporate more shortcuts, especially in interactive filters (as visible in the beta), but it's a long processs, and almost certainly will not be configurable, sorry. For that kind of feature, we would need to rewrite the core.
