### ISSUE TITLE
Option to reverse mouse zoom direction

### ISSUE THREAD

**Issue by jfbourdon** [cnr-isti-vclab/meshlab#423]
As asked on the [old SourceForge repo](https://sourceforge.net/p/meshlab/feature-requests/77/), it would great to have the option to reverse the mouse zoom direction as it's confusing when working with several programs where zooming is done in the opposite direction. I suppose it could be temporaly adressed by using [AutoHotkey](https://autohotkey.com/docs/commands/Click.htm), but that wouldn't be ideal.

**Comment by mcallieri** [comment]
There is no clear standard for mouse wheel zoom direction.
I will take note of this, but it's not on our priority list.

**Comment by SirAdelaide** [comment]
Hi, please add this option. Should be an easy toggle?

**Comment by stefanct** [comment]
Since there is no clear standard it is especially annoying if one of the many tools one uses is enforcing the way one is not used to without a way to change it... ;) I had opened up meshlab for about 15 seconds before I was looking for a way to reverse it and ended up in this (closed!) issue... :'(

**Comment by runxel** [comment]
This is really bad. Just give us an option please and don't enforce a clearly highly disliked behavior :(

**Comment by rhuitl** [comment]
Same here. After I updated Meshlab, the zooming direction is now opposite as it was in the earlier version. It's also opposite to other applications like Blender, CloudCompare, pretty much anything.

Maybe the author of the change has gotten used to "natural" scrolling with the mouse, i.e., moving the mouse wheel upward scrolls a page down, and wasn't consequent enough to accept that moving the wheel up would zoom out in Meshlab, and therefore reversed it.

Unfortunately, that hard-coded reversing causes annoyances for users that don't use natural scrolling at all, or people like me that use it for the touchpad but use the Logitech configuration (or software like Scroll Reverser) to make wheel on the mouse behave in the classic way.

I don't think Meshlab needs an option, but it needs to have the current behavior reversed to bring it back in alignment with other software.

**Comment by alemuntoni** [comment]
Nothing has changed in the last versions of MeshLab, the zooming direction has been always the same.
However, we added an option to reverse on PR #737, and will be available starting from version 2020.07

**Comment by GithubUser99999999** [comment]
Why is this option never saved? MeshLab seems to be the only application in the entire world that switches zooming around. It's nuts.

**Comment by vaclavmuller** [comment]
MeshLabMouseReverser AutoHotkey script:

#If WinActive("ahk_exe meshlab.exe")
WheelUp::Send {WheelDown} 
WheelDown::Send {WheelUp}

**Comment by adras** [comment]
Yeah, please add an option, this is really annoying

**Comment by JuhaW** [comment]
> Here is a simple MeshLabMouseReverser AutoHotkey script. It could be compiled into an exe and run at Windows startup.
Thank you. Here is the same script for AutoHotkey 2.+ version:

#Requires AutoHotkey v2.0
#SingleInstance Force
#HotIf WinActive("ahk_exe meshlab.exe")
WheelUp::WheelDown
WheelDown::WheelUp

**Comment by foreachthing** [comment]
I just opened MeshLab for the first time in about 3 years. Still no option to change zoom  direction?
This is really nerve wrecking.
