### ISSUE TITLE
MeshLabServer does not handle spaces on Linux

### ISSUE THREAD

**Issue by jaykumarthaker** [cnr-isti-vclab/meshlab#426]
I have installed Meshlab on ubuntu-xenial-16.04-amd64-server (AWS EC2) with below commands:

```
sudo apt-add-repository ppa:zarquon42/meshlab

sudo apt-get update

sudo apt-get install meshlab
```

The issue is, if output attributes (that of -m) listed with one command results **CommandLine Syntax Error** 
```
sudo xvfb-run -a -s "-screen 0 800x600x24" meshlabserver  -i "231960_2018-12-06_10-39_Citak_Maxillary_export.wrl" -o "231960_2018-12-06_10-39_Citak_Maxillary_export_30k.obj" -m vc vn wt -s "./tools/decimate_mesh/filter_30k.mlx"
```

above command wouldn't work because of _-m vc vn wt_ (though same work fine on windows)

---
now if ran seprately, like:

```
sudo xvfb-run -a -s "-screen 0 800x600x24" meshlabserver  -i "231960_2018-12-06_10-39_Citak_Maxillary_export.wrl" -o "231960_2018-12-06_10-39_Citak_Maxillary_export_30k.obj" -m vc -s "./tools/decimate_mesh/filter_30k.mlx"


sudo xvfb-run -a -s "-screen 0 800x600x24" meshlabserver  -i "231960_2018-12-06_10-39_Citak_Maxillary_export.wrl" -o "231960_2018-12-06_10-39_Citak_Maxillary_export_30k.obj" -m vn -s "./tools/decimate_mesh/filter_30k.mlx"


sudo xvfb-run -a -s "-screen 0 800x600x24" meshlabserver  -i "231960_2018-12-06_10-39_Citak_Maxillary_export.wrl" -o "231960_2018-12-06_10-39_Citak_Maxillary_export_30k.obj" -m wt -s "./tools/decimate_mesh/filter_30k.mlx"
```
works fine!

**Comment by sheoranhimansh** [comment]
@jaykumarthaker Were you able to solve this issue. Even I am facing the same problem.

**Comment by jaykumarthaker** [comment]
@sheoranhimansh not yet! Though as a workaround, I switched to Windows instance instead!

**Comment by rmathar** [comment]
This is a standard problem of Linuxes: the "multi-option" after the ``-m`` is forwarded to the meshlabserver executable as separate tokens because the Linux shell uses spaces to separate tokens. It will probably work if the shell is prevented from interpreting them as separate options by packing them all with a single tick-mark like this ``-m 'vc vn wt'``
