### ISSUE TITLE
Why the meshlab can't find render->color?

### ISSUE THREAD

**Issue by TouchDeeper** [cnr-isti-vclab/meshlab#427]
Hi,
The meshlab installed in my computer is of v2016.12. And as the image below show, I can't find the render->color
![1](https://user-images.githubusercontent.com/39310744/53706017-2120e880-3e63-11e9-95c3-4670e7499a6a.png)

**Comment by mcallieri** [comment]
In this new version, we have moved some controls. Now it is possible to change rendering modes from a set of controls in the middle of the layer panel
https://www.youtube.com/watch?v=UtbCmaLy5Ek
