### ISSUE TITLE
WARNING: Failure to find

### ISSUE THREAD

**Issue by yurivict** [cnr-isti-vclab/meshlab#429]
I'm trying to build using ```meshlab_full.pro``` on FreeBSD, trying to update the port. It fails:

```
Reading /usr/ports/cad/meshlab/work/meshlab-25f3d17/src/common/common.pro
Reading /usr/ports/cad/meshlab/work/meshlab-25f3d17/src/meshlab/meshlab.pro
WARNING: Failure to find: ../../../vcglib/wrap/gui/trackball.cpp
WARNING: Failure to find: ../../../vcglib/wrap/gui/trackmode.cpp
WARNING: Failure to find: ../../../vcglib/wrap/gui/coordinateframe.cpp
WARNING: Failure to find: ../../../vcglib/wrap/gui/trackball.h
WARNING: Failure to find: ../../../vcglib/wrap/gui/trackmode.h
WARNING: Failure to find: ../../../vcglib/wrap/gl/trimesh.h
```

There are a lot of places in .pro files where long paths like this are used: ```../../../../vcglib/wrap/ply/plylib.cpp``` with no corresponding files, for exsampe, the project doesn't contain ```plylib.cpp```.

How can I use external packages, for example ```vcglib```?

**Comment by martin-frbg** [comment]
As the README.txt in src (which is mentioned in the toplevel README) states, you need to clone the current develop branch of vcglib at the same directory level as meshlab.

**Comment by yurivict** [comment]
> you need to clone the current develop branch of vcglib at the same directory level as meshlab.

Why don't you create a submodule that would clone this lib at this place? This could eliminate such questions altogether.

**Comment by martin-frbg** [comment]
I cannot speak for the developers, but by the looks of it meshlab is primarily an in-house tool at ISTI and they probably lack the resources to provide a more user-friendly "build experience". I guess if you know how to fix this particular issue you could consider providing a PR.

**Comment by alemuntoni** [comment]
vcglib is now a submodule, and the errors listed by @yurivict should be fixed now.
Feel free to open new issues if the error persists.
