### ISSUE TITLE
how to import wgs 84 coordinate

### ISSUE THREAD

**Issue by geonature86** [cnr-isti-vclab/meshlab#43]
Hi, 
how to import in meshlab the file ply with wgs 84 coordinate?
thanks a lot

**Comment by mcallieri** [comment]
Hi... 
Geo-referenced models have, generally, very large numbers as X-Y coordinates (in the order of millions, e.g. 45142322.012), which cause problems to the rendering system (and to most filters). 
If you load a 3D model that has GLOBAL coordinates, the rendering will appear incorrect, and most functions will fail.
This is why, on Computer Graphics software (MeshLab, Blender, 3DStudio, Maya) you normally work with LOCAL coordinates. GIS tools are able to manage this kind of coordinates, but not many other software.
MeshLab does not have an automatic GLOBAL->LOCAL conversion (like CloudCompare), sorry. You may try with CloudCompare, to bring back your model to local coordinates, and then work on it inside MeshLab. Or you may edit/process your model _before_ geo-referencing it.
