### ISSUE TITLE
MeshLab induces a whole-system freeze on close

### ISSUE THREAD

**Issue by courtarro** [cnr-isti-vclab/meshlab#432]
**OS**: Ubuntu 16.04 64-bit
**Kernel**: `4.4.0-141-generic #167-Ubuntu`
**CPU**: i7-6820HQ
**Video**: NVidia Quadro M1000M
**Video driver**: NVidia binaries, version 384.130

I just isntalled MeshLab from the Ubuntu repositories to do some viewing of `.obj` files. Everything was nice until I hit the `X` to close MeshLab. Immediately my mouse cursor froze and the system hung. `Capslock` and `Numlock` did nothing, pressing `Ctrl-Alt-F1` (to get a text console) did nothing, undocking the laptop did nothing. The only remedy seemed to be a hard shutdown by holding the power button.

Upon reboot I tried again, simply opening the same `.obj` file. It loaded nicely, worked fine. I hit `X` to close MeshLab and immediately got another hard freeze.

I'm willing to bet the actual fault in this lies with the NVidia drivers or (less likely) some kernel bug, since it's obviously not supposed to be possible for a userland app like this to take down a whole system. But I figured I'd start with the first point of contact with the failure.

**Comment by mcallieri** [comment]
Which version is the MeshLab in the Ubuntu repository?
This is happening with _all_ obj? or you do have a specific one that does the trick?
