### ISSUE TITLE
commandline does not accept many valid file names

### ISSUE THREAD

**Issue by ALfuhrmann** [cnr-isti-vclab/meshlab#434]
In "meshlab/src/meshlabserver/mainserver.cpp" the commandline files are validated [using a regular expression](https://github.com/cnr-isti-vclab/meshlab/blob/f6c6675baa3b4486bddbf2c5c24d219671ccfaac/src/meshlabserver/mainserver.cpp#L624) that does not accept most of the unicode character set: "[a-z]|[A-Z]|\\\\|/|\\d|-|_|\\.|\\:"

Even the tilde "~" (common symbol in most filesystems) leads to an immediate abort of processing.

Since validating paths using regex is [notoriously difficult](https://stackoverflow.com/questions/27587956/how-to-check-if-a-string-has-a-valid-file-path-or-directory-path-format-in-unman), I would skip this altogether and "validate" it implicitly later, when accessing the file in question.

As (crude) workaround, I am using "match-all" instead:
`line 624:		QString filecharcont(".*");`

**Comment by jmespadero** [comment]
Hi,
Not sure if this has been fixed, because I'm sure that I regulary run command as `meshlabserver -i ~/file.obj -o ~/file.ply`.
Can you give an example of command line that aborts meshlabserver?

**Comment by ALfuhrmann** [comment]
On windows it also crashes when using "foreign" characters:

> E:\meshlab>meshlabserver.exe -i weide.obj
Loading Plugins:
Current Plugins Dir is: E:/meshlab/plugins
Total 247 filtering actions
Total 12 io plugins
Opening a file with extention obj
Mesh is Polygonal!
Mesh E://meshlab/weide.obj loaded has 14275 vn 28560 fn

wenn ich rename the input file with an Umlaut, it goes like this:
>E:\meshlab>meshlabserver.exe -i weöde.obj
Loading Plugins:
Current Plugins Dir is: E:/meshlab/plugins
Total 247 filtering actions
Total 12 io plugins
Opening a file with extention obj
MeshLabServer: Failed loading of E:/meshlab/we´┐¢de.obj from dir E:/meshlab
It was not possible to import mesh E:/meshlab/we´┐¢de.obj into MeshLabServer. The program will exit

I am not sure how the commandline parser copes with unicode, the output "we´┐¢de.obj" looks like it is interpreting it as 8 bit characters.

But you are right: the last version I tested accepts "~" tilde as parts of the filename on windows.

**Comment by jmespadero** [comment]
Yes. It should also be solved with the PR #530

**Comment by ALfuhrmann** [comment]
Very pragmatic fix, thanks!
