### ISSUE TITLE
Crash on Reference scene -> scale reference operations

### ISSUE THREAD

**Issue by prathamnar11** [cnr-isti-vclab/meshlab#435]
Steps to recreate:
Import a mesh -> Go to reference scene -> Scale reference
Add a distance and export it to a txt file
Delete the distance and try loading the same from the saved txt file
The distances don't load as well as Meshlab crashes itself
I was able to get points using the pick points tool through a .pp file but the same approache failed for Lines/Distances
I am new to Meshlab. In any case can you let me know if I am doing something wrong?

![Capture](https://user-images.githubusercontent.com/46445442/54973656-cfc5ce00-4fb6-11e9-8061-1cbf6b50d107.PNG)

This is what I want to achieve and I want to be able to do it through a txt file or another file format. Is there any other way to draw distances/lines in Meshlab?

**Comment by mcallieri** [comment]
hello there.
That interface is a bit confusing, I know. The problem is, when you export as TXT you export a REPORT of the process of scaling/georeferencing, and that TXT file is not the same format you need in the "import txt" button. They are both .txt files, but containing different things, my fault, it's confusing. 
Please, explain what you do need to achieve, and I can try giving you instructions.

**Comment by prathamnar11** [comment]
Hi!
I would like to know the format or view a sample of the "import.txt" used for the 'load distances from file' input. If you can let me know that, that solves the problem.

I am using Meshlab to plot points and distances between those points. 

I import different types of meshes and have a script to generate the 'import.pp' for pick points on the mesh. This helped me automate the process of generating points for all the meshes as I did not have to do it myself. I could simply load the 'import.pp' and my points on the mesh would be displayed

I would like to automate the process of drawing the distances in a similar manner but as you rightly pointed out, I am using the wrong format. If you could let me know the format, I can write an another script to generate the 'import.txt' to load the distances.

Is there any other way to draw lines on the mesh and have something like this to automate the process?

Thank you for your previous response

**Comment by prathamnar11** [comment]
I would like to draw lines on my mesh using a 'import.txt' file like these
I think it should fairly straightforward once you provide me with the input file format 
![image](https://user-images.githubusercontent.com/46445442/55075163-40a0df00-50b8-11e9-8394-9e8fb386d533.png)

**Comment by mcallieri** [comment]
the format is:
ascii .txt file. One line for each distance. Each line has this elements:
name X1 Y1 Z1 X2 Y2 Z2  targetdistance
name is the ID of the distance, shown in the interface, X1 Y1 Z1 are the coordinates of the first point, X2 Y2 Z2 are the coordinates of the second point, targetdistance is the real-world distance between the two points. 
This plugin was built to calculate the scale factor of a model created by 3d-from-photos: the idea is that you pick two points on the model, and then entere which should be the distance. The plugin calculates a scaling factor.

example:
---------------------------------------------
DIST1 0.0 0.0 0.0 2.0 2.0 2.0 11.35
DIST2 3.0 5.0 0.0 11.4 -3.5 3.9 560.15 
DIST3 0.0 0.0 0.0 5.0 1.0 33.0 55.4

**Comment by prathamnar11** [comment]
Thank you very much for the quick response. Really appreciate the help. It's a great tool without a doubt. Good luck!
