### ISSUE TITLE
Problem generating surface with poisson

### ISSUE THREAD

**Issue by alvaroarce29** [cnr-isti-vclab/meshlab#436]
Good evening,

I am doing a thesis for my mechanical engineering major which consists on photogrammetry on mechanical pieces. I am having troubles when generating the surface with Poisson. The normal parameters that I choose are these:

![image](https://user-images.githubusercontent.com/48968937/55039756-7203a700-4ff3-11e9-987d-093f4f838bda.png)

Nevertheless, I get this model with irregular surface:

![FOTO 1](https://user-images.githubusercontent.com/48968937/55039733-5ac4b980-4ff3-11e9-8f96-3cfb777c36ce.PNG)
![FOTO 2](https://user-images.githubusercontent.com/48968937/55039734-5ac4b980-4ff3-11e9-84ef-c5fdbd750be4.PNG)

I think that probably there is a problem with rounded edges because of the light intensity and when VisualSFM is creating the cloud points, it get lost and don´t locate the points in the right position.

Nevertheless, I want to ask you if this is normal, if you may have a solution for this issue or what causes of this problem.

I upload to VisualSFM normally like 150 images and it catch usually 120. So I think that is not a lack of information.

Thank you,

Alvaro Arce

**Comment by mcallieri** [comment]
15 minimum samples? that is really, really a lot. 
It should create geometry only where there is a very high density of points, so less "floating" elements. However, if the point cloud is noisy, the result will still be noisy. An if an area has been sparsely recovered by 3d-from.photos, it will disappear.
This result is determined by your data and by your parametes, there is nothig wrong with poisson
