### ISSUE TITLE
Cannot upload my .ply file to MeshLab in Mac book pro

### ISSUE THREAD

**Issue by SimronThapa** [cnr-isti-vclab/meshlab#437]
My .ply file can be visualized perfectly with other 3D viewer applications like 3D view of Xcode. However, when I try to upload in the meshlab, it shows an error: unexpected eof .
I have attached my .ply mesh along with this issue message. Could you please help me find out what the problem is?

Thanks,
Simron 
[data_128_1.ply.zip](https://github.com/cnr-isti-vclab/meshlab/files/3010923/data_128_1.ply.zip)

**Comment by mcallieri** [comment]
the problemis the PLY file. the hedear says there are 64518 faces, but if you count them, there are only 64517 
So, the files ends prematurely :) :)
If you just add a new face at the end of the file, it works. Check your exporter.
Be also careful with winding, odd and even triangle have opposte winding, resulting in a mess of normals.
