### ISSUE TITLE
Error compiling meshlab, related to vcglib

### ISSUE THREAD

**Issue by aniketkt** [cnr-isti-vclab/meshlab#438]
While compiling meshlab, I get the following error. Looks like it's coming from a file smooth.h for the function "ForEachTetra"...

Any help would be appreciated!

../../../../vcglib/vcg/complex/algorithms/smooth.h:261:10: error: no matching function for call to ‘ForEachTetra(vcg::tri::Smooth<CMeshO>::MeshType&, vcg::tri::Smooth<SmoothMeshType>::AccumulateLaplacianInfo(vcg::tri::Smooth<SmoothMeshType>::MeshType&, vcg::SimpleTempData<typename SmoothMeshType::VertContainer, vcg::tri::Smooth<SmoothMeshType>::LaplacianInfo>&, bool) [with SmoothMeshType = CMeshO; vcg::tri::Smooth<SmoothMeshType>::MeshType = CMeshO; typename SmoothMeshType::VertContainer = vcg::vertex::vector_ocf<CVertexO>]::__lambda26)’
         });
          ^

**Comment by mcallieri** [comment]
Are you using the "devel" branch of VCG, as explained in the readme?

**Comment by sariyanidi** [comment]
I get the same error. I did use the devel branch of VCG
