### ISSUE TITLE
Meshlab 2016.12: Poisson doesn't show up in the filters on Linux

### ISSUE THREAD

**Issue by Zoodinger** [cnr-isti-vclab/meshlab#44]
I can find the new Poisson filter when installing Meshlab on Windows. However, this option is not available on Linux (CentOS 7, using Qt 5.7 and GCC 4.8.5). The only plugin that failed to compile is filter_csg.

**Edit:** Poisson reconstruction appears in the list in Plugin Info, but it has no sub-items and shows no information. When running the executable from the terminal, I get the following when clicking on the specific plugin:
```
Trying to load the plugin '<omitted>/meshlab/src/distrib/plugins/libfilter_screened_poisson.so'
The device must be readable.
```

**Comment by granzuglia** [comment]
that's not just the Poisson filter you are not able to see...
move the files
- src\meshlabplugins\filter_measure\filter_measure.xml
- src\meshlabplugins\filter_mutualinfoxml\filter_mutualinfo.xml
- src\meshlabplugins\filter_screened_poisson\filter_screened_poisson.xml

into src\distrib\plugins.
Magically you will find all the things you needed...
It's just cause of my phobia to maintain not easy to access some really powerful features of MeshLab...
Can you open a new topics explaining me why you cannot compile filter_csg? Thanks

**Comment by Zoodinger** [comment]
Alright, thanks for that. It does recognise it now, but Meshlab crashes when trying to run it. First, it fails to recognise the symbol omp_get_num_procs(). Hard-coding it to 1 allows it to proceed a little further, but then it crashes on GOMP_parallel_start (undefined symbol).

Unfortunately my distro uses a very old GCC version which currently supports 4.8.5 GCC which is bundled with an equally ancient OpenMP release (3.1). I suppose I will have to update something before this can work.

**Comment by eboudrand** [comment]
@Zoodinger the crash is due to a lack of `-fopenmp` and `-lgomp` in compiler and linker directives. For details see pull request https://github.com/cnr-isti-vclab/meshlab/pull/55
