### ISSUE TITLE
builing an AppImage for linux distros

### ISSUE THREAD

**Issue by pr0m1th3as** [cnr-isti-vclab/meshlab#442]
Would it be possible to provide an AppImage for the latest release of Meshlab?
Thanks

**Comment by alemuntoni** [comment]
AppImage are now available in the release tab!

**Comment by alexenglish** [comment]
Is it possible to launch the server using the appimage?

**Comment by alemuntoni** [comment]
Right now meshlabserver it's inside the AppImage, so the only way to access to it is to unpack the AppImage (or just download the portable archive).
Releasing an AppImage of meshlabserver is in the todo list!

**Comment by alemuntoni** [comment]
@alexenglish I just uploaded the meshlabserver AppImage!
