### ISSUE TITLE
Initial view of imported mesh incomplete; completes upon changing bounding box/points/wireframe/vert/face mode.

### ISSUE THREAD

**Issue by bersbersbers** [cnr-isti-vclab/meshlab#448]
Start a new project, import this mesh:

```
solid RCS
facet normal 0 0 1
    outer loop
        vertex 1 1 0
        vertex 1 2 0
        vertex 2 1 0
    endloop
endfacet
facet normal 0 0 0
    outer loop
        vertex 0 0 0
        vertex 0 0 0
        vertex 0 0 0
    endloop
endfacet
facet normal 0 0 1
    outer loop
        vertex 1 2 0
        vertex 2 2 0
        vertex 2 1 0
    endloop
endfacet
facet normal 0 0 1
    outer loop
        vertex 2 3 0
        vertex 2 2 0
        vertex 1 2 0
    endloop
endfacet
endsolid RCS
```
You should see three triangles. Instead, you see a square composed of only two triangles. The third triangle appears only after you change one of bounding box/points/wireframe/vert/face modes - then, the view completes correctly.

My file has one zero triangle (normal vector and vertices all zero), which is not at the end. This is crucial to reproduce this issue.

After some experimentation, I have found that if you don't concentrate the zero triangles at the end, if x% of all triangles are zero, then the last roughly x% of the non-zero triangles will be missing from the initial view. This does not seem to depend on preprocessing. Also, this concerns only the initial view for some reason.

Windows 10 3D Viewer displays the same file fine.

**Comment by bersbersbers** [comment]
Haven't used meshlab in a while.

**Comment by bersbersbers** [comment]
Since there was no release since reporting this, I'd suppose this issue still exists.

**Comment by alemuntoni** [comment]
RCS format is not supported by meshlab. How is it possible that you are importing that file?

**Comment by bersbersbers** [comment]
This issue is old. I don't remember which version of MeshLab I was using at the time, but I just confirmed that the file shown above can be read as a `.stl` file in MeshLab 2016.12.

**Comment by bersbersbers** [comment]
Opening the file in MeshLab 2016.12 asks to "unify duplicated vertices". Choose "yes" to reproduce the bug there.

**Comment by bersbersbers** [comment]
This file reproduces the same bug in 2016.12, but not in 2020.07. So this is probably solved:

```
solid STL generated by MeshLab
  facet normal  0.000000e+00  0.000000e+00 -1.000000e+00
    outer loop
      vertex   1.000000e+00  1.000000e+00  0.000000e+00
      vertex   1.000000e+00  2.000000e+00  0.000000e+00
      vertex   2.000000e+00  1.000000e+00  0.000000e+00
    endloop
  endfacet
  facet normal  0.000000e+00  0.000000e+00  0.000000e+00
    outer loop
      vertex   0.000000e+00  0.000000e+00  0.000000e+00
      vertex   0.000000e+00  0.000000e+00  0.000000e+00
      vertex   0.000000e+00  0.000000e+00  0.000000e+00
    endloop
  endfacet
  facet normal  0.000000e+00  0.000000e+00 -1.000000e+00
    outer loop
      vertex   1.000000e+00  2.000000e+00  0.000000e+00
      vertex   2.000000e+00  2.000000e+00  0.000000e+00
      vertex   2.000000e+00  1.000000e+00  0.000000e+00
    endloop
  endfacet
  facet normal  0.000000e+00 -0.000000e+00 -1.000000e+00
    outer loop
      vertex   2.000000e+00  3.000000e+00  0.000000e+00
      vertex   2.000000e+00  2.000000e+00  0.000000e+00
      vertex   1.000000e+00  2.000000e+00  0.000000e+00
    endloop
  endfacet
endsolid vcg
```
