### ISSUE TITLE
Not Responding opening large ASC file type of building scan 

### ISSUE THREAD

**Issue by meshlabMauk** [cnr-isti-vclab/meshlab#457]
Importing a large (28GB) asc file type. Scan of a building
By continually spinning / moving the trackball, using a mouse, Meshlab updates the number of vertices that were loaded giving and indication that the import was still in progress.
Was able to load up to roughly 38-million vertices before the program locks up.
Lock up meaning the trackball no longer moves and the vertices stop updating.
Blue circle spins and then the screen grays out after trying to rotate the trackball again with the only option remaining is to close the window.
Repeated the process above three times on two separate files.
I have used smaller asc files from this vendor and opened, normalized points, meshed,  successfully.
![20910604 ML Screenshot](https://user-images.githubusercontent.com/51385458/58916948-b47beb00-86ea-11e9-82ac-5c3986dd1cd2.JPG)
![sytem info](https://user-images.githubusercontent.com/51385458/58917008-d83f3100-86ea-11e9-80ea-7b626e7fb738.JPG)
Nvidia P1000 video card

**Comment by martin-frbg** [comment]
How long did you wait for the program to recover ? Once it has read all vertices, meshlab will probably try to remesh the whole thing and/or convert it to its internal representation.
