### ISSUE TITLE
terminate called after throwing an instance of 'MLException'   what():  MLSceneGLSharedDataContext: GLEW initialization failed  Aborted (core dumped)

### ISSUE THREAD

**Issue by archenroot** [cnr-isti-vclab/meshlab#458]
I am on Xeon based workstation with 2 Nvidai 1080 ti and tried old meshlab 2016 latest release and also latest beta 2019 available and both throwing on start following error:
```
   Reading Param with name MeshLab::System::maxGPUMemDedicatedToGeometry : RichInt
    Reading Param with name MeshLab::System::maxTextureMemory : RichInt
    Reading Param with name MeshLab::System::minPolygonNumberPerSmoothRendering : RichInt
    Reading Param with name MeshLab::System::perBatchPrimitives : RichInt
Shader directory found '/usr/share/meshlab/shaders', and it contains 19 gdp files
terminate called after throwing an instance of 'MLException'
  what():  MLSceneGLSharedDataContext: GLEW initialization failed

Aborted

```
I found some older thread saying guy was having driver mismatch, but my drivers works, I have no error messages in dmesg regarding nvidia, also cuda works just fine.

**Comment by archenroot** [comment]
I reinstalled drivers and rebooted, still no help, I am on Gentoo system on wayland Plasma or LXDE

**Comment by Uio96** [comment]
Same issue reported.

**Comment by xinyazhang** [comment]
@archenroot @Uio96 
A temporary solution is to run meshlab with `QT_QPA_PLATFORM=xcb`.
The reason is the current glew has poor support of Wayland, and cannot load GL function pointers properly.

**Comment by emil-perhinschi** [comment]
might be related: 

running with the proprietary AMD drivers on Linux Mint 20.2
kernel "Linux home 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux" 

getting this: 
```
emilper@home:~$ QT_QPA_PLATFORM=xcb meshlab
qt5ct: using qt5ct plugin
Current Plugins Dir is: /usr/lib/x86_64-linux-gnu/meshlab/plugins 
qt5ct: D-Bus global menu: no
Shader directory found '/usr/share/meshlab/shaders', and it contains 19 gdp files
Unrecognized OpenGL version
Unrecognized OpenGL version
terminate called after throwing an instance of 'MLException'
  what():  MLSceneGLSharedDataContext: GLEW initialization failed
```
