### ISSUE TITLE
MeshLab's quadric edge collapse decimation is much faster than the VCGlib's example source code

### ISSUE THREAD

**Issue by MyEvolution** [cnr-isti-vclab/meshlab#461]
I want to add the meshlab's decimation source code to my project, and I find that the meshlab's decimation is based on the VCGlib, but the desktop-version-meshlab's decimation is much faster than the VCGLib. Why? Does the meshlab's source code use more concurrent tech? But it looks like that they are the same.

**Comment by jmespadero** [comment]
Are you sure that you have compiled your VCGlib decimation code with same optimization options than meshlab?
