### ISSUE TITLE
Unable to build meshlab on centos 7.6

### ISSUE THREAD

**Issue by lpouillo** [cnr-isti-vclab/meshlab#462]
Hello,

I am trying to build meshlab on Centos 7.6, following instructions given by the README.md
I have used the instructions from travis build system but I have an error at the last step 

```
cleanfilter.cpp:362:47:   required from here
../../../../vcglib/vcg/complex/algorithms/update/texture.h:173:4: error: no matching function for call to 'ForEachVertex(CMeshO&, vcg::tri::UpdateTexture<ComputeMeshType>::WedgeTexMergeClose(ComputeMeshType&, vcg::tri::UpdateTexture<ComputeMeshType>::ScalarType) [with ComputeMeshType = CMeshO; vcg::tri::UpdateTexture<ComputeMeshType>::ScalarType = float]::__lambda27)'
```
I have tried to change the version of the vcglib by using the b320f95ed72d2eda6e2344fa72fba29988310e07 commit from the devel branch which corresponds to the latest successful travis build but it does not change the compilation error.

Do you have any idea on how to solve this issue ?
OS : Centos 7.6
compiler : gcc 4.8.5
qt : QMake version 3.1 Using Qt version 5.9.2

Tell me if you need more information.

Regards,

Laurent

**Comment by alemuntoni** [comment]
I'll close this issue since it refers to an old and not anymore supported ubuntu version.
Feel free to open another issue if the problem persists in newer versions.
