### ISSUE TITLE
How to import a ply file containing edge information

### ISSUE THREAD

**Issue by yountreeg** [cnr-isti-vclab/meshlab#464]
when i import a ply file, i only can operate points and faces. But when i import a ply file containing edge information, how to only display color of edge?

For example, the following ply file contains index of edge and color of edge.but i can't display edge in MeshLab.
```
ply
format ascii 1.0
comment author: Greg Turk
comment object: another cube
element vertex 8
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element face 7
property list uchar int vertex_index
element edge 5
property int vertex1
property int vertex2
property uchar red
property uchar green
property uchar blue
end_header
0 0 0 255 0 0
0 0 1 255 0 0
0 1 1 255 0 0
0 1 0 255 0 0
1 0 0 0 0 255
1 0 1 0 0 255
1 1 1 0 0 255
1 1 0 0 0 255
3 0 1 2
3 0 2 3
4 7 6 5 4
4 0 4 5 1
4 1 5 6 2
4 2 6 7 3
4 3 7 4 0
0 1 255 255 255
1 2 255 255 255
2 3 255 255 255
3 0 255 255 255
2 0 0 0 0
```
If you have any suggestions, please share with me.Best wishes!

**Comment by jmespadero** [comment]
Please see if this helps...

https://stackoverflow.com/questions/47365731/how-to-draw-lines-in-ply-files-using-meshlab/58648176
