### ISSUE TITLE
[Ubuntu - Snap] Can't open any file on external hard drive

### ISSUE THREAD

**Issue by fishcu** [cnr-isti-vclab/meshlab#466]
MeshLab 2016.12 release on Ubuntu 16.04.
Problem: MeshLab won't open any .PLY files on any external hard drive. I have tested two different drives, and the issue is the same. I have tested if the .PLY file is valid: It is -- when I copy it to the internal hard drive, it will open fine.

The exact error reported by MeshLab upon trying to open the .PLY is:
```
While opening: '/media/user/external_hd/model.ply'

Error encountered while loading file:
"/media/user/external_hd/model.ply"

Error details: Can't open file
```

I have attached an example .PLY file that exhibits the problem when copied to an external drive.
[model.ply.zip](https://github.com/cnr-isti-vclab/meshlab/files/3397273/model.ply.zip)

**Comment by fishcu** [comment]
Bump. I'm still facing this issue.

**Comment by ValentinSteiner** [comment]
I had the same issue (also Meshlab 2016.12 running on Ubuntu 16.04). I couldn't open a file under `/mnt`. I had installed Meshlab using Snap. This is the crucial point.

Snap has a security model (confinement) which restricts the app from seeing directory contents and opening files.

Snaps can be configured to have access to removable media and other locations, so I think this could be solved by changing the Snap package.

For now, we can install Meshlab using the _devmode_, which disables confinement. The application will then have file permissions as if it was installed using apt (see https://tutorials.ubuntu.com/tutorial/advanced-snap-usage#3).

`sudo snap install --devmode meshlab`

This solved the problem for me, I can now see and open files under `/mnt` and `/media`.

**Comment by hiyyg** [comment]
I also have this problem usng the one installed by snap, but the one installed by apt is fine.

**Comment by saltynexus** [comment]
I faced the same issue with the default install. Solution by @ValentinSteiner seems to have resolved the issue.

**Comment by alemuntoni** [comment]
Right now, the removable-media interface for snap is enabled (see [here](https://github.com/cnr-isti-vclab/meshlab/blob/e447d7239948bfcd75f6645d721ca3e1eafdc7cb/snapcraft.yaml#L20)), and I thought this solved the problem... I am really not a snap expert and I have not found any other solutions for this issue. If someone could point to a solution or make a PR would be really appreciated!

**Comment by christian-rauch** [comment]
The snap confinement is also an issue for me, as I am often drag&drop files from `/tmp`.

@alemuntoni Would it be possible to integrate [`xdg-desktop-portal` support](https://forum.snapcraft.io/t/xdg-desktop-portals/17331) to allow opening files from outside the confined paths?

**Comment by alemuntoni** [comment]
Hi @christian-rauch, thanks for the tip on xdg-desktop-portal. However, it seems not to be an easy fix (as I said before, I am not a snap guru and I don't use it on linux).
I am quite busy right now, therefore I won't be able to integrate it anytime soon.
In any case, PRs are welcome :)

**Comment by SebastianGrans** [comment]
After some googling I found [these](https://snapcraft.io/docs/snap-confinement) [two](https://snapcraft.io/docs/snap-confinement) pages. 

Running `snap info --verbose meshlab` tells us that meshlab is runing in strict confinement. 
>  ..., strictly confined snaps can not access your files, network, processes or any other system resource without requesting specific access via an interface 

If we look at which interfaces meshlab is connected to, we find: 
```
> snap connections meshlab   
Interface        Plug                     Slot     Notes
home             meshlab:home             :home    -
[...]
removable-media  meshlab:removable-media  -        -
```
`meshlab:home` is connected to `:home` meaning that it has "access non-hidden files in the home directory", while `meshlab:removable-media` isn't connected. 

As [described](https://snapcraft.io/docs/removable-media-interface) `:removeable-media`  "allows read/write access to mounted removable storage in `/media`, `/run/media` and `/mnt`." 

I have additional hard drives mounted in `/mnt`, and USB drives are mounted in `/media` when plugged in, so after running:
```
sudo snap connect meshlab:removable-media
``` 
Files from external/additional drives are now openable!

**Comment by alemuntoni** [comment]
Hi @SebastianGrans, thanks for the deepening.
However, looking for example on the VLC snap package, the "Read/write files on removable storage devices" option is enabled by default. [This](https://github.com/videolan/vlc/blob/a708c988091d6bc770212f5deeaba45e2395f4b2/extras/package/snap/snapcraft.yaml#L28) is their snap yaml script.

On MeshLab's snap script there is the option "removable-media" ([here](https://github.com/cnr-isti-vclab/meshlab/blob/cfaa0bdd8b0e2d33218fc633ece100511564ff1f/snapcraft.yaml#L20)), however the option is not enabled by default. I really cannot understand why and what is the difference between the vlc's and the meshlab's snap script.

**Comment by masterjuggler** [comment]
How would you enable access to other mounted partitions? I have other hard drives in my system that are mounted, and snap doesn't seem to respect soft links to my home directory.

**Comment by alemuntoni** [comment]
We are dismissing the snap package in favor of the [flatpack package](https://flathub.org/apps/details/net.meshlab.MeshLab), which works better.
Maintain also the snap package (which breaks constantly and have a lot of small problems, like the one described in this issue) with our resources has become impossible to us. 
If someone wants to help us maintaining the snap package of MeshLab, is welcome of course. In the meantime, we suggest to switch to the flatpack, which will be update along with the official releases of MeshLab.
