### ISSUE TITLE
Meshlab 2016.12: CSG plugin does not compile on linux with final link error

### ISSUE THREAD

**Issue by Zoodinger** [cnr-isti-vclab/meshlab#47]
In the other topic I was asked to start a new topic with this issue. This is the log I get when trying to compile the CSG plugin:
```
g++ -Wl,-O1 -Wl,-rpath,/opt/Qt/5.7/gcc_64/lib -shared -o libfilter_csg.so filter_csg.o moc_filter_csg.o  -L../../distrib -lcommon -lGLU ../../external/lib/linux-g++/libmpirxx.a ../../external/lib/linux-g++/libmpir.a -L/opt/Qt/5.7/gcc_64/lib -lQt5OpenGL -L/usr/lib64 -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5XmlPatterns -lQt5Network -lQt5Script -lQt5Core -lGL -lpthread  
/bin/ld: ../../external/lib/linux-g++/libmpir.a(lt4-clear.o): unrecognized relocation (0x2a) in section `.text'
/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [../../distrib/plugins/libfilter_csg.so] Error 1
make[1]: Leaving directory `<omitted>/meshlab/src/meshlabplugins/filter_csg'
make: *** [sub-meshlabplugins-filter_csg-make_first-ordered] Error 2
```
Not an expert in this kind of error, but my wild guess would be there's probably something wrong with one of the libraries it's trying to link against, and possibly not an error on meshlab's end.

**Comment by granzuglia** [comment]
LibMpir is an external library that could be a little tricky to compile (that's particularly true on Windows...a lot easier on Linux), so we provide inside the MeshLab source code an already compile version of the library itself. Obviously that approach could be dangerous, considering the wide range of the compilers existing. If you are interested in the plugin I suggest you to:
- download the mpir 2.4.0 source code from the mpir official site http://mpir.org/downloads.html
- call ./configure --enable-cxx --enable-static --with-pic in the extracted library folder
- call ./make
- move the generated mpir.h and mpirxx.h in src\external\inc\linux-g++\mpir-2.4.0
- move the static libs libmpir.a and libmpirxx.a in src\external\inc\linux-g+(be careful the files are compiled in a hidden folder if you have the "don't show hidden folders" file browser option set to true you can waste an afternoon, as it happens to me, to find the compiled libs :D )
- try to compile again the filter_csg plugin in MeshLab

Let me know if you have still problems.

**Comment by DBobkov** [comment]
Does it make sense to add this info to the readme containing installation instructions?

**Comment by cignoni** [comment]
See #74 #
