### ISSUE TITLE
MeshLab latest version for MacOS does not work on MacOS Catalina

### ISSUE THREAD

**Issue by enzyme69** [cnr-isti-vclab/meshlab#470]
I tried running the app on MacOS Catalina Beta 4 and so far has been failing because it keep saying: developer needs to update the app and its integrity cannot be accepted. App failed to run. Any newer built that runs on MacOS Catalina? Thanks!

**Comment by enzyme69** [comment]
<img width="425" alt="Screen Shot 2019-07-28 at 12 30 23 pm" src="https://user-images.githubusercontent.com/3952687/62001424-8c7d9680-b133-11e9-8696-15e7a9ba634e.png">

@cignoni Is there a newer built that works with MacOS Catalina?

**Comment by alemuntoni** [comment]
I'll close this issue since it has been fixed. You can find a properly signed and notarized MeshLab version in the last [release](https://github.com/cnr-isti-vclab/meshlab/releases).
