### ISSUE TITLE
How to select multiple layers at the same time and change their visibility

### ISSUE THREAD

**Issue by tlsshh** [cnr-isti-vclab/meshlab#471]
I have 20 layers of .obj files. I want to make some of them visible, while others are not visible. Setting it up one by one is not convenient because I have to change the visibility multiple times. I want to know, can I select multiple layers at the same time and change their visibility at the same time?

**Comment by mcallieri** [comment]
unfortunately, no.
In the current beta, we are testing a feature for creating "visibility states": i.e. you may store and then recall specific visibility sets. But it is experimental.
