### ISSUE TITLE
This application has requested the runtime to terminate it in an unusual way..!

### ISSUE THREAD

**Issue by PedroMug** [cnr-isti-vclab/meshlab#472]
Hola. Intento ejecutar MeshLab 32 bits en mi PC con Windows 7 (32 bits) Inter Core 3i  c/ 32Gb de RAM pero al hacerlo me da un mensaje de error:

Mocrosoft Visual C++ Runtime Library:
This application has requested the runtime to terminate it in an unusual way. pleace contact the aplication support team for more information

Intente actualizando los update pero asi y todo no pedo hacer que funcione.
Busque en los temas del foro, pero no hay caso. No hay modo de hacer que funcione.
Necesito hacer conversión directa de mallas 3D al formato U3D y creo que este programa podría servirme, pero...
Agradeceré cualquier ayuda que puedan darme.
Atte

**Comment by mcallieri** [comment]
MeshLab 32bit is not supported anymore. PC with 32 bit O.S. have gone out of the market years ago, and does not make sense to support them anymore.
By the way, how the hell are you using 32GB of ram with a 32bit operating system?
