### ISSUE TITLE
Failing to compile AUR package on ArchLinux

### ISSUE THREAD

**Issue by blegat** [cnr-isti-vclab/meshlab#473]
I get the following error when trying to compile meshlab on ArchLinux with [the AUR package](https://aur.archlinux.org/packages/meshlab/). Is
```
/usr/bin/ld: ../distrib/libcommon.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
```
The qt version used is v5.13:
```
pacman -Qs qt5-base
local/qt5-base 5.13.0-7 (qt qt5)
    A cross-platform application and UI framework
```
there seems to be a discussion on the AUR package comments dating back to 2018 about issues with newer qt versions but I don't know if this is related.

**Comment by jjerphan** [comment]
I do have the same problem on Fedora. Do you by any mean use Anaconda's distribution of Python? This might be linked to the fact that qt5 is distributed in it.

**Comment by jjerphan** [comment]
The implementation of `std::string` changed with C++11.

> In the GCC 5.1 release libstdc++ introduced a new library ABI that includes new implementations of std::string and std::list. These changes were necessary to conform to the 2011 C++ standard which forbids Copy-On-Write strings and requires lists to keep track of their size. 

See [this document](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html).

See [this issue](https://github.com/preshing/junction/issues/37).

**Comment by rpavlik** [comment]
I'd suggest trying the CMake build, which was designed with packagers in mind, and thus will try to find system copies of libraries instead of pre-compiled, bundled binaries.
