### ISSUE TITLE
Mac version needs to be signed properly

### ISSUE THREAD

**Issue by UiharuKazari2008** [cnr-isti-vclab/meshlab#477]
When you launch Meshlab in a modern version of MacOS you can not launch it because its not signed properly and you have to manually go to the application and right click and select open to override the signature verification. The average user would simply assume the application is broken so it would be helpful if it could be signed by a proper apple certificate so it can actually launch. 

<img width="532" alt="Screen Shot 2019-08-27 at 15 28 21" src="https://user-images.githubusercontent.com/15165770/63802109-dfd43780-c8df-11e9-808e-d5771776b4b0.png">

**Comment by vtsgarbee** [comment]
+1. I'm having the same issue on my company laptop, with no possibility of disabling any safety feature. I'm currently forced to use meshlab through a virtual machine, which is terrible.

**Comment by UiharuKazari2008** [comment]
You can bypass the security by using 
sudo spctl --master-disable
I do not suggest leaving this disabled as it can open your system to a security risk but its a option that works. You may still have to right click and select open the first time to get it too allow the application

**Comment by vtsgarbee** [comment]
Already tried this, sadly I get no Open button, nor in Settings > Security and Privacy. I involved the ITs too - no luck. Thanks anyway

**Comment by UiharuKazari2008** [comment]
ah then I may be using the old authorization from Mojave 
This could have been avoided if they had just signed the application with a apple developer certificate. Could try to load it in Xcode and recompile it with a proper certificate that apple gives for free

**Comment by BenFranzi** [comment]
Hold option while you double click

**Comment by alemuntoni** [comment]
I'll close this issue since it has been fixed. You can find a properly signed and notarized MeshLab version in the last [release](https://github.com/cnr-isti-vclab/meshlab/releases).
