### ISSUE TITLE
Poisson crash on MacOS Sierra, OK on El Capitan

### ISSUE THREAD

**Issue by relevi** [cnr-isti-vclab/meshlab#48]
I have installed december 2016 release on a Mac Pro (2008) running El Capitan, and on a MacBook Pro (2011) running Sierra. Even with the simplest number of vertices the new Screened Poisson filter crashes on Sierra and not in El Capitan. Could it be a QT issue? 
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
Renzo

**Comment by relevi** [comment]
New test: if I launch meshlab from command line directly Poisson does not crash even in Sierra.
Strange
If I launch from command line meshlabserver I get:
dyld: Library not loaded: @rpath/QtOpenGL.framework/Versions/5/QtOpenGL
  Referenced from: /Applications/meshlab.app/Contents/MacOS/meshlabserver
  Reason: image not found
Abort trap: 6

**Comment by omhafez** [comment]
To resolve your second message, the following works for me on MacOS Sierra. Make the following call first (one line):

cd /Applications/meshlab.app/Contents/MacOS/ && install_name_tool -add_rpath "@executable_path/../Frameworks" meshlabserver && cd -

**Comment by alemuntoni** [comment]
I'll close this issue since it should be fixed with the last PRs.
Feel free to open another issue if the problem persists.
