### ISSUE TITLE
io_ctm.obj : error LNK2019

### ISSUE THREAD

**Issue by easterngarden** [cnr-isti-vclab/meshlab#480]
Hi,

I downloaded latest meshlab (master) and vcglib (devel) source codes from github. My machine (Windows 10 64 bit )has QT 5.9.8 installed. Follows issue [142](https://github.com/cnr-isti-vclab/meshlab/issues/142) compiling meshlab source codes, got these sort of link errors. Can anyone point out where might be the cause of this issue?

moc_io_ctm.cpp
        link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /DLL /SUBSYSTEM:WINDOWS /OUT:..\..\distrib\plugins\io_ctm.dll @C:\Users\xxx\AppData\Local\Temp\nmB86F.tmp
   Creating library ..\..\distrib\plugins\io_ctm.lib and object ..\..\distrib\plugins\io_ctm.exp
io_ctm.obj : error LNK2019: unresolved external symbol __imp_ctmNewContext referenced in function "public: static int __cdecl vcg::tri::io::ImporterCTM<class CMeshO>::Open(class CMeshO &,char const *,int &,bool (__cdecl*)(int,char const *))" (?Open@?$ImporterCTM@VCMeshO@@@io@tri@vcg@@SAHAEAVCMeshO@@PEBDAEAHP6A_NH1@Z@Z)

**Comment by datased2019** [comment]
Same error info. Any updates?

**Comment by alemuntoni** [comment]
Hi, which version of Visual Studio have you installed?

Right now, the only supported version is visual studio 2015.
I'm working on fixing this and supporting also vs2017 and vs2019, but at the moment the only working version is vs2015.

**Comment by alemuntoni** [comment]
Hi @datased2019, @easterngarden 

Right now, meshlab should compile also with newest MSVC and Visual Studio versions.

**Comment by datased2019** [comment]
@alemuntoni 
:-1: error: dependent '..\..\..\src\external\inc\win32-msvc2008\mpir-2.2.1_x64\mpirxx.h' does not exist.

**Comment by easterngarden** [comment]
My compiler is VS 2017.  @alemuntoni did you fix this issue? If so, please let me knowyour submission or what codes I should update. Thanks.

**Comment by datased2019** [comment]
@alemuntoni 
error: dependent '..\..\..\src\external\inc\win32-msvc2008\mpir-2.2.1_x64\mpirxx.h' does not exist.

**Comment by alemuntoni** [comment]
@easterngarden should be fixed, just pull from the meshlab repo and rebuild again.
@datased2019 did you pull from the meshlab repo? If yes, then clean and rebuld all.
I just double checked and there is no reference to "win32-msvc2008\mpir-2.2.1_x64" inside all the project anymore.

**Comment by datased2019** [comment]
> @easterngarden should be fixed, just pull from the meshlab repo and rebuild again.
> @datased2019 did you pull from the meshlab repo? If yes, then clean and rebuld all.
> I just double checked and there is no reference to "win32-msvc2008\mpir-2.2.1_x64" inside all the project anymore.

Done. Thx a lot for your support. @alemuntoni

**Comment by easterngarden** [comment]
pull meshlab (master) and vcglib (devel), run compilation


pull latest vcglib (devel) and meshlab (master) from github and get compile error below:

@alemuntoni  pull vcglib (devel) and meshlab (master) and got compile error shown blow:
meshio.h(36): Error: Undefined interface
NMAKE : fatal error U1077: 'C:\dev\Qt\5.9.8\msvc2017_64\bin\moc.exe' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.

**Comment by easterngarden** [comment]
@alemuntoni I take it back. The compile error from command line could be due to my setting mess up. I was able to build meshlab succeedfully from Visual Studio 2017. Nice job. Thanks!

**Comment by alemuntoni** [comment]
Great!
