### ISSUE TITLE
meshlab from git and package release defacing the UI in non HiDPI 4K display

### ISSUE THREAD

**Issue by sl1pkn07** [cnr-isti-vclab/meshlab#485]
![Screenshot_20191021_180813](https://user-images.githubusercontent.com/462213/67222763-44b69480-f42e-11e9-9e37-26265f8c5312.png)

builded with Qt 5.14-beta1, also defacing with Qt 5.13

greetings

**Comment by alemuntoni** [comment]
Hi, could you please try the [last appimage](https://github.com/cnr-isti-vclab/meshlab/releases/tag/Meshlab-2020.05) to see if the problem persists?

**Comment by doniom** [comment]
Hello I have the same issue.. with my xps 15 HiDPI 4k display :-(

i use arch meshlab 2020.12-2
https://aur.archlinux.org/packages/meshlab/

**Comment by sl1pkn07** [comment]
> Hi, could you please try the [last appimage](https://github.com/cnr-isti-vclab/meshlab/releases/tag/Meshlab-2020.05) to see if the problem persists?

appimage is not a option for me

greetings
