### ISSUE TITLE
Meshlabserver - export ascii

### ISSUE THREAD

**Issue by vtsgarbee** [cnr-isti-vclab/meshlab#486]
Hey guys, 
I need to batch process a lot of 3d geometries and compute vertex quality values.
Up until now I used to export this data using mehslab and saving a ASCII .ply, but now the process needs to be heavily automated.

Is there any way of exporting an ASCII (preferibly .ply) from meshlabserver? 
I couldn't find a way to do it.

Thanks

**Comment by martin-frbg** [comment]
seems like pull request #445 would add what you want.

**Comment by vtsgarbee** [comment]
Hi Martin, thank you for your reply.

Correct me if I'm wrong - it looks like the pull wasn't merged, right? 
So i have to recompile the whole thing?

**Comment by martin-frbg** [comment]
Yes, very few pull requests got merged lately - this looks more like an internal tool that gets infrequent updates mainly for the specific needs of the archeologists and art historians working with it.

**Comment by vtsgarbee** [comment]
Got it. Let's see how it goes. Thanks!

**Comment by jmespadero** [comment]
This issue can be closed after having #528 merged.
