### ISSUE TITLE
Issue with special character on linux

### ISSUE THREAD

**Issue by DerouineauNicolas** [cnr-isti-vclab/meshlab#487]
The following command fails under ubuntu 16.04 with the latest build of meshlab server:

    meshlabserver -l "/tmp/tmpaa4lopua.txt" -i "/Users/nicolasderouineau/Documents/RedBull_OBJ/Data/Tile_013_022/Tile_+013_+022.obj" -s "/tmp/tmp0lluf41h.mlx"

output:

    CommandLine Syntax Error: please refer to the following documentation for a complete list of the MeshLabServer parameters.
    MeshLabServer version: 2019.10

If I debug the source code from meshlabserver, I see it fails [here](https://github.com/cnr-isti-vclab/meshlab/blob/master/src/meshlabserver/mainserver.cpp#L660) where completecommandlineexp.matchedLength() == 97 and str.length() == 134.

The same command works fine under MacOS.

**Comment by alemuntoni** [comment]
We are going to dismiss meshlabserver in the future, and replace it with [PyMeshLab](https://github.com/cnr-isti-vclab/PyMeshLab). Take a look at it, it should be more flexible to perform the operations that you need!
It is an alpha stage, and we are looking for feedbacks :) If any other issue occurs in PyMeshLab, please open an issue there! :)
