### ISSUE TITLE
Converting model with single mesh to Collada: multiple textures not working

### ISSUE THREAD

**Issue by ConfidantCommunications** [cnr-isti-vclab/meshlab#488]
I am trying to convert a 3DS mesh into a DAE file which can be used in Away3D. When I open it in MeshLab it looks very good, i.e. textures look nice on all sides. Doing a straight conversion to DAE/Collada causes the textures to be scaled wrongly—it looks much different when loaded in Away3D. I suspect that I need to generate UV coordinates. (I tried doing this in Blender but it doesn't work quite as desired.)
I'm not very familiar with MeshLab. When I do Filters > Textures > Parameterization:Flat Plane it gets close but it's a projection so the texture only looks good on front/back and not sides. When I try Parameterization:Trivial Per Triangle it crashes so I can't tell if that's what I even want.

Is there an easy way to bake it so the textures I see in MeshLab will properly export to Collada?
Any ideas are greatly appreciated!

**Comment by jmespadero** [comment]
Please, remember to provide a minimal reproducible example of your data when reporting an issue. People will be better able to provide help if you provide the data that they can use to reproduce the problem.

Also, check if your input mesh has uv coordinates stored in vertex or wedges. This can be know looking for VT or WT flags in the meshlab info panel (right under the number of coordinates and faces in same panel).
You can try to convert from one to another using the filter:texture:convert vertex to wedge coordinates. It is possible that away3D don't support both types of coordinate textures

**Comment by ConfidantCommunications** [comment]
Thanks for your reply. The model is using WT for the record, which is supported by Away3D. 
I have done a lot of exploring and learning since posting this help request. My main problem at this point is having all the adjoining faces of a flat plane reflect diffuse and specular properly. If I remove diffuse and specular lighting everything appears smoothly textured. 

In the attached screen shots I'm using the same model, but different lights make the left side show its triangulation. The model is in the attached zip file.
![Screen Shot 2019-12-05 at 2 26 34 PM](https://user-images.githubusercontent.com/1410814/70271066-4ed8ec00-176b-11ea-8d52-24be7a0865f5.jpg)
![Screen Shot 2019-12-05 at 2 25 34 PM](https://user-images.githubusercontent.com/1410814/70271067-4ed8ec00-176b-11ea-9cb1-5a0bc0e4cc58.jpg)
[Model.zip](https://github.com/cnr-isti-vclab/meshlab/files/3928952/Model.zip)

**Comment by alemuntoni** [comment]
@ConfidantCommunications could please provide the original 3DS file that you used to obtain the model that you attached?

**Comment by ConfidantCommunications** [comment]
Since posting this issue I have worked with an Away3D expert who identified a math bug in the Haxe version of the engine. We have resolved this; thanks for your attention.
