### ISSUE TITLE
Meshlab2016.12 Compilation Errors on Ubuntu16.04...

### ISSUE THREAD

**Issue by jiapei100** [cnr-isti-vclab/meshlab#49]
Hi, to whom it may concern:

I'm trying to recompile meshlab entire package. My environment:
OS: Ubuntu 16.04.1
GCC/G++: 5.4.0

After some modification (I just tried to remove as many external dependent packages as possible, please refer to my fork), I failed to build the following 4 projects of meshlab_full solution, due to some potential reasons:

1. **filter_protosynth**
  QtSoap is NOT compatible with Qt5?

2. **filter_ssynth**
  StructureSynth is NOT compatible with Qt5?

3. **io_ctm**
  OpenCTM is NOT compatible with Qt5?

4. **meshlab**
  **jhead**, if I replace jhead-2.95 with jhead-3.00, and have it successfully built, a static library named "**libjhead.a**". However, when I tried to build project meshlab, I still obtained the following error messages:

- jhead.c:-1: error: multiple definition of `main'
- jpgfile.c:-1: error: undefined reference to `process_DQT'
- jpgfile.c:-1: error: undefined reference to `process_DHT'
- :-1: error: collect2: error: ld returned 1 exit status

So, any suggestions? It looks some of the dependent packages are really really too old, without updating for quite a bit.

**Comment by granzuglia** [comment]
Can you tell me which is your Qt framework version? You need at least Qt 5.6 to compile correctly all the MeshLab plugins. I compiled it successufully with Linux Mint 18, GCC/G++ 5.3.1 and Qt 5.7. If i well remember you have to comment the main function on jhead.c and, probably, you should be able to link it. Please, consider that we assure that MeshLab works and compiles just with Jhead 2.95 version.

**Comment by jiapei100** [comment]
@granzuglia 

Hi, Thank you granzugila.

I'm using Qt 5.7.1, the newester version.

**Comment by cignoni** [comment]
According to Travis https://travis-ci.org/cnr-isti-vclab/meshlab , current repo status of MeshLab correctly compiles on ubuntu and osx 
Please check your configuration against the .travis.yml configuration
