### ISSUE TITLE
PickPoints won't pick points

### ISSUE THREAD

**Issue by SamSwank** [cnr-isti-vclab/meshlab#494]
I'm using MeshLab (2016) to process skeletal CTs on a Windows 10 desktop.  I need to landmark bones on the skeleton and need x,y,z, coordinates, so I was hoping that the PickPoints function would allow me to do this.  I can change the mode in PickPoints and my cursor icon changes, but I can't select anything on my mesh.  I have had the same issue on a Windows 10 laptop and on a Mac Sierra.  Is the function broken?

Thanks.

**Comment by mcallieri** [comment]
the PickPoint filter has Always been erratic. However, it does work on all my machines. Right-click creates a locator.
However, there maybe is a better method. Without opening any plugin, when you double-click on a surface/point, the trackball re-centers on that point, and the coordinates of the clicked point appear in the log window. From there, you may copy-paste in any other tool you might need. Be careful of one thing, to copy from the log window, select the text and right-click then choose copy from the menu. CTRL-C does not work properly.
