### ISSUE TITLE
U3D plugin not in Linux

### ISSUE THREAD

**Issue by ferdymercury** [cnr-isti-vclab/meshlab#497]
Export to U3D does not work in the Linux version. I needed to compile this CMake project https://github.com/ningfei/u3d with CMAKE_INSTALL_PREFIX = /usr
to get the IDTFConverter and the export working.

Shouldn't this be done by default when installing Meshlab?

Or have a folder for Linux here:
https://github.com/cnr-isti-vclab/meshlab/tree/master/src/distrib/plugins

Or at least some instructions when trying to run this export under Linux?

Thanks

See also:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=629171
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=581854
https://sourceforge.net/p/meshlab/bugs/72/

**Comment by alemuntoni** [comment]
Hi @ferdymercury, thank you for reporting it. I'll work on a fix on this.

**Comment by alemuntoni** [comment]
Solved with #557.
