### ISSUE TITLE
How to import a ply file contains ‘ property ushort label’ of vertex  property?

### ISSUE THREAD

**Issue by wusuoweima** [cnr-isti-vclab/meshlab#498]
My ply file's header is as follows:

ply
format binary_little_endian 1.0
comment MLIB generated
element vertex 81369
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
property ushort label
element face 153587
property list uchar int vertex_indices
end_header

Among them, "property ushort label" can not be  recognized , which is the label of per vertex for 3D semantic task. Loading the ply file with meshlab, then export it from meshlab to disk. The header becomes
ply
format ascii 1.0
comment VCGLIB generated
element vertex 81369
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 153587
property list uchar int vertex_indices
end_header

"property ushort label" lost.

![image](https://user-images.githubusercontent.com/30040019/68582752-744d3f80-04b6-11ea-8e05-420710fff2e9.png)

**Comment by wusuoweima** [comment]
@granzuglia @mcallieri @cignoni

**Comment by jmespadero** [comment]
Can you share a minimal .ply file which is not working?

**Comment by jmespadero** [comment]
Ok, here a have one...

```
ply
format ascii 1.0
comment VCGLIB generated
element vertex 15
property float x
property float y
property float z
property ushort label
element face 16
property list uchar int vertex_indices
end_header
0 -0.942809 0 10
0 1.88562 0 10
0.816495 0.471406 0 1
-0.816495 0.471406 0 2
1.63299 -0.942809 0 3
-1.63299 -0.942809 0 4
0 0.648183 0 16
-0.56134 -0.32409 0 5
0.56134 -0.32409 0 6
0.408248 1.35529 0 7
-0.408248 1.35529 0 8
0.969588 -1.0312 0 9
1.37784 -0.32409 0 10
-1.37784 -0.32409 0 11
-0.969588 -1.0312 0 12
3 6 7 8 
3 6 9 10 
3 8 11 12 
3 7 13 14 
3 2 6 8 
3 6 3 7 
3 8 7 0 
3 3 6 10 
3 6 2 9 
3 10 9 1 
3 2 8 12 
3 8 0 11 
3 12 11 4 
3 0 7 14 
3 7 3 13 
3 14 13 5 
```

As I see, the .ply importer is just ignoring every attribute which is not recognized by meshlab.

It is valid for you just renaming the "property ushort label" line to "**property float quality**", as seen here?

```
ply
format ascii 1.0
comment VCGLIB generated
element vertex 15
property float x
property float y
property float z
property float quality
element face 16
property list uchar int vertex_indices
end_header
0 -0.942809 0 10
0 1.88562 0 10
0.816495 0.471406 0 1
-0.816495 0.471406 0 2
1.63299 -0.942809 0 3
-1.63299 -0.942809 0 4
0 0.648183 0 16
-0.56134 -0.32409 0 5
0.56134 -0.32409 0 6
0.408248 1.35529 0 7
-0.408248 1.35529 0 8
0.969588 -1.0312 0 9
1.37784 -0.32409 0 10
-1.37784 -0.32409 0 11
-0.969588 -1.0312 0 12
3 6 7 8 
3 6 9 10 
3 8 11 12 
3 7 13 14 
3 2 6 8 
3 6 3 7 
3 8 7 0 
3 3 6 10 
3 6 2 9 
3 10 9 1 
3 2 8 12 
3 8 0 11 
3 12 11 4 
3 0 7 14 
3 7 3 13 
3 14 13 5 
```

That approach is working for me, as you can see applying a color map using the `Edit->Quality Mapper`
[![enter image description here][1]][1]

If that approach is not valid for you... It would be necessary to change the .ply parser to store properties as meshlab attributes.

  [1]: https://i.stack.imgur.com/cVOFB.png
