### ISSUE TITLE
vcglib as git submodule

### ISSUE THREAD

**Issue by nmellado** [cnr-isti-vclab/meshlab#5]
Dear dev. team,

The connection between vcglib and meshlab is very strong, and require some manual steps when installing the development environment.

Would you consider to add vcglib as a git submodule, so the library is automatically updated, an the right branch is always selected ? This would change a bit the folder structure, since vcg would be included below  the project root folder. 

This requires very few amount of work on the dev. side, but can save a lot of time (see https://github.com/cnr-isti-vclab/meshlab/issues/1#issuecomment-260026093).

Cheers,

**Comment by alemuntoni** [comment]
vcglib is now a meshlab submodule.
