### ISSUE TITLE
Failed to open:  afile.asc on snap version v2016.12 on Ubuntu 18.4

### ISSUE THREAD

**Issue by sennalb** [cnr-isti-vclab/meshlab#509]
I have installed last snap version on Ubuntu 18.4 and I obtain a message error 

While opening: '/home/alsen/MyShare/blob.asc'
Failed to open:/home/alsen/MyShare/blob.asc

when Import Mesh... from File menu.

What is the problem ?
Thanks 
Alberto Senni

**Comment by jmespadero** [comment]
Can you share you blob.asc file here?
