### ISSUE TITLE
[linux] the number of selected components is not displayed

### ISSUE THREAD

**Issue by matthieu-nesme** [cnr-isti-vclab/meshlab#51]
The last line showing the number of selected faces/vertices on the bottom of the screen is not displayed on linux (but it is on windows).

kubuntu 16.04

**Comment by granzuglia** [comment]
mmm...can you give some specs on your system? I tested it in Linux Mint 18, Gcc/g++ 5.3.1 and Qt 5.7 on 1680 * 1050 monitor and It seems to work properly.

**Comment by matthieu-nesme** [comment]
Indeed, my bad, I downloaded the sources of an old version from https://sourceforge.net/projects/meshlab/. I did not notice it was not the last version.
