### ISSUE TITLE
Cannot import an OBJ where there are spaces in texture paths

### ISSUE THREAD

**Issue by sergiobd** [cnr-isti-vclab/meshlab#512]
Hi,

I'm trying to import an .obj file, and I get an error message saying the texture E:\EL is not found.
The path to the texture is E:\EL BEAT\XYZ\... 
So I guess currently texture paths with spaces are not supported...

**Comment by jmespadero** [comment]
Also, don't use backslash like \  use forward slash like /

**Comment by mcallieri** [comment]
Yes, the 2016_12 version has this issue.
The current version of the code should be fixed.
You can try grabbing one of the beta

**Comment by sergiobd** [comment]
Thanks!
