### ISSUE TITLE
-ljhead and [../distrib/meshlab] Error occurred when make!

### ISSUE THREAD

**Issue by zengletian1491** [cnr-isti-vclab/meshlab#519]
vcglib devel branch and meshlab were used. This project was run on ubuntu16.04LTS system.
However, errors occurred when make as follows:
**/usr/bin/ld: cannot find -ljhead
collect2: error: ld returned 1 exit status
Makefile:385: recipe for target '../distrib/meshlab' failed
make[1]: *** [../distrib/meshlab] Error 1
make[1]: Leaving directory '/devel/meshlab/src/meshlab'
Makefile:93: recipe for target 'sub-meshlab-make_first-ordered' failed
make: *** [sub-meshlab-make_first-ordered] Error 2**
The associated solutions in the "Issues" did not work!
Could you please give some suggestions?

**Comment by alemuntoni** [comment]
Hi @zengletian1491, did you first build src/external?
If yes, can you check if the jhead file is inside "src/external/lib/linux-g++"?

**Comment by zengletian1491** [comment]
> Hi @zengletian1491, did you first build src/external?
> If yes, can you check if the jhead file is inside "src/external/lib/linux-g++"?

Yes, it was my first time to build src/external. The jhead file was not inside "src/external/lib/linux-g++",  however, only libmpir.a and libmpirxx.a were in "src/external/lib/linux-g++",

**Comment by alemuntoni** [comment]
That's strange! If there is only libmpir.a it means that external was not compiled in the proper directory. After compiling external, all the libraries files should be inside "src/external/lib/linux-g++".
Some questions to understand where could be the problem:
- Did you compiled everything from command line or QtCreator?
- are you using gcc or clang?

**Comment by jmespadero** [comment]
I ran into same error yesterday building in linux-g++ after a `git pull origin master`. Only files in directory `src/external/lib/linux-g++/` were `libmpir.a` and `libmpirxx.a`, and I had built meshlab several times in same directory previously to `git pull`.

I solved the problem running again the commands:

```sh 
cd external
qmake external.pro && make
cd ..
qmake meshlab_full.pro && make
```

**Comment by rpavlik** [comment]
might be related to the makefile removal to avoid confusing nmake? perhaps that caused the need for a fresh qmake? Or perhaps just the fact that jhead was upgraded into a different directory meant qmake was needed again.

**Comment by alemuntoni** [comment]
I'll close this issue since it should be fixed with the last PR.
Feel free to open another issue if the problem persists.
