### ISSUE TITLE
Plugins in src/fgt?

### ISSUE THREAD

**Issue by rpavlik** [cnr-isti-vclab/meshlab#524]
Looks like they're all at least outdated (old plugin system, etc) - couldn't get any of them to build with CMake anyway. Are these like the ones in unsupported - outdated and probably should be removed since they're in git?

(specifically, this is what I found - directories not mentioned were empty:

- fgt/edit_topo - `edit_topodialog.h:31:10: fatal error: 'QtGui/QApplication' file not found`
- fgt/edit_virtual_scan - lots of build errors
- fgt/filter_decompose - old plugin system
- fgt/filter_gears - old plugin system
- fgt/filter_hqrender - `export_rib.h:58:8: error: no member named 'HasPerVertexColor' in 'CMeshO'`
- fgt/filter_physics - needs ODE, old plugin system,
- fgt/filter_scan_merging - build broken
- fgt/filter_shape - old plugin system, etc.
- fgt/filter_text - can't moc?
- fgt/filter_topo - can't moc?
- fgt/filter_waffle - old plugin system
- fgt/io_renderman - old plugin system

)

**Comment by cignoni** [comment]
Yes, this folder, like unsupported is here only for historical reasons. 
It was the folder used by students many years ago... 
Not deleted only for sentimental reasons. :) 
It could be reasonable to move it under unsupported. And add a Readme...
