### ISSUE TITLE
Meshlab 2016 Windows 10 usage issues

### ISSUE THREAD

**Issue by sian2306** [cnr-isti-vclab/meshlab#53]
On opening the program functionality only lasts for one action (e.g. opening a project), after that the only way to make any action happen (even rotating a mesh) is to do the action then minimise and maximise the screen. When you maximise it again the action has occured. 

I am running on an MSI Dominator Pro with 8GB NVIDIA GeForce, 16GB Ram etc. 

Tried cold restart, reinstall, and using Beta version

**Comment by mcallieri** [comment]
Never heard of such an issue. We are unable to replicate it.
Are you sure you are not using the integrated videocard?

**Comment by mcallieri** [comment]
I closed the topic beause it is inactive from a long time, we had no other reports of this issue, and we cannot replicate it on any of the tens of machines we are using.
