### ISSUE TITLE
Preserve orientation of meshes when adding a new one

### ISSUE THREAD

**Issue by oleg-alexandrov** [cnr-isti-vclab/meshlab#531]
When a mesh is opened, and one spends time zooming in and rotating for inspection, and another mesh is loaded on top of it, all that work is forgotten and the orientation is reset. It would be very helpful to keep existing orientation and zoom level (camera view) when adding a new cloud on top, as resetting to the default has no gain for the user.

**Comment by jmespadero** [comment]
This is discutible. When you load a mesh, meshlab chooses a zoom level that allows to view entire mesh in screen.

 If you move /scale it does not mean than loading a mesh you want to keep that camera position. You probably still want a view that shows both meses.

Anyway is quite easy to save the camera position and restore it after loading a new mesh. In meshlab-2016 the command ctrl-c copies to clipboard the camera settings, and ctrl-v paste the position from clipboard to camera.

Also see https://stackoverflow.com/questions/59326287/meshlab-possible-to-export-import-the-current-camera-configuration

**Comment by oleg-alexandrov** [comment]
Thank you. I ran into those options later. I must say that I find the names "copy shot" and "paste shot" to be unhelpful for what is actually going on, which is saving and restoring the camera view. Also, having the ability to load and save these views to disk, like CloudCompare, could perhaps add to usability. Though it is good to now meshlab at least can handle these somehow.

**Comment by cignoni** [comment]
Camera view can be easily saved/restored on disk. Just paste them into a text file and save it :)

**Comment by jmespadero** [comment]
>  I must say that I find the names "copy shot" and "paste shot" to be unhelpful for what is actually going on, which is saving and restoring the camera view.

You are right on this. I will propose to change the menu to show a better description of its purpose.

**Comment by oleg-alexandrov** [comment]
>
>
> Camera view can be easily saved/restored on disk. Just paste them into a
> text file and save it :)
>
>
Paolo, yes, it did not take me too long to figure that out. :) Yet, I will
argue that for somebody doing a lot of work with meshes, mucking around
with text files and copying and pasting xml snippets around is not as
effective as having camera views being first-order citizens, to be saved to
disk and loaded from disk just as meshes themselves. I understand however
that there is history behind the current approach, and yes, clunky as it
is, it does work. This was a mere suggestion. Thank you for your response.

**Comment by oleg-alexandrov** [comment]
I added the ability to save a view to a file in https://github.com/cnr-isti-vclab/meshlab/pull/541
