### ISSUE TITLE
OpenCTM compilation failed on Windows : error C2491 definition of dllimport function not allowed

### ISSUE THREAD

**Issue by eboudrand** [cnr-isti-vclab/meshlab#54]
I failed to compile OpenCTM on Windows with QtCreator Community 5.7. I am using compilation kit Desktop Qt 5.7.1 MSVC2015_64bit.

14:06:34: Débute : "C:\Qt\Tools\QtCreator\bin\jom.exe" 
	C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
	cl -c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zi -MDd -W3 -w44456 -w44457 -w44458 /Fddebug\openctm.vc.pdb -DUNICODE -DWIN32 -DWIN64 -DQT_GUI_LIB -DQT_CORE_LIB -I..\..\external\OpenCTM-1.0.3 -I. -I..\..\external\OpenCTM-1.0.3\lib -I..\..\external\OpenCTM-1.0.3\lib\liblzma -IC:\Qt\5.7\msvc2015_64\include -IC:\Qt\5.7\msvc2015_64\include\QtGui -IC:\Qt\5.7\msvc2015_64\include\QtANGLE -IC:\Qt\5.7\msvc2015_64\include\QtCore -Idebug -IC:\Qt\5.7\msvc2015_64\mkspecs\win32-msvc2015 -Fodebug\ @C:\Users\EBOUDR~1\AppData\Local\Temp\openctm.obj.9932.16.jom
openctm.c
 ..\..\external\OpenCTM-1.0.3\lib\openctm.c(187): error C2491: 'ctmNewContext': definition of dllimport function not allowed
 ..\..\external\OpenCTM-1.0.3\lib\openctm.c(209): error C2491: 'ctmFreeContext': definition of dllimport function not allowed
 ..\..\external\OpenCTM-1.0.3\lib\openctm.c(228): error C2491: 'ctmGetError': definition of dllimport function not allowed

Apparently, VCG team can compile the sources for Windows. Which kit do you use ? Can you give the compilation log for this file as example ?

**Comment by eboudrand** [comment]
I finally found the cause of the issue. Directive OPENCTM_STATIC was not used. OpenCTM project is contains files with .c suffixes and in OpenCTM.pro OPENCTM_STATIC is defined for QMAKE_CXXFLAGS. The directive will then applied only to cpp suffixes. 

I added this directive in win32-msvc2015 specification and it solves the issue. My patch : 

```
@@ -9,10 +9,11 @@ INCLUDEPATH += ./lib ./lib/liblzma
 win32-msvc2005:QMAKE_CXXFLAGS += /nologo /Ox /W3 /c /DOPENCTM_STATIC /D_CRT_SECURE_NO_WARNINGS 
 win32-msvc2008:QMAKE_CXXFLAGS += /nologo /Ox /W3 /c /DOPENCTM_STATIC /D_CRT_SECURE_NO_WARNINGS 
 win32-msvc2010:QMAKE_CXXFLAGS += /nologo /Ox /W3 /c /DOPENCTM_STATIC /D_CRT_SECURE_NO_WARNINGS
 win32-msvc2012:QMAKE_CXXFLAGS += /nologo /Ox /W3 /c /DOPENCTM_STATIC /D_CRT_SECURE_NO_WARNINGS
 win32-msvc2015:QMAKE_CXXFLAGS += /nologo /Ox /W3 /c /DOPENCTM_STATIC /D_CRT_SECURE_NO_WARNINGS    
+win32-msvc2015:DEFINES += OPENCTM_STATIC
 win32-g++:QMAKE_CXXFLAGS += -O3 -W -Wall -c -std=c99 -pedantic
 win32-g++:DEFINES += OPENCTM_STATIC
 linux-g++:QMAKE_CXXFLAGS += -O3 -W -Wall -c -std=c99 -pedantic
 linux-g++:DEFINES += OPENCTM_STATIC
 linux-g++-32:QMAKE_CXXFLAGS += -O3 -W -Wall -c -std=c99 -pedantic
```

_CRT_SECURE_NO_WARNINGS is also not applied for .c files. I changed ext_common.pri as follow : 

```
@@ -4,8 +4,9 @@ win32-msvc2005:DESTDIR       = $$EXTERNAL_BASE_PATH/lib/win32-msvc2005
 win32-msvc2008:DESTDIR       = $$EXTERNAL_BASE_PATH/lib/win32-msvc2008
 win32-msvc2010:DESTDIR       = $$EXTERNAL_BASE_PATH/lib/win32-msvc2010
 win32-msvc2012:DESTDIR       = $$EXTERNAL_BASE_PATH/lib/win32-msvc2012
 win32-msvc2013:DESTDIR       = $$EXTERNAL_BASE_PATH/lib/win32-msvc2013
 win32-msvc2015:DESTDIR       = $$EXTERNAL_BASE_PATH/lib/win32-msvc2015
+win32-msvc2015:DEFINES += _CRT_SECURE_NO_WARNINGS
 linux-g++:DESTDIR = $$EXTERNAL_BASE_PATH/lib/linux-g++
 linux-g++-32:DESTDIR = $$EXTERNAL_BASE_PATH/lib/linux-g++-32
 linux-g++-64:DESTDIR = $$EXTERNAL_BASE_PATH/lib/linux-g++-64
```

**Comment by mcallieri** [comment]
seems reasonable :)
Start a pull request, and I'll add it. Thanks for your contribution and testing work.

**Comment by eboudrand** [comment]
Ok. I will start a pull request. But I need to understand how to pull a request with only one commit. I will pull this commit : https://github.com/eboudrand/meshlab/commit/3b245d3b4f868553cef74e467ba7927742003aa9

**Comment by eboudrand** [comment]
Just started pull request https://github.com/cnr-isti-vclab/meshlab/pull/58
I finally understood how to send only one commit :)

**Comment by mcallieri** [comment]
should be working, now, can you conform?

**Comment by eboudrand** [comment]
I did a clone from `cnr-isti-vclab:master`  but, now, OpenCTM-1.0.3 has disappeared from external.pro. It was commented in commit https://github.com/cnr-isti-vclab/meshlab/commit/aa32869a11512cf61015a7b73967f8691340050e.

**Comment by cignoni** [comment]
it was a wrong commit. sorry. Corrected. Does it work now?

**Comment by eboudrand** [comment]
Yes. I could compile.
