### ISSUE TITLE
Meshlab documentation

### ISSUE THREAD

**Issue by oleg-alexandrov** [cnr-isti-vclab/meshlab#542]
The meshlab documentation at https://github.com/cnr-isti-vclab/meshlab/tree/master/docs did not see any love for 10 years.

The meshlab.1 and meshlab1.txt docs need to be merged and converted to .md format. 

Same for meshlabserver.1 and meshlabserver.1.txt

The outdated build instructions should be removed, as there is a dedicated document for that, at https://github.com/cnr-isti-vclab/meshlab/blob/master/src/README.md

The link pointing to http://meshlab.sourceforge.net/wiki/ needs to be removed, as it is dead.

The meshlabserver page does not explain at all what meshlabserver is. It is just a copy and paste job from the meshlab page. If I undertand correctly, and that page does not say it, meshlabsever is a batch mesh processing tool, which takes inputs from the command line and outputs files, without starting a GUI. It also needs to explain what functions it supports, how they are invoked, and to document the script it can take as input.

**Comment by martin-frbg** [comment]
>The meshlab.1 and meshlab1.txt docs need to be merged and converted to .md format.

Just in case you are not aware of this - the meshlab.1 is a Unix/Linux "manual page" for the standard `man` (online help) tool and the .1.txt is its (un)formatted text version - converting these to .md format will probably not provide much benefit.

**Comment by oleg-alexandrov** [comment]
Yes,  I am aware that meshlab.1 is a manual page. For it to be useful, it has to be installed in a path where man can find it. I looked at the meshlab code, and I could not find a place where an install tool would copy this doc page to the right place in the system. Also, on my system meshlab is installed, but "man meshlab" returns nothing.

Hence, it looks to me that meshlab.1 is a relic of another era, not updated for 10 years and not installed. 

The current documentation is at: https://github.com/cnr-isti-vclab/meshlab/blob/master/README.md

The build documentation is at: https://github.com/cnr-isti-vclab/meshlab/blob/master/src/README.md

The text in https://github.com/cnr-isti-vclab/meshlab/tree/master/docs is all very old and could as well be wiped or some bits of it appended to the earlier two docs where relevant.

**Comment by oleg-alexandrov** [comment]
I've addressed these with https://github.com/cnr-isti-vclab/meshlab/pull/556 and https://github.com/cnr-isti-vclab/meshlab/pull/558. The file 

  https://github.com/cnr-isti-vclab/meshlab/blob/master/README.md 

now contains all the text from 

  https://github.com/cnr-isti-vclab/meshlab/blob/master/src/readme.txt 

and then some more, but not all stuff from the former, which makes sense on github, would make sense if embedded in the latter, which is meant to be installed to be shipped with the built program. The second one also breaks long line but the first does not. It will take some thinking about how to sort this out, but it is better than before.
