### ISSUE TITLE
Need advice

### ISSUE THREAD

**Issue by NataCalc** [cnr-isti-vclab/meshlab#547]
Dear,

I have stl file with point clouds (vertices and faces, file is included). As you can see, the geometry consists of two layers. The idea is to merge these two layers making sure that while pulling or pushing sample layers will be a unique shell moving as a bulk of material. What would be the best way to do it? Right now I am following steps: resampling, calculate normal, remesh. However, the last step shows not fully meshed geometry (lots of holes, blocks). 

Regards,
Nataliya
[Scaffold_original.stl.zip](https://github.com/cnr-isti-vclab/meshlab/files/4024200/Scaffold_original.stl.zip)

**Comment by NataCalc** [comment]
I am enclosing result of Poisson reconstruction surface which is comparing to original surface mesh. The original surface mesh consists of layers where in MeshLab I want to merge these layers (growing next layer from previous/layers share triangles). As you can see, after the Poisson reconstruction I lost geometrical features. Is there the way to avoid it?
[Original Gibbon Mesh versus MeshLab Poisson Reconstruction Surface                                                          MeshLab.pdf](https://github.com/cnr-isti-vclab/meshlab/files/4033215/Original.Gibbon.Mesh.versus.MeshLab.Poisson.Reconstruction.Surface.MeshLab.pdf)

**Comment by mcallieri** [comment]
GitHub should not be used to ask advices.
The thing you want to achieve is not really a "merging". you are trying to "weld" together different elements, only affecting the contact areas and leaving alone the rest of the objects.
This operation is closer to what is normally called "boolean operations". MeshLab is not good at doing this on a CAD-like surface like this one, you may have better luck in other modeling software, or things like MeshMixer.
One issue is, however, that the different pieces do not touch one another 
In MeshLab, by subdividing the mesh (subdivision: midpoint) to create a lot more points and then using Poisson, I was able to obtain something on the model you linked, but it is a matter of fine tuning how much you subdivide and which poisson depth to use.
Another option is to use an offset surface, i.e. enlarging each part a bit, until they intersect and weld together, this is done using the "uniform mesh resamplig": the first paramter is the resolution of the finnal mesh you need, and the offset is how much you want to enlarge each surface to to meet the other one.  beware, in this way you are altering the size of the elements.

**Comment by NataCalc** [comment]
J'ai partagé un élément avec vous :

Scaffold_original.stl.zip
https://drive.google.com/file/d/14wKSb0kb9KjAu3rr9MM6HpUAJSdgKgUH/view?usp=sharing&ts=5e1baa0a

Ce fichier n'est pas une pièce jointe, il est stocké en ligne. Pour  
l'ouvrir, cliquez sur le lien ci-dessus.

Hi Marco,

Thank you for reply. I was exploring your options and I did not have a luck  
so far to obtain good results.

I was trying to uniform mesh resampling with offset between layers  
(overlap) and I got this message:
Failure of filter : 'Uniform Mesh Resampling'
This filter requires a mesh with some faces,
it does not work on PointSet

In enclosed stl files (the size is big and I used google drive to share stl  
file with you)  there are both faces and vertices. Prior to do the uniform  
mesh resampling, I do sampling the geometry. Maybe I have to follow other  
steps?

Rgeards,
Nataliya

**Comment by NataCalc** [comment]
Hi Marco,

In addition to email I sent to you via google drive (sharing stl file), I am sending results of uniform mesh operation (OffsetMesh.png) of original mesh (Original Mesh.png) which consists of overlapping layers.

Regards,
Nataliya
