### ISSUE TITLE
Meshlab tracking users behavior

### ISSUE THREAD

**Issue by oleg-alexandrov** [cnr-isti-vclab/meshlab#549]
Every day meshlab calls home to http://vcg.isti.cnr.it/ with information about how many meshes were loaded and saved by the user. While we live in a culture of mass surveillance, and plenty of spyware is inserted into virtually every closed software we use, I don't appreciate this juvenile attempt at keeping track of what I am doing.

I also question the motivation of this to start with. Meshlab is mature software, after all. Is somebody getting a raise (or getting high) seeing a counter being incremented? Frankly, open-source software should be above such shenanigans.

**Comment by cignoni** [comment]
About motivations. I am a government paid researcher, in a country (Italy) that invests less than other countries in Research . 
Writing and maintaining open source software is NOT a career rewarding activity. Writing papers, applying for grants, teaching, patenting, joining committees are much much more rewarding and accountable activities. So I have to justify the resources and the (little) time I and my lab invest in this project. And these numbers are strongly needed for this. This is something that is neither juvenile nor greed nor ego-promoting. This is something that we need.
Sorry if this is not a perfect world. 

BTW I agree it has to be done in a cleaner and less obtrusive/annoying way, and with a simple opt-out. In the original intentions it should pop up very rarely. We are going to fix it.

**Comment by oleg-alexandrov** [comment]
Thank you for your patient response. I am a government employee myself, supporting a free software package (more niche than meshlab) and I know about the vagarities of funding. 

Yet, a standard way to measure a tool's success is the number of publications and downloads. I would be uncomfortable writing in a funding proposal that "my users opened 1 million meshes last year and saved 0.2 million, and here's the breakdown for osx, windows and linux", based on your tracking. 

Yes, those pop-ups with "giving thanks" and "please upgrade" should be less frequent, and note that the latter one is also wrong (https://github.com/cnr-isti-vclab/meshlab/issues/550). 

It is odd you have the power to change the pop-up text, as it is streamed from your web site. All this logic and text must be in the meshlab code on the user machine. The tool should fetch from your web sever only the string with the latest version.
