### ISSUE TITLE
Meshlab bugging about upgrading

### ISSUE THREAD

**Issue by oleg-alexandrov** [cnr-isti-vclab/meshlab#550]
Every day I get a pop-up asking to upgrade to the latest version. Ironically, I actually run the latest build, and I am told to upgrade to the "new" 2016 version. 

And this bug can't be fixed, since the logic happens on http://vcg.isti.cnr.it/ to which meshlab tells my build version (2020.1) and which decides magically that my version is older than 2016.

**Comment by martin-frbg** [comment]
Probably a duplicate of "critical bug" #328

**Comment by oleg-alexandrov** [comment]
I added a pull request at https://github.com/cnr-isti-vclab/meshlab/pull/552
