### ISSUE TITLE
Meshlab crashes when using screened Poisson filter on Linux

### ISSUE THREAD

**Issue by eboudrand** [cnr-isti-vclab/meshlab#56]
Meshlab crashed when I try to apply Screened Poisson filter. Error message is : 
`./meshlab: symbol lookup error: /home/eric/dev/3D/meshlab/meshlab/src/distrib/plugins/libfilter_screened_poisson.so: undefined symbol: omp_get_num_procs`

I am running Ubuntu 16.04 LTS 64 bit.

OpenMP is installed. I did a ldd to a piece of code based on this [example](http://www.dartmouth.edu/~rc/classes/intro_openmp/hello_world_openmp.html) in which I added a call to omp_get_num_procs() and it worked.
```
$ ldd test_openmp
linux-vdso.so.1 =>  (0x00007ffdefdc0000)
libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f09b86cb000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f09b84ae000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f09b80e4000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f09b7ee0000)
/lib64/ld-linux-x86-64.so.2 (0x000055b34414e000)
```

**Comment by eboudrand** [comment]
A [patch](https://github.com/cnr-isti-vclab/meshlab/pull/55) was proposed but it did not work for me

**Comment by bartoszek** [comment]
Found the solution. Using addition `-fopenmp` flag aside library linking flag `-lgomp` fixes the issue. Unable to explain why exactly.

**Comment by eboudrand** [comment]
I confirm it did not crash when adding `-fopenmp` to `QMAKE_LFLAGS`. I notice that it is already in `QMAKE_CXXFLAGS`  a few lines lower in filter_screened_poisson.pro. According to [libopenmp documentation](https://gcc.gnu.org/onlinedocs/libgomp/Enabling-OpenMP.html), it is a compilation option and linker option also : 

"_To activate the OpenMP extensions for C/C++ and Fortran, the compile-time flag -fopenmp must be specified. This enables the OpenMP directive #pragma omp in C/C++ and !$omp directives in free form, c$omp, *$omp and !$omp directives in fixed form, !$ conditional compilation sentinels in free form and c$, *$ and !$ sentinels in fixed form, for Fortran. The flag also arranges for automatic linking of the OpenMP runtime library (Runtime Library Routines)._ "

`QMAKE_CXXFLAGS += -fopenmp` can be also found in filter_isoparametrization.pro

**Comment by mcallieri** [comment]
I accepted the pull request. Thanks for your contribution and all the testing.
If you confirm it is working now, I will close the issue.

**Comment by eboudrand** [comment]
Screened Poisson is working now. I successfully applied it to a ply file.
