### ISSUE TITLE
Fails displaying mesh

### ISSUE THREAD

**Issue by cdcseacave** [cnr-isti-vclab/meshlab#561]
Any Meshlab edition after v1.33 fails to render some simple meshes like this one:
[scene_mesh_raw.zip](https://github.com/cnr-isti-vclab/meshlab/files/4158773/scene_mesh_raw.zip)

**Comment by mcallieri** [comment]
![Clipboard-1](https://user-images.githubusercontent.com/12409141/73833384-32f4d380-480a-11ea-893f-90020602d468.jpg)
tried on 2016.12 and two other more recent betas
