### ISSUE TITLE
geodesc distance for mesh with holes

### ISSUE THREAD

**Issue by cutenc** [cnr-isti-vclab/meshlab#562]
Does the geodesic distance plugin support mesh with holes? I tried the attached stl file with all geodesic distance plugins, but without success. Just wonder if the algorithm is working for mesh with holes. Thanks.

[geodesic-distance.zip](https://github.com/cnr-isti-vclab/meshlab/files/4163489/geodesic-distance.zip)

**Comment by cignoni** [comment]
yes. btw for nice results you need a good triangulation
