### ISSUE TITLE
Includes problems with MersenneTwister

### ISSUE THREAD

**Issue by osvaldo14** [cnr-isti-vclab/meshlab#565]
When I try to build external.pro with QT there is always an include problem with Mersenne Twister. If I change the relativ path of the include by the absolut path I found another include problem. Have anyone face this problem before ?

#include "../../ThirdPartyCode/MersenneTwister.h": No such file or directory  (Error in Random.h line 8)

**Comment by alemuntoni** [comment]
Hi @osvaldo14, could you please add some other infos? In which platform are you compiling meshlab? 
Are you compiling with QtCreator or running qmake-make from terminal?

**Comment by osvaldo14** [comment]
Hi, I'm currently on a windows 10 with Qt 5.14 (Qt creator 4.11 community) with a MinGW 7.3 compiler
I use Qt creator to build the project

**Comment by alemuntoni** [comment]
Could you please update the meshlab repo (be sure that vcglib is properly downloaded as submodule) and try again to compile?
Please follow these [guidelines](https://github.com/cnr-isti-vclab/meshlab/tree/master/src).
