### ISSUE TITLE
No matching function for call vcg::tri::io::ImporterOUT and NVM  [function :  ReadHeader(fp) ]

### ISSUE THREAD

**Issue by osvaldo14** [cnr-isti-vclab/meshlab#566]
When I build meshlabfull, I got this 2 errors : 

- no matching function for call vcg::tri::io::ImporterOUT <OpenMeshType>::ReadHeader(FILE*&)'

- no matching function for call vcg::tri::io::ImporterNVM <OpenMeshType>::ReadHeader(FILE*&)'
ReadHeader(fp); 

On the files "import_out.h" and "import_nvm.h" on line 91 for both

**Comment by alemuntoni** [comment]
Hi @osvaldo14,
are you compiling with vcglib in the "devel" branch?

**Comment by osvaldo14** [comment]
Hi, to be honest I do not know. Where is why : I've been ask to "debug" a pluggin for meshlab and the project came with a Meshlab "fixed" version that is essential for the pluggin to work (as the previous dev says). So I don't know which version of vcglib came with the meshlab version. Can I know exactly which version is ?

**Comment by osvaldo14** [comment]
I don't know if these can be usefull, but when I try to build external (before full) I needed to comment the structuresynth on the pro file because I cannot succeed to build with the structuresynth directory in it

**Comment by alemuntoni** [comment]
Hi,
I think you didn't clone vcglib at all.
As wrote in [this](https://github.com/cnr-isti-vclab/meshlab/tree/master/src) readme, you should clone [vcglib](https://github.com/cnr-isti-vclab/vcglib) (devel branch), and it should be at the same level of meshlab.

**Comment by osvaldo14** [comment]
I'm sure I don't clone the vcglib, but I'm sure the vcglib forlder in there and at the right place. I see in a forum a patch for vcglib and I try to patch mine. The inital problem is gone but now I got a different problem : A lot (1613) errors, all reguarding an undifined reference to "gl" things like glPolygonMode or glEnable on meshmodel.cpp, trimesh.h etc

With this update do you recommend me to replace my version of vcglib by the devel branch ?

**Comment by alemuntoni** [comment]
There are a lot of missing details here. 
Which one is the plugin that you fixed in your meshlab version? Why it wasn't working? 
How old is the last commit in your meshlab repo?
Did you considered to submit a PR with your "fixed" plugin?
It is just impossible for me to help you running a imprecisely old and modified version of meshlab.

**Comment by osvaldo14** [comment]
I know... and I'm really lost too. The last dev who work on the pluggin did it between 2012 and 2014. The pluggin is SimuVex, it is a "home made" pluggin that have been made here at the university of Geneva. The only things that was given to me is the fact that they needed to do work directly on Meshlab the change things to make their pluggin work, but I don't know where and why. I know the configuration of the previous dev : 

- Windows

- Qt version : 5.4.1 (Qt creator 3.3.2)

- Compiler MSVC 2012

And I got a readME saying that I need to compile the "fixed" version of MeshLab by building first external and then full and after that add the SimuVex pluggin to MeshLab. I'm sorry it is very difficult to explain my problems because I cannot access to anyone who work on the project before...

**Comment by osvaldo14** [comment]
There was no git for the project and with the project folder came both the pluggin and a version of MeshLab

**Comment by alemuntoni** [comment]
Sorry @osvaldo14, but here we give support only for the current versions of MeshLab. 
You are referring to an old version, with errors that cannot be replicated and compiling with an old MSVC compiler.
