### ISSUE TITLE
cannot start meshlab Ubuntu 18.04

### ISSUE THREAD

**Issue by ga74kud** [cnr-isti-vclab/meshlab#568]
I cannot start meshlab:

I use NVIDIA RTX 2070 in Ubuntu 18.04 (Bionic). Cannot solve following issue:

`>>> meshlab`

`
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
QNetworkManagerInterface::QNetworkManagerInterface(QObject*) propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.342\" (uid=1000 pid=20141 comm=\"meshlab \" label=\"snap.meshlab.meshlab (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1136 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
QNetworkManagerInterface::QNetworkManagerInterface(QObject*) nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.342\" (uid=1000 pid=20141 comm=\"meshlab \" label=\"snap.meshlab.meshlab (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1136 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
Current Plugins Dir is: /snap/meshlab/4/bin/plugins 
"Cannot load library /snap/meshlab/4/bin/plugins/libfilter_ssynth.so: (/snap/meshlab/4/bin/plugins/libfilter_ssynth.so: undefined symbol: _ZTIN14StructureSynth5Model9Rendering16TemplateRendererE)"
    Reading Param with name MeshLab::Appearance::backgroundBotColor : RichColor
    Reading Param with name MeshLab::Appearance::backgroundTopColor : RichColor
    Reading Param with name MeshLab::Appearance::baseLightAmbientColor : RichColor
    Reading Param with name MeshLab::Appearance::baseLightDiffuseColor : RichColor
    Reading Param with name MeshLab::Appearance::baseLightSpecularColor : RichColor
    Reading Param with name MeshLab::Appearance::fancyBLightDiffuseColor : RichColor
    Reading Param with name MeshLab::Appearance::fancyFLightDiffuseColor : RichColor
    Reading Param with name MeshLab::Appearance::logAreaColor : RichColor
    Reading Param with name MeshLab::Appearance::pointDistanceAttenuation : RichBool
    Reading Param with name MeshLab::Appearance::pointSize : RichFloat
    Reading Param with name MeshLab::Appearance::pointSmooth : RichBool
    Reading Param with name MeshLab::Appearance::textColor : RichColor
    Reading Param with name MeshLab::Appearance::textureMagFilter : RichEnum
    Reading Param with name MeshLab::Appearance::textureMinFilter : RichEnum
    Reading Param with name MeshLab::Decoration::AreaHistParam : RichBool
    Reading Param with name MeshLab::Decoration::BBAbs : RichBool
    Reading Param with name MeshLab::Decoration::BoxRatio : RichFloat
    Reading Param with name MeshLab::Decoration::CameraFixedScaleParam : RichFloat
    Reading Param with name MeshLab::Decoration::CameraRenderScaleType : RichEnum
    Reading Param with name MeshLab::Decoration::CameraShowCameraDetails : RichBool
    Reading Param with name MeshLab::Decoration::CurvatureLength : RichFloat
    Reading Param with name MeshLab::Decoration::EnableAlpha : RichBool
    Reading Param with name MeshLab::Decoration::FixedHistMaxParam : RichFloat
    Reading Param with name MeshLab::Decoration::FixedHistMinParam : RichFloat
    Reading Param with name MeshLab::Decoration::FixedHistWidthParam : RichFloat
    Reading Param with name MeshLab::Decoration::GridBack : RichBool
    Reading Param with name MeshLab::Decoration::GridColorBack : RichColor
    Reading Param with name MeshLab::Decoration::GridColorFront : RichColor
    Reading Param with name MeshLab::Decoration::GridMajor : RichFloat
    Reading Param with name MeshLab::Decoration::GridMinor : RichFloat
    Reading Param with name MeshLab::Decoration::HistBinNumParam : RichInt
    Reading Param with name MeshLab::Decoration::HistType : RichEnum
    Reading Param with name MeshLab::Decoration::LabelEdgeFlag : RichBool
    Reading Param with name MeshLab::Decoration::LabelFaceFlag : RichBool
    Reading Param with name MeshLab::Decoration::LabelVertFlag : RichBool
    Reading Param with name MeshLab::Decoration::MeshBlendingColor : RichColor
    Reading Param with name MeshLab::Decoration::NormalFaceFlag : RichBool
    Reading Param with name MeshLab::Decoration::NormalLength : RichFloat
    Reading Param with name MeshLab::Decoration::NormalVertFlag : RichBool
    Reading Param with name MeshLab::Decoration::ProjRasterAlpha : RichDynamicFloat
    Reading Param with name MeshLab::Decoration::ProjRasterLighting : RichBool
    Reading Param with name MeshLab::Decoration::ProjRasterOnAllMeshes : RichBool
    Reading Param with name MeshLab::Decoration::SSAORadius : RichFloat
    Reading Param with name MeshLab::Decoration::ShadowIntensityVal : RichDynamicFloat
    Reading Param with name MeshLab::Decoration::ShadowMethod : RichEnum
    Reading Param with name MeshLab::Decoration::ShowAlpha : RichBool
    Reading Param with name MeshLab::Decoration::ShowContourAlpha : RichDynamicFloat
    Reading Param with name MeshLab::Decoration::ShowContourColorMap : RichEnum
    Reading Param with name MeshLab::Decoration::ShowContourFreq : RichFloat
    Reading Param with name MeshLab::Decoration::ShowContourRamp : RichBool
    Reading Param with name MeshLab::Decoration::ShowContourWidth : RichDynamicFloat
    Reading Param with name MeshLab::Decoration::ShowMeshCameras : RichBool
    Reading Param with name MeshLab::Decoration::ShowPerFaceCurvature : RichBool
    Reading Param with name MeshLab::Decoration::ShowPerVertexCurvature : RichBool
    Reading Param with name MeshLab::Decoration::ShowRasterCameras : RichBool
    Reading Param with name MeshLab::Decoration::ShowShadow : RichBool
    Reading Param with name MeshLab::Decoration::TextureFaceColor : RichBool
    Reading Param with name MeshLab::Decoration::TextureStyle : RichBool
    Reading Param with name MeshLab::Decoration::UseFixedHistParam : RichBool
    Reading Param with name MeshLab::GUI::perMeshToolBar : RichBool
    Reading Param with name MeshLab::Plugins::sketchFabKeyCode : RichString
    Reading Param with name MeshLab::System::maxGPUMemDedicatedToGeometry : RichInt
    Reading Param with name MeshLab::System::maxTextureMemory : RichInt
    Reading Param with name MeshLab::System::minPolygonNumberPerSmoothRendering : RichInt
    Reading Param with name MeshLab::System::perBatchPrimitives : RichInt
Shader directory found '/snap/meshlab/4/bin/shaders', and it contains 19 gdp files
Unrecognized OpenGL version
Unrecognized OpenGL version
`

**Comment by alemuntoni** [comment]
There are some missing informations here:
- did you compiled MeshLab or just downloaded?
- where did you downloaded MeshLab? what version?
At the moment, on linux we are deploying only a portable version and an AppImage.
Have you tryed MeshLab2020.02-linux.AppImage that you can download from the [Release Tab](https://github.com/cnr-isti-vclab/meshlab/releases)?
