### ISSUE TITLE
Simple Point Picking Tool

### ISSUE THREAD

**Issue by pr0m1th3as** [cnr-isti-vclab/meshlab#570]
Hi all,
my main usage of MeshLab is picking particular points (landmarks) from skeletal models and saving them in the pp format that although somewhat buggy, it used to work in version 1.3.3 or so. This has been deprecated since in later versions and even in the latest 2020.2 I can't find a simple way to do this task. Hence I am stuck with the older version. Is there any plan to include it again as a simple filter?
I know that I can get around this issue by double clicking on any point in the surface in order to recenter the model and then copy paste the coordinates, but it's not a straight forward method and very inefficient for saving a list of landmarks. Furthermore, the "show normals" option in the deprecated pointpicking tool is very handy for my needs, whereas the work-around does not provide for such visual aid.
Thanks. Best regards,
Andreas

**Comment by aslze** [comment]
I was surprised to find that the Pick Points tool has disappeared in MeshLab 2020. Why is that? I see there is a line commented out in CMakeLists.txt to disable the plugin.

**Please, bring it back**! (unless/until there is something better) It was very useful. I used to export picked points in the XML format it produced for processing in other programs.

**Comment by rpavlik** [comment]
The pick points plugin never got updated for some API changes a while ago, which is why it is disabled in CMake (it doesn't build).

**Comment by pr0m1th3as** [comment]
So, should we assume that another pick point tools is not in any to-do list for future Meshlab development? Should we look for alternative software if we are after this specific task?

**Comment by rpavlik** [comment]
Well, I'm not on the main dev team, I just mostly contribute build fixes from time to time. It may be fairly straightforward to make the porting change, perhaps the folks doing more of the dev weren't aware it was still widely used.

**Comment by cignoni** [comment]
Hi, the main motivation of the removal of the filter is that it was rather prone to crashing and in our (wrong :) ) opinion, not frequently used. Ok for me to re-include it.

**Comment by pr0m1th3as** [comment]
Hi, thanks for your reply and for any initiative to re-include it. This is great news for me, since most of my work (including the software I make) in osteological research is relying on Meshlab for landmark picking. I am really sorry that I don't have the necessary programming skills to contribute to the filters improvement somehow, but I will be delighted to test it and report back any bugs.

If it is easier or faster for your team to make a simpler version (e.g. without templates or undo options) in order avoid to make debugging easier, that would be great as well. The only actual problem with the old version (last working version with pick point filter enabled) is that it takes too much time to calculate each point's coordinates, which I presume is a problem with the filter's underlying code implementation rather computational requirements, since, in newer versions, locating a point when translating the origin is blazing fast. An increase in speed would be very beneficial in our line of work since we usually pick quite a few points from numerous samples (3d models).

An additional minor change that would be beneficial and most likely easy to implement concerns the automatic incremental naming. In the existing filter it starts with '0' and increments +1 for each new picked point. It would be more straight forward to start the increments from 1, since it is unusual to use '0' as a list index when presenting landmarks (or any other king of points) in a table and it is also more convenient when using the numeric names as matrix indices in GNU OCTAVE/MATLAB code.

Best regards

**Comment by alemuntoni** [comment]
Hi all, the filter has been re-included. You can find all the binaries in the last github actions build ([Windows](https://github.com/cnr-isti-vclab/meshlab/actions/runs/98065944), [MacOS](https://github.com/cnr-isti-vclab/meshlab/actions/runs/98065948), [Linux](https://github.com/cnr-isti-vclab/meshlab/actions/runs/98065951) ), and will be part of the next 2020.06 release.

**Comment by pr0m1th3as** [comment]
Thanks for that!!
I ve just tried it with a moderate sized (~500k faces) cranium model and I realized that the point filter does not allow rotation/translation of the model while enabled. If I remember correctly, this was a feature of filter predating the 1.3.3 version of Meshlab, which allowed rotation of the model while picking landmarks. Is it possible to revert to that version of the filter? Not being able to rotate the model is quite problematic, since switching on and off the filter also resets the counter for the points' names.

Additionally, after switching on and off the filter a few times in order to rotate the model and then pick a few more random points, Meshlab suddenly crashed (on Ubuntu 18.04.4 LTS) on one occasion. However, I am not able to duplicate the crash consistently.

**Comment by aslze** [comment]
Thank you!

**Comment by aslze** [comment]
Hey @pr0m1th3as you can switch between pick points and rotate view with ESC key while in the Pick Points tool. You pick with right mouse button, you press ESC and rotate/move/zoom view with left mouse button (plus modifiers or wheel), you press ESC again ang can click more points.

**Comment by pr0m1th3as** [comment]
@aslze thanks for the tip! I didn't know that, very convenient.

Unfortunately, it doesn't work properly. After a couple of times of switching between point picking and rotation/move/zoom Meshlab crashes and becomes totally unresponsive. I have tested this repeatedly in two ubuntu 18.04 systems (one of which with clean install) and I get the same behaviour. Additionally, the mouse is affected. xkill returns: 
```console
xkill:  unable to grab cursor
```
@alemuntoni Should I open a new issue and report this as a bug?

once again thanks everyone for supporting and re-including point picking filter

**Comment by rpavlik** [comment]
@pr0m1th3as yeah I'd open a new issue for that.
