### ISSUE TITLE
Appveyor builds no longer available

### ISSUE THREAD

**Issue by SpitfireMk** [cnr-isti-vclab/meshlab#571]
For some time I have been using this page to download the latest Windows builds, as suggested here:  https://github.com/cnr-isti-vclab/meshlab/issues/355#issuecomment-418109964

But now when I try to access the page I get this error:
_Project not found or access denied._
https://ci.appveyor.com/project/cignoni/meshlab/build/artifacts

Is it no longer available? It was quite useful, at least for Windows users. Thank you.

**Comment by alemuntoni** [comment]
As you can read in the main [readme](https://github.com/cnr-isti-vclab/meshlab/blob/master/README.md) we are now using Github Actions, which is naturally integrated with Github. For every commit, you can download a build from the artifacts of a workflow (example [here](https://github.com/cnr-isti-vclab/meshlab/actions/runs/38871592)).
For windows, right now only a portable version is provided. We will provide an installer ASAP.

**Comment by SpitfireMk** [comment]
That's exactly what I was looking for. Thank you!
