### ISSUE TITLE
Meshlab Crashes if When Aligning Large Point Clouds if Normal Equal Sampling is Enabled

### ISSUE THREAD

**Issue by Marsfan** [cnr-isti-vclab/meshlab#574]
Just discovered this glitch while trying to align a couple of 2.2 million voxel point clouds that I generated with ElasticFusion. 
Whenever I try to run automatic alignment in Meshlab on a couple of point clouds in this size range, Meshlab completely crashes with no output messages.  This occurs whether I use the latest stable build on the website (from 2016), or the most recent beta on GitHub (2020.02).

On a side note, is there any way to get some sort of error log from Meshlab? It took me forever to identify the source of the error as I had to just keep trying enabling and disabling different settings.

**Comment by mcallieri** [comment]
do the cloud have normals at all? Geometric alignment does require normals.
Unfortunately, normals are allocated by default, even if the input files does not have them, so the alignment does not know that the normals are "invalid"and, as soon as it tries to use them, the numbers make no sense and just crashes.

**Comment by Marsfan** [comment]
@mcallieri That appears to be the problem. I ran the filter `Compute Normals From Point Set` on each mesh, and it did not crash. 
Its strange, I know that ElasticFusion can report the normals of the data, I guess it does not properly export it. 

Perhaps some sort of error checker should be implemented in Meshlab to prevent this from happening.

**Comment by Marsfan** [comment]
@mcallieri I just ran a test. The poit clouds do indeed have normal. I cannot verify that they all have normals though. Is there a way I can check that?

**Comment by mcallieri** [comment]
it is possible that only **some** vertices have "invalid" normals (zero-length, NaN...).
I'm not sure there is an automatic way to find those...
There is a way to check for zero-lenght, but is a pain. However, you may use it to see if there are any.
filters->selection->conditional vertex selection 
and enter the function           (nx==0.0)&&(ny==0.0)&&(nz==0.0)
then hit apply. If some vertices are selected, those vertices have a zero-lenght normal. deleting them should solve the issue.
Another thing is trying filters->normals,curvature....->normalize vertex normals
should eliminate normals that are not 1 unit in lenght
I'm sorry but we do not have a filter to clean this things automatically. We may need one

**Comment by Marsfan** [comment]
@mcallieri I tried the conditional selection you specified, and nothing was selected.

**Comment by mcallieri** [comment]
then I do not know. 
With the normalization? any luck?
you may try with render-show normals, and see if every point does have a nromal, but on a 2 million vertices cloud, it's almost impossible to check every vertex with your eyes
