### ISSUE TITLE
Up to date version?

### ISSUE THREAD

**Issue by Marsfan** [cnr-isti-vclab/meshlab#580]
Hello,

I am not sure if this is the correct place to ask this, but I am having trouble finding out what version of meshlab is the most up to date version. 

Meshlab.net still hosts the 2016 version, while this GitHub repo has builds for 2020. 

Furthermore, on my Linux Computer, I see both a snap, and a normal package, as well a something called meshlab-mardy. 

Which of these is the correct one that is actively being maintained?

**Comment by alemuntoni** [comment]
Hello,
right now we are maintaining MeshLab with regular releases every month in GitHub.
The site right now points to the 2020.02 version.

For Linux, at the moment we are releasing only AppImages, and a deb shouls be provided in the next Ubuntu distro (20.04).

**Comment by Marsfan** [comment]
Ah. That makes sense. Maybe something should be added to the website to redirect downloads to here.

**Comment by alemuntoni** [comment]
I has been done a few days ago :)
2020.02 is now the version linked in http://www.meshlab.net/
