### ISSUE TITLE
Support E57 file format

### ISSUE THREAD

**Issue by brawer** [cnr-isti-vclab/meshlab#582]
Could MeshLab support the [ASTM E57 file format](https://www.researchgate.net/profile/Daniel_Huber5/publication/241537534_The_ASTM_E57_file_format_for_3D_imaging_data_exchange/links/5c46491692851c22a386f581/The-ASTM-E57-file-format-for-3D-imaging-data-exchange.pdf), which is used for point clouds, common in laser scanning? Some pointers:
* https://github.com/asmaloney/libE57Format
* http://www.libe57.org/

**Comment by alemuntoni** [comment]
Working on it :)

**Comment by virtualbri** [comment]
How's this going?  I'd love to use Meshlab in getting BLK360 point clouds to meshes.

**Comment by alemuntoni** [comment]
We'll try to have the plugin by the end of the summer, but I cannot guarantee anything.

**Comment by alemuntoni** [comment]
Added importer/exporter of e57 in #1036.
Will be available in the next version of meshlab, which will be released in the next days.

**Comment by mt-spg** [comment]
Hello!
I am extremely pleased and thankful you have gone through the work of implementing e57. I really appreciate it. 

I tried tonight to build from master to try out the e57 import feature, but I ran into some issues. It built just fine, but when I tried to run it I got the following error.

```
Unable to load the following plugins:
libio_e57.so: libio_e57.so does not seem to be a Qt Plugin.
Cannot load library /home/username/Meshlab/meshlab/src/install/usr/lib/meshlab/plugins/libio_e57.so: (libE57Format.so: cannot open shared object file: No such file or directory)
```

Once I closed the error dialog, meshlab ran, but there was no E57 import option. I tried to build the libE57Format.so from the source and did so successfully, but I couldn't figure out the correct place to put the library (I tried placing it in my path and also in a few different folders under  `/install` but I still got the error) I will be honest and say this is rather out of my wheel house, but I thought I would bring it up here in case it can help you guys for the next release. 

Thanks in advance and let me know if there is anything I can do to help!

I am running Pop OS 20.10 (Ubuntu). 
```
> lsb_release -a
Distributor ID: Pop
Description:    Pop!_OS 20.10
Release:        20.10
Codename:       groovy
```

**Comment by alemuntoni** [comment]
Hi @mt-spg, in the last commit I solved a small issue in the cmake configuration related to the e57 plugin.
Could you please try again? Or alternatively, could you please try the [last nightly](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version)?
