### ISSUE TITLE
Export to Sketchfab Filter Failure

### ISSUE THREAD

**Issue by Lasinja** [cnr-isti-vclab/meshlab#585]
Filter doesn't work!

**Comment by Lasinja** [comment]
![teren](https://user-images.githubusercontent.com/61557865/75874895-f620fa00-5e12-11ea-9e5c-e5501d23d8ee.jpg)
![Wood_chair](https://user-images.githubusercontent.com/61557865/75874898-f7eabd80-5e12-11ea-8851-1a10cac12482.png)
![wovenmat jpg](https://user-images.githubusercontent.com/61557865/75874905-fae5ae00-5e12-11ea-9015-93d6520e8fdd.jpeg)
![889](https://user-images.githubusercontent.com/61557865/75874906-fae5ae00-5e12-11ea-8f3a-82d19845ac90.png)
![cloth](https://user-images.githubusercontent.com/61557865/75874924-0507ac80-5e13-11ea-94c9-77a5d09b05c1.png)
![d-1](https://user-images.githubusercontent.com/61557865/75874930-0933ca00-5e13-11ea-9d92-9d2a5b00d8b0.jpg)
![granite jpg](https://user-images.githubusercontent.com/61557865/75874932-09cc6080-5e13-11ea-85e0-94d732527e47.jpeg)
![smoke](https://user-images.githubusercontent.com/61557865/75874934-0a64f700-5e13-11ea-8d0c-16479c5e0a46.jpg)

**Comment by alemuntoni** [comment]
Hi, the problem has been solved in the last commits and will be available starting from 2020.06 version. You can test it in advance by downloading one of the artifacts produced by github actions ([win](https://github.com/cnr-isti-vclab/meshlab/actions/runs/110321661), [macos](https://github.com/cnr-isti-vclab/meshlab/actions/runs/110321658), [linux](https://github.com/cnr-isti-vclab/meshlab/actions/runs/110321659) ). Feel free to open a new issue if the problem persists.
