### ISSUE TITLE
Crash when opening any .ply

### ISSUE THREAD

**Issue by ckgerard** [cnr-isti-vclab/meshlab#586]
MeshLab_64bit_fp v2020.02  MacOS High Sierra
Instant Crash when trying to open any .ply file

**Comment by martin-frbg** [comment]
Any messages accompanying the crash ? And actually any .ply, or just any created by a particular program ?

**Comment by alemuntoni** [comment]
I think this is related to #584.

**Comment by alemuntoni** [comment]
Closing this because it is duplicate of #584
