### ISSUE TITLE
Manpage error

### ISSUE THREAD

**Issue by rpavlik** [cnr-isti-vclab/meshlab#588]
Found by lintian:

```
W: meshlab: manpage-has-errors-from-man usr/share/man/man1/meshlab.1.gz  line 18: 'R' is a string (producing the registered sign), not a macro.
```

**Comment by alemuntoni** [comment]
I think it refers to [this](https://github.com/cnr-isti-vclab/meshlab/blob/master/docs/man/meshlab.1) file. 
I wrote that file, but I am not very practical on man syntax...

**Comment by rpavlik** [comment]
Me either, or I would have made a pull request instead :grin:

**Comment by rpavlik** [comment]
OK, so I re-wrote the manpages in mandoc format (originated in BSD, but works on Linux by default - it's semantic so a little less arcane) in here,  you're welcome to use them: https://salsa.debian.org/rpavlik-guest/meshlab/-/tree/master/debian

I can make a PR if you like.

**Comment by alemuntoni** [comment]
I can add it to my next PR!
Thank you very much @rpavlik!
