### ISSUE TITLE
Desktop file error/warning

### ISSUE THREAD

**Issue by rpavlik** [cnr-isti-vclab/meshlab#589]
Found by lintian:

- `I: meshlab: desktop-entry-lacks-keywords-entry usr/share/applications/meshlab.desktop`
  - https://lintian.debian.org/tags/desktop-entry-lacks-keywords-entry.html
- `W: meshlab: desktop-mime-but-no-exec-code usr/share/applications/meshlab.desktop`
  - https://lintian.debian.org/tags/desktop-mime-but-no-exec-code.html

(Ideally, the list of mime types would be generated at configure time based on which plugins were enabled, too, but that's probably a little complicated. If nothing else it should be reviewed.)

**Comment by alemuntoni** [comment]
This issue could be closed now, right?

**Comment by rpavlik** [comment]
Not entirely. I fixed the exec code one, but the lacks-keywords one is still there.
