### ISSUE TITLE
Redesign user interface

### ISSUE THREAD

**Issue by minusplusminus** [cnr-isti-vclab/meshlab#59]
Hi everyone,

My proposal is to redesign the entire user interface to be more according other UIs that are used nowadays.  Do other people agree with me?

I've mentioned in previous projects that it's hard to describe UI changes by using Github.

**Comment by uq1** [comment]
I feel that the current UI is just fine, however there is a very, very, annoying issue:
https://i.imgur.com/kqvJpgb.jpg (screenshot)

The main window doesn't fit the screen and can't be resized horizontally (it can vertically for some reason).

**Comment by mcallieri** [comment]
This is the first time, over many, many thousands of users, that we have had this problem reported. 
MeshLab window can be resized at will, in both direction.
But I see you are using non-standard desktop managers....

**Comment by uq1** [comment]
Thats just a theme. It happens when i switch to AERO, windows basic, classic, etc themes as well. I've found this happens with most QT applications. It's guesses the wrong screen size.
