### ISSUE TITLE
Build on 32-bit arm?

### ISSUE THREAD

**Issue by rpavlik** [cnr-isti-vclab/meshlab#592]
Context: the intended glorious return of MeshLab to Debian and its derivatives :)

As far as I know, the "armel" and "armhf" debian arches (32-bit arm v7 arches) do not have OpenGL, but OpenGLES instead. (I thought the same was true for aarch64, but I actually got the build to work there...) I worked around an undefined `glVector3f` in structure-synth code (which is weird since that package on its own builds on armel...), but then I hit a major issue where basically every OpenGL symbol in GLEW breaks the build.

I'd just exclude these two platforms, except that the last version of MeshLab that was in Debian (1.3 something) actually did build fine on them. Is there a known change since then that removed OpenGL-ES compatibility? Some other way to work around it perhaps?

**Comment by rpavlik** [comment]
(One option might be to consider a replacement for GLEW, especially since many files loudly complain that GLEW is incompatible with Qt OpenGL. I've personally used [GLAD](https://glad.dav1d.de/) recently to some success, not sure if it's more compatible.)

**Comment by alemuntoni** [comment]
I really don't know, I'm pretty sure nobody in our lab did the deb for 1.3.2, but was done but someone extern. I would just exclude the two platforms...

**Comment by rpavlik** [comment]
Looks like the hardest part may be getting rid of glBegin/glEnd: there's a fair amount of that type of code in the codebase. I have built with glad successfully, however.
