### ISSUE TITLE
Latest Windows release crashing on launch

### ISSUE THREAD

**Issue by sabalka** [cnr-isti-vclab/meshlab#595]
I'm running Windows 10 Home 1903 build 18362.657. I just installed the 2020.02 version on meshlab.net (I had been running the 2016.12 version just fine). The program crashes upon launch, never opening (regardless of whether a mesh is specified or not). No window or popup appears. Event log is below. I restarted but no love there.

Faulting application name: meshlab.exe, version: 0.0.0.0, time stamp: 0x5e4ad2cd
Faulting module name: Qt5Widgets.dll, version: 5.12.6.0, time stamp: 0x5dc597cd
Exception code: 0xc0000005
Fault offset: 0x000000000000c4df
Faulting process id: 0x3c68
Faulting application start time: 0x01d5f58939c277e7
Faulting application path: C:\Program Files\VCG\MeshLab\meshlab.exe
Faulting module path: C:\Program Files\VCG\MeshLab\Qt5Widgets.dll
Report Id: 1b0f4fe8-b79c-4ba4-94dc-d565af33693a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by potenziani** [comment]
Hi @sabalka, I had a similar issue.
I think the problem occurs with some specific system configurations when a user tries to install the latest MeshLab version (2020.02) without before uninstalling the previous versions installed. 
Anyway, I solved it just uninstalling MeshLab and then re-installing the 2020.02 version.

**Comment by sabalka** [comment]
Thanks, Marco
