### ISSUE TITLE
Matrix: Set/Copy Transformation interface broken

### ISSUE THREAD

**Issue by isaactian** [cnr-isti-vclab/meshlab#60]
The top left box (row 0 col 0) cannot be selected and cannot be changed from 1. The other boxes seem to work.

**Comment by granzuglia** [comment]
true. we will fix it as soon as possible.

**Comment by isaactian** [comment]
Is there any other way to set the transformation matrix?

**Comment by cignoni** [comment]
If you want to precisely set the transformation matrix, probably the easiest workaround is to save your current project, open the` *.mpl `file with a text editor (it is a simple xml), change the matrix by hand (16 floats tagged by `<MLMatrix44>`) and re-open the project.

**Comment by isaactian** [comment]
There appears to be something broken about this as well. The matrix shown in the bottom right corner in Meshlab do not contain the same values that I put in. (The bottom row becomes 0 1 0 0 instead of 0 0 0 1 for some reason and it causes massive distortion)

**Comment by isaactian** [comment]
Never

**Comment by mcallieri** [comment]
We are fixing it. It is an interface issue. 
In the meantime, just select the SECOND element, and hit shift-TAB to highlight the first, elusive element.

**Comment by mcallieri** [comment]
fixed with a workaround. We are preparing a new release.
