### ISSUE TITLE
fresh Meshlab install on MacOS Sierra 10.12.5 crashes

### ISSUE THREAD

**Issue by mrb3h** [cnr-isti-vclab/meshlab#602]
Any one have any problems opening files after a fresh install on MacOS Sierra 10.12.5 with  "MeshLab_64bit_fp v2020.02   (built on Feb 12 2020)" Meshlab fires up fine, but crashes when I try to open any existing file. I used Meshlab without a hitch on my last computer, but after repairs (new logic board, new keyboard, new case) it won't open the same files. Sorry I don't recall what the old computer was running before I fried it!

**Comment by Pindterx** [comment]
I have same Problem with High Sierra 10.13.6

**Comment by rpavlik** [comment]
Think this is probably the same as #584

**Comment by alemuntoni** [comment]
Closing this because it is duplicate of #584
