### ISSUE TITLE
Meshlabserver reading bundler.out and list file

### ISSUE THREAD

**Issue by ethansu1992** [cnr-isti-vclab/meshlab#603]
Hi i am currently facing a problem as the meshlabserver is not able to read the bundler.out file and list.txt file as the program. Are there any way we can go about doing it?

**Comment by alemuntoni** [comment]
Hi, could you please elaborate? What files are you trying to open?

**Comment by ethansu1992** [comment]
Hi, the problem i am facing is trying to open up a bundle.out (project file) and list.txt file that is the output from the photogrammetry codes osm-bundler. In the meshlab software, it is able to combine them and save it as a .mlp file. However, there is no such function or rather in mashlabserver, the file_in function is not able to take in these files and compile them in to a proper .mlp folder.

**Comment by alemuntoni** [comment]
Done with #736. Will be available starting from version 2020.07.
