### ISSUE TITLE
[Feature Request] Importing .out file and .txt file in Meshlab Server to create a .mlp file

### ISSUE THREAD

**Issue by ethansu1992** [cnr-isti-vclab/meshlab#607]
Hi i am writing in to request for an feature for meshlab server to be able to take in bundle.out file and list.txt file in think line of codes :

`def run(script='TEMP3D_default.mlx', log=None, ml_log=None,
        mlp_in=None, mlp_out=None, overwrite=False, file_in=None,
        file_out=None, output_mask=None, cmd=None, ml_version=ML_VERSION,
        print_meshlabserver_output=True):

    """Run meshlabserver in a subprocess.`

Currently the meshlab server is not able to accept bundler.out file and list.txt file to generate the texture file and the mlp file. 

Please let me know if this is possible as the programme is doable, i just hope to automate this process.

**Comment by alemuntoni** [comment]
Done with #736. Will be available starting from version 2020.07.
