### ISSUE TITLE
U3D-Export doesn't work in 2016.12 - IDFTConverter.exe is missing

### ISSUE THREAD

**Issue by michaelnum** [cnr-isti-vclab/meshlab#61]
Hello,

the eport of a mesh as *u3d doesnt't work.
The Plugin IDTFConverter is missing.

The older versions included this in the windows version. On Linux it was missing in the past, too.

Only to download the IDTFConverter from https://sourceforge.net/projects/u3d/ and extract it on the right path doesn't work. With this, Meshlab don't give an error. It write the *tex, but not a *u3d-file.

On which way can i get the *u3d-export to work?

Thanks!

Michael

**Comment by mcallieri** [comment]
Yes, it was not included in the distribution. sorry.
Please refer to issue #33 for a temporary fix, until the new release will be out.
