### ISSUE TITLE
VCRUNTIME140_1.dll not found

### ISSUE THREAD

**Issue by sneakypete76** [cnr-isti-vclab/meshlab#610]
Problem: 
Program wont start. Win10 64bit, installed to default directory, ran as admin. 

Error message: 
"VCRUNTIME140_1.dll not found. Reinstalling the program may fix this." 

Problem:
After re-install, same error.

Reason: 
dll seems to be missing/inaccessible from either Windows system files and/or meshlab installer.
Maybe VCRUNTIME140_1.dll is proprietary software and can't be distributed with meshlab?

Workaround: 
User will search for and download the missing dll and manually copy it to the Meshlab folder before running software again to see if error is cleared.

**Comment by edgroc** [comment]
This is a Microsoft Visual Studio 2015 runtime library redistributable. It comes with the compiler, and should come with the rights to redistribute it.
Not a solution, but as a workaround an end user should be able to install these themselves by downloading and running the approriate vc_redist from https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

**Comment by alemuntoni** [comment]
Hi, I can confirm that the problem can be solved installing the Visual Studio 2015 runtime library. 
Inside the MeshLab folder there is the installer (called vc_redist.x64.exe), installing it should be enough.
The MeshLab installer should propose to install it if the runtime library is not detected in the system, but apparently there is some bug and this is not happening. I will investigate on it.

**Comment by alemuntoni** [comment]
Hi again, I solved this problem in the last commits. 
You can find a working installer [here](https://github.com/cnr-isti-vclab/meshlab/actions/runs/73720133), or starting from version 2020.05.
Feel free to open other issues if any! :)
