### ISSUE TITLE
Meshlab Does not open

### ISSUE THREAD

**Issue by Ahm3dsay3d** [cnr-isti-vclab/meshlab#611]
The last release 2020.02 does not open on windows 8.1

**Comment by alemuntoni** [comment]
Hi, this issue should be solved in the last commits. 
Probably your graphic drivers do not support newer versions of OpenGL, and therefore MeshLab did not start. Now, if this happens, MeshLab asks to use a CPU implementation of OpenGL that allows it to start.
You can find a working installer [here](https://github.com/cnr-isti-vclab/meshlab/actions/runs/73720133), or starting from version 2020.05.
Feel free to open another issue if the problem persists! :)
