### ISSUE TITLE
"About" page copyright needs update

### ISSUE THREAD

**Issue by brutzman** [cnr-isti-vclab/meshlab#612]
"About" page copyright reads 2005-2018, needs update to 2005-2020.

p.s. Thanks for getting things moving again. The hardest part about driving a dog sled is... getting the rails unstuck from the ice.  Looking forward to lots of forward motion!  8)

**Comment by alemuntoni** [comment]
Hi @brutzman, thanks for reporting this!
It has been updated in the last PR! :)
