### ISSUE TITLE
error code -11

### ISSUE THREAD

**Issue by sfornengo** [cnr-isti-vclab/meshlab#62]
I am using meshlabserver for "Quadric Edge Collapse Decimation with texture" with python subprocess call.
Sometimes it fails returning error code -11.
Then relaunching with the same parameters it works.
What is the meaning of code -11 ?

**Comment by mcallieri** [comment]
Sorry for the late reply.
I searched a lot, but without much success. Frankly, I have no idea where this error code comes from: in no place there is a numerical error code return.
From the code, there are two cases where the filter will fail:
- mesh has no texture
- mesh has inconsistent texture (some triangles are textured, some other triangles are NOT)

**Comment by mcallieri** [comment]
I closed the topic beause it is inactive from a long time, we had no other reports of this issue, and we cannot replicate it on any of the tens of machines we are using.
