### ISSUE TITLE
MeshLabServer issue: current folder is not writable (even though it is)

### ISSUE THREAD

**Issue by joeegar** [cnr-isti-vclab/meshlab#621]
I've created a script that I want to run and am using the command line prompt:

`C:\Program Files\VCG\MeshLab>meshlabserver.exe -p C:\temp\project.mlp -o C:\temp\output.obj -s C:\temp\script.mlx`

The project file contains a valid file in put file (also in c:\temp) and the script runs the Screened Poisson filter. Both items work when done in the Gui version. However, when I run this from the command prompt, it provides me with a warning after the first few items of the script have successfully completed with a error:

> filter: Surface Reconstruction: Screened Poisson
LOG: 2 ERROR - current folder is not writable. Screened Poisson Merging needs to save intermediate files in the current working folder. Project and meshes must be in a write-enabled folder. Please save your data in a suitable folder before applying.

All files are located in a write-able folder (c:\temp) so I don't see how to avoid this. The only way to avoid this is to run CMD as admin OR to copy the entire Meshlab folder into a different directory. Neither options are attractive.
I've tried the same script without the Poisson filter and it works fine.
Is there a way to explicitly define the working directory? Can the script be modified to define where the working files are to be placed? I could not find much on how/where the working directory is to be defined other than by saving the project file, but as this is already provided, how would I need to change this? To be clear, all the files provided on the command prompt line are being automatically generated, I just can't seem to run it in this way...
Something like this would be helpful, but primarily there seems to be a bug in that the Poisson filter does not correctly identify the 'working' directory as the one where all files are being provided from.

Thanks,
J

**Comment by 3DLIRIOUS** [comment]
I believe that the meshlabserver working directory is the current directory that you are in when you run the command. Your current directory is "C:\Program Files\VCG\MeshLab", which is not writable, hence the error. Try this instead:

`cd C:\temp`
`C:\temp>"C:\Program Files\VCG\MeshLab\meshlabserver.exe" -p C:\temp\project.mlp -o C:\temp\output.obj -s C:\temp\script.mlx`

or, since your files are now in your working directory:
`C:\temp>"C:\Program Files\VCG\MeshLab\meshlabserver.exe" -p project.mlp -o output.obj -s script.mlx`

**Comment by joeegar** [comment]
Ah... had not thought of doing it that way.
Yes, this solves the general issue, though for my purpose I need to wrap the entire thing in a batch file.
But for now: Thank You!

(P.s. would be nice to be able to define the working directory in a parameter...)
