### ISSUE TITLE
Automatically computed version number is very problematic

### ISSUE THREAD

**Issue by nh2** [cnr-isti-vclab/meshlab#622]
Since `Meshlab-2020.03` (thanks btw!), the program release version is no longer fixed but computed from the build date.

This means that distributions packaging Meshlab will show the wrong version.

For example, if Ubuntu, Debian, or any other Linux distro packages Meshlab 2020.3 in April, it will show up as `2020.4`, which is _very_ confusing to users (especially because the version string in the About page -- see screenshot -- is intentionally copyable by mouse so that users can report their version when filing bugs).

Further, many distributions' build systems turn off time when building to get binary-[reproducible builds](https://reproducible-builds.org/). That makes the version show up even more wrong:

![image](https://user-images.githubusercontent.com/399535/77602493-efffd400-6f0d-11ea-9700-1c11a61a8af4.png)

Or in the terminal:

```
$ meshlabserver
MeshLabServer version: 1970.01
```

CC @alemuntoni via https://github.com/cnr-isti-vclab/meshlab/commit/4ede42efd9f53ebdd2b3ecee6500b45e0c21368f

**Comment by alemuntoni** [comment]
Hi @nh2,

I see the problem here, but I really don't know how to solve it.
On our side, we decided to automatically release a new MeshLab version every first day of the month, which makes available all the bugfixes and new features that we do to the users of all platforms. 
Modifying an header every month before the automatic build would be problematic. Right now we need this mechanism of "dynamic versioning" here in github.

The only solution I see is to put the version hardcoded in the sources that are going to be built for Debian/Ubuntu. But I'm open to hear some other solutions that satisfy everyone, if any!

**Comment by nh2** [comment]
@alemuntoni It seems the best approach would be to let your Github Workflow that creates the release tarballs write the version into the generate source dist:

In line https://github.com/cnr-isti-vclab/meshlab/blob/a5f1ae8506388c36d6d2f810067d791ddecae35e/.github/workflows/CompileAndRelease.yml#L166

you already get the date of the build.

Could use the same method to write a file, e.g. `VERSION`, into the source directory just before the build step, like in https://github.com/cnr-isti-vclab/meshlab/blob/a5f1ae8506388c36d6d2f810067d791ddecae35e/.github/workflows/CompileAndRelease.yml#L29-L31

?

By default, the contents of the `VERSION` file could be `git`, and your automatic build+release pipeline could replace that file's contents with e.g. `2020.3`.

That way,

* release tarballs would always have compile to the right version
* direct git clones would always show `git` as the version (which is good)

**Comment by alemuntoni** [comment]
Ok, makes sense. 
I'll do something similar, putting in the `VERSION` file the version that we link in the meshlab website (right now it is 2020.02), and then I'll manually update it whenever a new version will be linked.

**Comment by alemuntoni** [comment]
See #625

**Comment by nh2** [comment]
Thanks @alemuntoni !

**Comment by nh2** [comment]
@alemuntoni Just one issue I encountered on `2020.04`:

In https://github.com/cnr-isti-vclab/meshlab/commit/0a88a4f986673eabc2028b2780836bac230b8dbf#diff-dedf7c7c3ddd27c2b4a6a56b53ad2ca9R44

`MESHLAB_VERSION = $$cat(../../VERSION)` is it possible that this will include the trailing newline `\n` at the end of the file?

In at least one of my builds right now I ended up with a `flags.make` containing line

```
CXX_DEFINES = -DMESHLAB_SCALAR=float -DMESHLAB_VERSION=2020.02
 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SCRIPT_LIB -DQT_WIDGETS_LIB -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -Dcommon_EXPORTS
```

which is an illegal Makefile, so I suspect that the string injected is `2020.02\n`.

**Comment by alemuntoni** [comment]
Yes, could be that. 
I also had that issue when I was testing this solution, but somehow later it disappeared, and right now all CIs for both qmake and cmake are working... 

I am fixing this right now anyway!
