### ISSUE TITLE
Plugin Point-Cloud registration (Super4PCS) using OpenGR

### ISSUE THREAD

**Issue by nmellado** [cnr-isti-vclab/meshlab#624]
Dear Meshlab crew,

Would you be interested in a plugin for point-cloud registration, based on the library OpenGR ?

I have developed this some time ago, but it was hard to maintain on my side only (https://github.com/STORM-IRIT/OpenGR/tree/56eafeeba00025da395a38157364262ab313a034/demos/MeshlabPlugin).
So I disabled it recently (https://github.com/STORM-IRIT/OpenGR/commit/7f11a483b297716337c969435e0470932c3bf07c).
Would you consider adding such plugin in Meshlab directly ? I have some user requests for that (https://github.com/STORM-IRIT/OpenGR/issues/49#event-3166722856)

Cheers,
Nicolas

**Comment by alemuntoni** [comment]
Hi @nmellado,

Yes, that would be cool to add in MeshLab.
Is there any other dependency beside OpenGR library?

**Comment by nmellado** [comment]
Hi @alemuntoni 

Great news !
The only dependency is eigen. Note that OpenGR is header only now.

**Comment by nmellado** [comment]
How do we proceed ?
One option is that I create a PR with my current version of the plugin, and then we discuss it in order to improve the UI, functionalities, etc.

**Comment by alemuntoni** [comment]
Yep, that would be great! :) 
Thank you!!

**Comment by alemuntoni** [comment]
@nmellado is there any news on this? Can I help you with something?

**Comment by nmellado** [comment]
Sorry I couldn't find time to take care of it.
What needs to be done is first to take the code of the plugin that was included in OpenGR to add it into meshlab buildchain (https://github.com/STORM-IRIT/OpenGR/tree/56eafeeba00025da395a38157364262ab313a034/demos/MeshlabPlugin)

**Comment by alemuntoni** [comment]
Ok, cool.
If you find 5 minutes, just make a fork of the meshlab repo, and then copy-paste the plugin in the meshlabplugins folder.
I'll then take care to make it build.
In this way, you will result as a crontributor of the plugin in the MeshLab repo :)

**Comment by nmellado** [comment]
Thanks @alemuntoni , I finally did it !
Let me know if I can help on setting up OpenGR.
