### ISSUE TITLE
Trying to transfer vertex colour of a cpoint cloud to the mesh

### ISSUE THREAD

**Issue by TheBricktop** [cnr-isti-vclab/meshlab#629]
Hello im using the transfer attributes vertex colour to transfer the cloud colour to the mesh and
meshlab 2020 doesnt allow baking from point cloud to mesh
Error : both meshes require to have faces.

**Comment by mcallieri** [comment]
I believe you posted on two different threads, AND on reddit. 
If I got it correctly, you want to bake the vertex colors from a pointcloud to the texture of a textured mesh. 
The error you are getting is a pre-requisite of the filter. The mapping we have is only possible  between meshes, and not pointclouds. We can go from pointcloud to mesh, but not to texture.
In theory, it should be possible, but we do not have the process implemented, at the moment. 
It could be useful, but I'm not sure when we will be able to add this.

**Comment by mcallieri** [comment]
yes, there was an error in asking for both layers to have faces. When transfering color, a source pointcloud is enough. 
Corrected.

**Comment by TheBricktop** [comment]
Yes, I did,
thank You !
Is it now available to download?
