### ISSUE TITLE
"No respond" when loading large meshes and pointclouds

### ISSUE THREAD

**Issue by Askanderre** [cnr-isti-vclab/meshlab#63]
Hello!

I actually was looking forward to the new Meshlab Version but it turned out there might be an issue with the file managment? Always when I'm trying to load larger models or pointcloud nothing works and it shows "no respond" from the Software. When I'm triying to load them in 1.3.3 or 1.3.2 it works well. Even smaller models are taking much longer to load then in the older Versions. I even tried to uninstall all Meshlab Versions to use only the newest one (cleaned the Registry as well), but this didn't work out well... of course I'm not getting any failure report because the Programm don't break out it only gives no respond over more then 30min (longest try to wait before I shot it down).

My Computer:

Windows 7 Prof x64
AsRock 990fx Extreme9
AMD FX-8120 eight-core
NVIDIA Quadro K5000
32Gb Ram

What can I do btw. what kind of information do you need else for that issue? 

Thanks in Advance! (And sorry that I asked first in Facebook...)

Alex

**Comment by mcallieri** [comment]
Can you give an example of size (in terms of MB or number of triangles/points)? which format are you using?

It is strange, actually, the time for loading single files has decreased, in our tests.
We DO have an issue that affects the loading of MLP projects containing lots of layers: as the number of layers increases, the startup time grows exponentially. It is noticeable for MLP with more than 40-50 layers. We are working to solve it.

**Comment by Askanderre** [comment]
Hallo! Thanks for at least your fast respond ;) :D 

I usally worked until now with the new Meshlab only with .PLYs (.There will come .OBJ as well but currently there is no project with it). The last time (in the morning) after all that reinstalling I tested it with a point cloud of 12,232,236 Vertices inkl. Color information together with a surface model (v: 1,149,324 f: 2,294,491) also with color information. I also don't turn out alsways when I'm loading only one model - there it happen only twice till now but usually there are problems with no repond of the software when I'm trying to load more then one model when there is at leat a huge one by. 

Alex

**Comment by Askanderre** [comment]
Sorry to push, but the Problem is still not solved.... :)

**Comment by mcallieri** [comment]
I am sorry, but we are unable to exactly replicate the issue, we have tried with multiple files (1-50 Mpoints/tri) on multiple machines, but loading times seems ok.

However, QUADRO cards are generally slower at changing rendering mode, and in memory allocation/freeing. There is a parameter, in the new version, that tells MeshLab how much videocard memory can use. The default value may be low, for high-end graphics cards like QUADRO. Try setting it to a higher number, still below the available memory.. e.g. 3750MB if the card has 4096MB, 1700 if the card has 2000. Texture, at least 250MB. follow this tutorial to find and set the parameter https://www.youtube.com/watch?v=ZbyzQHo666E&t=4s

Sorry, but is really difficult to debug things on multiple platforms and hardware configurations.

**Comment by Askanderre** [comment]
Hey! 

As far as I see now this most likely solved it! :D - I just loaded 21 models with all togehter 61.800.000 Vertices / 119.770.000 Faces - and I can change the View-Mode and move all together and make Snapshoots! :D - Great Tool now! Thanks a lot! 

Alex

**Comment by mcallieri** [comment]
The issue seems related to the QUADRO cards. When the data fits in memory, the rendering is ok, when the memory is full, the "immediate mode" rendering is buggy and may freeze the tool.
Quadro are, in any case, slower at changing rendering mode (also in the older version of MeshLab).
We will try fixing it, but it may take some time.
