### ISSUE TITLE
export to 3ds: lost path to texture

### ISSUE THREAD

**Issue by JFgith** [cnr-isti-vclab/meshlab#630]
If I export  e.g. a DAE file to 3ds all seems to work fine but when I open the 3ds file in e.g. View3dscene I get following message:
Error while loading scene from"file:///Users/xxx/Desktop/Planeten/Test/cours(dae).3ds": Material "Material - 0" used but does not exist
and I cannot open the file.I can the file with glc-player but there is no texture.
The name of the original texture files is not Material - 0
I tried to rename the texture without success.
this export had worked with the 2016 version 

tried on Mac Pro 5.1 and MacBook Pro 2015 both with Mojave
[Export 3ds.zip](https://github.com/cnr-isti-vclab/meshlab/files/4433748/Export.3ds.zip)

**Comment by alemuntoni** [comment]
Probably same issue of #488

**Comment by alemuntoni** [comment]
Solved in previous commits. Texture I/O has been completely rewritten.
To try it, [download the last nightly](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version)
