### ISSUE TITLE
Cannot load texture 

### ISSUE THREAD

**Issue by in3des** [cnr-isti-vclab/meshlab#633]
Hi,
I'm trying to load texture for the mesh, but for some reason MeshLab is trying to locate it at the wrong path...
Please see the screenshot - https://prnt.sc/rw0pyj
The texture is located in the same folder where the OBJ is.

Thx.

**Comment by alemuntoni** [comment]
Hi @in3des ,
could you please share the files you are using?
just to reproduce the bug!
Thanks!

**Comment by in3des** [comment]
Hi @alemuntoni 
the original files are huge... 800mb+300
I will try to reproduce same issue with some small objects 

P.S. I found the problem exists if .mtl file is missing

**Comment by in3des** [comment]
here is the simplified version
to see the issue - just delete .mtl 
[test.zip](https://github.com/cnr-isti-vclab/meshlab/files/4469699/test.zip)

**Comment by alemuntoni** [comment]
Well, if the mtl is missing, obviously the texture cannot be loaded. And in the mtl you attached the texture path is global and cannot work if moved in some other directory or PC.

**Comment by sergiobd** [comment]
Just in case, you can open the mtl file as text and change the path of the textures to your path using **Find And Replace**
