### ISSUE TITLE
Export to off with polygonal checked produces invalid data [Windows 10]

### ISSUE THREAD

**Issue by hgroover** [cnr-isti-vclab/meshlab#638]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
Data files are in attached zip file.
Import mushroom-hat.obj (exported from Blender, a mesh with quad and triangle faces).
Mesh as imported appears as expected.
Export as off (with or without colors and textures - examples of both are included in the zip).
First unusual event: vertex entries appear to be properly defined in the resulting OFF file.
Face entries have the correct number of vertices listed but the vertex indices listed are all
16 (0 0 1 - note that OFF uses origin:0 index numbering).
An excerpt of face entries for both quad and triangle faces repeating the same index follows:
...
4 16 16 16 16 
4 16 16 16 16 
4 16 16 16 16 
3 16 16 16 
4 16 16 16 16 
3 16 16 16 
...
An excerpt of vertex entries 0-16 follows:
0 0 -1 
-0.19509 0 -0.980785 
-0.382683 0 -0.92388 
-0.55557 0 -0.83147 
-0.707107 0 -0.707107 
-0.83147 0 -0.55557 
-0.92388 0 -0.382683 
-0.980785 0 -0.19509 
-1 0 -0 
-0.980785 0 0.19509 
-0.92388 0 0.382683 
-0.83147 0 0.55557 
-0.707107 0 0.707107 
-0.55557 0 0.83147 
-0.382683 0 0.92388 
-0.19509 0 0.980785 
0 0 1 
...
Essentially, the OFF mesh is invalid as all faces consist of the same vertex. The resulting mesh does not describe a 3D shape (or 1D or 2D for that matter).
This problem is consistently reproducible using the OBJ file from the attached zip.
[mushroom-hat-obj-to-off-issuet.zip](https://github.com/cnr-isti-vclab/meshlab/files/4464308/mushroom-hat-obj-to-off-issuet.zip)
Another zip is attached with the Blender source, with the object moved to avoid crossing 0,0,0, and performing the same test with export to DAE (problem does not manifest because DAE forces the mesh to triangular).
[mushroom-hat-positives.zip](https://github.com/cnr-isti-vclab/meshlab/files/4464349/mushroom-hat-positives.zip)

...

**Comment by hgroover** [comment]
I should add for the sake of clarity that this problem only manifests with meshes containing quads. Some formats do not support polygons with edge count higher than 3 (or Blender's support for those formats does not cover polygon meshes). The Blender version used is 2.8.0 for Windows (latest Blender is 2.8.2).

**Comment by alemuntoni** [comment]
Fixed in [this commit](https://github.com/cnr-isti-vclab/meshlab/commit/c5c7633e6b6e8524f2b25c8aeee76dcfe9fe10ca). Thanks for reporting!
