### ISSUE TITLE
Embed an icon in AppImage

### ISSUE THREAD

**Issue by neildarlow** [cnr-isti-vclab/meshlab#641]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [x] feature request
- [ ] other (specify...)

#### Describe your issue
It is common to create a desktop launcher for applications packaged as  an AppImage.

To achieve this it helps if the AppImage contains an icon that can be specified for the launcher.
Please consider adding an application icon within the AppImage. Thank you.

**Comment by alemuntoni** [comment]
Hi @neildarlow,
for computing the AppImage of MeshLab we are using [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) in [this script](https://github.com/cnr-isti-vclab/meshlab/blob/master/install/linux/linux_appimages.sh). 
Following the linuxdeployqt guide, I obtain an [AppImage without icon](https://github.com/cnr-isti-vclab/meshlab/actions/runs/79955761), and I really don't know how to solve this issue.

If you, or someone else could point a solution I'll be happy to make an AppImage with an icon available :)

**Comment by neildarlow** [comment]
I have worked around this problem by installing **appimaged** which integrates MeshLab into the desktop with an icon.
