### ISSUE TITLE
windows_build.ps1 does not exist in install\windows folder

### ISSUE THREAD

**Issue by nefen** [cnr-isti-vclab/meshlab#655]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [x] other (specify...)
I caanot build in Windows
#### Describe your issue
There is not powershell script to build in windows
...

**Comment by alemuntoni** [comment]
In [this readme](https://github.com/cnr-isti-vclab/meshlab/tree/master/install/windows) there is written "work in progress". When it will be ready, also the `windows_build` script will be provided. Until then, you can look into the [github actions workflow script](https://github.com/cnr-isti-vclab/meshlab/blob/master/.github/workflows/CompileWindows.yml) or you can:
- download Qt (with QtScript) and QtCreator
- download visual studio
- open `meshlab.pro` with QtCreator and build.
