### ISSUE TITLE
error "GLEW Init: failed!"

### ISSUE THREAD

**Issue by Allvirus** [cnr-isti-vclab/meshlab#656]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

hi,guy
I call meshlabserver use shell on asp.net core webapi to run * .mlx script file, everything works fine.
But when I deploy my website with IIS , it didn't work ,the log display "GLEW Init: failed!". I dont kown  what's wrong , please hlep me!

**Comment by alemuntoni** [comment]
Hi @Allvirus, try to rename the `opengl32sw.dll` file to `opengl32.dll`.
Doing this, meshlabserver will use this implementation of opengl (which is entirely run on CPU) instead of the one of your graphic card, that doesn't seem to support newer opengl versions. 
Please let me know if this fix works.

**Comment by Allvirus** [comment]
I try before i ask this question ,but it didn't work.
![QQ截图20200428084743](https://user-images.githubusercontent.com/24863315/80434677-034af880-892d-11ea-8484-139c0af2e50f.png)
this is my error log . 
![QQ截图20200428085108](https://user-images.githubusercontent.com/24863315/80434828-6b014380-892d-11ea-9268-49261d06162a.png)
 i only have on graphic card ,that is gtx750Ti,  my cpu type is i5-4590 with a 
Core graphics, but i disable the core graphics device driver
i only can provide valid information for devic programs. in my opinion  i think the iis webserver Authority can't run meshlabserver even though i give admin authority.
So  I only created new project and didn't use iis webserver.  everything is ok.
But I'm curious what happened cause “GLEW Init: failed!”
