### ISSUE TITLE
AppImage crashes on Centos 8 on startup

### ISSUE THREAD

**Issue by waynehd** [cnr-isti-vclab/meshlab#658]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

[demo@right8 Downloads]$ ./MeshLab2020.03-linux.AppImage 
Current Plugins Dir is: /tmp/.mount_MeshLaFkAtW6/plugins 
Shader directory found '/tmp/.mount_MeshLaFkAtW6/shaders', and it contains 19 gdp files
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: QSslSocket: cannot resolve SSLeay_version
qt.network.ssl: QSslSocket: cannot call unresolved function SSLeay
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function sk_num
Segmentation fault (core dumped)

**Comment by alemuntoni** [comment]
I think this is related to [this](https://github.com/probonopd/linuxdeployqt/issues/400) issue. Right now we can only wait that linuxdeployqt solves this bug.

About the unresolved errors of qt (which are not causing the crash), you should install OpenSSL in your system.

**Comment by waynehd** [comment]
Openssl is installed. I was able to compile meshlab from source but I wanted to let you know about the problem. Thanks for the quick response.

 
[demo@right8 test]$ yum list openssl
Last metadata expiration check: 10:42:41 ago on Sun 26 Apr 2020 11:51:09 PM EDT.
Installed Packages
openssl.x86_64                                                                                                                                  1:1.1.1c-2.el8_1.1                                                                                                                                   @BaseOS
[demo@right8 test]$ 
 
 
-----Original message-----

**Comment by probonopd** [comment]
Appears to come from incompatible OpenSSL versions.
Looking at the error message, https://stackoverflow.com/questions/52210603/qt-and-openssl-incompatible-version-on-ubuntu may have relevant information.

Which exact version of OpenSSL (including the letter) is present on the build machine, and which exact version of OpenSSL (including the letter) is present on the target machine where it is crashing?

**Comment by alemuntoni** [comment]
About the OpenSSL problem, I just noticed that ubuntu 16.04 installs an old Qt 5.5 from apt. 
I'll adjust the workflow to use a newer Qt version asap.

**Comment by alemuntoni** [comment]
I adjusted the OpenSSL problem and now the AppImage runs on Fedora.
@waynehd could you please try [this appimage](https://github.com/cnr-isti-vclab/meshlab/actions/runs/91539435)? 
The fix will be available starting from version 2020.05.

**Comment by alemuntoni** [comment]
Thank you @probonopd for catching this issue!

**Comment by waynehd** [comment]
OK, I'll give it a try once it's out. Linux users used to snicker at Windows users for dll hell but the Linux community isn't much better. From what I read about AppImages you did what they recommend, use an older version of an OS but it seems that introduces other problems.

**Comment by probonopd** [comment]
Works nicely on Xubuntu 18.04. Thanks @alemuntoni

**Comment by alemuntoni** [comment]
Well, that was actually my fault :D I just hadn't thought about the fact that ubuntu 16.04 actually installs an old Qt version through apt!
