### ISSUE TITLE
OBJ file with Material link not work if Filename contain spaces.

### ISSUE THREAD

**Issue by Mannshoch** [cnr-isti-vclab/meshlab#66]
If an OBJ file is created with a Material.mtl, the material.mtl do not work if the material.mtl and/or the filenames of the textures contain spaces.

If you rename the file, open the .obj and.mtl with texteditor and remove the spaces. it works in Meshlab.

**Not work:**
test file.obj
test file.mtl
test texture.jpg

*.obj File
```
mtllib test file.mtl 
```
to
```
mtllib testfile.mtl 
```
and
*.mtl File
```
map_Kd test texture.jpg
```
to
```
map_Kd testtexture.jpg
```
**Works correct**
testfile.obj
testfile.mtl
testtexture.jpg

**Comment by mcallieri** [comment]
confirmed. 
I fixed the importer in the VCG Library, now it seems working.
I am not completely sure the format DOES allow for space in names and IDs (e.g. blender does add an underscore, when exporting), but this may solve compatibility with less strict exporters.
It will be available in the next MeshLab release (around 1 month).

**Comment by frederik-elwert** [comment]
This still seems to be a problem in Meshlab 2022.02, so maybe the fix hasn’t landed in a release yet?
