### ISSUE TITLE
Trying to transfer vertex colour of a point cloud to the mesh vol 2 : unsquashable bug

### ISSUE THREAD

**Issue by TheBricktop** [cnr-isti-vclab/meshlab#661]
Hello its me again with the same problem as before:
![obraz](https://user-images.githubusercontent.com/3866030/80489281-e1b73480-895f-11ea-8da1-bb222bd72e1d.png)
current release 2020.04, ive seen that @mcallieri tried to remove the requirement for point cloud to have faces but its still having the same issue.
The feature to transfer vertex colour to mesh would reaaaally help with my scans so im kinda bummed.
edit:

it also tries to find a texture for my target mesh in system32 folder : 
![obraz](https://user-images.githubusercontent.com/3866030/80490898-4c696f80-8962-11ea-9b37-b7c005e74330.png)

**Comment by mcallieri** [comment]
First of all: do not duplicate issues.
Second: as the commit was done in april, and the build was done on April 1st, it would be strange to find it in that release.
Each update does trigger an internal rebuild, but we do an "official" release only on the first of every month.
The internal build are under the "actions" tab. I believe this is the last one at the moment https://github.com/cnr-isti-vclab/meshlab/actions/runs/89180476

**Comment by TheBricktop** [comment]
@mcallieri 
Ok im very sorry that I didnt noticed that the  commits are done "since" the release, ive mistaken it for the commits that are IN the build. 
And sorry for the duplicate - it wasnt meant to nag anybody about the issue that we spoke about before. I thought that somehow it  still persisted after the build silly of me.
tl:dr i cant read
