### ISSUE TITLE
Issue exporting to .U3D

### ISSUE THREAD

**Issue by an775** [cnr-isti-vclab/meshlab#666]
[Mesh.zip](https://github.com/cnr-isti-vclab/meshlab/files/4568817/Mesh.zip)
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
Hi I am unable to export to ".u3d". Only the ".tex" file is generated. I am using MeshLab v2020.03 on Windows 10.

I imported the file as ".obj" (File generated using Blender. File attached [Mesh.zip](https://github.com/cnr-isti-vclab/meshlab/files/4568815/Mesh.zip) ) and when I export it to ".u3d", MeshLab is showing a message "Saved Mesh C:/***/mesh.u3d in 77 msec". But I cannot find any ".u3d" file except for the ".tex file"

Note: Earlier I was using the MeshLab 2016 version. At that time the issue was missing "IDTFConverter.exe" and I fixed it by downloading the zip file from GitHub and copy-pasting the "U3D_W32" Folder in the Plugins Folder. It used to work perfectly.

**Update: 03/05/2020**

I tried using several methods and I found one method was **successful**.

I am not sure of the reason why the issue is happening, but I will share my findings.

Installing two ".dll" files provided with older MeshLab versions and "Reload All" option in the Meshlab have solved the issue. Detailed description as below. 

After we install MeshLab, inside the folder "\MeshLab\plugins\U3D_W32", the only file in that is an "IDTFConverter.exe" (apart from some ".txt" files)

When I compared it with older Meshlab releases, I found some ".dll" files were also included in those downloads. These files include "IFXCore.dll" in the same folder of "IDTFConverter.exe" and an "IFXExporting.dll" which was included in a "Plugins" subfolder.

I downloaded the older version of Meshlab ([MeshLab-20191210-beta](https://github.com/cnr-isti-vclab/meshlab/releases/tag/7d5a377 )) from "https://github.com/cnr-isti-vclab/meshlab/releases" page (download the [source code.zip](https://github.com/cnr-isti-vclab/meshlab/archive/7d5a377.zip) file)

From the zip file, "**meshlab-7d5a377.zip\meshlab-7d5a377\src\distrib\plugins**" copy paste the folder "**U3D_W32**" to "**MeshLab\plugins**" folder as per instruction https://github.com/cnr-isti-vclab/meshlab/issues/33#issuecomment-269875248

Restart Meshlab and export to ".u3d" - [Both ".u3d" and ".tex" should be generated without fail]

This procedure mentioned until above solved the issue for file formats imported to MeshLab as ".COLLADA", ".PLY", ".STL", ".X3D"

For meshes imported as "**.OBJ**", the following procedure also was needed.

Restart MeshLab and export the mesh to ".u3d". Now **only** the ".tex" file is generated.

The solution to this I found was, once the ".tex" file is generated, in MeshLab go to "**File>Reload All**" option. Once we have done that, again Export Mesh as ".u3d" and this time the ".u3d" file should be generated

The ".tex" file should be generated **atleast once** before using "Reload All".

I am extremely sorry for the very long explanation. I am not a programmer at all, but I thought this information might help the developers to resolve this issue in the future releases.

Thank you...

**Comment by alemuntoni** [comment]
Hi @an775, yes this helps a lot. I'm pretty busy these days, but I'll try to solve once for all this problem as soon as possible. Thanks!

**Comment by quarky42** [comment]
I'm having this problem also and will try the workaround.  Thank you for sharing this while the developer is finding time to fix it.  I'm not sure why the installer is that hard to fix though, considering it should just be a matter of adding a couple DLLs to the installer and generating the updated installer that isn't missing the files.

**Comment by alemuntoni** [comment]
This issue should be solved on #713. You can test the u3d exporter by downloading the artifacts from the github actions tab ([windows](https://github.com/cnr-isti-vclab/meshlab/actions/runs/126283313), [mac](https://github.com/cnr-isti-vclab/meshlab/actions/runs/126283305), [linux](https://github.com/cnr-isti-vclab/meshlab/actions/runs/126283309)). The fix will be available starting from version 2020.07.
