### ISSUE TITLE
linux build system does not explain how to incorporate vcg

### ISSUE THREAD

**Issue by mderouss** [cnr-isti-vclab/meshlab#669]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [ x] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ x] other (specify...) build system 

#### Describe your issue
I am attempting to perform a Linux build of Meshlab. The environment is Xubuntu 19.10. 

I have cloned the repo given by github on the main Meshlab page. 

I have run the script linux_setup_env_ubuntu.sh which appeared to be successful.
I then ran the script linux_build.sh . This fails with this error -

> g++ -c -pipe -O3 -DNDEBUG -Wno-unused-result -fopenmp -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DMESHLAB_SCALAR=float -DMESHLAB_VERSION=2020.05 -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_SCRIPT_LIB -DQT_CORE_LIB -I. -I../.. -I/home/mark/Projects/Meshlab/meshlab/vcglib -isystem /usr/include/eigen3 -I../external/jhead-3.04 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtXmlPatterns -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtScript -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o filterscript.o filterscript.cpp
> filterparameter.cpp:28:10: fatal error: vcg/math/matrix44.h: No such file or directory
>    28 | #include <vcg/math/matrix44.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[1]: *** [Makefile:488: filterparameter.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> In file included from filterscript.h:27,
>                  from filterscript.cpp:30:
> filterparameter.h:33:10: fatal error: vcg/math/matrix44.h: No such file or directory
>    33 | #include <vcg/math/matrix44.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> In file included from interfaces.h:28,
>                  from interfaces.cpp:1:
> filterparameter.h:33:10: fatal error: vcg/math/matrix44.h: No such file or directory
>    33 | #include <vcg/math/matrix44.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[1]: *** [Makefile:499: interfaces.o] Error 1
> make[1]: *** [Makefile:504: filterscript.o] Error 1

It's apparent that the directory /home/mark/Projects/Meshlab/meshlab/vcglib, referred to in the compiler includes, is empty. I notice that there is no 'meshlab/vcglib' in the meshlab repo, instead there appears to be a reference to 'vcglib' followed by what looks like a git revision. 

The build documentation does not explain, anywhere that I have found so far, how to populate the 'vcglib' directory, if indeed that is where the missing include should be. My expectation was that one of the 'linux' scripts would do this if necessary. If it's up to me to checkout vcglib as a separate repo and build it before running the scripts, some explanation would be nice, because not everyone ( me very definitely included ! ) has the git-fu to work it out for themselves. But really the issue is simply 'how do I perform a linux build that resolves the problem given above ?'.

**Comment by alemuntoni** [comment]
As you can see [here](https://github.com/cnr-isti-vclab/meshlab/blob/master/src/README.md#compiling-meshlab), for cloning the meshlab repository the argument `--recursive` is needed. It cannot be done by a script because the script would be inside an already cloned repository.

**Comment by mderouss** [comment]
Ah, ok. Sorry, I'm just miss-parsing the instructions. I read 'After setting up the Qt environment:' and read it as 'here is how you set up the Qt environment', but I didn't have to do that so I skipped that step :).  No problem, everything builds and works fine now, thanks.
