### ISSUE TITLE
[question]Baking texture size cap

### ISSUE THREAD

**Issue by TheBricktop** [cnr-isti-vclab/meshlab#670]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows

#### What type of issue is?
- [x] bug or unexpected behavior

#### Describe your issue
After succesfully baking 8k texture on my ancient 670 gtx with 2gb ram I tried to fry it on 16k but meshlab handed me the popup that the 16384 size is invalid.
Is there a hard cap on 8k or the hardware limitations are manifesting themselves like that?
Im thinking about aquiring the 12 gb ram card for that reason but only if this would solve the issue.
![obraz](https://user-images.githubusercontent.com/3866030/81065853-8a274480-8edc-11ea-97cd-37b1093b8337.png)

**Comment by mcallieri** [comment]
As far as I can see, there is no hardcoded limit.
The strange thing is that the only check that returns that error message is if the width is "0 or less". Maybe you are using an old version or you entered the number wrongly (maybe an extraneous char when copy-pasting?)
I tried on my machine, and I'm able to bake 16k and 32k textures (even though it took 1 hour for a 3Mtri model)
