### ISSUE TITLE
[Critical] The app is constantly crashing almost on all commands on iMac Pro with Radeon Pro Vega 56 8 GB graphics

### ISSUE THREAD

**Issue by dmitry-kovba** [cnr-isti-vclab/meshlab#675]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [x] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

The app is constantly crashing almost on all commands on iMac Pro with Radeon Pro Vega 56 8 GB graphics. At the same time it works fine in a virtual Windows 10 on the same mac. Please provide more details about the information that you need to fix this issue.

**Comment by dmitry-kovba** [comment]
[CrashReport.txt](https://github.com/cnr-isti-vclab/meshlab/files/4590473/CrashReport.txt)

**Comment by alemuntoni** [comment]
Hi, could you please try the [last release](https://github.com/cnr-isti-vclab/meshlab/releases/tag/Meshlab-2020.05)? It has been just uploaded with some fixed for MacOS.
