### ISSUE TITLE
Meshlab crashes if the filter "Repair non Manifold edges by splitting verticles"

### ISSUE THREAD

**Issue by Mikhail-Kozlov-MRI** [cnr-isti-vclab/meshlab#679]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [ ] Linux
- [x] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
[eyes_staircase_non_manifold.zip](https://github.com/cnr-isti-vclab/meshlab/files/4606834/eyes_staircase_non_manifold.zip)

If this mesh (rather simple) is loaded to Meshlab 2020.05 and the filter "Repair non Manifold edges by splitting verticles" is selected Meshlab 2020.05 crashes. The crash is reproducible always.

Sincerely,

Mikhail

**Comment by Mikhail-Kozlov-MRI** [comment]
Sorry for non-perfect submission of my crash report. I am using this interface the first time.

Sincerely,
Mikhail

**Comment by KuzMaxOriginal** [comment]
Same

**Comment by unlugi** [comment]
Is there an update to this issue, I am still experiencing it. Thank you.

**Comment by tobiasvogel** [comment]
Even occurs with a mesh consisting of a single cube generated by the following line in OpenSCAD:
`cube([1,1,1],center=true);`

**Comment by alemuntoni** [comment]
I don't know exactly when, but this issue has been already solved.
2021.05 does not crash anymore.
