### ISSUE TITLE
MeshLab on MS Store [Windows]

### ISSUE THREAD

**Issue by Saijin-Naib** [cnr-isti-vclab/meshlab#681]
#### Check all platforms you experienced the issue
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [x] feature request
- [ ] other (specify...)

#### Describe your issue
Would you be willing to distribute a "donation" version of MeshLab on the MS Store?
I like to think of this as a way for you to get donations, and for users to get the convenience of store-distributed apps.

For instance, I make use of Paint.NET and LibreOffice Vanilla in this way. I would certainly make use of MeshLab this way.

**Comment by alemuntoni** [comment]
This is completed now! :)
MeshLab is available on the [Microsoft Store](https://apps.microsoft.com/detail/9N4TL5DXC6C0?hl=en-US&gl=US)!

**Comment by Saijin-Naib** [comment]
Congratulations! I hope this makes it easier for folks to use MeshLab. 

I no longer use Windows, but I am working towards packaging MeshLab for Alpine Linux 🤓

**Comment by alemuntoni** [comment]
@Saijin-Naib I don't know the package manager used by Alpine Linux, but let me know if you need some help on building MeshLab!
For Linux we are going to release the new version on Flatpak very soon :)
