### ISSUE TITLE
How to export sub-meshes in .obj file separately?

### ISSUE THREAD

**Issue by kracon7** [cnr-isti-vclab/meshlab#684]
Hi,
I'm using meshlab 1.3.2 on Ubuntu 16.04

I'm new to Meshlab and felt pretty struggle with my task as described below. 
I have a .obj file that has multiple sub-meshes in it. I want to export each component into different .stl files for later process. Is it possible to do this in a automated fashion (such as by calling meshlabserver in command line)?

![image](https://user-images.githubusercontent.com/40022305/82274619-35f17b00-9946-11ea-8294-7d2e674adebe.png)

![IMG_8031](https://user-images.githubusercontent.com/40022305/82274627-3c7ff280-9946-11ea-9b20-a9a0526ded23.JPG)

**Comment by cignoni** [comment]
Use the filter "Split in Connected Component" and save each layer separately
