### ISSUE TITLE
[manjaro i3] Segfault on right click

### ISSUE THREAD

**Issue by clbarnes** [cnr-isti-vclab/meshlab#686]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

Right clicking crashes meshlab with a segfault, if there is a mesh loaded. The only logging is

    [1]    48315 segmentation fault (core dumped)  ./Downloads/MeshLab2020.03-linux.AppImage

This is the case when downloading the AppImage from the website (latest release), and when building from source (master branch).

When there is no mesh loaded, right clicking does not cause a segfault, but I get this log line:

    LOG: 1 There are gl errors: invalid operation

**Comment by alemuntoni** [comment]
I had the same problem on ubuntu 20.04 on my machine.
I think it is just a bug on some graphic drivers (it crashes inside a gl draw call).
In my case, I solved changing an option on the nvidia drivers: go to nvidia X server settings -> PRIME profiles, and select "Performance mode". Default setting was "On-Demand", and for some reason was causing the problem.
Hope it helps!

**Comment by mikegee81** [comment]
I am encountering a similar segfault crash. I am running Ubuntu 20.04 with AMD graphics (Gigabyte RX580) ROCM amdgpu, 3.3-19, 5.4.0-31-lowlatency, x86_64: installed.

**Comment by fodiator** [comment]
Similar segfault crash here, running Ubuntu 20.04 with AMD graphics (Gigabyte RX5600) Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-38-generic
OS Type: 64-bit
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31,4 GiB
