### ISSUE TITLE
Meshlab not accepting valid *.mtl syntax for scaling.

### ISSUE THREAD

**Issue by ForceConstant** [cnr-isti-vclab/meshlab#688]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [ ] Linux
- [x] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
Meshlab isn't able to open *.obj files that have scale options set in *.mtl 
Such as: `map_Kd -s 1 1 1 capsule0.jpg`  This is valid obj/mtl syntax. I get "failure loading textures". I tried on Windows and Linux. Note above is trivial case since the scale is being set to 1, but it is useful if changing scales. Attached is an example.

[capsule.obj.zip](https://github.com/cnr-isti-vclab/meshlab/files/4662157/capsule.obj.zip)

..

**Comment by alemuntoni** [comment]
Now the texture filename is read correctly.
However, texture options are ignored since they are not supported by meshlab
