### ISSUE TITLE
Can improve the measure?

### ISSUE THREAD

**Issue by eexpress** [cnr-isti-vclab/meshlab#69]
meshlab only has point to point measure. I want face to face one, like https://a360.autodesk.com/viewer/.

**Comment by mcallieri** [comment]
What do you mean by "face to face"? Geodesic distance? distance along an axis?
the web viewer shown in the webpage you linked has no measurement feature (and the app version needs registration)
From the help, I do not understand what is your request https://knowledge.autodesk.com/support/a360/getting-started/caas/CloudHelp/cloudhelp/ENU/Autodesk-360-New/files/GUID-522901FB-DDBF-49F3-B20F-110F14A1AC34-htm.html

p.s. as my gradma said: the "I want" plant doesn't grow, not even in the king's garden.

**Comment by eexpress** [comment]
surface to surface, surface to point, surface to line. sorry about my expression above.

a360 web has magic measure tools when preview stl.

![p-noexif-2017-02-06_22-32-11](https://cloud.githubusercontent.com/assets/700793/22650939/237e41e0-ecbc-11e6-8750-40dd09a1b8a7.jpg)

**Comment by mcallieri** [comment]
In this case, the measurement seems to be "distance between two parallel polygonal faces", which only work on CAD-like models... I am not sure we can even replicate this, as MeshLab uses triangular faces, and not polygons. 
In the future, we MAY add a "distance along axis (X, Y or Z)" tool, but "distance along the normal of a face" or "distance between parallel faces" is probably unusable in the general context of MeshLab, sorry.
