### ISSUE TITLE
Increasing background grid line width.

### ISSUE THREAD

**Issue by MedievalMatt** [cnr-isti-vclab/meshlab#690]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [X] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [X] other (request for clarification)

#### Describe your issue
I have a model I've opened in Meshlab 2020.5 which I am exporting to serve as the cover of an edited volume using the snapshot function and using eight virtual screens. The series editor would like to include the background grid, but wants it more prominent -- by which he means that he wants the grid more visible when exporting. I can see where I need to change line width for models and the size of the grid, but not how to increase the stroke width of those lines. Can this be done? I'm willing to tweak the underlying libraries and recompile if needs be, but I'd rather not if there's a quick fix I'm just not seeing.
...

**Comment by alemuntoni** [comment]
There is still not a feature for doing this. The implementation of the filter is in the decorate_background plugin, right now the only way of doing this is change the grid width on the code and then recompile the plugin.

**Comment by alemuntoni** [comment]
Ok, thanks to @cignoni the feature has been implemented on [this commit](https://github.com/cnr-isti-vclab/meshlab/commit/b51f9e01ac53e92fef562a23d042438a68e4512c). You can download the built version for macos [here](https://github.com/cnr-isti-vclab/meshlab/actions/runs/144626333), and the feature will be available starting from 2020.07!

**Comment by MedievalMatt** [comment]
Awesome!  Thanks so much, guys.
