### ISSUE TITLE
batch conversion from binay ply to ascii ply, How to uncheck the binary encoding using the meshlabserver?

### ISSUE THREAD

**Issue by TouchDeeper** [cnr-isti-vclab/meshlab#697]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [x] other (specify...)

#### Describe your issue
To do batch conversion, I can use the script below:
```
for file in *.ply; do
    meshlabserver -i "$file" -o "${file%.*}.obj" # -om vc
done
```
But How can I uncheck the Binary encoding as shown in the figure below?
![image](https://user-images.githubusercontent.com/39310744/83013968-7476ec00-a050-11ea-99ee-c736031bfc11.png)

Ubuntu16.04
MeshLab version: 1.3.2

**Comment by martin-frbg** [comment]
I believe this was implemented last year in #445, adding a new "sa" parameter - of course this means a much more recent version than 1.3.2, which seems to be from around 2012 or so.
