### ISSUE TITLE
Convert binary_little_endian .ply file .obj ?

### ISSUE THREAD

**Issue by jagadish482** [cnr-isti-vclab/meshlab#70]
Hi,
I am working on getting 3d mesh from set of images. I got 3d mesh from set of images using some open source libraries. This 3d mesh file (.ply and .png(texture) generated from libraries). For this I am writing android app . In this I am facing loading 3d mesh file in android app still now i didn't got any information for loading .ply file android app but I can load .obj files. so here I need help from you that is can you tell me any library for converting .ply file to .obj. 

Actually I converted .ply(.ply and .png ) file into .obj  (.obj, .mtl, and .png) using MeshLab and I loaded these 3d mesh file means .obj file in my android app so like this I have to do programatically. Please help  me to solve this and I am new to this.

**Comment by mcallieri** [comment]
This help request is not relevant here, sorry.
MeshLab already load/save both ply and obj, and meshlabserver may be used to batch-convert.
