### ISSUE TITLE
The monthly built meshlab is not an executable file

### ISSUE THREAD

**Issue by oleg-alexandrov** [cnr-isti-vclab/meshlab#703]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [ x] Linux
- [ ] Every platform

#### What type of issue is?
- [ x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

I downloaded MeshLab2020.06-linux.zip from the releases page. It is nice that such releases are available, and that they can be installed/run without root access.

I have one minor quibble though. The unzipped usr/bin/meshlab should be an executable file, otherwise it won't run. Same for meshlabserver. Sure one can make it executable by hand, but it looks like a little oversight.

There is also the AppRun program (also not made executable) which seems to be another binary copy of the meshlab executable, I wonder what that one is for as the matlab.desktop shortcut calls usr/bin/meshlab as well. 

Thanks.

**Comment by alemuntoni** [comment]
Thanks for pointing this!
I solved this in the last commit, starting from 2020.07 binaries will be executable!
