### ISSUE TITLE
Bug with multiple open meshes?

### ISSUE THREAD

**Issue by oleg-alexandrov** [cnr-isti-vclab/meshlab#704]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [ x] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

I am running the latest 2020.06 meshlab. When opening a couple of meshes from the command line, like:

 meshlab file1.ply file2.ply

the pane on the right allows for turning on and off each mesh. Something changed in the last several months in the code, as now when I turn off a mesh, the mesh looks in that pane as still open (that little eye picture is meant to show a closed eye, but it still shows an open eye). 

Worse, if I resize that pane on the right showing the layers, it starts showing junk pixels. I feel that some Qt signal meant to refresh the pane does not get transmitted properly, so it is some UI change which was made recently that triggers this issue.

**Comment by alemuntoni** [comment]
I'm not able to replicate this beahviour. When you say "turn off a mesh", do you mean that you click in the eye for changing the visibility of the mesh?

**Comment by oleg-alexandrov** [comment]
Yes. I click on the eye, the mesh gets turned off, but the eye stays open. I hope you start the viewer with two meshes as described earlier. Maybe if one opens them one after another from the GUI it could be different.

I also wonder if resizing the pane on the right works for you, after two meshes are open. That pane with white background on the right having the layers and the mesh viewing area on the left with blue background are separated by a vertical line. Normally one can grab that line with the mouse and drag it left and right. When I drag it left, the pane does not refresh correctly. 

If you still think you can't reproduce it I could try debugging it myself.

**Comment by alemuntoni** [comment]
Yep, can't reproduce. Works correctly on my side and the right panel resizes correctly. 
What distro and desktop environment are you using?

**Comment by oleg-alexandrov** [comment]
Thank you for trying. I use Ubuntu 16 with FVWM over VNC (sorry, old
school). I don't think that is the problem. Looks like a Qt signal-slot
communication problem to me and it worked when I built Meshlab from source
a few months ago. I will try to debug it in the next several days. I
appreciate your attention.

**Comment by fdifonzo** [comment]
Same issue on Windows 10 with three .ply's.
I closed and reopened MeshLab and it worked correctly.
Looks like a bug.
