### ISSUE TITLE
Design of the layer management pane

### ISSUE THREAD

**Issue by oleg-alexandrov** [cnr-isti-vclab/meshlab#706]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [ x] Linux
- [ ] Every platform

#### What type of issue is?
- [x ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

If meshlab has more than one mesh open, there is a pane on the right, that normally says "project 1", that allows one to turn meshes on and off (show or hide meshes). It appears to have some artifacts:

1. When launching: meshlab mesh1.ply mesh2.ply mesh3.ply mesh4.ply the pane on the right shows up, then disappears, then shows up and disappears, etc, 4 times. Its width also changes each time it appears if the mesh file names get longer. 

2. After the meshes are open, if one clicks on the "Open" icon from the toolbar, to add another mesh, the pane on the right disappears temporarily. It comes back after the new mesh is opened or after the "open" dialog gets canceled.

I looked at the code. That pane is at various times made visible or invisible. I would think one could have a permanent Qsplitter with the mesh on the left and the pane on the right, and then these widgets should not disappear or be resized each time a mesh is added.

**Comment by alemuntoni** [comment]
Thank you @oleg-alexandrov for solving this issue :)
