### ISSUE TITLE
Windows and Chrome showing Warnings ⚠

### ISSUE THREAD

**Issue by TutorialsUp** [cnr-isti-vclab/meshlab#709]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [x] other (specify...)

#### Describe your issue
why google chrome and windows saying this app might be dangerous.
i try to download for this link: http://www.meshlab.net/#download
what i do? ignore or not?
![Captur11111e](https://user-images.githubusercontent.com/66201476/83689193-0c07ac00-a608-11ea-8fec-d3f1fc7416e7.PNG)
![Annotation 2020-06-04 015819](https://user-images.githubusercontent.com/66201476/83689201-0d38d900-a608-11ea-87b5-632f08da4d46.png)

...

**Comment by oleg-alexandrov** [comment]
That is the default warning for any program on Windows. Lucky you, my Windows system does not even offer the "Run anyway" option. If you are curious if Meshlab is safe, I can tell you, as a user, and not a developer for this package, that it keeps track of the number of meshes you save and may offer you some pop-ups on occasion ask you to cheer up its developers, but in recent versions the user is allowed to opt out of these. Other than that the software is harmless and the code is open.

**Comment by TutorialsUp** [comment]
hmm I think I need to ignore..
anyways the "Run anyway" option show up when i click on "more info"
![Captureeeee](https://user-images.githubusercontent.com/66201476/83733117-89620980-a666-11ea-8f6e-5978c08b19d6.PNG)

Thanks

**Comment by oleg-alexandrov** [comment]
Yes, you will have to run it anyway, and prepare for the world to end. :) Seriously, Windows bugs people like that all the time. If you got meshlab from this source, it is the official version, so you can run it without concerns.

**Comment by alemuntoni** [comment]
I can confirm that these warnings are default for every application that is not signed on windows.
We are planning to sign windows installers, but we don't know when.
