### ISSUE TITLE
Meshlab 2016.12 immediately crashes on Windows 7

### ISSUE THREAD

**Issue by jhpoosthoek** [cnr-isti-vclab/meshlab#71]
I installed MeshLab2016.12.exe on Windows 7.
meshlab.exe does not work, it immediately crashes.

Before I installed MeshLabDevel_v134BETA_64bit_2014_05_28.exe. Here meshlab.exe works fine.

Any idea what might be causing the crash?

**Comment by mcallieri** [comment]
Already reported in issue #29 
There seems to be a problem with OpenGL context on soem specific combination of videocard/drivers. Mostly happens on notebook, in particular when only an integrated videocard is present, or when there is integrated-accelerated dual cards, and theintegrated is used.
We are working on it. In the meantime, reinstalling/updating drivers may help, but not always.

- be sure to use the non-integrated videocard
- be sure the drivers are updated

I am closing this one as it is a replicated entry
