### ISSUE TITLE
Drag&drop missing in 2020.06

### ISSUE THREAD

**Issue by cbuchart** [cnr-isti-vclab/meshlab#712]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [x] feature request
- [ ] other (specify...)

#### Describe your issue

I've been using MeshLab 2016.12 until today that I upgraded to MeshLab 2020.06. Everything is working flawlessly but how I have to open files.

Until now it was enough to drag the file from the Files Explorer on MeshLab to open it (as a new project if none open, or appending it into current one). It is a very useful way to open files.

2020.06 seems to have removed / disabled such behavior. I've tested with .obj and .xyz files with both a project created and with no project open.

Is there any option to enable it? If not, please consider bringing back such handy feature.

**Comment by alemuntoni** [comment]
This feature was not supposed to be removed, it just disappeared for some reason starting from 2020.04. I'll investigate to bring it back for the next release. Thanks for reporting it!
Until then, you can open meshles by simply go to File->Import Mesh, or with the shortcut "Ctrl+I".

**Comment by cbuchart** [comment]
Thanks! It is funny, it seems to be working now. When I reported the issue I've just upgraded and was the first time I opened the application. Tried several times to import through D&P unsuccessfully. Accidentally I closed the application and when open it again it worked. May be just a first time bug?

**Comment by mcallieri** [comment]
Just checked... it seems like that, in the frst run, some features like the drag&drop and the file associations are not _yet_ active, but if you leave it alone, everything settles.

**Comment by alemuntoni** [comment]
It's actually related with admin privileges. When meshlab is run with admin privileges (which happens when launched from the installer) drag&drop does not work. I think Windows does not allow copying/moving files in this case for security reasons.

**Comment by mcallieri** [comment]
O_O
You are right... I never noticed it. I've tried, and this applies to all applications. drag&drop is disabled when "run as administrator". Beats me.
The only thing we _might_ do is not have the "launch MeshLab" at the end of installer, to avoid confusion. For the rest, then, it is "working as intended"
