### ISSUE TITLE
Meshlab take long time to open

### ISSUE THREAD

**Issue by Eberty** [cnr-isti-vclab/meshlab#714]
#### Check all platforms you experienced the issue
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

In the new version of meshlab (release 1-june-2020) installed by `snap`, takes about a minute to start (gui and meshlabserver) every time when open is requested.

I did the test on three different machines, using 3 different Ubuntu versions (16.04, 18.04 and 19.10), and in all machines the meshlab take a long time to start. One of these Ubuntu versions was even clean (I installed it because I thought it might be a conflict with other older apps) but the delay continued.

Other error also occurred on the three machines:  `Failed to rename ~/snap/meshlab/5/.local/share/mime/application/x-kexiproject-sqlite2.xml.new as ~/snap/meshlab/5/.local/share/mime/application/x-kexiproject-sqlite2.xml: No such file or directory`

**Comment by alemuntoni** [comment]
As far as I know, all the snap applications take a long time to start. Some applications I installed on my machine through snap: spotify, remarkable, discord. All these applications require similar times to start. On the other hand, if you try to run the MeshLab AppImage, it starts almost instantly. 
We are now using [this](https://github.com/cnr-isti-vclab/meshlab/blob/master/snapcraft.yaml) script to generate the snap package. I don't know much of snap packages, and I don't know if there are some magic tricks to make snap packages to start faster. In that case, PR are welcome.
But it seems to me that this is a snap issue, and not a meshlab issue.
