### ISSUE TITLE
2020.06 UI elements unreadable on macOS with dark mode

### ISSUE THREAD

**Issue by piiq** [cnr-isti-vclab/meshlab#718]
#### Check all platforms you experienced the issue
- [ ] Windows
- [x] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [x] other (UI improvement)

#### Describe your issue
When using the latest version of Meshlab 2020 on macOS 10.15.5 with dark UI mode set, the list of imported files and the filter log are unreadable (attached screenshot)
![image](https://user-images.githubusercontent.com/11668535/84164941-c7eb3000-aa7b-11ea-9873-5b7979d51749.png)

#### Possible solutions
- Either make a UI theme for meshlab that supports macOS dark mode. The minumum for such theme would require inverting text colors in the places where dark text appears on dark background. The maximum would require inverting/changing colors of some UI icons that appear dark on dark background.
- Or make background colors for the mesh list and the filter log changeable in the settings (similar to how the 3d scene background can be changed). This will make possible to simply change the background color in the 2 UI sections where dark text is rendered over dark background to a bright color making the text readable.
...

**Comment by alemuntoni** [comment]
Solved the issue in the [last commit](https://github.com/cnr-isti-vclab/meshlab/commit/26f69a669c27a890766aa018210960fedd764e52), will be available in the next version!

**Comment by qkqsb** [comment]
I am experiencing this issue on Linux, and it is not clear to me if/how this fix can be applied.
