### ISSUE TITLE
Option to reverse the wheel mouse roller on zoom in-zoom out.

### ISSUE THREAD

**Issue by Wayne5202** [cnr-isti-vclab/meshlab#721]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [ ] Linux
- [x] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [x] feature request
- [ ] other (specify...)

#### Describe your issue
Option to reverse the wheel mouse roller on zoom in-zoom out. 
All my cad/cam softwares are the opposite of MechLab and it is driving me crazy switching from them to MeshLab application.
Meshlab_64bit_fp v2020.06
...

**Comment by Wayne5202** [comment]
Thank you for the edit.  I am new to the github issues dialog forms.

**Comment by alemuntoni** [comment]
This feature has been implemented on PR #737, will be available starting from version 2020.07

**Comment by Wayne5202** [comment]
Thank you very much.  It may appear to be a minor change, but to me, it is a world of difference.  I will be using Meshlab more often.  Thank you again.
