### ISSUE TITLE
Meshlab does not start on win7

### ISSUE THREAD

**Issue by anbellit** [cnr-isti-vclab/meshlab#722]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
When I launch Meshlab 2020.06 in a PC with Win7, the program doesn't start.
In TaskManager I see the process Meshlab running, but I don't see the graphic window

PC Intel I7, 16 Gb RAM, Win7 professional.
Graphic board NVIDIA Quadro K600, 1 Gb RAM DDR3.
Meshlab 2020.05 runs well

The same program 2020.06 runs well in a PC Win10, 16GbRAM, NVIDIA Quadro P620, 4Gb Video RAM

**Comment by alemuntoni** [comment]
Windows 7 support has ended on jan 2020, I am not sure that every library we rely on still support it.
