### ISSUE TITLE
Meshlab crashed after raster importing

### ISSUE THREAD

**Issue by lieti** [cnr-isti-vclab/meshlab#723]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### 
Meshlab version 2000.06 (same problem on older version)
Win10 Pro (1909)
i9-9900K, 64 GB RAM, Nvidia GTX 1070 (8GB memory)

Hi, when I trying to import certain rasters I´m facing to direct crash. And I cannot find reason, because it seems that it is not related with size of raster or format (JPG, PNG).
One is in the attachement.

Thanks for advice
![DMT50cm_STU_Civil_NestichMod](https://user-images.githubusercontent.com/34206797/84918077-7583c200-b0c0-11ea-804d-74aa02c5c2d7.png)

**Comment by alemuntoni** [comment]
I am not experiencing any crash after importing the attached image, on any platform. 
Does it crash after just importing the image or did you import some other rasters/meshes before?
