### ISSUE TITLE
[Any OS] Set Texture on imported .obj uses hard-wired root directory "/"

### ISSUE THREAD

**Issue by welch** [cnr-isti-vclab/meshlab#728]
Meshlab v 2020.06

#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [X] Mac OS 10.14.5
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [X] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
The "Filters/Texture/Set Texture" for an imported OBJ fails, 
because it attempts to load from the root directory instead of
the local directory.

Steps to reproduce:
1. import foo.obj from working directory
2. texture foo.png is in same directory
3. Choose Filters/Texture/Set Texture, with "foo.png" as the texture filename
4. click Apply
5. Error popup appears, "In mesh file /Users/welch/foo.obj : Failure loading textures: /foo.png" 
(this popup appears again after you dismiss it the first time)
6. Copy foo.png to /foo.png
7. Choose Filters/Texture/Set Texture, "foo.png" is the texture filename
8. Texture import succeeds

Bonus related bug: When texture file does not exist, the described behavior of
creating a default texture and saving it to the named texture file does
happen, and texture is written to the directory containing the .obj.
However, this cannot subsequently be reloaded, because of the root directory
bug above

**Comment by ltxitai** [comment]
This reproduces for me 100% of the times too. Basically makes the "Set texture" filter completely unusable.

**Comment by alemuntoni** [comment]
Fix will be available in the next release!
