### ISSUE TITLE
How can i use BackFace Culling in meshlab2020?

### ISSUE THREAD

**Issue by Tomzxcv** [cnr-isti-vclab/meshlab#729]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [x] feature request
- [ ] other (specify...)

#### Describe your issue
How can i use BackFace Culling in meshlab2020
...

####Guidelines for a good issue

Before submitting an issue: 

- be as detailed as possible. If the issue is related to a specific mesh or file, please attach it. Make sure that the problem is reproducible; 
- specify the operative system you are using and its version/distribution; if it is possible, verify if the problem persists in other platforms;
- bspecify the MeshLab version you are using and be sure that your issue also happens on the last MeshLab version;
- check if your issue has been already reported by someone else. In this case, do not open another issue: just add your experience in the existing issue;
- If the issue is specific of a platform, please specify it on the subject in square brackets (example: `[MacOS] crash when opening obj`);
- delete these guidelines before submitting :)

**Comment by mcallieri** [comment]
Right-side panel (layer panel), in the middle part, there are tabs, controlling the appearance of the different elements. On the tab controlling the faces, there are the options to set the backface behavior: single-side lighting, double side lighting, double-side lighting + colors, CULL
