### ISSUE TITLE
Point size does not change

### ISSUE THREAD

**Issue by msalah80** [cnr-isti-vclab/meshlab#73]
I am using meshlab_64bit_fp v2016.12 on windows 10. When I visualize point clouds, sometimes I want to enlarge the size of the points. Changing the value of MeshLab::Appearance::pointSize does not have any effect, even when saved. I am not sure what is wrong, because it works on an older version of meshLab on another notebook with windows 7.

**Comment by granzuglia** [comment]
I confirm...but you can more easily use the "point size" slider on the per points tab in the side graphics options. See the attached the picture in order to locate it.

![point_size](https://cloud.githubusercontent.com/assets/13417796/22853467/689ecdfa-f057-11e6-9794-2254f9d070ce.jpg)

**Comment by msalah80** [comment]
worked. thanks !
