### ISSUE TITLE
snap package: needs desktop file

### ISSUE THREAD

**Issue by paroj** [cnr-isti-vclab/meshlab#731]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [x] feature request
- [ ] other (specify...)

#### Describe your issue

Currently meshlab is not available in the "open with" menu and the gnome shell launcher. This is due to a missing desktop file, which causes it not being recognized as a GUI application.
See: https://snapcraft.io/docs/snapcraft-app-and-service-metadata

**Comment by alemuntoni** [comment]
This issue has been already solved [in this commit](https://github.com/cnr-isti-vclab/meshlab/commit/37ca053bb2464d640457037a6f34745db3e30a96). On snap store will be available starting from 2020.07 version
