### ISSUE TITLE
[Windows] Bug loading ASCII STL

### ISSUE THREAD

**Issue by GiovanniSer** [cnr-isti-vclab/meshlab#732]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x]  Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

In Meshlab 64 bit 2020.05 - For many years I have successfully used my parser written in Lisp (autoCAD and IntelliCAD). Now I have a problem that I can't decode. Example, sorry for the verbose.
This file is OK 
-------------------------------------------------code
```
solid 2STL_V_1_0
 facet normal 0 0 0
  outer loop
   vertex -2.92760075 -0.53119241 -1.99058534E-16
   vertex -3.25250799E-17 -0.53119241 -3.25250799E-17
   vertex -2.61285774E-17 -0.68181818 -0.25509204
  endloop
 endfacet
 facet normal 0 0 0
  outer loop
   vertex -2.61285774E-17 -0.68181818 -0.25509204
   vertex -2.92760075 -0.68181818 -0.25509204
   vertex -2.92760075 -0.53119241 -1.99058534E-16
  endloop
 endfacet
 facet normal 0 0 0
  outer loop
   vertex -2.92760075 -0.53119241 -1.99058534E-16
   vertex -2.92760075 0.53119241 -1.99058534E-16
   vertex -3.25250799E-17 0.53119241 -3.25250799E-17
  endloop
 endfacet
 facet normal 0 0 0
  outer loop
   vertex -3.25250799E-17 0.53119241 -3.25250799E-17
   vertex 1.56193665E-17 -0.53119241 -5.55111512E-17
   vertex -2.92760075 -0.53119241 -1.99058534E-16
  endloop
 endfacet
 facet normal 0 0 0
  outer loop
   vertex -2.92760075 0.53119241 -1.99058534E-16
   vertex -3.25250799E-17 0.53119241 -3.25250799E-17
   vertex -2.61285774E-17 0.68181818 -0.25509204
  endloop
 endfacet
 facet normal 0 0 0
  outer loop
   vertex -2.61285774E-17 0.68181818 -0.25509204
   vertex -2.92760075 0.68181818 -0.25509204
   vertex -2.92760075 0.53119241 -1.99058534E-16
  endloop
 endfacet
endsolid 2STL_V_1_0
```
--------------------------------------------end code
BUT the SAME FILE but without 2 faces does not work. Error details "Malformed file"
-------------------------------------------code
```
solid 2STL_V_1_0
 facet normal 0 0 0
  outer loop
   vertex -2.92760075 -0.53119241 -1.99058534E-16
   vertex -3.25250799E-17 -0.53119241 -3.25250799E-17
   vertex -2.61285774E-17 -0.68181818 -0.25509204
  endloop
 endfacet
 facet normal 0 0 0
  outer loop
   vertex -2.61285774E-17 -0.68181818 -0.25509204
   vertex -2.92760075 -0.68181818 -0.25509204
   vertex -2.92760075 -0.53119241 -1.99058534E-16
  endloop
 endfacet
 facet normal 0 0 0
  outer loop
   vertex -2.92760075 -0.53119241 -1.99058534E-16
   vertex -2.92760075 0.53119241 -1.99058534E-16
   vertex -3.25250799E-17 0.53119241 -3.25250799E-17
  endloop
 endfacet
 facet normal 0 0 0
  outer loop
   vertex -3.25250799E-17 0.53119241 -3.25250799E-17
   vertex 1.56193665E-17 -0.53119241 -5.55111512E-17
   vertex -2.92760075 -0.53119241 -1.99058534E-16
  endloop
 endfacet
endsolid 2STL_V_1_0
```
----------------------------------------end code

NOTE: The windows 10 3D Viewer loads correctly both files.
Unfortunately I was unable to isolate the problem better. It is not dependent by exponential ASCII. Another similar problem (malformed file) also comes to me with a simple triangle, which is loaded if I have the vertices described with 4 decimals, but it generates an error with 8 decimals.
In practice I can no longer use Meshlab.
Thanx if someone can help me.

**Comment by alemuntoni** [comment]
Second file loads correctly on 2020.06 on linux. Need to investigate on windows.
Thanks for reporting @GiovanniSer!

**Comment by GiovanniSer** [comment]
Many thanks for the feedback!
Ok, I replaced with the new win version 2020.006, but with the same result "malformed file"
In the meantime I did a test with these steps.
- Loaded in Meshlab the file with 6 faces.
- Saving it via Meshlab in ASCII
- Manually delete the last two faces.
- Meshlab now loads it correctly.
But I realized that in Meshlab ASCII the exponential has a different encoding.
My file (with error loading if the file has only 4 faces) : 
vertex -2.92760075 -0.53119241 -1.99058534E-16
Meshlab generated file (at the same xyz point)
vertex  -2.927601e+00 -5.311924e-01 -1.990585e-16
........ a bit sintax(?) difference, which Meshlab recognizes as its own and uses it correctly
But I am confused, why Meshlab load correctly my encoding only by my first file?
Thanx again.

**Comment by GiovanniSer** [comment]
Well, something is now clarified, I think!
I swapped my exponential with thae exponential of meshlab, and the file is loaded correctly anyway.
But I have to make another new observation. The Meshlab generated file contains the exact vectors of the normals, while for convenience I usually set them to zero. If I attempt to convert to 0 0 0, the error appears again!
This system of mine (0 0 0 for the normals) is accepted in all programs and also in the previous versions of Meshlab. Now, however, it appears to generate the unpredictable errors that we have examined.

**Comment by GiovanniSer** [comment]
Nothing to do, even the simplest face in ASCII, generated by Meshlab 2020.06, is not loaded.
However, it happened to me a few times to load it, but only the first time it is generated.
Perhaps, given this fact, and since the problem occurs only with windows, it could be an error in the allocation of the memory of the mesh. I tried to go back to version 1.3.3 32 bit April 2014 and everything works perfectly. Unfortunately, I can't help, I wouldn't know how to get into the code and I wouldn't know what tests to do, but I'm clearly available for test suggestions.

```
solid STL generated by MeshLab
  facet normal  0.000000e+00  0.000000e+00 -1.000000e+00
    outer loop
      vertex  -2.927600e+00 -5.312000e-01  0.000000e+00
      vertex  -2.927600e+00  5.312000e-01  0.000000e+00
      vertex   0.000000e+00  5.312000e-01  0.000000e+00
    endloop
  endfacet
endsolid vcg
```

**Comment by GiovanniSer** [comment]
Solved in this thread
https://github.com/cnr-isti-vclab/meshlab/issues/734
