### ISSUE TITLE
[Win] Bug importing binary STL

### ISSUE THREAD

**Issue by Mr-Starbuck** [cnr-isti-vclab/meshlab#734]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
Binary STL (see attached ZIP) could not be loaded, MeshLab says `Error details: Malformed file`. Open the STL with e.g. `File -> Import Mesh`.

[BinarySTL_cantLoad.zip](https://github.com/cnr-isti-vclab/meshlab/files/4820203/BinarySTL_cantLoad.zip)

* MeshLab 2020.06 64 Bit (2020-06-01) ("most recent" it says)
* Windows 10 Version 1909 Build 18363.900

It is working under MacOS Catalina (same MeshLab version).

**Comment by GiovanniSer** [comment]
Yes, I checked your file. 
Meshlab on win cannot, but Windows 10 Viewer yes. This is the screenshot.
[Clipboard01.zip](https://github.com/cnr-isti-vclab/meshlab/files/4822007/Clipboard01.zip)

I am also attempting to isolate this bug.
I generated a simple file, using Meshlab, it works fine in binary format.
[633a_.zip](https://github.com/cnr-isti-vclab/meshlab/files/4822017/633a_.zip)
But if I save this file in ASCII format, using Meshlab on Win 10, the new file does not work. (Malformed file)
```
solid STL generated by MeshLab
  facet normal  0.000000e+00  0.000000e+00 -1.000000e+00
    outer loop
      vertex  -2.927600e+00 -5.312000e-01  0.000000e+00
      vertex  -2.927600e+00  5.312000e-01  0.000000e+00
      vertex   0.000000e+00  5.312000e-01  0.000000e+00
    endloop
  endfacet
  facet normal  0.000000e+00 -0.000000e+00 -1.000000e+00
    outer loop
      vertex   0.000000e+00  5.312000e-01  0.000000e+00
      vertex   0.000000e+00 -5.312000e-01  0.000000e+00
      vertex  -2.927600e+00 -5.312000e-01  0.000000e+00
    endloop
  endfacet
endsolid vcg
```

**Comment by Mr-Starbuck** [comment]
I took your binary stl, converted it myself to ASCII and got the same error. Then I multiplied the triangle information. With 5 triangles it worked the first time.

[AsciiStl_5Triangles.zip](https://github.com/cnr-isti-vclab/meshlab/files/4824094/AsciiStl_5Triangles.zip)

**Comment by GiovanniSer** [comment]
Yes, more polygons there are, more the frequency of the error decreases. It seems to me that there is a memory allocation problem. If the buffer has few elements that use it, the rest of the space is not cleaned. However, if it is rewritten with many elements, the error no longer occurs.

**Comment by Mr-Starbuck** [comment]
okay, I think I got it. I looked into the code. MeshLab is using VCGLIB. I could not find, where the version information  for VCGLIB is defined, but as MeshLab uses a certain enum `E_MALFORMED` which I did find in the `devel` branch (and not in versions tagged `1.0.0`. or `1.0.0`).

The "malformed" error occurs only in the case that `LoadMask()` returns false. The shortened call hierarchy is the following:

 `LoadMask() == false <= !IsSTLColored() <= if(!IsSTLBinary(filename,binaryFlag) <= if (tmpbuf[i] > 127) && if(abs(file_size-expected_file_size) > file_size/20 )`

The errorneous function is `IsSTLBinary()` (`wrap\io_trimesh\import_stl.h`) which changed since VCGLIB 1.0.1. They try to determine if an STL file is binary or ASCII. To determine this they parse the "triangle count" information of the file (assuming that it is a correct binary STL) and compute the file size the file would have if it were a correct binary. If the computed size equals the real size they say it is a binary STL.

If the size information differs they say "we don't trust the size information, sometimes it is 'a bit' wrong". This is new in the `devel` version of VCGLIB. 

In the following they read up to 1000 byte after the binary header. If there is a character with value greater than 127 they say it is a binary but deal with a heuristic: if the size delta is more than 20% of the file size they state the function did not work out and the "if" cascade comes back to the known error "malformed".

An error here is that the code works with the size value of the binary STL although it is unclear up to this point _if_ this is a binary STL.

Question is also why do we detect a binary character in the ASCII STL? It is because `fread` does not read the amount of bytes it should (up to file or or 1000 byte as max). `fread` returns zero which means function was not successful, but this is not checked here.

Why don't we read all bytes? Because the ASCII file has Windows line ending which is converted to Unix by `fread`, so we are reading unititialized values and most likely there a binary values in it.

Before we come to the point, let's look why my binary did not get read either. This is because the size value in the binary STL could not be read. Why is that? The file is okay and so is the size value. Because the `fseek` before is not working correctly. And why is that? Now we're coming to the point. Because the file is opened in text mode rather than binary mode.

If the file would be opened in binary mode the fseek would work and also the fread regarding the line ending (because it doesn't matter in binary mode).  But there is another error: the remaining size to read for the additional test is computed wrongly. The code read another 4 byte (triangle size) before so the buffer has uninitialized data in the last 4 bytes if the file is "small".

**Comment by GiovanniSer** [comment]
Many THANKS! Great and really accurate!
So my trouble seems solved in easy way :)
This ASCII is working (at this moment, with a rustic trick)

```
solid 2STL_V_1_0////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////BYE
 facet normal 0 0 0
  outer loop
   vertex -2.92800000 -0.53100000 0.00000000
   vertex -2.92800000 0.53100000 0.00000000
   vertex 0.00000000 0.53100000 0.00000000
  endloop
 endfacet
 facet normal 0 0 0
  outer loop
   vertex 0.00000000 0.53100000 0.00000000
   vertex 0.00000000 -0.53100000 0.00000000
   vertex -2.92800000 -0.53100000 0.00000000
  endloop
 endfacet
endsolid 2STL_V_1_0////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////BYE
```

NOTE:
In my little programs for personal use, I select succesfully the STLs in this way
```
STLface.header=STLf.ReadBinStr(80)
  IF INSTR(STLface.header,"solid ")<>0 THEN ....... (It is ASCII)
```

**Comment by Mr-Starbuck** [comment]
Thank you!

Good idea to fill the `solid` line with dummy text to get a filesize somewhere beyond 1080 byte.

In my parser I decided to first check if it is a binary STL (I did it with reading the triangle count and converted it to the filesize and compared, like VCGLIB does). If it is _not_ binary STL I check if it is ASCII STL. Besides checking that the first line starts with "solid" I counted the lines and said an ASCII STL needs to have 7 * n + 2 lines. But seeing through the VCGLIB code I learned, that an ASCII STL can have more than one solid.

**Comment by GiovanniSer** [comment]
Another way to confirm ASCII after the "solid" check.
A pointer at the end of the file minus one string length (i.e. at least 64 bytes). Get the string. If the string contains "endsolid" ....

**Comment by LC-RSWR** [comment]
hi, you are foreign programmers? you are very good at the meshlab.

**Comment by Mr-Starbuck** [comment]
Thank you.
I'm new to github and to the meshlab code. Yes, I'm a developer. Currently I'm programming to cut a mesh and triangulate the hole. I use meshlab to load the resulting STLs.

**Comment by LC-RSWR** [comment]
yeah, good study day day up

**Comment by alemuntoni** [comment]
I changed the `fopen` fall in `IsSTLBinary` to:
```
FILE *fp = fopen(filename, "rb");
```

so, opening it with the binary flag by default. I tested on all the STL files you shared and other ones and it seems to work well.
`fseek` apparently needs a binary file to work fine :)
Thank you very much @Mr-Starbuck for your detailed description! And sorry for the late fix :)
