### ISSUE TITLE
[linux - wayland] crash when starting

### ISSUE THREAD

**Issue by Stunkymonkey** [cnr-isti-vclab/meshlab#738]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Arch Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

I am on wayland with sway. I installed it via AUR and the version i am using "2020.06-1"

When starting the application the cmd is showing:
```
Current Plugins Dir is: /usr/lib/meshlab/plugins
Shader directory found '/usr/share/meshlab/shaders', and it contains 19 gdp files
```
and an error window is showing up:
![Screenshot-2020-06-24_114131](https://user-images.githubusercontent.com/1315818/85532486-07835180-b610-11ea-9e9e-5f844983e2d4.png)

after clicking "OK" the return code is `255`

**Comment by Stunkymonkey** [comment]
when starting it via `QT_QPA_PLATFORM=xcb meshlab` everything works (using x11).

but `QT_QPA_PLATFORM=wayland meshlab` crashes.

**Comment by alemuntoni** [comment]
Weird, I am running ubuntu with wayland and everything seems to work correctly.
Could you please try the appimage we are releasing? I have no idea on how the AUR version has been built.

**Comment by Stunkymonkey** [comment]
using the AppImage:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)
```
do you want to have the dump?

**Comment by alemuntoni** [comment]
No, it's not necessary. 
I may have found a possible solution [here](https://github.com/probonopd/linuxdeployqt/issues/406) for generating the appimage. I'll try it in the next days, but I won't be able to test it since I cannot replicate the issue. 
About the AUR package, if the mantainers are building meshlab using cmake, the problem could be in the cmake configuration, but I am not really an expert of cmake...

**Comment by alemuntoni** [comment]
Could you please try [this](https://github.com/cnr-isti-vclab/meshlab/actions/runs/146287179) appimage?

**Comment by Stunkymonkey** [comment]
no window is shown
```
Failed to load client buffer integration: wayland-egl

qt.qpa.wayland: No shell integration named "xdg-shell" found
qt.qpa.wayland: No shell integration named "xdg-shell-v6" found
qt.qpa.wayland: No shell integration named "wl-shell" found
qt.qpa.wayland: No shell integration named "ivi-shell" found
qt.qpa.wayland: Loading shell integration failed.
qt.qpa.wayland: Attempted to load the following shells ("xdg-shell", "xdg-shell-v6", "wl-shell", "ivi-shell")
Current Plugins Dir is: /tmp/.mount_MeshLavxEGzg/usr/lib/meshlab/plugins
"Cannot load library /tmp/.mount_MeshLavxEGzg/usr/lib/meshlab/plugins/libfilter_sketchfab.so: (/tmp/.mount_MeshLavxEGzg/usr/bin/../lib/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/lib/libQt5Qml.so.5))"
Shader directory found '/tmp/.mount_MeshLavxEGzg/usr/share/meshlab/shaders', and it contains 19 gdp files
```

**Comment by alemuntoni** [comment]
Sorry, but I'm out of options :( It seems that the linuxdeployqt team chosen to [not support wayland](https://github.com/AppImage/AppImageUpdate/issues/123). Seems that the only way is to run Meshlab with `QT_QPA_PLATFORM=xcb` in some linux distributions (don't know why it works on ubuntu 20.04, for example)

**Comment by Stunkymonkey** [comment]
another option is, that maybe something is wrong with my system.
so its up to you to close the issue.

starting via cmd with x11 parameters is a workaround for me.

**Comment by Stunkymonkey** [comment]
thanks for your work :+1:

**Comment by alemuntoni** [comment]
I'll keep monitoring the linuxdeployqt hoping that wayland will be supported soon!
