### ISSUE TITLE
 meshlab2020.6 running slow

### ISSUE THREAD

**Issue by bowknot** [cnr-isti-vclab/meshlab#739]
#### Check all platforms you experienced the issue (change to `[x]`)
- [X ] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [X ] other (specify...)

Meshlab 2020.6 can hardly run after it is opened, and it will take a long time for the click menu to respond, while version 1.3.4 has no such problem.

my PC:intel G1610+8G ram，No separate graphics card

**Comment by GiovanniSer** [comment]
I had the same trouble. I solved the problem by inserting the Meshlab folder in the list of elements that the windows antivirus must ignore.

**Comment by bowknot** [comment]
> 
> 
> I had the same trouble. I solved the problem by inserting the Meshlab folder in the list of elements that the windows antivirus must ignore.

Thank you. I turned off "real time protection. It's normal.

**Comment by alemuntoni** [comment]
Good to know, thank you @GiovanniSer. 
We are working on making MeshLab a trusted application on Windows, but there are some technical delays. Hoping to have it for version 2020.08!
