### ISSUE TITLE
Crash doing compute planar section

### ISSUE THREAD

**Issue by darrepac** [cnr-isti-vclab/meshlab#740]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

[Cameron_Valovi_Chair.zip](https://github.com/cnr-isti-vclab/meshlab/files/4836724/Cameron_Valovi_Chair.zip)
updated Windows 10 
Meshlab, latest version (downloaded today)

I open the attached stl.
I do:
Filters > Quality Measure and Computations > Compute Planar Section
I choose Z axis and click apply => CRASH
(with X and Y it works ok)

hope it helps

**Comment by alemuntoni** [comment]
Tried both on windows and linux, MeshLab does not crash...

**Comment by darrepac** [comment]
great! :/
What can I do more?... I will test on an other windows machine

**Comment by darrepac** [comment]
no crash with another machine... got other issues but no crash, so I guess it is due to system environment (even if both machines are running Windows10 latest...may-be HW related)
