### ISSUE TITLE
Aging and Chipping Simulation Filter defunct after changing values - 'Missing Postcondition' error

### ISSUE THREAD

**Issue by designsoul** [cnr-isti-vclab/meshlab#742]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ X] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

After changing most of the settings for the Mesh Aging and Chipping Simulation, the models ceases to update.
I believe either it has to do with the small detail level or higher frequency settings, because after changing some of the other settings the model did work. Besides not updating, Meshlab does not start any longer and on bootup gives the message:

"Missing postcondition for filter_aging.dll"

Then it closes.

After reinstalling the bug is not fixed.. do I need to alter a registry value?

**Comment by designsoul** [comment]
I would appreciate if anyone can provide an answer to this bug. I enjoy Meshlab too much . it's indispensable.

**Comment by alemuntoni** [comment]
Filter aging is not supported anymore. Which MeshLab version are you using?

**Comment by designsoul** [comment]
Hi,

I installed the latest one.

I need the aging filter for some projects. I did get it operable on another
laptop but Meshlab doesn't work at all anymore on my main system.
See the attached for the error.

Please advise. Thank you.

Met vriendelijke groet / Best regards,


The information contained in this email and any attachments may be legally
privileged and confidential. This email is subject to copyright and
intended only for the individual named. If you are no named addressee you
are hereby notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited. If you have received this email erroneously, notify the sender
and permanently delete the email and any attachments from your system
immediately. Request for information via email implies authorization to
respond via email as well. IDZone or its representatives cannot be held
responsible for lack of secure data transmission if it occurs. Consider the
environment before you print.

**Comment by alemuntoni** [comment]
It is not possible that you're installed the "latest one", because in the latest one (2020.07) filter aging is not present, because it is not supported.

**Comment by dlabi** [comment]
Hi, same problem here. Uninstalled last version then installed 2020.7. Got this error. My OS Win7 64bit. I didn't try restart my computer yet.
