### ISSUE TITLE
Export option freezes for minutes.

### ISSUE THREAD

**Issue by Sarah-C** [cnr-isti-vclab/meshlab#744]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x ] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
Windows 10..... new 2020-6 version.

Selecting "Export mesh" and "Export mesh as..." for any model results in the dialog box appearing - an empty white square, and hanging for over a minute.

Normal operation resumes until the opened folder is navigated away from, and it hangs again.

This makes it near impossible to export a mesh.

This is worse for the Desktop location, other folders appear to be indexed and displayed much faster.

I have Flashforge print program - which does real-time thumbnails of STL files. Perhaps this is the issue? Every other program's save dialogs do not exhibit this behaviour*1 - only MeshLab, hence me raising the issue. (thought - is MeshLab playing badly with Explorer extensions?)

*1 Photoshop CC, Office 365, Thea Render, Chrome, Edge, Maya, Notepad, Notepad++.... lots of general software all display the Desktop without any form of delay.

**Comment by GiovanniSer** [comment]
In my opinion, because I had the problem, it is the fault of the windows antivirus. Try to make him ignore the MeshLab folder. Even my graphics compiler had the same problem. In another post the developers said they are working on fixing the problem. Try inserting program and work folders into paths that the antivirus must ignore.

**Comment by Sarah-C** [comment]
I see, thanks!

It's sped it up a fair bit...... brilliant!
