### ISSUE TITLE
Missing return when not compiling in DEBUG mode

### ISSUE THREAD

**Issue by StefanBruens** [cnr-isti-vclab/meshlab#745]
https://github.com/cnr-isti-vclab/meshlab/blob/7b3202f9647f6d1c928bbaf186bac82dd1acc74c/src/meshlabplugins/edit_pickpoints/edit_pickpoints_factory.cpp#L48-L50

Without -DDEBUG, assert(0) is removed by the preprocessor, and GCC with '-Werror=return-type' fails to build:

```
./meshlab-Meshlab-2020.07/src/meshlabplugins/edit_pickpoints/edit_pickpoints_factory.cpp: In member function 'virtual MeshEditInterface* EditPickPointsFactory::getMeshEditInterface(QAction*)':
./meshlab-Meshlab-2020.07/src/meshlabplugins/edit_pickpoints/edit_pickpoints_factory.cpp:50:1: error: control reaches end of non-void function [-Werror=return-type]

```
instead, `abort()` or `assert(0); return nullptr;` should be used here.

**Comment by alemuntoni** [comment]
Thanks for pointing this, @StefanBruens!
Fixed in [this commit](https://github.com/cnr-isti-vclab/meshlab/commit/c0e55e569a2557c27bb9a4ea82500e9a16ff315b).
