### ISSUE TITLE
Crash when I import jpg raster 

### ISSUE THREAD

**Issue by Dpeigne** [cnr-isti-vclab/meshlab#746]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
When I import jpg raster, the new meshlab version (2020.07) crashed

**Comment by alemuntoni** [comment]
Could you please provide the file that causes the crash? Does it happens for every file?
