### ISSUE TITLE
Crash when closing align box

### ISSUE THREAD

**Issue by warmist** [cnr-isti-vclab/meshlab#750]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

Crash when closing align box (i.e. open align, close box, crash). Meshlab version 2020.07. Have the dump file but it's 600mb. Can't share the models -proprietary info.

**Comment by warmist** [comment]
Just reproduced with two boxes: open new project, filters->create new mesh layer->box (two times). Press align and then close with small "X" in corner. Instant crash.

**Comment by BFGRC** [comment]
Closing align window crashes meshlab 2020.07. Tried three different computers (all WIN7) same result. Load two meshs, go to align, then close align window, crash.

Went back to 2016.12 and the problem goes away.

**Comment by alemuntoni** [comment]
Hi, could you try one of the last builds (like [this](https://github.com/cnr-isti-vclab/meshlab/actions/runs/371861802))?
I tried one of these and apparently the crash does not happen anymore.

**Comment by BFGRC** [comment]
2020.09 seems to have fixed this issue.
Thanks
