### ISSUE TITLE
 Source code build in windows10

### ISSUE THREAD

**Issue by KOTOKORURU** [cnr-isti-vclab/meshlab#753]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x ] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ x] other (specify...)
  Build source code in win10.

Hi, all
i try to build meshlab in my windows envirnoment, but i encounter those issues:

with the  windows_build.ps1 script, it report: 
g++: error: winmm.lib: No such file or directory
g++: error: user32.lib: No such file or directory

with the command   g++ -Wl,-s -shared -Wl,-subsystem,windows -mthreads -Wl,--out-implib,D:\meshlab-master\meshlab-master\src\..\distrib\lib\win32-gcc\libIFXCore.a -Wl,..\src\RTL\Platform\Win32\IFXCore\IFXCore.def -o D:\meshlab-master\meshlab-master\distrib\lib\win32-gcc\IFXCore.dll object_script.IFXCore.Release  winmm.lib user32.lib -LD:\Qt\Qt5.9.9\5.9.9\mingw53_32\lib D:\Qt\Qt5.9.9\5.9.9\mingw53_32\lib\libQt5Gui.a D:\Qt\Qt5.9.9\5.9.9\mingw53_32\lib\libQt5Core.a release\IFXCore_res.o

and 

 g++ -Wl,-s -Wl,-subsystem,windows /MANIFESTUAC:level='requireAdministrator' -mthreads -o D:\meshlab-master\meshlab-master\distrib\UseCPUOpenGL.exe main.o  qrc_res.o  -lmingw32 -LD:\Qt\Qt5.9.9\5.9.9\mingw53_32\lib D:\Qt\Qt5.9.9\5.9.9\mingw53_32\lib\libqtmain.a -LC:\openssl\lib -LC:\Utils\my_sql\my_sql\lib -LC:\Utils\postgresql\pgsql\lib -lshell32 D:\Qt\Qt5.9.9\5.9.9\mingw53_32\lib\libQt5Widgets.a D:\Qt\Qt5.9.9\5.9.9\mingw53_32\lib\libQt5Gui.a D:\Qt\Qt5.9.9\5.9.9\mingw53_32\lib\libQt5Core.a
g++: error: /MANIFESTUAC:level='requireAdministrator': No such file or directory

so, what environment variables of vs or qt which i miss to set?

Thanks very much

**Comment by alemuntoni** [comment]
To make the windows_build.ps1 script working, we are using tools that automatically set all the environment variables needed, as you can see in [this workflow](https://github.com/cnr-isti-vclab/meshlab/blob/master/.github/workflows/BuildWindows.yml).

On windows, I suggest to use QtCreator: install visual studio >=2015, and Qt >= 5.9.
Then, open src/meshlab.pro and build (make sure to set a kit that uses msvc).

**Comment by KOTOKORURU** [comment]
hi,Alessandro
as your advice, i use qt5.9.9  and kit configuration with msvc++ compiler 16.6, but it seems that some dll, such as ifxcore.dll, so if i miss some nessary library again? 

thanks.

**Comment by alemuntoni** [comment]
Are you using QtCreator or just Qt 5.9?

Could you please install QtCreator, open src/meshlab.pro and build?
Before build, check that the kit is properly set to msvc and deactivate the QtQuick compiler.

**Comment by HungNgoCT** [comment]
> To make the windows_build.ps1 script working, we are using tools that automatically set all the environment variables needed, as you can see in [this workflow](https://github.com/cnr-isti-vclab/meshlab/blob/master/.github/workflows/BuildWindows.yml).
> 
> On windows, I suggest to use QtCreator: install visual studio >=2015, and Qt >= 5.9. Then, open src/meshlab.pro and build (make sure to set a kit that uses msvc).

Hi @alemuntoni ,

Why did I not see the file meshlab.pro anywhere in the source code?

**Comment by alemuntoni** [comment]
Because this issue was closed 3 years ago. We don't use qmake as a build system anymore.
