### ISSUE TITLE
[Linux] Meshlabserver freeze when applying a filter script

### ISSUE THREAD

**Issue by tobychui** [cnr-isti-vclab/meshlab#755]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
Meshlabserver freezes (with 100% CPU usage shown in the top command) when I try to apply a script using the command
```xvfb-run -a -s "-screen 0 800x600x24" meshlabserver -i  input.stl -o output.stl -m sa -s script.mlx ```,
The terminal shows the following before it freezes
```
Input mesh  input.stl
output mesh  output.stl
```

I also tested the help command (```xvfb-run -a -s "-screen 0 800x600x24" meshlabserver -h``` ) and all the help info are correctly printed out.

The meshlabserver is installed via ```apt-get install meshlab``` with apt update today. (``` meshlab is already the newest version (1.3.2+dfsg1-4+b1). ```)

The script content is as follow:
```
<!DOCTYPE FilterScript>
<FilterScript>
	<filter name="Merge Close Vertices"/>
	<filter name="Remove Duplicate Vertices"/>
	<filter name="Remove Unreferenced Vertices"/>
</FilterScript>
```
This script works perfectly on Windows but the script freeze when I am trying to run it on Debian 10. Here is my OS info from ```cat /etc/os-release``` running without desktop but with xorg installed.

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
...
```
The OS is hosted on a system with dual Xeon processor and a dedicated GPU from Nvidia, so I think it is not the problem of hardware being too slow. 

I also attached the mesh that I am testing with this issue. Any help / comments will be nice! Thank you.

[input.zip](https://github.com/cnr-isti-vclab/meshlab/files/4953320/input.zip)

**Comment by alemuntoni** [comment]
1.3.2 is an old version. 
You should try the last version of meshlabserver, the appimage is available in the release tab of this repo.
