### ISSUE TITLE
Exporting objs from Meshlab are removing UVs

### ISSUE THREAD

**Issue by cre8iveprime8** [cnr-isti-vclab/meshlab#756]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

I've imported an obj with uvs into Meshlab. Exported the obj, and imported into MAX; the Uvs have been removed. As a test, I've imported the same obj back into Meshlab and the Uvs are gone. I've tested obj exports now with your previous version of Meshlab and the most recent version. 

To note:
I've enabled wedge "TexCoord" in the export options.
I've also tested in your texture filters: "convert perwedge uv into pervertex uv" and enabled Vert TexCoord in the export options. So, Wedge and Vert TexCoords have been enabled and tested on obj exports and Uvs are being removed.

Is it possible to export objs in Meshlab without losing your Uvs? 

I've attached the obj that I tested with. Please let me know if there's anything else you need on my end.

Thank you in advance.

[mesh_lab.zip](https://github.com/cnr-isti-vclab/meshlab/files/4972669/mesh_lab.zip)

**Comment by alemuntoni** [comment]
Hi, in the attached file is missing the material file. Could you please attach it?

**Comment by cre8iveprime8** [comment]
[mshlb_updtd.zip](https://github.com/cnr-isti-vclab/meshlab/files/5066539/mshlb_updtd.zip)
Cool, I've attached textures too. (If you need them)

**Comment by alemuntoni** [comment]
Sorry for the late response. I am not able to load the objs you uploaded -- apparently, MAX exports them putting absolute paths on the mtl, making it impossible to being imported from anywhere else.
I am not able to reproduce the issue.

**Comment by cre8iveprime8** [comment]
Thank you for your time Alessandro

**Comment by maxmadzz** [comment]
I encountered the same problem on macOS. UV actually exists but is reduced to a point.
