### ISSUE TITLE
Crash (sometimes) when in "Get Info" mode and reload mesh

### ISSUE THREAD

**Issue by warmist** [cnr-isti-vclab/meshlab#758]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

It looks like if the vertex i'm looking info about does not exist in the new mesh reload crashes meshlab.

**Comment by alemuntoni** [comment]
Could you please provide a minimal reproducible example?
