### ISSUE TITLE
black viewport with KDE 5.9 Arch Linux

### ISSUE THREAD

**Issue by FuchtelJockel** [cnr-isti-vclab/meshlab#76]
When I use Meshlab in KDE the viewport is entirely black except for the menu bar. When I try it with a GTK based desktop (Budgie) everything works fine.
I also tried different desktop themes without success.

[screenshot](http://imgur.com/a/tCR9y)
http://imgur.com/a/tCR9y

**Comment by harrysummer** [comment]
I'm using the latest KDE with Arch Linux and experiencing exactly the same issue. However, I found that by opening a second view with Ctrl-N, the viewport can be correctly rendered. And after closing the second view by Ctrl-W, the first view can be displayed correctly.

**Comment by cignoni** [comment]
What MeshLab version? Are you using the latest snap?

**Comment by harrysummer** [comment]
@cignoni I built MeshLab from Arch Linux AUR `meshlab-git` package, which directly pulls the latest source from the master branch of this repo.

Another finding, it seems to be the KDE theming system that causes the problem. If I use a blank user without any KDE global configurations, everything is OK (except for no theme). I'll look into this later.

**Comment by jaggzh** [comment]
I'm experiencing this with a fresh build from git, in Debian-stable.

**Comment by jaggzh** [comment]
Also, changing the theme fixes it.  Hmm.  Breeze Dark fails.  Breeze works.

**Comment by alemuntoni** [comment]
This issue should be solved in the latest version (2020.06). Feel free to reopen if the problem persists.
