### ISSUE TITLE
Seeking better performance at scale

### ISSUE THREAD

**Issue by lowndesc** [cnr-isti-vclab/meshlab#762]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows

#### What type of issue is?
- [x] bug or unexpected behavior

MeshLab version 2020.06

When applying 'Flatten visible layers' for many (200-400) point cloud layers, containing up to (10^8) points/vertices with vertex color seems to be reaching the limits of MeshLab. However, it works, but can take around 90-120 minutes to complete on a Windows10/16GB RAM/i7+GPU local machine. I then tried running the exact same filter and data set on meshlab.exe on an Azure virtual machine (size NC24s_v3 = Windows10/ 448 GB RAM/24-core Intel Xeon E5-2690 v4 vcpus/NVIDIA Tesla V100 GPU) to see what difference massive scale-up would make. The answer = none. In fact, it took longer to execute the filter by about 7%.

Doing some analysis, it seems the bottleneck is contention between two mains threads accessing a third shared thread within the meshlab.exe process. 

Is there any suggestion as to how to improve this performance at scale?
Would executing the filter by scripting against meshlabserver.exe be any better?

**Comment by alemuntoni** [comment]
I'll look into this whenever it's possbile. When applying the filter, are the parameters set to the default values?

**Comment by alemuntoni** [comment]
Hi, I'm not able to investigate this issue, I don't have so many big point clouds to test :(
But the bottleneck could be something in meshlab. 
It's still an alpha, but you can try [pymeshlab](https://pymeshlab.readthedocs.io/en/latest/index.html) ([here](https://github.com/cnr-isti-vclab/PyMeshLab) is the repo) and see if the performances improve.

you should just install it, then on python:
```
import pymeshlab
ms = pymeshlab.MeshSet()
ms.load_mesh(...)
#load all the other point clouds
ms.apply_filter('flatten_visible_layers')
```
