### ISSUE TITLE
[MacOS] Meshlab does not load plugins

### ISSUE THREAD

**Issue by gezabohus** [cnr-isti-vclab/meshlab#764]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [x] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
Trying to open or import ply file results in unsupported file type error message. v2020.07, MacOS 10.13.06.

I don't know if it makes a difference, but no plugins are seen when Plugin info is asked for.

**Comment by ferdymercury** [comment]
Some PLY files might have issues, see: https://github.com/cnr-isti-vclab/meshlab/issues/463
Can you provide an example file?

**Comment by gezabohus** [comment]
Thanks @ferdymercury. My file is 20+ megs, but I can upload it somewhere. One thing I also noticed since yesterday is that when I do an Open from meshlab, ply files are greyed out. 

By the way, the linux version has no problem with this file.

Here is an example: http://gbohus.com/Eva1.ply

**Comment by alemuntoni** [comment]
I can confirm that the file has no problem on linux. I still need to check it on MacOS, I can't do it these days :(

**Comment by gezabohus** [comment]
Thanks for the confirm.

**Comment by alemuntoni** [comment]
Can't replicate the issue also on mac. Could you try to download the last 2020.09 version and let me know?

**Comment by gezabohus** [comment]
Hi Alessandro,

The dmg on the site is still 2020.07, so I tried to follow the example 
at the bottom of 
https://github.com/cnr-isti-vclab/meshlab/tree/master/install/macos, but 
I get errors:

============================

$ sh meshlab/install/macos/macos_setup_env.sh
Warning: libomp 10.0.1 is already installed and up-to-date
To reinstall 10.0.1, run `brew reinstall libomp`
Error: qt 5.15.0 is already installed
To upgrade to 5.15.1, run `brew upgrade qt`
npm WARN checkPermissions Missing write access to 
/usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access 
'/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access 
'/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this 
file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please 
double-check the
npm ERR! permissions of the file and its containing directories, or try 
running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/gbohus/.npm/_logs/2020-09-24T11_39_05_809Z-debug.log

============================

If I do it using sudo, different erros pop up.

============================

$ sudo sh meshlab/install/macos/macos_setup_env.sh

Password:
Error: Running Homebrew as root is extremely dangerous and no longer 
supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
/usr/local/bin/appdmg -> /usr/local/lib/node_modules/appdmg/bin/appdmg.js

 > macos-alias@0.2.11 install 
/usr/local/lib/node_modules/appdmg/node_modules/macos-alias
 > node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to 
access the dev dir "/Users/gbohus/Library/Caches/node-gyp/12.16.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir 
"/usr/local/lib/node_modules/appdmg/node_modules/macos-alias/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir 
'/usr/local/lib/node_modules/appdmg/node_modules/macos-alias/.node-gyp'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" 
"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" 
"rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/appdmg/node_modules/macos-alias
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! macos-alias@0.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the macos-alias@0.2.11 install script.
npm ERR! This is probably not a problem with npm. There is likely 
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/gbohus/.npm/_logs/2020-09-24T11_39_47_291Z-debug.log

============================

Thanks, cheers,

Geza

**Comment by alemuntoni** [comment]
In the [Release](https://github.com/cnr-isti-vclab/meshlab/releases) tab of this repo there is the 2020.09 version available to download

**Comment by gezabohus** [comment]
I'm afraid it's the same, both for Open and Import.

Is there anything other than copying the application into the 
Application folder that one must do?

**Comment by alemuntoni** [comment]
Nope, that should be enough..
could you please open a terminal, move inside the meshlab.app directory and run 
```
./Contents/MacOS/meshlab
```

and paste here the output?

**Comment by gezabohus** [comment]
Ah, I think we're getting closer 8)

$ ./Contents/MacOS/meshlab
The base dir is /
Meshlab Initialization: Serious error. Unable to find the plugins directory.
The base dir is /
Meshlab Initialization: Serious error. Unable to find the plugins directory.
The base dir is /
Current Plugins Dir is: /Applications/meshlab.app

**Comment by alemuntoni** [comment]
That's weird... There is something in your system that is confusing the position of the meshlab binary. The output should be something like:
```
The base dir is /Applications/meshlab.app/Contents
```
But I really don't know what could be.

**Comment by gezabohus** [comment]
I can't reboot right now, but I'll try this again when I rebooted.

**Comment by gezabohus** [comment]
Hi Alessandro,

I have reinstalled my system (for independent reasons) and it seems to 
be working now. Something must have been corrupted.

Thanks for your help.

G

**Comment by denics** [comment]
Can we please reopen this? It seems to be a recurrent problem. I have just installed and reinstalled the latest meshlab on a fresh OSX Sierra and I have exactly the same issue. 

Launching from command line:
```txt
$: /Applications/meshlab.app/Contents/MacOS $ ./meshlab --
The base dir is /
Meshlab Initialization: Serious error. Unable to find the plugins directory.
The base dir is /
Meshlab Initialization: Serious error. Unable to find the plugins directory.
The base dir is /
Current Plugins Dir is: /Applications/meshlab.app/Contents/MacOS
```

**Comment by denics** [comment]
And, the obvious, but impractical solution, is to run meshlab from the plugin directory!

```txt
$:/Applications/meshlab.app/Contents/PlugIns $ ../MacOS/meshlab
The base dir is /
Meshlab Initialization: Serious error. Unable to find the plugins directory.
The base dir is /
Meshlab Initialization: Serious error. Unable to find the plugins directory.
The base dir is /
Current Plugins Dir is: /Applications/meshlab.app/Contents/PlugIns
```

**Comment by alemuntoni** [comment]
Hi @denics, unfortunately I don't have a mac with OSX sierra, therefore I cannot replicate the issue and I cannot try to solve it, since it is impossible to understand what is causing this issue.
Could you please try [this](https://github.com/cnr-isti-vclab/meshlab/actions/runs/345792460) release? It has been built with a different build system and maybe the issue disappeared.

**Comment by denics** [comment]
Ciao @alemuntoni , same problem with same solution. It was not the case last year (sorry I do not remember what build I was using in my previous computer).

And sorry, I am not anymore on Sierra, I am on Catalina 10.15.7 recently installed.

**Comment by alemuntoni** [comment]
Hi @denics, could you please let me know if the problem persists with the new 2020.12 version?

**Comment by denics** [comment]
Ciao @alemuntoni , just downloaded, cleaned folders (hard delete from command line) but still: 

![image](https://user-images.githubusercontent.com/2407163/101173197-7abed400-3642-11eb-8060-8d2459f6a6a2.png)

**Comment by alemuntoni** [comment]
that's weird. Just for curiosity, could it be possible that you have macos installed with a filesystem with case sensitivity enabled?

**Comment by denics** [comment]
Here you go:

```
   File System Personality:   APFS
   Type (Bundle):             apfs
   Name (User Visible):       APFS
   Owners:                    Enabled
```

APFS is Case Sensitive by default, I am not using encryption.

**Comment by denics** [comment]
It is case sensitive, I can create TMP and tmp (I am a linux user)

**Comment by alemuntoni** [comment]
Ok, that could be the root cause of the problem, and it makes sense to me. 
I'll check!!

**Comment by yquerry** [comment]
It is a case sensitive problem.

Using Meshlab-2020.12 on MacOS create a soft link using the console:

cd /Applications/meshlab.app/Contents
ln -s PlugIns plugins

This will fix the plugins problem.

**Comment by alemuntoni** [comment]
This issue has been already solved and the fix will be available in the next version of MeshLab.

see #900 and #956.

**Comment by jbarros35** [comment]
hi, at 2021 there's not APplications folder for meshlab anymore on Mac OS m1. I would expect some issues

**Comment by alemuntoni** [comment]
@jbarros35 Could you please elaborate? I don't understand what you mean and how this is related with this (solved) issue.
