### ISSUE TITLE
[Feature Request] .tga texture loading failure with 3ds format

### ISSUE THREAD

**Issue by Fadgiras** [cnr-isti-vclab/meshlab#766]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows 10 (10.0.18362)
- [ ] Mac OS
- [ ] Linux
- [x] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [x] feature request
- [ ] other (specify...)

#### Describe your issue
With the current release (2020.07) when I try to load a .3ds file it displays "Failure of loading texture texture01.tga".
![image](https://user-images.githubusercontent.com/47023417/89592011-e4bd9d00-d84b-11ea-890c-4d367d1aa7e8.png)
(Knowing that the texture is at this location)
Maybe it's because of the .tga textures
Here's one of the models I tried to load.

[Gnd.zip](https://github.com/cnr-isti-vclab/meshlab/files/5038487/Gnd.zip)

**Comment by alemuntoni** [comment]
It depends on the .tga textures, this format is still not supported by meshlab. Labeling this issue as a feature request.
