### ISSUE TITLE
[Ubuntu 20.04] Pop-up windows fail to show

### ISSUE THREAD

**Issue by EverythingTech** [cnr-isti-vclab/meshlab#767]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

When I open any pop-up windows in "Filters", no pop-up windows appear while the Meshlab window defocuses. For example, if I want to scale a mesh, I would go to Filters-> Normals, Curvatures, and Orientation -> Transform: Scale, Normalize. A pop-up window should then appear but it doesn't.

**Comment by alemuntoni** [comment]
Do you two or more monitors? Sometimes I remember I had the problem that the window popped up in a different monitor on linux. I think that could be a Qt-related issue.

**Comment by kingjin94** [comment]
I have the same issue and can confirm the fix with regard to multi-monitor. It seems the pop up can appear outside the drawn area (e.g. above the laptop screen that sits to the left of a main external monitor. For Gnome a work around is to use ALT+Space and then select move to get hold of the window outside the viewing area
