### ISSUE TITLE
[Windows] crash on Alignment tool

### ISSUE THREAD

**Issue by anbellit** [cnr-isti-vclab/meshlab#771]
#### Check all platforms you experienced the issue (change to `[x]`)
- [X ] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x ] bug or unexpected behavior
- [X] crash
- [ ] feature request
- [ ] other (specify...)

Hello, I am using Meshab 2020.08 on Windows 10, 16 Mb RAM; Nvidia Quadro, 2Gb RAM
The files I am working on are on a network drive.

My first problem is on Align Tool:
I select the tool; then I select Glue Here mesh; then I select a second mesh, and then PointBase Glueing; now appears a new window. If I check Allow scaling, the program crashes; also if I check FalseColor the program crashes.
If I try a rotation of the model, the program crashes.

My second problem, is related to unaspected behaviour: When I click on Menu->File->Close project, the program closes the program itself, not only the project.
This happens when I open a project, and then apply a filter or I do an operation to the project.
Thanks for your attention

**Comment by anbellit** [comment]
If I use version 2020.03,  in WIN 10 , the problem is the same: alignement tool crashes 
If I use version 2020.03 in WIN7, the program works fine.
I know Win7 is no more supported by Microsoft, but Why the same program works well in Win7 and not in Win10?

**Comment by anbellit** [comment]
I found that the problem on align tool is related to win10, that uses the standard graphic card instead of the high-performance NVIDIA QUADRO graphic card. Then MeshLab shows 'unrecognized card', and then the program crashes in aligment tool. IF I run the program selecting 'High performance graphic board' then the program works well. Note that this is already the default option for Meshlab.
Remains the problem related to closure of the program instead of the current project.

**Comment by alemuntoni** [comment]
I cannot replicate the issue about the align tool, also in a machine showing the "UNRECOGNIZED CARD" message.
About the second issue regarding the crash of the program, there is an already opened issue (#780) for it.
