### ISSUE TITLE
Importing only two meshes then crashing [Windows]

### ISSUE THREAD

**Issue by travispark** [cnr-isti-vclab/meshlab#774]
#### Check all platforms you experienced the issue (change to `[x]`)
- [X ] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ X] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
I am importing meshes individually, checking them and then closing them. However, once I've closed the second mesh, it crashes every time. This has happpened with both the June and July 2020 updates. Prior to this I was using a much older version (> 2 years) and never had any issues
...

**Comment by alemuntoni** [comment]
What does it mean "once I've closed the second mesh"? Are you deleting the layer?
What windows version are you using?
