### ISSUE TITLE
[Linux] Cannot import obj file on NTFS partition

### ISSUE THREAD

**Issue by Deuce0** [cnr-isti-vclab/meshlab#775]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
I cannot import obj file on NTFS partition.
![image](https://user-images.githubusercontent.com/18064691/90110634-7f583780-dd88-11ea-8910-90aeaa8ef7d0.png)
If I copy the file to ext4 partition, I can import it.

Ubuntu 20.04
MeshLab_64bit_fp v2020.07

**Comment by alemuntoni** [comment]
Is MeshLab installed from the snap store? Or is the AppImage?

**Comment by Deuce0** [comment]
duplicate. closing
