### ISSUE TITLE
Can't import FBX on the latest meshlab

### ISSUE THREAD

**Issue by marcusx2** [cnr-isti-vclab/meshlab#779]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
I can't import any FBX file on meshlab. Using Windows 8.1. When I try to do so, the memory consumption on my machine steadily increases, to the point it BSODs and I need to hard reset. Not very fun. Size of the FBXs I tried are 86MB and 27MB.

**Comment by alemuntoni** [comment]
Could you please share a file that causes the crash?

**Comment by marcusx2** [comment]
I cannot, because it's from a client. But I successfully managed to import it in blender, and after I merged all meshes into a single one, meshlab was able to import it as well, which indicates that meshlab has trouble with multinested meshes.

**Comment by alemuntoni** [comment]
Without a sample file that causes the problem I cannot replicate the issue.
