### ISSUE TITLE
[Every Platform] Reproducible crash while closing project second time

### ISSUE THREAD

**Issue by bersbersbers** [cnr-isti-vclab/meshlab#780]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Every Platform

#### What type of issue is?
- [x] crash

#### Describe your issue
Copy path to `bug.stl` from https://github.com/cnr-isti-vclab/meshlab/issues/448#issuecomment-675879993 (attached) to clipboard (`C:\Work\Desktop\bug.stl` for me)

- Open MeshLab 2020.07
- Ctrl-I, Ctrl-V, Enter, Ctrl-W (does not crash yet)
- Ctrl-I, Ctrl-V, Enter, Ctrl-W (crashes)

[bug.stl.txt](https://github.com/cnr-isti-vclab/meshlab/files/5094439/bug.stl.txt)

**Comment by alemuntoni** [comment]
Fixed by #1349!
