### ISSUE TITLE
Is there a linux api for commands available in meshlab through commandline?

### ISSUE THREAD

**Issue by Codeguyross** [cnr-isti-vclab/meshlab#786]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [x] feature request
- [x] other (specify...)

#### Describe your issue

...

####Guidelines for a good issue

Before submitting an issue: 

- be as detailed as possible. If the issue is related to a specific mesh or file, please attach it. Make sure that the problem is reproducible; 
- specify the operative system you are using and its version/distribution; if it is possible, verify if the problem persists in other platforms;
- bspecify the MeshLab version you are using and be sure that your issue also happens on the last MeshLab version;
- check if your issue has been already reported by someone else. In this case, do not open another issue: just add your experience in the existing issue;
- If the issue is specific of a platform, please specify it on the subject in square brackets (example: `[MacOS] crash when opening obj`);
- delete these guidelines before submitting :)

**Comment by Codeguyross** [comment]
I am not sure if this is a feature request or something exist. I am looking for a command line api that i can run on linux for meshlab. I saw some reference to a windows server but nothing for linux

**Comment by alemuntoni** [comment]
There is meshlabserver, or you can try [pymeshlab](https://github.com/cnr-isti-vclab/PyMeshLab), which is a new python library that  allow to use meshlab components for batch processing

**Comment by Codeguyross** [comment]
> There is meshlabserver, or you can try [pymeshlab](https://github.com/cnr-isti-vclab/PyMeshLab), which is a new python library that allow to use meshlab components for batch processing

I thought meshlab server was only windows?

**Comment by alemuntoni** [comment]
Nope, meshlabserver is released for any platform, for linux there is the AppImage in the release tab, or you can find the binary inside the portable version

**Comment by Codeguyross** [comment]
> Nope, meshlabserver is released for any platform, for linux there is the AppImage in the release tab, or you can find the binary inside the portable version

Im looking at pymeshlab today but having trouble finding the thing I can make calls to from code for meshlabserver. The appimage that i found launches meshlab GUI and I need something that isnt running from a gui so that I can make function calls to it. I might be missing something but is there a command line option to be able to make calls to meshlab functions that would allow me to turn a point cloud .ply file into a .obj file without open a gui? It looks like pymeshlab might be able to do this but im not sure yet.

Btw thanks for the help @alemuntoni!

**Comment by alemuntoni** [comment]
> > Nope, meshlabserver is released for any platform, for linux there is the AppImage in the release tab, or you can find the binary inside the portable version
> 
> Im looking at pymeshlab today but having trouble finding the thing I can make calls to from code for meshlabserver. The appimage that i found launches meshlab GUI and I need something that isnt running from a gui so that I can make function calls to it. I might be missing something but is there a command line option to be able to make calls to meshlab functions that would allow me to turn a point cloud .ply file into a .obj file without open a gui? It looks like pymeshlab might be able to do this but im not sure yet.
> 
> Btw thanks for the help @alemuntoni!

There are two AppImages in the release tab: one of MeshLab and one of MeshLabSerber.
The one of MeshLabServer is [this one](https://github.com/cnr-isti-vclab/meshlab/releases/download/Meshlab-2020.09/MeshLabServer2020.09-linux.AppImage).

Using pymeshlab you can do that in the following way:

```
import pymeshlab
ms = pymeshlab.MeshSet()
ms.load_mesh("my_file.ply")
ms.save_mesh("my_file.obj")
```

pymeshlab is still a work in progress, but if the task is simple like this one, there should be no problem.
