### ISSUE TITLE
[MacOS] "Point Based Glueing" almost unusable on macOS

### ISSUE THREAD

**Issue by rcofix** [cnr-isti-vclab/meshlab#787]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [x] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

The "Point Based Gluing" feature (from the "Align Tool") has several serious usability issues.

1) The "Point Based Gluing" dialog on macOS (unlike in Windows, as demonstrated in the tutorials) presents with a _white_ background, and _dark_ point clouds - not necessarily a problem, but, the text colour that displays the selected points is also white, so if you zoom in to see a detail of the point cloud, the point text disappears against the background.  (see attachments)

2) It's _very_ hard to select a point when zoomed in to any degree, to successfully select a point you have to zoom out to the extent where the point cloud appears as a solid surface, but then you can't select a particular point with any acceptable degree of precision.

3) I could never get the Ctrl-Double-click action to _remove_ points once added.

I looked for a place to change the colour of the selection text, but this doesn't have a setting in Preferences that I could find.

This is with MeshLab version 2020.07, macOS 10.15.4 (19E287)

zoomed out - can see selected point text
<img width="449" alt="Screen Shot 2020-09-04 at 2 12 02 PM" src="https://user-images.githubusercontent.com/13002364/92282360-a94dd700-eeba-11ea-9bad-d8661ecd6e4d.png">

zoomed in, selected point text disappears against background of same colour
<img width="603" alt="Screen Shot 2020-09-04 at 2 12 13 PM" src="https://user-images.githubusercontent.com/13002364/92282433-ce424a00-eeba-11ea-8c60-9869a8ae8cdb.png">

View of dialog as displayed on my computer

<img width="1545" alt="Screen Shot 2020-09-04 at 2 30 14 PM" src="https://user-images.githubusercontent.com/13002364/92282642-46107480-eebb-11ea-862f-44c0d2425e9b.png">

**Comment by alemuntoni** [comment]
Fixed in the last commit, now the background of the point based gluing dialog will be always black also on macos.
You can try it by downloading the [last nightly](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version) (will be available in ~20 minutes).
