### ISSUE TITLE
[MacOS] Keyboard-shortcut conflict

### ISSUE THREAD

**Issue by Jmuccigr** [cnr-isti-vclab/meshlab#788]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [x] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
The shortcuts for File/Recent files and Window/View from conflict.

CMD-1,2,3... are listed as shortcuts under the File menu. They open (or re-open if the file is already loaded, which might be considered a bug itself) recently opened files.

At the same time, the Window/View from... shortcuts are various versions of 1, 3, and 7. Depending on something I haven't figured out, Meshlab decides to send the CMD-1 shortcut to one or the other of these two places, resulting in lots of duplicated layers as it re-opens the same file (CMD-1) over and over as I try to switch the viewing point.

I have no strong preference about how this _should_ work (except that I find the 1-3-7 keys totally unobvious), but clearly it's a problem. Perhaps the recent-files list doesn't need a shortcut?

PS On a Mac, that menu is usually "Open Recent...", and falls right below "Open", but perhaps the existence of both files and projects makes that tricky here.

MacOS 10.13.6
Meshlab 2020.07

**Comment by alemuntoni** [comment]
"Fixed" in the last commit. The shortcuts with numpad keys have been disabled on linux and macos (the modifier apparently works only on windows), therefore this conflict should disappear on the next version of meshlab.
You can try the fix by [downloading the last nightly](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version).
