### ISSUE TITLE
[MacOS] Windows/View From... menu items don't work

### ISSUE THREAD

**Issue by Jmuccigr** [cnr-isti-vclab/meshlab#789]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [x] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
Two issues, really:
1. Reported already (partially) as #788, where the keyboard shortcuts for the View From... menu simply don't make it through. So I can sit and hit ⌘-3 all day to no result. Pretty sure this happens when there is no third recent file to open and the File menu is grabbing the command.
2. Only the shortcuts with ⌘ (CMD) in them work. So ⌘-7 and ⌘-⌥-7 work fine, but 7 alone and ⌥-7 both do nothing. The menu commands work fine if I select them with the mouse.

**Comment by alemuntoni** [comment]
see #788
