### ISSUE TITLE
Rasters not shown when importing bundler project

### ISSUE THREAD

**Issue by mardy** [cnr-isti-vclab/meshlab#79]
After importing a bundler project (`bundle.out` + `list.txt`), the layers subwindow on the right side does not show the list of raster images.
It looks like it's just a graphical glitch, because if I press on the "unmaximize" button of the layers subwindow, the window refreshes and the list of raster images appears.

**Comment by mcallieri** [comment]
We tried and the layers are correctly shown as soon as the project is loaded.
Which OS are you using?

**Comment by mardy** [comment]
I'm using the snap package, which I've built in Ubuntu 17.04 (still under development) which is using Qt 5.7.1

**Comment by mcallieri** [comment]
I cannot find anything strange in the importing code.
All "open project" have the same code, as far as the layer panel goes. If you open an MLP project with images, do you have the same issue (raster not appearing immediately)?
I'll let you know if I find the problem.

**Comment by eric-schleicher** [comment]
Hi @mardy   not sure if you're still having this problem.   I've had issue with line returns preventing meshlab from properly import bundle files.   in general the process is very opaque and in my case i had a process writing bundle files and it took a while before i had a process that would work reliably.

tips from my experience (make sure)
- only one comment line.
- the first line of every camera entry must have all three values  focal, and both distortion values  (even fi they are 0 0) 
-the last camera entry must have a single line return and no additional characters on the last line of the file.

also if you're using the snap version.  don't.  It quite old and has a number of weird issues.

you might want to try this [launchpad repository](https://launchpad.net/~zarquon42/+archive/ubuntu/meshlab)
