### ISSUE TITLE
open OBJ: first vertex + 1-fan get's lost

### ISSUE THREAD

**Issue by BruegelN** [cnr-isti-vclab/meshlab#791]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [ ] Linux
- [x] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
Meshlab 2020.09 introduced a bug where the first vertex including it's 1-fan *get's lost* when loading an OBJ file resulting in a hole.
See 2020.09 vs 2020.07:
![Bildschirmfoto 2020-09-08 um 16 45 04](https://user-images.githubusercontent.com/9728182/92493332-acb3cc00-f1f4-11ea-88c1-3c1701ff96ea.png)
Occurs both when opening the OBJ file by drag-and-drop and via "Import Mesh".
This is the mesh but happens with other OBJs too [armadillo.obj.zip](https://github.com/cnr-isti-vclab/meshlab/files/5189124/armadillo.obj.zip)

I'm using macOS 10.15.6.

**Comment by alemuntoni** [comment]
I have updated all the releases of the 2020.09 version. 
Unfortunately, it has been built on a wrong commit that has been already reverted. 
Obj importer should work again now!

**Comment by BruegelN** [comment]
Hi @alemuntoni,

thanks for the quick response and fast fix, awesome!
<img width="1552" alt="Bildschirmfoto 2020-09-08 um 20 49 06" src="https://user-images.githubusercontent.com/9728182/92516068-ec8aab80-f214-11ea-8b72-03593da3a952.png">
btw: homebrew should update soon, too https://github.com/Homebrew/homebrew-cask/pull/88937
