### ISSUE TITLE
Load custom shaders from user-defined directories on snap and AppImage packages

### ISSUE THREAD

**Issue by h3ct0r** [cnr-isti-vclab/meshlab#792]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [X] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [X] other: Unable to edit config files?

#### Describe your issue

Hi, this is really more a question since the recommended install procedure for Ubuntu >= 16.04 is to use snap packages. In this case, which is the recommended way to add new shaders for a Meshlab in Ubuntu installed via snap? It seems that snap mounts a RO filesystem so its not possible to add the shared directly. Any light on this is appreciated.

Thanks,

**Comment by alemuntoni** [comment]
Right now it is not possible on snaps, nor on AppImages. 
The only way to do it on linux is to download the [portable version](https://github.com/cnr-isti-vclab/meshlab/releases/download/Meshlab-2020.09/MeshLab2020.09-linux.tar.gz) and then add your shader in the proper folder.

I'll mark the issue as a feature request, since it would be great to have the possibility to load shaders from user-defined directories.

**Comment by h3ct0r** [comment]
Hi @alemuntoni, thanks for the link! Yes, this feature of user-defined directories will be nice, as messing around at the installation folder could be cumbersome. Maybe a ~/.meshlab folder created at runtime will do the trick to store and load custom configurations!

**Comment by h3ct0r** [comment]
Maybe is a good idea to change the title of this issue to something like "Load custom shaders from user-defined directories on snap and AppImage packages"?

**Comment by alemuntoni** [comment]
This feature has been added on PR #919.
When a new GDP file is loaded (Render -> Shaders -> Add Shaders), it will be copied (along .vert and .frag files) in a proper system location (depending on the OS) that is automatically checked for shader files. It will be available in the next meshlab version!

**Comment by h3ct0r** [comment]
Very cool @alemuntoni ! I will test it when available. Thanks!
