### ISSUE TITLE
Can't save a u3d mesh with old meshlab and can't seem to get the new 2020 .07 to function!

### ISSUE THREAD

**Issue by nymf99** [cnr-isti-vclab/meshlab#793]
I tried to open meshlab and was prompted to download the newest version which I did. During the download process, I was prompted to delete my old version. Following this, I successfully downloaded the new version but it would not load. I did not take a screenshot of the issue to report as I thought it would be faster to complete a system restore to get the old program back.
After recovering the old meshlab, I am trying to expert mesh as a .u3d file but now have an error that says, "Missing converter executuable 'C:/Programfiles/VCG/Meshlab/plugins/IDTFconverter.exe'.
Any help is greatly appreciated as all I want is to convert to .u3d so I can try and create a pdf file.
Thanks!

**Comment by alemuntoni** [comment]
Well, here the main issue is that the new issue would not load. Could you please share the windows version and the meshlab version you are running?
Apparently, the system restore did not actually restored everything, missing the IDTFconverter.exe that is not present in newer versions of meshlab.
