### ISSUE TITLE
MeshLab exits/crashes importing OBJ

### ISSUE THREAD

**Issue by lex3001** [cnr-isti-vclab/meshlab#796]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
I am attempting to import an OBJ into MeshLab_64bit_fp v2020.07 (built on Jul  1 2020) and Meshlab is crashing. The OBJ has about 1.1M triangles. It was exported from Blender and has an MTL and three texture images. It opens fine in Blender, Meshmixer, and 3D Viewer on the same computer. I don't think it is a memory issues as Meshlab says I have about 6GB free (611/6144 MB). In Blender it takes 341MB. 
If I run Meshlab as Administrator, it stays open but the mesh is never displayed.

I would prefer not to post a public link to the mesh but I will share it with individual(s) who would like to test/fix. Not sure the best way to do that -- does GitHub have direct messaging?

I see on the status bar that it is loading vertices etc. and gets through Face Loading to 99% and then says Done in the lower left, and then MeshLab just closes.

I looked in the Event Viewer in Windows after and found this:

Log Name:      Application
Source:        Application Error
Date:          9/17/2020 4:16:19 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      LEXINATOR-M15
Description:
Faulting application name: meshlab.exe, version: 0.0.0.0, time stamp: 0x5efc3e4c
Faulting module name: meshlab.exe, version: 0.0.0.0, time stamp: 0x5efc3e4c
Exception code: 0xc0000005
Fault offset: 0x00000000000a3ab2
Faulting process id: 0x1a89c
Faulting application start time: 0x01d68d4887b2bea8
Faulting application path: C:\Program Files\VCG\MeshLab\meshlab.exe
Faulting module path: C:\Program Files\VCG\MeshLab\meshlab.exe
Report Id: f09a79b6-64c9-4951-b344-e4784d9180e2
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-09-17T23:16:19.625389700Z" />
    <EventRecordID>77567</EventRecordID>
    <Channel>Application</Channel>
    <Computer>(REMOVED)</Computer>
    <Security />
  </System>
  <EventData>
    <Data>meshlab.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5efc3e4c</Data>
    <Data>meshlab.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5efc3e4c</Data>
    <Data>c0000005</Data>
    <Data>00000000000a3ab2</Data>
    <Data>1a89c</Data>
    <Data>01d68d4887b2bea8</Data>
    <Data>C:\Program Files\VCG\MeshLab\meshlab.exe</Data>
    <Data>C:\Program Files\VCG\MeshLab\meshlab.exe</Data>
    <Data>f09a79b6-64c9-4951-b344-e4784d9180e2</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

```
...

**Comment by alemuntoni** [comment]
Could you please send me an email with the link to the obj file? Thanks!
muntoni.alessandro (at) gmail.com

**Comment by lex3001** [comment]
Link sent, thank you!

**Comment by alemuntoni** [comment]
Thanks! I can confirm the crash. I'll investigate.

**Comment by lex3001** [comment]
Excellent.

**Comment by DCxDemo** [comment]
i found out a specific crash case, when OBJ uses quad declarations (f 1/1 2/2 3/3 4/4) meshlab crashes if mtl file contains more than 1 material. these files do not crash in blender. tested the latest github release, let me know if i should test another build.
doesn't crash with triangles (f 1/1 2/2 3/3).
doesn't crash if second material is removed from mtl file.

sample files:
test.mtl
```
newmtl test
map_Kd test.png

newmtl test2
map_Kd test2.png
```
test.obj
```
mtllib test.mtl

v 10 0 0
vt 1 0
v 0 0 0
vt 0 0
v 0 10 0
vt 0 -1
v 10 10 0
vt 1 -1

usemtl test
f 1/1 2/2 3/3 4/4

v 20 0 0
vt 1 0
v 10 0 0
vt 0 0
v 10 10 0
vt 0 -1
v 20 10 0
vt 1 -1

usemtl test2
f 5/5 6/6 7/7 8/8
```
