### ISSUE TITLE
Missing Sketchfab plugin to Meshlab

### ISSUE THREAD

**Issue by pmd3sallijr** [cnr-isti-vclab/meshlab#797]
Hi,
I have just downloaded the latest version of Meshlab but it doesnt have the Sketchfab plugin. Please could someone tell me how to load this. It also doesn't appear in the Meshlab plugin directory that come with the install?
Thanks,
Jim

**Comment by alemuntoni** [comment]
Please read the issue guidelines before submitting an issue. 
Which OS are you using?

**Comment by pmd3sallijr** [comment]
Sincerest apologies. I am running Windows 10. Thank you, Jim

**Comment by alemuntoni** [comment]
Thanks for reporting this, sketchfab is missing on windows since 2020.07. 
I'll investigate.

**Comment by alemuntoni** [comment]
Update: filter sketchfab is missing only on widows builds since PR #702 was merged. However, the isse  depends on something related with the github actions build system, because if meshlab is built locally, filter sketchfab works as expected.

**Comment by pmd3sallijr** [comment]
Apologies but I am not very familiar with software/programming. Are you able to explain that a little more simply? Can I install the plugin on my 2020 version?
Thank you,
Jim

**Comment by alemuntoni** [comment]
Nope, unfortunately this is not an easy fix. Right now, the only way to use the sketchfab plugin on windows is installing 2020.06 version, or using meshlab from MacOS and Linux.

**Comment by alemuntoni** [comment]
Solved on commit [8098ee2](https://github.com/cnr-isti-vclab/meshlab/commit/8098ee2b88725446ab2ef294dd0a2923ca93b6a5). It will be available starting from the next MeshLab version!
