### ISSUE TITLE
libqconnmanbearer.so: undefined symbol: _ZdlPvm

### ISSUE THREAD

**Issue by jgascon** [cnr-isti-vclab/meshlab#801]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [X] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [X] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

Dear developers, 

When I try to start meshlab linux image app (after giving it execution permissions) in the shell, the executable fails and crashes, it does not launch at all, the error I get in the shell is:

/tmp/.mount_MeshLakPvPBF/usr/bin/meshlab: symbol lookup error: /tmp/.mount_MeshLakPvPBF/usr/plugins/bearer/libqconnmanbearer.so: undefined symbol: _ZdlPvm, version Qt_5

I am using Arch linux 64 bits, Linux 5.8.6-1-MANJARO #1 SMP PREEMPT Thu Sep 3 14:19:36 UTC 2020 x86_64 GNU/Linux

Thank you in advance
...

####Guidelines for a good issue

Before submitting an issue: 

- be as detailed as possible. If the issue is related to a specific mesh or file, please attach it. Make sure that the problem is reproducible; 
- specify the operative system you are using and its version/distribution; if it is possible, verify if the problem persists in other platforms;
- bspecify the MeshLab version you are using and be sure that your issue also happens on the last MeshLab version;
- check if your issue has been already reported by someone else. In this case, do not open another issue: just add your experience in the existing issue;
- If the issue is specific of a platform, please specify it on the subject in square brackets (example: `[MacOS] crash when opening obj`);
- delete these guidelines before submitting :)

**Comment by alemuntoni** [comment]
Found a similar error [here](https://dev.cancel.fm/tktview/11ddfb1536) for ripcord. Seems that it is not related to MeshLab, but to some strange configuration on some linux systems.
