### ISSUE TITLE
Alt + Scroll doesn't change point size anymore -- snaps to default instead

### ISSUE THREAD

**Issue by nvibd** [cnr-isti-vclab/meshlab#803]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

Ubuntu 18.04.
Meshlab 2020.07, using .AppImage.

Alt + Scroll doesn't change point size anymore. Instead, the point size will jump to the default value set in the options and stay there.

This used to work fine on earlier versions of Meshlab.

**Comment by alemuntoni** [comment]
Thanks for reporting this! I'll investigate.

**Comment by nvibd** [comment]
@alemuntoni I'm still seeing this error with 2021.5, installed via snap. Could you please reopen? Or tell me why you closed?

**Comment by alemuntoni** [comment]
Because has been solved with the linked commit, and it works fine both with my snap and appimage...

**Comment by nvibd** [comment]
My bad, I figured out that I'm seeing the issue because of `imwheel`. I'm using `imwheel` as a workaround for another issue.
Sorry for being aggressive, I've seen it many times that maintainers close issues without any patches. :) 
Is there any chance for a patch for using `imwheel`?

**Comment by alemuntoni** [comment]
I don't think there will be chances. We use Qt tools to manage mouse and keyboard in meshlab, therefore if Qt does not support it, we can't do much more.
