### ISSUE TITLE
distance of point to point

### ISSUE THREAD

**Issue by szryuu** [cnr-isti-vclab/meshlab#804]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [x] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [x] other (specify...)

#### Describe your issue
When I displaying a ply file ,how can I show the distance of point to point ?

**Comment by jmespadero** [comment]
This is not an issue for developers, you should post this in a user's forum (for example, stackoverflow.com)

**Comment by alemuntoni** [comment]
I think there is no tool to compute the distance between two vertices of a mesh. 
You could use the measuring tool, but it won't be the precise distance between two vertices of a mesh.

**Comment by szryuu** [comment]
> I think there is no tool to compute the distance between two vertices of a mesh.
> You could use the measuring tool, but it won't be the precise distance between two vertices of a mesh.

**Comment by szryuu** [comment]
> I think there is no tool to compute the distance between two vertices of a mesh.
> You could use the measuring tool, but it won't be the precise distance between two vertices of a mesh.

thank you
