### ISSUE TITLE
Meshlab unable to reload bin STL saved in Meshlab

### ISSUE THREAD

**Issue by GiovanniSer** [cnr-isti-vclab/meshlab#806]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

I use a lot of Meshlab to regularize the normal vectors. No problem until tonight. A shape executed as always, saved by me from CAD in ascii is loaded, after normalization I save the new STL in binary format.
But Meshlab is no longer able to load it. ("Malformed File error")
I downloaded the new 2020.7 version but the problem is identical to the 2020.6 version.
If I save in ASCII instead of bin, the shape is loaded as usually.
This is the file that creates the problem.
[FStipoTspurZv1.zip](https://github.com/cnr-isti-vclab/meshlab/files/5368335/FStipoTspurZv1.zip)

**Comment by GiovanniSer** [comment]
Well I spent a little time doing practical tests.
By varying the number of faces, because I had never had this problem.
Count faces base 1.
faces 1 to 6655 all ok
faces 6656 to 6911 Meshlabs fails to load bin STL (all my other 3D programs loading the same shape run fine)
faces 6912 to up all ok.
Well, a first attempt at reasoning:
6911 - 6656 = 255 (suspected number!)
Note: I  am sure the faces are good, I used a mirror to enlarge the shape ... and it works in largest  files with same faces not working... or lower files...
Next step : to try with a different project, but I am convinced that the problem is in the number of faces and not in their arrangement.

**Comment by GiovanniSer** [comment]
Ok, I confirm because I checked with a different shape
When the shape is in the range 6656-6911 faces and the file is binary, Meshlab fails loading it.
The same file, in ASCII STL, is loaded successfully.
I checked exactly the low difference (6655 ok, 6656 no).

**Comment by alemuntoni** [comment]
Thanks @GiovanniSer for all the details. 
I confirm the issue, and it happens only on Windows. I am quite busy this time, I'll check on this whenever it will be possible!

**Comment by GiovanniSer** [comment]
Thanks, today the same problem has come back, but with 19,482 faces. It certainly has periodic ranges...

**Comment by alemuntoni** [comment]
This issue has been already fixed with previous stl fixes. Closing
