### ISSUE TITLE
meshlab2020.07can not load obj data on ubuntu 18.04

### ISSUE THREAD

**Issue by MrCrazyCrab** [cnr-isti-vclab/meshlab#807]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
i installed the meahlab by following the order "sudo snap install meshlab", but the software can not load any obj or stl data on ubuntu18.04, it warns the file open error. And the meshlab2016 can run without any problem, but it can not linked to the data only opening data by draging it to the software?
how can i sovle the problem of mashlab2020.07?

**Comment by alemuntoni** [comment]
Is the data you are trying to load in the same partition of the filesystem where the snap is installed?
It may be related to #466. Try to use the last [AppImage](https://github.com/cnr-isti-vclab/meshlab/releases).

**Comment by SebastianGrans** [comment]
I just wrote a solution in the other issue: [#466](https://github.com/cnr-isti-vclab/meshlab/issues/466#issuecomment-725324256)
