### ISSUE TITLE
A bug was found in filter simplification

### ISSUE THREAD

**Issue by weiyu666** [cnr-isti-vclab/meshlab#812]
In the latest release package released in September 2020, it is "simp" lfication:Edge Collapse  for Marching Cude meshes”
![图片](https://user-images.githubusercontent.com/22174508/96703308-46aa8f00-13c5-11eb-8188-dba5ebc08f99.png)
在源代码中也没有找到！
![图片](https://user-images.githubusercontent.com/22174508/96703394-604bd680-13c5-11eb-8d7a-9a6b3c849637.png)

**Comment by alemuntoni** [comment]
Thanks for reporting this! Fixed on commit [ca69181](https://github.com/cnr-isti-vclab/meshlab/commit/ca69181cfb5a3351db82832644a0837f33c84b75).
