### ISSUE TITLE
Could there be a tutorial about how to add the code of a specific plugin on our own?

### ISSUE THREAD

**Issue by grtzsohalf** [cnr-isti-vclab/meshlab#814]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [ ] Linux
- [x] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [x] other (tutorial)

#### Describe your issue

Hi, thanks for the great source code!
Because I want to implement and experiment some features by myself, 
I wonder if there could be a tutorial about which files we need to modify to correctly compile Meshlab with our new feature (for example some .pro files I guess?) ?
Thank you very much!

**Comment by alemuntoni** [comment]
Hi, 
right now there is no tutorial for creating plugins (it is in the todo list).
You could create a copy of folder "filter_sample" in the meshlabplugins, and start from there. It is commented explaining what the filter does.

P.S. We are switching to CMake: I suggest to use the CMakeLists files!

**Comment by grtzsohalf** [comment]
Thanks for your immediate response!
I will start from there.
Thank you again!

**Comment by grtzsohalf** [comment]
Sorry, one more question.
After I git clone this repo, I can build with `scripts/Linux/1_build.sh` without errors.

Then I tried to use `src/make-cmake.py` to generate the required `CMakeLists.txt` files for new plugins,
but I found these `CMakeLists.txt` files had become different from the original ones.

After I ran `scripts/Linux/1_build.sh`, three kinds of errors occurred:

1.
```
In file included from /home/grtzsohalf/code/meshlab/src/common/meshlabdocumentbundler.cpp:15:
/home/grtzsohalf/code/meshlab/src/vcglib/wrap/io_trimesh/import_out.h:35:10: fatal error: exif.h: No such file or directory
   35 | #include <exif.h> //external easyexif lib
      |          ^~~~~~~~
compilation terminated.
```

2. A lot of errors:
```
CMake Error at meshlab/xxx/CMakeLists.txt:xxx (add_executable/library):
  Target "xxx" links to target "Qt5::Script" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

3. 
```
CMake Error at meshlabplugins/edit_align/CMakeLists.txt:67 (add_library):
  Cannot find source file:

    align/AlignPair.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at meshlabplugins/edit_pickpoints/CMakeLists.txt:49 (add_library):
  Cannot find source file:

    ../../meshlab/stdpardialog.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
```

Is there a bug in `src/make-cmake.py`?
Thank you!

**Comment by alemuntoni** [comment]
Hi, 
please re-clone the repo and try again (and post here if there is any issue)!
I'm going to remove `src/make-cmake.py` since now the cmake build is not anymore auotomatically generated from qmake.
