### ISSUE TITLE
surface reconstruction poisson new version bug with more than one mesh

### ISSUE THREAD

**Issue by bardou71** [cnr-isti-vclab/meshlab#816]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
I have installed today the version 2020.07 and the surface reconstruction bug when "merge all visible layers" is selected
orientation of the faces is reversed and not all visible layers are taken
I dont know the number of the version I have used before (but the poisson reconstruction was the last item of the list) and it seem have no problem with 2 or 3 point cloud merged

...

**Comment by anbellit** [comment]
I notice a similar behaviour with 2020.09 on Windows: I have 4 active point clouds; I select "merge all visible layers"; I click Apply, and the program creates a new "poisson Mesh" with 0 faces and 0 Vertices. If I use 2020.03, the new poisson mesh is created.

**Comment by alemuntoni** [comment]
Hi all, could you please provide files of the involved meshes and the exact sequence of the executed operations in order to reproduce the behavior? 
Thanks.

**Comment by anbellit** [comment]
This is my sequence:
Import mesh4
Import Mesh6
I don't save the project
I launch the filter 'Surface Reconstruction: Screened Poisson'
Check 'Merge all visible layers'
Reconstruction depth -> 11
Adapt. octree d. -> 6
Min Numb Samples -> 3
Check Pre-clean
Click on Apply
I have a new 'poisson mesh', with no points and no faces, in few seconds.

If I launch Poisson on a single cloud, with the same parameters but without the 'merge all visible layers' it reconstructs the mesh.
Tested on win10 and win7, 16Gb RAM, graphic board Nvidia Quadro 2Gb dedicated memory
My files are heavy, here the link to download:
https://drive.google.com/file/d/1mMPWr81WLEoS5mFHFev_gANkkymFpdIw/view?usp=sharing
https://drive.google.com/file/d/1HSOwaKM3Umc00urg38fp2ygIYQRvNkZ_/view?usp=sharing

**Comment by alemuntoni** [comment]
@anbellit I tried this on linux with 2020.12 and it works fine. I'll check on windows ASAP. In the meantime, could you please check if it works with 2020.12?

**Comment by anbellit** [comment]
No, with 2020.12, Windows, the problem remains: I have a new 'poisson mesh' in few seconds, with 0 vertices and 0 faces. Maybe my files are too heavy?

**Comment by mcallieri** [comment]
we confirm there is something fishy. There is a problem with transformation matrices
Quick possible temporary fix: flatten visible layer (keep unreferenced if you have poitclouds), then do poisson

**Comment by anbellit** [comment]
Thanks. I tried the workaround, and for my work is OK.

**Comment by alemuntoni** [comment]
Fixed with last commit!
The fix will be available in the next version, or you can use the nightly build generated by github actions!
