### ISSUE TITLE
Subdivision surfaces schemes

### ISSUE THREAD

**Issue by cedric-gerot** [cnr-isti-vclab/meshlab#82]
The subdivision schemes for surfaces do not run correctly in version 2016.12: the mesh is not smoothed and the vertices diverge.

Example:
1/start
2/Filters->Create New Mesh Layer->Sphere[radius=1; Subdiv. Level=1]->Apply->Close
3/Filters->Remeshing, Simplification and Reconstruction->Subdivision Surfaces:Loop[Iterations=1; Edge Threshold=0]->Apply->Close

With version 2016.12, on Windows 7, we get the following results:
 - after step 2: 2016.12-Win7-snapshot00.png [OK]
 - after step 3: 2016.12-Win7-snapshot01.png [Pb]

In order to compare, with the older version 1.3.2_64 on Debian-8.2, we get the following results:
 - after step 2: 1.3.2_64-Debian8.2-snapshot00.png [OK]
 - after step 3: 1.3.2_64-Debian8.2-snapshot01.png [OK]
![2016 12-win7-snapshot00](https://cloud.githubusercontent.com/assets/25849114/23074919/7b8de89e-f532-11e6-9a31-ea747905bfe7.png)
![2016 12-win7-snapshot01](https://cloud.githubusercontent.com/assets/25849114/23074917/7b88f866-f532-11e6-98e7-d861704b7670.png)
![1 3 2_64-debian8 2-snapshot00](https://cloud.githubusercontent.com/assets/25849114/23074918/7b8a54b8-f532-11e6-88f7-7fbcc2f8b75d.png)
![1 3 2_64-debian8 2-snapshot01](https://cloud.githubusercontent.com/assets/25849114/23074916/7b87dba2-f532-11e6-965d-b3f859c8d7c7.png)

**Comment by cignoni** [comment]
I have just tried to replicate the issue on osx, using both the distributed version and a freshly compiled, but it seems to work correctly... 

![out](https://cloud.githubusercontent.com/assets/8055819/23179014/c19405f2-f86c-11e6-9902-cbd98a9ca768.gif)

I will try on other platforms...

**Comment by cedric-gerot** [comment]
Hi,

 

I thank you for your concern. If you need extra-information about my os or computer, do not hesitate to ask me.

 

Note that a similar problem occurs for any subdivision scheme (Catmull-Clark, Butterly etc.)

 

Cedric

**Comment by mcallieri** [comment]
it works on Win8, everything seems ok.

**Comment by cignoni** [comment]
Can you try on linux if the 2016.12 version? 

There is a handy meshlab snap package provided by Mardy
so you can install by typing 

    snap install meshlab-mardy

Then you can launch the program from the terminal as meshlab-mardy.meshlab (or just launch it via the graphical interface).

**Comment by cedric-gerot** [comment]
It seems that snap is not available for Debian 8 (Jessie), the current stable release. It is available for Stretch (Debian 9) but it is the current testing distribution.

 

Cedric

**Comment by cedric-gerot** [comment]
Note that I have just installed an old BETA version (MeshLabDevel_v134BETA_64bit_2014_05_28) from source forge

https://sourceforge.net/projects/meshlab/

on my Windows7 computer, and the Loop subdivision works fine with this version.

 

Cedric

 

From: Cedric Gerot [mailto:cedric.gerot@gipsa-lab.grenoble-inp.fr] 
Sent: 22 February 2017 09:34
To: 'cnr-isti-vclab/meshlab' <reply@reply.github.com>; 'cnr-isti-vclab/meshlab' <meshlab@noreply.github.com>
Cc: 'cedric-gerot' <cedric.gerot@gipsa-lab.fr>; 'Author' <author@noreply.github.com>
Subject: RE: [cnr-isti-vclab/meshlab] Subdivision surfaces schemes (#82)

 

It seems that snap is not available for Debian 8 (Jessie), the current stable release. It is available for Stretch (Debian 9) but it is the current testing distribution.

 

Cedric
