### ISSUE TITLE
Segmentation fault when applying filter "Remove t-vertices by Edge Collapse"

### ISSUE THREAD

**Issue by quirxi** [cnr-isti-vclab/meshlab#821]
#### Check all platforms you experienced the issue
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
![Meshlab_bug00](https://user-images.githubusercontent.com/5494409/98436696-abf8c280-20dd-11eb-936e-611c55b3c140.png)
![Meshlab_bug01](https://user-images.githubusercontent.com/5494409/98436693-aa2eff00-20dd-11eb-8530-c31021220d27.png)

Whenever I apply the filter "Filters->Cleaning and Repairing->Remove t-vertices by Edge Collapse" on the mesh [voroni_hand.ply](https://drive.google.com/file/d/1JDBOOCtYHkQiUmiluO5NWg_bONap7Ali/view?usp=sharing) meshlab causes a segmentation fault and shuts down immediately.

The output on the console says:

> > ./MeshLab2020.07-linux.AppImage 
> Current Plugins Dir is: /tmp/.mount_MeshLaAA69vA/usr/lib/meshlab/plugins 
> Shader directory found '/tmp/.mount_MeshLaAA69vA/usr/share/meshlab/shaders', and it contains 19 gdp files
> LOG: 0 Opened mesh /home/user/3D/Voronoi_Hand/voroni_hand.ply in 328 msec
> LOG: 0 All files opened in 347 msec
> Segmentation Fault (core dumped)

The kernel writes following to the log:

> [ 6387.462029] meshlab[15010]: segfault at 48aa778 ip 00007f1433353c64 sp 00007ffc741d23c0 error 4 in libfilter_clean.so[7f1433323000+40000]
> [ 6387.462040] Code: 05 48 8d 04 f8 48 03 86 f0 00 00 00 48 89 c6 48 8b 00 48 85 c0 74 25 48 29 d8 48 8b bc 24 80 00 00 00 48 c1 f8 04 49 0f af c6 <48> 8b 04 c7 48 8d 04 40 48 c1 e0 04 48 01 d8 48 89 06 83 c1 01 83

**Operating system:** Linux 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux
**Meshlab Version:** MeshLab2020.07-linux.AppImage

You can download the [core dump](https://drive.google.com/file/d/1tBvC0hCgJeIp9aScAtokwvSsejJ82FG3/view?usp=sharing) from [google drive](https://drive.google.com/file/d/1tBvC0hCgJeIp9aScAtokwvSsejJ82FG3/view?usp=sharing) (174 MB!!) and also the [3D model](https://drive.google.com/file/d/1JDBOOCtYHkQiUmiluO5NWg_bONap7Ali/view?usp=sharing) I used.

I could not verify if this bug also exists on other platforms.

**Comment by alemuntoni** [comment]
Hi @quirxi, does this crash happen also with 2020.09? 
With the last version I cannot replicate the issue.

**Comment by quirxi** [comment]
Hi @alemuntoni, just tried out the 2020.09 version of meshlab and I  am sorry to say that the segmentation fault also occurs with this version on my computer. Do you need further information/data to investigate in this ?

**Comment by alemuntoni** [comment]
The only difference is that I am using ubuntu instead of debian, but I don't think that this could be the cause.
The number of iterations paramater of the filter is the default value (40)?

**Comment by quirxi** [comment]
Yes - the number of iterations of the filter was the default value of 40.

Just compiled meshlab (MeshLab_64bit_fp v.2020.09 / gcc 8.3.0 / Qt 5.11.3) from sources on Debian 10.0.0 ( Buster ) after installing these packages:
* cmake
* qt5-default
* libqt5xmlpatterns5-dev
* qtdeclarative5-dev

The compilation was running very smooth - there weren't any problems at all :).

I tried to reproduce the segmentation fault  by opening the [voroni_hand.ply](https://drive.google.com/file/d/1JDBOOCtYHkQiUmiluO5NWg_bONap7Ali/view?usp=sharing) mesh and applying the filter  "Remove t-vertices by Edge Collapse" to it. This time there was no segmentation fault, but an abort() due to an assertion.

Here is the output from the console:

> > ./meshlab 
> Current Plugins Dir is: /home/meshlab/src/build/distrib/plugins 
> Shader directory found '/home/meshlab/src/build/distrib/shaders', and it contains 19 gdp files
> LOG: 0 Opened mesh /opt/voroni_hand.ply in 568 msec
> LOG: 0 All files opened in 569 msec
> meshlab: /home/meshlab/src/vcglib/vcg/complex/allocate.h:1288: static void vcg::tri::Allocator<MeshType>::CompactFaceVector(MeshType&, vcg::tri::Allocator<MeshType>::PointerUpdater<typename MeshType::FacePointer>&) [with MeshType = CMeshO; typename MeshType::FacePointer = CFaceO*]: Assertion `fbase <= (*fi).FFp(i) && oldIndex < pu.remap.size()' failed.
> Aborted

Do you think that could help to find the bug ?

**Comment by quirxi** [comment]
Now I also found out what might trigger the bug.

Whenever the filter is applied while in the *Layer dialog* the tab with the "Boundary Edges", "Boundary Faces", "No-Manif Verts" and "No-Manif Edges" is displayed the bug occurs:
![LayerNOK](https://user-images.githubusercontent.com/5494409/99121763-49338980-25fd-11eb-97a9-ff2987e40d98.png)

Whenever the filter is applied and the *Layer dialog* tab shows the "Shading", "Color" and "Back-Face" entries the bug is **not** triggered:
![LayerOK](https://user-images.githubusercontent.com/5494409/99121769-4afd4d00-25fd-11eb-8458-f99e59c09c98.png)

Probably you did not activate this tab in the Layer dialog when you tried to reproduce the bug and that is why we got different results?

**Comment by alemuntoni** [comment]
It makes sense, I reproduced the crash! Thanks, Will look into it!
