### ISSUE TITLE
Filling holes on mesh with conditions

### ISSUE THREAD

**Issue by kathanvyas** [cnr-isti-vclab/meshlab#824]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows

#### What type of issue is?
- [x] other (specify...)

#### Describe your issue
So I have a mesh that I created using my registration algorithm. This mesh is of a dummy kid. Because the hands and legs are too close to the body, the scanning cam was not able to figure out the depth in between. so I used meshlab to remove points between the hand and body and between the mesh after I apply the screened poison. However, it leaves holes. I cannot fill the holes. Please see the figures for more details.

Image1: This image shows how there is some material in between hands and body and between two legs:
![before](https://user-images.githubusercontent.com/30324812/98862346-bd6f0100-2434-11eb-823a-6600be189ad7.JPG)

image2: This image shows after i have removed the material from the middle. this is what i want so that i can have hands and legs separate.
![after](https://user-images.githubusercontent.com/30324812/98862511-058e2380-2435-11eb-851c-c0758c2fd31a.JPG)

image3: this is my issue. After removing, it leaves such holes. when i use fill holes option, it again takes be back to something like image 1.
![holes](https://user-images.githubusercontent.com/30324812/98862531-0d4dc800-2435-11eb-9b0e-9e39ddd8a9b0.JPG)

How can I just fill these holes so I can get complete mesh without anything in the middle of the body -hands-and legs. I tried re-computing surface normals and trying again but it doesn't work.

**Comment by kathanvyas** [comment]
@alemuntoni anyway you can suggest me what to do here

**Comment by alemuntoni** [comment]
Sorry, I think there is no way to do this with the current meshlab tools.
