### ISSUE TITLE
Segmentation fault when loading any mesh in CentOS

### ISSUE THREAD

**Issue by satansin** [cnr-isti-vclab/meshlab#825]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
I am using CentOS Linux release 7.8.2003 to run MeshLab version 2020.09.
The software however crashes every time I try to load any ply file with segmentation fault.
It happens for both GUI and meshlabserver, and looks like the same error.

GUI:
$ /home/meshlab-2020.09/meshlab bunny2.ply
Current Plugins Dir is: /home/meshlab-2020.09/plugins
Shader directory found '/home/meshlab-2020.09/shaders', and it contains 19 gdp files
Segmentation fault

meshlabserver:
$ /home/meshlab-2020.09/meshlabserver -i bunny2.ply
Loading Plugins:
Current Plugins Dir is: /home/meshlab-2020.09/plugins
Total 266 filtering actions
Total 13 io plugins
Opening a file with extension ply
Segmentation fault

Has anyone experienced the same problem? Might a previous version work? Thanks.

**Comment by satansin** [comment]
I just tried version 2020.06, the problem does not exist. It seems that it should be a bug introduced later.

**Comment by alemuntoni** [comment]
Does Meshlab crash also when not opening any mesh?
Also, it is not clear to me if you're using the appimage or the portable version. None of our linux releases has the binary inside the root directory and the plugin directory inside the root directory.
Could you check if [this](https://github.com/cnr-isti-vclab/meshlab/actions/runs/361457986) version works?
