### ISSUE TITLE
Folder with accent: problem with "open with" from file browser

### ISSUE THREAD

**Issue by ferdymercury** [cnr-isti-vclab/meshlab#826]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
When I have a folder with an accent 'í' in the path, then Meshlab is able to open this file correctly via File, Import Mesh. However, if I go instead to my file browser and right click on it, and then do "open with", Meshlab, I get the following encoding error:

![image](https://user-images.githubusercontent.com/10653970/99281599-b4997900-2800-11eb-893e-7bbcf38dd955.png)

**Comment by alemuntoni** [comment]
I cannot replicate this issue, both using AppImage and snap versions on Ubuntu 20.04.
Which version and OS are you using?

**Comment by ferdymercury** [comment]
I was using the default meshlab package on Linux Mint 19 (meshlab 1.3.2).

I confirm that it works fine if I use the latest AppImage.

Thanks!!
