### ISSUE TITLE
Assertion when applying filter "Remove T-Vertices by Edge Flip"

### ISSUE THREAD

**Issue by quirxi** [cnr-isti-vclab/meshlab#827]
#### Platforms you experienced the issue:
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [x] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
![EdgeFlipAssertion01](https://user-images.githubusercontent.com/5494409/99434535-32e44100-290f-11eb-9b01-8a2a21968feb.png)
![EdgeFlipAssertion02](https://user-images.githubusercontent.com/5494409/99434528-311a7d80-290f-11eb-86fe-b30e5bfe7e91.png)

Whenever I apply the filter "Filters->Cleaning and Repairing->Remove t-vertices by Edge Flip" on the mesh ["fish_error.stl"](https://drive.google.com/file/d/1lE0UAC1LmLP93Vk8ay-bRra9fPKMWJo9/view?usp=sharing) meshlab produces an assertion and shuts down immediately.

The output on the console says:

> > ./meshlab 
> Current Plugins Dir is: /home/meshlab/src/build/distrib/plugins 
> Shader directory found '/home/meshlab/src/build/distrib/shaders', and it contains 19 gdp files
> LOG: 0 Opened mesh /home/meshlab/DOWNLOADED/brook-trout/fish_error.stl in 7195 msec
> LOG: 0 All files opened in 9136 msec
> meshlab: /home/meshlab/src/vcglib/vcg/simplex/face/pos.h:196: void vcg::face::Pos<FaceType>::FlipF() [with FaceType = CFaceO]: Assertion `f->FFp(z)->FFp(f->FFi(z))==f' failed.
> Aborted

* When I import the mesh I have to confirm the dialog that says "Unify Duplicated Vertices in STL file". 
* Before applying the filter the "Layer Dialog" with the tab "Boundary Edges", "Boundary Faces", "No-Manif Verts" and "No-Manif Edges" is activated like on the screenshot.
* Self compiled meshlab version: MeshLab_64bit_fp v.2020.09 / gcc 8.3.0 / Qt 5.11.3) 
* Operating System is Debian 10.0.0 ( Buster ).

I am not sure if this assertion would cause a segmentation fault with a version of meshlab that was compiled for release and not for debugging?

**Comment by alemuntoni** [comment]
If compiled for release, goes in infinite loop :)
Thanks for reporting, will look into it as soon as possible!

**Comment by alemuntoni** [comment]
The mesh is non-manifold, and a check before the filter execution was missing!

**Comment by quirxi** [comment]
Thanks for fixing it so fast! :+1:  :)
