### ISSUE TITLE
How to texture a mesh with a .out and .ply file through meshlabserver？

### ISSUE THREAD

**Issue by Haonan-DONG** [cnr-isti-vclab/meshlab#829]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [x] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [x] other (specify...)

#### Describe your issue
Hi, I was trying to texture a mesh using meshlab 's Filters -> Texture -> Parametrization + Texture from registered cameras.
It went well on GUI mode. And then I was trying to do the same thing with Meshlabserver. But it did not work.

My Steps:

1. Download the MeshLabServer2020.09-linux.AppImage
2. Open MeshLab GUI and import a mesh which named test.ply.
3. import images from a folder and use Filters -> Cameras -> Import Cameras for active roasters from a file. (And I loaded a bundler.out file into it.)
4. Use Filters -> Texture -> Parametrization + Texture from registered cameras. (and I got the textured mesh.)
5.  get the .xml with filters -> Show current script and save it up named with test.xml.
6. use server to redo above procedures. (the command line goes like:

_`./MeshLabServer2020.09-linux.AppImage -i data/test/mesh/test.ply -o ./test.ply -p data/test/input/images/test.bundle.out -s test.mlx`_

and it goes wrong like:

Loading Plugins:
Current Plugins Dir is: /home/cvrs/app/MeshLab2020.09-linux/usr/lib/meshlab/plugins 
Total 266 filtering actions
Total 13 io plugins
Opening a file with extension ply
Mesh /home/cvrs/app/MeshLab2020.09-linux/data/test/mesh/scene_mesh.ply loaded has 346913 vn 693459 fn
output mesh  /home/cvrs/app/MeshLab2020.09-linux/test.ply
Apply FilterScript: '/home/cvrs/app/MeshLab2020.09-linux/data/texture_meshlab.mlx'
FilterScript
Reading filter with name Import cameras for active rasters from file
Reading filter with name Parameterization + texturing from registered rasters
Starting Script of 2 actionsfilter: Import cameras for active rasters from file
Problem with filter: Import cameras for active rasters from file
Failed to apply script file /home/cvrs/app/MeshLab2020.09-linux/data/texture_meshlab.mlx

So my queston is:
1. How can repeat the texuture procedure in meshlabserver?
And I think the key issue might be the path of all the input.
Any Help Please.

------------ update -----------------------
I have fixed this problem. And this is just because of the configuration of all input files' path.
So another question is :
**_How can I get test.mlp with .out, .list and a mesh .ply, which is quite easy in the GUI mode._**
(Just import .out and select .list, and then import mesh, and save it.)

Thank you so much!

**Comment by alemuntoni** [comment]
We are going to dismiss meshlabserver in the future, and replace it with [PyMeshLab](https://github.com/cnr-isti-vclab/PyMeshLab). Take a look at it, it should be more flexible to perform the operations that you need!
It is an alpha stage, and we are looking for feedbacks :) If any other issue occurs in PyMeshLab, please open an issue there! :)

**Comment by Haonan-DONG** [comment]
cool, I will give it a shot. And just want to know more about the server, Does the above problem have a feasible solution? :)

**Comment by alemuntoni** [comment]
If I understood correctly, it should not be possible with meshlabserver and also with pymeshlab right now.
When it will be possible to load rasters in pymeshlab, it should be possible to automatize your pipeline easily. 
I still don't know when it will be possible, but I'm working on it!

**Comment by Haonan-DONG** [comment]
I understand and am willing to try both tools. Thank you for your quick response.
