### ISSUE TITLE
MeshLabServer: Failed loading of STL file

### ISSUE THREAD

**Issue by Ethefor** [cnr-isti-vclab/meshlab#83]
Hello! 
I have 3D model generated by Devide and saved as STL. It is possible to open this file in meshlab GUI and export is as IDTF. 

But unfortunately if I want to convert STL to IDTF using meshlabserver I got IDTF file without any vertices. 

I am using MeshLab v1.3.2_64bit on Ubuntu 16.04.
Output of meshlabserver is:
```
$ meshlabserver -i Devide_output.stl -o Meshlab_output_auto.idtf -om vn fn
Input mesh  /home/piotr/Devide_output.stl
output mesh  /home/piotr/Meshlab_output_auto.idtf
Output mask:
vertex normals, face normals, Loading Plugins:
Current Plugins Dir is: /usr/lib/meshlab/plugins 
Error in XMLFile: filter_measure.xml - line: -1, column: -1 - 
Error in XMLFile: filter_mutualinfo.xml - line: -1, column: -1 - 
Total 227 filtering actions
Total 13 io plugins
Opening a file with extention stl
MeshLabServer: Failed loading of /home/piotr/Devide_output.stl from dir /home/piotr/
Mesh Devide_output.stl loaded has 0 vn 0 fn
No Script to apply.
Mesh /home/piotr/Devide_output.stl saved as /home/piotr/Meshlab_output_auto.idtf (0 vn 0 fn)
```

**Comment by mcallieri** [comment]
I tried opening some STL files (both exported from MeshLab and from other tools), ad it is working corretly, it may be a problem with that specific file, or with files exported from a specific tool. Can you send me and example?

**Comment by Ethefor** [comment]
Sorry for late response. I solve problem by installing Meshlab 2016 which
works fine. Anyway, I sent you sample input which cause problem in Meshlab
1.3.2. It was STL generated by Devide.
Piotr Ciążyński

2017-03-26 14:15 GMT+02:00 Piotr Ciążyński <pciazynski@gmail.com>:
