### ISSUE TITLE
crash when loading vertices more than 2000

### ISSUE THREAD

**Issue by LemonMi** [cnr-isti-vclab/meshlab#833]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ -] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [- ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

...
It works well when loading simple obj file, but crash when loading obj more than 2000 vertices, and just no response.  My platform is windows 10,  i tried every version support windows, but all of them doesn't work.

**Comment by LemonMi** [comment]
Maybe this software doesn't support faces with more than three vertices?

**Comment by alemuntoni** [comment]
Could you please share the file that is causing the issue?
