### ISSUE TITLE
Error: Missing postcondition for filter_aging.dll

### ISSUE THREAD

**Issue by tomnmilnes** [cnr-isti-vclab/meshlab#834]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
Cannot start Meshlab after trying to install the new version.
Upon start-up Error message reads: " Error: Missing postcondition for filter_aging.dll Mesh aging and chipping simulation."
Please help as I'm new to anything coding related.
![Critical Error 21_11_2020 16_55_05](https://user-images.githubusercontent.com/74830677/99882829-24519e80-2c1b-11eb-9597-c2902421c9fa.png)

...

####Guidelines for a good issue

Before submitting an issue: 

- be as detailed as possible. If the issue is related to a specific mesh or file, please attach it. Make sure that the problem is reproducible; 
- specify the operative system you are using and its version/distribution; if it is possible, verify if the problem persists in other platforms;
- bspecify the MeshLab version you are using and be sure that your issue also happens on the last MeshLab version;
- check if your issue has been already reported by someone else. In this case, do not open another issue: just add your experience in the existing issue;
- If the issue is specific of a platform, please specify it on the subject in square brackets (example: `[MacOS] crash when opening obj`);
- delete these guidelines before submitting :)

**Comment by alemuntoni** [comment]
Hi! old uninstallers may have some issues.
Follow these instructions:
- uninstall meshlab
- delete manually meshlab's installation folder (default is C:\Programs\VCG\MeshLab)
- install again meshlab

**Comment by zwbdmm** [comment]
@alemuntoni works for me, thanks!!

**Comment by alemuntoni** [comment]
Definitively fixed with c055b433d00f15c2954a8794628e14c9485797a9.
Next meshlab's version will start anyway.
