### ISSUE TITLE
[MacOS] Freeze on point based glueing

### ISSUE THREAD

**Issue by MrRedab** [cnr-isti-vclab/meshlab#835]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [X] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [X] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

I tried to use the align tool. When i set the glued mesh and tried to align the second one with the point based glueing. The window of this function didn't open and the program was blocked. I had to close it with the task manager.

Does someone have similar problems with this function in meshlab on mac os?

Best
Simon

**Comment by alemuntoni** [comment]
Cannot replicate the issue. 
Are you able to replicate every time the behaiviour? In that case, could you share the meshes that are causing the problem?
