### ISSUE TITLE
Compiling for Windows

### ISSUE THREAD

**Issue by flaviu22** [cnr-isti-vclab/meshlab#837]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [X] other (Compiling for Windows)

#### Describe your issue

I have installed GIT, VS2017 and Qt. And WSL. My question is, how can compile this project for windows ?

I mean, how can I arrive from WSL command line window to my project path ?

I am here (inside of WSL):

flaviu@DESKTOP-HP:~$ pwd
/home/flaviu
flaviu@DESKTOP-HP:~$

I mean, how can I do in WSL to rich my meshlab project path ? (D:/Prject/MeshLab)

More over, to get rid of this problems, is possible to use Windows Tools only in order to compile it ?

Thank you.

**Comment by alemuntoni** [comment]
MeshLab is a multi-platform software. Windows tools exist only on windows, open source tools exists on all the platforms, therefore we won't support build systems using "only Windows tools".
If you don't want to use the build scripts, be sure to have installed and set all the required dependencies and open the CMakeLists.txt file with QtCreator.

**Comment by flaviu22** [comment]
Ok, understood. You are right, tools should be platform free.

I am still struggling to compile it for Windows.

I have loaded CMakeLists.txt into Qt, ran, but I got 2 big errors:

:-1: error: CMake process exited with exit code 1.

:-2: error: Generator: execution of make failed. Make command was: jom /nologo cmTC_31413\fast && CMake Error: Generator: execution of make failed. Make command was: jom /nologo cmTC_11cd7\fast && CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeTestCCompiler.cmake:66 (message):  The C compiler    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x86/cl.exe"  is not able to compile a simple test program.  It fails with the following output:    Change Dir: C:/Users/Flaviu/AppData/Local/Temp/QtCreator-bEFxdf/qtc-cmake-GRqlfwdg/CMakeFiles/CMakeTmp        Run Build Command(s):jom /nologo cmTC_11cd7\fast && The system cannot find the file specified    Generator: execution of make failed. Make command was: jom /nologo cmTC_11cd7\fast &&         CMake will not be able to correctly generate this project.Call Stack (most recent call first):  CMakeLists.txt:5 (project)

Ok, then I tried to run CMakeLists.txt into CMake GUI, successfully (I guess):

![image](https://user-images.githubusercontent.com/37621568/100633517-d9303d80-3336-11eb-8902-aa764cfcc88a.png)

And then I open this results into VS2017, but when I compiled I met several errors:

3>mocs_compilation.cpp
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(22): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(22): error C2146: syntax error: missing ';' before identifier 'GLint64'
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(22): warning C4091: '': ignored on left of 'GLint64EXT' when no variable is declared
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(23): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(23): error C2146: syntax error: missing ';' before identifier 'GLuint64'
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(23): warning C4091: '': ignored on left of 'GLuint64EXT' when no variable is declared
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(252): error C2143: syntax error: missing ')' before '*'
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(252): error C2143: syntax error: missing ';' before '*'
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(252): error C2059: syntax error: ')'
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(252): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(253): error C2143: syntax error: missing ')' before '*'
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(253): error C2143: syntax error: missing ';' before '*'
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(253): error C2059: syntax error: ')'
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(253): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(297): error C2143: syntax error: missing ')' before '*'
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(297): error C2143: syntax error: missing ';' before '*'
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(297): error C2059: syntax error: ')'
5>muParserInt.cpp
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(297): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(321): error C2143: syntax error: missing ')' before '*'
3>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(321): error C2143: syntax error: missing ';' before '*'

Obviously I did something wrong, but what ? Could you un-puzzle me a little bit ? I really need you code !

Thank you a lot !

**Comment by alemuntoni** [comment]
I have no clue on visual studio, I never used it.
Talking about the first error, apparently CMake is not finding the MSVC compiler.
Be sure to have the kit properly set (on QtCreator: Projects -> Manage kits). If everything looks fine, try to add to the PATH env variable the path of the msvc compiler (where `cl.exe` is stored).

**Comment by flaviu22** [comment]
The strange thing is that CMake is generating the project:

![image](https://user-images.githubusercontent.com/37621568/101133586-ad9ca400-3611-11eb-88cb-ea01bef3918c.png)

of course, for VS2017, but compiling this project I got:

```
5>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(22): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
5>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(22): error C2146: syntax error: missing ';' before identifier 'GLint64'
5>C:\Qt\Qt5.12.10\5.12.10\winrt_x86_msvc2017\include\QtGui/qopengles2ext.h(22): warning C4091: '': ignored on left of 'GLint64EXT' when no variable is declared

```
If you any clue about how can I solve this, please drop me a message, any hint is important to me !

**Comment by alemuntoni** [comment]
Delete first the two lines in the path env variables regarding cl.exe (btw, they were wrong: meshlab builds just on 64bits)
be sure that the project is using the right kit (in your case: Desktop Qt 5.12.10 MSVC 2017 64bit)
try to manually delete the shadow build directory and try to rerun cmake

**Comment by flaviu22** [comment]
Thanks to you, I succeeded into compiling for Windows.

**Comment by HungNgoCT** [comment]
Hi @flaviu22 ,

After you built on Qt, how can you load mainwindow in Qtdesign for designing? I did not see mainwindow.ui file for load

**Comment by flaviu22** [comment]
> Hi @flaviu22 ,
> 
> After you built on Qt, how can you load mainwindow in Qtdesign for designing? I did not see mainwindow.ui file for load

I am not working on that project now.
