### ISSUE TITLE
MeshCopyConst, MeshAppendConst causing build failure, not found anywhere

### ISSUE THREAD

**Issue by tkircher** [cnr-isti-vclab/meshlab#839]
Building the latest meshlab with the latest vcglib, /common/ml_document/cmesh.cpp tries to call MeshCopyConst and MeshAppendConst, but those are not actually defined anywhere in meshlab or vcglib.

**Comment by alemuntoni** [comment]
Please clone MeshLab with the `--recursive` flag. the vcglib submodule points to the `devel` branch.

**Comment by tkircher** [comment]
Noted, thanks.
