### ISSUE TITLE
System Qhull found but never used

### ISSUE THREAD

**Issue by tkircher** [cnr-isti-vclab/meshlab#841]
The FindQhull.cmake script sets QHULL_FOUND if the library is found, but it is never checked anywhere, and there doesn't seem to be a mechanism for linking it. The version of Qhull in meshlab is long obsolete.

**Comment by alemuntoni** [comment]
filter_qhull uses the target `Qhull::libqhull`, which is found by `FindQhull.cmake`. 
Other targets are not supported at the moment. 
Right now updating the qhull version in the external libraries of meshlab is not in the top of my priorities (no time to test everything right now), but PRs are always welcome.

**Comment by tkircher** [comment]
Leave this open and if I can get meshlab built with a recent Qhull I'll put together a PR, otherwise I'll close this.

**Comment by tkircher** [comment]
@cbbarber

**Comment by alemuntoni** [comment]
Thank you!!! :)

**Comment by StefanBruens** [comment]
Current versions of Qhull no longer provide a non-reentrant library (libqhull), but only the reentrant libqhull_r.

Unfortunately, the bundled Qhull 2003.1 does not provide the reentrant library (which was "just" added with Qhull 2015.1, i.e. 6 years ago). This means the bundled library is source incompatible to the library in any halfway current distribution.

The only sensible way forward now is to update both Qhull and filter_qhull in lock-step.

Porting filter_qhull to libqhull_r is actually quite trivial (I have done the same for several other projects already).

MeshLab should drop the obsolete bundled Qhull 2003.1, which is known to have memory leaks (look at its changelog), and has several more improvements.

**Comment by cbbarber** [comment]
This is a good plan.  
                                --Brad

At 06:10 PM 09/25/2021, StefanBruens wrote:

**Comment by alemuntoni** [comment]
qhull has been updated to 2020.2 version, therefore I guess that this issue can be closed!

**Comment by StefanBruens** [comment]
Latest meshlab (2021.10) was able to find the installed system qhull, so apparently this is fixed.
