### ISSUE TITLE
Problem with Transform: Rotate to fit to plane as a script

### ISSUE THREAD

**Issue by nyersa** [cnr-isti-vclab/meshlab#85]
When using the GUI I am able to select all and then choose the filter to rotate to fit a plane. However if I then save this as a meshlab script and run it via meshlabserver the script fails with the error "Problem with filter: Transform: Rotate to Fit to a plane". 

Version Specs:
Windows 7
Meshlab Version 64bit_fp v2016.12

Script:

<!DOCTYPE FilterScript>
<FilterScript>
 <filter name="Select All">
  <Param description="Select all Faces" value="true" name="allFaces" tooltip="If true the filter will select all the faces." type="RichBool"/>
  <Param description="Select all Vertices" value="true" name="allVerts" tooltip="If true the filter will select all the vertices." type="RichBool"/>
 </filter>
 <filter name="Transform: Rotate to Fit to a plane">
  <Param description="Rotate to fit:" value="0" name="targetPlane" tooltip="Choose the plane where the selection will fit" enum_val1="YZ plane" type="RichEnum" enum_val0="XY plane" enum_val2="ZX plane" enum_cardinality="3"/>
  <Param description="Rotate on:" value="0" name="rotAxis" tooltip="Choose on which axis do the rotation: 'any axis' guarantee the best fit of the selection to the plane, only use X,Y or Z it if you want to preserve that specific axis." enum_val1="X axis" type="RichEnum" enum_val0="any axis" enum_val2="Y axis" enum_cardinality="4" enum_val3="Z axis"/>
  <Param description="Move to Origin" value="true" name="ToOrigin" tooltip="Also apply a translation, such that the centroid of selection rests on the Origin" type="RichBool"/>
  <Param description="Freeze Matrix" value="true" name="Freeze" tooltip="The transformation is explicitly applied, and the vertex coordinates are actually changed" type="RichBool"/>
  <Param description="Apply to all visible Layers" value="true" name="allLayers" tooltip="If selected the filter will be applied to all visible mesh layers" type="RichBool"/>
 </filter>
 <filter name="Select None">
  <Param description="De-select all Faces" value="true" name="allFaces" tooltip="If true the filter will de-select all the faces." type="RichBool"/>
  <Param description="De-select all Vertices" value="true" name="allVerts" tooltip="If true the filter will de-select all the vertices." type="RichBool"/>
 </filter>
</FilterScript>

**Comment by mcallieri** [comment]
confirmed. I wil try finding the issue.

**Comment by granzuglia** [comment]
fixed. thanks a lot for the report

**Comment by nyersa** [comment]
Is there a place I can download a windows binary with your fix applied or do I need to recompile from source to have the update applied

**Comment by mcallieri** [comment]
Not at the moment, it is still only in the GitHub code. As soon as we have a candidate release, I'll let you know. 
In the meantime, I'll do some testing.
