### ISSUE TITLE
Manjaro snap crashing on launch

### ISSUE THREAD

**Issue by hectorlm** [cnr-isti-vclab/meshlab#851]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [X] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [X] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
After snap upgraded to version 2020.12, meshlab does not launch. Trying to launch from the CLI, I see the following messages:
- Unrecognized OpenGL version
- zsh: segmentation fault (core dumped)  meshlab

Installing using --devmode solves this problem.

**Comment by alemuntoni** [comment]
Do you know if the issue existed also with 2020.09?

**Comment by hectorlm** [comment]
I had 2020.09 installed before, it worked with no issue.

**Comment by SohnyBohny** [comment]
I can reproduce the issue on manjaro:
```bash
$ mashlab
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
Current Plugins Dir is: /snap/meshlab/36/usr/lib/meshlab/plugins 
Shader directory found '/snap/meshlab/36/usr/share/meshlab/shaders', and it contains 19 gdp files
Unrecognized OpenGL version
Unrecognized OpenGL version
Unrecognized OpenGL version
Unrecognized OpenGL version
fish: “meshlab” terminated by signal SIGSEGV (Address boundary error)
```

Fortunately the [AppImage](https://github.com/cnr-isti-vclab/meshlab/releases/download/Meshlab-2020.12/MeshLab2020.12-linux.AppImage) works

**Comment by alemuntoni** [comment]
Hi, could you please check if the issue still affects also 2021.05?

**Comment by SohnyBohny** [comment]
```bash
$ meshlab
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
Shader directory found '/snap/meshlab/186/usr/bin/shaders', and it contains 0 gdp files
Shader directory found '/snap/meshlab/186/usr/bin/shaders', and it contains 0 gdp files
Unrecognized OpenGL version
Unrecognized OpenGL version
Unrecognized OpenGL version
Unrecognized OpenGL version
fish: Job 1, 'meshlab' terminated by signal SIGSEGV (Address boundary error)

$ meshlab --version
MeshLab 2021.05
```

**Comment by hectorlm** [comment]
Checked the new version, got the same output as @SohnyBohny

**Comment by tkazik** [comment]
Just experienced something similar under Ubuntu 20.04.
I previously was using the version (`2020.03`) from apt, which worked without issues. Since I wanted to use a newer version in order to [invert scroll wheel direction](https://github.com/cnr-isti-vclab/meshlab/pull/737), I switched to the snap version (`2021.05`), which throws the following error during start-up:

```sh
$ meshlab 
Qt: Session management error: Could not open network socket
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.409\" (uid=1000 pid=20303 comm=\"/snap/meshlab/183/usr/bin/meshlab \" label=\"snap.meshlab.meshlab (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1757 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.409\" (uid=1000 pid=20303 comm=\"/snap/meshlab/183/usr/bin/meshlab \" label=\"snap.meshlab.meshlab (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1757 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
Shader directory found '/snap/meshlab/183/usr/bin/shaders', and it contains 0 gdp files
Shader directory found '/snap/meshlab/183/usr/bin/shaders', and it contains 0 gdp files
Unrecognized OpenGL version
Unrecognized OpenGL version
Unrecognized OpenGL version
Unrecognized OpenGL version
Segmentation fault (core dumped)
```

Any hints or tipps? Thx!

**Comment by alemuntoni** [comment]
We are dismissing snap in favor of flatpack (see #466).
Could you please check if the flatpack works with manjaro?

**Comment by DrBlackross** [comment]
getting the same error on both appimages ( MeshLab2021.07-linux.AppImage, and  MeshLab2021.07d-linux.AppImage ) and after apt install as well.

$ meshlab
Current Plugins Dir is: /usr/lib/x86_64-linux-gnu/meshlab/plugins 
Shader directory found '/usr/share/meshlab/shaders', and it contains 19 gdp files
Unrecognized OpenGL version
Unrecognized OpenGL version
Unrecognized OpenGL version
Unrecognized OpenGL version

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute



![Screenshot from 2021-09-09 18-25-58](https://user-images.githubusercontent.com/20823032/132770773-3a34561d-1994-4359-b23f-95978ad95636.png)


(all im trying to do is punch a hole in a model to print, in blender its scary as hell, and mattercontrol just breaks now lol)

**Comment by alemuntoni** [comment]
@DrBlackross your problem seems not related with this issue: you are not running manjaro.
Please check your graphic drivers, and to have opengl installed.

**Comment by DrBlackross** [comment]
hmmmm,

drblackross@BEAST:~$ glxinfo | grep "OpenGL version"
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.6
drblackross@BEAST:~$ glxinfo | grep 'version'
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.1.6
OpenGL core profile shading language version string: 4.60
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.6
OpenGL shading language version string: 4.60
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.1.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_separate_shader_objects, GL_EXT_shader_implicit_conversions, 
drblackross@BEAST:~$ glxinfo | grep '^direct rendering:'
direct rendering: Yes

seems to be installed just fine, steam doesn't have a problem with it.
![Screenshot from 2021-09-10 15-31-27](https://user-images.githubusercontent.com/20823032/132907467-7ed99fd9-2231-4a51-aea7-e475705ad8ab.png)

**Comment by DrBlackross** [comment]
ok, not installing manjaro (lol, hated dual booting in the 90's) i'll muck with blender, its been about 19 years (lightwave, rhino,blender,3dmax, and yes even poser and bryce)... but ill figure it out. 

thanks anyway
