### ISSUE TITLE
New Meshlab 2020.12 no longer supports JPG rasters

### ISSUE THREAD

**Issue by VisionaryMind** [cnr-isti-vclab/meshlab#852]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ x] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [x ] bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue

Unfortunately, the new version has completely eliminated JPG raster support. Please, bring it back. We have thousands of rasters with JPG extensions, and almost every graphic program in the industry uses both JPG and JPEG. You have presumed that JPEG is the new standard, and this is simply not true. By eliminating support for JPG extensions, you are adding an extra layer of complexity to most workflows, as now any files with this extension output from software will have to be manually renamed.

**Comment by alemuntoni** [comment]
We didn't suppose anything, it was just a mistake :)

**Comment by alemuntoni** [comment]
Solved with the last commit. It will be available with the next version.
Alternatively, you can download the nightly build automatically generated by github actions ([here](https://github.com/cnr-isti-vclab/meshlab/actions/runs/405354616)).

**Comment by VisionaryMind** [comment]
Thank you, I now have 2020.12d and see that it is working. Unfortunately, it is still not possible to project rasters on meshes or pick points between raster / mesh. I will be interested to know when this functionality will be available, as it is the key reason we want to use Meshlab.

**Comment by alemuntoni** [comment]
That's another issue.
I don't know when, because it is a big and old issue that needs a lot of time to be investigated and solved, and I am alone working on meshlab. Anyway, help is always appreciated and pull requests are always welcome.
