### ISSUE TITLE
Add a cylinder

### ISSUE THREAD

**Issue by flaviu22** [cnr-isti-vclab/meshlab#854]
#### Check all platforms you experienced the issue (change to `[x]`)
- [X] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ ] crash
- [X] feature request
- [ ] other (specify...)

I don't know if there is such a feature, if there is, I didn't found it. Can I add a certain cylinder on existing mesh ? Can this library do that ? If not, I can fully imply it myself to achieve this. To explain better, here is the model: https://youtu.be/m8QRhYQtuts, min 5.30

**Comment by alemuntoni** [comment]
Filters -> Create new mesh layer -> cone. You need just to set radius 1 = radius 2
