### ISSUE TITLE
vcruntime140.dll missing

### ISSUE THREAD

**Issue by ScottH123** [cnr-isti-vclab/meshlab#855]
#### Check all platforms you experienced the issue (change to `[x]`)
- [X ] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [ X] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
Just recently uploaded latest Meshlab and after install it returns the error message of missing the vcruntime140.dll file type and crashes. 
...

####Guidelines for a good issue

Before submitting an issue: 

- be as detailed as possible. If the issue is related to a specific mesh or file, please attach it. Make sure that the problem is reproducible; 
- specify the operative system you are using and its version/distribution; if it is possible, verify if the problem persists in other platforms;
- bspecify the MeshLab version you are using and be sure that your issue also happens on the last MeshLab version;
- check if your issue has been already reported by someone else. In this case, do not open another issue: just add your experience in the existing issue;
- If the issue is specific of a platform, please specify it on the subject in square brackets (example: `[MacOS] crash when opening obj`);
- delete these guidelines before submitting :)

**Comment by alemuntoni** [comment]
Thanks for report this! I'll update ASAP the 2020.12 release. In the meantime, you can install [this](https://github.com/cnr-isti-vclab/meshlab/actions/runs/408147697) nightly release.
