### ISSUE TITLE
ML vers. 2020.12 Failed start of Decorate mode Enable shadow mapping

### ISSUE THREAD

**Issue by GiovanniSer** [cnr-isti-vclab/meshlab#856]
#### Check all platforms you experienced the issue (change to `[x]`)
- X Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- X bug or unexpected behavior
- [ ] crash
- [ ] feature request
- [ ] other (specify...)

In STL files (**before working fine**) I get now:
"Failed start of Decorate mode Enable shadow mapping" 
and the render look does not change. [win 10]
B.R.
G.

**Comment by alemuntoni** [comment]
Could you please elaborate? Can you share a file that was working before (which version???) and does not work anymore?

**Comment by GiovanniSer** [comment]
The last two item of the "Render" menu are not working.



[FStipoTspurZv1.zip](https://github.com/cnr-isti-vclab/meshlab/files/5666467/FStipoTspurZv1.zip)

**Comment by GiovanniSer** [comment]
Sorry the message was posted before I finish.
All my files STL have the same problem in the new version. All my files was working before.
"Failed start of Decorate mode Enable Screen Space Ambient Occlusion" and "Failed start of Decorate mode Enable shadow mapping" 
I get this message in the bottom-right log window if I attemp to select the two last render items

**Comment by alemuntoni** [comment]
I just found that this never worked on linux. 
Thanks for reporting. I'll look into this. 
The only thing changed on shadow mapping before 2020.12 is the build system (cmake instead of qmake), therefore it may be related.

**Comment by GiovanniSer** [comment]
Many thanks, this is the difference. At left the function working in a old picture.
![Clipboard01](https://user-images.githubusercontent.com/67306481/101647196-bbe72780-3a38-11eb-9a3c-d884d5abddc5.jpg)

**Comment by alemuntoni** [comment]
Fixed with the last commit. You can download the nightly build from here: https://github.com/cnr-isti-vclab/meshlab/actions/runs/410918534 (when it will be ready)!
