### ISSUE TITLE
'Export Mesh as ...' does not save filtered mesh, but saves unaltered inported mesh

### ISSUE THREAD

**Issue by jpeter42** [cnr-isti-vclab/meshlab#857]
Following opening a ply mesh and applying, e.g., Filters -> Remeshing, Simplification and Reconstruction -> Close Holes, and doing File -> Export Mesh or Export Mesh as ... does not save the modified mesh but the unmodified inported mesh.

Filters -> Mesh Layer -> Flatten visible Layers or Filters -> Mesh Layer -> Matrix: Freeze current matrix do not solve this.

**Comment by jpeter42** [comment]
In my issue report above, I was using meshlab as packaged by archlinux. When, however, building mashlab from the sources, this issue is resolved.

**Comment by alemuntoni** [comment]
Ok, we don't control the archlinux packages. This issue should be reported to whoever manages it.
