### ISSUE TITLE
Windows 10: GLEW error even with CPU OpenGL lib

### ISSUE THREAD

**Issue by NilsRo** [cnr-isti-vclab/meshlab#858]
#### Check all platforms you experienced the issue (change to `[x]`)
- [x ] Windows
- [ ] Mac OS
- [ ] Linux
- [ ] Every platform

#### What type of issue is?
- [ ] bug or unexpected behavior
- [x] crash
- [ ] feature request
- [ ] other (specify...)

#### Describe your issue
Meshlab would not start even with CPU OpenGL support. The file was successfully renamed. 
![2020-12-09 11_43_55-Window](https://user-images.githubusercontent.com/51311453/101619955-3a7d9e00-3a14-11eb-8fbc-fb15d3566faa.png)

The laptop I like to use has an older graphic card without actual DirectX or OpenGL support.
Using Windows 10 X64 20H2 and Meshlab 2020.12

**Comment by alemuntoni** [comment]
I really don't know how can I help you. In a simple virtual machine without any graphic card, using cpu accelerated opengl works. 
When glew does not initialize, it means that something basic is missing in your system.

**Comment by jesusarell** [comment]
Hello, first of all thanks for the work and congratulations. It is my first time trying to install the program and I am experiencing the same error. Is there any news about it?

**Comment by NilsRo** [comment]
Change your laptop/pc. In my case another worked fine with a more actual driver.
