### ISSUE TITLE
OBJ format for polylines not supported

### ISSUE THREAD

**Issue by cnovel** [cnr-isti-vclab/meshlab#87]
Hello,

The OBJ file format is not correctly read with Meshlab. It is possible to save lines in OBJ, see [here](https://people.cs.clemson.edu/~dhouse/courses/405/docs/brief-obj-file-format.html). However, Meshlab only display the points, not the line.
For example, this OBJ file:
```
v 0 0 0
v 1 0 0
v 1 1 0
v 0 1 0
v -1 1 0
v -1 0 0
v -1 -1 0
v 0 -1 0
v 1 -1 0
l 1 2 3 4 5 6 7 8 9
```
render like this in CloudCompare
![image](https://cloud.githubusercontent.com/assets/5690282/23218001/4eca3e88-f91b-11e6-9b18-5a31a8f95d01.png)
and like this in Meshlab
![image](https://cloud.githubusercontent.com/assets/5690282/23218110/a226b066-f91b-11e6-851c-f27addeda7e4.png)

**Comment by mcallieri** [comment]
There are some elments of the OBJ file format that are ignored, as we have no support for them.
MeshLab has an **extremely limited** support for polylines. Just a couple of filters DO create polylines, but the only thing you may do with them is to export them. This is why they are ignored... Even if you were able to load them, there would be no way of selecting, manipulating and use them in filters, and the only usable elements would be the vertices.
Sorry, but we do not have any plan to support polylines in the immediate future.
