### ISSUE TITLE
Unable to apply filters with PyMeshlab (Windows 10, Python 3.7)

### ISSUE THREAD

**Issue by VisionaryMind** [cnr-isti-vclab/meshlab#873]
Platform: Windows 10
Meshlab version: 2020.12

The following lines of code:

import pymeshlab as ml
ms = ml.MeshSet()  
ms.load_new_mesh('mesh.ply')
ms.apply_filter('matrix_set_from_translation_rotation_scale', translationx=tx,translationy=ty,translationz=tz,rotationx=yaw,rotationy=pitch,rotationz=roll)   

..produce this error with the apply_filter invocation:
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)

This was installed using pip3 install git+https://github.com/cnr-isti-vclab/PyMeshLab. No compile errors.

Do we have to go back to using Meshlabserver?

**Comment by VisionaryMind** [comment]
This is a non-issue, ultimately. The problem happens when any other value except Float is passed to the filter parameters. User error.

**Comment by alemuntoni** [comment]
Just for curiosity, what type of data were you passing as parameter?

**Comment by VisionaryMind** [comment]
My apologies, as I posted this issue in the wrong window (I had both Meshlab and PyMeshLab open simultaneously). The data being passed in was a Numpy series. I had presumed it has filtered down to a single Float value, but it was an array of Floats. Passing in a single Float caused the issue.
