### ISSUE TITLE
Unespected eof while exporting ply files

### ISSUE THREAD

**Issue by taposk** [cnr-isti-vclab/meshlab#874]
Hi! I got a problem with 2020.12d  precompiled dmg on osx Catalina. 
When I export a "ply" file with quality, normals and color as binary, the ply becomes "unreadable" and I got the "Unespected eof" error showing. However, when exported as ascii it works perfectly. 
#Please read carefully before submitting an issue

- be as detailed as possible while describing an issue:
  - which platform are you using (say it also on the subject of the issue)
  - which version of meshlab are you using (e.g. 2020.09 portable. 2020.06 snap, 2020.12 installer)
  - be sure that the issue is reproducible: list step by step all the operations performed to reproduce the issue
  - if it applies, share all the involved files
- if it is possible, verify if the problem persists in other platforms;
- be sure that your issue also happens on the most recent MeshLab version;
- check if your issue has been already reported by someone else. In this case, do not open another issue: just add your experience in the existing issue;
- delete these guidelines before submitting :)

If it is not an issue but something else (need help, feature request, ...) consider to use github discussion: https://github.com/cnr-isti-vclab/meshlab/discussions

**Comment by alemuntoni** [comment]
Thanks for reporting, this issue has been already solved, the fix will be available in the next version.
In the meantime, you can download one of the nightly builds available in the [actions tab](https://github.com/cnr-isti-vclab/meshlab/actions) (like [this](https://github.com/cnr-isti-vclab/meshlab/actions/runs/430358303)).
