### ISSUE TITLE
Convex Hull run from script saves input mesh to disk, not convex hull

### ISSUE THREAD

**Issue by danwbean** [cnr-isti-vclab/meshlab#88]
Meshlab_64bit_fp v2016.12  Windows 10 

When Convex Hull is run from a script, it reports success, but writes the original mesh, not the convex hull, to disk.

Speculation: This may be related to writing the first file in the layer list and the new convex hull will be the second.  I do not know how to set the _current_ file within a script.

**Comment by mcallieri** [comment]
Hi, you guessed correctly, you are just saving the wrong layer :)
MeshLabServer keeps layers in the same way MeshLab does, and saves layers following their order. So, as there are two layers (the original one and the convex hull), you have to export 2 meshes. If you add two exporting parameters -o layer1.ply -o layer2.ply the first one will contain the original mesh, and the second the convex hull. Unfortunately, it is not possible, at the moment, to save just the CURRENT LAYER.
Another option is to make a script like this:
1) do the convex hull
2) select layer 0
3) delete current layer
In this way, the only remaining layer will be the convex hull (layer 1), and it will be possible to save only that one.
The filter to change the current layer is filter->mesh layer->"change the current layer", that in script will be 
```
<filter name="Change the current layer">
  <Param tooltip="The name of the current mesh" type="RichMesh" value="0" name="mesh" description="Mesh"/>
 </filter>
```
layer numbers start at 0.
then, to delete the current mesh, use filter->mesh layer->"delete current mesh".
```
<filter name="Delete Current Mesh"/>
```
If you add those filters after the convex hull, and than save the only remaining layer, you should have what you need.
Let me know...

**Comment by danwbean** [comment]
Marco,

Perfect!  I knew there must be a way.  You clear explanation makes sense.
It is early morning here and will try it after some coffee.
Thank you for your quick reply and effort to make meshlab work so well.

Regards,

Dan Bean
Corvallis, Oregon, USA
