### ISSUE TITLE
Colorize by vertex quality filter bug (MeshLab 2020.12)

### ISSUE THREAD

**Issue by SenyangJiang** [cnr-isti-vclab/meshlab#881]
Hi,
It seems that when using "colorize by vertex quality" filter, higher values are mapped to blue and lower values are mapped to red, however the help note in the UI indicates the opposite. There might be a small bug that the color mapping is reversed.

**Comment by alemuntoni** [comment]
Thanks for reporting, I updated the documentation!

**Comment by gpbonneau** [comment]
When using the Hausdorff distance as vertex quality, this choice of colormap is counterintuitive: low errors appear in RED while high errors appear in BLUE. Would it be possible to have the ability to reverse the colormap? That would be great.
