### ISSUE TITLE
meshlabserver missing from macOS 2020.12 build

### ISSUE THREAD

**Issue by flipphillips** [cnr-isti-vclab/meshlab#882]
Description -
`meshlabserver` missing from 2020.12 build on macOS

To replicate - 
` ls /Applications/meshlab.app/Contents/MacOS`

Expected result -
`meshlab* meshlabserver*`

Actual result -
`meshlab*`

Regression - 
Installed previous release. `meshlabserver` is present

**Comment by alemuntoni** [comment]
Please read the last news in https://www.meshlab.net/#news
