### ISSUE TITLE
Crash on Transfer: Vertex Color to Texture

### ISSUE THREAD

**Issue by TwistedWebbe** [cnr-isti-vclab/meshlab#885]
Hello! I am experiencing a repeated crash when attempting to use the Filture Transfer: Vertex Color to Texture. Here are the steps to reproduce it. I have attached the model I am testing with.

1. I am using Windows 10 (64-bit) and MeshLab 2020.12. 
2. I am creating base .obj files on my VR headset using SculptrVR, then exporting the mesh (with vertex colors) as .obj files. 
3. From there I am able to successfully import them into MeshLab. 
4. Next I do the required step of Filters > Texture > Per Wedge Texture Function
5. The next step is to go to Filters > Texture > Transfer: Vertex Color to Texture
6. Before I am allowed to save I must remove the file path from the Texture File box. If the full file path is left in a different error is spit out "Path in Texture file not allowed". Only the filename is left.
7. If I hit the Apply button the program crashes.

This is what shows up in Windows' Event Viewer:

> Faulting application name: meshlab.exe, version: 0.0.0.0, time stamp: 0x5fcf6b6d
> Faulting module name: Qt5Gui.dll, version: 5.15.2.0, time stamp: 0x5fa4ddbb
> Exception code: 0xc0000005
> Fault offset: 0x000000000008d1a9
> Faulting process id: 0x1f9c
> Faulting application start time: 0x01d6e09a9e414095
> Faulting application path: C:\Program Files\VCG\MeshLab\meshlab.exe
> Faulting module path: C:\Program Files\VCG\MeshLab\Qt5Gui.dll
> Report Id: de8e3c75-98b4-4fd2-b49a-4a9ce3d885d0
> Faulting package full name: 
> Faulting package-relative application ID: 

Now with all of that said, I have tried some other things to make the function work, and I was successful a single time, though I'm not sure what I did. I have tried simplifying the mesh and applying other filters first, but nothing seems to do the trick. Obviously the expected behavior is that it should just work as advertised, so maybe you will be able to shed some light on how to fix this.
[2020.12.31-10.20.06.obj.zip](https://github.com/cnr-isti-vclab/meshlab/files/5759600/2020.12.31-10.20.06.obj.zip)

**Comment by alemuntoni** [comment]
Thanks for reporting!! I confirm the crash that happens on all the plaforms!
I'll investigate on this!

**Comment by rensvdveldt** [comment]
Hello! Is there any update on this? Or are there alternative filters/software versions available for achieving the same results available?

**Comment by alemuntoni** [comment]
Fixed. It will be available in the next meshlab version, or you can try the nightly version from [github actions](https://github.com/cnr-isti-vclab/meshlab/actions).
