### ISSUE TITLE
Meshlab Shape Diameter Function (SDF) filter not working

### ISSUE THREAD

**Issue by Marriaga** [cnr-isti-vclab/meshlab#89]
When I run the Shape Diameter Function (SDF) filter in Meshlab I get white (255 255 255) everywhere.

I am on an old Desktop Computer (Intel Xeon E5606; 80GB RAM; Win 7; ATI FirePro V4800 FireGL V). When I launch Meshlab on the lower right corner of the window there is a green bar moving, which seems to be the place where the total amount of dedicated graphics memory is being used. In a tutorial video this was the diagnosis of the program using the integrated instead of the dedicated graphics in a laptop. Could this be the issue with the filter not working?

**Comment by mcallieri** [comment]
the Shape Diameter Function filter does NOT automatically color the layer, but stores the result in the per-vertex QUALITY value. This value can then be mapped onto color using the Quality Mapper Edit Filter (the one with the Bunny icon) or with one of the color filters like "per vertex color function" or "colorize by quality"

The never-ending scrolling bar may be the integrated videocard OR an accelerated ATI card. 
This filter does use GPU, if there are problems, you should read some error message in the log area.

**Comment by Marriaga** [comment]
The quality vs color was the issue. Thank you for the information.
