### ISSUE TITLE
Randomly disappearing images and explosion of images (MacOS)

### ISSUE THREAD

**Issue by bovidlover** [cnr-isti-vclab/meshlab#890]
I am working in 2020.12. I've been using it almost every day and it just started doing this issue. I'll try to scale and normalize and it will make the image disappear (doesn't matter what file type it does it on all of them). If I find it in the viewfinder and try to zoom in or center it will explode into tiny fragments. I had a college have the same issue. I thought it was just that function was not working so I've tried to flip the axis so I can collect my points and it does the same thing. Now I can no longer use the program to finish my projects till this is fixed. I have tried uninstalling and reinstalling the program and it still has the same issues. Any suggestions as to how to fix it?

**Comment by alemuntoni** [comment]
Hi, it's hard to understand what's going on here.
Could you please at least share some screenshots and list step by step the actions you did to reach that point?
