### ISSUE TITLE
Camera filter "image alignment" and "global refinement..."  Crashes !

### ISSUE THREAD

**Issue by robertorocca** [cnr-isti-vclab/meshlab#891]
Hi,
I am running Meshlab 2020.12 on Windows 7 and Windows 10. I found that meshlab crashes when i try to use the camera filter "image alignment-mutual information" and "image registration global refinement using mutual information". It happens in both the O.S.  I tried to use some earlier version of Meshlab and i found that the filters works fine on 2016.12 version.

**Comment by alemuntoni** [comment]
Hi, sorry for the late reply.
Could you please share an example mesh and image and all the steps needed to reproduce the issue? thanks!

**Comment by robertorocca** [comment]
Hi,
in the attached file you will find a mesh, two images and a meshlab project. The workflow is simple, i import the mesh and the raster images, do a rough alignment by trackball using "show current raster mode", and after that i set the camera for current raster. After i go to "filters/camera/image alignment: mutual information", push "get shot current trackball" and "estimate focal length" and when i apply the filter meshlab crashes.
Same thing if i have more aligned images and apply the filter "global refinement using mutual registration"
I hope this can help, best regards.

P.S. Any hope to see non rigid alignment filter inside Meshlab? Currently only "Artec Studio" have that function, but it's too much expensive for me....

[bunny.zip](https://github.com/cnr-isti-vclab/meshlab/files/6265247/bunny.zip)

**Comment by alemuntoni** [comment]
Thanks @robertorocca! 
I can confirm the crash, but just on windows... I am investigating!

About non rigid alignment filter, right now we don't have such plan, but if there is a working open source implementation of some state-of-the-art algorithm we could evaluate on adding it into meshlab! 
Moreover, starting from the next meshlab version, plugins can be loaded at run time and therefore it will be easier to use implementations provided by third parties into meshlab!

**Comment by alemuntoni** [comment]
Solved in the last commit! Will be available in the next version (a release candidate will be released in the next few days!)
