### ISSUE TITLE
MeshLab 2012.12 / Failing to Open Previously Saved STL File. Error detail: Malformed file.

### ISSUE THREAD

**Issue by LuckyResistor** [cnr-isti-vclab/meshlab#899]
After processing an STL file with MeshLab and save it as STL, MeshLab is unable to open the saved STL file with the error message "Malformed file".

# Steps to Reproduce the Error

- Load [original.stl.zip](https://github.com/cnr-isti-vclab/meshlab/files/5824668/original.stl.zip)
- Appy `merge_close_vertices` filter with defaults.
- Apply `remove_duplicate_vertices` filter with defaults.
- Apply `remove_duplicate_faces` filter with defaults.
- Apply `remove_zero_area_faces` filter with defaults.
- Apply `re_orient_all_faces_coherentely` filter with defaults.
- Export the file as STL with default settings.

# Expected Result
- The resulting mesh in the STL is not watertight but can be loaded in MeshLab and processed.

# Actual Result
- If you try to load the exported STL file, the error: Malformed file is raised.

This is the exported file:
[after_processing.stl.zip](https://github.com/cnr-isti-vclab/meshlab/files/5824669/after_processing.stl.zip)

It does not matter if I do the processing using the user interface or using PyMeshLab. The result is the same.

I processed +500 files with the same sequence of load, filter, and export with no problems. But this error happened on ~1% of the files. 

- MeshLab Version: 2020.12 installer
- Operating System: Windows 10

**Comment by alemuntoni** [comment]
Thanks for the detailed reporting! :)
Are you using meshlab 2020.12 or 2020.12d?

I tried it on meshlab 2020.12 on linux and works as expected, I'll try on other versions and OS asap!

**Comment by LuckyResistor** [comment]
I was using MeshLab 64bit v2020.12, built 8. Dec MSVC 1928, Qt 5.15.2 on a Windows 10 machine.

**Comment by alemuntoni** [comment]
This issue has been already solved in one of the previus fixes (may be #732 or #734), but now it works!
The fix will be available in the next meshlab version!
