### ISSUE TITLE
Laplacian smooth (surface preserve) not working from script

### ISSUE THREAD

**Issue by Marriaga** [cnr-isti-vclab/meshlab#90]
When I apply manually it works but if I apply it by loading a script and then selecting apply script it doesn't apply the filter.

Script:
```
<!DOCTYPE FilterScript>
<FilterScript>
 <filter name="Laplacian smooth (surface preserve)">
  <Param type="RichBool" name="selection" tooltip="Apply laplacian smooth on selected faces only" description="Update selection" value="false"/>
  <Param type="RichFloat" name="AngleDeg" tooltip="maximum mean normal angle displacement (degrees) from old to new faces" description="Max Normal Dev (deg)" value="4"/>
  <Param type="RichInt" name="iterations" tooltip="number of laplacian smooth iterations in every run" description="Iterations" value="10"/>
 </filter>
 </FilterScript>
```

PS: Would it be possible for filters to only require name and value? Having to include the other fields like the tooltip makes the script file hard to read.

**Comment by mcallieri** [comment]
We currently have an issue with scripting, some filters ar not working properly. We are investigating.

**Comment by granzuglia** [comment]
Fixed. Please when you will have the new MeshLabServer Version regenerate with the correspondent MeshLab version the Laplacian Smooth Script.

**Comment by nicolasugrinovic** [comment]
Same problem here with version 1.3.2_64bit. Which version solves the problem?

Script:
`<!DOCTYPE FilterScript>
<FilterScript>
 <filter name="Laplacian smooth (surface preserve)">
  <Param type="RichBool" value="false" name="selection"/>
  <Param type="RichFloat" value="10" name="AngleDeg"/>
  <Param type="RichInt" value="1" name="iterations"/>
 </filter>
</FilterScript>`
