### ISSUE TITLE
[MacOS] Meshlab starts but plugins are not loaded.

### ISSUE THREAD

**Issue by chongli-uw** [cnr-isti-vclab/meshlab#900]
Hi, 
  I got the following error message when opening any obj file. 

"Error details: file format obj not supported.  "

  Interestingly, if I open meshlab in the dmg image (without copying meshlab to Application directory), it works just fine. 

Platform: MacOS 10.15.7
Meshlab version: Meshlab2020.02 (tried all versions from 2020.02 to the latest, all the same error)

Thanks!

**Comment by alemuntoni** [comment]
I think that this is related to the fact that some filesystems in MacOS are case sensitive, but the default one is not.
Could you please check if your filesystem is case sensitive?

I think this is an issue that needs to be investigated and solved, but unfortunately I don't have a mac to wipe and format with a case-sensitive file system ;(

**Comment by chongli-uw** [comment]
Hi @alemuntoni , exactly! The file system on the MacOS is APFS case sensitive.

**Comment by alemuntoni** [comment]
Thanks! I'll try to check this and solve the issue as soon as possible!

**Comment by chongli-uw** [comment]
Thanks!

**Comment by alemuntoni** [comment]
Solved! Next meshlab version hopefully will work!

Unfortunately right now automatic builds are failing due to Qt servers down.
When they will be up again I'll trigger a new build and a nightly version will be available

**Comment by alemuntoni** [comment]
Nevermind, automatic builds are working on mac now!
You can download the nightly build from [here](https://github.com/cnr-isti-vclab/meshlab/actions/runs/503310180).
Let me know if it works!

**Comment by chongli-uw** [comment]
@alemuntoni Yes it works for me on MacOS 10.15.7 APFS case sensitive. Thanks so much for your help!
