### ISSUE TITLE
meshlab 2020.12: program crashes image alignment

### ISSUE THREAD

**Issue by FrederikDeKreyger** [cnr-isti-vclab/meshlab#903]
Hello,

i'm triying to add texture on a .ply file with several pictures. When i align the model with the picture and go to camera: image alignment and press apply, the program crashes. I didn't change the settings of the image alignment.  Does anyone know what the problem is?

**Comment by alemuntoni** [comment]
I'll check this as soon as possible, but the last time I used the filter it was working, and there were no big changes on the specific filter since then..
Could you please share the mesh and the images that you are trying to align?

**Comment by alemuntoni** [comment]
Sorry for the late reply. I cannot replicate the issue. 
Could you please share the mesh and the images that you are trying to align? What OS are you using?

**Comment by alemuntoni** [comment]
Solved in the last commit.

**Comment by FrederikDeKreyger** [comment]
Hello,

My problem is already solved but i have an other problem: i made a .obj but i can't export a texture map xith it. What can i do?

this is the link to the model:
<https://www.dropbox.com/s/bwo3dtg3veqfxv3/vierlander.obj?dl=0>


kindly regards,
Frederik De Kreyger

erkend archeoloog type 1|3D-scanning en visualisatie
(+32) ***@***.*** ***@***.***>

<http://www.dl-h.be> <https://www.dl-h.be/erfgo3d/home>


De Logi & Hoorne bv
<http://www.dl-h.be/>
Canadezenlaan 1A | 9991 Adegem
BTW BE 0845.028.465 | RPR Gent



Op 6 april 2021 14:50:33 +02:00, schreef Alessandro Muntoni ***@***.***>:

**Comment by alemuntoni** [comment]
The model you shared does not have textures.

Please open a new issue explaining what is the issue and giving as much details as you can in order to help us reproduce and then solve the issue.
