### ISSUE TITLE
Meshlab 2020.12d not exporting data correctly PLY -> DAE

### ISSUE THREAD

**Issue by crazycto** [cnr-isti-vclab/meshlab#907]
While using version `2020.12d`, exporting meshes in Collada does not work.

I've attached the original and export files for reference.

Using `v2020.12` and `v2020.09` works fine. Also file sizes produced by `v2020.12` and `v2020.12d` varies. I believe it is due to the new double precision feature.

Hope this helps. 😉

Let me know if you need any more details.

[Files for GitHub.zip](https://github.com/cnr-isti-vclab/meshlab/files/5881556/Files.for.GitHub.zip)

**Comment by alemuntoni** [comment]
Fixed with the last commit. Will be available in the next meshlab version!

**Comment by crazycto** [comment]
Awesome! 🎉
