### ISSUE TITLE
“Makehuman” export obj, can not read

### ISSUE THREAD

**Issue by bowknot** [cnr-isti-vclab/meshlab#91]
MeshLab1.3.4 can read......Why？

**Comment by cignoni** [comment]
Can you provide a bit more info? Please? 
Can you provide an example of the file that is not opened by MeshLab 2016.12?

**Comment by bowknot** [comment]
video and obj:
[video.zip](https://github.com/cnr-isti-vclab/meshlab/files/801972/video.zip)

**Comment by mcallieri** [comment]
It is something in the material (123.mtl)... It does not like the texture(s).
If you remove the material file, or just remove the texture from the material files, the geometry is loaded correctly.
 I'll do some test, and let you now.

**Comment by alemuntoni** [comment]
This issue has been solved in MeshLab 2020.04. If you still experience similar issues, feel free to open a new issue!
