### ISSUE TITLE
meshlab from git and package release defacing the UI in non HiDPI 4K display

### ISSUE THREAD

**Issue by doniom** [cnr-isti-vclab/meshlab#910]
see 
[https://github.com/cnr-isti-vclab/meshlab/issues/485](https://github.com/cnr-isti-vclab/meshlab/issues/485)

**Comment by alemuntoni** [comment]
I can't help you, the Arch package of MeshLab is not maintained by us, but from the Arch community (I think).
The [AppImage](https://github.com/cnr-isti-vclab/meshlab/releases/download/Meshlab-2020.12/MeshLab2020.12-linux.AppImage) works fine on my 4k hidpi xps15. Please check it or report the issue to who is packaging meshlab for arch.

**Comment by doniom** [comment]
I have now downloaded the AppImage and execute them... no effect... still the same...

I work under I3wm, is this a problem?

**Comment by alemuntoni** [comment]
I really don't know, I never heard of I3wm.. I don't know if it has issues with opengl and/or Qt for hidpi monitors..

**Comment by doniom** [comment]
ok :-(
