### ISSUE TITLE
How to use meshlabserver via the snap system?

### ISSUE THREAD

**Issue by Algomorph** [cnr-isti-vclab/meshlab#911]
Hi! 

Great tool, thank you for maintaining it!

On Ubuntu 20.04, I used to be able to make an alias for meshlabserver, i.e. `snap alias meshlab.meshlabserver meshlabserver` to simply invoke `meshlabserver` from the terminal, using the meshlab 2020.07 snap.

I am unable to do this in the 2020.12 snap, so I had to fall back to the 2020.03 apt image, but I want to keep things current in my scripts (I think filter syntax changed). 

1. How can I call meshlabserver at all with the 2020.12 snap?
2. Is it as easy to do a snap alias to that, like before?

**Comment by alemuntoni** [comment]
meshlabserver has been dismissed in favour of pymeshlab:

https://www.meshlab.net/
https://github.com/cnr-isti-vclab/meshlab/discussions/843
https://pymeshlab.readthedocs.io/en/latest/index.html#

**Comment by Algomorph** [comment]
Ah, I see! Thank you!
