### ISSUE TITLE
Error display raster images when importing raster image by bundler.rd.out and list.txt file on MacOS Sierra e MeshLab 2016

### ISSUE THREAD

**Issue by Marcuzzo77** [cnr-isti-vclab/meshlab#92]
When you import the files and then bundler.rd.out and list.txt and clicking on "show current raster mode" button is not been displayed the corresponding raster image but returns an error that does not appear in windows:
"There are gl errors: invalid value"...
an image is returned to the board

**Comment by mcallieri** [comment]
Are you sure you are reading the correct image list? It shoud be a ascii list of image file names. 

The "there are GL errors" is a problema unrelated to this, it is due to an error in the QT widget we use for rendering #45
