### ISSUE TITLE
Network folder not accesible under meshlab file explorer

### ISSUE THREAD

**Issue by ortegadlx** [cnr-isti-vclab/meshlab#920]
Hello team, we have installed meshlab on our Centos 7 workstation using snap method

Meshlab 2020.12 is working great but we are facing an issue, network folders are not available under meshlab´s file explorer

The network storage are mounten on /media, but if we go to that folder trough meshlab´s explorer, there are no folders to navigate

Is there any limitation with using meshlab and network storage? thank you

best regards

**Comment by alemuntoni** [comment]
See #466. Everything that is mounted is seen as an external drive on linux (also network storage).
Closing because duplicate.
