### ISSUE TITLE
Points visualization sizes does not reduce if they are far from point cloud center

### ISSUE THREAD

**Issue by jcr4p** [cnr-isti-vclab/meshlab#921]
The issue is reproducible with .ply files with vertices distant from each other.
When open a ply file, the points near the point cloud center correctly resize their dimension, while the points far from the center does not.
The problem is reproducible using either alt+wheel or "Point Size" slide bar.

Using version: 2020.12 (but the same issue is present also in older version, but NOT in v1.3.2 (Nov 21 2016) available in debian repo)
OS: debian stretch with KDE

[edge_1.zip](https://github.com/cnr-isti-vclab/meshlab/files/6021684/edge_1.zip)

**Comment by alemuntoni** [comment]
I cannot reproduce this issue: on ubuntu 20.04 with gnome all the points correctly resize..
