### ISSUE TITLE
(Still) Crash(ing) when opening large STL file (>2GB)

### ISSUE THREAD

**Issue by RodolfoGMA** [cnr-isti-vclab/meshlab#924]
Good afternoon.
Although it is considered a closed problem (https://github.com/cnr-isti-vclab/meshlab/issues/823), when I try to open any of my > 2GB STL files, meshlab crashes immediately. I am using the newest version, v2020.12, on Windows 10. All < 2GB files open perfectly.

Please, find an 2.6GB file as an example: https://www.dropbox.com/s/2pya836wbe7wt6k/Matrix.stl?dl=0

Kind regards,
Rodolfo

**Comment by alemuntoni** [comment]
Thanks for reporting!
Solved with the last  commit. Will be available in the next meshlab version.

**Comment by RodolfoGMA** [comment]
Many thanks for the fast response.
It will be very helpful.

**Comment by snotrman** [comment]
Still very slow on windows 10. Just downloaded the package from your homepage. UI menu bar hover color change happens some 4 seconds after the mouse actually has hovered over a menu item. So that slow to be descriptive.
And that is with nothing open. Just by opening the program and lettin it idile.

**Comment by alemuntoni** [comment]
@snotrman does this happens only when opening big mesh files?

**Comment by snotrman** [comment]
> 
> 
> @snotrman does this happens only when opening big mesh files?

No. It happens even if I just open Meshlab.

**Comment by alemuntoni** [comment]
> > @alemuntoni  does this happens only when opening big mesh files?
> 
> No. It happens even if I just open Meshlab and nothing else.

In that case, we are definitely out of topic here.

Could it be some antivirus issue? 
We still don't have windows sign certificates, therefore it could be that meshlab is slowed down by the antivirus.. 
If it is not the antivirus, please open a new issue describing what's happening.
