### ISSUE TITLE
(Win 10) Hangs when splitting certain meshes into connected components

### ISSUE THREAD

**Issue by JC3** [cnr-isti-vclab/meshlab#928]
Platform: Windows 10
Version: 2020.12 Installer

On certain meshes (I can not identify the trigger), MeshLab hangs indefinitely when attempting to split them into connected components. An example of one is attached.

To reproduce:

1. Start MeshLab
2. Open threadtest.stl, choose "no" to unify vertices
3. Right click on mesh layer and select "Split into connected components"

Expected: Operation completes in reasonable amount of time.

Actual: MeshLab hangs and must be force quit.

[threadtest.zip](https://github.com/cnr-isti-vclab/meshlab/files/6119305/threadtest.zip)

**Comment by JC3** [comment]
Actually it seems to work fine when unifying duplicate vertices. Not sure why I struggled with this. So, nevermind. Although it probably still shouldn't hang, it's not exactly a showstopper.

**Comment by cignoni** [comment]
If you do not unify vertices in a STL mesh, every single face is topologically a different component. So in your case it would mean that you would have 147028 different entries in the layer window, something for which the GUI is not prepared for :)

**Comment by JC3** [comment]
> If you do not unify vertices in a STL mesh, every single face is topologically a different component. So in your case it would mean that you would have 147028 different entries in the layer window, something for which the GUI is not prepared for :)

Thanks!!! Yeah, I've since learned that STL files don't store connectivity info, so now the dialog makes a lot more sense to me.
