### ISSUE TITLE
meshlabserver fails to apply any filter

### ISSUE THREAD

**Issue by Hugal31** [cnr-isti-vclab/meshlab#931]
On commit 748b597041c43e55ffe3e3a7a7c0c08845ed6f0c, meshlabserver never successfully apply a filter. By looking at the code, it seems that [ret](https://github.com/cnr-isti-vclab/meshlab/blob/748b597041c43e55ffe3e3a7a7c0c08845ed6f0c/src/meshlabserver/mainserver.cpp#L714) is never set to true. This is probably the case since commit 86620516bad10a66b7e372d911e47a109d139a15.

**Comment by alemuntoni** [comment]
Thanks for reporting, my bad.
Fixed in the last commit.
