### ISSUE TITLE
Isotropic Explicit Remeshing

### ISSUE THREAD

**Issue by HollowHeartNet** [cnr-isti-vclab/meshlab#934]
Hi , 
I would like to use the remeshing function "Isotropic Explicit Remeshing" in an automatic manner. Is there a way to automate the remeshing step in meshlab without using the GUI? Or is there a similar code available that is able to do the job (for Python if possible)?

FYI: I've read that the meshlabserver can be used for scripting and automation. But I cannot find it anywhere on my computer. I am using meshlab 2020.07 on windows 10. 

Thank you.

**Comment by cignoni** [comment]
Yes, just use pymeshlab 
https://pymeshlab.readthedocs.io/en/latest/index.html
