### ISSUE TITLE
Compiling for Windows

### ISSUE THREAD

**Issue by flaviu22** [cnr-isti-vclab/meshlab#939]
Have to changed something on this project regarding compiling for Windows ?

I have tried to compile this project for Windows, 64 bit, using VS2017 64bit.

Here is the steps:

![image](https://user-images.githubusercontent.com/37621568/113029565-3cbb6200-9195-11eb-8640-ef60b4f02657.png)

and then

![image](https://user-images.githubusercontent.com/37621568/113029608-480e8d80-9195-11eb-9077-9f9adae610ca.png)

```
CMake Error at CMakeLists.txt:29 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.

```
I have loaded CMakeLists.txt in Qt:

![image](https://user-images.githubusercontent.com/37621568/113029775-82782a80-9195-11eb-8cc3-4bc268e50ae7.png)

![image](https://user-images.githubusercontent.com/37621568/113029801-8b68fc00-9195-11eb-8709-f8781c4867a2.png)

![image](https://user-images.githubusercontent.com/37621568/113029832-94f26400-9195-11eb-951d-65719af62df8.png)

```
Running C:\Program Files\CMake\bin\cmake.exe -S C:/Project/meshlab/src -B C:/Users/u724776/AppData/Local/Temp/QtCreator-jooBhL/qtc-cmake-KyJTqgeE -GNinja "-DCMAKE_BUILD_TYPE:String=Debug" "-DQT_QMAKE_EXECUTABLE:STRING=C:/Qt/Qt5.12.10/5.12.10/msvc2017_64/bin/qmake.exe" "-DCMAKE_PREFIX_PATH:STRING=C:/Qt/Qt5.12.10/5.12.10/msvc2017_64" "-DCMAKE_C_COMPILER:STRING=C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/amd64/cl.exe" "-DCMAKE_CXX_COMPILER:STRING=C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/x86_amd64/cl.exe" in C:\Users\u724776\AppData\Local\Temp\QtCreator-jooBhL\qtc-cmake-KyJTqgeE.
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "C:/Users/u724776/AppData/Local/Temp/QtCreator-jooBhL/qtc-cmake-KyJTqgeE/CMakeFiles/CMakeOutput.log".
CMake process exited with exit code 1.
Elapsed time: 00:04.

```
I have done something wrong here ?

**Comment by flaviu22** [comment]
"`CMAKE_MAKE_PROGRAM is not set`" where and why should I setup a tool if I already did that on Qt CMakeLists.txt ?

**Comment by flaviu22** [comment]
What is the point with Ninja ? I even heard of this program ... I am using Windows only. Why is asking for Ninja ?

**Comment by alemuntoni** [comment]
https://en.wikipedia.org/wiki/Ninja_(build_system)

The issues you are describing are depends on your system configuration, not on meshlab.
