### ISSUE TITLE
Problem with flatten visible layers MeshLab v2016.12

### ISSUE THREAD

**Issue by LeonsId** [cnr-isti-vclab/meshlab#94]
after processing flatten visible layers, the new merged layer and all layers from which was merged, have no vertices.

**Comment by mcallieri** [comment]
There is an option to merge layers and keep unreferenced vertices (vertices not attached to a face).
This filters was developed for a specific purpose, and at that time removing unreferenced vertices made perfect sense, but then we started working with pointclouds :), so we added the parameter.
