### ISSUE TITLE
[Question] Wrong function call in FP_RECOMPUTE_VERTEX_NORMAL?

### ISSUE THREAD

**Issue by pjessesco** [cnr-isti-vclab/meshlab#948]
https://github.com/cnr-isti-vclab/meshlab/blob/f2c399ac8bff483ab661227c38dd09c82cff4d77/src/meshlabplugins/filter_unsharp/filter_unsharp.cpp#L577-L583

Hi, 

I was looking at the code upper link, it seems their behaviors are same except `NormalizePerFace()`. I'm wondering whether it is intended or an actual issue.

**Comment by alemuntoni** [comment]
Thanks for reporting, @pjessesco! I am pretty sure that this is not intended and it is a bug. I am fixing it
