### ISSUE TITLE
Meshlabserver: Can't export .ply file in ASCII using "-m sa" option

### ISSUE THREAD

**Issue by Toast-arch** [cnr-isti-vclab/meshlab#949]
Hello I am using Meshlab 1.3.2 (64bit) on Linux Ubuntu 18 and I've been trying to make a script for quickly cleaning up my meshes. I want to take a mesh in .ply format as input, run a script on it, and then export as .ply in ASCII. I use the command below to execute an mlx script using meshlabserver:
`meshlabserver -i sfm.ply -o sfm_cleaned.ply -m sa -s mesh_clean_v1.mlx`

I installed meshlab using `apt-get install meshlab` and have not had any issues exporting, running scripts, and exporting with the GUI version.

When I execute the command stated above the program prints back input & output and then stops without exiting indefinitely. Here is a printout of my terminal:

me@mycomputer:~/workdir/scripts$ meshlabserver -i sfm.ply -o sfm_cleaned.ply -m sa -s mesh_clean_v1.mlx
Input mesh  /home/me/workdir/scripts/sfm.ply
output mesh  /home/me/workdir/scripts/sfm_cleaned.ply

The command and script work perfectly without the "-m sa" option.
Any suggestions of why this is happenning?

**Comment by alemuntoni** [comment]
Meshlab 1.3.2 is a version of almost 10 years ago, and meshlabserver has been dismissed and it is not supported anymore.

Please take a look to [newer versions](https://github.com/cnr-isti-vclab/meshlab/releases) of meshlab  and to [pymeshlab](https://pymeshlab.readthedocs.io/en/latest/).
