### ISSUE TITLE
sampling using quality attribute

### ISSUE THREAD

**Issue by maxcorsini** [cnr-isti-vclab/meshlab#95]
To reproduce the problem: 

Import a mesh 
Under Filter -> Sampling select "Montecarlo Sampling"
Check "Quality Weighted Sampling" 
and run the filter. A mesh with 0 vertices and 0 faces is produced because the quality attribute is not set. 

We can fix this for the specific context, but I think that, in general, if a filter produces a mesh with 0 vertices and 0 faces a good practice should be to not generate the new layer and advise the user.

**Comment by mcallieri** [comment]
corrected, and did the same kind of checks for all sampling filters.
However, problems of parameter coherence has to be solved case-by-case. filter-by-filter, please create new issues when other similar situation arise.
