### ISSUE TITLE
VRML import does not apply some materials to shapes [Windows]

### ISSUE THREAD

**Issue by settinger** [cnr-isti-vclab/meshlab#958]
* Meshlab version: Meshlab_64bit_fp v2020.12
* Platform: Windows 10 64bit

## Overview
VRML permits DEF and USE statements to create named nodes and apply them multiple times throughout a file. Meshlab handles most of these, but appears to ignore Material nodes that are applied via the DEF/USE semantics. This is particularly troublesome for users of KiCad, which exports VRML files that frequently use DEF/USE Material nodes.

I have only tested this on my personal Windows Machine, but I suspect it affects all platforms due to the probable cause discussed below.

## How to replicate

[I've attached a minimal working example, `mwe.wrl`.](https://github.com/cnr-isti-vclab/meshlab/files/6340015/mwe.zip) There are three spheres that should have red textures. The first sphere uses DEF to create a named Appearance node and a named Material node. The second sphere applies the Material node via USE. The third sphere applies the Appearance node via USE. In meshlab, the first and third spheres appear red (as they should), but the second sphere appears stark white (implying there is NULL material on the mesh).

![Current Meshlab view of MWE.wrl. Two red spheres and a white sphere. All three spheres should be red.](https://user-images.githubusercontent.com/7494643/115324462-c62fd580-a13e-11eb-9e5b-c6203532b89c.png)

Viewing `mwe.wrl` in another program, such as FreeCAD v0.19, shows all three spheres colored red as desired.

![Viewing the same file, MWE.wrl, in FreeCad instead of Meshlab. All three spheres are red.](https://user-images.githubusercontent.com/7494643/115324513-df388680-a13e-11eb-9759-704dcb3c2b48.png)

## Probable cause and probable solution
I am almost certain that the issue is in the file `src/meshlabplugins/io_x3d/import_x3d.h`. In the `loadAppearance()` function, on line 2005 the Material node is partially parsed, but it does not check for USE statements. I mimicked the sections above and added a `solveDefUse()` call after that line, then built the code with Github Actions. This appears to have eliminated the bug in both my minimal working example, and in a more complex VRML file exported by KiCad.

![MWE.wrl as viewed in my build of Meshlab. It looks correct.](https://user-images.githubusercontent.com/7494643/115324614-055e2680-a13f-11eb-98b4-daa839378384.png)
![A VRML file generated by KiCad. On the left, the render in my build of Meshlab, on the right is the render in the current build of Meshlab](https://user-images.githubusercontent.com/7494643/115324663-1a3aba00-a13f-11eb-8771-2d715d791c6b.png)(Left side: my build of Meshlab. Right side: current release of Meshlab)

I will file a pull request soon. That said, I do not have the means to fully test this change. I appreciate anyone's input on the issue! :)

**Comment by alemuntoni** [comment]
Thank you very much for the PR!! It is very very appreciated :)
We are aware of several issues in the x3d/vrml importer (see #887), but I didn't have time to study these formats and solve them.
I tested your solution on the other platforms and it works fine! Thanks again!! :)
