### ISSUE TITLE
How to calculate the color of vertex while screened poisson reconstruction?

### ISSUE THREAD

**Issue by Gyudori** [cnr-isti-vclab/meshlab#964]
Hi. I'm currently reconstructing mesh from RGB colored point cloud.
I'm curious about how the color of vertex is calculated while processing the reconstruction function. 

Can I get the document of the calculation or the exact location of the calculation in source code... 

Thank you...

**Comment by alemuntoni** [comment]
The entire implementation of the screened poisson filter is in [this directory](https://github.com/cnr-isti-vclab/meshlab/tree/master/src/meshlabplugins/filter_screened_poisson).
You can check the `applyFilter` function in `filter_screened_poisson.cpp` ([this line](https://github.com/cnr-isti-vclab/meshlab/blob/74c644ffda39b9c56444bdf4a8eee3fe9861463b/src/meshlabplugins/filter_screened_poisson/filter_screened_poisson.cpp#L99)).
You can also refer on the paper of the filter, of course.
