### ISSUE TITLE
Crash on  "transfer  vertex-attributes to texture " with big data

### ISSUE THREAD

**Issue by jambus1986** [cnr-isti-vclab/meshlab#966]
Hello, i use meshlab 2020.07 on windows64, 24GB RAM

i try to transfer  vertex-attributes to texture with large meshes and pointclouds.
to transfer Pointcolor of a cloud to my texture.
and i have 2 problems:

1)  on meshlabserver  commandline there are thousands of 
warnings  Qimage:   setpixel... (-1,23414....).. out of Range  and so on
thats very bad for speed

2) meshlab crashes completely  with big data
following two steps i do:
- first Parametization Trivial Per Triangle...
         0 quads per line
         10000 px size
         2  px intertriangleBorder
         space optimizing
- second    transfer  vertex-attributes to texture:
        source:  cloud
       dest: mesh
       max dist:     0.05
       texture size x= 10000
       texturesize y = 10000
assign texture yes
fill texture   yes

i can reproduce it with large files i use.. 
so i have uploaded an example in wetransfer:

Hello, i use meshlab 2020.07 on windows64, 24GB RAM

i try to transfer  vertex-attributes to texture with large meshes and pointclouds.
to transfer Pointcolor of a cloud to my texture.
and i have 2 problems:

1)  on meshlabserver  commandline there are thousands of 
warnings  Qimage:   setpixel... (-1,23414....).. out of Range  and so on
thats very bad for speed

2) meshlab crashes completely  with big data
following two steps i do:
- first Parametization Trivial Per Triangle...
         0 quads per line
         10000 px size
         2  px intertriangleBorder
         space optimizing
- second    transfer  vertex-attributes to texture:
        source:  cloud
       dest: mesh
       max dist:     0.05
       texture size x= 10000
       texturesize y = 10000
assign texture yes
fill texture   yes

i can reproduce it with large files i use.. 
so i have uploaded an example in wetransfer:

https://we.tl/t-uqzbVtvmSk

**Comment by alemuntoni** [comment]
- meshlabserver has been dismissed
- you didn't share the material file associated to the mesh
- could you please try with [this version](https://github.com/cnr-isti-vclab/meshlab/actions/runs/778012557)?

**Comment by jambus1986** [comment]
in that moment there is still no material.
it works with small pointclouds. But if Data is too large,
Meshlab simply closes itsself completely during   transfer vertex-attributes to texture-process.

i tried it with the nightly version, its the same here.

**Comment by jambus1986** [comment]
Here is another example, much smaller, Meshlab closes when applying script..
[2021.zip](https://github.com/cnr-isti-vclab/meshlab/files/6404842/2021.zip)

**Comment by alemuntoni** [comment]
Fixed in the last commit. You can try the nightly by downloading it from the github actions tab when the build will finish.
The fix will be available in the next version of meshlab.

**Comment by runa91** [comment]
did anyone test this? for me meshlab is still crashing.
