### ISSUE TITLE
Meshlab crashes on:   Repair NonManifold Edges by splitting vertices

### ISSUE THREAD

**Issue by jambus1986** [cnr-isti-vclab/meshlab#978]
hi, do not be angry with me, i only want help to make meshlab more stable.   :-)
its a very good application.,,

meshlab crashes when using  Repair NonManifold Edges by splitting vertices filter.

way to reproduce:

- open attached example
-  first apply filter "Repair Non Manifold Vertices by splitting" using Vertex displacement ratio "0"
- second  use  Repair NonManifold Edges by splitting vertices filter. --
--->then crash

[err.zip](https://github.com/cnr-isti-vclab/meshlab/files/6417039/err.zip)

**Comment by alemuntoni** [comment]
Don't worry, these kind of reproducible crashes help a lot on making meshlab more stable :)
I'll look into this!
