### ISSUE TITLE
Installing Meshlab 2016.12 using Linux Snap on Ubuntu 14.04

### ISSUE THREAD

**Issue by omhafez** [cnr-isti-vclab/meshlab#98]
I successfully installed the Linux snap of Meshlab 2016.12 on 64-bit Ubuntu 14.04 but cannot get meshlabserver to work.

in /snap/bin only meshlab shows up
in /snap/bin/meshlab/current/bin when I try to run ./meshlabserver I get the folllowing error:

error while loading shared libraries: libcommon.so.1: cannot open shared object file: No such file or directory

Any advice?

Thanks,
Omar

**Comment by mardy** [comment]
Ah, my fault, I didn't even know there was a meshlabserver application. This needs to be added to the snap, I'll take care of it.
Meanwhile, could you try running it like this:
```
   cd /snap/bin/meshlab/current/bin
   LD_LIBRARY_PATH=/snap/meshlab/current/lib:/snap/meshlab/current/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH ./meshlabserver
```

**Comment by omhafez** [comment]
mardy,

When I do run what you suggested I get the following error:

./meshlabserver: symbol lookup error: /snap/meshlab/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_option_group_unref

Any suggestions?

P.S. I think you meant cd /snap/meshlab/current/bin above

**Comment by omhafez** [comment]
Hi mardy, any update on this? It appears you've merged a fix. Yet, I reinstalled meshlab from snap today and still get the same error above.

Thanks,
Omar

**Comment by cignoni** [comment]
Try again. 
Tonight (07/03/2016) I have uploaded a new snap with the patch provided by mardy. On my linux box , now meshlabserver, seems to works correctly ...

**Comment by omhafez** [comment]
meshlabserver works now on my system as well - thank you so much!
