### ISSUE TITLE
Bug importing Binary STL, Windows

### ISSUE THREAD

**Issue by Yan1703** [cnr-isti-vclab/meshlab#985]
**Describe your issue**
Binary STL (see attached ZIP) could not be loaded, MeshLab says Error details: Malformed file. Open the STL with e.g. File -> Import Mesh.
**Note**: The same file in Paint3D is opened without errors.
**Platform with the issue:** Windows Version	10.0.19041 Build 19041
**What type of issue is?:** Bug or unexpected behavior
**MeshLab version:** v2020.12 ( the most recent)

[4.3.zip](https://github.com/cnr-isti-vclab/meshlab/files/6501031/4.3.zip)

**Comment by alemuntoni** [comment]
Hi, this issue has been already solved and the fix will be available in the next version of meshlab (soon).
