### ISSUE TITLE
Mesh layer cannot be saved on a file. Project saving has been aborted

### ISSUE THREAD

**Issue by AymericFerreira** [cnr-isti-vclab/meshlab#997]
Since the new version (2021.05) I have a problem when saving a project with unsaved layer.
Prior to this version I was using "Save Project" to quickly save all layers and the project, now if the layer is not already saved I receive this error message

![mesh](https://user-images.githubusercontent.com/26620341/119861242-2a377d80-bee5-11eb-8147-5a63a23a4258.png)

Note that the layer is saved so I think this error is a bug and not related to writing permissions.

Also if I save all layers before I don't get this message anymore. 

Steps to reproduce : 
- Open a Mesh
- Duplicate 2 times
- Save Project
- After choosing name, the layer is saved and you get the error

**Comment by alemuntoni** [comment]
Definitely a bug, thanks for reporting @AymericFerreira.
I'll look into it.

**Comment by alemuntoni** [comment]
Fixed in the last commit. You can try it by downloading the last nightly (instructions [here](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-intall-the-last-nightly))

**Comment by AymericFerreira** [comment]
Hey, thank you for this quick fix, I installed the nightly but now by reproducing exactly the same step meshlab is crashing after saving the first mesh.
I'm using Windows 10 and nightly_8d6de6d via installer version

**Comment by alemuntoni** [comment]
Sorry, small mistake that for some reason did not came up when debugging the first time. Should be fine now (the new build will be ready soon and then you can try it)!

**Comment by AymericFerreira** [comment]
Yes working perfectly, thank you !
