### ISSUE TITLE
Failed start of Decorate mode Enable shadow mapping

### ISSUE THREAD

**Issue by GiovanniSer** [cnr-isti-vclab/meshlab#998]
In Win 10 I get "Failed start of Decorate mode Enable shadow mapping" after the command "Render->Enable shadow mapping" loading a STL.
This happens in the MeshLab version 2021.05.

In the previous version I got the failure twice, in
- Render->Enable shadow mapping
and in
- Render->Enable Screen Space Ambient Occlusion
- 
Now, the "Enable Screen Space Ambient Occlusion" is solved without renders's errors, but with a strange effects about the window. 
THe render is resized out of the screen. So it needs to reduce to the custom window and again to call the resize for restore the full win size in the screen.
Here the image of the strange effect where the bottom (with the information) is pushed out screen.
![Clipboard01](https://user-images.githubusercontent.com/67306481/119908425-d499ba00-bf52-11eb-8065-67dd4338ad51.jpg)

**Comment by alemuntoni** [comment]
Fixed in the last commit.
About the resize of the windows, are you using a small screen resolution? The meshlab window resizes when all the tools in the layer dialog do not fit...

**Comment by GiovanniSer** [comment]
I work always with the MeshLab win maximized. My resolution is 1366 x 768.
I never changed those parameters, but the out of screen (approximately equivalent at bottom text) began with the last  version 2020 (or first 2021)...
Thanks!
BR
G.

________________________________
Da: Alessandro Muntoni ***@***.***>
Inviato: lunedì 5 luglio 2021 16:04
A: cnr-isti-vclab/meshlab ***@***.***>
Cc: Giovanni S. ***@***.***>; Author ***@***.***>
Oggetto: Re: [cnr-isti-vclab/meshlab] Failed start of Decorate mode Enable shadow mapping (#998)


Fixed in the last commit.
About the resize of the windows, are you using a small screen resolution? The meshlab window resizes when all the tools in the layer dialog do not fit...

**Comment by GiovanniSer** [comment]
![FullScreenExample](https://user-images.githubusercontent.com/67306481/124498196-3d7b1a00-ddbc-11eb-81a7-10eba2623017.png)
